### ISSUE TITLE
Screen capture Firefox viewer not working

### ISSUE THREAD

**Issue by theDude30** [twilio/twilio-video.js#100]
- [X ] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [ X] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ X] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.

**Expected behavior:**

Chrome to Chrome works perfectly, when Chrome is sharing and firefox is viewing it should work the same way.

**Actual behavior:**

Firefox received 'trackAdded' event and video element is added, but no video is showing.
Below is the log from firefox:

WebRTC interfaces with the “moz” prefix (mozRTCPeerConnection, mozRTCSessionDescription, mozRTCIceCandidate) have been deprecated.  twilio-video.min.js:93:27233
Using more than two STUN/TURN servers slows down discovery twilio-video.min.js:93
RTCPeerConnection.getLocalStreams/getRemoteStreams are deprecated. Use RTCPeerConnection.getSenders/getReceivers instead.  twilio-video.min.js:93:29467
Using more than two STUN/TURN servers slows down discovery twilio-video.min.js:93
trackAddedEvent...  
Callback-based pc.getStats is deprecated, and will be removed in the near future! Use promise-version! See http://w3c.github.io/webrtc-pc/#getstats-example for usage.  twilio-video.min.js:92
non-maplike pc.getStats access is deprecated, and will be removed in the near future! See http://w3c.github.io/webrtc-pc/#getstats-example for usage.  twilio-video.min.js:93
ICE failed, see about:webrtc for more details

**about:webrtc Log:**

ICE restarts:
ICE rollbacks:
SDP
Local SDP

v=0

o=mozilla...THIS_IS_SDPARTA-53.0 2035306082463347027 0 IN IP4 0.0.0.0

s=-

t=0 0

a=sendrecv

a=fingerprint:sha-256 3F:7F:1C:54:C3:4F:A4:2F:C8:0A:3F:B4:64:15:61:35:DD:6E:EF:6B:A5:66:01:2A:5D:A5:C7:FB:80:D7:4A:AE

a=group:BUNDLE video1

a=ice-options:trickle

a=msid-semantic:WMS *

m=audio 0 UDP/TLS/RTP/SAVPF 0

c=IN IP4 0.0.0.0

a=inactive

a=rtpmap:0 PCMU/8000

m=video 35634 UDP/TLS/RTP/SAVPF 96

c=IN IP4 54.171.127.245

a=candidate:0 1 UDP 2122252543 192.168.1.31 58106 typ host

a=candidate:1 1 UDP 1686052863 77.138.90.97 58106 typ srflx raddr 192.168.1.31 rport 58106

a=candidate:3 1 UDP 92217087 54.171.127.245 35634 typ relay raddr 54.171.127.245 rport 35634

a=candidate:5 1 UDP 8331263 54.171.127.245 53066 typ relay raddr 54.171.127.245 rport 53066

a=candidate:4 1 UDP 8331263 54.171.127.245 58687 typ relay raddr 54.171.127.245 rport 58687

a=recvonly

a=fmtp:96 max-fs=12288;max-fr=60

a=ice-pwd:a8331d84cdfbe4af062ce4d82624a2ed

a=ice-ufrag:277eebd6

a=mid:video1

a=rtcp-fb:96 nack

a=rtcp-fb:96 nack pli

a=rtcp-fb:96 ccm fir

a=rtcp-fb:96 goog-remb

a=rtcp-mux

a=rtpmap:96 VP8/90000

a=setup:active

a=ssrc:454734559 cname:{e3ebe492-3f18-8144-9a9e-e34d6df84996}

Remote SDP

v=0

o=- 6081395776938531981 2 IN IP4 127.0.0.1

s=-

t=0 0

a=sendrecv

a=group:BUNDLE audio0 video1

a=msid-semantic:WMS *

m=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 110 112 113 126

c=IN IP4 0.0.0.0

a=candidate:3061656002 1 udp 2122255103 2001::9d38:90d7:14cd:388d:b275:a59e 60328 typ host generation 0 ufrag oOwt network-id 2 network-cost 50

a=candidate:202810205 1 udp 2122194687 192.168.1.21 60329 typ host generation 0 ufrag oOwt network-id 1

a=candidate:4194753161 1 udp 1685987071 77.138.90.97 60329 typ srflx raddr 192.168.1.21 rport 60329 generation 0 ufrag oOwt network-id 1

a=candidate:4177450290 1 tcp 1518275327 2001::9d38:90d7:14cd:388d:b275:a59e 9 typ host tcptype active generation 0 ufrag oOwt network-id 2 network-cost 50

a=candidate:1117085613 1 tcp 1518214911 192.168.1.21 9 typ host tcptype active generation 0 ufrag oOwt network-id 1

a=candidate:2228152881 1 udp 41820415 54.171.127.245 11847 typ relay raddr 77.138.90.97 rport 60329 generation 0 ufrag oOwt network-id 1

a=candidate:3394049729 1 udp 25042943 54.171.127.245 37621 typ relay raddr 77.138.90.97 rport 50495 generation 0 ufrag oOwt network-id 1

a=candidate:3394049729 1 udp 25042687 54.171.127.245 39591 typ relay raddr 77.138.90.97 rport 50496 generation 0 ufrag oOwt network-id 1

a=recvonly

a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level

a=fingerprint:sha-256 90:BB:79:63:20:D1:25:D8:BA:47:46:C8:0F:7E:D8:22:9D:E6:71:CA:D8:05:28:33:80:5A:11:AB:A7:B1:3F:9D

a=fmtp:111 maxplaybackrate=0;stereo=0;useinbandfec=1

a=ice-pwd:kcXOqTChuXVw7FoZ0SbKrmuC

a=ice-ufrag:oOwt

a=mid:audio0

a=rtcp:9 IN IP4 0.0.0.0

a=rtcp-mux

a=rtpmap:111 opus/48000/2

a=rtpmap:103 isac/16000/1

a=rtpmap:104 isac/32000/1

a=rtpmap:9 G722/8000/1

a=rtpmap:0 PCMU/8000

a=rtpmap:8 PCMA/8000

a=rtpmap:106 cn/32000/1

a=rtpmap:105 cn/16000/1

a=rtpmap:13 cn/8000/1

a=rtpmap:110 telephone-event/48000

a=rtpmap:112 telephone-event/32000

a=rtpmap:113 telephone-event/16000

a=rtpmap:126 telephone-event/8000

a=setup:actpass

m=video 9 UDP/TLS/RTP/SAVPF 96 98 100 102 127 97 99 101 125

c=IN IP4 0.0.0.0

a=sendrecv

a=extmap:2 urn:ietf:params:rtp-hdrext:toffset

a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time

a=extmap:4 urn:3gpp:video-orientation

a=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01

a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay

a=fingerprint:sha-256 90:BB:79:63:20:D1:25:D8:BA:47:46:C8:0F:7E:D8:22:9D:E6:71:CA:D8:05:28:33:80:5A:11:AB:A7:B1:3F:9D

a=fmtp:100 profile-level-id=42e01f;level-asymmetry-allowed=1;packetization-mode=1

a=ice-pwd:kcXOqTChuXVw7FoZ0SbKrmuC

a=ice-ufrag:oOwt

a=mid:video1

a=msid:af0c01e8-b86f-497e-8125-1f1f9b6c9a83 cc006ddc-9d04-43c6-92c2-5cb11f989049

a=rtcp:9 IN IP4 0.0.0.0

a=rtcp-fb:96 ccm fir

a=rtcp-fb:96 nack

a=rtcp-fb:96 nack pli

a=rtcp-fb:96 goog-remb

a=rtcp-fb:98 ccm fir

a=rtcp-fb:98 nack

a=rtcp-fb:98 nack pli

a=rtcp-fb:98 goog-remb

a=rtcp-fb:100 ccm fir

a=rtcp-fb:100 nack

a=rtcp-fb:100 nack pli

a=rtcp-fb:100 goog-remb

a=rtcp-mux

a=rtpmap:96 VP8/90000

a=rtpmap:98 VP9/90000

a=rtpmap:100 H264/90000

a=rtpmap:102 red/90000

a=rtpmap:127 ulpfec/90000

a=rtpmap:97 rtx/90000

a=rtpmap:99 rtx/90000

a=rtpmap:101 rtx/90000

a=rtpmap:125 rtx/90000

a=setup:actpass

a=ssrc:3694785782 cname:w+w0q2OLRBjhyLMI

a=ssrc:3694785782 mslabel:af0c01e8-b86f-497e-8125-1f1f9b6c9a83

a=ssrc:3694785782 label:cc006ddc-9d04-43c6-92c2-5cb11f989049

a=ssrc:432535811 cname:w+w0q2OLRBjhyLMI

a=ssrc:432535811 mslabel:af0c01e8-b86f-497e-8125-1f1f9b6c9a83

a=ssrc:432535811 label:cc006ddc-9d04-43c6-92c2-5cb11f989049

RTP Stats
inbound_rtp_video_1

**Software versions:**

 - [X ] Browser(s): Chrome 58.0.3029.96 (64-bit) , FireFox 53.0 (64-bit)
 - [X ] Operating System: OSX 10.12.4
 - [ X] twilio-video.js: 1.0.0
 - [ ] Third-party libraries (e.g., Angular, React, etc.): None

**Comment by markandrus** [comment]
Thanks for the ticket, @theDude30. Your logs reminded me we have some deprecation warnings to address in Firefox (we're tracking these publicly now on #101, #102, #103, #104, and #105).

From your local SDP, I can see that you are connecting with neither audio nor video from Firefox. From your remote SDP, I can see that Chrome is sending a single video MediaStreamTrack with ID `cc006ddc-9d04-43c6-92c2-5cb11f989049`. Unfortunately, you have hit the same root issue described as "[VideoTrack shared by Firefox appears black](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md#videotrack-shared-by-firefox-appears-black)" in [COMMON_ISSUES.md](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md). The tell-tale sign is the change in BUNDLE groups between the two SDPs:

```
a=group:BUNDLE video1
```

versus

```
a=group:BUNDLE audio0 video1
```

I should update the issue name and description in COMMON_ISSUES.md, since the issue can occur if Firefox should receive a VideoTrack, too.

Can you please try the suggested workaround, namely

> always share audio from Firefox-based Participants when connecting to a peer-to-peer Room. If you do not intend to playback the audio, you can `disable` the Track before connecting.

and let me know if that fixes the issue?

Thanks,
Mark

**Comment by theDude30** [comment]
Thanks, the workaround work(even that it doesn't make much sense to ask the viewer to allow microphone just to view screen ).
any ETA on when is this going to be resolved?

**Comment by markandrus** [comment]
We've identified a workaround that would not require sharing audio, although it involves some pretty involved SDP rewriting to fix the BUNDLE group. Before we attempt it, we'd like to get a better idea of the when the browsers will fix it. From what I understand, Chrome needs to improve its bundle behavior, although Firefox could perhaps be more lenient. We do not have an ETA at this time.
