### ISSUE TITLE
Certain user's video is not shown for other people, but LocalTrack is shown

### ISSUE THREAD

**Issue by whkim94** [twilio/twilio-video.js#1003]
Hi, I am building a web application for peer to peer video communication.

It works great with most of environments, but there is one user(Window 10, Chrome)
cannot connect her video, but audio, to the room. She can see her face with LocalTrack,
but her video is not shown for the other person.
She can see other person's video and hear their audio as well.

The weird thing is that she can do video chat using different apps like MS Teams and others.

It's just the Twilio Video that she can't really shoot(?) her video stream for other people.

The Room Sids are: RM21383eebf6a0257b255f1bb67854e043,
RM080e154eed8a80148ab99a6b2b821aa5,
RM3adf4258d72899b8c62438147ec29ca0.

One of the trial is with THE (window 10, chrome) <==> mac,
and the other is with window <==> window.

Thank you

------------------------------

**Software versions:**

 - [x] Browser(s): Chrome
 - [x] Operating System: Window 10
 - [x] twilio-video.js: 2.0.0
 - [x] Third-party libraries (e.g., Angular, React, etc.): Jquery

**Comment by manjeshbhargav** [comment]
Hi @whkim94 ,

Thanks for writing in. I'm curious, can you share with me the ConnectOptions you are passing to `connect()` as well as how you are creating the local video preview?

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by whkim94** [comment]
@manjeshbhargav Thanks for the reply.

Here is the javascript code that I use for connecting.

```
Video.connect(token, {
            name: room,
            audio: true,
            maxAudioBitrate: 16000,
            video: { height: 720, frameRate: 24, width: 1280 }
        }).then(function(room) {
            console.log('Connected to Room: "%s"', room.name);

            
            room.participants.forEach(function(participant) {
                participant.on('trackSubscribed', track => {
                    console.log('Participant "%s" already in the Room', participant.identity);
                    $('.disconnect-icon').attr('hidden','');
                    document.getElementById('remote-media-div').appendChild(track.attach());
                });
            });
         
      ......
```

I am following this [https://www.twilio.com/docs/video/tutorials/developing-high-quality-video-applications#p2p-or-group-rooms](url) (peer-to-peer) for enhancing the quality, which the quality isn't that great sometimes.. 

The quality is one of the issues since peer to peer option does not have region selection, but I would like to move on from the main issue first.

**Comment by manjeshbhargav** [comment]
Hi @whkim94 ,

Please take a look at this [guide](https://www.twilio.com/docs/video/build-js-video-application-recommendations-and-best-practices#acquiring-camera-in-mobile-browsers). It will help you get past this issue. Basically, by calling `Video.createLocalVideoTrack()`, you are creating a second LocalVideoTrack, which will fail if the camera is already being used by the first LocalVideoTrack, which is created by the SDK when you pass`video: { width: ..., height:... }` in ConnectOptions. The guide tells you how to work around it.

Thanks,

Manjesh Malavalli
JSDK Team
