### ISSUE TITLE
Video.connect doesn't work with video: false

### ISSUE THREAD

**Issue by anirudhsama** [twilio/twilio-video.js#1004]
Im trying to build an audio-only application. As mentioned in the documentation, in the connection options, I'm passing video as false. The below is the code to connect to the room.

```js
import Video, { ConnectOptions, Room, } from 'twilio-video';

const connectionOptions: ConnectOptions = {
  video: false,
  logLevel: 'debug',
};

const connect = async (_token: string) => {
  const _room: Room = await Video.connect(_token, connectionOptions);
  console.log('local audio tracks', _room.localParticipant.audioTracks);
};

```

**Expected behavior:**

1. Browser should ask for permission for using microphone *only*.
2. Connect to the room with audio only. The `room.localParticipant.audioTracks` should return a map of SIDs and tracks.

**Actual behavior:**
1. Browser doesn't ask for any permission.
2. `room.localParticipant.audioTracks` is an empty map.

**Software versions:**

 - [x] Browser(s): Firefox 75, Chrome 81.0.4044.129
 - [x] Operating System: macOS Mojave
 - [x] twilio-video.js: 2.3.0
 - [x] Third-party libraries: Typescript, Nextjs

**Debug logs:**
[console-export-2020-5-7_13-14-56.txt](https://github.com/twilio/twilio-video.js/files/4591496/console-export-2020-5-7_13-14-56.txt)

**Comment by makarandp0** [comment]
Hello @anirudhsama,  Thank you for writing about this issue. I see following line in your log:
```
2020-05-07 07:43:22.063Z | INFO in [createLocalTracks #1]: Neither audio nor video requested, so returning empty LocalTracks log.js:138
```
Can you try adding `audio: true` in the connectOptions?

Thanks,
Makarand

**Comment by anirudhsama** [comment]
Hi,

Yes, explicitly setting `audio: true` worked! I still see some error logs, but the connection is fine. Thanks for the quick response!

[console_logs.txt](https://github.com/twilio/twilio-video.js/files/4593302/console_logs.txt)
!

**Comment by anirudhsama** [comment]
Debug logs for the same.

[console-export-2020-5-7_19-28-23.txt](https://github.com/twilio/twilio-video.js/files/4593361/console-export-2020-5-7_19-28-23.txt)


> Hi,
> 
> Yes, explicitly setting `audio: true` worked! I still see some error logs, but the connection is fine. Thanks for the quick response!
> 
> [console_logs.txt](https://github.com/twilio/twilio-video.js/files/4593302/console_logs.txt)
> !

**Comment by manjeshbhargav** [comment]
Hi @anirudhsama ,

Since the issue you reported has been resolved, I will close this issue. Regarding the error you are seeing, it is due to the fact that the AccessToken you are passing to `connect()` is invalid. Please follow [this guide](https://www.twilio.com/docs/video/tutorials/user-identity-access-tokens) to make sure you are passing the right AccessToken. Also, here is an [example](https://github.com/twilio/video-quickstart-js/blob/master/server/index.js) for how you can create a server that hands out AccessTokens.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by anirudhsama** [comment]
Hi

The access token is valid and works. Users are able to hear others in the room. If video:true is passed to connection options, same token doesn’t report any error.
