### ISSUE TITLE
TwilioError: Signaling connection error in Angular 8 app with Laravel backend

### ISSUE THREAD

**Issue by jbryanx** [twilio/twilio-video.js#1006]
**Code to reproduce the issue:**
// get the token and create room from Laravel Backend API
private async getAuthToken(roomName: string, type: string) {
      const request = {
        roomName: roomName,
        type: type,
      };
      const auth =
          await this.http
                    .post<AuthToken>(this.SERVICE_URL + 'videocall/join/', request)
                    .toPromise();
      return auth.accessToken;
}
async joinRoom(name: string, tracks: LocalTrack[], type: string) {
      let room: Room = null;
        try {
            const token = await this.getAuthToken(name, type);
            room =
                await connect(
                    token, {
                        name: name,
                        // tracks: tracks,
                        logLevel: 'debug',
                        // video: { width: 300 },
                        // abortOnIceServersTimeout: false,
                    } as ConnectOptions);
        } catch (error) {
            console.error(`Unable to connect to Room: ${error.message}`);
        } finally {
            if (room) {
              this.roomBroadcast.next(true);
            }
        }
        return room;
    }

**Expected behavior:**
Twilio connection would be successfull.

**Actual behavior:**
INFO in [connect #1]: Error while connecting to a Room: TwilioError: Signaling connection error
    at SignalingConnectionError.TwilioError (https://localhost:4200/vendor.js:266339:23)
videocall.service.ts:101 Unable to connect to Room: Signaling connection error

Aceptado. sid: RMaac9f67acb918ae4dfaba230dc60f158
log.js:138 2020-05-08 04:57:15.040Z | INFO in [connect #1]: Connecting to a Room
log.js:138 2020-05-08 04:57:15.041Z | DEBUG in [connect #1]: Options: {wsServer: "wss://global.vss.twilio.com/signaling", abortOnIceServersTimeout: false, automaticSubscription: true, dominantSpeaker: false, createLocalTracks: ƒ, …}
log.js:138 2020-05-08 04:57:15.042Z | INFO in [NTSIceServerSource #1]: Created a new NTSIceServerSource
log.js:138 2020-05-08 04:57:15.042Z | DEBUG in [NTSIceServerSource #1]: ECS server: https://ecs.us1.twilio.com
log.js:138 2020-05-08 04:57:15.043Z | INFO in [connect #1]: LocalTracks were not provided, so they will be acquired automatically before connecting to the Room. LocalTracks will be released if connecting to the Room fails or if the Room is disconnected
log.js:138 2020-05-08 04:57:15.102Z | INFO in [createLocalTracks #2]: Call to getUserMedia successful; got MediaStreamTracks: (2) [MediaStreamTrack, MediaStreamTrack]
log.js:138 2020-05-08 04:57:15.103Z | DEBUG in [LocalAudioTrack #3: undefined]: Initializing
log.js:138 2020-05-08 04:57:15.104Z | DEBUG in [LocalVideoTrack #4: undefined]: Initializing
log.js:138 2020-05-08 04:57:15.106Z | DEBUG in [connect #1]: Creating a new LocalParticipant: LocalParticipantV2 {_events: {…}, _eventsCount: 1, _maxListeners: undefined, …}
log.js:138 2020-05-08 04:57:15.109Z | INFO in [LocalParticipant #1]: Created a new Participant
log.js:138 2020-05-08 04:57:15.111Z | INFO in [LocalParticipant #1]: Added a new LocalAudioTrack: a264062c-c9eb-4e72-9ab3-94c9ce21c1c8
log.js:138 2020-05-08 04:57:15.111Z | DEBUG in [LocalParticipant #1]: LocalAudioTrack: LocalAudioTrack {kind: "audio", name: "a264062c-c9eb-4e72-9ab3-94c9ce21c1c8", mediaStreamTrack: MediaStreamTrack, id: "a264062c-c9eb-4e72-9ab3-94c9ce21c1c8", …}
log.js:138 2020-05-08 04:57:15.112Z | INFO in [LocalParticipant #1]: Added a new LocalVideoTrack: b78efbf2-7d26-4cfd-aabb-b46871685b9a
log.js:138 2020-05-08 04:57:15.113Z | DEBUG in [LocalParticipant #1]: LocalVideoTrack: LocalVideoTrack {kind: "video", name: "b78efbf2-7d26-4cfd-aabb-b46871685b9a", mediaStreamTrack: MediaStreamTrack, dimensions: {…}, …}
log.js:138 2020-05-08 04:57:15.114Z | INFO in [connect #1]: Getting ICE servers
log.js:138 2020-05-08 04:57:15.114Z | DEBUG in [connect #1]: Options: {wsServer: "wss://global.vss.twilio.com/signaling", abortOnIceServersTimeout: false, automaticSubscription: true, dominantSpeaker: false, createLocalTracks: ƒ, …}
log.js:138 2020-05-08 04:57:15.115Z | INFO in [NTSIceServerSource #1]: Starting
log.js:138 2020-05-08 04:57:15.115Z | DEBUG in [NTSIceServerSource #1]: Getting ECS configuration
log.js:138 2020-05-08 04:57:15.125Z | DEBUG in [LocalAudioTrack #3: a264062c-c9eb-4e72-9ab3-94c9ce21c1c8]: Started
log.js:138 2020-05-08 04:57:15.146Z | DEBUG in [LocalVideoTrack #4: b78efbf2-7d26-4cfd-aabb-b46871685b9a]: Dimensions: {width: 640, height: 480}
log.js:138 2020-05-08 04:57:15.147Z | DEBUG in [LocalVideoTrack #4: b78efbf2-7d26-4cfd-aabb-b46871685b9a]: Started
log.js:138 2020-05-08 04:57:15.802Z | INFO in [NTSIceServerSource #1]: Got ICE servers: [{"urls":"turn:global.turn.twilio.com:3478?transport=udp","username":"2a2fab092f31208653ea018d282810c328277c8eca9c50841d66fe2c8151e7fd","credential":"wekKchLuyMGQ9gmgHiUfAGFX/OzovR++MMCjnUpQAis="},{"urls":"turns:global.turn.twilio.com:443?transport=tcp","username":"2a2fab092f31208653ea018d282810c328277c8eca9c50841d66fe2c8151e7fd","credential":"wekKchLuyMGQ9gmgHiUfAGFX/OzovR++MMCjnUpQAis="}]
log.js:138 2020-05-08 04:57:15.803Z | INFO in [NTSIceServerSource #1]: Getting ICE servers again in 14400 seconds
log.js:138 2020-05-08 04:57:15.803Z | INFO in [connect #1]: Got ICE servers
log.js:138 2020-05-08 04:57:15.804Z | DEBUG in [connect #1]: ICE servers: (2) [{…}, {…}]
log.js:138 2020-05-08 04:57:15.804Z | DEBUG in [connect #1]: Creating a new RoomSignaling
log.js:138 2020-05-08 04:57:15.804Z | DEBUG in [connect #1]: RoomSignaling params: {token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImN0eSI6InR3aW…n19fQ.OgmGchSU1EyAoF9fz6K3oV8kF5Dda-IvdeAAkwLpBao"}
log.js:138 2020-05-08 04:57:15.836Z | DEBUG in [TwilioConnection #1: wss://global.vss.twilio.com/signaling]: Created a new WebSocket: WebSocket {__zone_symbol__errorfalse: Array(4), __zone_symbol__openfalse: Array(4), url: "wss://global.vss.twilio.com/signaling", readyState: 0, bufferedAmount: 0, …}
log.js:138 2020-05-08 04:57:16.616Z | DEBUG in [TwilioConnection #1: wss://global.vss.twilio.com/signaling]: WebSocket opened: WebSocket {__zone_symbol__errorfalse: Array(5), __zone_symbol__openfalse: Array(6), __zone_symbol__closefalse: Array(1), __zone_symbol__messagefalse: Array(1), url: "wss://global.vss.twilio.com/signaling", …}
log.js:138 2020-05-08 04:57:21.618Z | WARN in [TwilioConnection #1: wss://global.vss.twilio.com/signaling]: Closing: 3000 - "welcome" message timeout expired
log @ log.js:138
warn @ log.js:199
_handleWelcomeTimeout @ twilioconnection.js:396
(anonymous) @ twilioconnection.js:266
(anonymous) @ timeout.js:75
invokeTask @ zone-evergreen.js:391
onInvokeTask @ core.js:30873
invokeTask @ zone-evergreen.js:390
runTask @ zone-evergreen.js:168
invokeTask @ zone-evergreen.js:465
ZoneTask.invoke @ zone-evergreen.js:454
timer @ zone-evergreen.js:2650
setTimeout (async)
scheduleTask @ zone-evergreen.js:2671
scheduleTask @ zone-evergreen.js:378
onScheduleTask @ zone-evergreen.js:272
scheduleTask @ zone-evergreen.js:372
scheduleTask @ zone-evergreen.js:211
scheduleMacroTask @ zone-evergreen.js:234
scheduleMacroTaskWithCurrentZone @ zone-evergreen.js:1107
(anonymous) @ zone-evergreen.js:2686
proto.<computed> @ zone-evergreen.js:1428
start @ timeout.js:72
Timeout @ timeout.js:38
(anonymous) @ twilioconnection.js:265
invokeTask @ zone-evergreen.js:391
onInvokeTask @ core.js:30873
invokeTask @ zone-evergreen.js:390
runTask @ zone-evergreen.js:168
invokeTask @ zone-evergreen.js:465
invokeTask @ zone-evergreen.js:1603
globalZoneAwareCallback @ zone-evergreen.js:1640
log.js:138 2020-05-08 04:57:21.618Z | WARN in [TwilioConnection #1: wss://global.vss.twilio.com/signaling]: Closed: 3000 - "welcome" message timeout expired
log @ log.js:138
warn @ log.js:199
_close @ twilioconnection.js:196
_handleWelcomeTimeout @ twilioconnection.js:397
(anonymous) @ twilioconnection.js:266
(anonymous) @ timeout.js:75
invokeTask @ zone-evergreen.js:391
onInvokeTask @ core.js:30873
invokeTask @ zone-evergreen.js:390
runTask @ zone-evergreen.js:168
invokeTask @ zone-evergreen.js:465
ZoneTask.invoke @ zone-evergreen.js:454
timer @ zone-evergreen.js:2650
setTimeout (async)
scheduleTask @ zone-evergreen.js:2671
scheduleTask @ zone-evergreen.js:378
onScheduleTask @ zone-evergreen.js:272
scheduleTask @ zone-evergreen.js:372
scheduleTask @ zone-evergreen.js:211
scheduleMacroTask @ zone-evergreen.js:234
scheduleMacroTaskWithCurrentZone @ zone-evergreen.js:1107
(anonymous) @ zone-evergreen.js:2686
proto.<computed> @ zone-evergreen.js:1428
start @ timeout.js:72
Timeout @ timeout.js:38
(anonymous) @ twilioconnection.js:265
invokeTask @ zone-evergreen.js:391
onInvokeTask @ core.js:30873
invokeTask @ zone-evergreen.js:390
runTask @ zone-evergreen.js:168
invokeTask @ zone-evergreen.js:465
invokeTask @ zone-evergreen.js:1603
globalZoneAwareCallback @ zone-evergreen.js:1640
log.js:138 2020-05-08 04:57:21.620Z | INFO in [NTSIceServerSource #1]: Stopping
log.js:138 2020-05-08 04:57:21.621Z | DEBUG in [NTSIceServerSource #1]: Stopped
log.js:138 2020-05-08 04:57:21.622Z | INFO in [connect #1]: The automatically acquired LocalTracks will now be stopped
log.js:138 2020-05-08 04:57:21.623Z | INFO in [LocalAudioTrack #3: a264062c-c9eb-4e72-9ab3-94c9ce21c1c8]: Stopping
log.js:138 2020-05-08 04:57:21.623Z | DEBUG in [LocalAudioTrack #3: a264062c-c9eb-4e72-9ab3-94c9ce21c1c8]: Ended
log.js:138 2020-05-08 04:57:21.624Z | INFO in [LocalVideoTrack #4: b78efbf2-7d26-4cfd-aabb-b46871685b9a]: Stopping
log.js:138 2020-05-08 04:57:21.624Z | DEBUG in [LocalVideoTrack #4: b78efbf2-7d26-4cfd-aabb-b46871685b9a]: Ended
log.js:138 2020-05-08 04:57:21.625Z | INFO in [connect #1]: Error while connecting to a Room: TwilioError: Signaling connection error
    at SignalingConnectionError.TwilioError (https://localhost:4200/vendor.js:266339:23)
    at new SignalingConnectionError (https://localhost:4200/vendor.js:265272:133)
    at TwilioConnection.disconnect (https://localhost:4200/vendor.js:257478:28)
    at Object.onceWrapper (https://localhost:4200/vendor.js:199439:5)
    at TwilioConnection.emit (https://localhost:4200/vendor.js:199347:5)
    at Object.closed (https://localhost:4200/vendor.js:260771:24)
    at TwilioConnection.<anonymous> (https://localhost:4200/vendor.js:260776:15)
    at TwilioConnection.emit (https://localhost:4200/vendor.js:199352:7)
    at TwilioConnection.transition (https://localhost:4200/vendor.js:257971:17)
    at TwilioConnection._close (https://localhost:4200/vendor.js:260831:12)
videocall.service.ts:101 Unable to connect to Room: Signaling connection error
(anonymous) @ videocall.service.ts:100
rejected @ tslib.es6.js:63
invoke @ zone-evergreen.js:359
onInvoke @ core.js:30892
invoke @ zone-evergreen.js:358
run @ zone-evergreen.js:124
(anonymous) @ zone-evergreen.js:855
invokeTask @ zone-evergreen.js:391
onInvokeTask @ core.js:30873
invokeTask @ zone-evergreen.js:390
runTask @ zone-evergreen.js:168
drainMicroTaskQueue @ zone-evergreen.js:559
invokeTask @ zone-evergreen.js:469
ZoneTask.invoke @ zone-evergreen.js:454
timer @ zone-evergreen.js:2650
setTimeout (async)
scheduleTask @ zone-evergreen.js:2671
scheduleTask @ zone-evergreen.js:378
onScheduleTask @ zone-evergreen.js:272
scheduleTask @ zone-evergreen.js:372
scheduleTask @ zone-evergreen.js:211
scheduleMacroTask @ zone-evergreen.js:234
scheduleMacroTaskWithCurrentZone @ zone-evergreen.js:1107
(anonymous) @ zone-evergreen.js:2686
proto.<computed> @ zone-evergreen.js:1428
start @ timeout.js:72
Timeout @ timeout.js:38
(anonymous) @ twilioconnection.js:265
invokeTask @ zone-evergreen.js:391
onInvokeTask @ core.js:30873
invokeTask @ zone-evergreen.js:390
runTask @ zone-evergreen.js:168
invokeTask @ zone-evergreen.js:465
invokeTask @ zone-evergreen.js:1603
globalZoneAwareCallback @ zone-evergreen.js:1640

**Software versions:**

 - [x] Browser(s): Chrome Version 81.0.4044.138 (Official Build) (64-bit)
 - [x] Operating System: Windows 10 Pro 64 bits
 - [x] twilio-video.js: 2.4.0
 - [x] Third-party libraries (e.g., Angular, React, etc.): Angular 8.0.0

**Comment by manjeshbhargav** [comment]
Hi @jbryanx ,

Thanks for writing in with your issue. It looks like there was a timeout in trying to connect to Twilio's back-end. Can you share the contents of your browsers Network tab, especially the messages sent over a WebSocket called `signaling`?

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by Kinnari7** [comment]
Hello @manjeshbhargav 

I am facing  error belvo while connect to video call using angular localhost.

2020-09-27 16:19:14.263Z | INFO in [connect #1]: Error while connecting to a Room: TwilioError: Signaling connection error
    at SignalingConnectionError.TwilioError (http://localhost:4200/chats-chats-module.js:37897:23)
    at new SignalingConnectionError (http://localhost:4200/chats-chats-module.js:36807:133)
    at disconnect (http://localhost:4200/chats-chats-module.js:28367:112)
    at TwilioConnection.<anonymous> (http://localhost:4200/chats-chats-module.js:28348:9)
    at Object.onceWrapper (http://localhost:4200/vendor.js:167169:5)
    at TwilioConnection.emit (http://localhost:4200/vendor.js:167077:5)
    at TwilioConnection.<anonymous> (http://localhost:4200/chats-chats-module.js:31742:20)
    at TwilioConnection.emit (http://localhost:4200/vendor.js:167082:7)
    at TwilioConnection.transition (http://localhost:4200/chats-chats-module.js:28866:17)
    at TwilioConnection._close (http://localhost:4200/chats-chats-module.js:31807:16)

Please help me to solve this issue.
