### ISSUE TITLE
trackUnpublished event for LocalParticipant

### ISSUE THREAD

**Issue by ksocha** [twilio/twilio-video.js#1007]
Hi!

I would like to receive an information when local participant has unpublished a track. Currently, `trackUnpublished` event is fired for remote participants only. Is this something that could be added in the future? If not, how I can tell if local participant has unpublished a track? 

Thanks!

 - [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ ] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Comment by ksocha** [comment]
I can see now that #657 addresses that. Any chance it would be merged anytime soon?

**Comment by manjeshbhargav** [comment]
Hi @ksocha ,

We have an internal ticket to work on providing a "trackUnpublished" event on the LocalParticipant. We need to figure out when to signal that event. From an SDK user's perspective, you can consider the Track as unpublished as soon as `LocalParticipant.unpublishTrack()` is called. Right now, we don't have a concrete ETA on this, but I'll keep you posted.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by manjeshbhargav** [comment]
We have de-prioritized this feature.
