### ISSUE TITLE
Using more than two STUN/TURN servers slows down discovery

### ISSUE THREAD

**Issue by markandrus** [twilio/twilio-video.js#101]
Twilio's servers provide 4 ICE servers to the Video SDKs today, e.g.

```json
[
   {
      "urls": "stun:global.stun.twilio.com:3478?transport=udp"
   },
   {
      "username": "ab5ef1008b2399b5f778f4ffa3291ddee17c55851ce9dafc34343468a3f280bf",
      "credential": "yiZFvp7KWjp4hBnUQVTari2bHEv3iK3KVDpD410PLIo=",
      "urls": "turn:global.turn.twilio.com:3478?transport=udp"
   },
   {
      "credential": "yiZFvp7KWjp4hBnUQVTari2bHEv3iK3KVDpD410PLIo=",
      "username": "ab5ef1008b2399b5f778f4ffa3291ddee17c55851ce9dafc34343468a3f280bf",
      "urls": "turn:global.turn.twilio.com:3478?transport=tcp"
   },
   {
      "credential": "yiZFvp7KWjp4hBnUQVTari2bHEv3iK3KVDpD410PLIo=",
      "username": "ab5ef1008b2399b5f778f4ffa3291ddee17c55851ce9dafc34343468a3f280bf",
      "urls": "turn:global.turn.twilio.com:443?transport=tcp"
   }
]
```

As of Firefox 53, this raises a warning in the console:

> Using more than two STUN/TURN servers slows down discovery

We will update our server to send fewer ICE servers to the Video SDKs. This work does not require any client-side changes, but we are tracking here until the change is made.

**Comment by markandrus** [comment]
ECS was deployed, fixing this.

**Comment by pnoeric** [comment]
Hi @markandrus  - hmmm I am a new Twilio customer and today I implemented getting STUN/TURN servers, following the docs exactly. I got back 4 servers. But it should only give us 2, no?

**Comment by pnoeric** [comment]
Hi Seth @innerverse - aha, got it, thank you. Yeah, I'm getting the STUN/TURN servers directly. How do you suggest I can best filter them for my app? Right now I just get 4 URLs.... should I just drop anything past the first 2?
