### ISSUE TITLE
dyld: Library not loaded: @rpath/TwilioVideo.framework/TwilioVideo

### ISSUE THREAD

**Issue by BayCem** [twilio/twilio-video.js#1011]
Hi,

I am trying to use TwilioVideo in the project. I added TwilioVideo with a pod and when I am trying to install to real device(just real device), app crashes with the given error:

`dyld: Library not loaded: @rpath/TwilioVideo.framework/TwilioVideo`

What I tried so far:
1. Tried with Paid Developer Account.
2. Tried to change build system to `Legacy`.
3. Tried to delete `#use_frameworks!` and/or `#use_modular_headers!` from pod file.
4. Tried to test different real devices(with different iOS versions).

Every time error does not fixed.

Then I created different project with using different dependencies. In that dependencies I got the same error but I tried above methods and the methods fixed the issue.

When I delete TwilioVideo, problem gone but I need to use TwilioVideo.

**Comment by manjeshbhargav** [comment]
Hi @BayCem ,

For issues related to the iOS SDK, please file them [here](https://github.com/twilio/video-quickstart-ios/issues). This is the repository for the JavaScript SDK.

Thanks,

Manjesh Malavalli
JSDK Team
