### ISSUE TITLE
Support for specifying room type for Ad-Hoc rooms

### ISSUE THREAD

**Issue by harshit-j** [twilio/twilio-video.js#1014]
I checked the documentation and found that there is no way to specify the room type from client side on JavaScript, Android and iOS client SDKs.
Is it possible to add this feature so that we may not need to create an API specifically for creating rooms.

**Comment by manjeshbhargav** [comment]
@harshit-j ,

Thanks for writing in with your question. Ideally, your application server should be the one creating the Room, in which case the REST API has the option to specify a peer-to-peer or group Room. We don't have any plans to add this to the SDK.

Thanks,

Manjesh Malavalli
JSDK Team
