### ISSUE TITLE
Disconnected the room after reconnected

### ISSUE THREAD

**Issue by DeepakR63** [twilio/twilio-video.js#1017]
Hi,

**steps to reproduce**
I am tried to make a video call with the web and iOS device platforms.

1. Both users have joined the room.
2.  In the web, turn off the wifi -- I got the **reconnecting ** log
3. Then turn-on the wifi -- got the **reconnected** log
4. Then both users can join the room well.
5. Within seconds, the web **disconnected** from the room due to the **Signal connection disconnected** error.

Browser: Chrome- v75
"twilio-video": "^2.4.0"

**Please give a solution to rectify this issue**

**Comment by makarandp0** [comment]
Hello @DeepakR63 - Thank you for reporting this issue. 
Does this repro consistently? Can you share some details, room sids and client side logs would be most helpful.

Thanks,
Makarand
