### ISSUE TITLE
how to get the number of participants connected to a room in twilio javascript sdk like total count of partipants.

### ISSUE THREAD

**Issue by kumargowdaa** [twilio/twilio-video.js#1019]
- [ ] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [ ] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ ] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [ ] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

```js
// TODO
```

**Expected behavior:**

TODO

**Actual behavior:**

TODO

**Software versions:**

 - [ ] Browser(s):
 - [ ] Operating System:
 - [ ] twilio-video.js:
 - [ ] Third-party libraries (e.g., Angular, React, etc.):

**Comment by kumargowdaa** [comment]
@manjeshbhargav

**Comment by manjeshbhargav** [comment]
Hi @kumargowdaa ,

Thanks for writing in with your question. Once everyone has joined the Room, you can find out how many total Participants are present by using `room.participants.size + 1`, with `+ 1` to account for the LocalParticipant.

I'll close this issue now since I've answered your question. But feel free to continue the conversation here if you need further clarifications.

**Comment by kumargowdaa** [comment]
Thank you @manjeshbhargav its worked for me.

**Comment by kumargowdaa** [comment]
fd
fs

public function removeParticipant(){
            $client = new Client($this->sid, $this->token);
            $participant = $client->video->rooms($_REQUEST['roomName'])
            ->participants($_REQUEST['ParticipantName'])
            ->update(array("status" => "disconnected"));
    }

@manjeshbhargav  i have added this function in controller for removal of participant but after calling this function its returning status as "disconnected, but in the ui participant was not removed and its not updating dynamically, please help me on this.

thanks in advance
