### ISSUE TITLE
How to fetch the room duration or each participant duration in UI, when users join into the room, using javascriptSDK.

### ISSUE THREAD

**Issue by kumargowdaa** [twilio/twilio-video.js#1022]
@manjeshbhargav 
How to fetch the room duration or each participant duration in UI, when users join into the room, using javascriptSDK and also how can i close the room so the session of that room should stop or diconnecting all the participants from the room.

 - [ ] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [ ] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ ] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [ ] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

```js
// TODO
```

**Expected behavior:**

TODO

**Actual behavior:**

TODO

**Software versions:**

 - [ ] Browser(s):
 - [ ] Operating System:
 - [ ] twilio-video.js:
 - [ ] Third-party libraries (e.g., Angular, React, etc.):

**Comment by kumargowdaa** [comment]
@manjeshbhargav 
Please share the solution as soon as possible.
Thanks in advance

**Comment by manjeshbhargav** [comment]
Hi @kumargowdaa ,

The JavaScript SDK gives you the Room's state from the point of view of a Participant. If you want to monitor the Room like an admin and know who's joining, who's leaving and time-limit the Room session, ideally you should be doing this from your application server using the [Programmable Video REST API](https://www.twilio.com/docs/video/api/rooms-resource).

Thanks,

Manjesh Malavalli
JSDK Team
