### ISSUE TITLE
Rotate video horizontal and vertical

### ISSUE THREAD

**Issue by santoshnextgeni** [twilio/twilio-video.js#1023]
Hi,

is there any option for flip/rotate video horizontal and vertical in twilio video javascript?

**Comment by manjeshbhargav** [comment]
Hi @santoshnextgeni ,

Do you want to rotate the video locally for your preview or do you want to rotate it also for sending to the remote party? If you want to do it just for your local preview, you can use [CSS](https://hacks.mozilla.org/2011/01/zooming-and-rotating-for-video-in-html5-and-css3/).

If you want to rotate the frames and then send it to the remote party, then you should refer to this [QuickStart Example](https://github.com/twilio/video-quickstart-js/blob/master/examples/localvideofilter/src/helpers.js), which shows how to capture video frames from your camera, apply a transform (in your case rotation) and then create a new LocalVideoTrack from it and publish to the Room.

Thanks,

Manjesh Malavalli
JSDK Team
