### ISSUE TITLE
Android Firefox Support

### ISSUE THREAD

**Issue by TC-bDelRosario1** [twilio/twilio-video.js#1024]
I think an asterisk should be appended to the check mark in browser support, there are open issues with firefox on android around webrtc/audio. We originally ran into a problem with the audio output only coming through the earport on android/firefox, this led us to find these bug reports: 

https://bugzilla.mozilla.org/show_bug.cgi?id=1152401
https://bugzilla.mozilla.org/show_bug.cgi?id=1493990
https://bugzilla.mozilla.org/show_bug.cgi?id=1498512
https://bugzilla.mozilla.org/show_bug.cgi?id=1637235

 - [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

an example of enumerate devices not giving proper result on firefox for android 
https://jsfiddle.net/jib1/LbtxeLvw/

**Expected behavior:**

enumerate devices gives valid audio sources

**Actual behavior:**

enumerate devices only gives input sources

**Software versions:**

 - [x] Browser(s): Firefox 68.8.0
 - [x] Operating System: Android 10
 - [x] twilio-video.js: 2.3.0, 2.4.0
 - [x] Third-party libraries (e.g., Angular, React, etc.):

**Comment by anna-vasilko** [comment]
@TC-bDelRosario1 Thanks for sharing your findings, much appreciated. We'll review and see if we can do something about it.
