### ISSUE TITLE
No dominantSpeaker and no firing of dominantSpeakerChanged in a React project

### ISSUE THREAD

**Issue by olegzhermal** [twilio/twilio-video.js#1026]
Using twilio in a React project. Room is created like this:

```
    const twilioConfig = {
      name: this.props.lessonRoomId,
      audio: localAudioTrack ? true : false,
      video: localVideoTrack ? true : false,
      dominantSpeaker: true,
      tracks
    }
```
```
    Twilio.connect(this.props.twilioIdentity.token, twilioConfig)
      .then(this.roomJoinedOk, this.roomJoinedFail)
      .catch(() => { throw Error({ message: 'Connection failed.' }) })
```

```
roomJoinedOk = (room) => {
  room.on('dominantSpeakerChanged', this.dominantSpeakerChangedHanlder)
  console.log(room)
}
```

```
  dominantSpeakerChangedHanlder = (participant) => {
    console.log('--->');
    console.log(participant);
  }
```

Three participants connected to the room. In the console, there is a room object with:
- localParticipant key containing LocalParticipant object
- participants key containing map of 2 remote participants objects
- dominantSpeaker key evaluated to **null**
And there are no 'dominantSpeakerChanged' fired when participants are talking.

**The question is why there is no dominantSpeaker and no firing of dominantSpeakerChanged event? What is done wrong?**

Thanks in advance.

**Comment by Bumbolio** [comment]
Did you configure your room as a Peer-to-Peer, Small Group, or Group room? The Dominant Speaker API only works on Small Group or Group rooms.

**Comment by makarandp0** [comment]
Thanks @olegzhermal for reporting this, and as @Bumbolio noted (thank you!) dominant speaker feature is available only on group rooms. Can you confirm that this was peer-to-peer room? If you are seeing it in a group room can you please provide room-sid where you see this issue?

Thanks,
Makarand

**Comment by olegzhermal** [comment]
Hi @Bumbolio and @makarandp0, I get it that the Dominant Speaker API only works on Small Group or Group rooms, but cannot find where to specify that. Should it be specified in the twilio panel or when creating a room at the front end? Thanks for your help.

**Comment by olegzhermal** [comment]
To note. In the panel at the usage section, I saw that p2p rooms are used.

**Comment by olegzhermal** [comment]
The issue is resolved. Thanks.
