### ISSUE TITLE
Calling pause() on video/audio tracks only works locally

### ISSUE THREAD

**Issue by andrew-tulip** [twilio/twilio-video.js#1028]
Hi there,

I'm trying to add functionality to my React app to mute your own microphone or disable the camera. I'm currently doing it by invoking these two methods:
```typescript
const disableCamera = () => {
	room?.localParticipant.videoTracks.forEach((publication) => {
		const track = publication.track;
		track.isEnabled ? track.disable() : track.enable();
	});
};

const muteMicrophone = () => {
	room?.localParticipant.audioTracks.forEach((publication) => {
		const track = publication.track;
		track.isEnabled ? track.disable() : track.enable();
	});
};
```

Unfortunately, it only seems to disable the video/microphone locally and it continues to send the tracks, which leads to all other participants still being able see/hear you.

I'm not sure what I'm doing wrong. How can I make it so it disables the tracks both locally and remotely?

Looking forward to a response! Thanks so much. 😄

**Comment by PikaJoyce** [comment]
Hi @andrew-tulip, 

You will have to also handle the enable and disable events on the remote side as well. Please refer to the [documentation](https://www.twilio.com/docs/video/javascript-getting-started#mute-and-unmute-audio-and-video) which should help guide you! 

There is also an example of enabling and disabling video/audio locally and handling it remotely in the [quickstart](https://github.com/twilio/video-quickstart-js) examples as well. 

Let me know if this helps or if you have any other issues. 

Thanks,
Joyce

**Comment by andrew-tulip** [comment]
Hey there, the documentation you provided helped. It works now! 

Thank you so much for your help. Have a great week!
