### ISSUE TITLE
ReferenceError: navigator is not defined

### ISSUE THREAD

**Issue by vineet-agrawal96** [twilio/twilio-video.js#1030]
HI,

I received access token successfully but when I'm pass token to connect roo then i'm getting following issue:-

code to connect room:

Video.connect(token.toJwt(), { name: 'room-name' }).then(room => {
    console.log('Connected to Room "%s"', room.name);
   
    room.participants.forEach(participantConnected);
    room.on('participantConnected', participantConnected);
   
    room.on('participantDisconnected', participantDisconnected);
    room.once('disconnected', error => room.participants.forEach(participantDisconnected));
  });

Error:-

D:\NodeJs\task-manager\node_modules\twilio-video\es5\util\support.js:24
  return !!(navigator.mediaDevices && navigator.mediaDevices.getUserMedia) || !!navigator.getUserMedia || !!navigator.webkitGetUserMedia || !!navigator.mozGetUserMedia;
  ^

ReferenceError: navigator is not defined
    at isGetUserMediaSupported (D:\NodeJs\task-manager\node_modules\twilio-video\es5\util\support.js:24:3)
    at isSupported (D:\NodeJs\task-manager\node_modules\twilio-video\es5\util\support.js:86:10)
    at Object.<anonymous> (D:\NodeJs\task-manager\node_modules\twilio-video\es5\index.js:42:37)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! task-manager@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the task-manager@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\billion\AppData\Roaming\npm-cache\_logs\2020-05-25T10_47_15_257Z-debug.log

**Comment by Swapnull** [comment]
This is most likely the same issue as https://github.com/twilio/twilio-video.js/issues/997 .
It will be fixed in the next release (2.5.0), which has a release candidate going through QA. 

You can use the RC tag in development until it is available by putting the following in your `package.json`
```
"twilio-video": "twilio/twilio-video.js#2.5.0-rc2",
```

**Comment by makarandp0** [comment]
Thanks @vineet-agrawal96 for writing about this, and Than you @Swapnull for the response!
as @Swapnull pointed this is known issue and will be fixed in upcoming release (early next week). 
I will close this as duplicate.
Thanks,
Makarand

**Comment by vineet-agrawal96** [comment]
Thanks @Swapnull  & @makarandp0  for the quick response.

I updated my package.json file with that version and navigator issue is fixed. But I'm facing another issue:-

**Comment by makarandp0** [comment]
Hello again @vineet-agrawal96,

Which browser/os do you see this error ? This could happen on a platform/browser that is not supported. Please make sure that  `require('twilio-video').isSupported` is true before running any of other code.

Thanks,
Makarand

**Comment by vineet-agrawal96** [comment]
Hi @makarandp0 ,

I'm using latest chrome browser version. My Os is **Window 10 Pro**.
And my browser version is : 
**Google Chrome is up to date
Version 83.0.4103.61 (Official Build) (64-bit)**

I checked require('twilio-video').isSupported and it's value is coming false.

**Comment by makarandp0** [comment]
Hello @vineet-agrawal96, The os/browser you mentioned are supported. Are you running this check inside the browser or server as part of server side rendering ? This check only works when run inside the browser.

Can you check if `navigator.mediaDevices.getUserMedia` evaluates correctly from the browser where you see this issue?
