### ISSUE TITLE
isSupported crashes on IE 

### ISSUE THREAD

**Issue by RusseII** [twilio/twilio-video.js#1033]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.
 
 
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.

**Expected behavior:**
isSupported should return false on IE

**Actual behavior:**
Since the isSupported method uses an API that is not supported in IE, 
IE gives error ".includes does not exist on object" 

**Software versions:**

 - [ ] Browser(s): IE11
 - [ ] Operating System: Windows 10
 - [ ] twilio-video.js: 2.4
 - [ ] Third-party libraries (e.g., Angular, React, etc.): React

**Comment by manjeshbhargav** [comment]
Hi @RusseII ,

Thanks for writing in with this issue. I tried reproducing this issue, and was not able to see the error you're seeing on IE11. Can you please share a snapshot of the browser console?

Thanks,

Manjesh Malavalli
JSDK Team
