### ISSUE TITLE
Default audio input track doesn't get replaced

### ISSUE THREAD

**Issue by ivansivaklepsi** [twilio/twilio-video.js#1038]
Hello,

I encountered this problem when trying to switch audio input track using `CreateLocalTrackOptions` -> `deviceId` set to `default` when default track's name changes due to user changing it in Sound in System Preferences or by disconnecting their headphones etc.

Performing device changes using the code below with a specific `deviceId`, rather than just "default", the devices change just fine, however, when user has "default" device selected, performs the one of the changes mentioned above, the code detects it, calls `replaceAudioTrack` with "default" for the `deviceId`, tracks stop as expected, but the newly attached track is still the same and not the new one from the System.

Also worth mentioning is that when you enter the website with `default` input device being e.g. Headphones Mic

1. Switching manually in the app to let's say Built-in Mic
2. Changing `default` in System Preferences to be Built-in Mic instead
3. Switching manually in the app to `default`, which is now labelled correctly as Built-in Mic
4. The flow seems okay, but you still end up with the `default` device which was when you entered the app, so that would be the Headphones Mic, instead of Built-in Mic, which user changed to.

The steps above work as expected without any complications in e.g. Google Meet

 - [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

```ts
  const replaceAudioTrack: ReplaceAudioTrack = React.useCallback(
    async (newDeviceId?: string) => {
      localParticipant?.audioTracks.forEach(trackPublication => {
        trackPublication.track.stop()
        localParticipant.unpublishTrack(trackPublication.track)
        localParticipant.emit('trackUnpublished', trackPublication)
      })
      const newTrack = await getLocalAudioTrack(newDeviceId)
      localParticipant?.publishTrack(newTrack)
      setDeviceId(newDeviceId)
      return newTrack
    },
    [localParticipant, getLocalAudioTrack],
  )
```
```ts
const getLocalAudioTrack: GetLocalAudioTrackFn = async (deviceId?: string) => {
  const options: CreateLocalTrackOptions = {}

  if (deviceId) {
    options.deviceId = { exact: deviceId }
  }

  await ensureMediaPermissions()
  const newTrack = await Video.createLocalAudioTrack(options)
  setTrack(newTrack)
  return newTrack
}
```

**Expected behavior:**

Changing `default` audio input device in the System or anyhow on background should be registered by Twilio when I want to stop the current `default` and publish new `default` track.

**Actual behavior:**

Described with steps above

**Software versions:**

 - [x] Browser(s): Chrome 83.0.4103.61
 - [x] Operating System: Mac OS X 10.14.6
 - [x] twilio-video.js: 2.5.0
 - [x] Third-party libraries (e.g., Angular, React, etc.): React 16.13.1

**Comment by manjeshbhargav** [comment]
Hi @ivansivaklepsi ,

Thanks for writing in with this issue. I think Chrome needs to be restarted for the default device change to take effect. The SDK does not have any control over it. I will close this issue, but we can continue the conversation here if you need more clarification.

Thanks,

Manjesh Malavalli
JSDK Team
