### ISSUE TITLE
Callback-based pc.getStats is deprecated, and will be removed in the near future! Use promise-version!

### ISSUE THREAD

**Issue by markandrus** [twilio/twilio-video.js#104]
Our `getStats` usage triggers a deprecation warning in Firefox. This GitHub ticket tracks the issue. @manjeshbhargav has been working on the necessary changes. Our internal JIRA ticket as JSDK-1227.

**Comment by syerrapragada** [comment]
This was fixed in 1.12.0 (July 25, 2018)
