### ISSUE TITLE
Remote participant video auto-resize itself

### ISSUE THREAD

**Issue by sboudouk** [twilio/twilio-video.js#1041]
- [X] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [X] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [X] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Expected behavior:**

I need the remote participant video track to keep a fix height/width, and not auto-resize itself.

**Actual behavior:**

After I connect to the room, the remote particpant track is displayed but does not take full screen size. After a while, the remote participant video track change size. I assume it's something to do with bandwith/cpu available ressources, but I don't want the user to see remote participant camera going crazy. I recorded a video to show you what is wrong, and I hope i'm not missing something evident since I'm a junior developper.

The video:

https://photos.app.goo.gl/yU4FL1b2uC76hKg28

**Software versions:**

 - [x] Browser(s): Remote = Chrome Latest, Local = Android (Cordova)
 - [x] Operating System: Mac OS
 - [x] twilio-video.js: 2.5
 - [x] Third-party libraries (e.g., Angular, React, etc.): React, Cordova.

Thanks for helping.

**Comment by makarandp0** [comment]
Hello @sboudouk, Thank you for writing with your question. 

As you noted the sdk and underlying webrtc can change the video stream dimensions according to network conditions. But obviously you do not want your video element size to change. General solution for this is to apply width and height constraints on the video element controlling style attributes using css. 

For example: setting max-width and max-height attribute on the video element will ensure that it limited to its parent element. 
```
video {
    max-width: 100%
    max-height: 100%
}
```

Please check out our [react based demo app](https://github.com/twilio/twilio-video-app-react) to see ideas on handling various css attributes. Let me know if it addresses your issue.

Thanks,
Makarand

**Comment by sboudouk** [comment]
Yes, it was an issue on my HTML and CSS, lack of experience, but maybe it will help someone, it works, thanks @makarandp0 .
