### ISSUE TITLE
Participant muting each other in a Room

### ISSUE THREAD

**Issue by kelvinmarshall** [twilio/twilio-video.js#1049]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

```js
// TODO
```

**Expected behavior:**

TODO

**Actual behavior:**

TODO

**Software versions:**

 - [x] Browser(s):
 - [ ] Operating System:
 - [ ] twilio-video.js:
 - [x] Third-party libraries (e.g., Angular, React, etc.):

**Comment by kelvinmarshall** [comment]
I have this usecase for a group room where we have several participants. My question is how can one participant mute another. I'm able to mute and unmute localpartipant audiotrack using `enable()` and `disable()` . But that seems not to work for a remote participant audiotrack

**Comment by manjeshbhargav** [comment]
Hi @kelvinmarshall ,

Thanks for writing in with your issue. As of today, you will have to build this in your application. For example, you could either your own websocket or publish DataTracks to signal to other Participants to disable/enable their audio/video. Then the Participants' code can call `disable()` or `enable()` on their LocalTracks.

Hope this helps.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by kelvinmarshall** [comment]
Thanks @manjeshbhargav . I'll try to implement this. This solution seems promising.

**Comment by p8952** [comment]
Hi @manjeshbhargav,

We're using Twilio Video with non-web participants, bridged from the PSTN: https://www.twilio.com/docs/video/adding-programmable-voice-participants-video-rooms

How can we mute these participants, given we have no way to signal to them out of band?
