### ISSUE TITLE
non-maplike pc.getStats access is deprecated, and will be removed in the near future! See http://w3c.github.io/webrtc-pc/#getstats-example for usage.

### ISSUE THREAD

**Issue by markandrus** [twilio/twilio-video.js#105]
Our `getStats` usage triggers a deprecation warning in Firefox. This GitHub ticket tracks the issue. @manjeshbhargav has been working on the necessary changes. Our internal JIRA ticket as JSDK-1227.

**Comment by sedenardi** [comment]
Just wanted to see if there was any update on this issue. Not currently a hindrance, happy to submit a PR.

**Comment by markandrus** [comment]
Thanks, @sedenardi — we're actually looking to schedule this not this sprint but next. If you still want to try submitting a PR yourself, you can try taking a look at this repo and [twilio/twilio-webrtc.js](https://github.com/twilio/twilio-webrtc.js).

**Comment by syerrapragada** [comment]
1.12.0 (July 25, 2018)
