### ISSUE TITLE
[Help] Need some clarification.

### ISSUE THREAD

**Issue by kumail-raza** [twilio/twilio-video.js#1050]
const client = require('twilio')(accountSid, authToken, { 
    region: 'au1',
    edge: 'sydney',
});

I read some of the links but not get clarity over the 'edge' option, media region is the one to define to which media server the room will be connected, so what 'edge' option will be doing here?

**Comment by manjeshbhargav** [comment]
Hi @kumail-raza ,

According to [this](https://github.com/twilio/twilio-node#specify-region-andor-edge), the `edge` property will help you hit the REST API endpoint in the specified region. While `region` is where the actual service is located, `edge` is where your connection terminates, and from here on till you reach `region`, it is considered internal to Twilio.

Hope this helps.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by kumail-raza** [comment]
Hi @manjeshbhargav 

Ok I am not on to asking something internal to Twilio, just to have high level detail as get a confusion with that region and edge field. Just to have much understanding about Twilio so when implementing with in my product I must know that I am doing it right way, as already facing some issues, reported with diff. issue.

Well still not get you clearly, let me know if I get it correct.

> This will result in the hostname transforming from api.twilio.com to api.sydney.au1.twilio.com

'au1' is the region, where in the region Twilio maintaining more servers in a same region, where 'edge' will be targeting more specific server in that region?

Actually, how it will be benefit to us?

**Comment by manjeshbhargav** [comment]
Hi @kumail-raza ,

`au1` will be the region where the server and data are hosted, and `sydney` is the location of the edge to which you will connect to. The edge will forward your traffic to the server in the region.

Hope this helps.

Thanks,

Manjesh Malavalli
JSDK Team
