### ISSUE TITLE
Poor Video Quality on some devices

### ISSUE THREAD

**Issue by rishab1065** [twilio/twilio-video.js#1059]
![WhatsApp Image 2020-06-10 at 12 36 35 PM (1)](https://user-images.githubusercontent.com/14363507/84278790-cfc9d380-ab52-11ea-974e-f0c624e45df6.jpeg)
![Image from iOS (74) (74)](https://user-images.githubusercontent.com/14363507/84278717-baed4000-ab52-11ea-9b92-41dd77a6b238.png)

In some device, remote participants video is distorted always whereas local participants video is fine.

**Software versions:**

 -  Browser(s): - Chrome / Safari
 -  Operating System: Android / iOS
 -  twilio-video.js: 2.4.0 
 - Third-party libraries : React

**Code for connecting to room**
``` 
Video.connect(<token>, {
        name: videoRoomId,
        audio: false,
        video: false,
        maxAudioBitrate: 16000,
        preferredVideoCodecs: [{ codec: iOSSafari() ? 'H.264' : 'VP8', simulcast: true }],
        networkQuality: { local: 1, remote: 1 },
        dominantSpeaker: true,
        bandwidthProfile: {
          video: {
            mode: 'collaboration',
            trackSwitchOffMode: 'detected',
            maxSubscriptionBitrate: 2500000,
            dominantSpeakerPriority: 'standard',
          },
        },
      })
```

**Comment by rishab1065** [comment]
@makarandp0 @manjeshbhargav attaching the room sid for one of such video call where we faced this issue `RM754d26e021f642d828796ff74652eff1`. Please let me know if anything else is required

**Comment by manjeshbhargav** [comment]
Hi @rishab1065 , @Balasnest ,

Thanks for writing in with this issue. It is a known [Chromium bug](https://bugs.chromium.org/p/webrtc/issues/detail?id=11337) + [WebRTC bug](https://bugs.chromium.org/p/webrtc/issues/detail?id=4787#c5), which we have mentioned in [common issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md#android-chrome-participants-sometimes-see-corrupted-frames-for-remotevideotracks).

If I remember correctly, this happens mostly on certain Pixel devices. Please let me know what devices you are seeing this issue in.

I'm going to close the issue. We can continue the conversation here if you need any more clarification.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by rishab1065** [comment]
@manjeshbhargav Thanks for your reply. I am facing this issue with IphoneX, Galaxy A70s, iPhone 6 S & Oppo F9.
the first image is of Galaxy A70s and the second one is of IphoneX
