### ISSUE TITLE
How to integrate twilio in react native

### ISSUE THREAD

**Issue by tapannathvani** [twilio/twilio-video.js#1061]
**What is the feature that you would like to see in the app? Please describe.**

I want to integrate twilio for video conferencing in my react native app. Can you please guide me how to do that? is there any tutorial or documentation for it?

**Is your feature request related to a problem? Please describe.**

NO
**Describe alternatives you've considered**

As of now i didn't look any other library for the same

**Additional context**
I have followed few examples like : https://medium.com/@neemssoni/react-native-twilio-video-webrtc-488daf735d9b

But its not working.

**Comment by Balasnest** [comment]
@tapannathvani @rebirthtobi You can check this out! 
https://github.com/blackuy/react-native-twilio-video-webrtc

**Comment by tapannathvani** [comment]
I have followed that tutorial.. able to do video call one-to-one.. many to many not working so raised an issue there. Thanks for the reply.

**Comment by Balasnest** [comment]
@tapannathvani Raise an issue on their repo. There are many contributors are coming up over there. Hope will be helpful.

**Comment by manjeshbhargav** [comment]
HI @tapannathvani ,

Thanks for writing in with your request. As of now, we don't have React Native support on our roadmap for 2020. For now, you can work with https://github.com/blackuy/react-native-twilio-video-webrtc.

Thanks,

Manjesh Malavalli
JSDK Team
