### ISSUE TITLE
Uncaught TypeError: Cannot read property '_log' of null

### ISSUE THREAD

**Issue by meness** [twilio/twilio-video.js#1063]
**Code to reproduce the issue:**

```jsx
  useEffect(() => {
    // ...
    return room.disconnect;
  }, [room]);
```

**Expected behavior:**

It should disconnect the user without throwing native exceptions.

**Actual behavior:**

> room.js:163 Uncaught TypeError: Cannot read property '_log' of null
>     at disconnect (room.js:163)
>     at HTMLUnknownElement.callCallback (react-dom.development.js:188)
>     at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
>     at invokeGuardedCallback (react-dom.development.js:292)
>     at safelyCallDestroy (react-dom.development.js:19617)
>     at react-dom.development.js:20090
>     at unstable_runWithPriority (scheduler.development.js:653)
>     at runWithPriority$1 (react-dom.development.js:11039)
>     at commitUnmount (react-dom.development.js:20083)
>     at unmountHostComponents (react-dom.development.js:20464)
>     at commitDeletion (react-dom.development.js:20500)
>     at commitMutationEffects (react-dom.development.js:22782)
>     at HTMLUnknownElement.callCallback (react-dom.development.js:188)
>     at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
>     at invokeGuardedCallback (react-dom.development.js:292)
>     at commitRootImpl (react-dom.development.js:22509)
>     at unstable_runWithPriority (scheduler.development.js:653)
>     at runWithPriority$1 (react-dom.development.js:11039)
>     at commitRoot (react-dom.development.js:22381)
>     at finishSyncRender (react-dom.development.js:21807)
>     at performSyncWorkOnRoot (react-dom.development.js:21793)
>     at react-dom.development.js:11089
>     at unstable_runWithPriority (scheduler.development.js:653)
>     at runWithPriority$1 (react-dom.development.js:11039)
>     at flushSyncCallbackQueueImpl (react-dom.development.js:11084)
>     at flushSyncCallbackQueue (react-dom.development.js:11072)
>     at discreteUpdates$1 (react-dom.development.js:21893)
>     at discreteUpdates (react-dom.development.js:806)
>     at dispatchDiscreteEvent (react-dom.development.js:4168)
> disconnect @ room.js:163
> callCallback @ react-dom.development.js:188
> invokeGuardedCallbackDev @ react-dom.development.js:237
> invokeGuardedCallback @ react-dom.development.js:292
> safelyCallDestroy @ react-dom.development.js:19617
> (anonymous) @ react-dom.development.js:20090
> unstable_runWithPriority @ scheduler.development.js:653
> runWithPriority$1 @ react-dom.development.js:11039
> commitUnmount @ react-dom.development.js:20083
> unmountHostComponents @ react-dom.development.js:20464
> commitDeletion @ react-dom.development.js:20500
> commitMutationEffects @ react-dom.development.js:22782
> callCallback @ react-dom.development.js:188
> invokeGuardedCallbackDev @ react-dom.development.js:237
> invokeGuardedCallback @ react-dom.development.js:292
> commitRootImpl @ react-dom.development.js:22509
> unstable_runWithPriority @ scheduler.development.js:653
> runWithPriority$1 @ react-dom.development.js:11039
> commitRoot @ react-dom.development.js:22381
> finishSyncRender @ react-dom.development.js:21807
> performSyncWorkOnRoot @ react-dom.development.js:21793
> (anonymous) @ react-dom.development.js:11089
> unstable_runWithPriority @ scheduler.development.js:653
> runWithPriority$1 @ react-dom.development.js:11039
> flushSyncCallbackQueueImpl @ react-dom.development.js:11084
> flushSyncCallbackQueue @ react-dom.development.js:11072
> discreteUpdates$1 @ react-dom.development.js:21893
> discreteUpdates @ react-dom.development.js:806
> dispatchDiscreteEvent @ react-dom.development.js:4168
> index.js:1 The above error occurred in the <Room> component:
>     in Room (at WithIO.jsx:5)
>     in Unknown (at WithAuthUser.jsx:8)
>     in WithAuthUser (at Meeting.jsx:69)
>     in Meeting (at WithIO.jsx:5)
>     in Unknown (at WithAuthUser.jsx:8)
>     in WithAuthUser (at ProtectedRoute.jsx:13)
>     in Route (at ProtectedRoute.jsx:9)
>     in ProtectedRoute (at App.jsx:101)
>     in Switch (at App.jsx:95)
>     in IntlProvider (at App.jsx:89)
>     in Router (created by BrowserRouter)
>     in BrowserRouter (at App.jsx:84)
>     in App (at WithIO.jsx:5)
>     in Unknown (at src/index.js:12)
>     in ErrorBoundary (at src/index.js:11)

**Software versions:**

 - [ ] Browser(s): Chrome 83.0.4103.97
 - [ ] Operating System: Window 10 build 19041.329
 - [ ] twilio-video.js: 2.5.1
 - [ ] Third-party libraries (e.g., Angular, React, etc.): React 16.13.1

**Comment by timmydoza** [comment]
Hi @meness, thanks for the question!

React changes the execution context of the cleanup function for useEffect hooks. This means that the value of `this` is changed for the function that is returned from the function passed to useEffect.  This breaks `room.disconnect` because it uses `this` to call other instance methods (see the [source](https://github.com/twilio/twilio-video.js/blob/master/lib/room.js#L137) if you're curious).  I think the hook will work as expected if you do this:

```
  useEffect(() => {
    // ...
    return () => room.disconnect();
  }, [room]);
```
This will preserve the original execution context for `room.disconnect()`. 

Please try this out and let me know if you still have any issues. Thanks!!

**Comment by meness** [comment]
Thanks @timmydoza You're right, your solution fixed it.
