### ISSUE TITLE
Camera not rotating with iPad when it's upside down

### ISSUE THREAD

**Issue by andrew-tulip** [twilio/twilio-video.js#1064]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Expected behavior:**

When I rotate my iPad, no matter the orientation, the local video feed should respect whatever orientation it's in.

**Actual behavior:**

When I rotate my iPad, it only updates the local video feed when it's in landscape left, landscape right, or portrait, not when its upside down.

**Software versions:**

 - [x] Browser(s): iOS Safari
 - [x] Operating System: iOS 13.3.1
 - [x] twilio-video.js: 2.5.1
 - [x] Third-party libraries (e.g., Angular, React, etc.): React

**Comment by TravBradfield** [comment]
Hey @andrew-tulip , 

I'm implementing this in an angular app. Just wondering how you got your videos working for iOS Safari? 

Currently, once I'm connected to the call other see a black video from the iPhone. Then if I disable then enable the camera via the iOS Safari red camera button then eventually the other participant can see the iPhone video. 

Any help would be very much appreciated! Thanks.

Travis

**Comment by andrew-tulip** [comment]
Hi there @TravBradfield,

I referred to this project quite a bit: https://github.com/philnash/twilio-video-react-hooks. I never had any issue with iOS Safari, it worked the same way as it did on desktop. I suggest maybe opening an issue if you can't figure this issue out yourself.

**Comment by TravBradfield** [comment]
Hmm. Okay. That is reassuring. Thanks @andrew-tulip

**Comment by andrew-tulip** [comment]
Any update with this issue?

**Comment by makarandp0** [comment]
Hello @andrew-tulip, Thank you for writing about this, and sorry for the late response - I checked my iPad and see the repro. Looks like an issue with the `getUserMedia` as I see the same behavior on this sample app. https://webrtc.github.io/samples/src/content/getusermedia/gum/

Interestingly I see this only for front camera - back camera rotates fine when iPad is held upside down. One workaround I can think of is to listen for [device orientation change](https://developer.mozilla.org/en-US/docs/Web/API/ScreenOrientation/onchange) and flash a light warning user if its upside down. Would that work in your scenario?

Thanks,
Makarand

**Comment by andrew-tulip** [comment]
Thanks for the response @makarandp0, unfortunately the warning light workaround doesn't work well for our use case.

So is this a Safari WebKit bug then? I can open a Radar with Apple.

**Comment by makarandp0** [comment]
Yes, it's an issue with iOS Safari - Please open a bug with Apple.

**Comment by andrew-tulip** [comment]
Opened a bug with Apple here: https://bugs.webkit.org/show_bug.cgi?id=213993.

Closing this issue. Thanks for the help!
