### ISSUE TITLE
Mistake in twilio getting started guide

### ISSUE THREAD

**Issue by Illia-hryhoryshyn** [twilio/twilio-video.js#1066]
I don't know in which repository I should put this little issue, so I decided put it here. It related to docs in twilio [getting started guide](https://www.twilio.com/docs/video/javascript-getting-started#video-api-overview). There are a little mistake, the variable `track` is undefined in this example and instead of this should be `publication.track`. Will be nice to correct it to help people avoid mistake by using this example.
![image](https://user-images.githubusercontent.com/49511783/85163770-064ad100-b26c-11ea-875b-91f1aa37f90c.png)

**Comment by PikaJoyce** [comment]
Hi @Illia-hryhoryshyn,

Thank you for reporting this issue! We will work on getting this fixed as soon as possible. I will update this when it is done. 

Regards,
Joyce

**Comment by PikaJoyce** [comment]
Hey @Illia-hryhoryshyn!

Thanks again for reporting the issue, the documentation has been fixed. I'll be closing this issue now. Feel free to open another if you come across any more issues! 

Best,
Joyce
