### ISSUE TITLE
track.stop() is not a function

### ISSUE THREAD

**Issue by TravBradfield** [twilio/twilio-video.js#1067]
- [y] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [y] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [y] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [y] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

```js
room.on('disconnected', room => {
        console.log('You disconnected: ', room);
        room.participants.forEach(element => {
          this.participantDisconnected(element)
        });
      })

  participantDisconnected = (participant) => {
    console.log('Participant "%s" disconnected', participant.identity);
    document.getElementById(participant.sid).remove();
    const track = [...participant.videoTracks.values()][0].track;
    track.stop();
    track.detach(this.localVideoTrack.current);
    participant.unpublishTrack(track);
    this.disconnectCall();
  }
```

**Expected behavior:**

I expect the local video to be stopped by "track.stop()".

**Actual behavior:**

I'm getting an error saying track.stop() is not a function.

TODO

**Software versions:**

 - [ ] Browser(s): Chrome, Safari
 - [ ] Operating System: MacOS Catalina 10.15.5
 - [ ] twilio-video.js: 2.4.0
 - [ ] Third-party libraries (e.g., Angular, React, etc.): Angular

**Comment by manjeshbhargav** [comment]
Hi @TravBradfield ,

Thanks for writing in with your issue. In your snippet, you are attempting to stop RemoteParticipants' Tracks, which is not possible. You can only stop your own Tracks, which can be done as follows:
```js
  room.on('disconnected', room => {
    console.log('You disconnected: ', room);
    room.participants.forEach(participant => this.participantDisconnected(participant));
    this.participantDisconnected(room.localParticipant);
  });

  participantDisconnected = participant => {
    console.log('Participant "%s" disconnected', participant.identity);
    document.getElementById(participant.sid).remove();
    const track = [...participant.videoTracks.values()][0].track;
    if (track.stop) {
      track.stop();
      track.detach(this.localVideoTrack.current);
    }
    this.disconnectCall();
  }
```

Hope this helps. I'll close this issue since I've answered your question, but we can continue the conversation here if you need any more clarification.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by TravBradfield** [comment]
@manjeshbhargav Thanks for your response. I've tried your code snippet but it hasn't made any difference.. Here is a screen shot of my console. 

<img width="834" alt="Screenshot 2020-06-23 at 20 47 57" src="https://user-images.githubusercontent.com/32768356/85452480-d44ead00-b592-11ea-82f5-b34c61d98791.png">

**Comment by TravBradfield** [comment]
> Hi @TravBradfield ,
> 
> Thanks for writing in with your issue. In your snippet, you are attempting to stop RemoteParticipants' Tracks, which is not possible. You can only stop your own Tracks, which can be done as follows:
> 
> ```js
>   room.on('disconnected', room => {
>     console.log('You disconnected: ', room);
>     room.participants.forEach(participant => this.participantDisconnected(participant));
>     this.participantDisconnected(room.localParticipant);
>   });
> 
>   participantDisconnected = participant => {
>     console.log('Participant "%s" disconnected', participant.identity);
>     document.getElementById(participant.sid).remove();
>     const track = [...participant.videoTracks.values()][0].track;
>     if (track.stop) {
>       track.stop();
>       track.detach(this.localVideoTrack.current);
>     }
>     this.disconnectCall();
>   }
> ```
> 
> Hope this helps. I'll close this issue since I've answered your question, but we can continue the conversation here if you need any more clarification.
> 
> Thanks,
> 
> Manjesh Malavalli
> JSDK Team

`const track = [...participant.videoTracks.values()][0].track;`

this track is always undefined!! I'm really battling to understand why. There is no participant being passed in which is why it always fails.. But why!?!?! 

(Tearing my hair out)
