### ISSUE TITLE
How can I capture log messages?

### ISSUE THREAD

**Issue by webjay** [twilio/twilio-video.js#1076]
I am using `loglevel` and `loglevel-plugin-remote` to have logs sent to [Loggly](https://loggly.com/).

But how can I best capture log messages from `twilio-video`?

Currently, this is what I do:
```
function Log() {}
Log.prototype.log = log.info;
Log.prototype.info = log.info;
Log.prototype.warn = log.warn;
Log.prototype.warnOnce = log.warn;
Log.prototype.debug = log.debug;
Log.prototype.error = log.error;
Log.prototype.throw = log.error;
Log.prototype.createLog = () => new Log();

connect(jwt, {
  name: roomName,
  Log,
  tracks: [...localTracks, dataTrack],
}))
```

**Comment by makarandp0** [comment]
Hello @webjay, thank you for writing about this issue. 

Unfortunately we do not yet have a way for you to customize the logger used by twilio-video. This feature has been asked for [before](https://github.com/twilio/twilio-video.js/issues/650) and it's on our backlog. (JSDK-2373)

One way would be to override console.log like somebody tried [here](https://github.com/twilio/twilio-video.js/issues/887). but I would suggest please wait such feature to be added to twilio-video.  

Thanks,
Makarand.
