### ISSUE TITLE
Black screen when renderer remote video track after trackSubscribed event

### ISSUE THREAD

**Issue by rishab1065** [twilio/twilio-video.js#1082]
- [X] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [X] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ ] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [X] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Expected behavior:**

After connecting to the room and getting trackSubscribed event for the participant, remote participant video is sometimes taking 10 - 20 secs to start

**Actual behavior:**
After connecting to the room and getting trackSubscribed event for the participant, remote participant video should start immediately

TODO

**Software versions:**

 - [X] Browser(s): Chrome
 - [X] Operating System: Mac
 - [X] twilio-video.js: 2.4.0
 - [X] Third-party libraries (e.g., Angular, React, etc.): React, React Native

**Comment by rishab1065** [comment]
Similar issues https://github.com/twilio/video-quickstart-android/issues/536

**Comment by Balasnest** [comment]
Huge delay in rendering remote video very first frame. @manjeshbhargav 

Looks like a global issue. It's happening in almost all the platforms.

**Similar issue related to iOS:**
[ios - 214](https://github.com/twilio/video-quickstart-ios/issues/214) 
[ios - 240](https://github.com/twilio/video-quickstart-ios/issues/240)

**Similar issue related to RN:**
[RN - 94](https://github.com/blackuy/react-native-twilio-video-webrtc/issues/94)

**Comment by manjeshbhargav** [comment]
Hi @rishab1065 , @Balasnest ,

Thanks for writing in with your issues. Can you share some Room SIDs so we can start investigating?

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by manjeshbhargav** [comment]
@rishab1065 ,

I'm closing this since there has been no response in 2 weeks. Please feel free to re-open if you need more assistance in this matter.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by izabelavmelo** [comment]
Hi,
I'm using twilio-video.js 2.10.0 and @types/twilio-video 2.7.1.

Experiencing a similar issue. When receiving remote video track subscribe (video is ok here) -> unsubscribe -> subscribe , after the last subscribe the user gets a black screen in the remoteVideoTrack.

Last year this works fine in our website.

**Comment by apostololeg** [comment]
Same issue here. 
iOS 13
twilio-video.js 2.12.0

**Comment by Flo-Mercaux** [comment]
Hi @manjeshbhargav ,

@apostololeg and I are still facing the same issue.
- We have managed to fix the issue with iOS13 thanks to [browsers' autoplay policy](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md#working-around-the-browsers-autoplay-policy)
- The workaround does NOT work for prior iOS version (iOS 11 and 12 and potentially earlier versions)
Any hint?

@rishab1065 , @izabelavmelo , have you managed to solve this issue?

Software version:
- Browser(s): Safari
- Operating System: iOS 11 and 12 (and potentially previous versions)
- twilio-video.js: 2.12.0
- Third-party libraries: JavaScript, React and Angular

Thanks,
Florent

**Comment by paradox-nhihieu** [comment]
Hi @manjeshbhargav ,
We are facing the same issue here
Software version:

- Browser(s): Safari ( I reproduce once time on Chrome/Ubuntu 18.04)
- Operating System: iOS 11 and 12 (and potentially previous versions)
- twilio-video.js: 2.4.0
- Third-party libraries: JavaScript, VueJs

**Comment by izabelavmelo** [comment]
Hi, @Flo-Mercaux !
I fixed with this issue: https://github.com/twilio/twilio-video.js/issues/558#issuecomment-467981412

I removed the `stop()` and it works for me:
![Screenshot from 2021-04-19 09-56-46](https://user-images.githubusercontent.com/11953003/115239905-97414180-a0f5-11eb-871e-0ae503d07413.png)

But I faced this bug on all devices (not only iOS). So, I think it's not the same as you. :disappointed:
