### ISSUE TITLE
getUserMedia is not supported Error

### ISSUE THREAD

**Issue by snigdho991** [twilio/twilio-video.js#1083]
- [ ] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [ ] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ ] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [ ] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

**Expected behavior:**

It is expected to view my current status via webcam. Website link- https://videochat.roaringbangladesh.com/

**Actual behavior:**

On Chrome webcam isn't opened and give the following error: 

``Unable to connect to Room: getUserMedia is not supported
``

Along with: 

`2020-07-03 01:08:16.172Z | WARN in [createLocalTracks #1]: Call to getUserMedia failed: Error: getUserMedia is not supported
    at _getUserMedia (app.js:57211)
    at getUserMediaPromise (app.js:57193)
    at new Promise (<anonymous>)
    at Object.getUserMedia (app.js:57192)
    at Object.createLocalTracks (app.js:50842)
    at getLocalTracks (app.js:56361)
    at onCreate (app.js:58680)
    at CancelablePromise.Object.defineProperty.value (app.js:50630)
    at new Promise (<anonymous>)
    at new CancelablePromise (app.js:50629)`

And On Internet Explorer, webcam is opened but give the following error: 

`Unable to connect to Room: Media connection failed`

**Software versions:**

 - [Chrome, Internet Explorer] Browser(s):
 - [Windows] Operating System:
 - [yes] twilio-video.js:
 - [Vue.js] Third-party libraries:

**Comment by TravBradfield** [comment]
I am having the exact same problem. 

I'm using Ionic/Angular. All works fine on Android browsers and desktop browsers. Problem arises on non-Safari iOS browsers (Firefox & Chrome on iPhone & iPad).

Software versions:

Browser(s): [iOS Chrome, iOS Firefox, iPadOS Chrome, iPadOS Firefox] 
Operating System: [iOS, iPadOS]
twilio-video.js: [yes] 
Third-party libraries: [@Ionic/Angular]

**Comment by makarandp0** [comment]
Hello @snigdho991 and @TravBradfield - Thank you for writing about your issue. 

@snigdho991,
I clicked on your app link, and did see video capture working fine (on chrome/MacOS).  `getUserMedia` could fail for lot of  reasons. Please refer to some of the common errors and their causes documented here: https://www.twilio.com/docs/video/build-js-video-application-recommendations-and-best-practices#media-errors

Which version of internet explorer do you see this error on? Perhaps it does not support `getUsermedia` or it could be that the access it blocked at system level by window. You can confirm that its not specific to twilio-video by checking sample @ https://webrtc.github.io/samples/src/content/getusermedia/gum/

@TravBradfield - In your case, I think it's expected. iOS does not allow media access to browsers others that Safari. 

Let me know if that answers your questions,
Thanks,
Makarand

**Comment by snigdho991** [comment]
@makarandp0  You are right. I was testing my application on the localhost. That's why this error was occurred. When I host the app in a live server and logged in to with another device it's running smoothly. Thanks for your response. Another thing, when the video call started my camera doesn't rotate. That means it doesn't look like a mirror. Rather than it gives an anti-mirror view. Can you please help me to the problem ?

**Comment by bryanhpchiang** [comment]
@snigdho991 on the <video> element use transform: scaleX(-1) for CSS

**Comment by snigdho991** [comment]
> @snigdho991 on the element use transform: scaleX(-1) for CSS

Excellent. Thank you.

**Comment by snigdho991** [comment]
I have been facing another problem. I have recently added mute audio and disable video feature. Everything works fine except when localParticipant disable his camera the screeen gets blank/nill. But on the other end, other users of the room don't see the blank/nill background. Instead of they can see the freezing image of the localparticipant user. That means, local participant end works fine but on the other participants end, the video freezes. Can anyone of here please help me to figure out the problem ? Or should I open a new issue ? Thanks in advance.

**Comment by manjeshbhargav** [comment]
@snigdho991 Pleas open a new issue so that we can track the discussion better. I will close this issue since your questions have been answered.

**Comment by bryanhpchiang** [comment]
@snigdho991 idk if theres a new issue created yet, but you need to detect one of the track disabled/unpublished/unsubscribed events and display a local avatar instead

i have more details about how i'm doing mute/disable video here
https://github.com/twilio/twilio-video.js/issues/656

**Comment by imrohangaur** [comment]
I am using twillio-video for my react Native app, and I am getting the same error that, _getUserMedia is not supported_ 
What could be solution for this?
