### ISSUE TITLE
Getting the same offset for all recordings in a room

### ISSUE THREAD

**Issue by todoroff** [twilio/twilio-video.js#1084]
Not related to the twilio-video.js package itself, but don't know where else to open this issue. In the Recordings REST API JSON response I'm getting the same offset value for each participant's recording, no matter when they join. 

Example:
1. **User A** creates and joins a room.
2. **User B** joins the room at **T+5s**.
3. **User C** joins the room at **T+35s**.

Result:
Each recording has the _same offset value_.

Expected: 
- offset(User A) = some value.
- offset(User B) = offset(User A) + **5000ms**
- offset(User C) = offset(User A) + **35000ms**

**Comment by manjeshbhargav** [comment]
Hi @todoroff ,

We only address issues related to twilio-video.js here. Please open a [support](https://support.twilio.com/) request for your issue to be handled by the proper team.

Thanks,

Manjesh Malavalli
JSDK Team
