### ISSUE TITLE
[Firefox] Remote video freezes when publishing local audio and video tracks independently.

### ISSUE THREAD

**Issue by ByScripts** [twilio/twilio-video.js#1087]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ ] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

When a remote video from our Android app is displayed on Firefox web app (peer-to-peer mode) and tracks from Firefox are published independently (one after the other) with `publishTrack`, the remote video on Firefox is freezing.

When the Firefox web app publishes its audio and video tracks simultaneously with `publishTracks` (notice the "s"), it works as expected.

```js
// WORKS

try {
  await room.localParticipant.publishTracks([localAudioTrack, localVideoTrack]);
} catch(error) {
  throw new Error('Unable to publish audio and/or video track');
}

// DOESN'T WORK (FREEZE THE REMOTE VIDEO)

try {
  await room.localParticipant.publishTrack(localAudioTrack);
} catch(error) {
  throw new Error('Unable to publish audio track');
}

try {
  await room.localParticipant.publishTrack(localVideoTrack);
} catch(error) {
  throw new Error('Unable to publish video track');
}

```

**Expected behavior:**

The remote video should not freeze in Firefox when publishing tracks one after the other

**Actual behavior:**

The remote video is freezing in Firefox. 

Not reproducible with Chrome nor Safari.

**Software versions:**

 - [ ] Browser(s): Firefox
 - [ ] Operating System: macOS
 - [ ] twilio-video.js: 2.6.0
 - [ ] Third-party libraries (e.g., Angular, React, etc.): No, vanilla JS

**Comment by manjeshbhargav** [comment]
Hi @ByScripts ,

Thanks for writing in with your issue. I have a few questions:

1. Can you reproduce this behavior between two browsers?
2. What version of the Twilio Video Android SDK are you using in your android app?
3. Can you share some Room SIDs so that we can take a look at our internal logs?

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by ByScripts** [comment]
Hi,

1. No, we were unable to reproduce the behavior with anything else but Firefox/Android. All other tests were OK.
2. Version 5.8.1 of Android SDK
3. It would be difficult to reproduce the problem now it is fixed (without reintroducing the bug and pushing the code to our staging env). But here is the SID of the Room I got while trying to figure out the bug, 3 days ago. Hope this helps : RM1e82a7c0363fd1cd399610753a5fe1b9

Thank you.

**Comment by auguszou** [comment]
@manjeshbhargav

we have same logic to support switch camera or mic separately.
the other end will see several seconds freeze when someone switched their audio device.

here is the log from the other end events.
![image](https://user-images.githubusercontent.com/3761283/109101071-012a1400-7761-11eb-876e-6d4e566a2942.png)

no video track event happened during audio switching. but why video froze for several seconds?

Software versions:
- [ ]  Browser(s): Chrome & Firefox (the other end)
- [ ] Operating System: MacOS
- [ ] twilio-video.js: 2.12.0
- [ ] Third-party libraries: ReactJS
