### ISSUE TITLE
Pixelated Stream from Desktop, P2P

### ISSUE THREAD

**Issue by Patrick-Ullrich** [twilio/twilio-video.js#1088]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

Using the twilio-video-app-react
```js
    video: {
      height: 480, // 720
      frameRate: 24,
      width: 640, // 1280
      echoCancellation: false, // true
      autoGainControl: false, // true
      noiseSuppression: false, // true
    }, 
   maxAudioBitrate: 40000,
```

**Expected behavior:**
Based on video input, I am expecting to see higher or lower Video Quality.

**Actual behavior:**
Video Quality stays pixelated throughout.

Related to #983  (which has been closed, but seeing same pixelation) and maybe a bit to #1055

Testing locally with 100mbit PC, and I can not get the video quality to improve. 

This is using Peer-to-Peer. I am mostly confused as in why the quality does not change what so ever when increasing those values. When changing to SmallGroup the quality increases as expected.

**Software versions:**

 - [x] Browser(s): 83.0.4103.116
 - [x] Operating System: Windows 10
 - [x] twilio-video.js: ^2.6.0
 - [x] Third-party libraries (e.g., Angular, React, etc.): React

**Comment by manjeshbhargav** [comment]
Hi @Patrick-Ullrich ,

`twilio-video-app-react` is a collaboration application, and therefore is optimized for Group Rooms. The most probable reason for the pixelated video in Peer to Peer Rooms is due to VP8 simulcast being turned on. The video quality should improve if you remove the `preferredVideoCodecs` ConnectOptions property.

Please let me know if this helps.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by Patrick-Ullrich** [comment]
Hey @manjeshbhargav ,

you are right. Once commenting out preferredVideoCodecs (including with simulcast: true), peer-to-peer quality increased based on the settings changed. 

Thanks,
Patrick
