### ISSUE TITLE
Screen Capture Firefox publisher not working

### ISSUE THREAD

**Issue by theDude30** [twilio/twilio-video.js#109]
- [X ] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [ X] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ X] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.

**Code to reproduce the issue:**

        var constraints = {
            video: {
                mozMediaSource: 'window',
                mediaSource: 'window'
            }
        }
 navigator.mediaDevices.getUserMedia(constraints)
                .then(function (stream) {
   Video.createLocalVideoTrack({
                video: {
                    mozMediaSource: 'window',
                    mediaSource: 'window'
                },
            }).then(function(desktopTrack) {
                var localMediaContainer = document.getElementById('localVideo');
                localMediaContainer.appendChild(desktopTrack.attach());
                return Video.connect(data.token, { name: room, tracks: [ desktopTrack ] });
            });
});

**Expected behavior:**

In chrome i receive sourceID and passed it into the the constraints. in Firefox i hoped to get something similar but i don't. I would like to be able to take the "LocalMediaStream" Object that i received from firefox and just pass it to "Video.createLocalVideoTrack" somehow.

**Actual behavior:**

I've created Firefox extension that seems to work, when i do "navigator.mediaDevices.getUserMedia(constraints)" i'm getting back "LocalMediaStream" but i have no way to add that into twilio.

TODO

**Software versions:**

 - [X ] Browser(s): publisher - Firefox 53.0.2, Viewer: chrome  58.0.3029.96 (64-bit)
 - [ X] Operating System: Publisher windows 10, viewer: osx 10.12.4
 - [X ] twilio-video.js: 1.0.0
 - [X ] Third-party libraries (e.g., Angular, React, etc.): None, pure javascript.

**Comment by markandrus** [comment]
Hi @theDude30,

In general, if you have a MediaStream you can call `getVideoTracks` on it and pass each MediaStreamTrack to the `LocalVideoTrack` constructor (exposed under the `Twilio.Video` global or exported by the CommonJS module, depending on how you include the library).

However, I think the most straightforward way to solve your problem is by calling `createLocalVideoTrack` with the constraints directly, e.g.

```
createLocalVideoTrack({
  mozMediaSource: 'window',
  mediaSource: 'window'
}).then(localVideoTrack => {
  // ...
});
```

I'm typing this on my phone, so hopefully that is correct. Can you try it out?

Mark

**Comment by theDude30** [comment]
Worked like a charm, thanks for the quick response.
By the way, firefox does not require to install any plugin or extension to start the screen sharing,which is great.
