### ISSUE TITLE
IOS-Safari audio is played in both channels during a conference call

### ISSUE THREAD

**Issue by tzipisheinin** [twilio/twilio-video.js#1100]
We are working in tele-audiology (remote hearing tests) world, using Twilio for video-conferencing on our web solution.
We currently face an issue with iOS-Safari, during a conference call, we're playing signal generated using webaudio to one ear only, but the signal is played to both channels as mono. 
Whenever we stop the video (using the red camera in url toolbar), the sound is played on the right channel, as intended. Back to the video, it's on both channels again.

In order to reproduce this bug, we just add to Twilio's quick start app a button that's playing simple oscilator audio to the right ear 
https://twilio-video-with-audio.herokuapp.com/quickstart/ - here you can simply see the bug and the audio code.

Sure this one works fine in all other platforms and browsers.
Any help would greatly be appreciated. Thanks!

**Comment by manjeshbhargav** [comment]
Hi @tzipisheinin ,

Sorry for the delayed response. This looks most likely like a bug in iOS Safari. I have reproduced the same behavior with this [CodePen Snippet](https://codepen.io/manjeshbhargav/pen/vYLwLxB). I will file a WebKit bug and close this issue. Thank you for bringing this to our notice.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by manjeshbhargav** [comment]
Hi @tzipisheinin ,

I have filed a WebKit bug [here](https://bugs.webkit.org/show_bug.cgi?id=214853). Please take a look and star it so that the Apple engineers are notified.

Thanks,

Manjesh Malavalli
JSDK Team
