### ISSUE TITLE
Disabling a track after a switch-off causes the track to never receive events again

### ISSUE THREAD

**Issue by preppypiet** [twilio/twilio-video.js#1107]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

```js
// Connect to a room with maxTracks set low, to something like 1 or 2 and mode 'presentation'
// Connect a few participants
// Once one of the participant's remote tracks are switched off by twilio's bandwidth api, disable that the local video track for that participant with the .disable() function on the track
// Turn on the mic for that disabled video track participant and start speaking to ensure they become dominant, and set the priority for their track to high, then re-enable their video track
```

**Expected behavior:**

The previously switched off and then disabled video track that was enabled again should correctly transmit to other participants, and the track should have its trackSwitchedOff flag set to false, and a track switched on event should have been raised with other participants.

**Actual behavior:**

None of the expected behaviour works, the track is never switched on again, and appears to never emit any sort of event. No data is sent from twilio either, the video stream just stops. I have debugging turned on, but never appear to receive an event for the remote track being switched on after being disabled, and no event either when re-enabling it.

TODO

**Software versions:**

 - [x] Browser(s): All supported
 - [x] Operating System: macOS Catalina
 - [x] twilio-video.js: ^2.5.1
 - [x] Third-party libraries (e.g., Angular, React, etc.): React

**Comment by manjeshbhargav** [comment]
Hi @preppypiet ,

Thanks for writing in with your question. I am including @jcaden , who is part of the media server team. @jcaden , can you take a look at this issue?

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by jcaden** [comment]
Hi @preppypiet,

Thank you for your report. Could you provide a room sid with a recent occurrence so we can better understand what is going on under the hood and why you are not getting the expected behavior? 

Thank you.

Jose Santos
Video Media Server Tech Lead

**Comment by preppypiet** [comment]
Hi @jcaden,

I could, but it will take a while as we've changed the way we turn video off to work around this issue. We now unpublish and publish a video track instead of calling .disable or enable on it. Our iOS team has experienced exactly the same issues with disabling and enabling video tracks between ios devices, and ios and web. We're pretty sure it's server side that this is happening. 

I will need time to change things around here, but will get that to you. Following the steps I outlined above will produce this issue 100% of the time though. It's not related to dominant speaker, you connect multiple participants with maxTracks set to 1 and mode 'presentation', once one of their videos is switched off, disable that participant's video from their device, and then twilio will never send you an event or any data from their disabled video track again, at least that's how it appears from what I can see, even if the video track is enabled by them again. This doesn't happen with audio tracks, as twilio never switches those off.

**Comment by jcaden** [comment]
Glad to hear that you found a workaround. It will be great if you could provide a roomSid, anyway we will investigate ourselves with the reproducing steps that you mentioned. 

Thanks again for your report.

**Comment by preppypiet** [comment]
> Glad to hear that you found a workaround. It will be great if you could provide a roomSid, anyway we will investigate ourselves with the reproducing steps that you mentioned.
> 
> Thanks again for your report.

Thanks, I'll try and get that to you soon, but it takes a lot of time changing things over and roping 3 colleagues into reproducing the issue. It's not really a great workaround, as there's a considerable performance cost to publishing/unpublishing vs enabling and disabling - we would really like to be able to use enable and disable. The steps I outlined will reproduce the issue every single time though. I'll get that sid as soon as I can, but it involves breaking working code and redeploying :)

**Comment by preppypiet** [comment]
@jcaden sorry for the delay there, here's a roomsid with the issue happening: RM440a011dd48486283cf3d6ef6987487b

In that call, i had three clients connected. Max tracks was 1. When one of the 3 participants was switched off by twilio, that participant then disabled their video. My participant (the one that had the other participant switched off) then muted, and everyone else was on mute. The participant that was switched off for my client then unmuted and talked in order to become dominant (which will set the track priority appropriately for everyone to ensure they should be switched back on) and then re-enabled their video (track.enable()). Everyone was still seeing their track as switched off (no switch on event occurred). If that participant then re-disabled their video, every other client updated correctly (showing video disabled), but on re-enabling again, the video was still switched off for all clients (track.isSwitchedOff true, no switchedOn event was ever fired).

The only way around this is to use unpublish and publish instead of enable and disable. I noted that the react video app you guys put on github does the exact same thing (pub and unpub instead of enable and disable). I'm pretty sure this is something twilio side, with the switching off and on of tracks seemingly disabling twilio from handling those tracks ever again. This exact same behaviour occurs with iOS between iOS clients, and iOS and web. 

These are called when we disable and enable tracks:

```javascript
const enableVideo = async () => {
     videoTrackPublication.track.enable()
}

const disableVideo = async () => {
     videoTrackPublication.track.disable()
}
```
Please let me know if there's any more information you need, or if there's something we can do to enable the use of the enable and disable api other than changing the mode from 'presentation' (we need to use this mode)

**Comment by jcaden** [comment]
Thank you for the report. I'm including this information to our internal issue. It actually looks like an issue, we are giving high priority to this.

**Comment by preppypiet** [comment]
Thank you, please let me know if there's anything more I can provide.

**Comment by nicopernas** [comment]
Just a quick update on this one. We were able to reproduce the scenario you described and applied a fix for it. The patch is now going through QA and will be made available to you with our next release, at some point in the next two weeks. We'll ping you back once that's happened. Thanks.

**Comment by preppypiet** [comment]
Hi @nicopernas do you have an update on this issue yet?

**Comment by nicopernas** [comment]
Hey! we deployed a fix for it just a few days ago. Would be great if you could confirm your use case is fixed now? Many thanks

**Comment by preppypiet** [comment]
Hi @nicopernas yes, it appears fixed now. Thank you very much!
