### ISSUE TITLE
need to understand screen sharing

### ISSUE THREAD

**Issue by hirenmistry17** [twilio/twilio-video.js#1111]
Hello i have to implement Screen sharing feature,
i have searched for documentation and some of methods and properties are deprecated, nothing works for me, 

anyone have idea how screen sharing works

**Comment by anderjs** [comment]
I recently have the same issue on my code.

I can attach the current share screen video as docs explain.
But only on my localVideoTrack, but I don't know how to display my share screen on other participants, exist a good tutorial on React docs?.

**Comment by ksocha** [comment]
Some time ago I created a repository with sample solution: [twilio-screensharing](https://github.com/ksocha/twilio-screensharing). Have a look, maybe it will be of some help.

**Comment by anderjs** [comment]
@ksocha Why my publishTrack is not working? I need to understand why. I need to do something extra when "publishTrack" event is fired?

**Comment by anna-vasilko** [comment]
@hirenmistry17 
Twilio video quick-start has a recent screen sharing example (see in "examples") - https://github.com/twilio/video-quickstart-js
Twilio React demo application has a working screen sharing functionality - https://github.com/twilio/twilio-video-app-react

**Comment by manjeshbhargav** [comment]
Hi @hirenmistry17 ,

Hope @anna-vasilko 's comment with the links to the screen sharing documentation has helped you. I will close this issue, but please reach out to us here if you need any more clarification.

Thanks,

Manjesh Malavalli
JSDK Team
