### ISSUE TITLE
Share screen is not working

### ISSUE THREAD

**Issue by anderjs** [twilio/twilio-video.js#1112]
I'm facing an issue while sharen my screen. 

```
  const handleMediaScreenShare = useCallback(async () => {
    try {
      const stream = await navigator.mediaDevices.getDisplayMedia({
        video: true
      })

      const [tracks] = stream.getTracks()

      const localVideoTrack = new LocalVideoTrack(tracks)

      room.localParticipant.publishTrack(localVideoTrack)

      localVideoTrack.mediaStreamTrack.onended = function () {
        room.localParticipant.unpublishTrack(localVideoTrack)
      }
    } catch (err) {}
  }, [room])

```

This should work as docs indicates, but the main problem is, is not publishing anything.
I don't need support on old browsers, so, my question is, the twilio extension is highly required?
I attach the stream to the current videoRef, but is not attaching anything on the other participants.
`trackPublished` event is for this case? it fires the event, but is not tracking anything on the track like `attach` function, so, I'm upgrade recently the project of twilio, and is very frustrating that the documentation is not very effective on the main libraries/frameworks of JavaScript.

Any solution here?

 - [Chrome Latest] Browser(s):
 - [Windows 10] Operating System:
 - [Latest ] twilio-video.js:
 - [React ] Third-party libraries (e.g., Angular, React, etc.):

**Comment by PikaJoyce** [comment]
Hi @anderjs 

Thank you for opening this issue with us. A few questions, if there are any errors being logged in the console, would it be possible to share them? Also, if you have some piece of code where the `remoteParticipant` is listening on the `trackPublished` event, could you please share that as well? 

Regards,
Joyce

**Comment by anderjs** [comment]
Hi @PikaJoyce  There's no error on the catch exception. 
Here are some logs.
First log is from` remoteParticipant.publishTrack`
The second is from the callback of `trackPublished` event on the lifecyle `useEffect`.

![Issue from localparticipant](https://user-images.githubusercontent.com/40301771/88342724-8a79f380-cd05-11ea-9616-eed844822287.png)

And here is the log from the remoteParticipant callback when takes the event from `trackPublished`
![109390296_308149780464284_2857607763674978011_n](https://user-images.githubusercontent.com/40301771/88343005-0ecc7680-cd06-11ea-9150-8e4618ec306d.png)


I need to make something different when the remoteParticipant is listening?
![code](https://user-images.githubusercontent.com/40301771/88343089-36234380-cd06-11ea-909e-86905217bc07.png)
Data is the prop through functional component that indicates `participant.on('trackPublished')`

Participant.js
https://gist.github.com/anderjs/fc46d5755921a822c13bb69098ac6d50
Gist from Participant Component.

ClassRoom.js
Component.
https://gist.github.com/anderjs/0591be7e826b30d27bb9b80ed6de680b

**Comment by anderjs** [comment]
I'm testing on two different laptops, I'm not using incognito mode.

**Comment by PikaJoyce** [comment]
Hi @anderjs,

It seems that your screenshare track is successfully getting published. However, one thing I noticed in `Participant.js` is on [Line 159](https://gist.github.com/anderjs/fc46d5755921a822c13bb69098ac6d50#file-participant-js-L159), this will allow you to render the first VideoTrack available. Meaning, if you're publishing a screenshare track, then you would have 2 videoTracks in `state.videoTracks` to account for (camera and screenshare). 

Can you confirm if that is the case here? 

We also have a React App where Screen Share is functional. See [here](https://github.com/twilio/twilio-video-app-react).

Thanks,
Joyce

**Comment by anderjs** [comment]
@PikaJoyce OMG! I didn't see that. But I understand now how it videoTracks works, thank you so much PikaJoyce, god bleess you. It works perfect now. You can close the issue. Maybe I can read a great article coming soon about that.

**Comment by PikaJoyce** [comment]
You're very welcome @anderjs! 

I'm glad this helped! I'll be closing this issue now, feel free to open another issue or simply comment on this issue if any further issues arise. Thank you!

We are looking forward to see what you build! 

Best, 
Joyce
