### ISSUE TITLE
I'm sure its just me, but I'm really stuck: iOS device using twilio video 2.7 not sending its video

### ISSUE THREAD

**Issue by steeleauto** [twilio/twilio-video.js#1124]
Hi, I'd like to first say, I'm not much of a programmer so please don't overlook the very obvious... as I may have missed it. :)

First I'm not using node or react or anything. Just jquery/php and the twilio video 2.7, and all works fine except when I join a room or someone joins the room and I'm already there. I don't see their video if that person is using iOS device.

Below I get the token (passing a vehicle repair ID for a room name since its unique)
I receive the token, I can confirm I connect to the room, see my local video preview.

If someone connects into the room using iOS, or I join the room and they are already connected, I can hear them fine, but their video isn't coming in to me it's just a black screen, though they can see my video as long as I'm not using an iOS device. 

Its like the iOS device isn't sending/publishing its video. If android phone connecting I get their video fine. Or if I connect on a desktop device all is fine.

The console log shows they are connecting/connected fine.
That the other party is already in the room or joining the room and is connected etc. no problem
I hear the audio regardless
Just if the user is on iOS, I don't see their video.

I'm really stuck so hoping someone can shed some light on what I'm doing wrong.

`
 $.ajax({
        url:"/video/token/" + $('#repair_id').val() + "",
        type:'GET',
        success: function(data) { // receiving the token back with the predefined room
        const { connect, createLocalVideoTrack } = Video;
        connect(data,{
        audio:true,
        video:true
        }).then(room => {

        const videoChatWindow = document.getElementById('local-media');

        createLocalVideoTrack().then(track => {
            videoChatWindow.appendChild(track.attach());
        });

        // Log your Client's LocalParticipant in the Room
        const localParticipant = room.localParticipant;
        console.log(`Connected to the Room as LocalParticipant "${localParticipant.identity}"`);

        // Log any Participants already connected to the Room
        room.participants.forEach(participant => {
            console.log(`Participant "${participant.identity}" is connected to the Room`);
        });

        // Log new Participants as they connect to the Room
        room.once('participantConnected', participant => {
            console.log(`Participant "${participant.identity}" has connected to the Room`);
        });

        // Log Participants as they disconnect from the Room
        room.once('participantDisconnected', participant => {
            console.log(`Participant "${participant.identity}" has disconnected from the Room`);
        });

        console.log('Connected to Room "%s"', room.name);

        room.participants.forEach(participantConnected);
        room.on('participantConnected', participantConnected);

        room.on('participantDisconnected', participantDisconnected);
        room.once('disconnected', error => room.participants.forEach(participantDisconnected));

        });

        function participantDisconnected(participant) {
            console.log('Participant "%s" disconnected', participant.identity);
            document.getElementById(participant.sid).remove();
            }

        function participantConnected(participant) {
            console.log('Participant "%s" connected', participant.identity);

            const div = document.createElement('div');
            div.id = participant.sid;

            participant.on('trackSubscribed', track => trackSubscribed(div, track));
            participant.on('trackUnsubscribed', trackUnsubscribed);

            participant.tracks.forEach(publication => {
                if (publication.isSubscribed) {
                trackSubscribed(div, publication.track);
            }
            });

            document.getElementById('remote-media-div').appendChild(div);

        }

        function trackSubscribed(div, track) {
            div.appendChild(track.attach());
        }

        function trackUnsubscribed(track) {
            track.detach().forEach(element => element.remove());
        }

} // success
`

**Comment by manjeshbhargav** [comment]
Hi @steeleauto ,

When you call `connect({ audio: true, video: true })`, the SDK creates its own video track. Now, when you create a second video track using `createLocalVideoTrack()` for your local preview, the first video track gets muted (iOS Safari allows only one camera track). So, instead of creating a second video track, you can use the first video track for preview as follows:
```js
const localVideoTrack = Array.from(room.localParticipant.videoTracks.values())[0].track;
videoChatWindow.appendChild(localVideoTrack.attach());
```
Please let me know if this helps. I will close this issue since I've answered your question. However, we can continue the conversation here.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by steeleauto** [comment]
I tried but I'm missing something. I'm getting this:
Uncaught (in promise) TypeError: videoChatWindow is null

Added it as below
`
const { connect, createLocalVideoTrack } = Video;
        connect(data,{
        audio:true,
        video:true
        }).then(room => {
        
        const videoChatWindow = document.getElementById('local-media');

        const localVideoTrack = Array.from(room.localParticipant.videoTracks.values())[0].track;
        videoChatWindow.appendChild(localVideoTrack.attach());
`

I've got to be getting close. I was about to finally give up so you're response is a breath of fresh air. Thank you in advance!

**Comment by steeleauto** [comment]
OMG thank you a thousand times over!! I've been suffering on this for days and was about to give up.
I dropped that in and voila... it worked. Thought I was going to cry lol
I really needed the help. thanks!!
