### ISSUE TITLE
Room event disconect after 30 seconds reconnection

### ISSUE THREAD

**Issue by MBlanpe** [twilio/twilio-video.js#1125]
Version 2.7.1
Room Reconnection States and Events problem.
The room is disconnected if they spend 30 seconds in the reconnecting state, can that time be changed?
Less than 30 seconds, reconnection is done without problem.
Is this normal time?
Thanks.

**Comment by manjeshbhargav** [comment]
Hi @MBlanpe ,

As of now, the 30 seconds timeout cannot be changed at this time. It is a limit set by our back-end server. Hope this answers your question.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by MBlanpe** [comment]
Thanks you.
