### ISSUE TITLE
Video.isSupported should return true on Microsoft Edge 44.19041.1.0

### ISSUE THREAD

**Issue by papuruth** [twilio/twilio-video.js#1129]
- [  * ] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [  *  ] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [  *  ] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [  *  ] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Expected behavior:**
Video.isSupported should return true on Microsoft Edge 44.19041.1.0

**Actual behavior:**
Video.isSupported returns false on Microsoft Edge 44.19041.1.0

**Software versions:**

 - [ * ] Browser(s): Microsoft Edge 44.19041.1.0
 - [ * ] Operating System: Windows 10
 - [ * ] twilio-video.js:  2.7.1
 - [ * ] Third-party libraries (e.g., Angular, React, etc.): React

**Comment by anna-vasilko** [comment]
Hi @papuruth,
Thanks for reaching out.
Video.isSupported should return true only for browsers officially supported by Twilio.
Microsoft Edge 44 is a legacy Edge, which is not officially supported by Twilio Video. We support only Chromium based Microsoft Edge (versions 79 and up)

I am going to close this ticket. Let us know if you have more questions
