### ISSUE TITLE
Triggering statusCallbacks

### ISSUE THREAD

**Issue by jamesgraham** [twilio/twilio-video.js#113]
Hi,

We are using the new Rooms api- so far so good. We are unsure of which conditions create the following 2 [events](https://www.twilio.com/docs/api/video/status-callbacks#status-callback-events):

- track-removed
- room-ended

Which JS methods should we call to cleanly remove a track and generate that `track-removed` event?

Does a room end when it has no tracks or is "completed" by API?

**Comment by markandrus** [comment]
Hi @jamesgraham,

> * track-removed

This should fire whenever a previously-added LocalTrack (either added by way of [`tracks` in ConnectOptions](http://media.twiliocdn.com/sdk/js/video/releases/1.0.0/docs/global.html#ConnectOptions) or by calling [`addTrack`](http://media.twiliocdn.com/sdk/js/video/releases/1.0.0/docs/LocalParticipant.html#addTrack__anchor) once connected to a Room) is removed with [`removeTrack`](http://media.twiliocdn.com/sdk/js/video/releases/1.0.0/docs/LocalParticipant.html#removeTrack__anchor).

> * room-ended

This fires when all Participants disconnect from a Room (via `disconnect`) or if the Room is [completed via the REST API](https://www.twilio.com/docs/api/video/rooms-resource#complete-room). When ending a Room, "All connected Participants will be immediately disconnected from the Room."

> Which JS methods should we call to cleanly remove a track and generate that track-removed event?

[`removeTrack`](http://media.twiliocdn.com/sdk/js/video/releases/1.0.0/docs/LocalParticipant.html#removeTrack__anchor)

> Does a room end when it has no tracks or is "completed" by API?

When all Participants have disconnected (which can be forced via the REST API—see above).

Here's a log I captured of the Status Callback events for a single-Participant Room. In this example, I connected to a Room, removed one of my Tracks, and added it back. (Note that we're missing "track-added" events for the Tracks the Participant initially connected with—this is a bug we are currently fixing).

```js
{ RoomStatus: 'in-progress',
  RoomSid: 'RM6b154bf694591033ea4c857ffb4cd1e6',
  RoomName: 'xxx',
  SequenceNumber: '0',
  StatusCallbackEvent: 'room-created',
  Timestamp: '2017-05-17T17:31:58.125Z',
  AccountSid: 'ACcd224d70006373d9b37eb3202c52df90' }
{ RoomStatus: 'in-progress',
  RoomSid: 'RM6b154bf694591033ea4c857ffb4cd1e6',
  RoomName: 'xxx',
  ParticipantStatus: 'connected',
  ParticipantIdentity: 'HolyLandoTulsa',
  SequenceNumber: '1',
  StatusCallbackEvent: 'participant-connected',
  ParticipantSid: 'PA5fb92377c7403b8e727c5e9dde9fcbb9',
  Timestamp: '2017-05-17T17:31:58.125Z',
  AccountSid: 'ACcd224d70006373d9b37eb3202c52df90' }
{ RoomStatus: 'in-progress',
  RoomSid: 'RM6b154bf694591033ea4c857ffb4cd1e6',
  RoomName: 'xxx',
  ParticipantStatus: 'connected',
  ParticipantIdentity: 'HolyLandoTulsa',
  SequenceNumber: '2',
  StatusCallbackEvent: 'track-removed',
  ParticipantSid: 'PA5fb92377c7403b8e727c5e9dde9fcbb9',
  Timestamp: '2017-05-17T17:32:10.058Z',
  AccountSid: 'ACcd224d70006373d9b37eb3202c52df90' }
{ RoomStatus: 'in-progress',
  RoomSid: 'RM6b154bf694591033ea4c857ffb4cd1e6',
  RoomName: 'xxx',
  ParticipantStatus: 'connected',
  ParticipantIdentity: 'HolyLandoTulsa',
  SequenceNumber: '3',
  StatusCallbackEvent: 'track-added',
  ParticipantSid: 'PA5fb92377c7403b8e727c5e9dde9fcbb9',
  Timestamp: '2017-05-17T17:32:20.700Z',
  AccountSid: 'ACcd224d70006373d9b37eb3202c52df90' }
{ RoomStatus: 'in-progress',
  RoomSid: 'RM6b154bf694591033ea4c857ffb4cd1e6',
  RoomName: 'xxx',
  ParticipantDuration: '123',
  ParticipantStatus: 'disconnected',
  ParticipantIdentity: 'HolyLandoTulsa',
  SequenceNumber: '4',
  StatusCallbackEvent: 'participant-disconnected',
  Timestamp: '2017-05-17T17:34:01.232Z',
  ParticipantSid: 'PA5fb92377c7403b8e727c5e9dde9fcbb9',
  AccountSid: 'ACcd224d70006373d9b37eb3202c52df90' }
{ RoomStatus: 'completed',
  RoomSid: 'RM6b154bf694591033ea4c857ffb4cd1e6',
  RoomName: 'xxx',
  RoomDuration: '123',
  SequenceNumber: '5',
  StatusCallbackEvent: 'room-ended',
  Timestamp: '2017-05-17T17:34:01.232Z',
  AccountSid: 'ACcd224d70006373d9b37eb3202c52df90' }
```

**Comment by jamesgraham** [comment]
Hey @markandrus, can you check we we don't get any track or participant events for this room?

`RM1719594e076e70d7cc1c1a91caad1837`

**Comment by jamesgraham** [comment]
Thanks Mark
