### ISSUE TITLE
Android 11 Beta - RTCPeerConnection never emits ICE Candidates on Chrome

### ISSUE THREAD

**Issue by nbjames2** [twilio/twilio-video.js#1133]
- [X ] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [X ] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [X ] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [X ] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

Found a bug in Chrome on the Android 11 beta where RTCPeerConnection never emits ICE candidates so a video/audio connection cannot be established through webRTC. For more info I have create bug report on chrome here:
https://bugs.chromium.org/p/chromium/issues/detail?id=1115068

For a clear demonstration of this go to  https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/ on android 11 beta, or try https://appr.tc (on android 11 as well).

Is there any work around that we could use in the meantime?

**Comment by manjeshbhargav** [comment]
@nbjames2 ,

Thanks for reporting this issue. Unfortunately, there are no workarounds for this issue, because without ICE candidates WebRTC will not establish a media connection. Having said that, I will make sure to bring this to the attention of our contact in the Chromium engineering team.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by fippo** [comment]
This should be fixed: https://bugs.chromium.org/p/chromium/issues/detail?id=1115498

**Comment by manjeshbhargav** [comment]
@fippo ,

Thanks for the notification. I will close this issue now.
