### ISSUE TITLE
Flip Camera doesn't work on S20+ and S20 Ultra android v10 devices

### ISSUE THREAD

**Issue by PradeepaJey1** [twilio/twilio-video.js#1136]
- [ ] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [X] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ ] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [X] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Problem**

The flip camera doesn't work on S20+ and S20 Ultra devices (android v10). In the first load, the video appears but when the flip camera button is clicked the application throws an error.

But this doesn't happen in other android v10 devices.

The S20+ and S20 Ultra have 5 video inputs, therefore I doubt if that raises the issue.

![image](https://user-images.githubusercontent.com/32606884/90094803-8bbe9f00-dd4c-11ea-99bf-225dc377b7c2.png)

**Code to reproduce the issue:**
```js
Video.createLocalVideoTrack({
        facingMode: dataManager.isForwardCameraSelected() ? 'user' : 'environment',
        name: 'camera',
}).then(newTrack => {
        console.log('new track created')
        setTrack(newTrack);
        return newTrack;
}),
```
**Expected behavior:**

The camera should be flipped (environment)

**Actual behavior:**

It throws the following error:

![image](https://user-images.githubusercontent.com/32606884/90095043-2dde8700-dd4d-11ea-98b3-2ffeadabb83b.png)

**Software versions:**

 - [X] Browser(s): Chrome 
 - [X] Operating System: Android, v10 (Galaxy S20+ and Galaxy S20 Ultra)
 - [X] twilio-video.js: 2.7.0
 - [X] Third-party libraries (e.g., Angular, React, etc.): React

**Comment by Debson** [comment]
Noticed that issue a few months back on S20+ and S20 Ultra. Couldn't figure a workaround. Would be great to know what causes it.

**Comment by charliesantos** [comment]
This seems to be the same issue as https://github.com/twilio/twilio-video.js/issues/1180. Please check out the fix. I'll close this now but feel free to follow up here.

**Comment by PradeepaJey1** [comment]
Hi @charliesantos 

This issue still exists on some devices
Example: Galaxy S21 Android 11 Chrome

Could you please give an update?
![image](https://user-images.githubusercontent.com/32606884/144173961-1fd45f5c-b7fe-4304-ace2-e90965b006fd.png)
