### ISSUE TITLE
Changing Camera Ipad -- Duplicate Tracks Error

### ISSUE THREAD

**Issue by mfharding** [twilio/twilio-video.js#1138]
When I change the input on the camera and restart the track per the recommendations of the documentation, I get the duplicate tracks error. Is there something that I am missing in the documentation or is there an error where twilio video is not properally killing the first track, before making the new one?

**Code to reproduce the issue:**

Code that tracks change in the input selected by user
```
  useEffect(() => {
    if (pickedVideoInput?.deviceId && localParticipant) {
      console.log('changing the video input device!', {
        deletedTrack: videoTrack,
      });
      const tracks = Array.from(localParticipant.tracks.values())
        .filter((track: any) => track.kind === 'video')
        .map(publication => publication.track);
      console.log({tracks});
      if (tracks?.[0]) {
      const localVideoTrack = tracks?.[0];
       localVideoTrack.restart({
            frameRate: 24,
            height: 720,
            width: 1280,
            name:
              pickedVideoInput?.deviceId + pickedVideoInput?.label || 'camera',
            deviceId: pickedVideoInput?.deviceId || null,
          });
    }
  }, [pickedVideoInput?.deviceId]);
```

**Expected behavior:**
Restart the video with the new track

**Actual behavior:**
Duplicate track error 70% of the time, correct behavior half the time

**Software versions:**

 - [ ] Browser(s): IPad
 - [ ] Operating System: IOS - Safari (Which is supported)
 - [ ] twilio-video.js:
 - [ ] Third-party libraries: React.js (Built from starter project)

**Comment by makarandp0** [comment]
Hello @mfharding, 

Thank you for writing about this issue. Where do you see "duplicate tracks" error - is this something printed on console or is this an error that promise returned by `restart`  rejects with? I would like to investigate further - Can you share room-sid, participant-sid and logs from the browser console when you see such error ? 

One thing I noticed from your code is you are not waiting for the promise returned by `localVideoTrack.restart` - Does the repro involve calling restrart again while previous promise is pending?

Thanks,
Makarand

**Comment by makarandp0** [comment]
Hello @mfharding,  We have not heard from you and I am closing this old ticket. If you still seeing this issue, please reopen new ticket. 
Thanks,
Makarand
