### ISSUE TITLE
Detecting when a participant has subscribed to localParticipant datatrack

### ISSUE THREAD

**Issue by athollon** [twilio/twilio-video.js#1139]
## Context

We are powering a 3D web application similar to Hubs : https://hubs.mozilla.com/
In a given 3D environment, users can have a multiplayer experience talking and seeing each other as avatars which can move/rotate/...

## Technical overview

We are relying on aframe a web framework to build VR experiences, and networked-aframe a framework to build multi-users experience on top of aframe.

We have implemented a networked-aframe adapter which uses twilio-video to:
- allow audio communication through AudioTrack
- avatar networking through DataTrack

## Current issue

We have two steps to network avatar, given a player 1 (P1) point of view:

1. When P1 detects that he is "connected" to a new player (called P2), P1 sends to P2 all sync information for P2 to instantiate P1 avatar in its browser
2. P1 continuously sends partial update information to all its subscribers

I have an issue with part 1: "**connected**" means that a two-way communication have been established between P1 and P2. In my understanding, with twilio, in P1 browser it is only possible to determine that P1 has subscribed to P2 datatrack but we don't know if P2 is receiving data from P1, which is my issue here.

I have developed a simple but error-prone protocol to ensure that P1 and P2 can communicate in both way, but is it possible to do it more easily ? 

Thank for your help!

**Comment by makarandp0** [comment]
Thank you for writing about this @athollon 

Idea of using video avatars in 3d environment sounds very interesting. Would love to see the product when its ready.

Unfortunately I can't think of a way to know if other participant has subscribed to data channel. As you mention some application protocol, something like - P1 sends initial avatar periodically to P2, and stops sending it when it gets ack from P2 and then onwards only sends update - would be the way to go.


Thanks,
Makarand

**Comment by makarandp0** [comment]
Hey @athollon, I am closing this old issue.
regards,
Makarand
