### ISSUE TITLE
Cannot resolve './Grammar/dist/Grammar'

### ISSUE THREAD

**Issue by cyorobert** [twilio/twilio-video.js#114]
This issue is related to #46 . I get the following error:

```
Module not found: Error: Can't resolve './Grammar/dist/Grammar' in '/path/to/project/node_modules/sip.js/src'
```

When installing via npm I get the following error:

```
sip.js@0.7.5 postinstall: `cd src/Grammar && mkdir -p dist && pegjs --extra-options-file peg.json src/Grammar.pegjs dist/Grammar.js`
Failed at the sip.js@0.7.5 postinstall script
```

This is how twilio-video appears like this in my package.json file

```json
"dependencies": {
    "twilio-video": "^1.0.0"
}
```

I've tried uninstalling and re-installing twilio-video and using npm instead of yarn. I've also verified in `/node_modules/sip.js/Grammar` there is no dist folder. The package was working just fine for me yesterday, so this is strange.

**Expected behavior:**

Modules build successfully and can't find all dependencies

**Actual behavior:**
Building modules fails because Grammar doesn't have a dist folder.

**Software versions:**

 - [x] Browser(s): Google Chrome
 - [x] Operating System: Mac OSX
 - [x] twilio-video.js: ^1.0.0
 - [x] Third-party libraries (e.g., Angular, React, etc.): React.js + Redux.js

**Comment by cyorobert** [comment]
Looks like the problem was pegjs. Once I installed pegjs everything worked. Closing.

**Comment by Emobe** [comment]
I had this issue and installing sip.js worked for me instead
