### ISSUE TITLE
IndexSizeError thrown from detectSilentVideo

### ISSUE THREAD

**Issue by garrettreed** [twilio/twilio-video.js#1142]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

We are intermittently seeing the following uncaught error: `IndexSizeError: The index is not in the allowed range.`

This is a result of the `drawImage` call in `lib/util/detectsilentvideo.js`. We have only seen this happen on Safari v13.1.2 and is possibly restricted to iOS. We cannot reliably replicate, though it should be thrown [If the canvas or source rectangle width or height is zero](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage#Exceptions_thrown).

**Software versions:**

 - [x] Browser(s): Safari 13.1.2
 - [x] Operating System: iOS 13.6 and Mac OS X 10.15.4 (possibly iPad using desktop user agent)
 - [x] twilio-video.js: v2.7.2
 - [x] Third-party libraries (e.g., Angular, React, etc.): React v16.13.1

**Comment by makarandp0** [comment]
Thank you for reporting this issue @garrettreed. It's not clear to me what is causing this, but since the error is documented (and possible), we should handle it in `drawImage`. I have filed a bug to track this issue (JSDK-2965)

**Comment by makarandp0** [comment]
I am closing this old issue - we do have corresponding ticket open (VIDEO-3608)
