### ISSUE TITLE
[Question] How detectsilentvideo.js will work?

### ISSUE THREAD

**Issue by kumail-raza** [twilio/twilio-video.js#1146]
https://github.com/twilio/twilio-video.js/blob/aef53ccde2b9b53492ed6c9cd5626b09b0c5e62a/lib/util/detectsilentvideo.js#L19

I just came across with this utility to detect the silent video, just to have more understanding with the algorithm you guys are using here to detect if video is silent or not.

Its seems you guys are checking movement of a user and audio being muted in that timeframe?

**Comment by makarandp0** [comment]
Hello @kumail-raza, 

This utility and few others were introduced as a way to workaround various media issues seen on Safari on iOS. We have seen that when application gets backgrounded / foregrounded on IOS safari, sometimes the audio/video tracks become unusable.  The sdk uses such checks to determine if the media stream need to be reacquired. We are hoping to retire such checks once we get fixes for these ios safari issues. 

Thanks,
Makarand

**Comment by makarandp0** [comment]
closing this issue now.
