### ISSUE TITLE
[Question] What if room created but no user published the stream?

### ISSUE THREAD

**Issue by kumail-raza** [twilio/twilio-video.js#1149]
@manjeshbhargav @philnash 

A quick question

Will room creation take up penny? Or Twilio costing started when user join and published the track?

**Comment by philnash** [comment]
@kumail-raza according to [the pricing page](https://www.twilio.com/video/pricing), you only get charged per participant per minute. If there are no participants in a room, then there is no charge.

**Comment by donaltoomey** [comment]
@kumail-raza, the charge starts when a participant connects to the Room.

**Comment by makarandp0** [comment]
@kumail-raza  closing this issue now, please reopen if you further questions.
