### ISSUE TITLE
video chat not connect on safari 13 mac

### ISSUE THREAD

**Issue by rajesh-smartwebtech** [twilio/twilio-video.js#1150]
hello @paynerc 

There are lot of try but video js  not working  on mac safari 13 
both user one connected on google chrome and safari but safari throw error 
i am using https connection 

```Video.isSupported``` method return true on safari 
```
2020-08-20 – "12:20:19.636Z" – "|" – "WARN" – "in" – "[createLocalTracks #1]:" – "Call to getUserMedia failed:"
OverconstrainedError
```
so why error for getUserMedia  ? 

js cdn using
https://media.twiliocdn.com/sdk/js/video/releases/2.5.0/twilio-video.min.js

following image in error  
![image](https://user-images.githubusercontent.com/35251001/90770442-6c58e080-e30f-11ea-8da2-0471ca0b399c.png)

Thank you

**Comment by makarandp0** [comment]
Hello @rajesh-smartwebtech, Thank you for writing about your issue.

[OverconstrainedError](https://developer.mozilla.org/en-US/docs/Web/API/OverconstrainedError) indicates that the constraints specified for getUserMedia call were not valid for this platform. For video the constraints are determined by `video` property of [connectOptions](https://media.twiliocdn.com/sdk/js/video/releases/2.7.2/docs/global.html#ConnectOptions) that you passed to [Video.connect](https://media.twiliocdn.com/sdk/js/video/releases/2.7.2/docs/module-twilio-video.html#.connect__anchor) or [createLocalTracks](https://media.twiliocdn.com/sdk/js/video/releases/2.7.2/docs/module-twilio-video.html#.createLocalTracks__anchor) call.

Can you post the constraints you are specifying for those calls? You can also try [this sample](https://webrtc.github.io/samples/src/content/peerconnection/constraints/) on the device to see which constraints work. 

Let me know if that helps,
Thanks,
Makarand

**Comment by makarandp0** [comment]
@rajesh-smartwebtech, I tried the constraints you specified on Safari on Mac, and was able to get the media stream. I wrote a quick sample to try various video constraints, Can you try this: 
https://makarandp0.github.io/videoconstraints.html
and see if see the issue with the constraints you specified?

**Comment by makarandp0** [comment]
Hello @rajesh-smartwebtech, I am closing this old issue. Please reopen if you are still seeing issue  with those constraints.
Thanks,
Makarand
