### ISSUE TITLE
Chrome Android Simulcast + dimensions constraints yields row alignment rendering issues when other layers are selected

### ISSUE THREAD

**Issue by ryango** [twilio/twilio-video.js#1153]
By specifying a height constraint of 720 and VP8 simulcast, secondary layers from Pixel 3 Chrome are not rendered properly by iOS SDK, Safari, Chrome on Mac.

This is specific to when the playback has selected a lower resolution plane. Unfortunately it seems mobile devices even on gigabit wifi tend to select lower resolutions very frequently.

Code
```
    const tracks = await Video.createLocalTracks({
      video: {height: 720, frameRate: 30},
      maxAudioBitrate: 192000,
      maxVideoBitrate: 3000000,
      audio: true
    });
```

```
    const connectOptions = {
      name: connectResponse.roomSid,
      logLevel: 'error',
      tracks: [],
      preferredVideoCodecs: [{ codec: 'VP8', simulcast: true }],
    };
```
iOS VideoView rendering the track
![IMG_0570](https://user-images.githubusercontent.com/1054881/91356037-0233b600-e7bd-11ea-85f0-06b1bb5890a3.png)

iOS Safari video element
![IMG_0012](https://user-images.githubusercontent.com/1054881/91356064-0c55b480-e7bd-11ea-96c0-b04b2dc3fd66.png)

Mac Chrome video element
<img width="1288" alt="mac" src="https://user-images.githubusercontent.com/1054881/91356086-14adef80-e7bd-11ea-973e-eaefde6a38f7.png">

**Comment by makarandp0** [comment]
Hello @ryango, Thank you for writing about this issue. Unfortunately this is a known issue on Pixel 3 devices, and a workaround is to not use vp8 as on such device. 
```
if ( mobileModel === 'Pixel 3') { // you would need to detect mobile model
  connectionOptions.preferredVideoCodecs = ['H264'];
} else {
  connectionOptions.preferredVideoCodecs = [{ codec: 'VP8', simulcast: true }];
}
```

Let me know if that helps. 
Thanks,
Makarand

**Comment by ryango** [comment]
Ok thanks!
