### ISSUE TITLE
Error's in peer-to-peer room

### ISSUE THREAD

**Issue by PimentaLucas** [twilio/twilio-video.js#1156]
Hello, i'm getting this error after i join the peer-to-peer room in Chrome: 
Uncaught` (in promise) TwilioError: Client is unable to apply a remote media description

I'm also getting another error that happens when the second user joins the room:
peerConnection[getStreams] is not a function

This is the code that i'm using to join the room and receive the streams from the other participant

```
const room = await Video.connect(
      "accessToken",
      {
        name: "consulta5f2c5968265e4e3f50f701f3",
        audio: true,
        video: { width: 640 },
      }
    );
    room.participants.forEach((participant) => {
      participant.tracks.forEach((publication) => {
        if (publication.track) {
          document
            .getElementById("remote-media-div")
            .appendChild(publication.track.attach());
        }
      });

      participant.on("trackSubscribed", (track) => {
        document.getElementById("remote-media-div").appendChild(track.attach());
      });
    });
```

Thanks in advice.

**Comment by makarandp0** [comment]
Thank you for writing about this issue @PimentaLucas,

Are you using angular framework by any chance - There is a known issue with angular described [here](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md#angular). 

If that does not fix it, Please provide more details - any room-sids and client side console logs would be very helpful. You can fill in following template for more details:

 - [ ] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [ ] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ ] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [ ] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**



```js
// TODO
```

**Expected behavior:**

TODO

**Actual behavior:**



TODO

**Software versions:**

 - [ ] Browser(s):
 - [ ] Operating System:
 - [ ] twilio-video.js:
 - [ ] Third-party libraries (e.g., Angular, React, etc.):

**Comment by PimentaLucas** [comment]
```
    // Attach the Tracks to the DOM.
    attachTracks(tracks, container) {
      tracks.forEach((publication) => {
        if (publication.isSubscribed) {
          const track = publication.track;
          container.appendChild(track.attach());
        }
      });
    },

    // Attach the Participant's Tracks to the DOM.
    attachParticipantTracks(participant, container) {
      let tracks = participant.tracks;
      this.attachTracks(tracks, container);
      console.log(participant);
    },

    // Detach the Tracks from the DOM.
    detachTracks(tracks) {
      tracks.forEach((track) => {
        track.detach().forEach((detachedElement) => {
          detachedElement.remove();
        });
      });
    },

    // Detach the Participant's Tracks from the DOM.
    detachParticipantTracks(participant) {
      let tracks = participant.tracks;
      this.detachTracks(tracks);
    },

    // Leave Room.
    leaveRoomIfJoined() {
      if (this.activeRoom) {
        this.activeRoom.disconnect();
      }
    },

    // Create a new chat
    connectChat() {
      const VueThis = this;
      const Video = Twilio.Video;
      console.log(Video);
      Video.connect(
        "accessToken",
        {
          name: "consulta5f2c5968265e4e3f50f701f2",
          audio: true,
          video: { width: 640 },
        }
      )
        .then((room) => {
          console.log(`Successfully joined a Room: ${room}`);
          console.log(room);
          room.participants.forEach(function (participant) {
            let previewContainer = document.getElementById("remoteTrack");
            VueThis.attachParticipantTracks(participant, previewContainer);
          });
          room.on("participantConnected", function (participant) {
            consoole.log("Joining: '" + participant.identity + "'");
          });
          room.on("trackAdded", function (track, participant) {
            console.log(participant.identity + " added track: " + track.kind);
            let previewContainer = document.getElementById("remoteTrack");
            VueThis.attachTracks([track], previewContainer);
          });
          room.on("trackRemoved", function (track, participant) {
            consoole.log(
              participant.identity + " removed track: " + track.kind
            );
            VueThis.detachTracks([track]);
          });
          room.on("participantDisconnected", function (participant) {
            consoole.log(
              "Participant '" + participant.identity + "' left the room"
            );
            VueThis.detachParticipantTracks(participant);
          });
        })
        .catch((erro) => {
          console.log(erro);
        });
    },

```
Expected behavior:

Video and voice peer-to-peer conection working

Actual behavior:

```
41twilio-video.min.js:54 Uncaught TypeError: peerConnection[getStreams] is not a function
    at getTracks (twilio-video.min.js:54)
    at _getStats (twilio-video.min.js:54)
    at getStats (twilio-video.min.js:54)
    at PeerConnectionV2.getStats (twilio-video.min.js:46)
    at twilio-video.min.js:46
    at Array.map (<anonymous>)
    at PeerConnectionManager.getStats (twilio-video.min.js:46)
    at RoomV2.getStats (twilio-video.min.js:47)
    at twilio-video.min.js:47
```

Software versions:

 Browser(s): Chrome  85.0.4183.83
 Operating System: Windows 10
 twilio-video.js: 2.7.2
 Third-party libraries (e.g., Angular, React, etc.): Vue.js

**Comment by makarandp0** [comment]
Hey @PimentaLucas thank you for the information,  

 `Uncaught TypeError: peerConnection[getStreams] is not a function` seem to indicate that twilio-video did not find [some functions](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/getReceivers) that it was expecting from RTCPeerConnection. This should not happen on Chrome 85.

are you using any  polyfill libraries ? if you have your app hosted somewhere, I can take a quick look and see what is going on.

Thanks,
Makarand

**Comment by makarandp0** [comment]
Hey @PimentaLucas, I am closing this old ticket, please reopen if you are still seeing this issue.
Thanks,
Makarand
