### ISSUE TITLE
Settings for incoming video resolution

### ISSUE THREAD

**Issue by av-k** [twilio/twilio-video.js#116]
Hi all!
How can I change the settings for incoming data? Could not find the change dimensions for [VideoTrack](https://media.twiliocdn.com/sdk/js/video/releases/1.0.0/docs/VideoTrack.html).

**Comment by markandrus** [comment]
Hi @av-k,

Currently, the size of a VideoTrack _received_ by any particular Participant matches the size of the LocalVideoTrack _sent_. So the only control for setting the dimensions of a VideoTrack are those which can be specified when calling `createLocalTracks` or `createLocalVideoTrack` (see https://github.com/twilio/twilio-video.js/issues/47 for more info). In the future, when we support simulcast/SVC, we may allow you to choose, e.g., a lower resolution; but this is not support yet.

Mark

**Comment by markandrus** [comment]
@av-k closing this issue for now, since i think you're issue may have been solved? if not, feel free to re-open.

thanks,
mark

**Comment by kashid16** [comment]
Is it now possible to set different dimesions for local and remote video track?
