### ISSUE TITLE
How we can get room info without token? 

### ISSUE THREAD

**Issue by manprajapat** [twilio/twilio-video.js#1160]
I need to know weather room is full of 2 people, then 3rd person will not be asked for video access and not to be listed in remote participants, He can see their video chat only. 
Is there any hack of this?

**Comment by makarandp0** [comment]
Hello @manprajapat, I am not sure if I understand your question correctly. But If you want to query participants in room w/o joining it you can use our [rest api ](https://www.twilio.com/docs/video/api/rooms-resource#get-by-unique-name)

let me know if that helps,
Thanks,
Makarand

**Comment by kunalnagar** [comment]
@manprajapat I was digging around for similar info. I think what OP is trying to ask is that the `twilio-video` package currently has no way of querying rooms info (nothing that I could find as well).

**Comment by manprajapat** [comment]
hmm, I was thinking the same. Anyways, it is good repo for learning as well.

**Comment by makarandp0** [comment]
Looks like this question is answered - closing this old issue.
Thanks,
Makarand
