### ISSUE TITLE
Sound issue with chrome 85

### ISSUE THREAD

**Issue by beeeemster** [twilio/twilio-video.js#1161]
- I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 -  I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

Unable to share the code.

**Expected behavior:**

Users can hear each other.

**Actual behavior:**

Users on chrome 85 cannot hear other users. Users not on chrome 85 cannot hear users on chrome 85.

TODO

**Software versions:**

 - [ ] Browser(s): Chrome 84,85 & Canary
 - [ ] Operating System: Windows, Mac & Linux
 - [ ] twilio-video.js: 2.7.2
 - [ ] Third-party libraries (e.g., Angular, React, etc.): React Redux Saga

**Comment by makarandp0** [comment]
Hey @beeeemster, I see this issue is duplicated as https://github.com/twilio/twilio-video.js/issues/1158 - I am closing this as we discuss more about this in https://github.com/twilio/twilio-video.js/issues/1158
