### ISSUE TITLE
Is there a way to list video calls with their information? 

### ISSUE THREAD

**Issue by zunnurainbadar** [twilio/twilio-video.js#1166]
Hi,

I am trying to display list of all my calls with their basic information in my dashboard. Is there a way to do that? Is there any API available to achieve that? I didn't find anything about that in the docs?

thanks.

**Comment by DaniyalBasit** [comment]
https://www.twilio.com/docs/video/api/rooms-resource

**Comment by zunnurainbadar** [comment]
Can you please be more specific? I need to find an api which lists all my calls in a room

**Comment by DaniyalBasit** [comment]
Dude, do some effort and read that doc. It has the API you’re looking for.
