### ISSUE TITLE
Unhandled Promise Rejection: Error: getUserMedia is not supported in Cordova iOS App

### ISSUE THREAD

**Issue by Sajanrav01** [twilio/twilio-video.js#1168]
I have tried Twilio Vide Chat in React +Cordova App.

React JS App is working as excepted in All Mac Browsers(Chrome,Firefox,Safari) ,ie Camera is coming up and able to start Video chat.

Also working in iPhone safari browser after making http://lochalhost into  https://lochalhost .

After that i have tried to put React JS Application inside Cordova iOS Plugin,suddenly it stopped Working  and getting error 

**'Unhandled Promise Rejection: Error: getUserMedia is not supported'** after fetching access token.Please help me out of this problem.Thanks in advance.

<img width="360" alt="Screen Shot 2020-09-08 at 11 43 47 PM" src="https://user-images.githubusercontent.com/2862745/92514821-3339cf00-f230-11ea-8659-7364fb90cc85.png">
<img width="591" alt="Screen Shot 2020-09-08 at 11 43 21 PM" src="https://user-images.githubusercontent.com/2862745/92514899-52d0f780-f230-11ea-9635-f3d28d28a88d.png">

**Software versions:**

 - [ ] Browser(s):
 - [ ] Operating System:
 - [ ] twilio-video.js:
 - [x] Third-party libraries ( React,Cordova etc.):

**Comment by PikaJoyce** [comment]
Hi @Sajanrav01,

Thank you for submitting this issue. twilio-video.js currently supports the following [browsers and platforms](https://www.twilio.com/docs/video/javascript#supported-browsers). On iOS11/12 navigator.getMediaDevices is not available for WKWebView and UIWebView. It is only available for Safari: [thread](https://forums.developer.apple.com/thread/88052). However, SFSafariViewController got WebRTC support in iOS 13.0. 

You may need to use an alternative library ([example](https://github.com/cordova-rtc/cordova-plugin-iosrtc)) that allows for iOS + WebRTC Support. 

I hope this helps. 

Best,
Joyce
