### ISSUE TITLE
MediaStreams and Hark

### ISSUE THREAD

**Issue by Samenai** [twilio/twilio-video.js#117]
Hi All

We are starting to migrate our beta4 implementation of Twilio Video to the latest but it looks like there was a change to remove MediaStreams from participants.

Unfortunately, we had used those for a Hangouts/Skype-like switching view or highlighting of the user who started talking with the help of https://github.com/otalk/hark, and it seems hark can't work without the mediaStream.  Additionally, I had tried to use the element from the audio track but with no success.

We'd really rather not lose this functionality, it was a big hit with our users.  Let me know what you think.

**Comment by markandrus** [comment]
Hi @Samenai,

Thanks for writing in. I'm glad to hear you are beginning a migration from beta4 to 1.0.0!

> it looks like there was a change to remove MediaStreams from participants.

That's true—whereas before you could call [`removeStream` (beta4)](http://media.twiliocdn.com/sdk/js/video/releases/1.0.0-beta4/docs/LocalMedia.html#removeStream__anchor), in 1.0.0 we'd recommend you use [`removeTracks` (1.0.0)](http://media.twiliocdn.com/sdk/js/video/releases/1.0.0/docs/LocalParticipant.html#removeTracks__anchor). Here's an example of the difference:

```js
// 1.0.0-beta4
localParticipant.media.removeStream(stream);

// 1.0.0
localParticipant.removeTracks(stream.getTracks());
```

Is this something you can adopt in your app?

> Additionally, I had tried to use the element from the audio track but with no success.

I'd like to help you with this, too—can you explain in a little more detail?

Also, you can typically create a new MediaStream at any time, and add MediaStreamTracks to them, as follows:

```js
function addToNewMediaStream(track) {
  const mediaStream = new MediaStream();
  const mediaStreamTrack = track.mediaStreamTrack;
  mediaStream.addTrack(mediaStreamTrack);
  return mediaStream;
}

// Imagine `track` is some twilio-video.js Track object...
const mediaStream = addToNewMediaStream(track);

// Then, do something with `mediaStream`...
```

Not sure, but this code snippet may be helpful to you.

Best,
Mark

**Comment by Samenai** [comment]
Oh, sorry, when I said "there was a change to remove mediaStreams", I meant that between beta4 and latest, it seems participants no longer have mediaStreams anymore. As in, there was a decision on your end to remove mediaStreams and just use tracks, which is a good decision as I'm having better luck with tracks during this migration to latest. 

However, we have a third party tool we used called Hark (https://github.com/otalk/hark) that would monitor the volume of a webRTC mediaStream and we would use that information to let users know who the 'main speaker' is or outline who is currently talking.

Is there any chance I can still access the webRTC mediaStream of the participants for this particular tool?

**Comment by markandrus** [comment]
@Samenai yes, you can either use a helper function like the `addToNewMediaStream` function I shared above, or you could call [`attach`](http://media.twiliocdn.com/sdk/js/video/releases/1.0.0/docs/Track.html#attach__anchor) and pull the `srcObject` attribute off of the resulting HTMLMediaElement. Either case is the same: construct a MediaStream on-the-fly, and add the Track's underlying MediaStreamTracks to the MediaStream. Can you try this out? Is there some code in particular you're having trouble with?

**Comment by Samenai** [comment]
Sounds like a plan and I'll dive deeper into this.  Here's the hark part in the old code that I'm migrating:

```javascript
hark (participant) {
  var _this = this;
  if (participant.media.audioTracks.size > 0 && !participant.speechEvents) {
    participant.speechEvents = hark(Array.from(participant.media.audioTracks.values())[0].mediaStream, {});
    participant.speechEvents.on('speaking', function () {
      _this.outlineRed(_.findIndex(_this.videos, participant), true);
    });
    participant.speechEvents.on('stopped_speaking', function () {
      _this.outlineRed(_.findIndex(_this.videos, participant), false);
    });
  }
}
```

**Comment by Samenai** [comment]
Thanks Mark!

I used the helper function and was able to modify the code to work:

```javascript
addToNewMediaStream(track) {
  const mediaStream = new MediaStream();
  const mediaStreamTrack = track.mediaStreamTrack;
  mediaStream.addTrack(mediaStreamTrack);
  return mediaStream;
}

hark (participant) {
   var _this = this;
   if (participant.audioTracks.size > 0 && !participant.speechEvents) {
     participant.speechEvents = hark(this.addToNewMediaStream(Array.from(participant.audioTracks.values())[0]));
     participant.speechEvents.on('speaking', function () {
       _this.outlineRed(_.findIndex(_this.videos, participant), true);
     });
     participant.speechEvents.on('stopped_speaking', function () {
       _this.outlineRed(_.findIndex(_this.videos, participant), false);
     });
   }
}
```
