### ISSUE TITLE
Video localhost and https live not working in chrome sometimes 

### ISSUE THREAD

**Issue by rajesh-smartwebtech** [twilio/twilio-video.js#1173]
@paynerc Hello

Browser `isSupported ` return true working in browser 
but another pc's google chrome same version browser getting error Requested device not found same in all browser

Error:  Requested device not found same in all browser 
and i have checked web rtc website to access web camera successfully but my code not working with twilio-video.js here

i dont know in same version browser  in different win 10 system conflagration but one side working and other one not working  only with  twilio-video.js here

i am using following code 
  ```
var Video = Twilio.Video;
  var participateConnected = false;
  var active_room = {};
var id  =  "";
  console.log("browser support: " , Video.isSupported);

  if( Video.isSupported == true ){

  //, video: videoConstraints, audio: true
  Video.connect('<?=$vd->accessToken?>', { name: '<?=$vd->roomName?>' }).then(function(room) {
    console.log('Connected to Room "%s"', room.name);

    active_room = room;

    console.log(room.participants);

    const updateStatus = function(id){
      if( room.participants.size == 0 ){
        $(id ).find(".video-status").show();
        //$(id).find(".status").html("Sorry, other participant didn't show up yet, we will wait 5 min to allow him to join "+' <span class="loader"></span> <div class="wait-timer-div" ></div>');

        $(id).find(".status").html("Your challenger may be experiencing technical difficulties, please allow a few minutes to see if your challenger will log on "+' <span class="loader"></span> <div class="wait-timer-div" ></div>');

        $($($(id).find(".video-status")).find(".loader")).LoadingForVideo('show');

      }else{
        $($($(id).find(".video-status")).find(".loader")).LoadingForVideo('hide');
      }
    };

    room.participants.forEach(participantConnected);
    room.on('participantConnected', participantConnected);

    room.on('participantDisconnected', participantDisconnected);
    room.once('disconnected', error => room.participants.forEach(participantDisconnected));

  });
  } else { // Video.isSupported validation
      var id = "#div_video_static,#div_video";
      $(id).find(".status").html("Sorry your browser does not support videostream. <br> Please use google chrome browser.");
  }
```
 
![image](https://user-images.githubusercontent.com/35251001/92991280-7e8a0100-f500-11ea-8c87-58e7bedc29a1.png)

Thank you

**Comment by rajesh-smartwebtech** [comment]
Both pc everything same, but i notice on not working browser side /
WebRTC working on this browser but on twilio show error getUserMedia() failed why ? 
Why twilio failed for getUserMedia and here already support WebRTC ?

**Comment by manjeshbhargav** [comment]
Hi @rajesh-smartwebtech ,

Thanks for writing in with your question. Your ConnecOptions object is `{ name: 'room-name' }`, which means the SDK will try to access both the microphone and camera for you. What is most likely happening in your case is that `getUserMedia` is failing in those particular windows machines because even though they have cameras they might not have microphones.

Can you confirm whether those failing machines have microphones or not?

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by rajesh-smartwebtech** [comment]
Hi @manjeshbhargav  
Windows machine has camera and microphones 
i will update and check driver for microphone may be microphone driver problem  
Thank you 

Chrome version Version 85.0.4183.102 (Official Build) (64-bit)

Thanks you

**Comment by rajesh-smartwebtech** [comment]
Hi @manjeshbhargav  

```
var Video = Twilio.Video;
console.log(Video .isSupported )
```

isSupported property return browser support or not support

Twilio has any property for available device for video and microphone  ?
so here we do not use any browser property for check for  available device like has camera or microphone  

Thank you

**Comment by manjeshbhargav** [comment]
Hi @rajesh-smartwebtech ,

You can use [MediaDevices.enumerateDevices](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/enumerateDevices) to find out about the devices on your system.

I'm going to close this issue since there is not much more I can do to help. Please feel free to reopen if you are still experiencing this issue.

Thanks,

Manjesh
