### ISSUE TITLE
Chrome 85 on Mac suffers poor video quality in peer-to-peer rooms

### ISSUE THREAD

**Issue by nicklyra** [twilio/twilio-video.js#1174]
- [X] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [X] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [X] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [X] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

* Create a peer-to-peer room
* Using the video quickstart, join the room using Chrome 85 on a Macbook Pro
* Also join the room on another device; I used a desktop PC with Firefox on the same LAN with 1Gbps connectivity to the Internet and also Safari on the same Mac.
* Observe webrtc-internals and compare with Safari on the same Macbook Pro.

**Expected behavior:**

Reasonable bandwidth choices; sufficient network bandwidth existed to easily handle 720 video even using TURN servers.  Expected Chrome to perform similarly to Safari.

**Actual behavior:**

Chrome is extraordinarily pessimistic; it quickly reduces resolution to 320x180 at 10 fps, or worse.  Safari consistently sends 720p at 24fps or better.

Curiously this doesn't seem to happen with Chrome on a PC, so this may well be a Chrome regression and naught to do with Twilio.  Still, it may be that there are workarounds possible (but I haven't found one yet).

**Software versions:**

 - [X] Browser(s):  Chrome 85 on Macbook Pro
 - [X] Operating System:  MacOS 10.14.6
 - [X] twilio-video.js: 2.7.2
 - [X] Third-party libraries (e.g., Angular, React, etc.): video-quickstart-js

**Comment by nicklyra** [comment]
I've narrowed this down to an option set in the Quickstart:

```js
  preferredVideoCodecs: [{ codec: 'VP8', simulcast: true }],
```

The preceding comment says:

```js
  // VP8 simulcast enables the media server in a Small Group or Group Room
  // to adapt your encoded video quality for each RemoteParticipant based on
  // their individual bandwidth constraints. This has no utility if you are
  // using Peer-to-Peer Rooms, so you can comment this line.
```

Worse than having no utility; it's actually quite destructive if using a Peer-to-Peer room with Chrome 85 on a Mac.  Changing to `simulcast: false` makes the problem go away.

I'm not sure what the answer is here; perhaps forcing simulcast to `false` if the room is a peer-to-peer room, or perhaps raising an error if it is `true`.

**Comment by manjeshbhargav** [comment]
Hi @nicklyra ,

Thanks for writing in with your question. You have it right - VP8 simulcast is only useful in Group or Small Group Rooms since the media server can forward the appropriate encoded video layer based on the subscriber's bandwidth constraints. So, please turn off simulcast for Peer-to-Peer Rooms.

Thanks,

Manjesh Malavalli
JSDK Team
