### ISSUE TITLE
Feature Request: add speech recognition to audio/video

### ISSUE THREAD

**Issue by theDude30** [twilio/twilio-video.js#118]
Hi,
I just read about twilio speech recognition feature:
https://www.twilio.com/blog/2017/05/introducing-speech-recognition.html?utm_campaign=70140000000iShR&utm_medium=email&utm_source=drip&utm_content=EVENT_CONF_2017-MAY-25_SIGNAL_SF_Product_Recap_Email_WW&utm_term=namer&elqTrackId=8d37bcf55ff04e0f88a45ede7dc6cf25&elq=8de39d2e1d8a431590b5b71487c60895&elqaid=4020&elqat=1&elqCampaignId=2154

Is there a way to add this feature to the audio/video(with parameter that can turn this on/off)?

**Comment by vincentwoo** [comment]
Yeah, realtime video subtitles in calls would be amazing.

**Comment by mrosenlund** [comment]
Any movement on this? @manjeshbhargav @kedartoraskar
