### ISSUE TITLE
[Question] Is there a way /api to increase /decrease my (localparticipant) MIC volume of a audio track?

### ISSUE THREAD

**Issue by kumail-raza** [twilio/twilio-video.js#1181]
@philnash @markandrus @makarandp0 @manjeshbhargav 

Scenario, where user can increase/decrease his/her volume while in the video call. So there any api/method available with Twilio Video SdK?

**Comment by philnash** [comment]
I've not tried it, but I guess you could put the user's microphone audio stream through the [Web Audio API using a gain node](https://developer.mozilla.org/en-US/docs/Web/API/GainNode) to increase volume. Just a suggestion though, I'm not sure how successful that would be.

**Comment by Wajeehkhan123** [comment]
d

**Comment by Wajeehkhan123** [comment]
@philnash can we differentiate between the host and other participants, like my scenario is that I want to display the text **host** for the participant who creates the room and when the **host** ends or disconnects the meeting, all other remote participants should be disconnected from the room. Moreover, is there any mechanism to authorize and then authenticate the user who wants to join the meeting?

**Comment by kumail-raza** [comment]
@philnash Thanks, that is quite interesting piece of information you have shared, I will check for that!

@Wajeehkhan123 you might need to open an another question since, I believe your problem not related to it.

Second, I will recommend you to check QUICKSTART app from Twilio here, this has all the answers to your questions I am sure
https://github.com/twilio/video-quickstart-js
