### ISSUE TITLE
I am able to get multi-participant video conference, however, I do not hear audio at all.

### ISSUE THREAD

**Issue by rgelb** [twilio/twilio-video.js#1189]
As the title says, no audio. I am not sure what I am missing.  Do I need an `<audio>` element?  My understanding was that the `<video>` element takes care of both.

What is missing?

 - [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ ] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

```js
const localTracks = await Twilio.Video.createLocalTracks({
                audio: true,
                video: true
            });

this.room = await Twilio.Video.connect(authToken, {
                name: this.roomName,
                tracks: localTracks
            });

const localParticipant = this.room.localParticipant;
const videoElement = document.getElementById('myvideo');
const localVideoTrack = localTracks.find(track => track.kind === 'video');
localVideoTrack.attach(videoElement);

// unmute
localParticipant.audioTracks.forEach(publication => {
                publication.track.enable();
            });
```

**Expected behavior:**

I hear the audio

**Actual behavior:**

I do not hear the audio

**Software versions:**

 - [x] Browser(s): Firefox, Edge (new), Safari on iOS 14
 - [x] Operating System:  Windows, iOS
 - [x] twilio-video.js: 2.7.2
 - [ ] Third-party libraries (e.g., Angular, React, etc.):  none

**Comment by makarandp0** [comment]
Hello @rgelb, 

The code you posted shows the handling of local participant's track. Can you post the handing of remote participant's tracks as well. You need to attach remote participant's audio track to media element. You can either attach it to new audio element or you can attach to existing `video` element. Please check out [quickstart](https://github.com/twilio/video-quickstart-js) application, it can help get started quickly.

Thanks,
Makarand

**Comment by rgelb** [comment]
Here is the code to handle remote participants:

```JS
// connect participants that are already connected
this.room.participants.forEach(participant => {
    this.log(`Already connected: ${participant.identity}`);          

    participant.tracks.forEach(publication => {
        if (publication.isSubscribed) {
            const track = publication.track;

            if (track.kind === 'video') {
                const videoElement = this.createVideoElement(participant.identity);
                track.attach(videoElement);
            }
        }
    });

    participant.on('trackSubscribed', track => {
        if (track.kind === 'video') {
            const videoElement = this.createVideoElement(participant.identity);
            track.attach(videoElement);
        }
    });
});

// connect remote participants that will connect in the future
this.room.on('participantConnected', participant => {
    this.log(`Participant connected: ${participant.identity}`);

    participant.tracks.forEach(publication => {
        if (publication.isSubscribed) {
            const track = publication.track;

            if (track.kind === 'video') {
                const videoElement = this.createVideoElement(participant.identity);
                track.attach(videoElement);
            }
        }
    });

    participant.on('trackSubscribed', track => {
        if (track.kind === 'video') {
            const videoElement = this.createVideoElement(participant.identity);
            track.attach(videoElement);
        }
    });

});
```

@makarandp0 When you say `You need to attach remote participant's audio track to media element.`, do you mean that both audio and video tracks need to be attached to the same  `<video>`?

**Comment by makarandp0** [comment]
Looks like you are not attaching audio tracks to dom. You need to attach both audio and video tracks. They can either be attached to separate `audio` and `video` elements respectively. Or you can attach them to same `video` element. 
[quickstart example](https://github.com/twilio/video-quickstart-js/blob/master/quickstart/src/joinroom.js#L198) attaches them to separate elements.

Thanks,
Makarand

**Comment by manjeshbhargav** [comment]
Hi @rgelb,

Since @makarandp0 's answer seems satisfactory to you, I'll close this issue. Please feel free to reopen if your issue hasn't been resolved.

Thanks,

Manjesh
