### ISSUE TITLE
[Quick Q/A s] Regarding preferredCodec and simulcast.

### ISSUE THREAD

**Issue by kumail-raza** [twilio/twilio-video.js#1196]
@philnash @makarandp0 @manjeshbhargav @andrewryno @anna-vasilko 

Hi Team, 

I have some quick questions as following:

**Referencing Doc: [Enabling Simulcast using the JavaScript SDK](https://www.twilio.com/docs/video/tutorials/working-with-vp8-simulcast#enabling-simulcast-chrome)** 

**Q1: Do simulcast works only with 'VP8' codec?**
```js
preferredVideoCodecs: [
      { codec: 'VP8', simulcast: true }
]
```

**Q2: Defining  `preferredCodec` will actually restrict users connecting to that room to be join with that specific codec?** 
> .... You can enable Simulcast on a per-Participant basis at Room connect-time. This is done using the ConnectOptions as shown in the following code snippet:

**Q3: Can `preferredCodec` change after the room creation (what if room created via Rest Api on server end)?**

**Q4: Configuration via portal `twilio/console` could be override while room creation using Rest API?**
> MediaRegion, StatusCallback, RoomType, etc..

**Q5: We need to have analysis report after switching between codecs and decide what goes well, how we can test that on Twilio?** 

**Q6: Same for simulcast, how we can test the difference having simulcast or not having it?** 

Looking forward for your response. Thanks & Regards

**Comment by philnash** [comment]
> Q1: Do simulcast works only with 'VP8' codec?

According to the [limitations and known issues](https://www.twilio.com/docs/video/tutorials/working-with-vp8-simulcast#limitations), simulcast is only supported for VP8

> Q2: Defining `preferredCodec` will actually restrict users connecting to that room to be join with that specific codec?

Yes, but you can provide an array of codecs to give your user's device an option.

```javascript
const room = await connect(token, {
    preferredVideoCodecs: [
      { codec: 'VP8', simulcast: true },
      "H264"
    ]
});

```

> Q3: Can `preferredCodec` change after the room creation (what if room created via Rest Api on server end)?

When you create a room with the REST API, you can set the available codecs ("VP8", "H264" or both). Then each user connecting can set their `preferredCodec`. If they don't match up then a user won't be able to connect to the room.

There is no way (that I can see) to change the preferred codec for a user after they have connected to a room.

> Q4: Configuration via portal twilio/console could be override while room creation using Rest API?

Yes

> Q5: We need to have analysis report after switching between codecs and decide what goes well, how we can test that on Twilio?
> Q6: Same for simulcast, how we can test the difference having simulcast or not having it?

I'm afraid I don't have any experience testing the difference between codecs/simulcast. I'll have to leave that up to others to answer. It might help to define what kind of thing you expect here though.
