### ISSUE TITLE
Unintentionally paused

### ISSUE THREAD

**Issue by dmitry-tikva** [twilio/twilio-video.js#1197]
Hello!

I am not sure if there is no issue in this repo about it but anyways pls let me describe :)

Once I minimise safari on mobile or to other app it says me in console 
```[LocalVideoTrack #2: 351395ae-7eeb-42a2-a7d1-31d8b53c6849]:" – "Unintentionally paused:"```

And my participants can't see my video and can't hear me.

So, as I understand it close connection between camera once tab with my app is not on focus.

Can pls someone help me? Maybe you know how create local tracks without interrupting or pausing on blur safari or tab.

Thanks a lot!

**Comment by makarandp0** [comment]
Hello @dmitry-tikva, Thank you for writing about this. This is a limitation imposed by Safari - it pauses the media element when the tab goes/stays in background. twilio-video sdk does try to unpause such elements when it tab gains foreground, but while its backgrounded there isn't much we can do about it. 

One thing you can try at app level is watch for the [visibilitychange](https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilitychange_event) and notify other participant about the tab getting backgrounded and except interruption in video/audio feed.

Hope that helps,
Thanks,
Makarand
