### ISSUE TITLE
Frequent connection failure / disconnection

### ISSUE THREAD

**Issue by DaniyalBasit** [twilio/twilio-video.js#1201]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Expected behavior:**

The user should not disconnect frequently.

**Actual behavior:**

The users from the android device get disconnected frequently. In order to check the logs please use this room sid ```RMc8b31869da8b0199ea43cbe3cc2eac79```

**Software versions:**

 - [x] Browser: Chrome 85
 - [x] Operating System: Android
 - [x] twilio-video.js: 1.20.1
 - [x] Third-party libraries: React

**Comment by makarandp0** [comment]
Hello @DaniyalBasit, You are using older version of the SDK (1.20.1), we have made lot of [improvement in connectivity](https://www.twilio.com/docs/video/migrating-1x-2x#reconnection-states-and-events) in 2.x. I recommend that you upgrade your app to use newer SDK. Most notably on 1.x any network glitches caused the connection to disconnect, on 2.x sdk automatically tries to re-establish the connection with the room. 

Also note that support for 1.x will cease on December 4th, 2020

Thanks,
Makarand
