### ISSUE TITLE
Issues with Track Disabled/Enabled/Started/Stopped

### ISSUE THREAD

**Issue by jlukic** [twilio/twilio-video.js#1202]
I'm working on trying to resolve issues where a video/audio track is disconnected manually by the user (i.e. unplugging camera or mic from usb) 

I've been debugging with both participant level and track level event callbacks that I would expect to fire when a participant manually stops the video/audio track.

I've been opening two connections with a normal browser window and incognito window, then disconnecting my camera by yanking the USB plug to determine what callbacks will fire.

```javascript

const trackPublished = function(participant, publication) {
  // If the TrackPublication is already subscribed to, then attach the Track to the DOM.
  if (publication.track) {
    onConnect(participant, publication.track);
  }

  // Once the TrackPublication is subscribed to, attach the Track to the DOM.
  publication.on('subscribed', track => {
    console.log('publication subscribed');
    console.log(track);
    onConnect(participant, track);

    track.on('switchedOff', track => {
      console.log('track switched off');
      console.log(track);
    });
    track.on('switchedOn', track => {
      console.log('track switched on');
      console.log(track);
    });
    track.on('enabled', track => {
      console.log('track enabled');
      console.log(track);
    });
    track.on('disabled', track => {
      console.log('track disabled');
      console.log(track);
    });
  });
};

const registerParticipant = function(participant) {

  participant.tracks.forEach(publication => {
    trackPublished(participant, publication);
  });

  // Handle theTrackPublications that will be published by the Participant later.
  participant.on('trackPublished', publication => {
    trackPublished(participant, publication);
  });

  participant.on('trackEnabled', track => {
    console.log('track enabled');
    console.log(track);
  });
  participant.on('trackDisabled', track => {
    console.log('track disabled');
    console.log(track);
  });
  participant.on('trackSwitchedOn', track => {
    console.log('track switched on');
    console.log(track);
  });
  participant.on('trackSwitchedOff', track => {
    console.log('track switched off');
    console.log(track);
  });

};
```

I can manually hook up some code with `deviceChange` but it becomes a ton of boilerplate because i will have to track which devices were associated with which track IDs to know which tracks are no longer available. 

I'd expect the API to wrap this functionality and provide callbacks when the track no longer was available.

**Expected behavior:**

When user disconnects mic via USB i'd expect there would be a callback like `trackSwitchedOff` or `trackDisabled` that would fire to allow the UI to correctly adjust to the disconnected media track.

**Actual behavior:**
No callbacks above fire for remote participant or track.

**Software versions:**

Twilio Video `2.7.2`
Any supported web browser

**Comment by makarandp0** [comment]
Thank you for the suggestion @jlukic. We are aware of this issue, and its on our backlog (JSDK-2973). We will update you once we have some updates about this.

But for now as you mentioned you need to monitor `deviceChange` from app side.

Thanks,
Makarand

**Comment by makarandp0** [comment]
@jlukic, I am closing this old issue, We still have a corresponding feature request is our database (VIDEO-3609)

Thanks,
Makarand
