### ISSUE TITLE
H.264 simulcast support

### ISSUE THREAD

**Issue by hantonelli** [twilio/twilio-video.js#1203]
Is adding H.264 simulcast support on the roadmap?

Safari 12.1 supports it, so it will be very beneficial to be used by most Apple devices
https://developer.apple.com/documentation/safari-release-notes/safari-12_1-release-notes

**Comment by manjeshbhargav** [comment]
Hi @hantonelli ,

This is not in our roadmap in the near future. Please follow the pull requests in the repository. You will see some PRs once we do start work on it.

Thanks,

Manjesh
