### ISSUE TITLE
Audio Output Devices is empty on cellphone browsers(chrome/firefox), while pc browser is good 

### ISSUE THREAD

**Issue by cengit** [twilio/twilio-video.js#1207]
- [√ ] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [ √] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [√ ] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [ √] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

```js
// TODO
// video-quickstart-js can reproduce this issue
open this url on cellphone browser: http://localhost:3000/mediadevices/
```

**Describe the bug**
Audio Output Devices list is empty on cellphone browsers(both android and iPhone, happens on Chrome and Firefox), but pc browser is good.

**To Reproduce**

open the site using chrome/ Firefox in your cellphone, plugin your headphone
Click setting option in the menu, you can see setting popup layer is visible
Check the Audio Output dropdown
No Audio Output devices found, it just display "Default"

**Expected behavior**
all available Audio Output devices should be list in the dropdown

**Screenshots**
http://demo.cenday.com/twilio-output-device-none.jpg
http://demo.cenday.com/twilio-output-device.jpg

**Environment (please complete the following information):**

OS: android 10
Browser: [Chrome 85.0.4183.121 (64bit)] Firefox and iPhone safari also reproduce
SDK Version: twilio-video-2.7.0

**Additional context**
this issue only happen on cellphone, when open it pc browsers, it's fine though.

**Comment by cengit** [comment]
hello, any update on this?

**Comment by makarandp0** [comment]
Hey @cengit, Thank you for writing about this - yes, looks like browser does not let you pick audio output when running on some configurations. Can you confirm that you see similar results when you use a webrtc sample here: https://webrtc.github.io/samples/src/content/devices/input-output/

Thanks,
Makarand

**Comment by cengit** [comment]
@makarandp0 Thanks for your reply. 
Yes, I get the same results when using a webrtc sample you provided above:https://webrtc.github.io/samples/src/content/devices/input-output/

this is my screenshot: http://demo.cenday.com/webrtc-input-output.jpg (android 10 Chrome 81.0.4044.117)
and same result on android 10 + latest firefox.

any solution?

**Comment by manjeshbhargav** [comment]
Hi @cengit ,

Mobile browsers generally do not allow developers to specify specific output devices. So, there is nothing we can do at this point.

Thanks,

Manjesh
