### ISSUE TITLE
How do I specify the room type when creating a room in the browser?

### ISSUE THREAD

**Issue by rgelb** [twilio/twilio-video.js#1209]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**
```js

           const localTracks = await Twilio.Video.createLocalTracks({audio: true, video: true});

            this.room = await Twilio.Video.connect(authToken, {
                name: 'myroomname',
                tracks: localTracks
            });
```

Where exactly do I specify whether I want a peer-to-peer room or a small group or a large group?

**Software versions:**

 - [x] Browser(s):  Any
 - [x] Operating System:  Any
 - [x] twilio-video.js: 2.7.2
 - [x] Third-party libraries (e.g., Angular, React, etc.): none

**Comment by makarandp0** [comment]
Hello @rgelb, Thank you for your question. 

You can create the type of room you want to join by specifying [type parameter](https://www.twilio.com/docs/video/api/rooms-resource#post-parameters) in createRoom request. And specify the room name created in `Video.connect` call. 

If you do not pre-create a room an ad-hoc room gets created, and the type of ad-hoc room depends on your [console settings](https://www.twilio.com/console/video/configure).

You can read more about  video rooms [here](https://www.twilio.com/docs/video/tutorials/understanding-video-rooms#video-rooms).

Thanks,
Makarand

**Comment by rgelb** [comment]
@makarandp0 So to clarify.  When you refer to `createRoom` request, you mean do this server-side, right?  Your [type parameter](https://www.twilio.com/docs/video/api/rooms-resource#post-parameters) only has examples for server-side languages.

So in effect, I cannot specify the type of room in the browser in JavaScript only?

**Comment by makarandp0** [comment]
That is correct, you typically create room from server side, just like you create tokens from server side.

**Comment by baj84** [comment]
@makarandp0 @rgelb I just want to follow up on this as I think it's still not that clear. Are you saying it's impossible to specify the room type (GO, Peer2Peer, etc) when creating an ad-hoc room from the client side? 

If so, is this feature on the horizon?

**Comment by rgelb** [comment]
> @makarandp0 @rgelb I just want to follow up on this as I think it's still not that clear. Are you saying it's impossible to specify the room type (GO, Peer2Peer, etc) when creating an ad-hoc room from the client side?

Yes, that is what I am saying.  Having said that I haven't used the SDK since last year.  Things could have changed.

**Comment by baj84** [comment]
@rgelb Thanks. I've had a look at the code and unfortunately the only way to specify room type is by using the Twilio REST API on the backend.
