### ISSUE TITLE
Best Video quality for one track

### ISSUE THREAD

**Issue by 4ydo4elovek** [twilio/twilio-video.js#1213]
Hi, our team want to use your Video Service and we have some problems with quality. It’s supposed that in Video Room we have one main user and usual(from 1 to 50). Main user should have the best video quality then others (HD or better). Video quality of usual it’s not important.
So we try different ConnectOptions for different cases:

For main user:
`const isMacLike = /(Mac|iPhone|iPod|iPad)/i.test(navigator.platform);
const codec = isMacLike ? 'H264' : 'VP8';

{
              name: roomName,
              audio: true,
              tracks: [videoTrack, audioTrack],
              dominantSpeaker: true,
              video: {
                  width: { ideal: 1024, max: 1024},
                  height: {
                      ideal: 768,
                      max: 768,
                  },
              },
              bandwidthProfile: {
                  video: {
                      mode: 'presentation' as BandwidthProfileMode,
                      trackSwitchOffMode: 'predicted',
                      dominantSpeakerPriority: 'high' as Priority,
                      renderDimensions: {
                          high: { height: 1080, width: 1920 },
                          standard: { height: 720, width: 1280 },
                          low: { height: 176, width: 144 },
                      },
                      maxSubscriptionBitrate: 0,
                  },
              },
              preferredVideoCodecs: [{ codec: codec as VideoCodec, simulcast: true }],
              region: 'gll',
 }
`
For usual user:
`{
              name: roomName,
              audio: true,
              tracks: [videoTrack, audioTrack],
              dominantSpeaker: false,
              video: {
                  width: { max: 176 },
                  height: { max: 144 },
              },
              bandwidthProfile: {
                  video: {
                      mode: 'grid' as BandwidthProfileMode,
                      renderDimensions: {
                          high: { height: 1080, width: 1920 },
                          standard: { height: 176, width: 144 },
                          low: { height: 176, width: 144 },
                      },
                      maxSubscriptionBitrate: 0,
                  },
              },
              preferredVideoCodecs: [{ codec: codec as VideoCodec }],
              maxAudioBitrate: 16000,
              region: 'gll',
}`

So result is: usual users get Main User’s Videotrack with «floating» quality. In best case they have (around: {w: 960, h: 540} but it is constantly changing.
WebCam is ok, it send HD. Signal is ok - we give 5 networkQualityLevel from main participant.

What should we change in options?

**Comment by anil1712** [comment]
@4ydo4elovek I am also facing the quality issue. I am always getting the 640x480 video but the expected video should have 1920x1080 in size. 
So please suggest me that what solution works for you to achieve high quality video?

**Comment by 4ydo4elovek** [comment]
Hi, I wrote to support and they said this: 
"I would recommend using the "Collaboration" bandwidth profile for this use case.  Collaboration is a setting that can be configured when the participant's join the room. The collaboration profile will allow your main track to have top priority while the other 10 tracks will be smaller and in lower quality.  All other participants should join without publishing any tracks. "
It's work for me. 
After this settings I start get quality from 640x480 to 1280x720.
