### ISSUE TITLE
[Question] Is it possible with Twilio to broadcast to an RTMP capable streaming stack

### ISSUE THREAD

**Issue by bogy0** [twilio/twilio-video.js#1219]
In our use-case, we need to replace our Flash-based web broadcaster which streams the webcam video to an RTMP capable streaming stack. 
Is this possible with Twillio video solution?
I try to found related info in the documentation, but can't find anything related to RTMP.

Thanks in advance!

**Comment by manjeshbhargav** [comment]
@bogy0 ,

Sorry for the delayed response. Right now, we do not support this out of the box, but you can build a Room Participant that subscribes to all the Tracks in a Room and pipes it to the streaming stack.

Thanks,

Manjesh

**Comment by ciclanoio** [comment]
Any changes on this or is it still a the same to send a RTMP? If so, do you have a tutorial on how to do it?

Thanks

**Comment by manjeshbhargav** [comment]
Hi @ciclanoio ,

Thanks for writing in with your question. This capability is under consideration but we don’t have anything concrete to share at this time. The approach described above is the only way to support this today.

Thanks,

Manjesh

**Comment by ciclanoio** [comment]
Ticket subject: Seu ticket foi aberto.




Converse agora: https://direct.lc.chat/8505373/0


Powered by https://www.helpdesk.com/powered-by-helpdesk/?utm_source=ticket-footer-lc&utm_medium=email&utm_campaign=lc_8505373
