### ISSUE TITLE
getStats() response property "audioLevel" (remote) is always null in Firefox 81.0.1

### ISSUE THREAD

**Issue by untilted-document** [twilio/twilio-video.js#1221]
Our app calls `room.getStats()` on a regular basis (100ms) and extracts the `audioLevel` (plus some other things) from the returned stats. Later we use this `audioLevel` to render a volume meter. In Chrome it works well, but in Firefox the (remote) `audioLevel` is always reported as `null`. I note that the codec is also `null` in FF but `"opus"` in Chrome

### Screenshot of firefox's dev console "Scopes" panel 
showing the return value from getStats() - it returns an array from which we extract the first/only element

![image](https://user-images.githubusercontent.com/18049243/95664447-d63b7c80-0b3f-11eb-9fcc-b74dedf262ad.png)

### Shot of the same thing in chrome; 
all other aspects of this are the same - we just literally switch browser and launch the app in Chrome instead:

![image](https://user-images.githubusercontent.com/18049243/95664534-b8224c00-0b40-11eb-9c8b-51a9401deb75.png)

-----

 - [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

 - [x] Browser(s): Firefox
 - [x] Operating System: Microsoft Windows [Version 10.0.18362.1082]
 - [x] twilio-video.js: 2.7.2
 - [x] Third-party libraries (e.g., Angular, React, etc.): React

**Comment by ccchapman** [comment]
This is also happening for me.

Possibly related:

- https://github.com/twilio/twilio-video.js/issues/1140
- JSDK-2842

**Comment by manjeshbhargav** [comment]
@untilted-document ,

Thanks for writing in with your issue. @makarandp0 Can you take this one?

Thanks,

Manjesh

**Comment by andreikazmirovich** [comment]
@manjeshbhargav @makarandp0  any updates on that?
It's still reproducible in Firefox
"twilio-video": "2.27.0"
