### ISSUE TITLE
Support for reverse-proxy

### ISSUE THREAD

**Issue by DanEdwards61** [twilio/twilio-video.js#1222]
I am working on adding support for a reverse-proxy setup to allow Twilio Video to operate using URL's that resolve under our domain. 

At present, 2 URL's are at play. These can be found in 'lib/util/constants.js' and 'lib/util/insightspublisher/index.js'.  The code snippets are:
`
module.exports.WS_SERVER = (environment, region) => {
  region = region === 'gll' ? 'global' : encodeURIComponent(region);
  return environment === 'prod'
    ? `wss://${region}.vss.twilio.com/signaling`
    : ``wss://${region}.vss.${environment}.twilio.com/signaling``;
};
`

`function createGateway(environment, realm) {
  return environment === 'prod' ? ``wss://sdkgw.${realm}.twilio.com``
    : ``wss://sdkgw.${environment}-${realm}.twilio.com``;
}
`

Desired Behavior:
I would like to be able to pass these 2 URL's as properties in the connect options parameter.

Twilio version:
2.7.2

**Comment by manjeshbhargav** [comment]
@DanEdwards61 ,

We have a couple of internal ConnectOptions properties that are not part of the public API:

* `wsServer` - Override the default signaling server URL.
* `wsServerInsights` - Override the insights server URL.

Please let me know if this works. I will close this issue, but we can continue the conversation here.

Thanks,

Manjesh

**Comment by DanEdwards61** [comment]
@manjeshbhargav 

It looks like wsServer is a local variable and not pulled from the connect options. I'm looking at lib/connect.js and wsServer is set from WS_SERVER, which builds up the signaling URL.. wsServerInsights is there and I'll be using that as well.

It seems easy enough to change that to:
`wsServer = (option.wsServer || WS_SERVER(...))`
which was my initial approach.

If I'm missing something there, please correct me.

In addition, one other thing I would like to see for our use case is to allow us to append to iceServers instead of over-writing them.  We would prefer to always use Twilio media servers, if possible. We want our TURN server to be a backstop for customers who don't whitelist the Twilio domain. 

The simplest option appears to be providing something like "additionalIceServers" & appending them to iceServers in "onIced". I would appreciate any thoughts you have on this.
