### ISSUE TITLE
Call quality is low and users get disconnected with "signaling_connection_timed_out"

### ISSUE THREAD

**Issue by fromanother** [twilio/twilio-video.js#1223]
- [X] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [X] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [X] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [X] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

Earlier today (13 Oct 2020, 16:30 - 18:00 UTC), a peer to peer room, with two participants had very low quality video and the participants kept getting disconnected. These same participants, had previously used the same setup a few days before and it worked fine.

Looking at the logs at https://www.twilio.com/console/, I can see that the "End Reason" is specified as `signaling_connection_timed_out` a few times, and this happened for both participants, not just one.

The participants are in separate countries, and they had tried both WiFi and hotspot with mobile data with no improvements.

Due to the above, and the fact that both received "signaling_connection_timed_out" separately, I thought this was a Twilio server issue, but there are no incidents reported on status.twilio.com.

Later, while testing with one of the participants, I was unable to reproduce any issues.

One of the participants, also received `TwilioError: Signaling connection error` while trying to connect to the room.

**Software versions:**

 - [ ] Browser(s): Chrome
 - [ ] Operating System: Android and OSX
 - [ ] twilio-video.js: 2.7.2
 - [ ] Third-party libraries (e.g., Angular, React, etc.): React 16

**Comment by anns-carveniche** [comment]
iam also facing the same issue for my users several times.
Error Code : 53000
Error Message : Signalling Connection Error

**Comment by fromanother** [comment]
@anns-carveniche When have you experienced these issues? Only recently? Or is it an ongoing problem.

Just to add the OP, the two users are from Europe, one from W Europe and one from E Europe.

**Comment by anns-carveniche** [comment]
This problem for us we have been facing for last two weeks.there are two participants one is from india and another one is from Dubai.

**Comment by manjeshbhargav** [comment]
Hi @fromanother ,

Can you share some Room SIDs so that we can start investigating?

Thanks,

Manjesh

**Comment by fromanother** [comment]
> Can you share some Room SIDs so that we can start investigating?

Here are some room SIDs:
RMd4f85f807fa966e2a7d7542707d30eb2
RM18ce5490c0d7340eb471353645c55cf4
RM03595bd1ff86fa176f432f04f1d51c23
RMb16f8ff918843aaeb25de34c64fd271d

Thanks.

**Comment by manjeshbhargav** [comment]
Hi @fromanother ,

"Signaling connection timed out" usually means that the client temporarily lost connection to Twilio due to a network disruption, tried to reconnect for a while but failed. This usually points to bad network conditions. The fact that video quality is low points towards a bad network. One way to confirm this is to test with only audio. If the connection is maintained, then it points to a network bandwidth issue.

I also saw that one of the Participants is from Dubai. We don't guarantee support for UAE based clients at this point because the government has some restrictions on outgoing connections and a lot of the times Twilio services are not reachable.

Thanks,

Manjesh
