### ISSUE TITLE
iOS remote video track is blank when created with certain size constraints

### ISSUE THREAD

**Issue by robsoden** [twilio/twilio-video.js#1224]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

Using mobile Safari on iOS, when I create a video track and supply specific constraints for certain sizes, the local track displays correctly but the remote track is blank for other users in the room. 

Supplying 640x480, and 1280x720 works fine, and not supplying constraints also works (dimensions seem to revert to default of 640x480). But any other resolutions fail, even resolutions that are supported by the iphone camera (such as 1920x1080)

All desktop browsers seem to work correctly. I can set constraints as high as 4k resolution and the desktop browsers seem to find their upper limit automatically (as the getUserMedia documentation implies they should, treating the constraints as 'ideal' values). The problem seems limited to iOS.

**Code to reproduce the issue:**

```js
const constraints = {
  width: 1920,
  height: 1080
}

Video.createLocalVideoTrack(constraints).then(localVideoTrack => {
  room.localParticipant.publishTrack(localVideoTrack);
})
```

**Expected behavior:**

Other users should see the remote track published with video dimensions of 1920x1080

**Actual behavior:**

Other room participants do see the remote track published, but it does not render, and lists NULL dimensions. However, the local track DOES render correctly. The problem is limited to the remote track publication.

**Debug Information**

No errors are being thrown at the time of local track creation (nothing from the browser about constraints being exceeded, etc) or time of publication. Console logging the local track shows that everything is ok and track dimensions exist as expected. The local track renders correctly. 

Below are snippets of what the other users see when the tracks of the remote participant in question are logged.

Correct, working track published with constraints of 1280x720

```
videoTracks: Map(1)
[[Entries]]
0: {"<publicationId>" => RemoteVideoTrackPublication}
key: "<publicationId>"
value: RemoteVideoTrackPublication
isSubscribed: true
isTrackEnabled: true
kind: "video"
publishPriority: "standard"
track: RemoteVideoTrack {
  dimensions: {width: 1280, height: 720}
  isEnabled: true
  isStarted: true
  isSwitchedOff: false
  kind: "video"
}
```

Publication for a broken track, published with constraints set at 1920x1080

```
videoTracks: Map(1)
[[Entries]]
0: {"<publicationId>" => RemoteVideoTrackPublication}
key: "<publicationId>"
value: RemoteVideoTrackPublication
isSubscribed: false
isTrackEnabled: true
kind: "video"
publishPriority: "standard"
track: RemoteVideoTrack {
  dimensions: {width: null, height: null}
  isEnabled: true
  isStarted: false
  isSwitchedOff: false 
  kind: "video"
}
```

**Software versions:**

 - [x] Browser(s): Safari
 - [x] Operating System: iOS 14.0.1
 - [x] twilio-video.js: 2.7.2
 - [x] Third-party libraries (e.g., Angular, React, etc.): React

**Comment by manjeshbhargav** [comment]
Hi @robsoden ,

Thanks for writing in with this issue. I will investigate and get back to you.

Thanks,

Manjesh

**Comment by manjeshbhargav** [comment]
Hi @robsoden ,

I was not able to reproduce the issue. I tried 1920x1080 and was able to see the video feed on my desktop. Can you share the console logs by re-running the experiment and enabling `logLevel: 'debug'` in ConnectOptions.

Thanks,

Manjesh

**Comment by deadmanIsARabbit** [comment]
Isn't this related to the issue described in this changelog:
https://www.twilio.com/docs/video/changelog-twilio-video-ios-version-2x

> Publishing H.264 video at greater than 1280x720 @ 30fps is not supported. If a failure occurs then no error is raised to the developer. [ISDK-1590]
