### ISSUE TITLE
JS - How to get frame from video track - like VideoRenderer (iOS, Android)

### ISSUE THREAD

**Issue by NALWeb** [twilio/twilio-video.js#1226]
@philnash @markandrus @makarandp0 @manjeshbhargav 
I am using JS SDK, I need change the background of local video and remote video. I am using [BodyPix](https://github.com/tensorflow/tfjs-models/tree/master/body-pix) for detecting person and I need get frame from video track. Please show me a way. Thanks!

**Comment by philnash** [comment]
Hi @NALWeb, the [`image` param for `segmentPerson` actually take the following types as an argument](https://github.com/tensorflow/tfjs-models/tree/master/body-pix#params-in-segmentperson): `ImageData | HTMLImageElement | HTMLCanvasElement | HTMLVideoElement`. So you can create a video element with `videoTrack.attach()` and pass that to the BodyPix method.

As a warning, I have tried working with this and the performance in the browser is not great. I'd love to hear about your results though.

**Comment by NALWeb** [comment]
@philnash I am handling at the client for local video and remote video, not attach into raw data. I use `canvas` as input for BodyPix method but it isn't cool. I am trying to find the another way.

HTML:
`<div id="local-media"></div>
 <canvas id="canvasPerson" width="640px" height="480px"></canvas>`

JS:
`var canvas = document.getElementById("canvasPerson");
        const ctx = canvas.getContext("2d");
        ctx.drawImage(video, 0, 0, video.videoWidth, video.videoHeight);
        net.segmentPerson(canvas, {
            flipHorizontal: false,
            internalResolution: "medium",
            segmentationThreshold: segmentationThreshold,
        })
...
function roomJoined(room) {
       var detectPerson = setInterval(detectBody, 50);
...
}
`
[My screen recording](https://drive.google.com/drive/u/2/folders/1v47jXySqxGAGU_u5YzYRWNkc6TKe--Yq)

**Comment by philnash** [comment]
Like I said, I did not find BodyPix worked very well in the browser for me either. It is a huge drain on the system and could not sustain a good frame rate. It looks like you are getting similar issues.

I've not tried anything else for this in the browser, but I am not convinced the browser is the best place to do this work. I don't have any other suggestions for you, sorry.

**Comment by NALWeb** [comment]
@philnash OK, I got it, thank you!
