### ISSUE TITLE
PeepToPeer call mediaStreamTrack muted: true in wrapper objects but underneath wrapper streams are proper.

### ISSUE THREAD

**Issue by kamesh-a** [twilio/twilio-video.js#1233]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Scenario Steps :**
- Connected peer to peer call with twilio lib in electron browser environment inside `webview`
- After connecting participant A with B
- Participant A can not see or hear participant B
- But participant B can hear and see participant A
- Looking further it looks like participant A is not getting trackStarted events from participant B
- when we looked into `active.participants` we can see `videoTracks & audioTracks`
- but both `audio & video tracks` are `muted: true`
- on looking into internal peerConnections object, participant B  audio & video tracks have `readyState:live` and `muted:false`
- Reconstructing the MediaStream from those objects attaching to the video tag srcObject produced the video stream properly.

Having the above, we were able to understand some how the custom calls events from twilio didn't bubble up but, underlying wrapper put the cloned mediastream into ended/muted state yet real media stream received is still working.

Attached screenshots for reference with 
<img width="1017" alt="Screen Shot 2020-10-16 at 4 10 07 PM" src="https://user-images.githubusercontent.com/3531949/96253177-c48b2680-0fd0-11eb-8e7e-d5be39e40e31.png">
<img width="1216" alt="Screen Shot 2020-10-16 at 4 09 21 PM" src="https://user-images.githubusercontent.com/3531949/96253180-c94fda80-0fd0-11eb-9870-e1f7970acb70.png">
<img width="1129" alt="Screen Shot 2020-10-16 at 4 08 17 PM" src="https://user-images.githubusercontent.com/3531949/96253183-c9e87100-0fd0-11eb-9f36-e055d5c920e2.png">

```js
SID: RM6f85ff43fbe770b69a9bf2ff174f925a

participant-A: "PA0b0b693e55fe9e214c61f0e7127d4c49"
	audio: "MT472c96afa03a84bc3804f517a2fcf3b8"
		mediaStreamTrack: c0d48c63-4911-4d97-b6a4-2865d9d81a4c
	video: "MT5a8768bf84c655e3dabbb239b1694a98"
		mediaStreamTrack: edc081d7-b6c7-4fdd-bd8b-be0fa26956d5

participant-B : "PA9d34cf6ecd8487f4a871bc61d7719702"
	audio: "MT92f70ba458dcfdaa09c7c5995a793e38"
		mediaStreamTrack: dda90192-d4ba-4527-938d-a1a7033e0f03
	video: "MT34349110c4200069ef32d58e2de20e07"
		mediaStreamTrack: a48f6982-9027-4fdf-aefa-6f39c7dc7cf4
```

**Expected behavior:**
- Video stream should produce stream with `muted:false & readyState: live`
- Audio stream should produce stream with `muted:false & readyState: live`
- `trackStarted` event should be emitted successfully.

**Actual behavior:**
- Video stream has `muted:true & readyState: live`
- Audio stream has `muted:true & readyState: ended`
- `trackStarted` event is not emitted.

PS: we couldn't get the twilio logs in this system. Issue reproduction is sporadic. 

**Software versions:**

 - [x] Browser(s): Electron 
- [x] User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) anywhere.app/8.1.9 Chrome/80.0.3987.165 Electron/8.5.0 Safari/537.36
 - [x] Operating System: Mac OS 10.15.6
 - [x] twilio-video.js: 2.7.2
 - [x] Third-party libraries (e.g., Angular, React, etc.): React

**Comment by sandeepnandula** [comment]
👍

**Comment by manjeshbhargav** [comment]
Hi @kamesh-a ,

Thanks for writing in with your issue. Can you clarify what you mean by running electron in a webview? Usually electron is its own environment right? Also, can you provide the exact reproduction steps? I would like to try it out  on my end.

Thanks,

Manjesh

**Comment by kamesh-a** [comment]
Hi @manjeshbhargav 

In electron traditionally developers use to load the assets in the `browserWindow/browserView` to render in case of standalone desktop application also does support weburls. In our application we have multiple integrated web apps in single browserWindow so we are webview inside an Electron BrowserWindow.

Each webview will get a separate renderer process/event-loop/heap individual from each other embedded webviews. One of those webviews is embedded with video app which uses P2P to make remote calls.

Reproduction Steps:
- 1. Create an instance of BrowserWindow. ( app )
- 2. Create a Webview and embed inside BrowserWindow with twilio quick start with P2P
- 3. Join participant A
- Spin another instance of the *app* step1-step3
- Join participant B

- Participant A media ( audio, video ) will flow properly to Participant B
- Participant B media `trackPublished` event will emit, but `trackStarted` emit will never emit.
- When we inspect `activeRoom` internal peerConnection mediaStreams are proper.

It will take few tries to get this effect.
Mac OS  : 10.15.7
Electron :  Electron/8.5.0

Please let me know, if you need anything we can create a sample app in electron if necessary and send the source code. Note: We have to give 3-6 tries to get this issue. It doesn't happen every time.

**Comment by manjeshbhargav** [comment]
@kamesh-a ,

If you can publish your reproduction app and link me to the source, I will be happy to try it out and start debugging.

Thanks,

Manjesh
