### ISSUE TITLE
Does Twilio programmable video work in UAE?

### ISSUE THREAD

**Issue by shared-studios** [twilio/twilio-video.js#1234]
We are building a web application using the following tools: Twilio Programmable Video, AWS API/Websocket Gateway, React.js, and node.js.

We have tested with a user in UAE and the application worked fine. However, we used other teleconference tools before (zoom, skype) in UAE and they get blocked after 3-4 hours due to the UAE restrictions; requiring us to use VPN services.

Does anyone have experience with Twilio Programmable video services in UAE and did you experience any issues with UAE restrictions?

**Comment by swarnava** [comment]
Hi,

Thanks for checking with us.  Unfortunately we don't have feedback specifically about UAE Network.  There is a basic connectivity test here:

https://networktest.twilio.com/

however it only tests voice, not video.

To test Programmable Video you would need to set up a demo app, on your server.  The easiest way to do that is with this Node.js project:

https://github.com/twilio/video-quickstart-js.

Please note that, UAE apps using may work but the in country entities  control access and can ban comm apps at any time. We don't have control of whether if and when they decide to block IP addresses or apps that use our services. I hope this helps! feel free to reach out at help@twilio.com if you have any question.
