### ISSUE TITLE
[Question] How to kick someone from a meeting and keep them from rejoining?

### ISSUE THREAD

**Issue by dannnnthemannnn** [twilio/twilio-video.js#1236]
I know that you can kick a participant from a meeting by setting their status to "disconnected" with the REST API (https://www.twilio.com/docs/video/api/participants?code-sample=code-remove-a-participant-3&code-language=Node.js&code-sdk-version=default#kickremove-participant-from-a-room).

However, they will still have the token that was used to connect them to the room and could just rejoin (right?). Is there a way to invalidate that token, or tell the room to not let that identity in again? I'm imagining someone joins a conversation and the host wants to ban them from rejoining.

**Comment by swarnava** [comment]
To do this, you'd want to write your app so that a new token must be requested if they're connecting to a room. When you kick a participant, you can update your server so that token requests for that particular user are rejected.

**Comment by dannnnthemannnn** [comment]
My understanding is that an access token indicates: 
- The room you have access to
- The identity of the user who it grants access to

So even if my application doesnt put them into the room until they get a new token, it seems that anyone who knew what they were doing could this JS SDK (or for example forking https://github.com/twilio/twilio-video-app-react) and enter the room directly with that token without me having any way of stopping them.

**Comment by vargad** [comment]
You can do what @swarnava advised, and set the TTL of the token to be short, so by the time the user tries to rejoin it's expired.

**Comment by dannnnthemannnn** [comment]
It says [here](https://www.twilio.com/docs/video/tutorials/user-identity-access-tokens#time-to-live) that "Access Tokens must be valid while joining a Room and when reconnecting to a Room due to network disruption or handoff. Therefore, we recommend that you set the ttl to the maximum allowed session length, which is currently 14,400 seconds (4 hours)."

If I use the solution you are suggesting wont it mean my users will have a bad experience "when reconnecting" or during "handoff"?

**Comment by vargad** [comment]
Indeed, that's a problem. Since revoking a JWT token is not standard and twilio doesn't seem to have any API, I guess it's not possible to revoke. I wonder how difficult would be to add a callback to twilio-video.js to allow requesting a new token for reconnect.

**Comment by dannnnthemannnn** [comment]
Would be great to hear from someone at Twilio if there is anything that can be done (or plans for something to be done) to support this use case.

**Comment by ykhodosh** [comment]
@dannnnthemannnn, I think the problem boils down to the "identity management" and today Twilio Video delegates that responsibility to your application. Although we support participant disconnect via API, banning would need to happen at the identity management layer. The best you can do right now is exactly what was suggested in this thread:
- Only hand out JWT tokens to the identities, which you've determined have not been banned
- Keep the token TTL to a minimum
- Design your application to re-authenticate a user during reconnect (you should get a callback from JS SDK when it's reconnecting and this is where you can check if a user was banned)
- Use status callbacks to monitor and kick out "banned" users that are trying to "work around" your applications' logic

As you correctly pointed out, people that "know what they are doing" can try and bypass these controls, but if you follow the above guidelines, it should make it difficult enough for everyone else. My apologies for the inconvenience.

We're going to close this issue, but feel free to reopen it (or open a new one) if you have follow-up questions.
