### ISSUE TITLE
Is it possible to set aspect ratio?

### ISSUE THREAD

**Issue by vincentwoo** [twilio/twilio-video.js#124]
I'm having trouble finding something corresponding to aspect ratio or width + height. CreateLocalTracks seems to only take booleans for whether to acquire a track or not.

**Comment by manjeshbhargav** [comment]
@vincentwoo ,

We can specify constraints in `createLocalTracks()` like so:
```javascript
const { createLocalTracks } = require('twilio-video');

const tracks = await createLocalTracks({
  video: <MediaTrackConstraints>
});
```
[MediaTrackConstraints](https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints)

I noticed that the docs don't mention this. Thanks for bringing this to our notice. We'll update the docs as required.

Thanks for using the Twilio Video JS SDK! Please feel free to post any other questions you might have on this forum.

Manjesh Malavalli

**Comment by vincentwoo** [comment]
This is pretty clunky and it leaks the native abstraction. Can you consider adding a default media constraint object to twilio-video?

**Comment by vincentwoo** [comment]
Also, can you resize a stream?

**Comment by manjeshbhargav** [comment]
@vincentwoo ,

* Regarding adding our on default constraints, our default behavior is to treat them as booleans and set them to true, so the standards-defined default constraints are applied. The reason we went with the native constraints is that they are well defined by the standard, and we need not re-invent the wheel by introducing our own constraints.

* I'm not sure whether you can resize a stream after creating it. At least not directly.

Please let me know if you have any further questions.

Thanks,

Manjesh Malavalli

**Comment by markandrus** [comment]
@vincentwoo the `applyConstraints` API (which also takes MediaTrackConstraints) should let you resize a MediaStreamTrack. It currently works in Firefox, but not Chrome. Once Chrome lands support for this, I think we will consider adding a new public API to our LocalTrack classes, mirroring this functionality.

Check out this [JSFiddle](https://jsfiddle.net/j1wjfoe7/1/) in both Chrome and Firefox. I'll look to see if there is a Chromium bugtracker issue for this one and add to the thread.

**Comment by markandrus** [comment]
[Issue #338503](https://bugs.chromium.org/p/chromium/issues/detail?id=338503) is marked "Fixed" as of Chrome 64. Closing.

**Comment by coding365days** [comment]
@manjeshbhargav - can you please help me in modifying the mirror view of the twilio video. I am running the twilio video quickstart (https://github.com/twilio/video-quickstart-js) in which the video view has a mirror image. The video in the app is performing the opposite of my movements. Thank you in advance.

**Comment by SandeepGitHub121** [comment]
Hi, I am also facing issue while mainitaining the video track size on the web portal.
There is no option to maintain the height and when I am reducing or increasing the width it is automatically increasing the height of the container.

**Comment by ppokharkar3** [comment]
facing same issue. Using client side rooms Angular 6. 
Whenever the video starts, it auto-sizes the dimensions of remote and local video.. Any hints for resolving this? @manjeshbhargav

**Comment by sboudouk** [comment]
I think i'm facing the same issues as @ppokharkar3 and @Sparashar1408, here's a video about it :

https://photos.app.goo.gl/yU4FL1b2uC76hKg28

Am I doing something wrong ? I feel like Twilio is changing the remote participant size with CPU/Bandwith values, but, how do I set a static size so the user don't see video going crazy ?
