### ISSUE TITLE
Twilio Video Room Call Peer to Peer, Mobile connects & web disconnects and vice versa

### ISSUE THREAD

**Issue by NumanGillani-jackys** [twilio/twilio-video.js#1251]
Since a long time, I'm trying to fix an issue in Twilio Android SDK and PHP Backend.

I used an Access Token, and it works fine. If I connect from Mobile it's showing me the video from front camera, and if I connect from my Laptop browser via LocalHost, it shows me video of mine. but when I try to connect from Mobile and Laptop at a same time, the other side disconnected.

i.e. If I connect from Mobile first, then I login from Laptop, Mobile will be disconnected. and vice versa.

Is anyone else has faced the same problem?

**Comment by swarnava** [comment]
Hi @NumanGillani-jackys,

This repository is for Javascript SDK. Could you file an issue to our Android SDK repository [here](https://github.com/twilio/video-quickstart-android/issues/new) or email us at help@twilio.com? Thank you!

**Comment by manjeshbhargav** [comment]
@NumanGillani-jackys ,

This is most likely because you are using the same identity string while creating tokens for both the mobile and desktop Participants. Please use different identity strings.

Thanks,

Manjesh
