### ISSUE TITLE
Canvas.captureStream() as a VideoTrack - Remote Participants see only black from the stream

### ISSUE THREAD

**Issue by mattdemichele-pearson** [twilio/twilio-video.js#1256]
**Describe the bug**
When creating a video track from a canvas.captureStream(), the remote participants only sees black. However the local participant can see the captured track as expected.

[The idea behind this is taken from here](https://github.com/twilio/twilio-video.js/issues/317#issuecomment-395175070)

**To Reproduce**

[I created a fork from your twilio-video-app-react repo to demonstrate the bug.](https://github.com/mattdemichele-pearson/twilio-video-app-react)

The fork is very simple, it draws a canvas on the page with a square, and attempts to publish a new LocalVideoTrack with the canvas.captureStream() as a source.

1. [Get code from fork here](https://github.com/mattdemichele-pearson/twilio-video-app-react) and set up environment variables as normal.
2. Run client/server
3. Open two tabs to the localhost client.
4. In the first tab, join as "canvas" name, the room name can be anything. The name as "canvas" is specifically needed though.
5. Here you will see that the canvas captureStream gets displayed correctly side by side with your webcam.
    **NOTE: you need to have your webcam turned on to see the canvas capture, which is simply a limitation of my basic example. The Publications/VideoTracks won't get rendered without it**
4. In the second tab, join the same room as before but with another user of any other name.
5. Here you will see that the VideoTrack from the canvas is completely black.

**Expected behavior**
Publishing a canvas.captureStream() as a VideoTrack should work for remote participants.

**Screenshots**
Local "canvas" user where it works: 
![Screen Shot 2020-10-28 at 2 36 05 PM](https://user-images.githubusercontent.com/73609677/97481485-45c8ae80-192b-11eb-8b34-3d1d3a381b07.png)

Remote "any" user where it is broken:
![Screen Shot 2020-10-28 at 2 36 38 PM](https://user-images.githubusercontent.com/73609677/97481484-45301800-192b-11eb-8440-6595434a1fc6.png)

**Environment:**
 - OS: MacOS Catalina Version 10.15.3
 - Browser: Chrome 86.0.4240.111, Firefox 81.0.1, 
 - App Version: latest from twilio-video-app-react repo
 - SDK Version: 
        "twilio": "^3.39.3",
        "twilio-video": "2.8.0-beta.2",
 - Node.js version: 10.17.0

**Additional context**
If I had to guess, I think it has to do with a failure to handle the more specific "CanvasCaptureMediaStreamTrack" instead of "MediaStreamTrack". 
I tried comparing this to the way Screen Share works and that seemed to be the only real difference.
I could be totally wrong about that though.

**Comment by manjeshbhargav** [comment]
Hi @mattdemichele-pearson ,

Thanks for writing in with your issue. I ran your app and followed your steps, but I did not see any canvas stream, but the normal local video feed. Can you point me to the correct source of your reproduction?

Thanks,

Manjesh

**Comment by mattdemichele-pearson** [comment]
Sorry about that I just realized I never pushed the test code to my fork. The code is there now, @manjeshbhargav.

Thanks!

**Comment by mbodge** [comment]
@mattdemichele-pearson Did you ever figure out how to make this work?

**Comment by makarandp0** [comment]
Hey @mbodge, Looks like the transparency is lost just after acquiring stream from canvas and rendering on video element - so it seems that its unrelated to WebRTC - This sample demonstrates it:  https://webrtc.github.io/samples/src/content/capture/canvas-video/

Not yet sure what is causing this.

**Comment by makarandp0** [comment]
Hello @mbodge, sorry for long silence on this - I experimented again with this, and looks like alpha channel is [not supported](https://groups.google.com/g/discuss-webrtc/c/i0jci-N1BA0?pli=1) by VP8. Alpha values seem gets omitted from the remote frames .  

And some clarification on my earlier comment - I found that the transparency is not lost when a stream is captured from canvas element - it is omitted only when canvas's capturing context was created with alpha=false https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/getContext
so 
```
canvas.getContext('2d', { alpha: false });
...
return canvas.captureStream()
```
will produce a local stream just like how it would look on remote. 

I suggest as a workaround fill the canvas rect with opaque color, and not depend on preserving alpha when publishing such canvas stream

Thanks,
Makarand

**Comment by cindyloo** [comment]
it would be nice to know what the best practice is to utilize the `canvas.captureStream`
eg, if I want to keep the original localTrack, which is the video track, and then add the canvas track and publish them both to Twilio.
in which hook is it most advisable to do this? I am getting a black canvas locally as well

code:
```
useEffect(() => {
let canvasOverlayBuff = document.querySelector(`#${canvasName}`) as any;
      let cStream = canvasOverlayBuff.captureStream(5);

      // github https://github.com/twilio/twilio-video.js/issues/1256
      canvasOverlayBuff.getContext("2d", { alpha: false });

      let canvasTrack = new LocalVideoTrack(cStream.getTracks()[0], {
        logLevel: "info",
        name: canvasName,
      });


      // this causes blank canvas. looks like the faces are read, but nothing is drawn
      //canvas is small and nothing is drawn to it
      const options = {
        logLevel: "webrtc",
        name: 'anonPublish'
      } as any;
      (participant as Video.LocalParticipant).publishTrack(canvasTrack, options);
}, [*toggleOnUi**]);

```
