### ISSUE TITLE
Own video shown as black on Xiaomi Note5 Pro (chrome)

### ISSUE THREAD

**Issue by metalelf0** [twilio/twilio-video.js#1261]
Hi, we're doing some tests with a Xiaomi Note5 Pro Android device.

Using the latest available Chrome (86.0.4240.110), own video is always displayed as black, and the other peer receives no video. We're using the following code to display local video:

```js
    const localVideoTrack = Array.from(this.room.localParticipant.videoTracks.values())[0].track;
    const video = document.getElementById('local_video').firstChild;
    video.appendChild(localVideoTrack.attach());
```

And this other code to get the video device:

```js
          navigator.mediaDevices
            .getUserMedia({
              audio: {
                echoCancellation: true,
                noiseSuppression: true
              },
              video: { facingMode: 'user' },
            })
            .then((mediaStream) => {
              return Twilio.Video.connect(data.token, {
                name: appointmentHash,
                tracks: mediaStream.getTracks(),
              });
```

Some notes:
- the device camera obviously works fine;
- I'm using version 2.7.2 of the Twilio video javascript SDK;
- the same code works fine on other devices (specifically, a Xiaomi Mi9);
- there is no error in our console, the Twilio connection is correctly established and `room.localParticipant.videoTracks` is set correctly;
- the Android SDK works fine on this device, but the JS SDK doesn't;
- the [webrtc testing page](https://webrtc.github.io/samples/src/content/getusermedia/gum/) reveals no error, just a warning about IPv6, but I get the same warning on the other working device; it says there is "1 black frame on 61", whatever this means;
- I tried with P2P rooms and group rooms, but I still get the same error.

Let me know if I can provide any further info.

Kind regards,

**Comment by manjeshbhargav** [comment]
Hi @metalelf0 ,

Sorry for the delayed response. Can you monitor the `muted` property of the LocalVideoTrack and let me know what happens:
```js
console.log('Muted:', localVideoTrack.mediaStreamTrack.muted);
localVideoTrack.mediaStreamTrack.onmute = () => console.log('Muted:', localVideoTrack.mediaStreamTrack.muted);
localVideoTrack.mediaStreamTrack.onunmute = () => console.log('Muted:', localVideoTrack.mediaStreamTrack.muted);
```

**Comment by metalelf0** [comment]
Hi @manjeshbhargav , we solved this issue on our end. The problem was due to the fact that we opened two video streams, and apparently some mobile devices can only handle one video stream at a time. The strange thing was that with the exact same browser and OS, another device (a Xiaomi MI9) could work flawlessly even with two connections, so we originally ruled out that as a possible cause of trouble.

I'd suggest to add this point to the documentation of the JS SDK. Thanks!

**Comment by manjeshbhargav** [comment]
Hi @metalelf0 ,

We do mention this in our [best practices guide](https://www.twilio.com/docs/video/build-js-video-application-recommendations-and-best-practices#acquiring-camera-in-mobile-browsers), but you're fight. I will create a ticket to add this to the documentation for `createLocalTracks()` and `createLocalVideoTrack()`.

Thanks,

Manjesh
