### ISSUE TITLE
Camera is not working on Samsung Note 10+ with Firefox

### ISSUE THREAD

**Issue by hantonelli** [twilio/twilio-video.js#1264]
- [X] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [X] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [X] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii) or sensitive account information (API keys, credentials, etc.) when reporting this issue.

We are experiecing this issue in our app, but the issue can be reproduce using https://github.com/twilio/twilio-video-app-react.

**Expected behavior:**
You go to the prejoin and you can see your camera..

**Actual behavior:**
You go to the prejoin and you can't see your camera..
Video 
![image](https://user-images.githubusercontent.com/18269845/98011025-46f85080-1def-11eb-8cfe-c9fd9527d59e.png)

**Logs:**
This log is from our system, as there is no error in the twilio react referece app, just the message of the attached image.
Uncaught (in promise)
MediaStreamError { name: "NotFoundError", message: "The object can not be found here.", constraint: "", stack: "" }

**Software versions:**
 - [X] Browser(s): Firefox
 - [X] Operating System: Android
 - [X] twilio-video.js: 2.8.0-beta.2
 - [X] Third-party libraries: React

This issue is related to:
https://github.com/twilio/twilio-video.js/issues/1136

**Comment by manjeshbhargav** [comment]
Hi @hantonelli ,

What you are reporting most likely means that Firefox does not have permission in the system settings to access the camera.
Can you verify the camera permissions in the system settings for Firefox?

Thanks,

Manjesh

**Comment by manjeshbhargav** [comment]
Hi @hantonelli ,

Sorry for the delayed response, but did you say that your app asks for the mic permission but not camera permission? That would explain why camera is not accessible. The error you have reported:
```
MediaStreamError { name: "NotFoundError", message: "The object can not be found here.", constraint: "", stack: "" }
```
points to the fact that Firefox does not detect the device camera. Can you try running this [getUserMedia open source demo](https://webrtc.github.io/samples/src/content/getusermedia/gum/) to see if you can access the camera in that app?

Thanks,

Manjesh

**Comment by hantonelli** [comment]
Hi @manjeshbhargav ,

Sorry for the late response. As you point out it seems to be a device issue.

![samsung_note_10_issue](https://user-images.githubusercontent.com/18269845/107252111-f0716280-6a2c-11eb-94b2-bbb99bb66ba4.png)

Could it be raise to Samsumg? As it was a popular phone I would expect that a few users will experience that issue.

Thanks,
Horacio

**Comment by manjeshbhargav** [comment]
Hi @hantonelli ,

Right now, we work only with browser vendors in order to raise issues with them. Since you have access to the device in question, I recommend that you file a bug in [Bugzilla](https://bugzilla.mozilla.org/home) to see if the Firefox engineers can do something about it.

I'll close this issue for now, but we can continue our conversation here.

Thanks,

Manjesh
