### ISSUE TITLE
Switch camera is not working on Samsung Note 10+ with Chrome

### ISSUE THREAD

**Issue by hantonelli** [twilio/twilio-video.js#1265]
- [X] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [X] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [X] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii) or sensitive account information (API keys, credentials, etc.) when reporting this issue.

We are experiecing this issue in our app, but the issue can be reproduce using https://github.com/twilio/twilio-video-app-react.

**Expected behavior:**
Press switch camera.
The camara does switches.

**Actual behavior:**
Press switch camera.
The camera doesn't switch.

**Logs:**
log.js:138 2020-11-03 16:52:19.151Z | ERROR in [LocalVideoTrack #4: 81920ca9-3906-46e5-8ec7-15e63456f611]: Failed to re-acquire the MediaStreamTrack: DOMException: Could not start video source {width: 1280, height: 720, frameRate: 24, facingMode: "environment"}
value @ log.js:138
value @ log.js:229
(anonymous) @ localmediatrack.js:201
Promise.catch (async)
value @ localmediatrack.js:200
value @ localmediatrack.js:278
value @ localvideotrack.js:166
(anonymous) @ FlipCameraButton.tsx:31
....

**Software versions:**
 - [X] Browser(s): Chrome
 - [X] Operating System: Android
 - [X] twilio-video.js: 2.8.0-beta.2
 - [X] Third-party libraries: React

This issue is related to:
https://github.com/twilio/twilio-video.js/issues/1136

**Comment by manjeshbhargav** [comment]
Hi @hantonelli ,

Please follow the discussion in #1180 . I will close this issue as a duplicate.

Thanks,

Manjesh

**Comment by hantonelli** [comment]
Hi @manjeshbhargav,

The issue is still happening with Samsung Note 10+ on Chrome using the release 2.9.0
It seem that the switch is working, but is switching to the wrong camera.


This are the cameras:
![cameras](https://user-images.githubusercontent.com/18269845/101195622-997b9580-3657-11eb-85d5-3e9fbcbc1a30.png)

When using the switch button, to switch to the facing back camera, it fails. The screen get black and the camera in the video input list is not updated.

When doing the manual video input selection using the video input list, we are able to select the facing back camera (camera 2, 0 facing back). One thing to notice is that if we select the camera 2, 4 facing back from the video input list, the video is all black also, and the option goes back to select the previous options, that is the same behavior that when we use the switch.

Thanks,
Horacio
