### ISSUE TITLE
Reduce bundle size

### ISSUE THREAD

**Issue by gregjoeval** [twilio/twilio-video.js#1272]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**The problem**
twilio-video (2.7.1) has a bundle size of 292.74 KB, which is almost 10% of my app's total bundle size. I would expect this to be much less or provide a way to tree-shake unused code.

![image](https://user-images.githubusercontent.com/12819403/99020180-f1791d80-252b-11eb-9b65-848a5c6e04b7.png)

To create the html page shown in the image above I built my app, which depends on twilio-video, and used `source-map-explorer` to view the bundle source map breakdown.

**Software versions:**

 - [x] Browser(s): n/a
 - [x] Operating System: n/a
 - [x] twilio-video.js: 2.7.1
 - [x] Third-party libraries (e.g., Angular, React, etc.): React

**Comment by makarandp0** [comment]
Hello @gregjoeval, Thank you for writing about this and sharing this map showing breakdown of module sizes. Looking the usage I do not see anything that can help reduce the size of twilio-video at this point.  

But we will keep this in mind in future when we take up some restructuring of the code.

**Comment by gregjoeval** [comment]
Thanks for the reply! If you were able to support [ESM](https://dev.to/iggredible/what-the-heck-are-cjs-amd-umd-and-esm-ikm) then that would most likely suffice. I personally use [tsdx](https://github.com/formium/tsdx) for my typescript packages and I'm sure you would be able find something similar for this project (since it does not use typescript).

**Comment by newtriks** [comment]
@makarandp0 I agree with @gregjoeval last comment. The transition to using ESM is becoming more and more popular and I'm using Snowpack and integrating Twilio Video based on the current architecture has been problematic to say the least.

**Comment by MonstraG** [comment]
My NextJs application includes video calls, chat and audio calls, but has nothing else inside it, it's a big wrapper for those tree features, As such, twilio services uses 175 kb gzipped, out of 546.01 kb of whole app, that's about a third. While this is not just twilio-video issue, I couldn't find a better place to chime in on bundle size issue.

<details>
  <summary>bundle-analyzer client result</summary>
  
![twilio_size](https://user-images.githubusercontent.com/17963791/112809852-ea464c80-9093-11eb-9928-f17f1a50aeca.png)
</details>

**Comment by Steakeye** [comment]
Is ESM support on the roadmap yet?

**Comment by manjeshbhargav** [comment]
@Steakeye ,

Sorry for the delayed response. As of now, it is not on the roadmap, but we will definitely look into it when we have some cycles free.

Thanks,

Manjesh
