### ISSUE TITLE
[Question] Understanding of published tracks in the Room logs

### ISSUE THREAD

**Issue by athollon** [twilio/twilio-video.js#1278]
We are currently using:
- twilio-video@2.7.0
- ad-hoc group room

For each user, we have:
- two datatracks: one reliable, one unreliable
- one audiotrack
- one videotrack when user wants to do screensharing

We are publishing tracks:
- when the user connects
- when the visibility has changed on device xr session (which should not happen hundred of time)

When looking at the logs in twilio video console, we are seeing many published tracks. We were wondering if there was a huge issue in our client application with twilio usage or if we do not understand what is the published tracks metrics. We would have expect 4 published tracks for each user but not hundreds...

Here are some rooms in which you can see the issue but it is general and concerning all our twilio rooms
- RMa4dc4c071f876399fa559a688aa0c84d
- RMdea271fa29ad238704774edb6fbb564c
- RM59f3142270ac310e36cbbcb4d377257e

Is it possible to determine what types of track are published to determine the place in code where we are wrong if it is link to our handling of media streams ?

Thank for your reply

**Comment by makarandp0** [comment]
Hello @athollon, Thank you for writing about your question. 

I looked at room-sids that you mentioned and I do not see hundreds of track published in these rooms. I see 3 or 4 tracks published per user. Why do you think there are 100s of published tracks? Can you attach logs that showed too many published tracks. I suspect the logs mention same tracks multiple time as they get negotiated multiple times.  You can verify that by noting the track sid - each published track gets a unique track sid ( for example: `MT16493f9a98112f96be737784f1d1f95f`)

Let us know if that answers your question,
Thanks,
Makarand

**Comment by athollon** [comment]
I think there are 100s of published tracks because of twilio video room details which can be seen in the twilio console.
In the room detail in the column "PUBLISHED TRACKS" , I can see that there is hundreds of published tracks which seems to be wrong as you stated.

**Comment by makarandp0** [comment]
Thank you @athollon for the update - We looked into this and it turns out to be a bug. Console is listing "number of messages received on data track" for the column titled "PUBLISHED TRACKS", which explains the large numbers you see there.

Will keep you updated as the bug is fixed.
Thanks,
Makarand

**Comment by makarandp0** [comment]
Closing as this is fixed in recent version of console.
