### ISSUE TITLE
Switching between wifi and 3G kills video 

### ISSUE THREAD

**Issue by theDude30** [twilio/twilio-video.js#128]
When starting audio video and switching between networks it will freeze the videos and even when doing stop/start will not recover the video

 - [X ] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [ X] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ X] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.

**Code to reproduce the issue:**

**Expected behavior:**

Switching between networks in mobile is very common. We excpect that video could be reovered as soon as the internet is back.

**Actual behavior:**

Start audio/video with PC and Mobile, when audio video is connected and working switch between wifi to 3g or the other way around.
This will cause a freeze to the video without a chance to recover from that point( we can confirm that internet was working after the network switch)

**Software versions:**

 - [X ] Browser(s): PC Chrome version 59.0.3071.115 (Official Build) (64-bit) , Mobile Chrome version 58.0.3029.83
 - [X ] Operating System: OSX 10.12.5 (16F73), Mobile Android 7.0
 - [X ] twilio-video.js: 1.0
 - [ ] Third-party libraries (e.g., Angular, React, etc.):

**LOGS:**
PC: 
[pc_logs.txt](https://github.com/twilio/twilio-video.js/files/1104769/pc_logs.txt)

Mobile:
[phone_logs.txt](https://github.com/twilio/twilio-video.js/files/1104771/phone_logs.txt)

**Comment by rfbrazier** [comment]
Hello @theDude30, thanks for reporting this issue. This is a known limitation in our JavaScript SDK--one that is unfortunately missing from our changelog issues list (we'll add it now). 

We do plan to address this problem, but we don't have a release timeline set at this time. Will keep this issue open and reference it in the changelog update.

**Comment by apurcaroiu** [comment]
Hi,
Is this supported in the Android SDK or it is a limitation across all platforms?
I am using  version 1.3.7 of  the Android one and the video is killed too there during  connection changes between Wifi and 3G.

Thanks!

**Comment by manjeshbhargav** [comment]
Hi @theDude30 , @apurcaroiu ,

[twilio-video.js@2.0.0-beta6](https://github.com/twilio/twilio-video.js/blob/2.0.0-beta6/CHANGELOG.md) now supports Signaling Reconnection due to Network Disruptions behind an experimental ConnectOptions flag. Please try it out.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by manjeshbhargav** [comment]
Hi @theDude30 , @apurcaroiu ,

Network Reconnection States and Events are now generally available in [twilio-video.js@2.0.0](https://github.com/twilio/twilio-video.js/blob/2.0.0/CHANGELOG.md).

Manjesh Malavalli
JSDK Team
