### ISSUE TITLE
Low quality Video in P2P rooms

### ISSUE THREAD

**Issue by arnoldsimha** [twilio/twilio-video.js#1280]
Hello,
We developed a video 1:1 meeting tool for our product which taking an integrated part of our product.
Unfortunately, we are facing video quality issues although we configured everything according to the documentation:
https://www.twilio.com/docs/video/tutorials/developing-high-quality-video-applications#desktop-browser-in-p2p-rooms

This is the connect options that we are using:
```javascript
const connectOptions: ConnectOptions = {
        name,
        tracks,
        dominantSpeaker: true,
        maxAudioBitrate: 16000,
        video = {
          height: 720,
          frameRate: 24,
          width: 1280,
          aspectRatio: 1280 / 720
        },
        bandwidthProfile: {
          video: {
            renderDimensions: {
              high: { width: 1280, height: 720 },
              standard: { width: 640, height: 480 },
              low: { width: 320, height: 240 }
            }
          }
        }
      };
```

Our local track really looking sharp, but the remote participant video is blurry and seems as low quality (even on high network).

I'll appreciate your feedback.
Thank you

**Comment by anil1712** [comment]
I am also getting the same issue. @arnoldsimha did you get any solution for this?

**Comment by jokuja** [comment]
also having same issue, when debugged, remote video had very low resolution: 
`dimensions: {width: 320, height: 180}`

**Comment by arnoldsimha** [comment]
@anil1712, unfortunately, I couldn't find a solution to that. I hope someone from the team will respond here

**Comment by manjeshbhargav** [comment]
Hi @arnoldsimha ,

Sorry for the delayed response. FYI, `dominantSpeaker` and `bandwidthProfile` are available only in Group Rooms. Regarding your issue, can you provide a Room SID to start our investigation?

Thanks,

Manjesh

**Comment by arnoldsimha** [comment]
@manjeshbhargav thank you for your response. I will look for the ID
