### ISSUE TITLE
It take long time to connect to Twilio room

### ISSUE THREAD

**Issue by vinguyen** [twilio/twilio-video.js#1289]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

Hi there, 
We are using twilio-video js with Reactjs and we are facing with problem that sometime it take more than 10 seconds ( even more than 60 seconds ) to connect to Twilio room on all kinds of devices and Operating Systems.

I'll appreciate your feedback.
Thank you

**Software versions:**

 - [x] Browser(s): Chrome, Safari
 - [x] Operating System: iOS, Mac, Android, Window
 - [x] twilio-video.js: 2.7.2
 - [x] Third-party libraries (e.g., Angular, React, etc.): ReactJS

**Comment by makarandp0** [comment]
Hello @vinguyen, Thank you for reporting this issue. Can you share some room-sids that took long time to connect? 10 seconds is bit high, and I am wondering if the participants are using sub-optimal signaling region.

Thanks,
Makarand
