### ISSUE TITLE
Consistent ICE warnings for Windows in Chrome and React-Native app

### ISSUE THREAD

**Issue by lidia-saf** [twilio/twilio-video.js#1290]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Expected behavior:**

We have a peer-to-peer connection between browser in the laptop and React-Native app on iPhone that should last for 50-60 minutes.

**Actual behavior:**

We noticed that on older iPhones (like iPhone 7, iPhone 7 Plus) after 9-10 minutes into the call, there are ICE warnings:  

```
WARN in [PeerConnectionV2]: ICE Connection Monitor detected inactivity
WARN in [PeerConnectionV2]: An ICE restart has been scheduled
WARN in [PeerConnectionV2]: Attempting to restart ICE

```
After that video of remote participants goes freezing on both sides. After 2 minutes waiting, the remote participant video sometimes unfreezes for the website, but remains frozen for the React-Native app. Also, older iPhones get hot and reduce battery charge fast. 

I found this issue https://github.com/twilio/twilio-video-ios/issues/108 and tried changing video codec to H.264 inside React-Native app and browser. It did help a little with React-Native app to reduce the hotness of the phones, but ICE warnings and video of remote participants freezing persisted.

**Connection options:**

- for the website in the laptop: 
 const options: ConnectOptions = {
        audio: true,
        maxAudioBitrate: 16000,
        video: { height: 720, frameRate: 24, width: 1280 }
      };

- for the React-Native app:
    twilioVideoRef.current?.connect({
      accessToken: token
    });

**Software versions:**

 - [x] Browser(s): Chrome 86
 - [x] Operating System: Windows 10
 - [x] twilio-video.js: ^2.7.3
 - [x] Third-party libraries (e.g., Angular, React, etc.):
for the website:
- React

for the React-Native app:
- react-native
- react-native-twilio-video-webrtc (1.0.2-1):
   - React
   - TwilioVideo (~> 3.7)

**Comment by manjeshbhargav** [comment]
Hi @lidia-saf ,

Thanks for writing in. Unfortunately, we do not support the React Native platform at this time. Sorry about the inconvenience.
