### ISSUE TITLE
ERROR - 53405 - Media connection failed or Media activity ceased for Video.connect

### ISSUE THREAD

**Issue by mc4rol9** [twilio/twilio-video.js#1294]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii) or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

```js
 await Video.connect(accessToken, connectOptions)
        .then(room => {
          sessionStorage.setItem('accessToken', true)
          updateCallRoom(room)
          setView(2)
        }).catch(err => {
          Sentry.captureException(err)
          history.replace('error')
          setView(1)
        })
```

**Expected behavior:**
The connection with Twilio happens in a Waiting Room. It´s expected the user to be redirected to the Main Calling Room to connect with another participant.

**Actual behavior:**
It happens only with a few users, but the occurrence has increased in the last 15 days.

The catch block is getting the following error: **Media connection failed or Media activity ceased**.
I don´t have a browser log. I´m getting the error from Sentry and I found 

**Software versions:**
I am using React. It´s happening since Twilio SDK 2.7 and still with version 2.8.

Browsers and Operating System from the last 15 days:

* Chrome Mobile 86.0.4240 - Samsung - Android 8, Android 10 - 2 events
* Chrome 86.0.4240 - Windows 10 - 2 events
* Mobile Safari 14.0.1 - iPhone - iOS 14.2 - 1 event
* Mobile Safari 14.0 - iPhone - iOS 14.1 - 1 event
* Mobile Safari 11.0 - iPhone - iOS 11.4 - 1 event
* Safari 14.0. - Mac OS X 10.15.6 - 1 event
* Safari 14.0.1 - Mac OS X 10.15.7 - 3 events
* Chrome Mobile 87.0.4280 - Samsung - Android 10 - 1 event
* Chrome Mobile 84.0.4147 - Samsung - Android 5.1.1 - 1 event

 - [x] Browser(s):
 - [x] Operating System:
 - [x] twilio-video.js:
 - [x] Third-party libraries (e.g., Angular, React, etc.):

**Comment by mc4rol9** [comment]
Hello! Any news on this one? @manjeshbhargav 
thankx

**Comment by manjeshbhargav** [comment]
Hi @mc4rol9 ,

Sorry for the delayed response. Can you share a few Room SIDs where this has happened? If you are getting error 53405 while connecting to a Room, then it must be due to one of the following reasons:

* WebRTC is not supported by the browser
* Incorrect ICE server URLs being passed to the RTCPeerConnection

So, some Room SIDs would be good to get started.

Thanks,

Manjesh

**Comment by mc4rol9** [comment]
Hi @manjeshbhargav,

Thank you very much for your response.

If there are only those two possible reasons, I'm sure it's not because of the browser support, once this verification is made in a step before the connection with Twilio. So, if the browser isn't compatible with WebRTC and Twilio the user is redirected to an error page.

I found some Room SIDs from my Sentry logs: RM2ae90f57042519fe625cef01e91c1162, RMb4c113deed9f35c0d92f35ef28a84846, RM31fcb04fb8b715fec6ff6af76dc08fac

Thank you,

Carolina.

**Comment by manjeshbhargav** [comment]
Hi @mc4rol9 ,

Sorry for the delayed response. I could not extract the logs for the Rooms you shared here because we delete the logs after 30 days. Is it possible for you to share some more recent Room SIDs?

Thanks,

Manjesh

**Comment by mc4rol9** [comment]
Hello @manjeshbhargav,

Yes, it took 2 months to verify the SIDs I shared. :-)
The error recurrence has stopped.

Thank you!
