### ISSUE TITLE
Share Screen

### ISSUE THREAD

**Issue by oscarcornejo** [twilio/twilio-video.js#1302]
Hi!, I'm integrating the function screen sharing, I follow the steps mentioned in your articles, but failed to show the screen that I share, I'm using Reactjs (without typescript). There is some support for this problem.

I stay tuned, thank you.
Greetings!

**Comment by PikaJoyce** [comment]
Hi @oscarcornejo!

Thanks for opening this issue! Just as a heads up, I'm going to close the same issue opened [here](https://github.com/twilio/video-quickstart-js/issues/161) so we can continue the discussion on this thread instead. I see that you've checked out the React App! 

Just repeating for clarification, do you have any errors that are showing for you on the console? If so, please share them here and we can try taking a look at it! 

Regards,
Joyce

**Comment by PikaJoyce** [comment]
Hey again @oscarcornejo!

There hasn't been any activity here for several months, and I believe Collin as responded to you as well, so I'll be closing out this issue now. Again, please feel free to continue our conversation here if you're still having issues.

Have a great weekend!
Joyce
