### ISSUE TITLE
Robotic voice in Chrome on MacBook Pro

### ISSUE THREAD

**Issue by CyranMS** [twilio/twilio-video.js#1304]
Any ideas why this happens anad what we can do to fix this?

**Expected behavior:**

- You sound nicely when joining a meeting. (if jitter and packet-loss is alright).
- You sound nicely when disconnecting airpods. (if jitter and packet-loss is alright).

**Actual behavior:**

I connect to a meeting. I am heard nicely. 
We have two occurrences:
1. You sound like a robot from the start 
2. You sound like a robot if you disconnect your airpods during meeting.
3. Every participant will hear you like thaat

Workaround: If you refresh your browser you are being heard perfectly fine. 

On Chrome v.87.0.4280.67
Computer: MacBook Pro
Codecs: H.264 and Opus
Twilio SDK: 2.7.3
Room SID: RM7a5529e02fc2b996cfbd3973ee90bdb7
Large Group room with gll

Video: https://share.vidyard.com/watch/Vj3srSDJAP3dvzMutY9FRd?

 - [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Comment by hsavit1** [comment]
can confirm I've also been experiencing this periodically

**Comment by syerrapragada** [comment]
Hello, I have not been able to reproduce the issue. I tried multiple Airpods all seem to work just fine. One of the video I recorded using your App: https://share.vidyard.com/watch/4nLbqierteKstMJW4Kkjoo?

**Comment by hsavit1** [comment]
it's an iOS 14.2 safari issue

**Comment by CyranMS** [comment]
@syerrapragada thanks for testing. Our App is [demodesk.com ](https://demodesk.com/). It happens there. I use airpods version 1 on a MacBook Pro.

**Comment by makarandp0** [comment]
Hello @CyranMS, Today I encountered an issue where others in meeting described my voice as "Robotic" - I had joined with wired headset on MacOS 10.15.7 + Google Chrome | 86.0.4240.75. Not sure if this is related to the issue you are seeing but muting and unmuting restored the audio. Can you please see if it works in your case as well? I will keep looking out for more details on this issue.

Thanks,
Makarand

**Comment by anna-vasilko** [comment]
@CyranMS Can you please mention what is the reproducibility of this issue for you? (example: 1 out of 20 video calls have robotic audio)

**Comment by jhogervorst** [comment]
We’re having a similar issue in Safari on iPadOS (latest version) using [twilio-video-app-react](https://github.com/twilio/twilio-video-app-react). The employee (using iPadOS) is always hearing the customer (on a ‘random’ device) with a robotic voice for the first minutes, similar the the video shared by @CyranMS. Sometimes it also happens in the other direction.

**Comment by CyranMS** [comment]
Happened again on twilio v2.8 with a participant on. chrome v87. 
Refreshing browser usually helps. We do not have data on how often it happens. I assume 2-5% of meetings. Usually happens with Bluetooth devices.

**Comment by adilanchian** [comment]
We experience a similar issue on our platform. Most of our rooms have 2 - 5 participants in it at a time. We got past the Safari bug, but this chrome one is now new to us. Randomly happens and haven't been able to pinpoint it unfortunately!

We are running v2.7.2 and haven't tied upgrading yet!

**Comment by makarandp0** [comment]
@adilanchian @CyranMS, We have seen sporadic reports of this issue but have not found a reliable repro. We are tracking this issue internally (JSDK-3093). Please report if you find anything that could help narrow this down.

**Comment by smolster** [comment]
@makarandp0 Any update on that internal issue?
