### ISSUE TITLE
Firefox cannot change audio input device - NotReadableError: Concurrent mic process limit

### ISSUE THREAD

**Issue by jtbirney** [twilio/twilio-video.js#1309]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

Launch the Quickstart repo in Firefox 83.0+ and selecting a different microphone before joining the room.

I discovered this bug in my application and was able to reproduce it in the Quickstart. It appears to be a Firefox bug ([see here](https://bugzilla.mozilla.org/show_bug.cgi?id=1675538)), but I am wondering if there is a workaround. This works fine in Safari 14 and Chrome 87

**Expected behavior:**

It changes the audio input to use the selected microphone. 

**Actual behavior:**

No audio is picked up by either microphone and the following error is thrown.
```
MediaStreamError
constraint: ""
message: "Concurrent mic process limit."
name: "NotReadableError"
stack: ""
```

**Software versions:**

 - [x] Browser(s): Firefox 83.0
 - [x] Operating System: MacOS 10.15.7
 - [x] twilio-video.js: 2.7.2
 - [x] Third-party libraries (e.g., Angular, React, etc.): n/a

**Comment by nickpell** [comment]
Can confirm that this is an issue.

Oddly, switching microphones in Firefox works for me in this WebRTC sample:
https://webrtc.github.io/samples/src/content/devices/input-output/
Perhaps that suggests a workaround?

**Comment by manjeshbhargav** [comment]
Hi @jtbirney , @nickpell ,

Sorry for the delayed response. I think in recent versions of Firefox you have to stop the existing Track before creating a new Track with a different device. I think we already updated our quickstart to do this. Please try it out and let me know if it works for you. I will close this issue since I have answered your question, but we can continue our discussion here.

**Comment by MaxChu23** [comment]
Same issue here. Were you able to solve it guys?

**Comment by jan-ivar** [comment]
> I think in ... Firefox you have to stop the existing Track before creating a new Track with a different device.

I confirm this is the recommended workaround in Firefox, and matches what you'd need to do on most mobile devices for camera. LMK if anyone is having trouble using this workaround. Mozilla is working on fixing this for desktop in [bug 1238038](https://bugzil.la/1238038).
