### ISSUE TITLE
Zoom constraint does not work on android webview

### ISSUE THREAD

**Issue by savgiannis** [twilio/twilio-video.js#1312]
I print the results of 
```js
navigator.mediaDevices.getSupportedConstraints()
```
to confirm that the zoom property is there. And indeed it is, in both chrome desktop, mobile and webview.

Then, on my local track:
```js
    this.localTracks.forEach((track) => {
      if (track.kind == "video") {
        alert(JSON.stringify(track.mediaStreamTrack.getCapabilities()));
        alert(JSON.stringify(track.mediaStreamTrack.getSettings()));
      }
    });
```
I get the capabilities and the settings of the tracks. And here what happens: When I am on chrome mobile the 
```js
.getCapabilities()
```
and 
```js
.getSettings()
```
contain the zoom property and as a result the 
```js
.applyConstraints({ advanced: [{ zoom: 5 }] }) //5 is an example value
```
works as expected. But when the app runs on android webview, the zoom property in the above methods is undefined and the 
```js
.applyConstraints({ advanced: [{ zoom: 5 }] })
```
returns an error.

**Expected behavior:**

zoom constraint should exist (assuming the camera hardware supports it) when running on webview. And as a result applying a new value of zoom should work.

**Software versions:**

 - [ ] Browser(s): latest chrome desktop, latest chrome mobile, latest android webview
 - [ ] Operating System: windows, android
 - [ ] twilio-video.js: 2.8.0
 - [ ] Third-party libraries (e.g., Angular, React, etc.): Vue

**Comment by manjeshbhargav** [comment]
Hi @savgiannis ,

Thanks for writing in. It looks like your issue is related more with Android WebView and not the SDK. Please file a bug in the [Chromium bug tracker](https://bugs.chromium.org/p/chromium/issues/list) and provide me with the URL. I would be happy to star it in order to increase its visibility.

Thanks,

Manjesh

**Comment by radhakrishnan308** [comment]
Refer this
https://bugs.chromium.org/p/chromium/issues/detail?id=1249435
