### ISSUE TITLE
Choppy video in safari 14.3 + Twilio 2.7.3

### ISSUE THREAD

**Issue by hsavit1** [twilio/twilio-video.js#1321]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Expected behavior:**
Clear and smooth video

TODO

**Actual behavior:**
Video appears clear but "choppy" - the bitrate is very slow. 

TODO

**Software versions:**

 - [x] Browser(s): Safari 14.3 14.02+
 - [x] Operating System: iOS, macOS
 - [x] twilio-video.js: 2.7.3
 - [x] Third-party libraries (e.g., Angular, React, etc.): React

**Comment by bartdewulf** [comment]
+1

**Comment by manjeshbhargav** [comment]
Hi @hsavit1 ,

Thanks for writing in with your issue. To start with, can you provide some Room SIDs where you observed this behavior? Choppy video is mostly associated with bad network conditions, so I would like to take a look at our logs.

**Comment by hsavit1** [comment]
> Hi @hsavit1 ,
> 
> Thanks for writing in with your issue. To start with, can you provide some Room SIDs where you observed this behavior? Choppy video is mostly associated with bad network conditions, so I would like to take a look at our logs.

**Comment by bartdewulf** [comment]
For my case: 

- RM27b1d4b1bb7f8da51d7e4d97ed22f883
- RM7e96283daed2410b637351c973b52db4

**Comment by kim3er** [comment]
Hi!

On macOS Big Sur, Safari 14.0.2, video cuts off after about a minute, prior to that their are a few chops in an otherwise clear stream. Here is an example SID, RMc1a79ea1c2a48abf9c463da007b4c80f.

I was unable to replicate on the Big Sur 11.2 Beta, that includes Safari 14.0.3.

Both tests were carried out peer-to-peer.

**Comment by sboudouk** [comment]
> Hi!
> 
> On macOS Big Sur, Safari 14.0.2, video cuts off after about a minute, prior to that their are a few chops in an otherwise clear stream. Here is an example SID, RMc1a79ea1c2a48abf9c463da007b4c80f.
> 
> I was unable to replicate on the Big Sur 11.2 Beta, that includes Safari 14.0.3.
> 
> Both tests were carried out peer-to-peer.

Are you using React Hooks to trigger a connection to a room ?

**Comment by kim3er** [comment]
Hey @sboudouk. We're not using React at all, vanilla TypeScript.

**Comment by kim3er** [comment]
Just as a point of interest, we don't see the same issue with the WebRTC test page, https://test.webrtc.org/.

Up to this point I had assumed a Safari 14.0.2 bug related to WebRTC. Still feels like the bug is localised to Safari 14.0.2, but perhaps not related directly to WebRTC?

**Comment by manjeshbhargav** [comment]
Hi @kim3er , @bartdewulf ,

It looks like your issues are different than the one mentioned here. Can you file separate Github issues? I am closing this since the original reporter has not responded to my request for Room SIDs.
