### ISSUE TITLE
Unexpected video dimensions

### ISSUE THREAD

**Issue by vbabenko** [twilio/twilio-video.js#1327]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

I have the following setup. And I render the video with the same aspect ratio as requested in the client. Everything works fine, but sometimes I receive enlarged video (see attached screen, looks bigger 3 times, only part of the head is visible) or smaller. The first video is enlarged (the second and 3rd are fine).
![enlarged_video_censored](https://user-images.githubusercontent.com/4083910/102614428-e1f97f80-413c-11eb-9934-f56ba2d3ac4a.jpg)

```js
Video.connect(token, {
  audio: true,
  video: true,
  bandwidthProfile: {
    video: {
      renderDimensions: {
        high: { width: 480, height: 360 },
        standard: { width: 480, height: 360 },
        low: { width: 480, height: 360 },
      },
   },
 },
 networkQuality: {
   local: 3,
 },
 dominantSpeaker: true,
})
```

**Expected behavior:**
The video has the same sizes, original scale as requested in the video client

**Actual behavior:**
One video (remote stream) has a different scale.
Note: the local stream for that person looks normal and only one person sees the enlarged video. For others that remote stream looks normal.
After some time it can stabilize automatically to normal sizes.

1) Is it possible to receive a video in a different resolution/scale despite on provided configuration and when?
2) Can the Media server mess up something during mux'ing and return a corrupted stream?

**Twilio Room ID: RM6fba5272391bf7220395edfc5a329ee4**

**Software versions:**

 - [x] Browser(s): FireFox 83
 - [x] Operating System: Windows 10
 - [x] twilio-video.js: 2.8.0
 - [x] Third-party libraries (e.g., Angular, React, etc.): vue.js

**Comment by manjeshbhargav** [comment]
Hi @vbabenko ,

Thanks for writing in with your question. If I understand your question correctly, are you expecting the RemoteParticipant's video to be 480x360 since that is what you have specified in `renderDimensions`? If so, I want to let you know that `renderDimensions` is a setting you provide the media server based on which it will calculate the amount of bandwidth to allocate for your RemoteVideoTracks. It has nothing to do with the actual resolution of the RemoteVideoTrack, which depends on the capture resolution of the publisher and network conditions.

Please let me know if you need any further clarification.

**Comment by vbabenko** [comment]
@manjeshbhargav thanks for the quick response!

In this case, default browser video constraints will be applied.  
Can Twilio dynamically change them for example if the network degraded? Or what would be the cause of this (the video was scaled up and then normalized automatically after some time)?

**Comment by vbabenko** [comment]
Hi @manjeshbhargav 
Are any insights here?

Thank you,

**Comment by vbabenko** [comment]
The same issue: https://github.com/twilio/twilio-video.js/issues/1314
