### ISSUE TITLE
Signaling connection timed out

### ISSUE THREAD

**Issue by DmitryMorozov228** [twilio/twilio-video.js#1328]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Actual behavior:**

Hi Twilio Team,
We have upgraded our twilio-video-js library from 1.x to 2.7.2 using [this](https://www.twilio.com/docs/video/migrating-1x-2x) guide. I have a couple of questions that I would like to ask you:
1. We are faced with Twilio limitation in P2P/Group Rooms: maximum session length is 4 hrs. I check [this](https://www.twilio.com/docs/video/programmable-video-limits) article. After 4 hrs of active call all users are disconnected and there is no way to get video/audio streams or send a message/command in the call while the Twilio room itself exists. Twilio disconnects participants with the error 53002 - Signaling connection timed out from the Twilio.

Could you please explain the main goal of the Max Participant duration limit?
Do you, guys, have any participant's reconnection mechanism to the room after maximum session limit was reached or should we implement a custom mechanism to reconnect users to the twilio P2P/Group room on our side?

Logs:
[frontend-app-twilio-logs](https://drive.google.com/file/d/16XMNKCZNK-DL0UxCbWrofeT3MGpolOH9/view?usp=sharing)
[mobile-app-twilio-logs](https://drive.google.com/file/d/1vIoe6jGKA22ZJs9H12UGAucHI6UKjs7C/view?usp=sharing)

2. Sometimes we are faced with hearbeats fails 3 times due to low connection issue. Twilio disconnects local participant with the "Signaling connection timed out" message. We have got from the twilio the same error code - 53002.
Looks like you tries to ping the server 3 times for a short time. In such a short time users might not be able to fix their Wi-Fi connection. 
Do you have any reconnection mechanism here? 

3. One important thing is that we cannot differ two cases described above because Twilio sends the same code for "maximum session length" and "Signaling connection timed out" (53002). 
Is it possible to differ two cases so we need to update UI in our application differently depending on the cause of the gap?

**Software versions:**

 - [x] Browser(s): Google Chrome Version 87.0.4280.88
 - [x] Operating System: Windows
 - [x] twilio-video.js: 2.7.2
 - [x] Third-party libraries (e.g., Angular, React, etc.): ReactJS

**Comment by DmitryMorozov228** [comment]
Hi, guys!

Any updates here?

**Comment by manjeshbhargav** [comment]
Hi @DmitryMorozov228 ,

Sorry for the delayed response, since we are slowly catching up from our time off for the holidays. See my responses below:

> 1. We are faced with Twilio limitation in P2P/Group Rooms: maximum session length is 4 hrs. I check this article. After 4 hrs of active call all users are disconnected and there is no way to get video/audio streams or send a message/command in the call while the Twilio room itself exists. Twilio disconnects participants with the error 53002 - Signaling connection timed out from the Twilio.

> Could you please explain the main goal of the Max Participant duration limit?
Do you, guys, have any participant's reconnection mechanism to the room after maximum session limit was reached or should we implement a custom mechanism to reconnect users to the twilio P2P/Group room on our side?

All I can say is the 4 hour limit for Participants is a limit imposed on all media sessions in all of Twilio's media products. You are free to build logic into your application to rejoin the Room after the limit.

> 2. Sometimes we are faced with hearbeats fails 3 times due to low connection issue. Twilio disconnects local participant with the "Signaling connection timed out" message. We have got from the twilio the same error code - 53002. Looks like you tries to ping the server 3 times for a short time. In such a short time users might not be able to fix their Wi-Fi connection. Do you have any reconnection mechanism here?

After 3 failed heartbeats, we actually try to reconnect for 30 seconds, which is the session timeout. Can you share some SDK logs from the JS console so that I can see what exactly is going on?

> 3. One important thing is that we cannot differ two cases described above because Twilio sends the same code for "maximum session length" and "Signaling connection timed out" (53002). Is it possible to differ two cases so we need to update UI in our application differently depending on the cause of the gap?

In case of reconnection failure, the error is raised after the Room receives a "reconnecting" event. So, you can differentiate between the two behaviors by checking if you have received the "reconnecting" event or not.

Thanks,

Manjesh
