### ISSUE TITLE
dominant speaker issue

### ISSUE THREAD

**Issue by arbaazkhan5050** [twilio/twilio-video.js#1332]
room.on('dominantSpeakerChanged', participant => {
                console.log(participant)
               this.swapParticipant(participant);
  });
this function not working it only works when enable or disable audio.

**Comment by golinka** [comment]
I have this issue too. The handler doesn't trigger on group video sessions.
```
state.room.on('dominantSpeakerChanged', dominantSpeaker => {
      console.warn('Triggered dominantSpeakerChanged handler:', dominantSpeaker)
      dispatch('setDominantSpeaker', dominantSpeaker)
})
```
"twilio-video": "^2.7.2"

**Comment by golinka** [comment]
@arbaazkhan5050 I've found the reason why it's not working in one of the issues related to dominantSpeaker:
https://github.com/twilio/twilio-video.js/issues/1218#issuecomment-708675813

We didn't add `dominantSpeaker: true` options property for a connection

**Comment by manjeshbhargav** [comment]
Hi @arbaazkhan5050 ,

Audio is required for the dominant speaker to work, so this is expected behavior.
