### ISSUE TITLE
Question: Creating Local Tracks in multiple components

### ISSUE THREAD

**Issue by mding5692** [twilio/twilio-video.js#1335]
I am using React and also the Twilio-Video library v2.10.0

I just have a general question as I am using multiple components with Video and using `getLocalVideoTrack` and `getLocalTracks` at the same time in each of these components for getting video, would it affect each other? I am trying to fix this issue: https://github.com/twilio/twilio-video.js/issues/325#issuecomment-457917889 （also this one: https://github.com/twilio/twilio-video.js/issues/325#issuecomment-397687584) and I realized there were video tracks being grabbed for each of these components. Should I just `getLocalTracks` in one location and then send those tracks as props to the components or is it ok to do what is being done now?

**Comment by mding5692** [comment]
Just read through these issues: 
https://github.com/twilio/twilio-video.js/issues/1163

I guess also for un-attaching or re-attaching the local tracks to fix the issue with the Device NotReadableError error:
https://github.com/twilio/twilio-video.js/issues/558

**Comment by manjeshbhargav** [comment]
@mding5692 

Yes, that is what I would recommend. Ideally tracks should be acquired only once and passed to the React components that operate on them. This is important especially on mobile browsers, since only one LocalAudioTrack and LocalVideoTrack can be active at a time.

Thanks,

Manjesh
