### ISSUE TITLE
Twilio-video.js keeps attempting to call Configuration after call ends

### ISSUE THREAD

**Issue by vincentwoo** [twilio/twilio-video.js#134]
Even after calling twilioRoom.disconnect(), the browser will continually attempt to reach `https://ecs.us1.twilio.com/v1/Configuration`, hours after the fact (if the tab is left open). This results in many errors in the Twilio console when using a short-lived access token.

**Comment by markandrus** [comment]
Ah, good catch. Thanks for the report @vincentwoo

**Comment by markandrus** [comment]
We're testing the fix for this in [1.2.0-rc1](https://github.com/twilio/twilio-video.js/tree/1.2.0-rc1)

**Comment by markandrus** [comment]
This should be fixed now.
