### ISSUE TITLE
Crash room.disconnect

### ISSUE THREAD

**Issue by Alezhik** [twilio/twilio-video.js#1348]
I try disconnect user from the room and run room.disconnect function. After that, I have a bug -
room.js:550 Uncaught TypeError: participant._unsubscribeTracks is not a function
    at room.js:550
    at Map.forEach (<anonymous>)
    at RoomV2.stateChanged (room.js:549)
    at RoomV2.emit (events.js:157)
    at RoomV2.transition (statemachine.js:367)
    at RoomV2.preempt (statemachine.js:211)
    at RoomV2._disconnect (room.js:168)
    at RoomV2._disconnect (room.js:239)
    at RoomV2.disconnect (room.js:216)
    at Room.disconnect (room.js:164)
    at TwilioModel.disconnect (twilio.js:388)

I try to do correct disconnect user and shut down local camera and mic.

My twilio code connect with desconnect process:

  disconnect = () => {
    console.log("Run disconnect");
    this.room && this.room.disconnect();
    console.log('disconnect');
    this.room = null;
  }
  
  newRoom.on('disconnected', room => {
    console.log('run on disconnected');
    room.localParticipant.tracks.forEach(publication => {
      const attachedElements = publication.track.detach();
      attachedElements.forEach(element => element.remove());
    });
    setRoomState(room);
  });

  newRoom.once('disconnected', error => {
    console.log('Run onse disconnected',);
    setTimeout(() => setRoom(null));
    window.removeEventListener('beforeunload', disconnect);
    if (isMobile) {
      window.removeEventListener('pagehide', disconnect);
    }
  });

**Software versions:**

 - [ ] Browser(s): Chrome
 - [ ] Operating System: Linux
 - [ ] twilio-video.js: 2.10.0
 - [ ] Third-party libraries (e.g., Angular, React, etc.): React
 
 
![image](https://user-images.githubusercontent.com/14822500/105356463-1b218580-5bfc-11eb-8d8a-b2d631d38042.png)
![image](https://user-images.githubusercontent.com/14822500/105356854-9e42db80-5bfc-11eb-8a88-d4bce4181687.png)
![image](https://user-images.githubusercontent.com/14822500/105356894-ae5abb00-5bfc-11eb-8346-c3cbf99ab2b8.png)
![image](https://user-images.githubusercontent.com/14822500/105356941-c0d4f480-5bfc-11eb-8ab4-39d65b9d3f6b.png)
![image](https://user-images.githubusercontent.com/14822500/105357721-e282ab80-5bfd-11eb-9e53-4f592b4689b3.png)

**Comment by manjeshbhargav** [comment]
Hi @Alezhik ,

Sorry for the delayed response. Can you share a link to a test version of your app? Please enable SDK logging by setting `logLevel: 'debug'` in ConnectOptions. I will try and debug it from my end.

Thanks,

Manjesh
