### ISSUE TITLE
Video object is not exported for the projects using require.js

### ISSUE THREAD

**Issue by AhmerMH** [twilio/twilio-video.js#1349]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii) or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**
Use twilio-video in a project with require.js, only `Logger` module is returned.

**Expected behavior:**
The module should return both `Logger` and `Video` objects.

**Actual behavior:**
The module is inly returning

**Software versions:**

 - [x] Browser(s): Chrome, Safari
 - [x] Operating System: macOS Catalina(10.15.7)
 - [x] twilio-video.js: 2.10.0
 - [x] Third-party libraries (e.g., Angular, React, etc.): AngularJS, requireJs

**Comment by manjeshbhargav** [comment]
Hi @AhmerMH ,

Thanks for reporting this issue. I have filed an internal bug and we will work on this immediately. Please watch this space for updates.

**Comment by charliesantos** [comment]
Hey @AhmerMH , this issue has been fixed in 2.11.0.
