### ISSUE TITLE
isSupported flag retuning true for iOS 12 + Chrome 73.0.3683.68 using twilio-video 2.7.x

### ISSUE THREAD

**Issue by leojnxs** [twilio/twilio-video.js#1356]
- [ ] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [ ] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

The only information I have is that this issue occurred with an participant using iOS 12 + Chrome 73.0.3683.68. It was returning `true` on `isSupported` flag.
I could not find on `isSupported` function code, a check to ensure safari browser on iOS devices.

**Comment by manjeshbhargav** [comment]
Hi @leojnxs ,

Thanks for writing in. Can you share the `userAgent` for Chrome 73 on iOS 12?

Thanks,

Manjesh

**Comment by charliesantos** [comment]
Closing this now due to inactivity. But please feel free to follow up here and provide the requested information.
