### ISSUE TITLE
Flow annotations?

### ISSUE THREAD

**Issue by randallb** [twilio/twilio-video.js#136]
This isn't a bug but a question... we're using flow in our application to add typing. I'm going to probably end up making types for Twilio on my own at some point... is there interest/receptivity to adding flow type definitions to the library or should I just go on my own to add them?

**Comment by markandrus** [comment]
Hi @randallb,

Flow is pretty cool, and there's definitely interest on my part. FWIW, we plan to convert to TypeScript at some point in this project's future, although I don't think that'd preclude us adding support for Flow, too. I don't think writing the Flow definitions would be particularly difficult—my only questions revolve around how to manage the definitions, package them, keep them up to date, etc. I guess we'll need to push to [flow-typed](https://github.com/flowtype/flow-typed/)?

Do you have experience here? I think we're definitely open to proposals.

Thanks!
Mark

**Comment by randallb** [comment]
Flow typed would be if you guys don't want to maintain them. If you do, they'd probably live in your repo like immutable.js does: https://github.com/facebook/immutable-js/tree/master/type-definitions. I'm new to flow so I don't know how one associates the definition with the package. With TS it happens in package.json.

https://flow.org/en/docs/libdefs/creation/ -- some info but I think there's gotta be a better way to bake it along side the lib.

**Comment by randallb** [comment]
I'm finally getting around to this. It seems like you've implemented TS in #217 in v2.0, so I'll probably be doing my declaration in flow mirroring that setup. I'm going to use it to flow-typed. Not sure if anyone will want to maintain after my initial implementation? I'm going to go for a pretty comprehensive implementation, which should be pretty simple because the api docs are good enough. I guess you could implement it into your core project but then someone would probably have to care about keeping it in sync, or you'd need tooling (probably better) to do that.

**Comment by randallb** [comment]
Looking through the docs... it's obvious your docs are programmatically generated, and i'm assuming you're using docblocks to build the api docs. It wouldn't be that much of a stretch to build a flow annotation based on this process that already exists. Does this happen inside twilio internal processes? Is that process open source? Is there any way I could hook into your api doc generation process?

**Comment by manjeshbhargav** [comment]
@randallb ,

We have TypeScript definition support in our roadmap for 2020. As part of this effort, we would love to have access to whatever you have implemented in terms of Flow type declarations as well. This might help us support both in one attempt. Please let me know.

Thanks,

Manjesh Malavalli
JSDK Team
