### ISSUE TITLE
`No overload matches this call` error for `room.on(...)` after upgrading to 2.11.0

### ISSUE THREAD

**Issue by nmkedziora** [twilio/twilio-video.js#1362]
Hi there,
I get TS errors when subscribing to a room - this error started to show after upgrade to `twilio-video@2.11.0` and removal of `"@types/twilio-video": "2.7.3",`. I removed this dependency as types are now included in the library as stated in [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md#2110-january-26-2021) 
I'd appreciate any help.
Thanks!
Natalia

 - [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

```js
const roomEvents = [
  'participantConnected',
  'participantDisconnected',
  'trackSubscribed',
  'trackUnsubscribed',
  'trackDisabled',
  'trackEnabled',
  'trackStarted',
  'trackPublished',
  'trackUnpublished',
  'networkQualityLevelChanged',
  'dominantSpeakerChanged',
] as const;

export function subscribeToAllRoomEvents(room: Room, callback: () => void): void {
  roomEvents.forEach(eventName => {
    room.on(eventName, callback); // TSC fails here
  });
}
```

**Expected behavior:**
No TS errors

**Actual behavior:**
TS error as follows
```
TS2769: No overload matches this call.   The last overload gave the following error.
Argument of type '"participantConnected" | "participantDisconnected" | "trackSubscribed" | "trackUnsubscribed" | "trackDisabled" | "trackEnabled" | "trackStarted" | "trackPublished" | "trackUnpublished" | "networkQualityLevelChanged" | "dominantSpeakerChanged"' is not assignable to parameter of type '"trackUnsubscribed"'.
Type '"participantConnected"' is not assignable to type '"trackUnsubscribed"'. 
Room.d.ts(51, 3): The last overload is declared here.
```

**Software versions:**
 - [x] Browser(s): Google Chrome Version 88.0.4324.96 (Official Build) (x86_64)
 - [x] Operating System: MacOS 10.15.7
 - [x] twilio-video.js: 2.11.0
 - [x] Third-party libraries (e.g., Angular, React, etc.): React

**Comment by makarandp0** [comment]
Thank you for writing about this issue @nmkedziora. 

With 2.11.0, we have added strongly typed versions for these event handlers, You might find them more useful to  listen to events with:
```
  export function subscribeToAllRoomEvents(room: Room, callback: () => void): void {
    room.on('participantConnected', (participant: RemoteParticipant) => console.log(participant));
    room.on('participantDisconnected', (participant: RemoteParticipant) => console.log(participant));
    room.on('trackSubscribed', (track: RemoteTrack) => console.log(track));
    room.on('trackUnsubscribed', (track: RemoteTrack) => console.log(track));
    room.on('trackDisabled', (publication: RemoteTrackPublication, participant: RemoteParticipant) => console.log(publication, participant));
    room.on('trackEnabled', (publication: RemoteTrackPublication, participant: RemoteParticipant) => console.log(publication, participant));
    room.on('trackStarted', (track: RemoteTrack, participant: RemoteParticipant) => console.log(track, participant));
    room.on('trackPublished', (publication: RemoteTrackPublication, participant: RemoteParticipant) => console.log(publication, participant));
    room.on('trackUnpublished', (publication: RemoteTrackPublication, participant: RemoteParticipant) => console.log(publication, participant));
    room.on('dominantSpeakerChanged', (dominantSpeaker: RemoteParticipant) => console.log(dominantSpeaker));
    room.localParticipant.on('networkQualityLevelChanged', (level: NetworkQualityLevel|null, stats: NetworkQualityStats|null) => console.log('yes'));
  }
```

but if you want to keep your current generic handling of all events you can use something like
```
 export function subscribeToAllRoomEvents(room: Room, callback: () => void): void {
    roomEvents.forEach(eventName => {
      room.addListener(eventName, callback); // TSC fails here
    });
  }
```
  
Let me know if that addresses your issue,
Thanks,
Makarand

**Comment by makarandp0** [comment]
closing this resolved issue.
