### ISSUE TITLE
Safari 14.0.2 video freezes in under a minute on P2P

### ISSUE THREAD

**Issue by kim3er** [twilio/twilio-video.js#1365]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ ] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Expected behavior:**

Continuous video stream.

**Actual behavior:**

If one of the participants of a Peer to Peer video call is using Safari 14.0.2, thier video stream of the other participant freezes in less than a minute. The other participant can still see a live video stream of the Safari participant. Unable to reproduce on 14.0.3 RC1. We don't see the same issue with the WebRTC test page, https://test.webrtc.org/. Originally referenced in https://github.com/twilio/twilio-video.js/issues/1321.

Example SIDs:

 - RMc1a79ea1c2a48abf9c463da007b4c80f
 - RMbb140af34d02df6223206df4e259df9f

**Software versions:**

 - [x] Browser(s): Safari 14.0.2
 - [x] Operating System: macOS 11
 - [x] twilio-video.js: 2.11.0
 - [x] Third-party libraries (e.g., Angular, React, etc.): SignalR, TypeScript

**Comment by makarandp0** [comment]
Hello @kim3er, Thank you for writing about this issue.
Unfortunately, I have not been able to reproduce this  on my Safari 14.0.2 running on MacOS (10.15.7). Do you get consistent repro for this? Which version of macOS do you see this on? 

I noticed that for the room `RMbb140af34d02df6223206df4e259df9f` the safari participant lost connection and was reconnecting after ~15 seconds in the call, and wondering if that is aways the case when you see this issue repro. Can you share few more room sids where the issue repro. 

Thanks,
Makarand

**Comment by kim3er** [comment]
Hi @makarandp0, very sorry for not replying sooner! It appears you've picked you this issue in https://github.com/twilio/twilio-video.js/issues/1365. The error is not present in Big Sur 11.2 Safari 14.0.3, so our advice to our users has been to update to the latest version of Big Sur.

To answer your question, we're able to replicate the issue consistently on multiple Big Sur 11.1 14..0.2 machines.

**Comment by makarandp0** [comment]
Hello @kim3er, I am closing this old issue, as its fixed in subsequent MacOS versions. Please reopen if you see this again.
