### ISSUE TITLE
Question about detached MediaStreamTracks, HTMLAudioElements & HTMLVideoElements pilling up

### ISSUE THREAD

**Issue by bwillner** [twilio/twilio-video.js#1367]
Hi,

when memory profiling my react implementation of twilio-video app I noticed that there are detached MediaStreamTracks, HTMLAudioElements and HTMLVideoElements pilling up after a call has ended and the room was disconnected. Around 4 per call. 
Is this expected behavior?

Please let me know if you need any additional logs etc.

Thanks in advance

**Comment by charliesantos** [comment]
Hey @bwillner , thanks for reporting. Can you please export a heaptimeline using chrome dev tools? Also, how many participants are in the room? Can you please provide some steps that I can try on my end?

Thank you,
Charlie

**Comment by bwillner** [comment]
Hi @charliesantos ,
There are two participants in the room. Room type is group room. I can send you a heaptimeline of the call. The corresponding Room ID is: RM2a800e21d54bd4f12d7d0745b7bd06e3.

How should I send you the Heaptimeline? I'd rather not post it here.

If it is any help for you I probably could give you access to our testing server.

Thanks,

**Comment by charliesantos** [comment]
Hi @bwillner , 
Thank you for this additional information. You can send the heaptimeline to csantos@twilio.com if you prefer. No need to give me access to your testing server for now. I'll let you know if I need more information after inspecting the heaptimeline.

Thank you,
Charlie

**Comment by bwillner** [comment]
Have just sent you the Heaptimeline via Email.

**Comment by charliesantos** [comment]
Hi @bwillner , thank you for sending the heaptimeline. I'm also able to reproduce it. We already have an internal tracker for this and will keep you posted once we have a fix.
https://issues.corp.twilio.com/browse/JSDK-3120

**Comment by alucio-echen** [comment]
Has there been any updates to this issue? 

I believe we are seeing something similar in chrome 92 (Chrome Beta) where we get the following error in the console:  
```[Intervention] Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27```

When this happens new video / audio tracks don't play. 

Our react app is roughly based on the sample react video app and switches video publications on and off frequently during meetings (20 participants /w video & audio). It seems like each time a publication is stopped and re-started a new media player is being allocated and they are never freed. 

We are calling detach whenever the track is switched off (like in the sample app) and I've tried different combinations of stopping the playback of the element, setting the src on the video element to null, etc. but the issue remains.

This is with version 2.15.1 of twilio-video.js

**Comment by pethog77** [comment]
Seconded on @alucio-echen 's comment. We recently experienced the same with Chrome 92 which is now in the Stable branch for Chrome. Once we reach 15 participants in our Collaboration room with Simulcast on, the media tracks stop loading for users in the event and we get the error:
`[Intervention] Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27`

The Chromium developers appear to recommend using the `preload=none` on the `<audio>` HTML tag as a workaround. I am not sure if it would help with this issue:
https://groups.google.com/a/chromium.org/g/feature-media-reviews/c/ej_x3Ovqltw/m/PHwfBq0qAgAJ

**Comment by makarandp0** [comment]
Thank you for the additional information @pethog77  and @alucio-echen. We are tracking this internally (VIDEO-6336) and working on a fix with high priority. I will have some updates soon.

**Comment by charliesantos** [comment]
This has been fixed on 2.15.3. Closing.
