### ISSUE TITLE
It it possible to connect to same room from mutiple tabs?

### ISSUE THREAD

**Issue by DavidArutiunian** [twilio/twilio-video.js#1368]
I'm using `twilio-video@1.20.0` and I can't figure out whether it's possible to connect ot same room from mutiple tabs. Imagine having 2 opened tabs with incoming call. Whenever I accepct call on 1st tab, I'm recieving socket event `room-did-connect` and want to connect all other tabs to the call.  I'm trying to do this using `connect` function, but when fired it immediately kills call on all tabs except whoever has connected last. Googling this issue doesn't result in any way to solve it.

Any feedback is appreciated. Thanks.

**Comment by makarandp0** [comment]
Hello @DavidArutiunian, 

Thank you for writing about this issue. First of all twilio-video@1.x is older version of the sdk, Support for the this version ended on December 4th, 2020. Please check [this guide ](https://www.twilio.com/docs/video/migrating-1x-2x)to plan your migration to the latest 2.x version.

You should be able to connect to same room from multiple tabs. Just need to insure you are using different identity to connect from each tab. Using same identity would explain the behaviour you are seeing, where previous user (with same identity) gets disconnected. You can read more about identity and tokens [here](https://www.twilio.com/docs/video/tutorials/user-identity-access-tokens)


Thanks,
Makarand

**Comment by DavidArutiunian** [comment]
@makarandp0 but will this approach duplicate same participant connected twice in a room? Or somehow twilio will identify that this is same participant?

**Comment by DavidArutiunian** [comment]
@makarandp0 thanks for your answer! Making identity unique per tab worked well 🤘
