### ISSUE TITLE
APi docs missing / linking broken

### ISSUE THREAD

**Issue by rmaunder** [twilio/twilio-video.js#1369]
Not a code issue, documentation related. 

Searching for the API docs takes you to : https://media.twiliocdn.com/sdk/js/video/releases/2.11.0/docs/

There is a basic usage example: https://media.twiliocdn.com/sdk/js/video/releases/2.11.0/docs/#toc5__anchor
which states:

For more information, refer to the API Docs, which links to 

https://media.twiliocdn.com/sdk/js/video/latest/docs

which just redirects you back to https://media.twiliocdn.com/sdk/js/video/releases/2.11.0/docs/

So the more detailed API docs (which I assume exist) are lost. 

Specifically, I'm looking for errors that thrown is an invalid JSON blob is passed into the Video.connect() method.

**Comment by manjeshbhargav** [comment]
Hi @rmaunder ,

Thanks for reporting this. Basically, any invalid options passed `Video.connect()` is ignored. I will make sure to add this in our documentation.

Thanks,

Manjesh
