### ISSUE TITLE
Calling setSinkId on second output device overrides the first output

### ISSUE THREAD

**Issue by tzipisheinin** [twilio/twilio-video.js#1371]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**
```html
<div id="content" />
```
```js
import { connect } from 'twilio-video';
const content = document.getElementById('content');
let sessionAudioOutputDevice, transducerAudioOutputDevice;

navigator.mediaDevices.enumerateDevices().then(devices => {
  const audioDevices = devices.find(device => device.kind === 'audiooutput');
  sessionAudioDevice = audioDevices.find(device => device.label === 'session');
  transducerAudioDevice = audioDevices.find(device => device.label === 'transducer' );
  return connect('$TOKEN', { name: 'my-room-name' });
}).then(room => {
  room.on('trackSubscribed', (track) => {
    if (track.kind === 'audio') {
      const audioElement = track.attach();
      if (track.name === "session") {
        audioElement.setSinkId(sessionAudioOutputDevice.deviceId).then(() => {
          content.appendChild(audioElement);
        }); 
      } else if (track.name === "transducer") {
         audioElement.setSinkId(transducerAudioOutputDevice.deviceId).then(() => {
           content.appendChild(audioElement);
        });
     } 
    }
  });
});
```

**Expected behavior:**

I have only two participants in this session, let's say local and remote
The local is sending two audio tracks having two different audio input devices (two different microphones), the tracks are defined by their names.
When changing the sinkId I expect every audio track to come from the device that has been set using `setSinkId`.

**Actual behavior:**

The first added track (session) is working, after the second track is added both tracks are coming from the second output device (transducer).
Somehow, the second `setSinkId` affects both tracks.

All devices are existed, I can see them after calling `enumerateDevices`

**Software versions:**

 - [x] Browser(s): Google Chrome 85.0.4183.102 
 - [x] Operating System: ubuntu
 - [x] twilio-video.js: 2.0.0
 - [x] Third-party libraries (e.g., Angular, React, etc.):

**Comment by manjeshbhargav** [comment]
Hi @tzipisheinin ,

Thanks for writing in with your issue. Can you confirm the behavior in other browsers like Firefox and Safari? Do they correctly route audio through the appropriate devices? If so, then this might be a Chromium bug.

Thanks,

Manjesh
