### ISSUE TITLE
Changing MediaStreamTrack in Twilio.Video.createLocalAudioTrack()

### ISSUE THREAD

**Issue by JunusErgin** [twilio/twilio-video.js#138]
Hello,

the function `Twilio.Video.createLocalAudioTrack()` creates a new `LocalAudioTrack` element which has a property `mediaStreamTrack`. It records audio from my default microphone. 
Instead of the default microphone i want to use another. Is there a way to change the whole `mediaStreamTrack` property of the `LocalAudioTrack` or can i somehow pass the deviceId of my microphone as a parameter to the function `Twilio.Video.createLocalAudioTrack()`?

In the documentation is says, that there is only a loglevel i can pass to the function.

Thanks in advance

Junus

**Comment by tobiaseisenschenk** [comment]
I would also be happy to see this feature supported!

**Comment by markandrus** [comment]
Hey @JunusErgin and @tobiaseisenschenk,

Thanks for writing in! It's not easy to tell from the JSDoc, but `createLocalAudioTrack` (and `createLocalVideoTrack`) accept [`CreateLocalTrackOptions`](http://media.twiliocdn.com/sdk/js/video/releases/1.1.0/docs/global.html#CreateLocalTrackOptions). You're right, these do accept a `logLevel`, but they also extend [`MediaTrackConstraints`](https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints). I wish JSDoc made this a little clearer:

<img width="333" alt="screen shot 2017-07-18 at 8 21 58 am" src="https://user-images.githubusercontent.com/359154/28325264-3234e004-6b92-11e7-8d33-094008209540.png">

So anything you can pass as `MediaTrackConstraints` you can pass to `createLocalAudioTrack` (or `createLocalVideoTrack`). For example, if you know your `deviceId`, you could do

```js
createLocalAudioTrack({ deviceId: 'foo' })
```

Similarly, `createLocalTracks` accepts [`MediaStreamConstraints`](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamConstraints), so you could do

```js
createLocalTracks({
  audio: {
    deviceId: 'foo'
  },
  video: {
    deviceId: 'bar',
    width: 1920,
    height: 1280
  }
})
```

Could you please try this out? I'm going to close the ticket now, but if you have any further questions feel free to write back.

Thanks,
Mark

**Comment by JunusErgin** [comment]
Hello Mark,

thank you very much! It works out of the box.

Junus
