### ISSUE TITLE
Cannot set up a minimum fps for share screen

### ISSUE THREAD

**Issue by mrsasuu** [twilio/twilio-video.js#1381]
Hi, I have been trying to increase the framerate for screen sharing when an user is streaming high dinamyc video but I am not able to specify any minimum framerate when I create the share screen track.

`  navigator.mediaDevices.getDisplayMedia({
video:{
        width: {  ideal: 1920, max: 1920 },
        height: {  ideal: 1080, max: 1080 },
        frameRate: {min: 30,max: 60}
    }
      }).then(...`

When I try to initialize the track the navigator returns this error:
`TypeError: min not allowed`

I have tried to just specify a fixed framerate as:
`  navigator.mediaDevices.getDisplayMedia({
video:{
        width: {  ideal: 1920, max: 1920 },
        height: {  ideal: 1080, max: 1080 },
        frameRate: 60
    }
      }).then(...`

(These are the constraints for that track after creation)
`frameRate: Object { max: 60 }
​
height: Object { ideal: 1080, max: 1080 }
​
mediaSource: "window"
​
width: Object { ideal: 1920, max: 1920 }`

And then it works but the minimum framerate is by default set to 0.

**Expected behavior:**

Being able to specify a maximum and minimum framerate for screen share. 

`  navigator.mediaDevices.getDisplayMedia({
video:{
        width: {  ideal: 1920, max: 1920 },
        height: {  ideal: 1080, max: 1080 },
        frameRate: {min: 30,max: 60}
    }
      }).then(...`

**Actual behavior:**

When I specify a minimum navigator returns an error:
`TypeError: min not allowed`

**Software versions:**

 - [ ] Browser(s): Firefox, Google Chrome. (not checked on others)
 - [ ] Operating System: Windows 10
 - [ ] twilio-video.js: 2.11.0
 - [ ] Third-party libraries (e.g., Angular, React, etc.): React js

**Comment by makarandp0** [comment]
Hello @mrsasuu, Thank you for writing in, and sorry it took long. 

This is specific to browser implementation, and looks like browsers do not support same constraints for `getDisplayMedia` as they do for `getUserMedia`. I see a [webrtc getDisplayMedia sample](https://www.webrtc-experiment.com/getDisplayMedia/) that shows limited supported constraints.

Thanks,
Makarand
