### ISSUE TITLE
Safari on Apple M1 Mac crashes when more than one video element present

### ISSUE THREAD

**Issue by rbasto1** [twilio/twilio-video.js#1383]
Tested on M1 and non-M1 MacBooks, and on Safari and Chrome.
Crashes for M1 + Safari, works well in all other 3 combinations of device and browser.

**Code to reproduce the issue:**
https://codepen.io/rbasto/pen/ExNNveE
Enter a valid token and click Connect. Agree to accessing the camera device.

**Expected behavior:**
See myself in 3 windows until I close the page.

**Actual behavior:**
Works for a couple of seconds and then crashes the tab. Safari then reloads the page.
(Sometimes it works, if it does please refresh and try again. It crashes more often than not though)

**Software versions:**
 - [x] Browser(s): Safari 14.0.2
 - [x] Operating System: macOS 11.1, Darwin 20.2.0
 - [x] twilio-video.js: 2.12
 - [x] Third-party libraries (e.g., Angular, React, etc.): none

**Logs**
Crash report on Console app:
```
Process:               com.apple.WebKit.WebContent [9812]
Path:                  /System/Library/Frameworks/WebKit.framework/Versions/A/XPCServices/com.apple.WebKit.WebContent.xpc/Contents/MacOS/com.apple.WebKit.WebContent
Identifier:            com.apple.WebKit.WebContent
Version:               16610 (16610.3.7.1.9)
Build Info:            WebKit2-7610003007001009~1
Code Type:             ARM-64 (Native)
Parent Process:        ??? [1]
Responsible:           Safari [9218]
User ID:               501

Date/Time:             2021-02-11 18:51:04.023 +0100
OS Version:            macOS 11.1 (20C69)
Report Version:        12
Anonymous UUID:        1389D40A-91AD-BB2B-D539-82BC9985F99D

Sleep/Wake UUID:       177A2DFD-26BE-463F-9E71-6DAD7DB9E1D3

Time Awake Since Boot: 51000 seconds
Time Since Wake:       1400 seconds

System Integrity Protection: enabled

Crashed Thread:        26  EncoderQueue  Dispatch queue: com.apple.videotoolbox.compressionQueue

Exception Type:        EXC_BAD_ACCESS (SIGBUS)
Exception Codes:       EXC_ARM_DA_ALIGN at 0x000000000000000b
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Bus error: 10
Termination Reason:    Namespace SIGNAL, Code 0xa
Terminating Process:   exc handler [9812]

VM Regions Near 0xb:
--> 
    __TEXT                      1048a0000-1048a4000    [   16K] r-x/r-x SM=COW  /System/Library/Frameworks/WebKit.framework/Versions/A/XPCServices/com.apple.WebKit.WebContent.xpc/Contents/MacOS/com.apple.WebKit.WebContent

Application Specific Information:
dyld3 mode
Bundle controller class:
BrowserBundleController
```
[...]

**Comment by noobleapp** [comment]
Same issue this side

**Comment by johndevor** [comment]
Also seeing this

**Comment by makarandp0** [comment]
Hello @rbasto1 - Sorry for delay on this. We tested your codepen on  M1 running Big Sur 11.2.3 with Safari 14.0.3 and were not able to  issue. Since you reported the issue macOS 11.1 with Safari 14.0.2, we are wondering if the issue is fixed in newer version. Can you please check update to newer MacOS version to see if the issue still reproduces ?

Thanks,
Makarand

**Comment by rbasto1** [comment]
Hey @makarandp0, it seems to be working for me now. Thank you!

**Comment by SMART2016** [comment]
I am getting the same issue with Packt videos on Big Sur 11.2.3 .. Any solution ...

**Comment by zhanlarr** [comment]
@makarandp0 we were not able to test with VP8 as our reproducer ended up upgrading their Big Sur, but, we have not seen the issue again on upgraded Big Sur.
