### ISSUE TITLE
Safari: trackStopped event is emitted when Safari in background mode

### ISSUE THREAD

**Issue by vbabenko** [twilio/twilio-video.js#1387]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

**Preconditions:**
- Open any other tool (for example, your editor etc.) in **_full screen mode_**

1. Connect to the Group meeting with Safari (grant all needed audio/video permissions)
2. Mute your audio on the call
3. Switch to your opened full-screen tool and stay there for ~15 sec
4. Return to the Safari browser with your call

```js
localParticipant.on('trackStopped', track => {
    console.log('TRACK STOPPED', track);        
});
```

**Expected behavior:**
If the stream is active it should not emit `trackStopped` event

**Actual behavior:**
LocalParticipant receives `trackStopped` event. 
But the stream is active. Only reproduced for `audio` track & local participant

TODO

**Software versions:**

 - [x] Browser(s): Safari 14.0.2
 - [x] Operating System: macOS Catalina
 - [x] twilio-video.js: 2.12.0
 - [x] Third-party libraries (e.g., Angular, React, etc.): Vue.js
<img width="596" alt="trackStoppedEvent" src="https://user-images.githubusercontent.com/4083910/108235134-370e3d80-714e-11eb-9fbb-2433267edc07.png">

**Comment by makarandp0** [comment]
Hello @vbabenko, Thank you writing about with this issue.

How do acquire the audio track that is seeing this issue? I am surprised that its being detected as silent.

We added some workarounds for cases where Safari (mainly on iOS) stops providing media on captured audio track when  it goes into background. Workarounds involved detecting that Safari has gained foreground, and check if audio track was stopped or has silenced while safari was running in background. On detecting such instances twilio-video sdk stops the track and try to reacquire it. Looks like you are seeing such an instance and its somehow detecting the track to be silent even if its not.

You can disable this behavior by passing 
`workaroundWebKitBug1208516: false` when creating LocalAudio track.  

```
const Video = require('twilio-video');
const audioTrack = await Video.createLocalAudioTrack({ workaroundWebKitBug1208516: false })
const room = await Video.connect(token, { name: 'my-cool-room', tracks: [audioTrack] });

```

Thanks,
Makarand

**Comment by ascpeter** [comment]
@makarandp0 I'm occasionally getting the exact same error message after rejecting an incoming phone-call (actual phone call, not video call). Most of the time, it only shows that first warning "Silence detected" and then resumes perfectly after rejecting the phone call. But sometimes it shows the subsequent retry messages and then fails to re-acquire the microphone audio.

I've only seen this happen on iOS (I'm using iOS Safari 14.4, and Twilio-video SDK 2.10.0).

I'm acquiring audio like so: `Video.createLocalAudioTrack({})`. And sometimes like this: `Video.createLocalAudioTrack({ exact: deviceId })`. I believe the first was used each time this failure occurred.

**Comment by makarandp0** [comment]
From the logs this look like an iOS / Safari issue, but unfortunately we have not been able to reproduce this. If anybody has somewhat  consistent repro steps that we can share with Apple, please share and we will pass that information and follow up on it. On our side we have decided to collect more info (insights) on such audio track reacquire failures (VIDEO-5348) to be able to proactively find out how many customers are affected by this issue.

**Comment by makarandp0** [comment]
Hello @ascpeter, @vbabenko - This is an old issue on old version of Safari, we verified that Safari issues are mitigated in newer versions. I am closing this issue now, Please reopen a new issue if you encounter this again.
