### ISSUE TITLE
iOS mic not initially transmitting

### ISSUE THREAD

**Issue by chrismatthieu** [twilio/twilio-video.js#1392]
iOS 14.4 devices connect to large room just fine and can see and hear participants from PC/Mac; however, participants on PC/Mac can see but *not* hear iOS devices - as if the iOS mic is not streaming audio up.

If iOS user switches apps and comes back to Safari, iOS mic automatically starts working and all parties can hear each other.

Running Twilio-video v2.12.0, Safari (Mac and iOS), vanilla javascript

 - [X ] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [X ] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [X ] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [X ] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Comment by makarandp0** [comment]
Hello @chrismatthieu, sorry for late reply. 

I suspect this to be a permission issue, with browser on iOS somehow been denied the permission to the audio device. Can you verify that the permissions are granted in System Settings?

Is this problem limited to a specific iOS device or do you see it on other devices/ios versions as well? Can you share a room-sid that shows this issue?
Thanks
Makarand

**Comment by chrismatthieu** [comment]
V2.13 fixed the iOS mic issue but...

Now iOS users cannot speak to Chrome users. 
Chrome users can speak to iOS users.
iOS users can speak to other iOS users.

**Comment by makarandp0** [comment]
Hey @chrismatthieu, Thank you for the update. Can you provide more details on this. Does this new issue - iOS users cannot speak to Chrome users- consistently repro ? is it limited to specific version of iOS or device? 
  
Any room-sid that experienced this issue and logs from the console would be very useful to debug this futther.
Thanks,
Makarand

**Comment by chrismatthieu** [comment]
It's reproducible for me every time via large rooms.

Chrome: Version 88.0.4324.192 (Official Build) (x86_64) (Mac BigSur 11.2.2 )
iOS 14.4 Safari (iPhone 11 Pro)

I'm not seeing any errors.  Seems like a media server issue maybe - not sure.

**Comment by makarandp0** [comment]
Thanks for the update again, Can you share the room-sid and client logs that experienced this issue.  
Thanks,
Makarand

**Comment by chrismatthieu** [comment]
I was mistaken. V2.13 did not fix this issue. 

If I swap out of my iOS Safari and re-open browser into the same session, the chrome users start to hear me.

**Comment by makarandp0** [comment]
@chrismatthieu, we are not aware of any generic issue with iOS Safari - So need more information to investigate this case. Can you share the room-sid and client logs that experienced this issue.

**Comment by chrismatthieu** [comment]
I just verified that it's still reproducible every time. 

room-sid: RMf376050c3f72a43a6281415c799a368e

**Comment by chrismatthieu** [comment]
Room SID:
RMb5dd0dfd68af219fa927b41189e4cfcd

**Comment by makarandp0** [comment]
Hello @chrismatthieu, Can you share the logs from the console  ? I see that the room-sid you share has 7 different participants  (4 from Safari, and 3 from Chrome) 
```
P1: PA2788b24d203187bc61ffc8c4a664deb5 |  Safari 14.0.3 
P2: PA543e731d9cef03b65f1e50a682f2db86 |  Mobile Safari 14.0.3 
P3: PAe5427a37d3a8668ad207593abd640eac |  Chrome 89.0.4389 
P4: PAfa93413f5af3b2ee7c4315fd131c0ccb |  Chrome 89.0.4389 
P5: PAd3827929d6141774a8e685f6b2221a56 |  Mobile Safari 14.0.3 
P6: PA8fbf312f886d026ef990dd271cdf93ad |  Chrome 89.0.4389 
P7: PA259bf36b25bd965ece2365760de5cc45 |  Mobile Safari 14.0.3 
``` 
Its likely that they were same participant re-connecting after refreshing the browser.  It would be easier if you could repro this with just one participant from iOS and one from Chrome, and please attach the logs from the console (it would be great if we could see logs from both side, but I am mostly interested in logs from the participant whose audio is not heard. 

By the way, have you tried the [quickstart sample](https://github.com/twilio/video-quickstart-js) - does it repro the issue as well? 

Thanks,
Makarand

**Comment by chrismatthieu** [comment]
Thanks for your patience and support as I worked through this issue. I can confirm that this issue was not a Twilio error but rather an error in my code trying to gain access to the microphone twice. It worked fine on every device except iOS. Problem has been resolved.
