### ISSUE TITLE
Remote Participant Video Fit to Device Scrin

### ISSUE THREAD

**Issue by om123patel** [twilio/twilio-video.js#1396]
Hello Team,

I am developing video calling Application.

In my case, I am using mobile application from client side and web application from admin side.

I want to show full screen video of remote participant in web application.

Could you please guide me how can I achieve this functionality?

 - [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

```js
// TODO
```

**Expected behavior:**

TODO

**Actual behavior:**

TODO

**Software versions:**

 - [x] Browser(s):
 - [x] Operating System:
 - [x] twilio-video.js:
 - [x] Third-party libraries (e.g., Angular, React, etc.):

**Comment by makarandp0** [comment]
Hello @om123patel, Thank you for writing with your question. I found [this link](https://stackoverflow.com/questions/1055214/is-there-a-way-to-make-html5-video-fullscreen) that addresses question of how to render any element full screen - Does that answer your question ?
Thanks,
Malarand

**Comment by makarandp0** [comment]
Hey @om123patel, we haven't heard back from you. I am assuming that this issue is resolved now.
