### ISSUE TITLE
Can a user view participants video without joining the room?

### ISSUE THREAD

**Issue by baj84** [twilio/twilio-video.js#1404]
Hi,

Is it possible for a user to 'preview' the room and receive participants videos without joining the room first?

Thanks!

**Comment by makarandp0** [comment]
Hey @baj84, There are [rest apis](https://www.twilio.com/docs/video/api/rooms-resource) that can be used to query room details without joining it but that does not provide access to media in the room. Participant need to join the room to be able to subscriber to published tracks,

Thanks,
Makarand

**Comment by makarandp0** [comment]
closing this issue now.
