### ISSUE TITLE
Xiaomi Redmi Note 8

### ISSUE THREAD

**Issue by m1kjh43l2020** [twilio/twilio-video.js#1417]
i cant use the app with Xiaomi Redmi Note 8, sends me browser dont supported why? (chrome installed)

**Comment by makarandp0** [comment]
Hello @m1kjh43l2020, can you share userAgent reported by this browser. Our [check](https://github.com/twilio/twilio-video.js/blob/master/lib/util/support.js#L93) for `isSupported` uses user agent and few necessary APIs to determine if the browser is supported. Looking at user agent we can see why it would return not supported.

Also can you check if [this sample](https://webrtc.github.io/samples/src/content/peerconnection/pc1/) works on your device?

Thanks,
Makarand

**Comment by makarandp0** [comment]
@m1kjh43l2020, we haven't heard back from you. I am closing this issue now - Please reopen if you still seeing issue with this.
