### ISSUE TITLE
Polyfills needed for webpack 5

### ISSUE THREAD

**Issue by emilkarl** [twilio/twilio-video.js#1429]
If you include `twilio-video` when using webpack 5 you will need to add some polyfills. Might be good to add them as dependencies.

https://github.com/browserify/node-util
https://github.com/defunctzombie/node-process

**Comment by manjeshbhargav** [comment]
Hi @emilkarl ,

Thanks for writing in. I'm concerned with adding them as dependencies because it is specific to Webpack, and I don't want developers who don't depend on Webpack to have to install these dependencies.

Thanks,

Manjesh
