### ISSUE TITLE
trackAdded fired with error

### ISSUE THREAD

**Issue by Eugene-Sviridov** [twilio/twilio-video.js#143]
Hi. When I am trying to add new track to localParticipant and then trying to get this track on another user side I get `Cannot read property 'id' of null` error. 

```
receiver = self.getReceivers().find(function(r) {
  return **r.track.id** === te.track.id;
});
```

GIF - https://cl.ly/322F390m2G1j

// stream creating - **I thing problem here**
```
return navigator.mediaDevices.getUserMedia({
  video: {
    deviceId: sourceId
  }
});
```
// adding track
```
const screenLocalTrack = new twilio.LocalVideoTrack(action.stream.getVideoTracks()[0]);
this.room.publicInstance.localParticipant.addTrack(screenLocalTrack);
```

// receiving track
```
room.participants.forEach((participant) => {
  if (participant.identity.toString() === creatorId.toString()) {
    participant.on('trackAdded', (track) => {...});
  }
});
```

self.getReceivers() - https://cl.ly/1B2Q0Q3q1k0k

 - Chrome
 - MacOS
 - twilio-video.js:
 - Angular 4, Redux

**Comment by markandrus** [comment]
Hi @Eugene-Sviridov,

This appears to be a bug in [webrtc/adapter](https://github.com/webrtc/adapter).

I'll see if I can triage, but the fix will be in that library. If you can omit this library from your application, things should work.

Mark

**Comment by Eugene-Sviridov** [comment]
@markandrus Wow, that works! Thank you man. I was trying to fix it whole day.
Google didn't give me an answer, hope this will help somebody.
I will test it one more time and let you know if something break.

**Comment by markandrus** [comment]
@Eugene-Sviridov no worries! FWIW, I have opened an issue on webrtc/adapter: https://github.com/webrtc/adapter/issues/640

**Comment by markandrus** [comment]
@Eugene-Sviridov also, can you share what version of Chrome you were using? I reproduced with Chrome Canary 62.

**Comment by Eugene-Sviridov** [comment]
@markandrus Version 60.0.3112.90 (Official Build) (64-bit)
