### ISSUE TITLE
Question regarding billing for 100 Participant Rooms Pilot ?

### ISSUE THREAD

**Issue by sandeepnandula** [twilio/twilio-video.js#1430]
Hello team, could you help us regarding how the billing minutes will be calculated for 100 Participant Rooms Pilot ?

**Comment by PikaJoyce** [comment]
Hello @sandeepnandula!

Thank you for opening this issue with us. I recommend reaching out to an expert [here](https://www.twilio.com/video/pricing) with regards to the pricing of those rooms. As there is no actionable items with this issue, I will be closing it but if you have further questions or issues, feel free to continue the conversation on this issue. 

Thank you again!

Regards,
Joyce
