### ISSUE TITLE
Echoing issue in Safari

### ISSUE THREAD

**Issue by joelongstreet** [twilio/twilio-video.js#1433]
I'm using the Twilio Programmable Video API and have run into audio echoing issues in a few circumstances. My particular implementation is pretty complicated, but I can actually duplicate this problem 100% of the time using this example project.

1. Follow the directions on the readme to setup the application.
2. Use ngrok to publicly expose your application.
3. Open Safari and send the ngrok url to a friend to open in Safari.
4. If the participants aren't wearing headphones, both will get very loud pronounced echoing problems.
5. This issue doesn't seem to occur in Chrome.

I've messed with the audio settings quite a bit - the preferred audio codecs, turning off gain control, manually turn on echo cancellation - all of these seem to have an effect, but none fix the echoing issue in Safari.

What are the next steps in debugging? How can I make this echoing issue go away?

**Comment by manjeshbhargav** [comment]
Hi @joelongstreet ,

Sorry for the delayed response, but we are already investigating a similar issue. I will keep you posted.

Thanks,

Manjesh

**Comment by alex-konoval** [comment]
@joelongstreet I guess this is because [noiseSuppression](https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackSettings/noiseSuppression#browser_compatibility) and [echoCancellation](https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackSettings/echoCancellation#browser_compatibility) are not supported in Safari.

**Comment by manjeshbhargav** [comment]
Hi @joelongstreet ,

We have updated this [Safari bug](https://bugs.webkit.org/show_bug.cgi?id=213723) with reproduction steps (with a plain WebRTC app). We will monitor it and let you know once they fix it.

Thanks,

Manjesh

**Comment by baranovskyi** [comment]
Hi
I faced this problem as well
@manjeshbhargav Any updates on this?

**Comment by Bikash-lama** [comment]
Hello,
Any update here.
I am also facing the echoing issue, though its occurrence is low, but still reproducible in 2/10 cases.

Device: iphone SE(14.8) Safari Caller
Occurrence: 2/10

I tried the echoCancellation, but did not have any effect
