### ISSUE TITLE
React Native Support - Roadmap

### ISSUE THREAD

**Issue by jacob-israel-turner** [twilio/twilio-video.js#1439]
Hello!

This is not a bug, but more of a roadmap question - if there is a better place for this question, please point me in the right direction!

I've dug through issues a little bit and have found a couple of responses from contributors - my current understanding is that there is no official support for React Native, and there is no plan in 2020 to add support.  It also seems that there is already partial functionality, mostly just bugs, with using this library for React Native.

My team is looking to build many-to-many video calling in our app, which is built entirely in React Native (including a web component using react-native-web).  Twilio is the obvious solution, as we are already using the verify and SMS products.  However, if we cannot use the Twilio SDK for video calling, then we may need to look elsewhere.

Is React Native support on the roadmap at all?  Is there an understanding of what needs refactored or updated in order to support React Native?  There's a large community that would benefit from being able to use this library.

Thanks!

**Comment by manjeshbhargav** [comment]
Hi @jacob-israel-turner ,

Thanks for writing in. Unfortunately, we do not have React Native support in our near-term roadmap. However, you can check out this [open source project](https://github.com/blackuy/react-native-twilio-video-webrtc) and see if this is something that works for your development.

Thanks,

Manjesh
