### ISSUE TITLE
Poor performance using Safari on iOS devices (Low FPS)

### ISSUE THREAD

**Issue by Galzk** [twilio/twilio-video.js#1448]
When using the app on an iOS device with Safari browser, we get very low FPS count.

1. Enter a room using the Safari browser on an iOS device
2. See bad performance on peer's screen
3. Incoming video is smooth as expected on the iOS device itself

**Expected behavior**
Video should be smooth and performant on all supported devices and platforms

**Video**

https://user-images.githubusercontent.com/34302982/113510142-f9307180-9561-11eb-81b6-0b62866ea317.mp4

**Environment (please complete the following information):**
 - OS: iOS 14.4.1 (on iPad 8)
 - Browser: Safari 14.4.1
 - App Version: 0.2.4
 - SDK Version: 2.13.1
 - Node.js version: 12.21.0

**More info**
-I've also tried running the "build" version (non-development) in order to narrow down the possibility of the issue only occurring when using the development code
-No changes were made to the code
-I think this issue is related to the twilio-video repo, but let's make sure
-I've used 2 different networks in order to check, and in the video I use my cellular connectivity, and on the mac I'm on WIFI
-When using https://appr.tc/ I get a smooth 30 FPS at all times (well, not considering the occasional frame drop). Both Safari on mac and on iOS

**Comment by manjeshbhargav** [comment]
Hi @Galzk ,

Thanks for writing in with your issue. Are you using Group Rooms or Peer-to-Peer Rooms. Also, can you share a Room SID for the test you ran? In the react app, you can get the Room SID by running `twilioRoom.sid` in the JS console after joining the Room.

Thanks,

Manjesh

**Comment by Galzk** [comment]
RM3b09eb2184c4369213dc91debce65746
Here you go
I'm using the default preferences for room type
I've done this:
1. Log in with the iPad (safari)
2. Log in with my mac (safari) - now the iPad feed is laggy like in the video
3. Log in with Firefox on my android - my android feed and mac feed is working flawlessly, iPad feed is laggy on both device

**Comment by manurana** [comment]
I can confirm this on a vanilla twilio-react-app installation.
Tried with 2 separate iPads, of different vintages, both had this issue. Could not see this on iPhones.

Something I noticed, the network level indicator is VERY LOW (1 bar) for the user on the iPad, in spite of being on a fast network.

**Comment by agpl** [comment]
Hello, I'm experiencing similar issue with iOS safari, but I just discovered that, whenever I use unmute button and say something it's smooth again. Is there any way to fix this issue? Here is my Room SID RMa6941f1176e404dbab2b7ef25c23d3ca

Network level indicators are ok (4-5 bars)
