### ISSUE TITLE
Is there anyway to start and stop recording during the video call?

### ISSUE THREAD

**Issue by likhit-vivek** [twilio/twilio-video.js#1456]
Based on the documentation, we can specify whether to record or not while creating a group room.

But usually in zoom or microsoft teams, the host gets to start and stop recording whenever he wants during the call. Is it possible to do that in twilio video? Pls let me know. Thanks.

**Comment by charliesantos** [comment]
Hey @likhit-vivek you can start/stop recording using rest apis documented here: https://www.twilio.com/docs/video/api/recording-rules

**Comment by likhit-vivek** [comment]
Thank you @charliesantos. I tried using the recording rules to start and stop recording during the video call. But I am running into an issue there.

When I run my API server locally and call the twilio endpoint for updating the recording rules, it is working fine. But if I try to update the rules after moving the API to staging (dev server) I am receiving an error. Pls see details below:

{ sid: 'RM9627f06ef96757fb73d9443cababe3f2',
room: '138250829230_BeFKb49cUm',
created_at: '2021-05-03T04:35:45.991Z' }
1|sg  | err TypeError: Cannot read property 'update' of undefined
`Cannot read property 'update' of undefined`

I don't understand why I am able to update the rules from a local server but not the staging server. Pls help.

**Comment by charliesantos** [comment]
@likhit-vivek , is this staging server your own server or are you referring to a twilio staging server (unlikely)?

**Comment by likhit-vivek** [comment]
@charliesantos I was talking about our own staging server (nodejs based) which is responsible for calling the twilio endpoint to update the recording rules.

So when the referer is localhost (i.e. when the server is running locally) the twilio endpoint is working fine.
When the referer is the public url of the server (i.e. when the server is hosted publicly for development purpose) the twilio endpoint is returning an error mentioned above.

Hope this gives you more clarity.

**Comment by charliesantos** [comment]
@likhit-vivek can you share an example of the whole request object that is coming from your server?

**Comment by charliesantos** [comment]
> @likhit-vivek can you share an example of the whole request object that is coming from your server?

Please do not forget to mask any sensitive information such as creds, tokens, etc.

**Comment by likhit-vivek** [comment]
@charliesantos Sorry for the delay... This is our code for calling the update rules endpoint
`client.video.rooms(event.meeting_id.sid).recordingRules.update({ rules: [{ "type": "include", "all": true }] })
.then(recording_rules => {
	console.log(recording_rules);
}).catch(err => {
	console.log(err);
});`

**Comment by likhit-vivek** [comment]
So basically `recordingRules` is becoming undefined in our server, thus update is not working. That explains the error we are getting. But I dont understand why it is happening only on our staging server.

**Comment by charliesantos** [comment]
Hi @likhit-vivek , `recordingRules` would be empty if room sid provided to `client.video.rooms(roomSid)` method is invalid or non-existent. Try logging your roomSid to make sure it is valid.

Also, not sure what is the difference and how you setup your own staging server but I would look into verifying the node version, npm modules version, and npm caches are all the same. You can try clearing npm cache and deleting node_modules folder and package-lock.json/yarn.lock files to pull down un-cached versions of your modules and see if that works.

**Comment by likhit-vivek** [comment]
@charliesantos roomSid provided is not invalid... Pls check this
```
step 1. Room Details on join event
{   sid: 'RMfa9fef993e841b1d5d1de53b8ec7c8db',
    status: 'in-progress',
    dateCreated: 2021-05-12T02:39:08.000Z,
    dateUpdated: 2021-05-12T02:39:08.000Z,
    accountSid: 'AC243323b1907a291a1c5aef8e3af5530f',
    enableTurn: true,
    uniqueName: '140354049013_iFsYj1l13cd',
    statusCallback: null,
    statusCallbackMethod: 'POST',
    endTime: null,
    duration: null,
    type: 'group',
    maxParticipants: 50,
    recordParticipantsOnConnect: true,
    videoCodecs: [ 'H264', 'VP8' ],
    mediaRegion: 'us1',
    url:
     'https://video.twilio.com/v1/Rooms/RMfa9fef993e841b1d5d1de53b8ec7c8db',
    links:
     { recordings:
        'https://video.twilio.com/v1/Rooms/RMfa9fef993e841b1d5d1de53b8ec7c8db/Recordings',
       participants:
        'https://video.twilio.com/v1/Rooms/RMfa9fef993e841b1d5d1de53b8ec7c8db/Participants',
       recording_rules:
        'https://video.twilio.com/v1/Rooms/RMfa9fef993e841b1d5d1de53b8ec7c8db/RecordingRules' } 
}
step 2. fetching sid for start recording
{ 
    sid: 'RMfa9fef993e841b1d5d1de53b8ec7c8db',
    room: '140354049013_iFsYj1l13cd',
    recording: true,
    created_at: '2021-05-12T02:39:08.099Z' 
}
step 3: recoridng rules
{ rules: [ { type: 'include', all: true } ] }
error:
TypeError: Cannot read property 'update' of undefined
```

Also everything is same between local and staging server including node and modules version... Pls check from your side once in which other scenarios would twilio return such an error. Thanks.

**Comment by charliesantos** [comment]
Hey @likhit-vivek this error returns if you're using an older version of the twilio-node helper library. `recordingRules` was only added very recently. Can you please double check your twilio-node library version in your package.json and package-lock.json?

**Comment by likhit-vivek** [comment]
@charliesantos Thanks a lot for ur help... Using older version of twilio was the problem... After updating, twilio recording rules endpoint is not returning any error... Closing this issue.

**Comment by pinkishahub-sdn** [comment]
video composition take very much time to composite
