### ISSUE TITLE
Logging: stringified json inside message instead of data object

### ISSUE THREAD

**Issue by MonstraG** [twilio/twilio-video.js#1461]
I've followed [this blogpost](https://www.twilio.com/blog/capturing-twilio-video-js-sdk-logs) to set up logging, like this:
```
const logger = Logger.getLogger("twilio-video");
const originalFactory = logger.methodFactory;
logger.methodFactory = (methodName, logLevel, loggerName) => {
	const method = originalFactory(methodName, logLevel, loggerName);
	return (datetime, logLevel, component, message, data) => {
		console.log({message, data})
		method(loggerName, datetime, logLevel, component, message, data);
	};
};
```

And I found that for most of the messages during a video call, `data` is undefined, and `message` includes it instead:
![image](https://user-images.githubusercontent.com/17963791/116443241-d77a8f80-a86c-11eb-80ac-e53eeb359a3f.png)

Which makes it really difficult to filter and redact tokens and such, Please, send data inside data.

twilio-video.js: 3.14.3

**Comment by charliesantos** [comment]
Thanks @MonstraG for submitting. I added an internal ticket to track this improvement.

**Comment by charliesantos** [comment]
Hi @MonstraG I will close this now since we are already tracking this enhancement internally. Please watch out for future updates. Thanks!
