### ISSUE TITLE
Vertical video cut off because remote participant track dimensions coming as 0 on session join.

### ISSUE THREAD

**Issue by piyush2054** [twilio/twilio-video.js#1470]
**Describe the bug**
When a remote participant joins a session from a mobile device (portrait mode) then the video track dimensions come as 0, because of which the isPortrait check always return false and the video track's top and bottom portion gets cut off. If we try to change the orientation of mobile device from portrait to landscape and then again from landscape to portrait then it works fine because the track dimensions come correctly after the track is refreshed.

**To Reproduce**
1. User 1 Starts a new room from PC/Laptop and act as the observer.
2. User 2 joins the room created by User1 but from a mobile device (device should be in Portrait Mode)
3. User 1 can observe that the User 2's video track is showing up in Landscape mode and is cut off from top and bottom.

**Expected behavior**
Remote participant should send correct track dimensions when the session is joined and VideoTrack is loaded on screen.

**Screenshots**
![vertical video cutoff issue](https://user-images.githubusercontent.com/822425/109999833-a718e800-7d38-11eb-84f2-72892e1fd172.jpg)

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser: [e.g. Chrome 88.0.4324.190]
 - App Version: [e.g. 0.2.3]
 - SDK Version: [e.g 2.12]
 - Node.js version: [e.g. 15.14.1]

**Comment by piyush2054** [comment]
Hi @aaalaniz and @timmydoza do we have any update on this issue?

**Comment by piyush2054** [comment]
Hi @aaalaniz and @timmydoza do we have any update on this issue? We are holding back on the new updates just to get this issue resolved.

Thanks

**Comment by charliesantos** [comment]
@timmydoza @piyush2054 the SDK supports a [dimensionsChanged](https://sdk.twilio.com/js/video/releases/2.18.1/docs/RemoteVideoTrack.html#event:dimensionsChanged__anchor) event. Can you listen to this event and update the UI accordingly?

**Comment by timmydoza** [comment]
Hi @piyush2054 - I'm happy to report that we have fixed this issue in version 2.21.2 of the Twilio Video SDK. You can see the changelog entry [here](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md#2212-june-1-2022).

I've also released a new version of the React Video App that uses this new SDK version. With this, I'm going to close this issue as it is fixed. 

Please let me know if there's anything else that we can help with!!
