### ISSUE TITLE
Support for Chrome on iOS

### ISSUE THREAD

**Issue by a-type** [twilio/twilio-video.js#1475]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

Third-party browsers on iOS now have access to WebRTC APIs. I've tried using our app on Chrome iOS, however, and it still fails to publish media tracks (even though it can now acquire them successfully and display them locally with `getUserMedia`).

Are there remaining blockers to supporting third-party browsers on iOS, and if so, is there a timeline for addressing them?

In case the problem I described of not being able to publish tracks is not anticipated, here are the logs from Chrome iOS:

```
WARNING2021-05-17T16:52:34.884Z warn [PeerConnectionV2 #10: ae2836fd-a765-4502-8c3a-b965e4e56d74] Calling setRemoteDescription with an RTCSessionDescription of type "answer" failed with the error "Failed to set local offer sdp: max-bundle is used but no bundle group found.".
WARNING2021-05-17T16:52:34.888Z warn [PeerConnectionV2 #10: ae2836fd-a765-4502-8c3a-b965e4e56d74] The SDP was v=0
o=- 3830259154 3830259154 IN IP4 0.0.0.0
s=VM904a5fa0686a6f67a10ea88fcb6a99ff
c=IN IP4 0.0.0.0
t=0 0
a=msid-semantic: WMS
a=ice-lite
a=msid-semantic:WMS *
WARNING2021-05-17T16:52:34.898Z warn [connect #10] event [object Object]
WARNING2021-05-17T16:52:44.932Z warn [LocalParticipant #38: PA4bf4a5968a2f28da174ca1885ba84743] Failed to publish the LocalVideoTrack: LocalParticipant disconnected
WARNING2021-05-17T16:52:44.932Z warn [LocalParticipant #38: PA4bf4a5968a2f28da174ca1885ba84743] Failed to publish the LocalDataTrack: LocalParticipant disconnected
```

**Comment by PikaJoyce** [comment]
Hey there @a-type!

Thank you for submitting this issue! Would it be possible for you to provide some more details in order for me to help you debug this further? Information such as device, iOS version, Chrome version, as well as the room sid would allow me to be able to investigate further.

With that being said, I just tried to reproduce your issue using our [Quickstart](https://github.com/twilio/video-quickstart-js) on Chrome (version 159.1.372414826) / iOS (version 14.4.2). 
![image](https://user-images.githubusercontent.com/43423318/118541619-c2c04780-b706-11eb-983b-534af4001578.png)
Our Quickstart is functioning on Chrome iOS. I was hoping you could try it out as well to see if you're getting the same error?

Thanks!
Joyce

**Comment by a-type** [comment]
Thanks for taking a look. Let me be ensure my device is up to date. Your Chrome looks quite different from mine...

**Comment by PikaJoyce** [comment]
Hey @a-type!

My apologies, I accidentally used the Google app and not the Chrome app, so please disregard my image from earlier.  

But I'm going to look more into this for you as well :) .

Thank you for your patience! 
Joyce

**Comment by PikaJoyce** [comment]
Hi there @a-type,

After some investigating, I've found that it is in our backlog to support third party browsers on iOS and we plan on getting to it later this year.

With that being said, I'm going to close this issue as there are no immediate actions for us to take. But if you have further questions, we can continue our discussion here.

Thank you,
Joyce
