### ISSUE TITLE
Do you have a sample app of grid layout mode

### ISSUE THREAD

**Issue by dbuldansjah** [twilio/twilio-video.js#1476]
- [ ] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [ ] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ ] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [ ] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

```js
// TODO
```

**Expected behavior:**

TODO

**Actual behavior:**

TODO

**Software versions:**

 - [ ] Browser(s):
 - [ ] Operating System:
 - [ ] twilio-video.js:
 - [ ] Third-party libraries (e.g., Angular, React, etc.):

**Comment by PikaJoyce** [comment]
Hey there @dbuldansjah,

Thank you for submitting this question. We have two example applications. The [quickstart](https://github.com/twilio/video-quickstart-js), and the [react app](https://github.com/twilio/twilio-video-app-react). 

You can adjust the [video mode here in the Quickstart](https://github.com/twilio/video-quickstart-js/blob/59627b4f5fdd03da9a322fc6da63482de7aa0d7d/quickstart/src/index.js#L26).

You can also set the mode in the react app like so:
![image](https://user-images.githubusercontent.com/43423318/118564398-0de95300-b725-11eb-8beb-a1e464161a72.png)

Please try these out, I'll be closing this issue as there are no immediate actions from this. But if you have further questions, we can continue our discussion on this thread.

Thanks!
Joyce
