### ISSUE TITLE
getStats in Safari iOS 13.7 returns null for frameRate, roundTripTime, packetsLost in localVideoTrackStats

### ISSUE THREAD

**Issue by KleptoKat** [twilio/twilio-video.js#1477]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Expected behavior:**

When I call getStats() in safari for a peer to peer connection I should get a localVideoTrackStats object with packetsLost, roundTripTime, and frameRate set. 

**Actual behavior:**

However, in JUST Safari, all of these values are null (but other properties, such as bytesSent, are set)

I am using `"twilio-video": "^2.14.0"` on an iPad iOS Safari 13.7

I am trying to implement my own automatic video quality downgrade/upgrade API for peer to peer video - I am connecting to the latest version of Chromium. Let me know if  you need more to reproduce this issue.

**Comment by PikaJoyce** [comment]
Hey there @KleptoKat!

Thank you for submitting this issue. I was wondering if you had a second participant in the peer to peer room when you called `getStats()`? If not, could you please try to call `getStats()` with a second participant in the room and see if the issue still persists?

Thanks!
Joyce

**Comment by KleptoKat** [comment]
Hey Joyce - thanks for the fast response!

I have tried getStats() with a second and third participant in the peer-to-peer room. When getStats() is called with 1 participant in the room, it returns an array of length 0. When getStats() is called with 2 participants in the room, it returns an array with length of 1 and localVideoTrackStats has an array of 1 with some properties set but the properties I need (framerate, roundtriptime, packetslost).

This is what it looks like on iOs Safari with two participants in the room (note localVideoTrackStats):

```json
{
    "peerConnectionId": "7f1a10c3-d78a-4ec1-afc6-6806498717bd",
    "localAudioTrackStats": [
        {
            "trackId": "96a76747-8e44-41c0-b342-2dbed441b41b",
            "trackSid": "MTc3cc763399823f05b86f6f705e787519",
            "timestamp": 1621522890268,
            "ssrc": "2704024074",
            "packetsLost": null,
            "codec": "opus",
            "bytesSent": 36598,
            "packetsSent": 659,
            "roundTripTime": null,
            "audioLevel": null,
            "jitter": null
        }
    ],
    "localVideoTrackStats": [
        {
            "trackId": "f1391cc1-5941-4d6c-ac14-6958193cde21",
            "trackSid": "MTafbe634b8d2763b8e819c158584377ed",
            "timestamp": 1621522890268,
            "ssrc": "477122403",
            "packetsLost": null,
            "codec": "H264",
            "bytesSent": 1637653,
            "packetsSent": 1466,
            "roundTripTime": null,
            "captureDimensions": null,
            "dimensions": {
                "width": 480,
                "height": 360
            },
            "captureFrameRate": null,
            "frameRate": null
        }
    ],
    "remoteAudioTrackStats": [
        {
            "trackId": "fe90bc86-4539-4897-b374-80a0deb3d11b",
            "trackSid": "MTa05609f6e5827ee8ebeed80fd0813682",
            "timestamp": 1621522890268,
            "ssrc": "3679644396",
            "packetsLost": 1,
            "codec": "opus",
            "bytesReceived": 19217,
            "packetsReceived": 461,
            "audioLevel": 1,
            "jitter": 4
        }
    ],
    "remoteVideoTrackStats": [
        {
            "trackId": "44d899d7-8a30-47f5-8565-ad4c4fed2563",
            "trackSid": "MTf30a025487722836973325b7d266873d",
            "timestamp": 1621522890268,
            "ssrc": "3742495371",
            "packetsLost": 0,
            "codec": "VP8",
            "bytesReceived": 386474,
            "packetsReceived": 584,
            "dimensions": {
                "width": 720,
                "height": 540
            },
            "frameRate": null
        }
    ]
}
```

Here is what it looks like from chrome (and the other participant):

```json
{
    "peerConnectionId": "7f1a10c3-d78a-4ec1-afc6-6806498717bd",
    "localAudioTrackStats": [
        {
            "trackId": "76ae047d-8046-4c04-820f-b22f5ec6e9d3",
            "trackSid": "MTa05609f6e5827ee8ebeed80fd0813682",
            "timestamp": 1621522889394,
            "ssrc": "3679644396",
            "packetsLost": 1,
            "codec": "opus",
            "bytesSent": 6299,
            "packetsSent": 458,
            "roundTripTime": 98,
            "audioLevel": null,
            "jitter": 4
        }
    ],
    "localVideoTrackStats": [
        {
            "trackId": "8edc064d-7ddb-41f1-aa2c-259845c02639",
            "trackSid": "MTf30a025487722836973325b7d266873d",
            "timestamp": 1621522889394,
            "ssrc": "3742495371",
            "packetsLost": 0,
            "codec": "VP8",
            "bytesSent": 324999,
            "packetsSent": 536,
            "roundTripTime": 110,
            "captureDimensions": null,
            "dimensions": {
                "width": 720,
                "height": 540
            },
            "captureFrameRate": null,
            "frameRate": 33
        }
    ],
    "remoteAudioTrackStats": [
        {
            "trackId": "9b428631-3117-4ac4-a13a-ea239c1edaef",
            "trackSid": "MTc3cc763399823f05b86f6f705e787519",
            "timestamp": 1621522889394,
            "ssrc": "2704024074",
            "packetsLost": 0,
            "codec": "opus",
            "bytesReceived": 22055,
            "packetsReceived": 617,
            "audioLevel": 698,
            "jitter": 3
        }
    ],
    "remoteVideoTrackStats": [
        {
            "trackId": "ef381ae1-9406-4e44-8008-34782afda218",
            "trackSid": "MTafbe634b8d2763b8e819c158584377ed",
            "timestamp": 1621522889394,
            "ssrc": "477122403",
            "packetsLost": 1,
            "codec": "H264",
            "bytesReceived": 1496058,
            "packetsReceived": 1367,
            "dimensions": {
                "width": 480,
                "height": 360
            },
            "frameRate": null
        }
    ]
}
```

Thanks!

**Comment by PikaJoyce** [comment]
Thanks for trying it out @KleptoKat !

I've investigated a bit more and I've been able to reproduce this issue myself multiple times. Seems like some of the properties may be returning null as a result of lack of support across various RTCPeerConnection APIs (more specifically [RTCIceCandidatePairStats](https://developer.mozilla.org/en-US/docs/Web/API/RTCIceCandidatePairStats)) for iOS Safari. 

In addition, null values can imply that those stats are simply not reported by the browser. In order to confirm whether that's the case, you can utilize [this application](https://webrtc.github.io/samples/src/content/peerconnection/constraints/) and verify whether or not that is the case. 

Please let me know if that is the case for you!
Thank you!
Joyce

**Comment by KleptoKat** [comment]
Hey @PikaJoyce  thanks for getting back to me!

roundTripTime: currentRoundTripTime is available under the candidate-pair report type.

packetsLost: There is no packetsLost under outbound-rtp but there is packetsLost under inbound-rtp. This is reflected in the Twilio report because we can see packetsLost in remoteVideoTrackStats and NOT in localVideoTrackStats.

frameRate: outbound-rtp does have framesEncoded so you should be able to calculate framerate off of this, no?

If this is a limitation of WebRTC in Safari, is there a way that I am able to determine whether the current connection needs to upgrade/downgrade constraints? Is there an easier way to do this with peer to peer connections? I am unable to use "group" calling features from Twilio because of my applications requirements.

Currently I am evaluating these three metrics and determining a score for the current connection based off of them. If the average of that score over the past 10 seconds goes to below/above a certain value I downgrade/upgrade the video connection.

Loving Twilio Video so far!

**Comment by PikaJoyce** [comment]
Thanks for the information @KleptoKat!

For roundTripTime, this is not reported as it's the value for the whole connection and not for any specific track, so it is not reported. 

As for packetsLost, since it is being reported under inbound-rtp but not in outbound-rtp, this may be a bug. I will file a ticket for us to investigate further. 

And as for frameRate, we are unable to calculate this as framesEncoded only gives the encoded frame rate, but not the captured frame rate.

Unfortunately, a lot of those features are available only for group rooms. RTCPeerConnections is not officially exposed to the developer, but you can call `getStats` directly on the peer connection as shown below:
```JavaScript
[...(await room._signaling._peerConnectionManager._peerConnections.values().next().value._peerConnection._peerConnection.getStats()).values()]
```

Let me know if this was helpful! 

We appreciate the kind words :) 

Thank you!
Joyce

**Comment by KleptoKat** [comment]
Thanks Joyce!

After evaluating bytesSent and bytesReceived from each of these stats reports, it appears as though my solution doesn't seem to lower the evaluated bitrate on _any_ browser, rather it just decreases the quality. It appears as though video uses as much of the maxVideoBitrate as it possibly can up to a certain point - so even with my constraints really low, I was still using at least 1Mbps. I've lowered this rate to 100Kbps and stream quality seems to automatically be throttled through webRTC (to a point where it's really noticable). This is something we want sometimes - we often work in really low bandwidth scenarios or where there are a lot of connections running on the network at the same time. However, we don't want it all the time.

New question: is it possible to change maxVideoBitrate on the fly? (IE, a user is midway through the session and needs to lower their video quality because it is jittery/buggy - or we can detect dropped frames with some browsers. Is this possible? Or does it need to be done within the connect method?

Thanks so much!

**Comment by PikaJoyce** [comment]
You're welcome @KleptoKat !

It is totally possible to set maxVideoBitrate! In fact, we have an example of how to do this in the quickstart! Please check out the [Bandwidth Constraints example](https://github.com/twilio/video-quickstart-js/tree/master/examples/bandwidthconstraints). 

You can do so by calling `setParameters` on the `localParticipant` like so:
```
room.localParticipant.setParameters({ maxVideoBitrate: someMaxBits });
```
Here is some [documentation](https://media.twiliocdn.com/sdk/js/video/releases/2.14.0/docs/LocalParticipant.html#setParameters__anchor) on this as well.

Let me know if this works for you! 

I've also created an internal ticket(VIDEO-5535) to track investigation of why packetsLost is not being reported. For now, I'm going to close up this issue, but if you still have questions, please feel free to continue our discussion on this thread! 

Thank you again!
Joyce
