### ISSUE TITLE
What does network quality API actually report?

### ISSUE THREAD

**Issue by Ryner01** [twilio/twilio-video.js#1480]
I was looking at the network quality API and I am unsure about was is actually reported in `NetworkQualityBandwidthStats`.

From the docs, I can see the `actual` and `available` bandwidth fields. I presume that `available` is what the algorithm thinks that max upload speed is and `actual` is current real-time usage by Twilio?

But then when I check `actual` bandwidth in one of our calls I see a number like `4342248` which is way too large. According to docs, this should be in bytes but that would be around 35 Mb. Group rooms are limited to 4Mbps per participant right? So this should not be possible.

How should I interpret the stats from this API?

**Comment by charliesantos** [comment]
Hi @Ryner01 , thanks for reaching out! Let me find more information and get back to you.

**Comment by charliesantos** [comment]
Hey @Ryner01 , the API docs has been updated in this [PR](https://github.com/twilio/twilio-video.js/pull/1485/files).

> actual - the actual bandwidth used, in bits per second
> available - an estimate of available useable bandwidth, in bits per second

So in your example, `4342248` is about 4.3 megabits per second

**Comment by Ryner01** [comment]
Perfect thanks! Closing the issue.
