### ISSUE TITLE
Video.isSupported returning false in Safari for iOS

### ISSUE THREAD

**Issue by educobuci** [twilio/twilio-video.js#1484]
**Code to reproduce the issue:**

```js
const { isSupported } = require('twilio-video');
// Always return false
```

**Expected behavior:**

To return ```true```

**Actual behavior:**

It returns ```false```

**Software versions:**

 - [ ] Browser(s): Safari for iOS 14.6
 - [ ] Operating System: iOS 14.6
 - [ ] twilio-video.js: 2.14.0
 - [ ] Third-party libraries (e.g., Angular, React, etc.): none/plain JS

**Comment by charliesantos** [comment]
Hey @educobuci can you please post the userAgent string?

**Comment by educobuci** [comment]
Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15
(KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1

**Comment by charliesantos** [comment]
@educobuci the user agent looks good and it passes our checks when determining support. We cannot however check at this time whether RTCPeerConnection and getUserMedia are available, as we are currently updating our device to 14.6. Meanwhile, can you please check if WebRTC is supported? I think it should be, but I'm interested to see what is returned when you check the WebRTC APIs. Can you please try running this?
```js
function isWebRTCSupported() {
  return typeof navigator === 'object'
    && typeof navigator.mediaDevices === 'object'
    && typeof navigator.mediaDevices.getUserMedia === 'function'
    && typeof RTCPeerConnection === 'function';
}
```

**Comment by educobuci** [comment]
It returns 'false' as well. I found that ```navigator.mediaDevices === 'object'``` is failing. It looks like it is only supported in iOS if the page is served through https, is that true? That might be the reason since I'm testing from a local server without https.

**Comment by charliesantos** [comment]
@educobuci , that is correct. You need to serve your page through https with the exception of localhost. You might want to consider using ngrok or similar if you want to access your local server from your iOS device using https.
