### ISSUE TITLE
How much does the wait cost (Twilio-video)

### ISSUE THREAD

**Issue by Nawarius** [twilio/twilio-video.js#1486]
I have a group video chat. For example, I have 10 people chatting. 8 of them paused the video like this.

`publication.track.disable()`

Q: will I pay for these 8 people while their videos are paused?

**Comment by makarandp0** [comment]
Hello @Nawarius, Thank you for your question. The Video pricing is based on amount of time participants are connected to room. So yes, you will be charged for the even if the participants are not sharing video. You can read more about pricing [here](https://www.twilio.com/video/pricing)

Thanks,
Makarand

**Comment by Nawarius** [comment]
> Hello @Nawarius, Thank you for your question. The Video pricing is based on amount of time participants are connected to room. So yes, you will be charged for the even if the participants are not sharing video. You can read more about pricing [here](https://www.twilio.com/video/pricing)
> 
> Thanks,
> Makarand

Thanks for the answer. If I use this 

`publication.track.stop()`
`publication.unpublish()`


Will the money be spent too?

Will the board be the same as if I used
`publication.track.disable()`

The only way to stop wasting money is to leave the twilio room completely?

**Comment by makarandp0** [comment]
As long as participant is connected to the room, they will be charged. To avoid getting charged they need to leave the room.

**Comment by Nawarius** [comment]
> As long as participant is connected to the room, they will be charged. To avoid getting charged they need to leave the room.

So, speaking of payment, there is no difference between `disable()` and `unpublish()`?

**Comment by Nawarius** [comment]
Thanks for the answer. Now everything is clear

**Comment by makarandp0** [comment]
That is correct. You are charged for room minutes and not media flow.
