### ISSUE TITLE
How to publicly access twilio recording videos 

### ISSUE THREAD

**Issue by likhit-vivek** [twilio/twilio-video.js#1487]
Currently I am able to allow user to record the video meeting, use twilio Composition API to get the final video. 

But to access the video it is asking for a username and password. 

Since we have to show the recording on our website for the user who recorded the meeting, is there any public url of the recording which we can use to render the recording in a video tag without asking for login?

**Comment by makarandp0** [comment]
Hello @likhit-vivek, we don't provide public links to those videos. If you need them publicly accessible I suggest you download and host them on your server.
Thanks,
Makarand
