### ISSUE TITLE
Safari on M1 Mac crashes when accessing complex pages (usually with embeded content)

### ISSUE THREAD

**Issue by Fuchschr11** [twilio/twilio-video.js#1488]
Safari crashes when opening these pages:
- https://learningapps.org/
- https://rewoolution.it
- more to come, when it occurs...

The mouse pointer spins endlessly.

See Memory Dump

Same behaviour does not occur on Intel-Mac which I used before. M1 Mac was cloned with migration tool 5 month ago.

Hopefully someone can reproduce. 
Apple Support was no help :-(

——
[dump02062021.log](https://github.com/twilio/twilio-video.js/files/6584435/dump02062021.log)

**Comment by PikaJoyce** [comment]
Hey @Fuchschr11,

Please follow our issue template format in order for us to better assist you. 

I will be closing this issue now, if you'd like to reopen another issue, we hope to be more equipped to tackle the issues you're facing.

Regards,
Joyce
