### ISSUE TITLE
Not able to disconnect from room during browser refresh

### ISSUE THREAD

**Issue by swarnimsuman** [twilio/twilio-video.js#1494]
I've added the event handler to disconnect from the room when the user refreshes the browser but after the application loads back and tries to connect to the room again I'm getting the below error

Error Message  :  TwilioError: Participant disconnected because of duplicate identity
Error Code: 53205

It seems like room.disconnect is not working for some reason. 
Is it possible to handle this scenario after a refresh or just rejoin the room again?

**Comment by PikaJoyce** [comment]
Hi @swarnava,

When are you calling `room.disconnect`?

In our [Quickstart](https://github.com/twilio/video-quickstart-js), we rely on window events such as in [this example](https://github.com/twilio/video-quickstart-js/blob/59627b4f5fdd03da9a322fc6da63482de7aa0d7d/examples/remotereconnection/src/index.js#L95) to disconnect.

Best,
Joyce
