### ISSUE TITLE
[Question][Case] Integration of external audio stream with Twilio Video Program(video only)?

### ISSUE THREAD

**Issue by kumail-raza** [twilio/twilio-video.js#1499]
Is there a possibility that audio streamed over sip protocol can be published via Twilio video program?

An already build application for audio conferencing (using lib SipML). We have another application which is build with Twilio. We like to integration both the app such that audio from product A can be used in product B where video feature from product B remains there?

Is it possible, if yes! is there any document which could help me in this?

**Comment by charliesantos** [comment]
@kumail-raza thanks for reaching out! This should work if you use a SIP phone call in to Twilio and use the <Connect> TwiML verb to bring the call into the Room. See these docs for details

https://www.twilio.com/docs/video/adding-programmable-voice-participants-video-rooms

https://www.twilio.com/blog/now-you-can-add-programmable-voice-participants-video-group-rooms
