### ISSUE TITLE
Critical Issue: Extremely poor video quality

### ISSUE THREAD

**Issue by theDude30** [twilio/twilio-video.js#150]
Users were PC chrome using javascript and iphone using webview+ native iOS SDK.
Both users were in the same office space, one was connected using LTE connection and the other used the company network(after modifying the firewall to allow twillio video traffic).
The Client did more then a few tests, all of them had a very poor video quality that made the solution unusable.

In addition, the PC that the client used was quite old computer and the chrome browser happen to freeze at the beginning of the call and then it work fine, can it be related?

 - [X ] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [ X] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ X] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.

**Expected behavior:**

Video Should look good and crisp, if there are some network issues i would rather see small latency rather then poor video image.

**Actual behavior:**

I do not have any logs to show, however i have the following :
* SID: "6945ff46-7e97-4c88-aef2-f57d3b5f1582"
* Screen shots:
![s1](https://user-images.githubusercontent.com/5785389/29346954-95774758-8251-11e7-8d17-582dd446d924.png)

![s2](https://user-images.githubusercontent.com/5785389/29346961-9b0541a2-8251-11e7-9a0e-730dd7b291a3.png)

TODO

**Software versions:**

 - [ X] Browser(s): Chrome version 60
 - [X ] Operating System: PC Windows 7, iphone 10.3.2
 - [X ] twilio-video.js: 1.2.0
 - [X ] Third-party libraries (e.g., Angular, React, etc.): PC : Pure javasctipt. Iphone : Webview+ Native ios twilio SDK.

**Comment by kedartoraskar** [comment]
@theDude30 - as this issue is more operational in nature, I have moved this issue to the support channel. You can follow progress over email or from the Twilio Support inbox in your Twilio Account Console. Ticket #: 1051614
