### ISSUE TITLE
How to add VP9 codec to Group Room

### ISSUE THREAD

**Issue by mgarnick1** [twilio/twilio-video.js#1502]
I'm trying to set the preferredVideo Codec to be VP9 in the connectOptions for Chrome and Firefox, but when i inspect chrome://webrtc-internals. It still shows my code as VP8. Is there a correct way to use VP9 for group rooms. Here is an example of my network bandwidth profile and how i tried to use VP9. 

First attempt: 
`const bandwidthProfile = {
        preferredVideoCodecs: [{ codec: 'VP9' }],
        video: {
          mode: `${this.mode}`,
          trackSwitchOffMode: this.trackSwitchOffMode,
          maxSubscriptionBitrate: 4000000,
          dominantSpeakerPriority: 'standard',
          // allow all tracks to come through = 0
          clientTrackSwitchOffControl: 'auto',
          contentPreferencesMode: 'auto'
        },
      }`
      
  Second attempt: 
`const bandwidthProfile = {
        preferredVideoCodecs: ["VP9"],
        video: {
          mode: `${this.mode}`,
          trackSwitchOffMode: this.trackSwitchOffMode,
          maxSubscriptionBitrate: 4000000,
          dominantSpeakerPriority: 'standard',
          // allow all tracks to come through = 0
          clientTrackSwitchOffControl: 'auto',
          contentPreferencesMode: 'auto'
        },
      }`

Third Attempt
`const bandwidthProfile = {
        preferredVideoCodecs: "VP9",
        video: {
          mode: `${this.mode}`,
          trackSwitchOffMode: this.trackSwitchOffMode,
          maxSubscriptionBitrate: 4000000,
          dominantSpeakerPriority: 'standard',
          // allow all tracks to come through = 0
          clientTrackSwitchOffControl: 'auto',
          contentPreferencesMode: 'auto'
        },
      }`
 - [ x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [ x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x ] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Expected behavior:**

When i set the code to VP9, in chrome and firefox, the webrtc internals displays vp9 as the video codec. 

**Actual behavior:**
The video code states VP8 regardless of what was added to the preferredVideoCodec
**Software versions:**

 - [x ] Browser(s): Chrome and Firefox, i know Safari does not support VP9. 
 - [x ] Operating System: macOS 
 - [ x] twilio-video.js: 2.15.0
 - [ x] Third-party libraries (e.g., Angular, React, etc.): Vuejs

**Comment by charliesantos** [comment]
Hi @mgarnick1 , thank you for submitting. We currently do not support VP9 codec so the behavior you're seeing is expected.

**Comment by mgarnick1** [comment]
@charliesantos thank you for responding and addressing my question. You may want to put in a ticket to remove the reference to VP9 in <constant> VideoCodec :string
in the following location
https://media.twiliocdn.com/sdk/js/video/releases/2.14.0/docs/global.html#VideoCodec

**Comment by charliesantos** [comment]
@mgarnick1 thank you for pointing that out. We will update it.
