### ISSUE TITLE
Duplicate identity error - how to stop automatically rejoining?

### ISSUE THREAD

**Issue by chengtiffany** [twilio/twilio-video.js#1512]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**
Happens with base code.

**Expected behavior:**
Do not automatically rejoin room until error dialog is dismissed.

**Actual behavior:**
Both windows are disconnected (new window connects for a brief period before being disconnected), shown the error dialog, and both rooms continually attempt to rejoin.

**Software versions:**

 - [x] Browser(s): Chrome, Firefox
 - [x] Operating System: MacOS
 - [x] twilio-video.js: 2.15.1
 - [x] Third-party libraries (e.g., Angular, React, etc.): React 17.0.2

**Comment by PikaJoyce** [comment]
Hey @chengtiffany!

Thanks for opening this issue, apologies for the late response. Do you have any samples of the code that is causing this? 

Best,
Joyce

**Comment by chengtiffany** [comment]
> Hey @chengtiffany!
> 
> Thanks for opening this issue, apologies for the late response. Do you have any samples of the code that is causing this?
> 
> Best,
> Joyce

Hi Joyce! Thanks for responding! I think it might be an inherent feature. It was happening on after I cloned the repo without any additional code.

**Comment by PikaJoyce** [comment]
Hi Tiffany,

Sounds good! Thank you again, I'll be closing this issue now. Feel free to open another if you open into any new issues!

Best,
Joyce
