### ISSUE TITLE
Incompatible with angular 12

### ISSUE THREAD

**Issue by itsTeknas** [twilio/twilio-video.js#1517]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

```js
Upgrade working project to angular 12 using official guidelines
```

**Expected behavior:**

Angular project should compile and work

**Actual behavior:**
ng build
```
./node_modules/twilio-video/es5/media/track/es5/localaudiotrack.js:6:15-30
./node_modules/twilio-video/es5/media/track/es5/localvideotrack.js:6:15-30
./node_modules/twilio-video/es5/media/track/es5/localdatatrack.js:6:15-30
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
        - install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "util": false }
```

**Software versions:**

 - [x] Browser(s): Chrome
 - [x] Operating System: Mac OS
 - [x] twilio-video.js: 2.15.1
 - [x] Third-party libraries (e.g., Angular, React, etc.): Angular 12.0.0

**Comment by PikaJoyce** [comment]
Hey @itsTeknas 

Thank you for opening this issue, I apologize for the delayed response. Is it possible for you to provide more information? We don't believe that we need polyfills so it would be useful to know where the build is failing.

Best,
Joyce

**Comment by mgesuitti** [comment]
@PikaJoyce I have the same issue and there are more details in this thread https://github.com/twilio/twilio-video.js/issues/1242

**Comment by PikaJoyce** [comment]
Hey @mgesuitti! 

Thanks for linking that issue. I will respond back once I gather some more information with the team on how to proceed forward with this issue! In the meanwhile, I'll keep this thread open and keep it updated.

Regards,
Joyce

**Comment by itsTeknas** [comment]
I believe they have removed some node polyfills in webpack5 that were included by default in webpack4.
The webpack config file for angular is in node_modules and editing it should not be considered. 
Maybe an overriding config in our project and how to set that up in your readme/setup guide will help.

**Comment by PikaJoyce** [comment]
Hey everyone,

Small update, we have created an internal ticket to track this issue and investigate further. 

Thanks everyone for your patience!
Joyce

**Comment by KaelWD** [comment]
Also see #1147

**Comment by hsavit1** [comment]
@PikaJoyce any updates?

**Comment by PikaJoyce** [comment]
Hi @hsavit1,

Thank you for the ping! Currently, there are efforts that address this issue in the works. We hope to have a resolution out sometime in the near future! I will keep this thread updated as progress continues.

Best,
Joyce

**Comment by PikaJoyce** [comment]
Hi folks,

Just a quick update here, the latest release [2.21.1](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md#2211-march-22-2022) fixes this issue. Please give it a spin and let us know if you're still seeing any issues! I will now be closing this ticket. Please do feel free to open another issue if any new ones occur!

Thank you for all of your patience,
Joyce
