### ISSUE TITLE
The room recording is stopped if any of participants leaves

### ISSUE THREAD

**Issue by alexxty7** [twilio/twilio-video.js#1522]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

You can reproduce using https://github.com/twilio/twilio-video-app-react

**Expected behavior:**
When any of the participants leave the room we do not receive recordingStopped event
Recording should be stopped when it is triggered by some user or the last user left the room 

**Actual behavior:**
We start recording using recording rules API ({ type: :include, all: true }).
When recording started user sees the recording indicator using room.isRecording getter as true
and recordingStarted event.

When any of the participants leave the room we receive recordingStopped event and room.isRecording as false.
This means the recording is stopped but it wasn't initiated by any of the users.
If the user makes page refresh then room.isRecording shows back are true.

**Software versions:**

 - [x] Browser(s): Version 91.0.4472.114 (Official Build) (x86_64)
 - [x] Operating System: MacOs 11.2.2
 - [x] twilio-video.js: 2.15.1
 - [x] Third-party libraries (e.g., Angular, React, etc.): React

**Comment by eoris** [comment]
Any news about this issue?

**Comment by ivanin-illia** [comment]
it has been reproduced  for me as well

**Comment by charliesantos** [comment]
Hi, apologies for the delay. I submitted an internal ticket for this issue.

**Comment by grp06** [comment]
Thank you so much for reporting this! It's making me go crazy, I thought it was something I was doing wrong! This bug is literally making our app unstable and not usable. We released a feature that uses the composition API and if any user refreshes during a session, it completely ruins our user's experience.

I don't know how many other organizations are using the compositions API but I'm certain that this bug is causing problems for every customer using it. Please fix!

**Comment by donaltoomey** [comment]
Hi folks, apologies for the inconvenience here. We have a fix in the works. Bear with us as we do the required test and release process.

**Comment by donaltoomey** [comment]
The fix is in production. Let us know if you still see the issue.

**Comment by charliesantos** [comment]
Closing as this is already fixed on prod.
