### ISSUE TITLE
Issue with Firefox version 55.0.2 using Group mode -no video on participant reconnect

### ISSUE THREAD

**Issue by diydan** [twilio/twilio-video.js#155]
Hello,

I'm experiencing a specific issue with Firefox version 55.0.2 using Group mode.

If there are only 2 participants, both connect fine initially however if the FIRST participant needs to reconnect within a short time (use case crash/internet drop or page refresh) then no video is displayed (black video on Chrome, blank on local Firefox) on recconect

Audio track works fine.

No problem using peer-to-peer and no problem if using pervious versions of Firefox (54)
If both participants reconnect, works fine.
 
Can replicate in both our own app and the example app as shown in screenshots below

Initial Connect: Video all A OK
![image](https://user-images.githubusercontent.com/1441472/29486800-d2a984e6-8531-11e7-9073-273162539477.png)

After refresh or leave and rejoin room (no remote video):
![image](https://user-images.githubusercontent.com/1441472/29486810-ec670958-8531-11e7-8098-4174fbb96da0.png)

Thanks

Dan

 - [X] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [X] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [X] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.

**Code to reproduce the issue:**
https://github.com/twilio/video-quickstart-js (using a group token)

Debug Log suggests video track was ended :

SIP/2.0 200 OK
Via: SIP/2.0/WSS 172.18.7.183:443;branch=z9hG4bKdf5a2622-bff3-47fd-8095-1672541cbbcf_6772d868_187-12589759545284304035
To: <sip:f0b88a01-fb3e-44b6-bd33-588371aa3786@endpoint.twilio.com>;tag=fc1l46u3sl
From: <sip:orchestrator@endpoint.twilio.com>;tag=05691326_6772d868_df5a2622-bff3-47fd-8095-1672541cbbcf
Call-ID: 26vgbmoiuljvuraongr5
CSeq: 3 INFO
Supported: outbound, room-signaling, timer
User-Agent: SIP.js/0.7.5
Content-Length: 0

twilio-video.min.js:93 2017-08-19 13:13:05.315Z | DEBUG in [VideoTrack #74: {0aefe0f9-7e3d-0941-91d0-b34fdeec7881}]: Ended
twilio-video.min.js:97 Sat Aug 19 2017 23:13:05 GMT+1000 (AEST) | sip.transaction.nist | Timer J expired for non-INVITE server transaction z9hG4bKdf5a2622-bff3-47fd-8095-1672541cbbcf_6772d868_187-12589759545284304035
twilio-video.min.js:97 Sat Aug 19 2017 23:13:05 GMT+1000 (AEST) | sip.transport | sending WebSocket message:

INFO sip:172.18.7.183:443;transport=wss SIP/2.0
Via: SIP/2.0/WSS pml2dqj3qu20.invalid;branch=z9hG4bK2578432
Max-Forwards: 70
To: <sip:orchestrator@endpoint.twilio.com>;tag=05691326_6772d868_df5a2622-bff3-47fd-8095-1672541cbbcf
From: <sip:f0b88a01-fb3e-44b6-bd33-588371aa3786@endpoint.twilio.com>;tag=fc1l46u3sl
Call-ID: 26vgbmoiuljvuraongr5
CSeq: 6549 INFO
Content-Type: application/room-signaling+json
Event: room-signaling
Info-Package: room-signaling
Supported: outbound, room-signaling, timer
User-Agent: SIP.js/0.7.5
Content-Length: 2727

{"type":"update","version":1,"peer_connections":[{"description":{"type":"answer","revision":3,"sdp":"v=0\r\no=- 5013932752531673422 4 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE audio video\r\na=msid-semantic: WMS c80845fe-32bb-4e83-a6f3-2637592497c2\r\nm=audio 56105 UDP/TLS/RTP/SAVPF 111 0\r\nc=IN IP4 120.154.112.166\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=candidate:3186149815 1 udp 2122260223 10.0.0.4 56105 typ host generation 0 network-id 1 network-cost 10\r\na=candidate:2190355870 1 udp 1686052607 120.154.112.166 56105 typ srflx raddr 10.0.0.4 rport 56105 generation 0 network-id 1 network-cost 10\r\na=candidate:4083889479 1 tcp 1518280447 10.0.0.4 9 typ host tcptype active generation 0 network-id 1 network-cost 10\r\na=ice-ufrag:f79N\r\na=ice-pwd:C1DtbLc1Z7YpbLQLhUvDOHbZ\r\na=ice-options:trickle\r\na=fingerprint:sha-256 DA:11:DC:70:25:7D:A7:94:27:1E:C9:42:0E:2F:14:DD:8B:49:9E:B9:99:AC:A8:65:7E:B7:6F:4B:9D:D3:1B:F8\r\na=setup:passive\r\na=mid:audio\r\na=sendrecv\r\na=rtcp-mux\r\na=rtpmap:111 opus/48000/2\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=rtpmap:0 PCMU/8000\r\na=ssrc:878983093 cname:6xOjAkjIFeak+92u\r\na=ssrc:878983093 msid:c80845fe-32bb-4e83-a6f3-2637592497c2 8f361e0b-09b7-461e-9c8b-148e70ab70f9\r\na=ssrc:878983093 mslabel:c80845fe-32bb-4e83-a6f3-2637592497c2\r\na=ssrc:878983093 label:8f361e0b-09b7-461e-9c8b-148e70ab70f9\r\nm=video 9 UDP/TLS/RTP/SAVPF 96\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:f79N\r\na=ice-pwd:C1DtbLc1Z7YpbLQLhUvDOHbZ\r\na=ice-options:trickle\r\na=fingerprint:sha-256 DA:11:DC:70:25:7D:A7:94:27:1E:C9:42:0E:2F:14:DD:8B:49:9E:B9:99:AC:A8:65:7E:B7:6F:4B:9D:D3:1B:F8\r\na=setup:passive\r\na=mid:video\r\na=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=sendrecv\r\na=rtcp-mux\r\na=rtpmap:96 VP8/90000\r\na=rtcp-fb:96 ccm fir\r\na=rtcp-fb:96 nack\r\na=rtcp-fb:96 nack pli\r\na=rtcp-fb:96 goog-remb\r\na=ssrc-group:FID 2354561333 308866419\r\na=ssrc:2354561333 cname:6xOjAkjIFeak+92u\r\na=ssrc:2354561333 msid:c80845fe-32bb-4e83-a6f3-2637592497c2 5985b827-ffb8-4a29-8ba5-74d7b7716b8e\r\na=ssrc:2354561333 mslabel:c80845fe-32bb-4e83-a6f3-2637592497c2\r\na=ssrc:2354561333 label:5985b827-ffb8-4a29-8ba5-74d7b7716b8e\r\na=ssrc:308866419 cname:6xOjAkjIFeak+92u\r\na=ssrc:308866419 msid:c80845fe-32bb-4e83-a6f3-2637592497c2 5985b827-ffb8-4a29-8ba5-74d7b7716b8e\r\na=ssrc:308866419 mslabel:c80845fe-32bb-4e83-a6f3-2637592497c2\r\na=ssrc:308866419 label:5985b827-ffb8-4a29-8ba5-74d7b7716b8e\r\n"},"id":"cb6b7d85-28cc-4d9b-a281-f3cdb9e3c3f5"}],"participant":{"revision":1,"tracks":[{"enabled":true,"id":"8f361e0b-09b7-461e-9c8b-148e70ab70f9","kind":"audio"},{"enabled":true,"id":"5985b827-ffb8-4a29-8ba5-74d7b7716b8e","kind":"video"}]}}

**Software versions:**

 - [X] Browser(s):FireFox 55.0.2
 - [X] Operating System: Mac Sierra
 - [X] twilio-video.js: 1.2.1
 - [ ] Third-party libraries (e.g., Angular, React, etc.): N/A

**Comment by markandrus** [comment]
@diydan thanks for your report. I will share this with our media server team, and we'll work towards identifying a fix. As a short-term workaround, could you try re-connecting with a new LocalVideoTrack? Does this improve things?

Best,
Mark

**Comment by diydan** [comment]
This looks to be resolved in recent updates, can no longer replicate 👍
