### ISSUE TITLE
Scrrenshare video stream not showing in mobile

### ISSUE THREAD

**Issue by sdz28r** [twilio/twilio-video.js#1558]
issue: I am building a screen-share app using latest version of twilio video sdk, everything is working great for desktop. But when I share the screen from desktop and try to receive it in mobile, the video tag gets attached to the correct parent but video feed is not showing up in mobile....

Anybody facing the same issue??

**Comment by manjeshbhargav** [comment]
Hi @sdz28r ,

Sorry for the delayed response. Can you please share some room sids so we can begin to investigate?

Thanks,

Manjesh
