### ISSUE TITLE
trackAdded event not being called in Safari 11 Using Angular 4.x.x

### ISSUE THREAD

**Issue by treyrich** [twilio/twilio-video.js#156]
Apologies if this should have been included under #122, but if feels like it may merit additional discussion.

I've been successful in getting Safari to send its media to another browser (Chrome, FF, etc), and that browser is able to see and hear everything fine. However, for whatever reason Safari never receives the `trackAdded` event (neither on the room nor the participant). All other events appear to be functioning as expected (`participantConnected`, `participantDisconnected`, `disconnected`).

The odd thing about this is that the quickstart is working in Safari, and is receiving the `trackAdded` events as expected.

It's entirely possible that something about our application is causing this, but I'd say this still qualifies as a bug of some kind considering the app works perfectly with Chrome/Firefox.

I'm happy to make a pull request surrounding this, and plan to try to debug it further, but I figured getting it on other's radar's is a good idea in case I'm making a complete rookie mistake.

**Comment by markandrus** [comment]
Hi @treyrich,

Can you share a Room SID? Also, can you share the code for

1. Handling Participants, and
2. Handling Tracks?

For 1, you need to handle Participants already connected in `participants` _as well as_ any Participants connected via the "participantConnected" event. For 2, you need to handle any Participant's Tracks already added in `tracks` _as well as_ any Tracks added via the "trackAdded" event. Can you confirm you are doing this? Typically the code will look like

```js
room.participants.forEach(handleParticipant)
room.on('participantConnected', handleParticipant)

function handleParticipant(participant) {
  participant.tracks.forEach(handleTrack)
  participant.on('trackAdded', handleTrack)
}

function handleTrack(track) {
  const element = track.attach()
  // Do something with element...
}
```

Also, any logs you can share (especially from Safari) would be very useful. In order to enable debug logging, please `connect` with `logLevel` set to "debug", e.g.

```js
connect(token, { logLevel: 'debug' })
```

Thanks,
Mark

**Comment by treyrich** [comment]
Definitely, let me see if I can get you everything here in a coherent manner...

**Room SID:** RM3337f01cbeb902a70f9387f8ba3fb314

I've emailed you the debug logs to avoid too enormous of a comment here, feel free to post anything you feel relevant to the issue from them back here for future users.

So, to begin we connect the call:
```typescript
    Video.connect(this.token, {
      name: callName
    }).then((room) => {
      this.roomConnected(room);
    }, (err) => {
      console.log('Error connecting to room!');
      console.log(err);
    });
```
which calls the method `roomConnected` which looks like:
```typescript
private roomConnected(room) {
    ...
    room.localParticipant.videoTracks.forEach((track, trackID) => {
      track.attach(this.localMediaVideoElm);
    });
    room.localParticipant.audioTracks.forEach((track, trackId) => {
      track.attach(this.localMediaAudioElm);
    });
    room.participants.forEach((participant, participantId) => {
      this.participantConnected(participant);
    });
    room.on('participantConnected', (participant) => {
      this.participantConnected(participant);
    });
    // when a participant disconnects
    room.once('participantDisconnected', (participant) => {
      participant.removeAllListeners();
      ...
    });
    room.once('disconnected', (room) => {
      ...
    });
    ...
}
```
This calls the `participantConnected` method which is defined as:
```typescript
  private participantConnected(participant) {
    ...
    if (participant.videoTracks) {
      participant.videoTracks.forEach((track, trackId) => {
        track.attach(this.remoteMediaVideoElm);
      });
    }
    if (participant.audioTracks) {
      participant.audioTracks.forEach((track, trackId) => {
        track.attach(this.remoteMediaAudioElm);
      });
    }
    participant.on('trackAdded', (track) => {
      if (track.kind === 'video') {
        track.attach(this.remoteMediaVideoElm);
      } else {
        track.attach(this.remoteMediaAudioElm);
      }
    });
  }
```

As mentioned, all of the events are being called with the exception of `trackAdded`, so I can see when the participant joins, and when they leave, but not when they add tracks. This is the case 100% of the time. I can always see the local media preview on screen, and the other browser can always see the remote video (using the exact same code). 

For the record this is being tested on Safari Version 11.0 (12604.1.38.1.3).

**Comment by treyrich** [comment]
The oddest thing to me is that the event fires properly using the quickstart using the same 2 browsers as test subjects, but I cannot figure out what the difference is, they seem all but identical to me.

**Comment by markandrus** [comment]
@treyrich I am still looking at the logs you sent me, but I am wondering

> The oddest thing to me is that the event fires properly using the quickstart using the same 2 browsers as test subjects, but I cannot figure out what the difference is, they seem all but identical to me.

Is there any chance a library like adapter.js is also loaded into your webapp?

**Comment by treyrich** [comment]
Hmmm, no, the closest thing would be https://github.com/muaz-khan/DetectRTC

It's an Angular app, so it has all the regular suspects involved with that, but otherwise nothing to do with WebRTC.

**Comment by markandrus** [comment]
Based on the SDPs in the logs, we should be expecting an AudioTrack and VideoTrack to be received in Safari with IDs `ad8cf83f-ce62-441e-a3b8-e842c91964f7` and `a3d6a9b1-7224-489d-a464-13dd749916d1`, respectively. But they never show. Thanks for confirming on the WebRTC thing. Can you check one more thing, that there is no `window.adapter` global? (Just in case it snuck in there via a transitive dependency...)

**Comment by treyrich** [comment]
Yeah, I just checked and there's nothing. Additionally I tried removing the DetectRTC library from the build and it still had the same issues.

If this helps narrow it down, I do believe that the information is being sent about the tracks, but where it gets hung up is [here](https://github.com/twilio/twilio-video.js/blob/master/lib/signaling/v2/remoteparticipant.js#L91) this promise never resolves.

**Comment by markandrus** [comment]
Thanks for checking again. Your analysis that the Promise doesn't resolve seems correct, and the reason it wouldn't resolve is because a "track" event from the underlying RTCPeerConnection containing the MediaStreamTrack is not being raised. I've tried to trigger this behavior by loading the same SDP from your logs in a JSFiddle and trying to set it via `setRemoteDescription`, but even then I am able to see the expected RTCTrackEvents. I wonder, could you update Safari and try with `Safari 11.1, WebKit 12605.1.2`? I see you are using `12604.1.38.1.3` (although I'm not sure what Safari's versioning scheme is...)

**Comment by treyrich** [comment]
Yeah, I'm happy to update if you think that's what is needed, though I'd venture to say that with the quickstart working correctly for me in this version I'm running it probably won't make a difference.

To be clear, the version that I'm running is the most up to date Safari 11 beta out there. The 11.1 that you're running is the tech preview version which will not be what ships with iOS 11 or macOS 10.13

So, just to double check, you still think it's worth me updating to the tech preview?

**Comment by markandrus** [comment]
@treyrich and I chatted--Safari Beta versus Tech Preview should not be the issue. Instead, this may be another Zone.js-related issue. I saw, for example, some funny properties added to the underlying RTCPeerConnection:

<img width="483" alt="screen shot 2017-08-21 at 2 38 45 pm" src="https://user-images.githubusercontent.com/359154/29539919-e350a70c-8680-11e7-8c6c-07d30da52a68.png">

The `__zone_symbol__trackfalse` entry is concerning, since, if the "track" event handler gets messed up in any way, we won't resolve the Promise described above. I am going to update our Angular Framework Test to test this.

**Comment by markandrus** [comment]
This is a Zone.js issue: https://github.com/angular/zone.js/issues/883

The last version of Zone.js without this bug was 0.8.12. If you can pin to this version, I think the bug will go away. In the meantime, perhaps the Zone.js Team will be able to land a fix?

**Comment by treyrich** [comment]
Awesome, well I suppose I'll start tracking that issue there. Not sure that this issue needs to remain open if there's no bug in this library...?

**Comment by markandrus** [comment]
If pinning to 0.8.12 for the time being works for you, then yes, I think we can close this ticket. Based on my comment [here](https://github.com/angular/zone.js/issues/883#issuecomment-323875541), we could potentially workaround this in twilio-video.js by replacing [our use of `addEventListener('track', ...)`](https://github.com/twilio/twilio-video.js/blob/1.2.1/lib/webrtc/rtcpeerconnection/safari.js#L182) with `ontrack`, but if Zone.js can fix this quickly I'd rather not workaround it. So if you are OK closing the ticket, feel free.

**Comment by treyrich** [comment]
Yeah, I can confirm 0.8.12 works as expected. I think for now I'll close this out and track the Zone.js issue, though I assume that as we get closer to Safari actually launching it may start to make sense to perform the patch you're describing.

**Comment by treyrich** [comment]
@markandrus any thoughts on this now that the launch of Safari 11 is looming? I tried asking over at the zone.js issue and just got crickets.

**Comment by markandrus** [comment]
@treyrich that's unfortunate... I [commented](https://github.com/angular/zone.js/issues/883#issuecomment-329879530) over there with a potential workaround. Could you try placing this in your application before loading/using twilio-video.js?

```js
const originalAddEventListener = RTCPeerConnection.prototype.addEventListener
RTCPeerConnection.prototype.addEventListener = function addEventListener(event, listener) {
  if ('on' + event in this) {
    this._eventListeners = this._eventListeners || new Map()
    const listeners = this._eventListeners.get(event) || []
    listeners.push(listener)
    this._eventListeners.set(event, listeners)
    if (typeof this['on' + event] !== 'function') {
      var self = this
      this['on' + event] = function applyListeners() {
        const listeners = self._eventListeners.get(event) || []
        listeners.forEach(listener => {
          try {
            listener.apply(self, arguments)
          } catch (error) {
            console.error(error)
          }
        })
      }
    }
    return
  }
  originalAddEventListener.call(this, event, listener)
}

const originalRemoveEventListener = RTCPeerConnection.prototype.removeEventListener
RTCPeerConnection.prototype.removeEventListener = function removeEventListener(event, listener) {
  if ('on' + event in this) {
    this._eventListeners = this._eventListeners || new Map()
    const listeners = this._eventListeners.get(event) || []
    this._eventListeners.set(event, listeners.filter(_listener => _listener !== listener))
    return
  }
  originalRemoveEventListener.call(this, event, listener)
}
```

If it looks OK, we may land it in a proper release.

**Comment by treyrich** [comment]
Does it matter whether it's ran before or after zone.js is added?

**Comment by markandrus** [comment]
@treyrich it should not matter.

**Comment by treyrich** [comment]
It appears this is causing an error [here](https://github.com/twilio/twilio-webrtc.js/blob/master/lib/rtcpeerconnection/safari.js#L186). `TypeError: undefined is not an object (evaluating 'event.track.kind')`

The issue is that `event` is a function, not an object.

**Comment by treyrich** [comment]
Actually, scratch that. The issue was  the `listener.apply(self, arguments)` was getting screwed up when running through TypeScript.

I modified to this:
```JavaScript
const originalAddEventListener = RTCPeerConnection.prototype.addEventListener
RTCPeerConnection.prototype.addEventListener = function addEventListener(event, listener) {
  if ('on' + event in this) {
    this._eventListeners = this._eventListeners || new Map()
    const listeners = this._eventListeners.get(event) || []
    listeners.push(listener)
    this._eventListeners.set(event, listeners)
    if (typeof this['on' + event] !== 'function') {
      var self = this
      this['on' + event] = function applyListeners() {
        var a = arguments;
        const listeners = self._eventListeners.get(event) || []
        listeners.forEach(listener => {
          try {
            listener.apply(self, a)
          } catch (error) {
            console.error(error)
          }
        })
      }
    }
    return
  }
  originalAddEventListener.call(this, event, listener)
}

const originalRemoveEventListener = RTCPeerConnection.prototype.removeEventListener
RTCPeerConnection.prototype.removeEventListener = function removeEventListener(event, listener) {
  if ('on' + event in this) {
    this._eventListeners = this._eventListeners || new Map()
    const listeners = this._eventListeners.get(event) || []
    this._eventListeners.set(event, listeners.filter(_listener => _listener !== listener))
    return
  }
  originalRemoveEventListener.call(this, event, listener)
}
```

And now it's functioning properly.

**Comment by markandrus** [comment]
Since the update in https://github.com/angular/zone.js/issues/883#issuecomment-329938702, I wonder if we should add the "official" workaround to `COMMON_ISSUES.md`.

**Comment by treyrich** [comment]
Yeah, I suppose that's probably the best solution for now...It's unfortunate that there's nothing better, but I guess it's on webkit.

**Comment by sfakir** [comment]
Is this still needed in the latest version of twilio video?

**Comment by huntersinclairtiv** [comment]
Just posting in case anyone comes along this thread.  As of June 3, 2020 - Using version 2.4 of Twilio and Angular 8.x - I was still experiencing this issue with Safari - It would not get any events on tracks or room.  My Safari I tested was 12.1.2 on Mac Pro Mojave.  A few users reported it working for them in safari 13.x so not sure why that is, but this fix mostly worked for me.  However I had to add a browser check condition around the main override code to check for Safari, since I noticed that it broke video subscriptions from working in Chrome.  Here is my slightly altered code used in Angular - I just load this in the ngOnInit for my main application page where I call connect from.  
```
      const isSafari = this.deviceService.browser === 'Safari';
      const originalAddEventListener = RTCPeerConnection.prototype.addEventListener;
      RTCPeerConnection.prototype.addEventListener = function addEventListener(event, thisListener) {
        if (('on' + event in this) && isSafari) {
          this._eventListeners = this._eventListeners || new Map();
          const listeners = this._eventListeners.get(event) || [];
          listeners.push(thisListener);
          this._eventListeners.set(event, listeners);
          if (typeof this['on' + event] !== 'function') {
            const self = this;
            this['on' + event] = function applyListeners() {
              const a = arguments;
              const theseListeners = self._eventListeners.get(event) || [];
              theseListeners.forEach(listener => {
                try {
                  listener.apply(self, a);
                } catch (error) {
                  console.error(error);
                }
              });
            };
          }
          return;
        }
        originalAddEventListener.call(this, event, thisListener);
      };

      const originalRemoveEventListener = RTCPeerConnection.prototype.removeEventListener;
      RTCPeerConnection.prototype.removeEventListener = function removeEventListener(event, listener) {
        if (('on' + event in this) && isSafari) {
          this._eventListeners = this._eventListeners || new Map();
          const listeners = this._eventListeners.get(event) || [];
          this._eventListeners.set(event, listeners.filter(_listener => _listener !== listener));
          return;
        }
        originalRemoveEventListener.call(this, event, listener);
      };

```
