### ISSUE TITLE
No video/audio from a participant from Chrome on Android 11

### ISSUE THREAD

**Issue by KosmyninOleksandr** [twilio/twilio-video.js#1562]
Some of our users who have mobile phone with Android 11 experience issues joining to group rooms. Other participants can neither see nor hear them.

I've done several check using https://test.webrtc.org and https://networktest.twilio.com:
- https://test.webrtc.org/ stoped on checking network. I was restarting it several times. UDP a few times passed but TCP.
- https://networktest.twilio.com/ most of checks failed. Only `Video ... Connectivity` passed. 

I was able to reproduce this issue on the app build from https://github.com/twilio/twilio-video-app-react

**Comment by manjeshbhargav** [comment]
Hi @KosmyninOleksandr ,

Thanks for writing in with your issue. Please provide some Room sids so we can begin the investigation.

Thanks,

Manjesh

**Comment by leonard-morina** [comment]
Im facing this issue as well with Android phones on version 11, based on my observation the user was able to connect to twilio via the token but the audio tracks and video tracks are undefined, Firefox does work. Also did the test on [https://networktest.twilio.com/](url) and all of the checks were failing for me.

Room Sid: RM794c1d2ee825353715b442217f60c049
Participant Sid: PA1562c029e29d7235f68fc187e5842345

Test was done on a Samsung Galaxy A12.
