### ISSUE TITLE
White noise/ Hiss sound when using my system's default mic

### ISSUE THREAD

**Issue by git-anshuls** [twilio/twilio-video.js#1567]
There is a constant hissing sound when the user has joined the call using their system microphone. 

 - [ yes] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [ yes] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ ] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [ yes ] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Expected behavior:**

The voice should be clear.

**Actual behavior:**

There is a hissing sound.

**Software versions:**

 - [ ] Browser(s): Chrome 92
 - [ ] Operating System: Mac Big Sur
 - [ ] twilio-video.js: 2.16 / 2.12
 - [ ] Third-party libraries (e.g., Angular, React, etc.): React

**Comment by makarandp0** [comment]
Hello @git-anshuls, This looks related the the an internal ticket (VIDEO-6919) - Looks like you need to turn on `noiseSuppression: true` for the acquired audio track to be able to remove the hiss sound. 

I created a small demo app that acquires an audio track with specified settings and then uses loopback webrtc connection to render remote track. This app does not use any twilio-video sdk code. Please check out the sample @ https://makarandp0.github.io/echo_cancellation_demo/index.html to experiment with various settings.

**Comment by makarandp0** [comment]
Hello @git-anshuls - I am closing this old issue, Please open a new issue if you have further questions .
