### ISSUE TITLE
Error stopping track in iOS devices

### ISSUE THREAD

**Issue by AliciaCamCas** [twilio/twilio-video.js#1571]
We recently updated twilio-video from v1.20.0 to v2.15.3 and we modified the code to adapt it to the new methods. In our app, we first record with the back camera and, in the middle of the process, we change to the front camera. 
After the update, when we retrieve the video to visualice it, in the case of videos recorded in iOS, there is a 10 seconds fragment in black between the back camera frames and the front frames (when we are recording the video, the transition from back to front camera is quick).
To avoid this, in iOS' cases we have to stop the back record with tracks.disable() and in other devices with tracks.stop(). Is this correct?
Below I include the code we use to change from back to front camera. Is this the right way to do it?

**Code to reproduce the issue:**
This is the code where we stop the back camera track:
function closeVideoStreams(isIosDevice) {
    if(activeScan && activeScan.localParticipant) {
        const tracks = Array.from(activeScan.localParticipant.videoTracks.values()).map(publication => publication.track);
        if (isIosDevice) {
            tracks[0].disable();
        } else {
            tracks[0].stop();
        }
    }
}

This is the code where we create the new front camera track:
function generateStream(callback) {
  Video.createLocalVideoTrack({
        facingMode: 'user'
      }).then(function(localVideoTrack) {
        activeScan.localParticipant.publishTrack(localVideoTrack);
        if(callback != undefined) {
            callback(localVideoTrack.mediaStreamTrack);
        }
      });
}

**Expected behavior:**

Stop the video with the same method for all devices and when we visualice the video, it shouldn't have a fragment in black.

**Actual behavior:**

We have to use a different method to stop the track for iOS devices. If not, there is a black fragment in the recorded video.

**Software versions:**

 - [ ] Browser(s): Safari, Chrome
 - [ ] Operating System: iOS 14.5
 - [ ] twilio-video.js: 2.15.3

**Comment by manjeshbhargav** [comment]
Hi @AliciaCamCas ,

Thanks for writing in with your question. Actually, there is a much simpler way to switch cameras. You can use the [LocalVideoTrack.restart](https://sdk.twilio.com/js/video/releases/2.17.0/docs/LocalVideoTrack.html#restart__anchor) method with a new capture constraints. You don't need to unpublish and re-publish the video track. Please let me know if this helps.

**Comment by AliciaCamCas** [comment]
Hi @manjeshbhargav ,

Thanks for your answer. This solution worked for us.

Thank you!
