### ISSUE TITLE
Audio desynchronized after updating to v2.x

### ISSUE THREAD

**Issue by AliciaCamCas** [twilio/twilio-video.js#1577]
Hello, and thank you for your time.
In our app, the user has to say some codes while the video is being recorded by twilio. When we retrieve the video, the audio is not synchronized with it. The code sounds a few seconds before it is really said by the user. Also, in the last 10 seconds (approximately) of the video, it doesn't have sound.
This started to happen after we updated twilio-video from 1.20.0 to 2.15.3. We changed all the things indicated in your migration guide.

**Code to reproduce the issue:**

This is how we create the tracks:
Video.createLocalTracks(videoOptions).then(function(localVideoTrack) {
     connectVideo(localVideoTrack); // Calls Video.connect() and create the room
     startLocalVideoTrack = localVideoTrack[1]; // Saves the video track to publish it when room is created
});

When the room is created, we publish the video track:
activeScan.localParticipant.publishTrack(startLocalVideoTrack);

We also tried publishing the audio track but the result is the same

**Expected behavior:**

Video and audio should be synchronized, as it was in v1.20.0

**Actual behavior:**

Video and audio are not synchronized. The audio is a few seconds ahead of the video.

**Software versions:**

 - [ ] Browser(s): Chrome, Safari, Firefox...
 - [ ] Operating System: iOS, Android, Mac
 - [ ] twilio-video.js: 2.15.3

**Comment by makarandp0** [comment]
Hello @AliciaCamCas, Thank you for reporting this issue. Please share room-sid where you saw this issue. We  also need your permission to access recording for the same room.

Thank,
Makarand

**Comment by AliciaCamCas** [comment]
Hello @makarandp0, thanks for your answer. After doing some test in our server, the problem seems to be in the program we use to mix the audio and video we download from Twilio. The audio file we receive is correct. I'll update this post when we finally fix this problem.

**Comment by makarandp0** [comment]
Hello @AliciaCamCas - I am closing this issue now. Please reopen if you are seeing issue after fixing your audio mixer.
