### ISSUE TITLE
[TwilioVideo] Error on publish track

### ISSUE THREAD

**Issue by nicolasdezena** [twilio/twilio-video.js#1581]
- [x ] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [ x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [ x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

Hey guys, I have a problem with the video, when I start then pause then start and pause and start again I get the error below

![Captura de Tela 2021-09-20 às 17 16 46](https://user-images.githubusercontent.com/14208388/134218923-c836ae64-3c93-47ab-9927-80c28975ae2b.png)

My enabled/disabled video:

```
const enableVideo = async () => {
    if (videoTrackRef.current && videoTrackRef.current.name) return;
    let createVideoTrack = await createLocalVideoTrack(getWidthHeight());
    createVideoTrack.enable();
    if (room.name) {
      console.log("enabled: " + createVideoTrack.name);
      await room.localParticipant.publishTrack(createVideoTrack, {
        priority: "low",
      });
    }

    setVideoTrack(createVideoTrack);
  };


  const disableVideo = useCallback(async () => {
    let createdVideo = videoTrackRef.current;
    if (createdVideo && room) {
      const localTrackPublication =
        room.localParticipant?.unpublishTrack(createdVideo);
      room.localParticipant?.emit("trackUnpublished", localTrackPublication);
      createdVideo.stop();
      setVideoTrack(undefined);
    }
  }, [videoTrack, videoTrackRef]);
```

**Comment by makarandp0** [comment]
Hello @nicolasdezena, Thank you for reporting this issue. 

Can you provide some more details on the repro steps, browser/os versions. Please include room-sid and client side log where this issue was encountered.

Thanks,
Makarand

**Comment by starloveit** [comment]
I am getting same issue on iOS15. @makarandp0 

so I cant see participants screen on iOS15. but it is working well on the older iOS versions.

**Comment by makarandp0** [comment]
Hey @starloveit, Please provide more details on your repro. repro steps, browser/os versions, room-sid and client side log where this issue was encountered would be very useful.

**Comment by vbabenko** [comment]
@makarandp0 I've the same problem under the latest Safari version (v15). Works fine under v14.
Happens when you try to publish media.

![Publish media error](https://user-images.githubusercontent.com/4083910/134896228-41fbb429-64b6-48fd-8eb8-079338dd49ab.jpg)

**Comment by starloveit** [comment]
@makarandp0 I am getting same issue

**Comment by makarandp0** [comment]
@starloveit @vbabenko - Are you using adapter.js as one of your dependency? The error "Attempted to assign readonly property" with setRemoteDescription caused by  a bug in older versions of adapter.js. [adapter-7.7.1.js](https://webrtc.github.io/adapter/adapter-7.7.1.js) has has [the fix](https://github.com/webrtcHacks/adapter/commit/de0348c756b7bda11a700bf7ea9e9393cab16421). This shows up in Safari 15 as it has started treading RTCSessionDescription.sdp property as readonly again.

**Comment by vbabenko** [comment]
@makarandp0 thank you for your quick response. I did not install the adapter explicitly. But I use `peerjs` that has `adapter.js` as its dependency.
Let me update the package to the latest version

**Comment by starloveit** [comment]
Thanks @makarandp0 It is working after using adapter-8.0.0

**Comment by vbabenko** [comment]
Hey @makarandp0,
Thank you for your help! Upgrade of `peerjs` to the latest version solved the problem as well.
