### ISSUE TITLE
createLocalTracks fails in Chrome

### ISSUE THREAD

**Issue by koistya** [twilio/twilio-video.js#1589]
Calling `createLocalTracks()`, `createLocalAudioTrack()`, or `createLocalVideoTrack()` fails with the following error:

```
TypeError: track must be a LocalAudioTrack, LocalVideoTrack, LocalDataTrack, or MediaStreamTrack
```

![image](https://user-images.githubusercontent.com/197134/135316944-669e90c5-3660-4e64-9c43-e32393a75c12.png)

Note that in Chrome `window.MediaStreamTrack` is `undefined`  and `track instance of options.MediaStreamTrack` compares native instance of `MediaStreamTrack` (returned by `getUserMedia()`) with a mock from `@twilio/webrtc`.

 - [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Software versions:**

 - Browser(s): Chrome v94
 - Operating System: macOS v11.6, darwin-arm64 (Apple M1 Silicon chip)
 - twilio-video.js: 2.17.1

**Comment by makarandp0** [comment]
@koistya, I am closing this old issue. Please reopen if you are still seeing the issue.
