### ISSUE TITLE
Unintentionally paused on Twilio on Remote unmute Audio

### ISSUE THREAD

**Issue by Bikash-lama** [twilio/twilio-video.js#1592]
Hello!

I am not sure if there is no issue in this repo about it but anyways pls let me describe :)

Actually, the current system is there is two party connected to a room once call started as default both audio/video off for both party, however on safari browser on this rare condition, whenever one side unmute audio, the other side with safari browser cannot hear the audio at all. 

Heres the brief log for it.
```
[Warning] 2021-10-05 – "01:36:42.163Z" – "|" – "WARN" – "in" – "[RemoteAudioTrack #1: MT40da9cfc2d244c2cd282df4ec792ede4]:" – "Unintentionally paused:" –  (twilio-video.min.js, line 52)
<audio autoplay trackid="MT40da9cfc2d244c2cd282df4ec792ede4" participant="PA37d0adde1cf9567c0a4523926e45f31f"></audio>

<audio autoplay trackid="MT40da9cfc2d244c2cd282df4ec792ede4" participant="PA37d0adde1cf9567c0a4523926e45f31f"></audio>
[Warning] 2021-10-05 – "01:36:43.165Z" – "|" – "WARN" – "in" – "[RemoteAudioTrack #1: MT40da9cfc2d244c2cd282df4ec792ede4]:" – "Error while playing unintentionally paused <audio> element:" (2) (twilio-video.min.js, line 52)
NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.
<audio autoplay trackid="MT40da9cfc2d244c2cd282df4ec792ede4" participant="PA37d0adde1cf9567c0a4523926e45f31f"></audio>
[Warning] 2021-10-05 – "01:36:43.211Z" – "|" – "WARN" – "in" – "[RemoteAudioTrack #1: MT40da9cfc2d244c2cd282df4ec792ede4]:" – "Unintentionally paused:" –  (twilio-video.min.js, line 52)
<audio autoplay trackid="MT40da9cfc2d244c2cd282df4ec792ede4" participant="PA37d0adde1cf9567c0a4523926e45f31f"></audio>
```

<audio autoplay trackid="MT40da9cfc2d244c2cd282df4ec792ede4" participant="PA37d0adde1cf9567c0a4523926e45f31f"></audio>

Note: There is no issue if we start a call by default audio/video on, since its the feature of our system to disable all media during call, it will helpful if any solution is there.

Twilio version: 2.7.3
Safari:  14.1.2

**Comment by makarandp0** [comment]
Hello @Bikash-lama,  Is the participant on Safari sharing his audio when you see this error ? It looks like browsers auto play policy is preventing the element from being played. Please check out [this common issue](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md#all-browsers) which talks about auto play policy

Thanks,
Makarand

**Comment by Bikash-lama** [comment]
Thank you for the comment @makarandp0 .

I was able to solve it by following the provided link.
