### ISSUE TITLE
Twilio-video fails to connect when page is inside an iframe

### ISSUE THREAD

**Issue by chrismatthieu** [twilio/twilio-video.js#1594]
Running the latest version 2.17.1 (and previous versions), Twilio-video works fine when page is accessed directly but fails to connect when page is running inside of an iframe with allow="camera 'src';microphone 'src'" permissions. It prompts for mic and camera access as it should but returns the following errors in the console log on connect.

Here's the error stack:

[Warning] 2021-10-05T18:18:13.888Z – "warn" – "[PeerConnectionV2 #1: d7898ce6-916c-44a7-aa72-342900897e99]" (twilio-video.min.js, line 51)
"Calling setRemoteDescription with an RTCSessionDescription of type \"answer\" failed with the error \"Failed to set remote answer sdp: The order of m-lines in answer doesn't match order in offer. Rejecting answer.\"."

-- 

2021-10-05T18:18:13.888Z – "warn" – "[PeerConnectionV2 #1: d7898ce6-916c-44a7-aa72-342900897e99]"
"The SDP was v=0
o=- 3842446693 3842446693 IN IP4 0.0.0.0
s=VM3d462760e27a3c7128e9fac8e3f5fdfa
t=0 0
a=ice-lite
a=msid-semantic: WMS *
a=group:BUNDLE video audio
m=video 10856 UDP/TLS/RTP/SAVPF 98 104 106 108
c=IN IP4 3.235.111.248
a=rtcp-rsize
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=rtcp:10856 IN IP4 3.235.111.248
a=rtpmap:98 H264/90000
a=rtpmap:104 VP8/90000
a=rtpmap:106 red/90000
a=rtpmap:108 ulpfec/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=rtcp-fb:104 goog-remb
a=rtcp-fb:104 ccm fir
a=rtcp-fb:104 nack
a=rtcp-fb:104 nack pli
a=fmtp:98 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=candidate:2 1 UDP 2013266430 3.235.111.248 10856 typ host
a=candidate:2 2 UDP 2013266429 3.235.111.248 11726 typ host
a=rtcp-mux
a=setup:active
a=mid:video
a=recvonly
a=ice-ufrag:/pg8
a=ice-pwd:pG/m5tptgF4t+UqswKyg/e
a=fingerprint:sha-256 44:F8:4C:E1:6C:AD:EA:AB:11:5D:DB:A6:7D:2B:EC:18:F1:DE:42:9B:BF:E9:B1:90:BA:D8:B7:67:C0:A9:8A:F3
m=audio 10856 UDP/TLS/RTP/SAVPF 111 0
c=IN IP4 3.235.111.248
a=extmap:14 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=rtcp:10856 IN IP4 3.235.111.248
a=rtpmap:111 opus/48000/2
a=rtpmap:0 PCMU/8000
a=fmtp:111 minptime=10;useinbandfec=1;usedtx=1
a=candidate:2 1 UDP 2013266430 3.235.111.248 10856 typ host
a=candidate:2 2 UDP 2013266429 3.235.111.248 11726 typ host
a=rtcp-mux
a=setup:active
a=mid:audio
a=recvonly
a=ice-ufrag:/pg8
a=ice-pwd:pG/m5tptgF4t+UqswKyg/e
a=fingerprint:sha-256 44:F8:4C:E1:6C:AD:EA:AB:11:5D:DB:A6:7D:2B:EC:18:F1:DE:42:9B:BF:E9:B1:90:BA:D8:B7:67:C0:A9:8A:F3
"

--

2021-10-05T18:18:13.889Z – "warn" – "[connect #1]" – "event"
Object

elapsedTime: 1228

group: "media"

level: "warning"

name: "error"

payload: {message: "Calling setRemoteDescription with an RTCSessionDescription of type \"answer\" failed", code: 53402, context: "{\"error\":\"Failed to set remote answer sdp: The ord…E:42:9B:BF:E9:B1:90:BA:D8:B7:67:C0:A9:8A:F3\\r\\n\"}"}

timestamp: 1633457893889

--

Unhandled Promise Rejection: TwilioError: Client is unable to apply a remote media description

TwilioError: Client is unable to apply a remote media description

-- RoomName and SID

23:18:52 UTC 2021-10-04 | TubeMakingCover | RM4d3324c0e3f75c4e6174caba855683b2 | Group | 15 min 25 sec
-- | -- | -- | --

**Comment by chrismatthieu** [comment]
Apologies, that appears to be the wrong SID. I can't find these failed calls in the video log portal...

**Comment by makarandp0** [comment]
Hello @chrismatthieu, I am closing this old issue. Please reopen another one if you still seeing issues with iFrame.
