### ISSUE TITLE
Unable to change participants audioOutput during stream

### ISSUE THREAD

**Issue by jdbbaugh** [twilio/twilio-video.js#1597]
Currently our app is hitting an issue where a user is unable to swap their audioOutput source in an active room. If for example they are currently hearing audio via their headphones and they then select from the provided settings tools to change that audio source from headphones to MacBook Speakers nothing will occur. The function in place to make that speaker transition is:

```
updateSpeaker(deviceId) {
     const audioElements = document.getElementsByTagName('audio')
     for (const audio of audioElements) {
       audio
         .setSinkId(deviceId)
         .then(() => {})
         .catch((e) => {
           Sentry.captureException('failed to updateSpeaker', {
             extra: {
               error: e,
               deviceId,
             },
           })
         })
     }
     this.speakerId = deviceId
     Sentry.setContext('speaker', {
       speaker: deviceId,
     })
     window.localStorage.setItem('speaker', this.speakerId)
   }
```

In addition to this base method we have tried creating a localAudioTrack. We have tried updating the speaker when updating the microphone, we have tried subscribing to the track, We have tried listening in the room for a trackAdded. We have tried attaching the audio element using the following link:

https://www.twilio.com/docs/video/configuring-audio-video-input-and-output-devices#selecting-a-specific-audio-output

as well as:
https://www.twilio.com/docs/video/javascript-v1-configuring-audio-video-inputs-and-outputs#selecting-a-specific-audio-output

and explored a few similar issue tickets such as:
https://github.com/twilio/twilio-video.js/issues/161

**Software versions:**

 -  Browser(s): Chrome 93.0.4577.82
 -  Operating System: Big Sur 11.6
 -  twilio-video.js: 2.15.0
 - Third-party libraries (e.g., Angular, React, etc.): Vue

**Comment by makarandp0** [comment]
Hello @jdbbaugh, We haven't heard from you. I am assuming that your issue is fixed now. Please reopen new issue if you are still seeing this issue.
