### ISSUE TITLE
Tracks in P2P rooms are not subscribed to when using iOS SDK v 4.6

### ISSUE THREAD

**Issue by will-ks** [twilio/twilio-video.js#1598]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ ] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

This seems similar to this issue: https://github.com/twilio/twilio-video.js/issues/1595 
Our specifics are different, but feel free to merge if you think these have the same cause.

We have calls initiated with the iOS SDK, answered with the JS SDK. 
Everything has been working fine until we updated the iOS SDK to version 4.6 (the version using unified plan).
I have confirmed that reverting the iOS SDK to version 4.5 fixes the issue.
It also appears that the issue is limited to P2P rooms. I can reproduce the issue maybe 50% of the time in P2P rooms but not at all in group rooms.

The issue we are seeing is that the caller (iOS)'s video, audio and/or data tracks do not get subscribed to. They are published fine, and the responder gets the `trackPublished` event triggered when they are, but the `trackSubscribed` event never triggers. I thought it might be the `automaticSubscription` option failing, but according to the docs this has no effect in P2P rooms, and I can't seem to find a way to manually subscribe to tracks anyway. 

The issue is intermittent, and refreshing the browser to reconnect to the call fixes it when it occurs.

Example room sid: `RM6fb0c51cdd405aedda6d256a74bdddaa`

**Expected behavior:**

Tracks should automatically subscribe.

**Actual behavior:**

Tracks are not subscribed to.

TODO

**Software versions:**

 - [x] Browser(s): Chrome / Edge
 - [x] Operating System: Mac / Win 10
 - [x] twilio-video.js: 2.15.3. Also confirmed on 2.17.1.
 - [x] Third-party libraries (e.g., Angular, React, etc.): React 17.0.2

**Comment by makarandp0** [comment]
Hello @dambusm, Thank you fore reporting. This looks like an interop issue https://github.com/twilio/twilio-video.js/issues/1504 that @ceaglest is looking at.

**Comment by ceaglest** [comment]
Yes, I looked at `RM6fb0c51cdd405aedda6d256a74bdddaa` and I see the same pattern of the iOS SDK generating a second offer that it cannot apply locally. It's pretty likely that it is the same issue being discussed in recent comments of #1504.
