### ISSUE TITLE
onaddstream is deprecated! Use peerConnection.ontrack instead.

### ISSUE THREAD

**Issue by GarPit** [twilio/twilio-video.js#16]
onaddstream is deprecated! Use peerConnection.ontrack instead.

I have this issue in Firefox and sometimes local video preview not showing up.

```
Twilio.Conversations.LocalMedia.getLocalMedia().then((cameraTrack)=>{
    // attach to a <video> element
    cameraTrack.attach('.chat .left-part .video .preview-video');
  }, (error)=>{
    console.error('Unable to get access to the local camera.' + error.message);
    this.set('cameraDisabled', true);
  }
);
```

**Comment by GarPit** [comment]
`then` callback not called, but if I add breakpoint at 1st line and 3rd (with cameraTrack.attach), then I can see preview

**Comment by markandrus** [comment]
@GarPit thanks for the report! We'll work on updating this. The Firefox behavior is strange...

**Comment by markandrus** [comment]
@GarPit we started doing feature detection for `ontrack` versus `onaddstream` in recent twilio-video.js releases. This warning should no longer print.
