### ISSUE TITLE
RTCSessionDescription's members are readonly! Writing to them is deprecated and will break soon

### ISSUE THREAD

**Issue by markandrus** [twilio/twilio-video.js#160]
We see this warning. Although we need to update [twilio-webrtc.js](https://github.com/twilio/twilio-webrtc.js), we already have other Firefox deprecation warnings tracked here.

> RTCSessionDescription's members are readonly! Writing to them is deprecated and will break soon

**Comment by markandrus** [comment]
This was fixed by @manjeshbhargav in twilio-webrtc.js 1.0.1.

**Comment by bennyn** [comment]
@markandrus Do you have a link to the commit that fixed this issue?

**Comment by markandrus** [comment]
@bennyn it should've been fixed here: https://github.com/twilio/twilio-webrtc.js/pull/10/files
