### ISSUE TITLE
Chrome 93 and above on Android 11 sets incorrect frame height for resolutions below 720p

### ISSUE THREAD

**Issue by michal-blinderhq** [twilio/twilio-video.js#1603]
- [X] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [X] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ ] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [X] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

We've noticed issues with frame height in Chrome on Android 11 since Chrome 93. We're using the VP8 codec. It appears that the codec encodes a few pixels less, equally from the top and the bottom of the frame. This is later noticeable in the MKV recordings as a tiny black fill at the top and at the bottom of the frame.

- Local tracks seem to be attached with the correct dimensions
- Once the tracks are published to the room, the height of the frame isn't in a perfect 16:9 ratio with the width
- The width of the frame is set correctly
- The height is set to a slightly smaller size than a perfect 16:9 ratio according to the width (our tests have shown this to be 2.2% less than the expected height)
- This is only happening in landscape mode. Portrait mode is fine.
- This is only happening on resolutions below 720p. Once 720p is reached, the frame height is correct - 720px.
- This behaviour has been confirmed in Chrome 93 and 94 on three different devices: Google Pixel 3, Samsung Galaxy S21+ 5G, Xiaomi Mi 9
- We've tried to set the width only and then specify the aspect ratio constraint but the result was exactly the same
- An example of the incorrect frame size is 640x352 (instead of 640x360) and 960x528 (instead of 960x540)

**Software versions:**

 - [x] Browser(s): Chrome 93.0.4577.82, Chrome 94.0.4606.61
 - [x] Operating System: Android 11
 - [x] twilio-video.js: 2.14.0, 2.17.1
 - [x] Third-party libraries (e.g., Angular, React, etc.): Angular 11.2

**Comment by makarandp0** [comment]
I have filed a chrome bug to track this: https://bugs.chromium.org/p/chromium/issues/detail?id=1260419

**Comment by michal-blinderhq** [comment]
We tried setting the resolution programmatically when creating the local tracks, e.g.:
```
createLocalVideoTrack({
    width: 640,
    height: 360
});
```

We've also tried to manipulate the track resolution on the fly once it has been published to the room by manipulating the underlying mediaStreamTrack's constraints `localVideoTrackPublication._signaling._trackTransceiver.track.applyConstraints({ width: 640, height: 360 })` but this produced exactly the same issues.

Now, there is a much bigger issue with HW encoding after upgrading my Pixel 3 to Android 12 and Chrome 95. Encoding for most of the resolutions is completely broken (e.g. 540p) and the ones that work have a "sepia" tint to the image and the colours are all wrong.

There is already a [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1237677) raised against chromium so hope this gets fixed ASAP by them as it makes any Android device running Chrome and supporting HW acceleration fundamentally unusable for WebRTC.

**Comment by makarandp0** [comment]
Hello @michal-blinderhq, Thank you for the update. Indeed there is [bigger issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1264894) with chrome on Android 12 - I have verified that disabling hardware encoding works around that issue.

About updating the track resolution - I think it's better to use the [LocalVideoTrack.restart](https://media.twiliocdn.com/sdk/js/video/releases/2.18.0/docs/LocalVideoTrack.html#restart__anchor) api and specify new constraints than calling `localVideoTrackPublication._signaling._trackTransceiver.track.applyConstraints`.

**Comment by michal-blinderhq** [comment]
Hi @makarandp0,

Thanks for following up and for the tips re. updating the track resolution.

I'm going to close this issue as it seems like there is nothing that can be done programmatically to work around the initial problem...

Regarding the latter issue, it actually appears that this is currently only present on Pixel phones. We've tested in Chrome 95 on Samsung S8 (Android 9) and Chrome 95 on Samsung S21 5G (Android 11) and it wasn't reproducible.

Anyway, hope Chrome will do something about both of these problems.

Cheers

Michal
