### ISSUE TITLE
setSinkId support for changing audio output device

### ISSUE THREAD

**Issue by vinnymac** [twilio/twilio-video.js#161]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.

**Code to reproduce the issue:**

```html
<div id="content" />
```

```js
import { connect } from 'twilio-video';
const content = document.getElementById('content');
let audioOutputDevice;

navigator.mediaDevices.enumerateDevices().then(devices => {
  audioOutputDevice = devices.find(device => device.kind === 'audiooutput' && device.label === 'HDMI');
  return connect('$TOKEN', { name: 'my-room-name' });
}).then(room => {
  room.on('trackAdded', (track, participant) => {
    if (track.kind === 'audio') {
      const audioElement = track.attach();
      audioElement.setSinkId(audioOutputDevice.deviceId).then(() => {
        content.appendChild(audioElement);
      });
    }
  });
});
```

**Expected behavior:**

When changing the sinkId I expect the audio output to come from the device that has been set using `setSinkId`.

**Actual behavior:**

When I set the audio elements sinkId its promise resolves successfully, and its sinkId changes. Yet the audio still comes from the default device. If I instead attempt to set the sinkId of the video element like I see in examples online [here](https://webrtc.github.io/samples/src/content/devices/input-output/), I receive the following error.

`DOMException: The requested operation cannot be performed and was aborted`

I followed the documentation [here](https://www.twilio.com/docs/api/video/configuring-audio-video-inputs-and-outputs) and [here](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/setSinkId) and [here](https://github.com/twilio/video-quickstart-js/blob/master/examples/mediadevices/src/helpers.js#L31-L38).

The same [example](https://webrtc.github.io/samples/src/content/devices/input-output/) I mentioned above, does in fact change my audio output device, but I assume it works differently than `twilio-video` does.

Below are the 3 audio DeviceInfo labels that I can see after calling `enumerateDevices`. My goal is to get the audio to come from HDMI, just like the example above does.
* Default
* Built-In Output
* HDMI

Things I have tried/confirmed:
* setSinkId to audio element using all 3 deviceIds
* setSinkId to video element using all 3 deviceIds (fails)
* Confirm my mic is not muted just in [case](https://bugs.chromium.org/p/chromium/issues/detail?id=506124).
* Confirm both MediaStreamTracks for audio and video elements are enabled and not muted
* Confirm the sinkId is actually being changed when the audio element successfully sets the sink id.
* Manually calling `setSinkId` using the Chrome DevTools.
* Made sure at least 2 participants are connected so I can test audio output properly.
* Participant making the noise was tested using both `twilio-video` and the Android SDK, and in both cases audio came from the default device.

**Software versions:**

 - [x] Browser(s): Chrome 61.0.3163.79 (Official Build) (64-bit)
 - [x] Operating System: macOS Sierra 10.12.6
 - [x] twilio-video.js: 1.2.2
 - [ ] Third-party libraries (e.g., Angular, React, etc.):

**Comment by vinnymac** [comment]
This was PEBKAC. The code sample does work properly. Make sure you are setting the sink ID on all foreign participants, and never the localParticipant. I think it would be convenient if we could do this from the `AudioTrack` class or the `Participant` class level, but that is not an issue, more of a request.

**Comment by markandrus** [comment]
Hi @vinnymac,

> I think it would be convenient if we could do this from the AudioTrack class or the Participant class level, but that is not an issue, more of a request.

Would you mind expanding on this a bit? What kind of an API would you like to see? We could perhaps add a `sinkId` option to `attach`, but then I think we'd want to make it an async API... are there any other ways you'd like to see this work?

Thanks,
Mark

**Comment by vinnymac** [comment]
Hey @markandrus,

I can expand a little. I understand that some users may want to be able to have participants using various different audio output devices, but my use case is that I want all non-local participants to use 1 audio output device. To be certain that all of my participants, at the current time or in the future are going to use the same output device I had to do something like this:

```js
export function applyAudioOutputDeviceSelection(room, deviceId) {
  // Array of promises for whether setSinkId was successful
  const sinkIdPromises = []

  // helper for setting our sink id
  const setSinkIdHandler = (track) => {
    // ignore all non-audio tracks
    if (track.kind !== 'audio') return
    const audioElement = track.attach()

    return audioElement.setSinkId(deviceId)
      .then(() => {
        console.log('Set Sink ID for', track.id, 'with sink id', deviceId)
      })
      .catch((error) => {
        console.error('Failed to set Sink ID for', track.id, 'with sink id', deviceId, error)
      })
  }

  // we are changing the device ID so lets stop managing device ids
  room.removeListener('trackAdded', setSinkIdHandler)

  // start managing the new audio device id when tracks are added
  room.on('trackAdded', setSinkIdHandler)

  // setSinkId on all current participants
  room.participants.forEach((participant) => {
    participant.audioTracks.forEach((audioTrack) => {
      sinkIdPromises.push(setSinkIdHandler(audioTrack))
    })
  })

  // evaluate if all of these resolve, or any reject
  return Promise.all(sinkIdPromises)
}
```

This lets me be certain that all the participants are going to use the same deviceId. Whenever a device changes, participants are added, or participants already exist, I can be certain that all my audio tracks are using the same deviceId. It would be convenient to me if this was built in. Where `twilio-video` managed this use case for me. But I understand why you first and foremost provide a flexible API that we can build upon, and not a helper that can fit a very specific use case like this.

**Comment by PavloShchur** [comment]
@vinnymac I am using the following fucntion and it does not work for me.
         function applyAudioOutputDeviceSelection(device, track) {
             const audioElement = track.attach();
             return typeof audioElement.setSinkId === 'function' ? audioElement.setSinkId(device.deviceId)
                 .then(() => {
                     console.log('Set Sink ID for', track.id, 'with sink id', device.deviceId)
                 })
                 .catch((error) => {
                     console.error('Failed to set Sink ID for', track.id, 'with sink id', device.deviceId, error)
                 })
             : Promise.reject('This browser does not support setting an audio output device');
         }

**Comment by PavloShchur** [comment]
Are there any way to change output audio just for local participant?

**Comment by smoothgrips** [comment]
I would also like to find a way to change output audio just for local participant. @PavloShchur , did you ever figure out a way to do this?
