### ISSUE TITLE
Dominant Speaker - Local Participant

### ISSUE THREAD

**Issue by kylegosen** [twilio/twilio-video.js#1614]
I know this was brought up a couple of years ago (in [this](https://github.com/twilio/twilio-video.js/issues/604) issue) but I would like to bring it up again. I would like to know if the local participant is the dominant speaker but we only get a `dominantSpeakerChanged` event for remote participants.

The work around I have in place is really hacky. I created a data track between participants and when a participant receives a `dominantSpeakerChanged` event, they forward a message to everyone else with the SID. If the local participant SID matches, you update the dominant speaker to yourself, if not you drop the message on the floor.

It seems like a common "issue"/feature request, I'm wondering if this could be implemented in the SDK.

**Comment by charliesantos** [comment]
Hi @kylegosen , thank you for submitting. Currently, this is not supported in the SDK. Your implementation is our current recommendation to achieve this.

**Comment by charliesantos** [comment]
Closing this now. Please feel free to follow up on this space.

**Comment by cmavelis** [comment]
I haven't looked very hard, but it seems to me that the signaling from the server doesn't support this, is that correct?  Knowing if the `localParticipant` is the `dominantSpeaker` would be pretty useful for my case as well

**Comment by charliesantos** [comment]
@cmavelis that is correct. The server doesn't currently support this.
