### ISSUE TITLE
'trackSubscribed' not fired for RemoteParticipants on Safari 15.1

### ISSUE THREAD

**Issue by ankraj077** [twilio/twilio-video.js#1628]
**React.js Web app**
## `"twilio-video": "^2.18.1"`

---

## `trackSubscribed` not getting fired on Safari Browser

---

## Works on `Chrome` and `Edge`

---

## Safari: `Version 15.1 (17612.2.9.1.20)`

![image](https://user-images.githubusercontent.com/20252226/140598890-08056356-8f53-41d3-9fe7-d726f31bd215.png)

---

```js
      console.log("NEW REMOTE PARTICIPANT", participant);

      const trackSubscribed = (track) => {
        console.log("SUBSCRIBED - WORKS");

        // Video
        if (track.kind === "video") {
          setVideoTracks((videoTracks) => [...videoTracks, track]); // For initial video track
          handleVideoTrack(); // Handle future video track
        }
        // Audio
        else if (track.kind === "audio") {
          setAudioTracks((audioTracks) => [...audioTracks, track]); // For initial audio track
          handleAudioTrack(); // Handle future audio track
        }
      };

      const trackUnsubscribed = (track) => {
        console.log("UN SUBSCRIBED");

        if (track.kind === "video") {
          setVideoTracks((videoTracks) => videoTracks.filter((v) => v !== track));
        } else if (track.kind === "audio") {
          setAudioTracks((audioTracks) => audioTracks.filter((a) => a !== track));
        }
      };

      participant.on("trackSubscribed", trackSubscribed);
      participant.on("trackUnsubscribed", trackUnsubscribed);
```
---

## Chrome: Works fine

![image](https://user-images.githubusercontent.com/20252226/140599071-4ec20cf3-4aae-4c49-92e2-13a4bac93a73.png)

---

## **Safari: Does not work**

![image](https://user-images.githubusercontent.com/20252226/140599084-b9a14d34-287f-4726-b8e4-e0aa2fd2f48f.png)

**Comment by makarandp0** [comment]
Hello @ankraj077, Thank you writing about this. 

`trackSubscribed` is fired when a new track is subscribed. It does not fire for any tracks that were already subscribed. I suspect in your case by the time you are hooking up to `trackSubscribed` the track was already subscribed.

our quickstart demonstrates the handling required for existing tracks: 
https://github.com/twilio/video-quickstart-js/blob/master/quickstart/src/joinroom.js#L203

Let me know if you still seeing issues after this.
Thanks,
Makarand

**Comment by ankraj077** [comment]
Hi @makarandp0,

Thanks for your response. `trackSubscribed` is not fired for any new remote participants in Safari. It is not even fired if I join to a room which already has remote participant.

**Comment by makarandp0** [comment]
Hello @ankraj077, Did you try updating the code so that you generate `trackSubscribed` for already subscribed tracks ? By the time a  `participantConnected` is emitted it's possible that tracks were already subscribed and thus you will not see trackSubscribed event fired for those tracks.

See if this change like this fixes your issue:
```
  participant.on("trackSubscribed", trackSubscribed);  
  participant.tracks.forEach(publication => {
    if (publication.isSubscribed) {
      trackSubscribed(publication.track);
    }
  });

```
If above solution does not work, we need to debug further, Please try our quickstart sample and see if you can reproduce the issue with it.  Please share client side console logs and room sid  if the problem persists.

Thanks,
Makarand

**Comment by ankraj077** [comment]
Thank you @makarandp0, this solved my issue.
