### ISSUE TITLE
[iOS 15.1] VideoTracks goes black and the page freezes on certain interruptions

### ISSUE THREAD

**Issue by charliesantos** [twilio/twilio-video.js#1632]
Certain interruptions such as incoming calls, backgrounding the browser or switching between apps causes VideoTracks on Chrome and Safari on iOS 15.1 to go black. Sometimes, the whole page also freezes and become unresponsive causing audio and video to cut off. These issues are regressions on iOS 15.1. See the following bugs for more details.

   * [Page freezing](https://bugs.webkit.org/show_bug.cgi?id=230922#c12)
   * [VideoTrack going black](https://bugs.webkit.org/show_bug.cgi?id=232599)

   A workaround can be implemented to prevent the VideoTrack from going black. This workaround however doesn't prevent the issue where sometimes the page freezes. It is recommended to apply this workaround on Chrome and Safari on iOS 15.1.

  ```js
  // Keeps track of video elements and their event listeners
  const videoElements = {};

  // Listen to onPlay and onPause events and intelligently re-attach the video element
  function shimVideoElement(track, el) {
    let wasInterrupted = false;

    const onPause = () => {
      wasInterrupted = true;
    };

    const onPlay = () => {
      if (wasInterrupted) {
        track.detach(el);
        track.attach(el);
        wasInterrupted = false;
      }
    };

    el.addEventListener('pause', onPause);
    el.addEventListener('play', onPlay);

    // Track this element so we can remove the listeners
    videoElements[el] = { onPause, onPlay };
  }
  ```

  Apply the workaround after attaching the video element.

  ```js
  videoTrack.attach(videoElement);
  shimVideoElement(videoTrack, videoElement);
  ```

  Remove the listeners before detaching the video element.

  ```js
  const { onPause, onPlay } = videoElements[videoElement];
  videoElement.removeEventListener('pause', onPause);
  videoElement.removeEventListener('play', onPlay);
  ```

**Comment by charliesantos** [comment]
This appears to be resolved in iOS 15.2 beta. I will keep this issue open until we verify on iOS 15.2 stable release.

**Comment by sundardsTechMind** [comment]
The same issue for me also for I have tested chrome, firefox, brave, safari browsers ( Twilio Video Freeze & Black Screen ) I'm able to see Error Code: 11200 On Twilio Console (Call back requests failed ) Previously I have used this version of Twilio ( "Twilio": "^3.37.1",) but tried updating latest Twilio SDK no luck same issue. Android 11,12 & IOS 14

**Comment by charliesantos** [comment]
We verified this is fixed on iOS 15.2.

**Comment by shaibt** [comment]
@charliesantos ,

What we see on iOS 15.1 multiple devices:
- Safari iOS 15.1 client is connected to room (P2P). other participant in room is desktop chrome.
- When iOS user backgrounds Safari or moves to another tab, remote audio is stopped. When coming back to the room tab , the tab containing the original page UI is refreshed/reloaded (we assume because browser decided to refresh) but other side of the room is seeing frozen video so iOS client did not disconnect cleanly.
- Same case w/ iOS 15.2, when moving to another tab or backgrounding Safari, remote audio is played and the iOS status bar is orange signifying media is in play. When returning to the room UI tab, video continues as usual.

Is this the same problem as described in this thread? If the browser page freezes, Safari will simply try to refresh it?

**Comment by charliesantos** [comment]
@shaibt that is correct. If the browser freezes, Safari will eventually refresh it.

**Comment by shaibt** [comment]
@charliesantos 
We are recreating this consistently in production with multiple iOS 15.1 devices (~40% of our room participants are on this device/OS combo).
As iOS 15.1 is still immensely popular,  anything you can recommend to lessen the impact?

**Comment by charliesantos** [comment]
Hi @shaibt , we have a suggested [workaround](https://github.com/twilio/twilio-video.js/issues/1632#issue-1047952740) for the black frames issue. However, we don't have any workaround for the freezing issue. The only option we have at the moment is for the user to update to 15.2.
