### ISSUE TITLE
Twilio Video JS working in iOS Chrome but not in in-app webviews (FB,Instagram, etc)

### ISSUE THREAD

**Issue by shaibt** [twilio/twilio-video.js#1635]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

```js
// N/A
```

**Expected behavior:**

As my understanding that since iOS 14.3, native web views support webRTC and `getUserMedia`. Also since Sep, `twilio-video` for JS officially supports Chrome browsers on iOS. 
However, attempting to start Twilio video sessions in an in-app webview (for example: FB,Twitter and Instagram apps on iOS open any url when clicked by user in an in-app webview), twilio `isSupported` returns `false`

**Actual behavior:**

 in-app webviews in iOS should also be supported by `twilio-video`.

**Software versions:**

 - [x] Browser(s): iOS inapp browsers using webviews.
 - [x] Operating System: iOS 14.8
 - [x] twilio-video.js: 2.18
 - [ ] Third-party libraries (e.g., Angular, React, etc.):

**Comment by PikaJoyce** [comment]
Hi @shaibt,

Thank you for opening this issue with us. The flag denotes whether or not we officially support a browser by including it in our QA testing matrix and providing support issues that are experienced on that browser. The SDK can be used on any WebRTC compatible browser, but if `isSupported` is returning false, Twilio does not provide support for issues you may face on that browser. Here is a [list of current supported browsers](https://www.twilio.com/docs/video/javascript#supported-browsers). 

I'll be closing this issue now as we don't have any current action items from this, but I'm more than happy to help answer any further questions on this thread if you have any.

Thank you again!
Joyce

**Comment by shaibt** [comment]
Hi @PikaJoyce,

I understand Twilio's official policy on this but I do think you should reconsider official support of iOS in-app webview browsers (e.g, Instagram, Facebook, etc).
These "browsers" are not really at users' choice, especially on iOS. A large part of web traffic is forcefully displayed by SM apps in in-app webviews and this makes any links to Twilio-based webrtc webapps unusable! 
I don't know for fact the exact usage rate but I'd wager more webpages are viewed on in-app browsers on iOS than on Chrome.

**Comment by PikaJoyce** [comment]
Hi @shaibt, 

Thanks for your response. I understand but unfortunately, it's currently not on our roadmap. However, a workaround is to alter the behavior for the SDK to return `true` for WKWebView within `isSupported`. The `isSupported` flag only denotes whether or not we officially support a browser by including it in our QA test matrix and providing support for issues experienced on the browser in question. Therefore, `isSupported` returning `false` just means that Twilio does not provide support you might see in that browser, but it doesn't mean you can't use the SDK in that browser.

Best,
Joyce

**Comment by shaibt** [comment]
@PikaJoyce 
Just to understand the suggested "unsupported" work around:
We set our app to ignore the `isSupported` flag completely and ran some tests on popular in-app browsers like Facebook & Instagram on iOS 15.1. 
The result (for P2P rooms, 1 participant in-app WKWebView, other participant OS-X Chrome ) was that connections were successfully made but no audio or video was received by the in-app browser. Chrome participants could see/hear in-app participant but not other way around.
Is there code internally in the SDK that also relies on the `isSupported` flag that could explain the difficulties we saw in these rooms?  Was your suggestion to change the implementation of `isSupported` so that internal SDK functionality also is unlocked for `WKWebView`? or did you mean that on our "app" level we should accept `WKWebView` (which is not working.

**Comment by PikaJoyce** [comment]
Hi @shaibt,

Could you please share some room sids in which your problems occurred? I just did a quick test and was able to join a room successfully with the Slack WKWebView but was unable to do the same with Instagram WKWebView along the same application. This seems to be something worth investigating. Could you please try out your app on WKWebView through other applications and let me know if you're having the same issues? However, the `isSupported` is simply a flag, changes are applied through the `@twilio-webrtc` layer but that should not affect your particular usage. For now, I'll reopen this ticket since it may be bigger than originally anticipated. 

Thanks,
Joyce

**Comment by shaibt** [comment]
Hi @PikaJoyce 
We attempted to run several tests with both Facebook & Instagram (did not try Slack).
The results were the same for both:
* in iOS 14.4, local media (in FB/IN in-app browser) is acquired, connecting to room is successful, **no media is being streamed tin either direction**. Example room sids: `RM793915183d3e90fe612e1a7090863ba5`, `RM416b9409617e0411940ce4fb967ea57b`
* in iOS 15.1 , local media is acquired but once connected to room, in-app browsers are **sending media but not receiving**. Example room SIDs: `RMeee224c4f7b528f6dc36fb0359df1d4f`, `RM6271c11f918def43f56c305c01bf3d2d`,`RM3c91dc016a071f00e7a26ed14b7a0815`

**Comment by RyanDurkin** [comment]
Is there an update for this @PikaJoyce ? Or any workarounds that people use to tell the person to open up the Twilio video in their supported web browser rather than the in-app browser?

**Comment by PikaJoyce** [comment]
Hi @RyanDurkin,

There has not been any major movements on this as there are other higher priority items but I'll move it up further along so hopefully we can get to looking into this issue sooner. With that being said, (depending on device) do advise folks to open up the preferred browser from the [supported browsers matrix](https://www.twilio.com/docs/video/javascript#supported-browsers). For iOS, it would be Chrome and Safari. For Android, it'd be Chrome and Firefox.

**Comment by RyanDurkin** [comment]
I understand your point about the supported browsers but this is causing some big issues for my customers as they get sent a reminder email for their video session and then if they click on that link in their email client, it opens the in app browser and the video session does not work.

I'm not expecting there to be a quick fix here but it would be interesting if anyone has any workarounds in detecting if the person is using an in-app browser so I can show a relevant message to the user to attend the video session in their native browser?

**Comment by shaibt** [comment]
You can always check and parse the user agent string to check for popular in-app browsers (Meta family, etc) but this isn't a great workaround IMHO - more likely users will drop off when things don't work for them.
I don't know what the exact ratio is but I'd assume a large chunk of internet browsing, on mobile in particular, is done from in-app browsers and Twilio should prioritize this issue. Many of our clients don't even use email for notifications like you described - facebook, instagram,  etc.

**Comment by RyanDurkin** [comment]
That's my temporary plan @shaibt. I had some basic browser detection code but it wasn't good enough for in-app browsers so I'm taking a look at UAParser.js now

**Comment by PikaJoyce** [comment]
Folks,

I've got some great news and the team has decided to move forward with prioritizing this work for this PI. We will begin investigations next week on how to improve the WKWebView experience for everybody. Thank you both for your patience and valuable input. We are all looking forward to working on this and delivering this feature! I will continue to update this thread as we progress with the development of supporting WKWebViews.

Best,
Joyce

**Comment by shaibt** [comment]
Great news Joyce!
Thanks for pushing this forward.
Will really improve UX for many of our customers. Looking forward.

**Comment by shaibt** [comment]
Hi @PikaJoyce ,
Wanted to ask - will the effort to support in-app webviews also be applied to Android derivatives? 
We're experiencing a flood of customer complaints due to users clicking on links asking to join rooms on Android email apps and/or Whatsapp apps who then start Webviews with `Samsung Browser` or `Chrome WebView` user-agents that are returning `isSupported === false`.

**Comment by PikaJoyce** [comment]
Hi @shaibt,

Apologies for the late response, I didn't see it! But to answer that question, for now it is not. This effort was directed towards supporting iOS WebViews. With that being said, the most latest 2.21.0 release now supports iOS 14.3 and onward. So I'll be closing this issue now. If there are any issues that arise, feel free to open another issue! 

Thanks again folks for being incredibly patient. 

Best,
Joyce
