### ISSUE TITLE
No Local Video feed and black (or no) video feed on remote browser if connected through iOS device

### ISSUE THREAD

**Issue by Zohair-Equitec** [twilio/twilio-video.js#1640]
-I was unable to solve my problem even with [this](https://github.com/twilio/twilio-video.js/issues/927#issuecomment-612076785) ticket

 - [ ] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [ ] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ ] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [ ] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

```js
<script>
    const joinMeeting = document.getElementById("join-meeting");
    const container = document.getElementById("video-div");
    const muteButton = document.getElementById("mute-button");
    const unmuteButton = document.getElementById("unmute-button");
    const stopButton = document.getElementById("stop-video-button");
    const startButton = document.getElementById("start-video-button");
    const $leave = $('#leave-room');

    async function startVideo() {
      debugger;
      const token = document.getElementById("token").value;
      await Twilio.Video.connect(token, { name: 'TEST' }).then(room => {
        console.log('Connected to Room "%s"', room.name);
        debugger;
        const { createLocalVideoTrack } = Twilio.Video;
        createLocalVideoTrack({
          audio: true,
          video: { width: 720, height: 1440, frameRate: 24 },
        }).then(track => {
          debugger;
          CreateStudentList("local", track);
        });

        room.participants.forEach(participantConnected);
        room.on('participantConnected', participantConnected);

        room.on('participantDisconnected', participantDisconnected);

        const muteAudio = document.getElementById('muteAudio');
        debugger;
        muteAudio.addEventListener("click", function () {
          debugger;
          MuteSelfAudio(room);
        });

        const unmuteAudio = document.getElementById('unmuteAudio');
        debugger;
        unmuteAudio.addEventListener("click", function () {
          debugger;
          $("#muteAudio").removeClass("hidden");
          $("#unmuteAudio").addClass("hidden");
          room.localParticipant.audioTracks.forEach(track => {
            track.track.enable();
          });
          $("li#local .micLink").removeClass("active");
        });

        const stopVideo = document.getElementById('stopVideo');
        debugger;
        stopVideo.addEventListener('click', function () {
          debugger;
          pauseVideo(room);
        });

        const startVideo = document.getElementById('startVideo');
        debugger;
        startVideo.addEventListener('click', function () {
          debugger;
          playVideo(room);
        });

        // Leave the Room when the "Leave Room" button is clicked.
        $leave.click(function onLeave() {
          debugger;
          $leave.off('click', onLeave);
          room.disconnect();
        });
      });
      $("#join-meeting").addClass("hidden");
    }

    function CreateStudentList(participant, track) {
      debugger;
      var username;
      if (participant != "local") {
        username = participant.identity
      } else {
        username = "You";
      }
      if ($("li#" + (participant == "local" ? participant : participant.identity)).length < 1) {
        var studDiv = '<li id=' + (participant == "local" ? participant : participant.identity) + ' class="active">\
                <div class="studListBox">\
                  <a href="#" class="micLink"></a>\
                    <div class="stuImgBox1">\
                        <img src="./Assets/img/blank.png">\
                                            </div>\
                        <div class="stuName stuName1">' + (participant == "local" ? "You" : username) + '</div>\
                    </div></li>'
        $("ul.studList").append(studDiv);
      }
      $("li#" + (participant == "local" ? participant : participant.identity) + " .stuImgBox1").append(track.attach());

      if (track.kind == "video" && track.isEnabled) {
        $("li#" + (participant == "local" ? participant : participant.identity) + " .stuImgBox1 img").css("display", "none");
        $("li#" + (participant == "local" ? participant : participant.identity) + "  .vidLink").removeClass("active");
        $("li#" + (participant == "local" ? participant : participant.identity) + " .stuImgBox1 video").removeClass("hidden");
      } else if (track.kind == "video" && !track.isEnabled) {
        $("li#" + (participant == "local" ? participant : participant.identity) + " .stuImgBox1 img").css("display", "block");
        $("li#" + (participant == "local" ? participant : participant.identity) + " .vidLink").addClass("active");
        $("li#" + (participant == "local" ? participant : participant.identity) + " .stuImgBox1 video").addClass("hidden");
      }

      if (track.kind == "audio" && track.isEnabled) {
        $("li#" + (participant == "local" ? participant : participant.identity) + " .micLink").removeClass("active");
      } else if (track.kind == "audio" && !track.isEnabled) {
        $("li#" + (participant == "local" ? participant : participant.identity) + " .micLink").addClass("active");
      }
      $("#muteAudio").removeClass("hidden");
      $("#stopVideo").removeClass("hidden");
      $("#starVideo").removeClass("hidden");
      $("#leave-room").removeClass("hidden");
    }

    function trackAdded(participant, track) {
      debugger;
      if (track != null && participant.tracks.size < 3) {
        debugger;
        attachTrackEnabledDisabledHandlers(track, participant);
        if (participant.identity != null) {
          CreateStudentList(participant, track);
        }
      }
    }

    function trackEnabled(track, participant) {
      debugger;
      if (track.kind == "video") {
        $("li#" + (participant == "local" ? participant : participant.identity) + " .stuImgBox1 img").css("display", "none");
        $("li#" + (participant == "local" ? participant : participant.identity) + "  .vidLink").removeClass("active");
        $("li#" + (participant == "local" ? participant : participant.identity) + " .stuImgBox1 video").removeClass("hidden");
      }

      if (track.kind == "audio") {
        $("li#" + (participant == "local" ? participant : participant.identity) + " .micLink").removeClass("active");
      }
    }

    function trackDisabled(track, participant) {
      debugger;
      if (track.kind == "video") {
        $("li#" + (participant == "local" ? participant : participant.identity) + " .stuImgBox1 img").css("display", "block");
        $("li#" + (participant == "local" ? participant : participant.identity) + " .vidLink").addClass("active");
        $("li#" + (participant == "local" ? participant : participant.identity) + " .stuImgBox1 video").addClass("hidden");
      }

      if (track.kind == "audio") {
        $("li#" + (participant == "local" ? participant : participant.identity) + " .micLink").addClass("active");
      }
    }

    function attachTrackEnabledDisabledHandlers(track, participant) {
      debugger;
      track.on('enabled', () => trackEnabled(track, participant));
      track.on('disabled', () => trackDisabled(track, participant));
    }

    function MuteSelfAudio(room) {
      debugger;
      $("#unmuteAudio").removeClass("hidden");
      $("#muteAudio").addClass("hidden");
      room.localParticipant.audioTracks.forEach(track => {
        track.track.disable();
      });
      $("li#local .micLink").addClass("active");
      conversation.server.roomActivity(identity, identity, "All", "SelfMute");
    }

    function pauseVideo(room) {
      debugger;
      $('li#local video').addClass("hidden");
      $('li#local img').css("display", "block");
      $("li#local .vidLink").addClass("active");
      $(".li-local video").addClass("hidden");
      $('.li-local img').css("display", "block");
      room.localParticipant.videoTracks.forEach(track => {
        track.track.disable();
      });
      $("#stopVideo").addClass("hidden");
      $("#startVideo").removeClass("hidden");
    }

    function playVideo(room) {
      debugger;
      room.localParticipant.videoTracks.forEach(track => {
        track.track.enable();
      });
      $('li#local img').css("display", "none");
      $('li#local video').removeClass("hidden");
      $("li#local .vidLink").removeClass("active");
      $('.li-local img').css("display", "none");
      $('.li-local video').removeClass("hidden");
      $("#startVideo").addClass("hidden");
      $("#stopVideo").removeClass("hidden");
    }

    function participantConnected(participant) {
      debugger;
      console.log('Participant "%s" connected', participant.identity);

      participant.on('trackSubscribed', track => trackAdded(participant, track));
      participant.on('trackEnable', track => trackEnabled(track, participant));
      participant.on('trackDisable', track => trackDisabled(track, participant));
    }
    function trackRemoved(track) {
      if (track.kind == "data") {
        track.detach().forEach(element => element.remove());
      }
    }
    function participantDisconnected(participant) {
      debugger;
      console.log('Participant "%s" disconnected', participant.identity);
      participant.tracks.forEach(trackRemoved);
      $("li#" + participant.identity).remove();
    }

    function trackSubscribed(div, track) {
      div.appendChild(track.attach());
    }

    function trackUnsubscribed(track) {
      track.detach().forEach(element => element.remove());
    }

    joinMeeting.addEventListener("click", startVideo);
  </script>
```

**Expected behavior: Well, it should connect two parties and show the video and audio feed on both sides.

**

**Actual behavior: When connecting via an iPhone (tested with the latest version of Safari and Chrome), there doesn't seem to be any local video feed, and, while I do get both an audio and video track on my remote device, the audio track is fine, while the video track reproduces as just a black video element.**

**I have even tried changing the resolution constraints but it's not working. Can anyone please help me out?

**Software versions:**

 - [ ] Browser(s): Chrome, Safari
 - [ ] Operating System: iOS
 - [ ] twilio-video.js: 2.18.1

**Comment by PikaJoyce** [comment]
Hi @Zohair-Equitec,

Thank you for submitting this issue with us. Could you please share the Room Sid for us for us to inspect the logs? Also, which version of iOS are you using? I was able to reproduce this issue on iOS 15.1. But I've since updated to 15.2 and I'm unable to reproduce this issue. Also, are you able to reproduce this issue on our [Quickstart](https://github.com/twilio/video-quickstart-js) as well?

Best, 
Joyce

**Comment by Zohair-Equitec** [comment]
Below are the room SIDs

RM2703653336f0f93091c917a2c2ad9231
RM65a77cc4f415b4e8f85e7600f6c58ffe
RM3f3194c9c8795929801b7e51c71417c8

**Comment by PikaJoyce** [comment]
Hi @Zohair-Equitec,

Thank you for providing some sids. The first one seemed to only contain one participant on Chrome. The second room contained two participants on chrome. Last, but not least, the final room contains both an iOS user as well as a Chrome user. Despite that, all of the room sides provided contained no successful subscriptions and there were ICE failures in all three rooms. In order to help us debug further could you please answer some questions:

Please confirm that your scenarios are working on the [quickstart](https://github.com/twilio/video-quickstart-js) as well? 

With that being said, please take a look at this [example](https://github.com/twilio/video-quickstart-js/tree/master/examples/localmediacontrols/src) in order to set up your local media.

Also, I noticed that none of your participants ever successfully subscribed to the given tracks in any of the rooms. Can you please check if it's your remote or the local video/audio track you're hearing and seeing? 

[Here](https://www.twilio.com/docs/video/javascript-v2-getting-started#working-with-remote-participants) is some additional documentation in handling remote participants.

Thank you,
Joyce

**Comment by sundardsTechMind** [comment]
The same issue also for I have tested chrome, firefox, brave, safari browser ( Twilio Video Free & Black Screen ) I'm able to see Error Code: 11200 On Twilio Console (Call back requests failed ) Previously i have used this version of Twilio ( "Twilio": "^3.37.1",) but tried updating latest Twilio SDK no luck same issue. Android 11,12 & IOS 14.
![Twilio-video-black-screen -issue](https://user-images.githubusercontent.com/37631010/142450408-c3b72ded-4abd-4432-bf7b-09aef83a3716.png)
8
![black screen](https://user-images.githubusercontent.com/37631010/142450458-4dc4f15d-fb71-463d-a09f-39c0f4896989.jpg)
.

Help needed.
Thank you
Sundar

**Comment by PikaJoyce** [comment]
Hi @sundardsTechMind,

Thank you for the information. However, I do believe that your issue may be different than OPs issue. I have checked your room sid and it doesn't have any obvious errors. This may be a [certificate error](https://support.twilio.com/hc/en-us/articles/360007853433-Troubleshooting-Certificate-Errors-from-the-Twilio-REST-API). But it may be something else, we would need more details such as code samples and more sids in order to debug further. Because your issue seems to be a different, please open a new issue with us so we can help you there.

Best,
Joyce

**Comment by Zohair-Equitec** [comment]
@sundardsTechMind is your issue sorted? If it's sorted then please let me know the solution.

**Comment by amunchet** [comment]
I'm currently on iOS 15.2.1 and I have this issue.  I can see the local video until I click "Allow Access", then the video display turns black.

I'm using this project as a base: https://github.com/miguelgrinberg/flask-twilio-video.  I have updated the version of the Twilio-video JS to 2.18.0.

The phone's video is still being recorded and I can see it if I connect to the room from a desktop computer - I just can't see it from the device after I connect (but I can see it before).

A sample Name and SID are: 

Test Room
RM2046bff5d5247238ed7193d2c919b987

**Comment by amunchet** [comment]
Worked it out - this comment pointed me in the right direction: https://github.com/twilio/video-quickstart-js/issues/116#issuecomment-665794978
