### ISSUE TITLE
Pixelated Video Stream initiated from Chrome.

### ISSUE THREAD

**Issue by PavloShchur** [twilio/twilio-video.js#1646]
**Problem**
When a video is published on Chrome then it always has a bad quality for other participants who use different browsers (Chrome, Safari, Firefox). The issue cannot be reproduced when a video is published on Firefox.

**Technical details**
1. Room sid : RMc3339289e5dae115a737ca5f45cb55ac;
2. Room type : group;
3. Browser : Chrome, 96.0.4664.45 (Official Build) (64-bit);
4. Latest browser versions are used;
5. Internet download/upload speed is 13.16/0.81Mbps;
6. Video dimensions : `{width: 480, height: 242}`. It is expected to be `{width : 1920, height : 1080}`.

**Workaround**
Comment out the following code : `preferredVideoCodecs : [{ codec : 'VP8', simulcast : true }]` for participant who publishes and for participant who receives the video track. When we remove this code then video resolution is changed from `{width: 480, height: 234}` to `{width: 720, height: 351}`.

The issue could be reproduce also with iOS SDK. When a video is published by using iOS SDK with `[TVIVp8Codec(simulcast: true)]` then for other participant quality is `{width: 245, height: 180}`, without property - `{width: 980, height: 780}`.

As a result, our multiple tests with different browsers/devices and SDKs show that for **Group** rooms with **presentation** mode video quality is better without `preferredVideoCodecs : [{ codec : 'VP8', simulcast : true }] / [TVIVp8Codec(simulcast: true)]`.

The property was added because it is recommendation:

- https://www.twilio.com/docs/video/tutorials/developing-high-quality-video-applications#mobile-browser-presentation-recommended-settings
- https://www.twilio.com/docs/video/tutorials/developing-high-quality-video-applications#mobile-sdks-presentation-recommended-settings

**Questions**
1. Is the workaround valid? If it is valid, could it be used for P2P and Group rooms?;
2. Which minimum requirements for download/upload Internet speed for participant who publish video tracks for those who receives them?

**Comment by makarandp0** [comment]
Hello @PavloShchur, Thank you for writing and sorry about the delay.

I looked at the room (`RMc3339289e5dae115a737ca5f45cb55ac`) you mentioned and I see that you have set `contentPreferencesMode` to `manual`. Does your application set the video dimensions for remote track by calling [setContentPreferences](https://media.twiliocdn.com/sdk/js/video/releases/2.18.1/docs/RemoteVideoTrack.html#setContentPreferences__anchor)?  What render dimensions does it set ?  When `contentPreferencesMode` is set to `manual`, the render dimension set by the subscriber determine the simulcast layer it receives. Can you try specifying larger dimensions and see if that helps?

Thanks,
Makarand

**Comment by PavloShchur** [comment]
Hello @makarandp0, thank for the reply.

Yes, we use `setContentPreferences({renderDimensions: {width : 1920, height : 1080}})`.

Currently, we use **VP8** `preferredVideoCodecs : [{ codec : 'VP8', simulcast : true }]` but when we changed to **H.264** `preferredVideoCodecs : [{ codec : 'H.264', simulcast : true }]` video resolution has changed from approximately **480x234** to **Full HD**.

1. Room sid: RMdc3c2ea1897b6d534b2a3ede5dcd257b;
2. Video JS SDK: 2.18.1.

Could you tell us if video codec could be an issue?

**Comment by makarandp0** [comment]
Hello @PavloShchur, Thank you for the update. Your `setContentPreferences ` looks good. 
BTW: `[{ codec : 'H.264', simulcast : true }]` is not a valid value for codec. For H.264 it needs to be  `[{"codec":"H264"}]`. I saw that in your room  (`RMdc3c2ea1897b6d534b2a3ede5dcd257b`) when you set invalid codec value, SDK ended up using VP8 w/o simulcast. In this setting publisher encodes  a single layer, and SFU simply forwards the layer to subscriber - which results in subscriber seeing full HD as expected.

Re: why do subscribers get low-res tracks with simulcast enabled - we are still investigating into this.

**Comment by PavloShchur** [comment]
Hello @makarandp0,

We have also tried with `[{"codec":"H264"}]` and we still receive low-resolution video. It always happens with simulcast enabled.

Do I need to provide you with some additional information?

**Comment by makarandp0** [comment]
Hello @PavloShchur, we just released SDK with support for [adaptive simulcast](https://github.com/twilio/twilio-video.js/releases/tag/2.19.0). Please give it a try and let us know if that helps.

**Comment by PavloShchur** [comment]
Hello @makarandp0,

Our problem was resolved by enabling sender side congestion control algorithm.
