### ISSUE TITLE
The `connect` method does not return a `Promise` despite Typescript type definitions saying so

### ISSUE THREAD

**Issue by Mange** [twilio/twilio-video.js#1647]
- [X] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [X] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [X] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [X] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

```js
connect("access-token-here", {name: "room-name"}).finally(() => alert("Finally"));
```

**Expected behavior:**

An alert should be shown after the connection is fulfilled or errors. Typescript type definitions say that `connect` should return a `Promise`.

**Actual behavior:**

Uncaught `TypeError` because `finally` is not a method on `CancelablePromise`, which is returned instead of a `Promise`.

Either declaring the types of `connect` correctly or implementing `finally` is a good solution to me, but these kinds of issues will keep happening if the types indicate a `Promise` and the library doesn't return a `Promise` (or subclass of it), so I think that solution is more correct.
(I wouldn't mind a `finally` too, of course! :smile: )

**Comment by PikaJoyce** [comment]
Hi @Mange,

Thank you for submitting this issue. You're right in that `connect` is supposed to return a `CancelablePromise` instead of a `Promise`. I've created an internal ticket to fix this (VIDEO-7831). I'll keep this issue open and keep it updated as we progress with this ticket.

Thanks again!
Joyce

**Comment by PikaJoyce** [comment]
Hi @Mange !

The fix for this issue has been merged into develop so I'll be closing this issue now. Let me know if you've got any further questions or issues. And please don't hesitate to open another issue with us if that's the case :) 

Thanks again!
Joyce

**Comment by Mange** [comment]
Thank you. Very nice work! :heart:
