### ISSUE TITLE
Frozen Video Frame on Remote Participant

### ISSUE THREAD

**Issue by jujuzz** [twilio/twilio-video.js#1658]
**ISSUE DESCRIPTION**

We are building an application where both iOS and desktop users can share video and audio via a shared twilio room.

We are adding the capability for iOS users to “hide” their video from the room by unpublishing their video track to the room. These users can additionally “unhide” their video by re-publishing their video track to the room.

**EXPECTED BEHAVIOR**

When an iOS user re-publishes their video, their video feeds should be streaming to all subscribed participants.

**ACTUAL BEHAVIOR**

When an iOS user re-publishes their video, their video feeds resume streaming to iOS participants, but their video appears frozen for desktop participants. Reloading the desktop window resolves this issue.

**FURTHER INFORMATION**

We are currently listening to the “trackUnpublished” event and “trackPublished” event on the RemoteTrackPublication to hide and show the video element in the desktop. 

**SOFTWARE VERSIONS**
Browser(s): Chrome
Operating System: iOS 15.1
twilio-video.js: 2.17.1

**Comment by charliesantos** [comment]
Hi @jujuzz thanks for reporting. This sounds related to this issue https://github.com/twilio/twilio-video.js/issues/1632
Can you reproduce on iOS 14 or older?

**Comment by jujuzz** [comment]
Hi @charliesantos. Thank you for your response. We are not able to reproduce on older versions.

**Comment by charliesantos** [comment]
@jujuzz thanks for verifying. Please check and watch #1632 instead and I will close this one now.
