### ISSUE TITLE
iOS browser: Selecting audiooutput or make it default to speaker

### ISSUE THREAD

**Issue by tavoohoh** [twilio/twilio-video.js#1662]
By default when joining a video room from an iOS device the audio output defaults to the earpiece. Already tried  `navigator.mediaDevices.enumerateDevices()` to find the audiooutput devices but iOS does not return any. Is there another way to change the output device or make it default to the speaker or headphones?

**Comment by PikaJoyce** [comment]
Hi @tavoohoh,

Thank you for opening this issue with us. Unfortunately, iOS does not let us query the output device. If you'd like to set an alternative output device from your input, you can try implementing [selectAudioOutput](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/selectAudioOutput). However, this does not work on iOS. Here's how we do it within our [quickstart examples](https://github.com/twilio/video-quickstart-js/blob/master/examples/mediadevices/src/index.js#L219). 

I'll be closing this issue as there's no action items on our side from this issue, but I'm more than happy to continue discussions on this thread!

Regards,
Joyce
