### ISSUE TITLE
Random black screen of remote participant coming from web client

### ISSUE THREAD

**Issue by jgarciapueyo** [twilio/twilio-video.js#1663]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ ] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Background Information:**  
We have developed a 1-to-1 web <-> android videocall service using Twilio P2P rooms. The web client (wc) creates the room and connects to it using the function `connect()`. Later, it communicates the name of the room to the android client (ac) through Firebase, so that the android client can connect to the same room.

**Expected behavior:**  
On both clients (web and android), the local video track and the remote video track should be rendered normally.

**Actual behavior:**  
Sometimes (approximately 1 out of 15 times), the android client renders the remote track of the web client as a black screen from the beginning of the videocall. We have identified that when this happens, right at the start of the videocall the android client registers a chain of events `onVideoTrackSubscribed -> onVideoTrackUnsuscribed -> onVideoTrackSubscribed`.
(It exists a similiar issue of a black screen with a comment referring to this chain of events [twilio/video-quickstart-android#536](https://github.com/twilio/video-quickstart-android/issues/536#issuecomment-677785833), but it has been closed without an answer).

We have tried to develop a secondary android client (ac2) with similar behaviour as the web client (wc) to test if the failure of the rendering of the remote track in the original android client (ac) was coming from the web client (wc) or it was in the receiving part of the original android client (ac). When the communication was between ac - ac2, the rendering of the remote track in the original android application was always correct, so we are inclined to believe that the origin of the problem comes from the web client.

In addition, this problem has been accentuated when we created the video and audio local tracks manually in the web client and passed them to the `connect()` function. 

**Code to reproduce the issue:**  
We use Angular on the web client, so we have included the main file of the videocall component.

`main.component.ts`
```ts
export class MainLayoutComponent implements OnInit {
  ngOnInit(): void {
    this.route.paramMap
      .pipe(
        // ============================
        // logic to get videocall token ...
        // ============================
        concatMap((result: {token: string, roomUUID: string}) => {
          return from(
            this.deviceSelectionService
              .getDeviceSelectionOptions(
                this.audioOutput,
                this.audioInput,
                this.videoInput
              )
              .then(([audioOutput, audioInput, videoInput]) => {
                this.audioOutput = audioOutput;
                this.audioInput = audioInput;
                this.videoInput = videoInput;
                return Promise.all([
                  createLocalAudioTrack({
                    deviceId: audioInput.selected.deviceId,
                  }),
                  createLocalVideoTrack({
                    deviceId: videoInput.selected.deviceId,
                  }),
                ]);
              })
              .then((createdTracks) => {
                const [localAudioTrack, localVideoTrack] = createdTracks;
                this.localAudioTrack = localAudioTrack;
                this.localVideoTrack = localVideoTrack;
                return connect(result.token, {
                  name: result.roomUUID,
                  tracks: createdTracks,
                })
              })
          );
        }),
        tap((room: Room) => {
          this.room = room;

          room.localParticipant.videoTracks.forEach((publication) =>
            this.appendLocalVideoDisplay(publication)
          );

          room.participants.forEach(this.onParticipantConnected.bind(this));
          room.on(
            'participantConnected',
            this.onParticipantConnected.bind(this)
          );

          room.on('participantDisconnected', (participant) =>
            this.onParticipantDisconnected(participant, room)
          );

          this.changeAudioOutput();
        }),
      )
      .subscribe(
        (room) => (this.room = room),
      );
    }

  changeAudioOutput(): void {
    this.room.participants.forEach((participant) => {
      participant.audioTracks.forEach(async (audio) => {
        const track = audio.track;
        if (track.kind === 'audio') {
          const audioElement: any = track.attach();
          await this.deviceSelectionService.applyAudioOutputDeviceSelection(
            this.audioOutput,
            audioElement
          );
        }
      });
    });
  }

  async changeAudioInput(): Promise<void> {
    this.localAudioTrack =
      (await this.deviceSelectionService.applyInputDeviceSelection(
        this.audioInput,
        'audio',
        this.localAudioTrack
      )) as LocalAudioTrack;
  }

  async changeVideoInput(): Promise<void> {
    this.localVideoTrack =
      (await this.deviceSelectionService.applyInputDeviceSelection(
        this.videoInput,
        'video',
        this.localVideoTrack
      )) as LocalVideoTrack;
  }
```

The code below is the responsible to abstract the selection of audio and video output in order to change microphones, speaker and cameras.

`deviceSelectionService.ts`
```js
  /**
   * Apply the selected audio output device.
   */
  public applyAudioOutputDeviceSelection(
    device: MediaDevices,
    audio: any
  ): any {
    return typeof audio.setSinkId === 'function'
      ? audio.setSinkId(device.selected.deviceId)
      : Promise.reject(
          'This browser does not support setting an audio output device'
        );
  }

  /**
   * Apply the selected input device.
   */
  public applyInputDeviceSelection(
    device: MediaDevices,
    kind: 'audio' | 'video',
    localTrack?: LocalAudioTrack | LocalVideoTrack
  ): Promise<LocalAudioTrack | LocalVideoTrack> {
    const constraints = {
      deviceId: {
        exact: device.selected.deviceId,
      },
    };
    if (localTrack) {
      return localTrack.restart(constraints).then(() => {
        return localTrack;
      });
    }
    return kind === 'audio'
      ? createLocalAudioTrack(constraints)
      : createLocalVideoTrack(constraints);
  }

  /**
   * Get the list of available media devices.
   */
  public async getDeviceSelectionOptions(
    audioOutput: MediaDevices,
    audioInput: MediaDevices,
    videoInput: MediaDevices
  ): Promise<[MediaDevices, MediaDevices, MediaDevices]> {
    const [audioOutputDevices, audioInputDevices, videoInputDevices] =
      await this.getDevices();

    audioOutput.devices = audioOutputDevices;
    audioInput.devices = audioInputDevices;
    videoInput.devices = videoInputDevices;

    if (!audioOutput.selected) {
      audioOutput.selected =
        audioOutput.devices.length > 0 ? audioOutput.devices[0] : null;
    }

    if (!audioInput.selected) {
      audioInput.selected =
        audioInput.devices.length > 0 ? audioInput.devices[0] : null;
    }

    if (!videoInput.selected) {
      videoInput.selected =
        videoInput.devices.length > 0 ? videoInput.devices[0] : null;
    }

    return [audioOutput, audioInput, videoInput];
  }
```

**Extra Information**
In case this is useful, some of the Room sid of the rooms where the black screen issue has appeared are:
- RM9947ec64945bbae74c8e91c6106968d2
- RM405cb60b295256fc87555944a38802f0
- RM2db23e78bdb3aa9b6a700cffd2d068ae
- RMeaab9ab015ad5cfca3555f5839316668
- RM8a6e643340f54a12cccf56d9119554a2

We have also added three debug files:
[normal-screen.log](https://github.com/twilio/twilio-video.js/files/7702636/normal-screen.log)
[black-screen.log](https://github.com/twilio/twilio-video.js/files/7702642/black-screen.log)
[black-screen2.log](https://github.com/twilio/twilio-video.js/files/7702644/black-screen2.log)

**Software versions:**

 - [x] Browser(s): Chrome Version 95.0.4638.69, Safari 15.1 (17612.2.9.1.20)
 - [x] Operating System: Ubuntu 20.4.3, macOS Monterrey 12.0.1
 - [x] twilio-video.js: 2.18.1
 - [x] Third-party libraries (e.g., Angular, React, etc.): Angular

**Comment by PikaJoyce** [comment]
Hi @jgarciapueyo,

Thank you for opening this issue with us! Can you please share how you are attaching the track, you do this for your audio track but the same isn't done for the video track? Here's how we do this on our [React App](https://github.com/twilio/twilio-video-app-react/blob/master/src/components/VideoTrack/VideoTrack.tsx), and here's some extra [documentation](https://www.twilio.com/docs/video/javascript-v2-getting-started#working-with-remote-participants) that may be helpful. If possible, it would also be helpful to try this out on the [Quickstart](https://github.com/twilio/video-quickstart-js) as well. 

Please let me know! Thank you!
Joyce

**Comment by jgarciapueyo** [comment]
The remote video in the web client is attached in the `onParticipantConnected` function. I have also added the code for attaching the local video:

```js
  onParticipantConnected(participant: Participant): void {
    participant.on('trackSubscribed', (track: RemoteVideoTrack) => {
      const video = track.attach();
      video.id = participant.sid;
      document.getElementById('remote-display').appendChild(video);
    });

    participant.on('trackUnsubscribed', (track: RemoteVideoTrack) => {
      track.detach().forEach((element) => element.remove());
    });
  }

  appendLocalVideoDisplay(publication: LocalVideoTrackPublication): void {
    const myVideo = publication.track.attach();
    document.getElementById('local-display').appendChild(myVideo);
  }
```

However, what fails is the rendering of the remote video track in the android client. This would be the local video track in the web client that is published to the android client. The reason I have opened the issue in the `twilio-video.js` repo is because when the web client (wc) is replaced by another android client (ac2) there is no black screen in the remote video track in the original android client (ac), so the error must come from the publication of the local video track in the web client (or that is what we think). 

Do you know how could we verify if the video being published from the web client is correct and has not been corrupted? The debug logs attached previously do not seem to give that information.

Thank you for the other suggestions like the React App and Quickstart. As soon as I have some time, I'll take a look and see if the black screen appears using them.

Regards,  
Jorge.
