### ISSUE TITLE
Twilio Network Quality API networkQualityLevel dropped to 1-2 and never rose back 

### ISSUE THREAD

**Issue by Dipesh-Das97** [twilio/twilio-video.js#1672]
Hi, I have been seeing an issue where the `networkQualityLevel` never rose back once it dipped to levels 1-2. Also `networkQualityLevelChanged` event is set on participant connect but it never triggers once it drops to level below 2. Can some one give any insight on this?

**Comment by charliesantos** [comment]
Hi @Dipesh-Das97 thanks for reporting. Are you seeing this only recently? Can you also please provide some room sids, browser information, OS information, and sdk version?

**Comment by CyranMS** [comment]
We also have this issue. Seems like it occurred in the recent 3-4 weeks. Before that it was never a problem for us.
We will collect SIDs and get back to you.

**Comment by CyranMS** [comment]
@charliesantos here is one room sid
RMc3ec1e1081fbe3f171ccf45f1a6a070d

**Comment by vbabenko** [comment]
The same problem,
Could it be related to the fix introduced in the release?
2.18.2 (December 15, 2021)

**Comment by charliesantos** [comment]
Thanks for the information everyone. I'll submit an internal ticket to investigate further.

**Comment by vbabenko** [comment]
@charliesantos Any news on this topic?

**Comment by charliesantos** [comment]
Hey @vbabenko , please check out 2.19.1 release once it goes out and let me know if you're still able to reproduce.

**Comment by vbabenko** [comment]
Thank you for the update! We've updated the Twilio version to 2.19.1 and we will need several days to test and gather feedback from users. I will keep you updated!

**Comment by vbabenko** [comment]
@charliesantos seems like the issue is fixed! Thank you for your work!
