### ISSUE TITLE
Video track pausing in middle of calls. 

### ISSUE THREAD

**Issue by Jaikishann** [twilio/twilio-video.js#1676]
Hi Team, Recently we are getting more and more reports on screen video track pausing in middle of call and resuming after some time. We were also able to reproduce the issue and collect the logs for all the participants in the call.

RoomSid: RM781d56f0b5a03041a997756d6646c13b
No of participants in call: 3
track publisher's twilio log: https://storage.teleport.video/files/f81JyJSiXQyF/twiliolog-910b7a23-f2b7-4ca2-911e-90d44e7a67a6.log
track subscriber1 twilio log: https://storage.teleport.video/files/fdyOGwwZ6TP8/twiliolog-b5d9f6e8-9d5b-4069-b82e-11c58d23ed83.log
track subscriber2 twilio log: https://storage.teleport.video/files/fL1VFwC5Q8jN/twiliolog-50ba9957-00f0-40ca-bb4b-8e0312542629.log

We also took screenshot of the webrtc graph - https://share.anysnap.app/fJhK3WqiNwdc. As you can see the framesReceived graph dropped for a couple of minutes and resumed after some time.

**Expected behavior:**

The screen track ( technically video track) should be playing without any interruption.

**Actual behavior:**

The video track pauses often for about 5 mins and resumes back. We have also noticed that this issue sometimes occurs multiple times in the same call.

**Software versions:**

 - [ ] Browser(s): Chrome/96.0.4664.110
 - [ ] Operating System: Mac OS X 10_15_7
 - [ ] twilio-video.js: 2.15.3
 - [ ] Third-party libraries (e.g., Angular, React, etc.): React

**Comment by axel127** [comment]
We've been seeing the same issue for a few weeks and haven't found a resolution yet. We've tried changing the `trackSwitchOffMode`, but that didn't really help.

**Comment by makarandp0** [comment]
Hello @Jaikishann, Thank you for reporting this issue. I looked into the room `RM781d56f0b5a03041a997756d6646c13b `, but found that we do not have metrics from client for this room. This could happen if you are connected with option `insights: false` - Was that the case for your application? Could you send us another room sid with insights turned on?

The webrtc graph you attached is helpful - it does indicate that subscriber did not receive any frames during that period, Could you be able to collect the graph (or even better webrtc dump) from both subscriber and publisher ?

You mentioned that you were able to reproduce the issue locally - Can you send us some steps if possible that would help us reproduce the issue locally?

Thanks,
Makarand

**Comment by makarandp0** [comment]
Hello @Jaikishann,  @axel127  I have filed an internal bug to track this issue (VIDEO-8211), If you find repro steps or any details to help narrow this down please let us know.

**Comment by Jaikishann** [comment]
Hi @makarandp0, Currently we are not aware of the steps to reproduce the issue. It happens randomly. But we will try to turn on insights and provide you the RoomSID when it happens in future calls.

**Comment by nicopernas** [comment]
Hey! quick update on our next steps regarding this issue. We've identified the culprit and we are rolling out a mitigation that should be available WW within 2 or 3 days max. Apologies for the inconveniences. Thanks.

**Comment by nicopernas** [comment]
The mitigation has been rolled out WW. Any feedback or confirmation of the fix will be appreciated :) cc: @axel127 @Jaikishann

**Comment by axel127** [comment]
Thanks @nicopernas! We'll follow up with the users who were experiencing the issue and let you know if they observe an improvement.

**Comment by makarandp0** [comment]
@Jaikishann, @axel127 I am closing this issue now as its fixed. Please reopen another if you are still seeing this behavior.
