### ISSUE TITLE
How to improve noise suppression with twilio?

### ISSUE THREAD

**Issue by CyranMS** [twilio/twilio-video.js#1691]
The Noise suppression on Twilio seems almost non-existent. We have real trouble when people are in the same room as the mic pics up everything

Compared with Teams which has great suppression so that you could have 10 people all on calls in the same space….at the moment whenever anyone needs to demo on demodesk they go find their own room

**Comment by makarandp0** [comment]
Hello @CyranMS, Thank you for your post. 

Currently twilio depends on browser's noise suppression.  Can you please confirm that you obtain the audio track with `noiseSuppression` enabled ? You can enable noise suppression by specifying it in constraints when acquiring the track. 
```
const mediaStream = await navigator.mediaDevices.getUserMedia({ audio: { noiseSuppression: false }})
```

That said, we are aware that browsers noise suppression can be limited. We are working on alternatives to the browsers noise suppression.  Will post here when we have more details to share.

Thanks,
Makarand

**Comment by CyranMS** [comment]
Thank you. Yes, browser-based noise suppression is very limited. Good to hear that you guys work on something, because this is super urgent to provide a better video experience.

**Comment by genevpd** [comment]
Our customers asking about the same noise suppression capability. We'd appreciate any update on when this could be made available.

**Comment by genevpd** [comment]
@makarandp0 it looks like Agora released a beta version of AI noise reduction as an extension to client libraries  https://docs.agora.io/en/Video/noise_reduction_web_ng

Is this something you have on the roadmap as well?

**Comment by makarandp0** [comment]
Yes, we are actively working on noise suppression improvements, We will have more details to share soon.

**Comment by manjeshbhargav** [comment]
Hi @CyranMS , @genevpd ,

The latest video sdk version `2.24.3` supports [third-party noise cancellation](https://www.twilio.com/docs/video/noise-cancellation). Please check it out.
