### ISSUE TITLE
Video Dimension Events Not Occuring

### ISSUE THREAD

**Issue by treyrich** [twilio/twilio-video.js#170]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.

**Expected behavior:**

When using twilio-video.js with a native client, and the native client rotates their device, the various video dimension changed events should occur.

**Actual behavior:**

Video dimension events aren't occurring. I'm not sure when this started happening, but I know for sure that in a previous version the events were happening as expected.

**Software versions:**

 - [x] Browser(s): Chrome 61
 - [x] Operating System: macOS 10.12.6
 - [x] twilio-video.js: 1.3.0
 - [x] Third-party libraries (e.g., Angular, React, etc.): Angular 4.3.6

**Comment by markandrus** [comment]
Thanks for the report @treyrich,

At first glance, because you mention rotation, I'm wondering if this may be related to https://github.com/twilio/twilio-video.js/issues/20 Could you please share

* Whether or not you see this in P2P Rooms, Group Rooms, or both?
* A Room SID where this issue occurs?
* Which native client are you using? iOS? Android? version?

Thanks,
Mark

**Comment by treyrich** [comment]
It's a P2P Room, an SID is RMa5bb5e8176330f4aa2b29699eb96752e, said SID was tested with one of the 2.0.0 previews (not quite sure which one was installed on the device I tested with).

I doubt that it's related to #20 since since even under the conditions described in that issue I'd still expect the dimension change events to run when the dimensions change (even if the video is rotated incorrectly).

**Comment by shaneahern** [comment]
I am having this issue also, using Chrome 63, mac os 10.13.1,  twilio-video.js 1.7.0 -- dimensionsChanged event never fires when chat participant running on mobile client rotates device. Same code on Firefox 57.0.4 works as expected, dimensionsChanged fires each time chat participant rotates device. Any updates on this issue?

**Comment by markandrus** [comment]
There is a Chrome bug for this—[Issue 782245: Video element in desktop Chrome is not resized when remote iOS client rotates the device](https://bugs.chromium.org/p/chromium/issues/detail?id=782245).
