### ISSUE TITLE
Audio and Video Tracks comes as empty array while Participant join to video call 

### ISSUE THREAD

**Issue by ganap** [twilio/twilio-video.js#1707]
Hello, 
I am trying to integrate Video chat in my project But When I or any participant join the room, value of Audio and Video tracks are comes as empty array because of which I couldn't able to do track visualization on screen.
Below is what I get as participant log,

![image](https://user-images.githubusercontent.com/7342398/153731092-d16492e6-2dd5-4611-9e48-b46923ef8d6b.png)

         room.on('participantConnected', participant => {
            console.log("Remote Participant --->",participant)

            participant.on("trackSubscribed", track => console.log("Subscribe",track));
            participant.on("trackUnsubscribed", this.trackUnsubscribed);
        });
Please help me to figure out exact issue

**Comment by manjeshbhargav** [comment]
Hi @ganap ,

Thanks for writing in with your issue. Is it possible to access your application using a URL? I would love to debug your source in order to see if the SDK is being used as intended.

Thanks,

Manjesh
