### ISSUE TITLE
Video is black

### ISSUE THREAD

**Issue by naissa12** [twilio/twilio-video.js#1708]
Hi,

I followed this tutorial https://www.twilio.com/blog/build-a-custom-video-chat-app-with-react-and-twilio-programmable-video, but unfortunately, when I connect with a remote user, his video is black to me. He can see me, but I can't see him even though he enabled the camera. He is on a Windows 11. 

Can someone please help?

I'm coding in React JS and Node using this tutorial https://www.twilio.com/blog/build-a-custom-video-chat-app-with-react-and-twilio-programmable-video

**Comment by naissa12** [comment]
Login to mentordial.com

Login as test12@gmail.com
Password - learnnow

Go to https://mentordial.com/meeting/1264

**Comment by dbounds** [comment]
@manjeshbhargav any success?
