### ISSUE TITLE
Twilio sms delivery failed 

### ISSUE THREAD

**Issue by Bikash-lama** [twilio/twilio-video.js#1709]
Hello Twilio,

From last week, there is a scenario that message containing specially url are kind of failing. This issue was not seen before, 
but currently the undelivered rate is kind of high. 

Could you guide me in it?

**Comment by manjeshbhargav** [comment]
@Bikash-lama ,

This repository is concerned with the Twilio Video JavaScript SDK. In order to file an issue related to Programmable SMS, please go to https://support.twilio.com.
