### ISSUE TITLE
Unstable video quality

### ISSUE THREAD

**Issue by IvanKalachev** [twilio/twilio-video.js#1711]
From 31st January I have a major issue with unstable video quality. First let me explain what exactly my use case is. I have an application where every user that is connected to the room can have 2 video feeds with max resolution of 1920 x 1080 and one screen share feed. Basically only one user have 3 feeds constantly on and others are just watching with audio. Until now I was using peer 2 peer rooms and everything was working fine (last with version 2.18.3). From 31st January I have major problem with a video quality - for example if the user is streaming at 1920 x 1080 on the remote participant's side the video resolution is not stable - it constantly jumps from 1920 x 1080 to 1440 x 900 then to 960 x 540 or even to 640 x 480 and then back up. On the both ends the network quality is perfect and there is not packets lost or CPU overload. 

I've contacted a Twilio's support but they didn't provide any  reasonable answer for the issue and they've suggested a switch to a group rooms. And this is exactly what I did, but the problem still persists.  I've also updated twilio-video.js to version 2.19.1.

My settings on connect for group room are:

```
 bandwidthProfile: {
                        video: {
                            mode: 'presentation',
                            trackSwitchOffMode: 'detected',
                        }
                    },
 dominantSpeaker: false,
```

I've choose presentation mode because is important for the 3 main feeds (mentioned above) to get the highest bandwidth. Also this feeds are with 'high' priority with frame rate of 24 for video feeds and 15 for the screen share feed. I don't want to use dominant speaker API because basically the user with the 3 important feeds will not become  a dominant speaker. 

After these changes the result is the same as it was with the peer to peer rooms - constantly changing the video resolution.

I've contacted again the Twilio's support and they gave me and advise to run a test with a Twilio Video Diagnostic App which I did and the results are perfect (on the both ends):

_RTT (ms) avg/max | 142.2 / 552 (Good)
Jitter (s) avg/max | 0.01 / 0.02 (Excellent)
Packet loss avg/max | 0.66% / 4.24% (Excellent)
Bitrate (kbps) avg/max | 3,774.6 / 5,990.55 (Excellent)_

Also they suggested to do a test connection to the room with Preflight and again there is no issues with the connection (on the both ends). 

I am currently out of ideas what exactly cause this issue that I have and the strangest thing is that I didn't change anything in the code related to Twilio and the video before the problem appeared on 31 January.

**Comment by makarandp0** [comment]
Hello @IvanKalachev, Thank you for reporting this issue, and sorry for late reply

You mentioned that you are using peer-2-peer rooms. The bandwidthProfile settings you mentioned are applicable only to group rooms, so those should not have any effect on p2p rooms. 

Which browser/os are you using to connect? Can you please share some room sids that had this video quality issue, and also client side logs if possible.
Thanks,
Makarand
