### ISSUE TITLE
User seems to connect to a room even after the connect attempt fails

### ISSUE THREAD

**Issue by rykkers** [twilio/twilio-video.js#1723]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

```js

const signalingRegions = [
   "gll", //Global Low Latency (see section below)
   "ie1", //Ireland
   "us1", //US East Coast (Virginia)
   "de1", //Germany
   "au1", //Australia
   "br1", //Brazil
   "in1", //India
   "jp1", //Japan
   "sg1", //Singapore
];

const connectToRoom = (retryNumber = 0) => {
  let region = signalingRegions[retryNumber];

  Video.connect(token, { name: roomName, tracks: myTracks, region: region }).then(room => {

     twilioRoom = room;

     //handle all of the room connection states
     twilioRoom.on('disconnected', function(room, error) {
       if (error) {
         flashAlertMessage("bg-red", "Unexpectedly disconnected: ("+error+"), retrying connection, please wait", 8000);

         //disconnect and reconnect to room
         twilioRoom.disconnect();
         connectToRoom();
       }
     });
     twilioRoom.on('reconnecting', error => {
       //show reconnect alert
     });
     twilioRoom.on('reconnected', () => {
       flashAlertMessage("bg-dustyBlue", "Connection was reestablished", 5000);
     });

     document.dispatchEvent(videoConferenceJoinedEvent);

   }, error => {

     console.error(`Unable to connect to Room: ${error.message}`);
     console.error(error);

     if (retryNumber < signalingRegions.length-1) {
       //flash warning and try again
       flashAlertMessage("bg-red", "Unable to connect to session, retrying...", 5000);
       retryNumber++;
       connectToRoom(retryNumber);
     } else {
       //fail
       flashAlertMessage("bg-red", "Couldn't connect to session at all", 5000);
     }
   });
}

```

**Expected behavior:**

When a connect fail happens it stays failed and the user isn't added as a participant.
If a subsequent attempt to join the room is made, we shouldn't see a "Duplicate Identity" or "Max Capacity" error.

**Actual behavior:**

On some occasions we receive a signalling error.

Attempt to connect again with a different signal server.

Receive either "Duplicate Identity" or "Max Capacity" error.

Note that this clearly only happens under certain conditions on our live server and we haven't been able to reproduce locally.

**Software versions:**

 - [x] Browser(s): multiple
 - [x] Operating System: multiple
 - [x] twilio-video.js: 2.20.1
 - [x] Third-party libraries (e.g., Angular, React, etc.): none

**Comment by makarandp0** [comment]
Hello @rykkers, Thank you for reporting this issue. This does look odd - can you share room and participant sid for the participant which saw this duplicate identity error?
Thanks,
Makarand

**Comment by rykkers** [comment]
This is one example: RM7a9e2ebc8996537472296b3cfa5a7c21

Here is another: RMcadcc906ff898d15ab5515027de6877e

But we do have many more if you need them

**Comment by makarandp0** [comment]
hey @rykkers, I took a quick look at the room, and I see those are `go` rooms which allow maximum of two participants. I see that the room had lots (20+) participants, although not at same time. 
Given your repro scenario I see a possibility where connection attempt timed out, so client gave up  but server wasn't aware of the disconnection yet, and therefore it disallowed next participant which tried to connect immediately.  One way to workaround this issue would be to wait about 30 seconds between connection attempts. If you can provide client side logs from the connection attempt that failed (but the one you suspect was counted anyways) I could confirm this theory.

Another workaround would be to use [REST apis](https://www.twilio.com/docs/video/api/rooms-resource) to query room and ensure that there aren't multiple participants before attempting to join the room again.  

Thanks,
Makarand

**Comment by rykkers** [comment]
Hey, thanks for the feedback. The client side logs we have support that theory, that the participants are trying to connect one after the other.

I'm thinking from a UX point of view that waiting 30 seconds between attempts wouldn't be the best, considering the 9 signalling servers that we cycle through (4 minutes 30 seconds to be told that you can't connect).

We could of course keep polling the REST API and wait until we can get in, but would be interested to know what sort of timeout we'd be looking at on the server side. As i guess this is all moot if the server hangs onto an identity for 30 minutes in this scenario.

I think what's interesting, is that clearly we are managing to connect to one server to register our intent to connect to the room. But it breaks when connecting to the signalling server. Perhaps a suggestion would be to return a room (in an in-progress state), within the error promise. Then we could at least try a room.disconnect() before attempting any other connection.

**Comment by makarandp0** [comment]
@rykkers, Can you please share the client side logs, I would like to see details on what is failing the connection and if we can do something as you suggested.

Also I am curious about why do you need to cycle thru the signaling regions? Isn't connecting to GLL or your local region always the best choice?

**Comment by rykkers** [comment]
We don't have full Twilio Client logs, as this happens on a only a few of our users and is hard to predict when. But our own logs show when disconnections happen and for what reasons.

I'd like to just use GLL, but some of our users get an error connecting to signalling server with GLL, and are able to connect when we use a different region. So it appears that they have firewall rules that are blocking some, but not all of the Twilio signalling servers.

Correct me if that assumption is not correct and we need to look at another route of getting people connected who are blocked from reaching some signalling servers.
