### ISSUE TITLE
What is the minimum version of Chrome

### ISSUE THREAD

**Issue by dannycohn** [twilio/twilio-video.js#173]
This isn't really an issue but I couldn't find the answer anywhere. What is the minimum version of Chrome supported?

**Comment by markandrus** [comment]
Hi @dannycohn,

It's a little difficult to identify a specific minimum version of Chrome, but I'd say Chrome 52 and up (52 introduced the non-buggy Promise-based WebRTC APIs as well as `srcObject`). We always aim for support for the current Chrome Stable release (plus a few preceding versions, based on usage patterns we see).

Mark
