### ISSUE TITLE
Could I force other user to disconnect from room?

### ISSUE THREAD

**Issue by PavloShchur** [twilio/twilio-video.js#1734]
I have not found such functionality in the official documentation:

1. [Release Notes](https://github.com/twilio/twilio-video.js/releases);
2. [twilio-video.js](https://media.twiliocdn.com/sdk/js/video/releases/2.21.0/docs/index.html);
3. [JavaScript Getting Started](https://www.twilio.com/docs/video/javascript-getting-started).

But I have found the [discussion](https://stackoverflow.com/questions/62762792/is-it-possible-to-force-others-to-leave-the-twilio-video-room-by-a-selected-user#:~:text=IF%20you%20want%20to%20remove,msg%20with%20tour%20own%20backend).

Could you confirm that the only way to disconnect a participant from room in JS SDK is to send **data track** to participant and this participant disconnects himself?

**Comment by anna-vasilko** [comment]
Hi @PavloShchur,
Thanks for reaching out!
The best way to disconnect a remote participant from a room is to use [Twilio Video REST API]([[url](https://www.twilio.com/docs/video/api)]). 
Find a specific example [here](https://www.twilio.com/docs/video/api/participants#kickremove-participant-from-a-room).
Hope it helps! I will close this ticket for now but let us know if you have further questions.

**Comment by PavloShchur** [comment]
@anna-vasilko, thank for the quick reply but I am asking about Twilio Video JS SDK, not about Twilio Video REST API.

Could you confirm that in Twilio Video JS SDK there is no way to force somebody to leave? We can just disconnect by ourselves by using `disconnect()` function.
