### ISSUE TITLE
Question: Can we get the current Twilio media server UTC time client-side?

### ISSUE THREAD

**Issue by michal-blinderhq** [twilio/twilio-video.js#1742]
Hi twilio-video team!

Is there any way to retrieve the current Twilio media server UTC time client-side via twilio-video.js?

We are collecting certain client-side events from group rooms that we are sending to our centralised data store for later analytics and processing. It is absolutely crucial that they share the same source of timestamps. Using client time is notoriously unreliable as each client machine may have the OS clock out of sync with the UTC servers.

We've taken a look at the signalling websocket channel but the messages don't appear to have any timestamps included. 

Ideally, we'd need the current media server timestamp to be sent with each room event (e.g. _trackStarted_, _trackDisabled_, etc.) but also be able to request this explicitly from the code if needed.

Of course, we can build our own "time API" but ideally we'd like to have this provided by Twilio as the single source of truth.

Thanks!

Michal

**Comment by michal-blinderhq** [comment]
Hi @charliesantos ,

Thank you for the reply.

Any chance this would be on the _twilio-video.js_ roadmap in the near future? E.g., all video room status callback events already contain timestamps - https://www.twilio.com/docs/video/api/status-callbacks#rooms-event-parameters

Cheers

Michal

**Comment by charliesantos** [comment]
Hey @michal-blinderhq ,
It is currently not in the road map, but we will consider it. Thank you for the suggestion!

Thanks,
Charlie

**Comment by michal-blinderhq** [comment]
Thanks, Charlie.
