### ISSUE TITLE
Add avatar in the moment the disabled Video

### ISSUE THREAD

**Issue by jeffamed** [twilio/twilio-video.js#1747]
I reviewed your documentation https://www.twilio.com/docs/video/javascript-getting-started#handle-remote-media-unmute-events, but did not understand with applying the style put a background black or hide the associated <video> for the other participants. my app is video conferencing, an example that Participant A disabled video and it is disabled but the Participant B see the video of Participant A with the last screen freeze and i want to show the avatar of person o background black

**code of Documentation**
```
function handleTrackDisabled(track) {
  track.on('disabled', () => {
    /* Hide the associated <video> element and show an avatar image. */
  });
}

room.participants.forEach(participant => {
  participant.tracks.forEach(publication => {
    if (publication.isSubscribed) {
      handleTrackDisabled(publication.track);
    }
    publication.on('subscribed', handleTrackDisabled);
  });
});
```

**My code in disabled video**

```
$("#muteVideo").click(function () {
        room.localParticipant.videoTracks.forEach(function(track) {
            track.track.disable();
            $("#iconMuteVideo").addClass('hidden');
            $("#iconUnmutedVideo").removeClass('hidden');
            console.log('mute video');
        })
    })
```
You can to give me the example for hide the associated <video> element and show an avatar image, please.

**Expected behavior:**

the screen of participant A will image avatar or background black

**Actual behavior:**
the last image of freeze participant 

TODO

**Software versions:**

 - [ ] Browser(s): Chrome
 - [ ] Operating System: Windows
 - [ ] twilio-video.js: 2.11
 - [ ] Third-party libraries (e.g., Angular, React, etc.): Laravel and Livewire

**Comment by charliesantos** [comment]
Hey @jeffamed thanks for submitting. I have a few questions:
- What version of Chrome are you using?
- Can you please try to update to the latest video sdk and see if you're still having the same behavior?
- Can you please try on Firefox and Safari?
- Are you seeing the same issue in our quickstart? https://github.com/twilio/video-quickstart-js

**Comment by jeffamed** [comment]
@charliesantos the answers to your questions

1. version of Chrome : Versión 99.0.4844.82 (Build oficial) (64 bits)
2. update the last version of twilio: 2.17.1  (it not working, same, last image of participant frame freeze)
3. i tried in firefox and same
4. i will review the quickstart


but like add style the track <video> or remove the last image freeze for the image avatar or background black

**Comment by jeffamed** [comment]
@charliesantos the answers to your questions

1. version of Chrome : Versión 99.0.4844.82 (Build oficial) (64 bits)
2. update the last version of twilio: 2.17.1  (it not working, same, last image of participant frame freeze)
3. i tried in firefox and same
4. i reviewed of quickstart and i can not disable video (muted video or turn off camara) 


but like add style the track <video> 
or remove  or hide tag <video> with the last image freeze for the image avatar or background black

**Comment by jeffamed** [comment]
i need to remove o hide the image freeze of the participant (in the moment the user turn off the camera ) and add the image avatar or background black  for the other participants in the room

**Comment by charliesantos** [comment]
Closing this now due to inactivity and there is no further action on our side. Please check my previous comment for the solution.
