### ISSUE TITLE
No video or record given normal bitrate

### ISSUE THREAD

**Issue by q-kit** [twilio/twilio-video.js#1748]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Expected behavior:**

User video should be properly streamed and recorded.

**Actual behavior:**

This issue happened to room RMa37cf1caad27eff793d8ea244655ce60. Only one participant published video/audio in this room, while all other participants subscribed the publisher's video/audio/data track. During the session, no video/audio was received by the subscribers. The log shows that the publisher had very high packet loss in the first 1 min of the session, but after that the bitrate, packet loss and round-trip time all seem to be normal. This room lasted about 30 mins, while the video record is only 56 sec long.

**Software versions:**

 - [x] Browser(s): Chrome/99.0.4844.73
 - [x] Operating System: Android 12
 - [x] twilio-video.js: 2.18.1
 - [x] Third-party libraries (e.g., Angular, React, etc.): vue.js

**Comment by charliesantos** [comment]
Hey @q-kit We have added some fixes related to this issue in the most recent releases. Can you please update to the latest version of the SDK and see if you're still able to reproduce?

**Comment by q-kit** [comment]
Hello @charliesantos,

Thanks for the suggestion! Could you also let me know some detail of this issue? I'm just curious about what caused it and how it was fixed.

Thanks!

Q

**Comment by charliesantos** [comment]
Hey @q-kit ,

No problem! This issue seems related to media connections not being able to reconnect after some network glitches. We have fixed some related issues in 2.19.1 which I think could address your issue. Please see the following links for more details.

- [Changelog](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md#2191-february-7-2022)
- [PR1](https://github.com/twilio/twilio-video.js/pull/1684)
- [PR2](https://github.com/twilio/twilio-video.js/pull/1685)

Thanks,
Charlie

**Comment by charliesantos** [comment]
Sounds good @q-kit . Please feel free to follow up in this space if you are still seeing the same issue.
