### ISSUE TITLE
Similar to Hangouts

### ISSUE THREAD

**Issue by brightworks** [twilio/twilio-video.js#175]
Is it possible with the Programmable Video API to build something that resembles the Hangouts functionality in terms of how it focuses on the person talking automatically?

**Comment by rfbrazier** [comment]
@brightworks, yes this is possible, but it would require some custom code. 

You'd need to gather and signal to your server the input volume from each Participant's microphone. Then, when one Participant becomes the "loudest," you would signal to the other participants in the Room to make the loudest Participant the dominant speaker.

This is a common feature request and we may add APIs that make it easier to implement this behavior in the future. 

Let us know if there is anything else we can do to help.

**Comment by brightworks** [comment]
Thank you for the response, this is helpful! Just wanted to confirm for now that it's doable.

**Comment by markandrus** [comment]
We'll close this issue for now. In the future, we may follow up with a code sample/demo of this.
