### ISSUE TITLE
Twilio creating multiple rooms with same room id ,even though the room is exist .

### ISSUE THREAD

**Issue by naveengit2000** [twilio/twilio-video.js#1754]
hi i am facing issue recently , twilio creating multiple rooms with same room id .even though the room is in active .

in my case : one person joined in the room with one id ,the second person also joined with same room id but it creates different room with same room id .

![Screenshot 2022-04-09 at 4 16 44 PM](https://user-images.githubusercontent.com/103245792/162568744-abbc927b-0a2b-46ed-9745-361a63382714.png)

10:43:38 UTC 2022-04-08 | 7852b59a-720f-4a64-b853-b4af4970701fRM865675b1accd1c7c8ad3351148089c50 | Group | 5 min 46 sec
-- | -- | -- | --
10:41:33 UTC 2022-04-08 | 7852b59a-720f-4a64-b853-b4af4970701fRM95149a0411ce048cd31551fb63930c48 | Group | 1 min 47 sec
10:21:41 UTC 2022-04-08 | 7852b59a-720f-4a64-b853-b4af4970701fRM17bbe75c90102ba0b378ea94abce0b83 | Group | 8 min 29 sec
10:08:19 UTC 2022-04-08 | 7852b59a-720f-4a64-b853-b4af4970701fRM7d85d1ff12903822cfbf7970e1b19e48 | Group | 9 min 11 sec
10:08:07 UTC 2022-04-08 | 7852b59a-720f-4a64-b853-b4af4970701fRMc14036216c338715619fade52e2ccd66 | Group | 10 sec
10:06:29 UTC 2022-04-08 | 7852b59a-720f-4a64-b853-b4af4970701fRM1a56bd20d7e730a54a1bd098957b6ace | Group | 46 sec

[10:43:38 UTC 2022-04-08](https://www.twilio.com/console/video/historic/logs/rooms/RM865675b1accd1c7c8ad3351148089c50)	
7852b59a-720f-4a64-b853-b4af4970701f
RM865675b1accd1c7c8ad3351148089c50
Group
5 min 46 sec
[10:41:33 UTC 2022-04-08](https://www.twilio.com/console/video/historic/logs/rooms/RM95149a0411ce048cd31551fb63930c48)	
7852b59a-720f-4a64-b853-b4af4970701f
RM95149a0411ce048cd31551fb63930c48
Group
1 min 47 sec
[10:21:41 UTC 2022-04-08](https://www.twilio.com/console/video/historic/logs/rooms/RM17bbe75c90102ba0b378ea94abce0b83)	
7852b59a-720f-4a64-b853-b4af4970701f
RM17bbe75c90102ba0b378ea94abce0b83
Group
8 min 29 sec
[10:08:19 UTC 2022-04-08](https://www.twilio.com/console/video/historic/logs/rooms/RM7d85d1ff12903822cfbf7970e1b19e48)	
7852b59a-720f-4a64-b853-b4af4970701f
RM7d85d1ff12903822cfbf7970e1b19e48
Group
9 min 11 sec
[10:08:07 UTC 2022-04-08](https://www.twilio.com/console/video/historic/logs/rooms/RMc14036216c338715619fade52e2ccd66)	
7852b59a-720f-4a64-b853-b4af4970701f
RMc14036216c338715619fade52e2ccd66
Group
10 sec
[10:06:29 UTC 2022-04-08](https://www.twilio.com/console/video/historic/logs/rooms/RM1a56bd20d7e730a54a1bd098957b6ace)	
7852b59a-720f-4a64-b853-b4af4970701f
RM1a56bd20d7e730a54a1bd098957b6ace
Group
46 sec

**Comment by charliesantos** [comment]
Hey @naveengit2000 , thanks for reporting. We're checking this now.

**Comment by charliesantos** [comment]
@naveengit2000 Our logs indicate that a single participant is connecting to an adhoc room (it is created on the fly as part of connect processing). That participant disconnects for some reason, which causes the room to be destroyed (this is how adhoc rooms work - they are ended as soon as the last participant leaves). Then the next participant connects, which creates a new adhoc room with a different roomSid. You'll need the second participant to connect before the first one disconnects to have them use the same room.

An alternative strategy is to use the REST API to create the room explicitly. That would allow you to specify how long you want the room to be kept in progress when there are no participants.

**Comment by charliesantos** [comment]
Closing since no further action is required. Please feel free to follow up if needed.
