### ISSUE TITLE
No video, audio, data for Android 12 users

### ISSUE THREAD

**Issue by q-kit** [twilio/twilio-video.js#1755]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Expected behavior:**

User audio/video/data tracks should be properly published.

**Actual behavior:**
We have two Android 12 users who failed to publish their audio/video/data tracks (and their logs show 0 bitrate for audio and video, 0 packet loss, 0ms round trip time). Below are the participant SIDs and room SIDs involved.

*User 1*
- Room SID: RMc8861fcdee0c6f926313362ca0853cd6
- Participant SID: PA4fe41f80999af0b44ab1fc20a5503519
- Browser: Chrome 99.0.4844.58
- Device: Samsung (SM-S908U)
-  twilio-video.js: 2.21.1
-  Third-party libraries: vue.js

*User 2*
- Room SID: RM3c556fb767facffa7fbc9a25d7d114a7
- Participant SID: PAb2c2af3650b55b53102025d50e4c7099
- Browser: Chrome 100.0.4896.58
- Device: Samsung (SM-G781V)
-  twilio-video.js: 2.21.1
-  Third-party libraries: vue.js

**Comment by charliesantos** [comment]
Hey @q-kit , thanks for reporting. Your room sids are showing ICE failures which indicates network related issues.
Are you able to reproduce this 100%?
Can you please try running these [tests](https://networktest.twilio.com/) on your affected devices and let me know the results? Try multiple runs if possible.

**Comment by q-kit** [comment]
Thanks @charliesantos for the investigation! I haven't been able to repro it as the two specific users are out of my reach. Anyway, I've implemented preflight test with the [Preflight API](https://www.twilio.com/docs/video/troubleshooting/preflight-api) in the hope of catching this kind of issue before it happens in the future. By the way, are the room logs that you checked available to the SDK users like me?

**Comment by charliesantos** [comment]
Hi @q-kit , that's right. Preflight API should help.
Not all the room logs on the server are available on the SDK. But we do log ICE failures on the console. https://github.com/twilio/twilio-video.js/blob/master/lib/signaling/v2/peerconnection.js#L816
