### ISSUE TITLE
Cause of video shut-off

### ISSUE THREAD

**Issue by taylor1791** [twilio/twilio-video.js#1757]
- [X] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [X] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [X] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [X] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii) or sensitive account information (API keys, credentials, etc.) when reporting this issue.

We have users in low-bandwith environments and we want to provide them with the best experience possible. To that end, we set `trackSwitchOffMode: "detected"` and `clientTrackSwitchOffControl: 'auto'` in our application. When the user's downlink bandwidth is insufficient, video tracks begin to shutoff. Great! To help the user understand what is happening, we wanted to inform them when track switch off occurs due to insufficient downlink bandwidth. However, as far as I can tell there is no way to establish why a track was shutoff. It could be shutoff due to at least these reasons (there are probably more):

 * The participant’s downlink bandwidth is insufficient.
 * The participant switched tabs on a desktop browser or backgrounded the mobile browser.
 * The video tag is no longer visible on the screen.

Is there anyway to establish that a video track was turned off due to insufficient downlink bandwidth?

**Expected behavior**: A way to tell why video was shutoff.
**Actual behavior**: We are given the track that was shutoff.

**Software versions:**

 - [X] Browser(s): All
 - [X] Operating System: All
 - [X] twilio-video.js: 2.21.1
 - [X] Third-party libraries: Not relevant.

**Comment by charliesantos** [comment]
Hi @taylor1791 , thanks for the report. We currently don't support this feature. However, it will be supported in 3.x version.
I will close this now since there is no further action needed from us. But please feel free to follow up!

**Comment by charliesantos** [comment]
@taylor1791 please check [this](https://github.com/twilio/twilio-video.js/tree/feature/large-rooms-pilot) out.
Also, please note that this is a work in progress and we don't have an ETA yet for this feature. You can watch this repo for future updates.

**Comment by vuongdv-spinshell** [comment]
Hi @charliesantos How about this feature? I'm facing the same problem. Do you already have ETA for this feature?
