### ISSUE TITLE
[Question] Can I catch local media track error?

### ISSUE THREAD

**Issue by q-kit** [twilio/twilio-video.js#1758]
While doing some tests on Chrome, I noticed that I can block the access to camera and microphone while local video track and local audio track are enabled, then in the dev tool console, I saw error messages like "Failed to re-acquire the MediaStreamTrack..." (which seems to be logged by `LocalMediaTrack._restart` at [this line](https://github.com/twilio/twilio-video.js/blob/664d6e222ca9e7c73355696cc2b53178ebfb691c/lib/media/track/localmediatrack.js#L172)) and "failed to restart track..." (which seems to be logged by `maybeRestart` at [this line](https://github.com/twilio/twilio-video.js/blob/664d6e222ca9e7c73355696cc2b53178ebfb691c/lib/media/track/localmediatrack.js#L325)). It seems that the `maybeRestart` function just logged the error, but does not throw it. I'm wondering if it's possible for me to catch the error for customized handling. I thought that there might be an event for error in local media track, but, as far as I can see, the available events for local media track are `disabled`, `enabled`, `started`, `stopped` and `dimensionsChanged` (only for LocalVideoTrack), none of which seems to be related to error.

Please suggest. Thanks!

**Comment by charliesantos** [comment]
Hey @q-kit , thanks for the question. I believe if you block the access to the device, the browser will ask to reload the page. Therefore, you won't hit this path. But I'm interested on how you're triggering this path. Can you please provide exact repro steps?

**Comment by q-kit** [comment]
Hello @charliesantos,

Thanks for the reply!

When I have my selfie video on Chrome, I saw that a camera button at the right end of the address bar, as shown by the screenshot below. If you click on the camera button, you will see the options for always block camera and microphone access. If you select it and click the Done button, the selfie video will turn to a black screen, and the error messages would be printed in the console of dev tool.
<img width="130" alt="Screen Shot 2022-04-21 at 4 04 28 PM" src="https://user-images.githubusercontent.com/87209197/164570505-a55171e5-3a94-43c3-b31b-32b2929aaa19.png">

Hope this helps.

Q

**Comment by charliesantos** [comment]
Hey @q-kit , thanks for the additional information. Currently, you cannot catch that specific error with this use case. But we will consider it.

**Comment by q-kit** [comment]
Thanks @charliesantos! For now, could you suggest the best practice that ensures the users' media tracks are always enabled and published? This is very import for my use cases.

**Comment by tmb** [comment]
You can't catch them but you might be able to act based on the logs (if they're in the main logger, which I am unsure of here). Details are buried https://www.twilio.com/blog/troubleshooting-twilio-video-app under "Data collection tools for troubleshooting"
