### ISSUE TITLE
iOS 11 safari crash the phone on createLocalTracks 

### ISSUE THREAD

**Issue by theDude30** [twilio/twilio-video.js#176]
- [X ] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [ X] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [X ] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.

**Code to reproduce the issue:**
var   constraints={
                video: true,
                audio: true
            }
 Twilio.Video.createLocalTracks(constraints).then(function(localTracks) {
            currentLocalTracks=localTracks;
            var localMediaContainer = document.getElementById('localVideo');
            localTracks.forEach(function(track) {
                localMediaContainer.appendChild(track.attach());
                twRoom.localParticipant.addTrack(track);
            });
        });

** Issue Description:**
We tried group and P2P.
The issue refers to GROUP and we managed to get the following working:
1. connect to room.
2. receive participant audio and video.

When we tried on P2P, it completely did not work and did not crash.

**Expected behavior:**

When user clicks to start audio video, the phone should prompt to allow camera/microphone.

**Actual behavior:*

The phone completely crashed and we had to do hard reset after each test.

**Software versions:**

 - [X ] Browser(s): Safari 11, Chrome 61.0.3163.100
 - [X ] Operating System: iOS 11,MAC OSX 10.12.6
 - [X ] Device: iphone 6 plus.
 - [X ] twilio-video.js: Using the latest from CDN:
//media.twiliocdn.com/sdk/js/video/v1/twilio-video.min.js
 - [X ] Third-party libraries (e.g., Angular, React, etc.): None

**Comment by markandrus** [comment]
Thanks for the report, @theDude30. We will try to reproduce on our end. Can you please tell me how far you were able to get in P2P? For example, did you fail immediately when requesting audio/video? Or did you fail when connecting to the Room? Do you have a Room SID you could share?

Thanks,
Mark

**Comment by theDude30** [comment]
I can confirm that the following works well:
* Connecting to a room(P2P).
* receiving audio/video stream from peer.

Once i try to start localTrack it immediately freezes the safari and crash the entire phone.

**Comment by theDude30** [comment]
I've identified the issue.It appears that safari does not allow to getusermedia or anything related to webRTC from within an IFRAME.
The phone totally crash when you try to getusermedia from IFRAME, i would recommend that you will block this option if you identify safari+IFRAME and just show error message.

**Comment by jfols** [comment]
I'm experiencing a similar iOS crash on iOS 11 Safari on iPhone 7

`twilio-video` v1.5.1 via npm + P2P room + react

It seems the crash occurs when I trigger a scroll event on iOS Safari, which seems to trigger the `VideoTrack` [onresize](https://github.com/twilio/twilio-video.js/blob/6ebf77a7b6867dbb097b7a6cd3a3e2331b32be63/lib/media/track/videotrack.js#L58) callback. This is just a guess from looking at the Safari remote device profiler recording.

When the crash occurs the iOS Safari Video track continue to successfully send to other peers, however iOS/the phone is generally unresponsive, the display is unresponsive, the lock button dims the screen but does not lock the device.

The iOS Safari audio track is logged as connect on participant (chrome/firefox on macOS) devices, however no audio is played.

**Comment by acoolprogrammer123** [comment]
This is potentially related to this webkit bug:  https://bugs.webkit.org/show_bug.cgi?id=176439

There are two other threads on this repository asking about this same issue:
https://github.com/twilio/twilio-video.js/issues/189
https://github.com/twilio/twilio-video.js/issues/192

**Comment by jfols** [comment]
iOS 11.1 beta 5 seems to clear this up for me, likely something in Safari and now `twilio-video`

**Comment by markandrus** [comment]
[Youenn mentions](https://bugs.webkit.org/show_bug.cgi?id=176439#c23) that iOS 11.2 beta may have fixed this.

**Comment by markandrus** [comment]
AFAICT, iOS 11.2 did indeed fix this. Closing.
