### ISSUE TITLE
Should use globalThis instead of global

### ISSUE THREAD

**Issue by davbrito** [twilio/twilio-video.js#1762]
The `global` object is available on node but not in browser environments. so you should use the [`globalThis`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis) object instead, which is the standard way to reference the global object on every environment.

https://github.com/twilio/twilio-video.js/blob/352ebf3e1d85aacdf4a888ba8a99e4ab37465131/lib/twilioconnection.js#L64

**Comment by davbrito** [comment]
I think this is solved by #1752 . Am I right?

**Comment by makarandp0** [comment]
Yep. Should be released soon

**Comment by makarandp0** [comment]
Hello @davbrito - This is released as part of [2.21.2](https://github.com/twilio/twilio-video.js/releases/tag/2.21.2), Thanks again for the tip!
