### ISSUE TITLE
Signaling Connection Timed Out

### ISSUE THREAD

**Issue by q-kit** [twilio/twilio-video.js#1763]
We recently noticed that two users got disconnected due to signaling connection timed out. It seems that the disconnection occurred silently and the users didn't notice that since their local selfie videos were not interrupted. Our app actually has an event handler that does reconnection on room disconnected, but reconnection actually didn't happen in those two cases. Could you please help with further investigation? Below are the users' room info. Thanks!

_User 1_

* Room SID: RM4b602b5285c702f53c9d620a5be589cb
* Participant SID: PA26e9ae51f9a8b25002d192c9168db987
* Browser(s): Mobile Safari 15.4
* Operating System: iOS 15.4.1
* twilio-video.js: 2.21.1
* Third-party libraries (e.g., Angular, React, etc.): vue.js

_User 2_

* Room SID: RM88c4883a7e9eea1a70ec19f5c12147f5
* Participant SID: PA5fc358e5aa263a107423f081ce3a9ffe
* Browser(s): Mobile Safari 15.4
* Operating System: iOS 15.4.1
* twilio-video.js: 2.21.1
* Third-party libraries (e.g., Angular, React, etc.): vue.js

**Comment by kimey-robertson** [comment]
Hi, did anyone find a solution to this? Or any helpful information anybody found out? Much appreciated
