### ISSUE TITLE
preferredVideoCodecs: 'auto' causes error in v2.21.1

### ISSUE THREAD

**Issue by nickjgentile** [twilio/twilio-video.js#1765]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

If I set my preferredVideoCodecs connect option to 'auto', I get errors and the A/V streams break.

I am setting my preferredVideoCodecs to 'auto' as it is a recommended workaround to another unresolved issue, https://github.com/twilio/twilio-video.js/issues/1738. 

```js
    var room = await Video.connect(token, {
      name: data.roomName || uuid(),
      dominantSpeaker: true,
      tracks: preSetTracks,
      preferredVideoCodecs: 'auto',
      bandwidthProfile: {
        video: {
          mode: 'collaboration',
          trackSwitchOffMode: 'detected',
          maxSubscriptionBitrate: 2400000,
          dominantSpeakerPriority: 'standard',
          maxTracks: 25, // default logic = activity, when a track stops there is a track switchoff event to queue off of
          renderDimensions: {
            high: {
              width: 1920,
              height: 1080,
              framerate: 10
            },
            standard: {
              width: 640,
              height: 360
            },
            low: {
              width: 640,
              height: 360
            }
          }
        }
      },
      maxAudioBitrate: 16000,
      preferredVideoCodecs: 'auto'
    })
```

**Expected behavior:**
Works with preferredVideoCodecs: 'auto'. 

**Actual behavior:**
I receive the following error `TwilioError: Client is unable to apply a remote media description` and the A/V streams dont come through.

If I set the  preferredVideoCodecs property to what I had previously, I no longer receive this error and everything works, but my screenshare quality is still poor. See previous config below: 

```js
      maxAudioBitrate: 16000,
      preferredVideoCodecs: [
        {
          codec: 'VP8',
          simulcast: true
        }
      ]
```

**Software versions:**

 - [x] Browser(s): 100.0.4896.88 (Official Build) (x86_64) 
 - [x] Operating System: MacOS Monteray v12.0.1
 - [x] twilio-video.js: Installed via NPM, v2.21.1
 - [x] Third-party libraries (e.g., Angular, React, etc.): Project is using Vue.

**Comment by makarandp0** [comment]
Hello @nickjgentile, Thank you for reporting this issue.
 
I tried to join a room with a video and audio track using the connect options you provided, but did not see any issue. Can you provide more details.

When do you see this error? Do you see at connect time, or later ? 
Are you trying to connect a P2P room or Group room? 

Please share console logs and any room sids to help debug this further. 

Thanks,
Makarand

**Comment by nickjgentile** [comment]
@makarandp0 Thanks for the reply, here are some responses to help:

I see this error in the browser-console when I attempt to connect to the room, so at connect time.
I am connecting to a group room.

Here is a room SID where a user received that error upon connecting to the room: `RM8a5eab98eeed8f149c3dbe9f974021f4`.

**Comment by makarandp0** [comment]
Hello @nickjgentile, Thank you for providing the room sid - I looked at the room and I see that there were two participants connected to the room

```
PA8c6707ae618bd21868f5fed621400acb connected with SDK version 2.7.2 from Chrome 100.0.4896
PAced184680e7c89bfe3acc73b35fbf84a connected with SDK version  2.21.1 on  Chrome 100.0.4896 
```

Did you see this error when connecting `PAced184680e7c89bfe3acc73b35fbf84a` ? From our logs I see one possibility - This could happen if video track of the participant was in 'ended' state when connecting to the room (VIDEO-9511).  Does your application try to publish a stopped track or stop the track while `connect` is ongoing by any chance?  Can you share console logs - that would help clarify this question. 


Thanks,
Makarand

**Comment by nickjgentile** [comment]
Hey @makarandp0 

Here is how we are getting/configuring/manipulating the tracks before we connect to a room:

```    let localTracksConfig = {}

    if (data.videoInputDeviceFound) {
      localTracksConfig.video = {
        deviceId: data.videoInput || 'default',
        height: 360,
        width: 640,
        aspectRatio: 1.777777778
      }
    }

    if (data.audioInputDeviceFound) {
      localTracksConfig.audio = {
        deviceId: data.audioInput || 'default'
      }
    }

    MediaDeviceManager.setAudioOutput(data.audioOutput)

    var preSetTracks = await Video.createLocalTracks(localTracksConfig)

    var preSetVideoTrack = preSetTracks.find(track => track.kind == 'video')
    let constraints = {
      width: { min: 1280 },
      height: { min: 720 },
      aspectRatio: 1.777777778
    }
    // fix for firefox stream dimensions, FF only supports some dimension sets
    if (navigator.userAgent.toLowerCase().indexOf('firefox') > -1) {
      preSetVideoTrack.mediaStreamTrack.applyConstraints(constraints)
    }

    if (data && data.videoHidden && data.videoInputDeviceFound) {
      var videoTrack = preSetTracks.find(track => track.kind == 'video')
      videoTrack.mediaStreamTrack.stop()
      videoTrack.mediaStreamTrack.enabled = false
    }

    if (data && data.micMuted && data.audioInputDeviceFound) {
      var audioTrack = preSetTracks.find(track => track.kind == 'audio')
      audioTrack.mediaStreamTrack.enabled = false
    }```

So yes, in some instances we may be connecting with a video track that has had stop() called on it. We have a preview modal that they set their mute/hide video/device options before they connect, so this is to allow users to come into a room with their audio muted/video hidden. We haven't had any issues with this setup prior to updating the connect configuration to include `preferredVideoCodecs: 'auto'` however. 

I did just test an instance where I don't mute my audio/hide my video before connecting (I usually do when testing this application so I don't get audio feedback as it requires me to connect two instances) and it did work, so I think you're right that it is the stopped track causing issues.

**Comment by nickjgentile** [comment]
@makarandp0 our issue with just calling `videoTrack.mediaStreamTrack.enabled = false` on the track is that the device's video-active light (the little light next to your webcam that indicates that your camera is on) stays on unless the track has `stop()` called on it, so it is confusing for our clients. So I don't believe taking the stop() call off of the track is an option for us at the moment.

**Comment by makarandp0** [comment]
Thanks @nickjgentile, Thats a valid concern with 'disable'ing the track. For now I would suggest instead of publishing a stopped' track publish the track only when user chooses to enable it. This issue with stopped track will be fixed in next SDK release.

**Comment by makarandp0** [comment]
Hello @nickjgentile. This issue is now be fixed in the [latest release](https://github.com/twilio/twilio-video.js/releases/tag/2.21.2). Please try it out.
