### ISSUE TITLE
Call to getUserMedia failed (React + video)

### ISSUE THREAD

**Issue by CarlosUvaSilva** [twilio/twilio-video.js#177]
i'm trying to implement a React App with video chat,

when i'm connecting to a room I get a "Call to getUserMedia failed" error but the error's message comes back empty so i don't really understand what's my problem.

<img width="1203" alt="screen shot 2017-09-27 at 16 49 55" src="https://user-images.githubusercontent.com/6827956/30923523-fa955c74-a3a3-11e7-9378-6aebfe674691.png">

this is my code:
```
Twilio.connect(token, { name: `room0`, logLevel: 'debug' }).then(function (room) {
      function attachParticipantTracks(participant, container) {
        var tracks = Array.from(participant.tracks.values());
      }
    });
```
thanks for any help

**Comment by manjeshbhargav** [comment]
@CarlosUvaSilva ,

Thanks for writing in. I'm assuming from the image that you've attached that you're running the app on Mac OS using Chrome. Let me know if that indeed is the case. Also, are you serving your app on a locahost server?

[This post](https://stackoverflow.com/questions/43919639/what-is-a-trackstarterror) given more information about the error you're seeing.

**Comment by CarlosUvaSilva** [comment]
Hello @manjeshbhargav 
Yes, i'm using Chrome with MacOS, and yes i'm "hosting" locally

**Comment by manjeshbhargav** [comment]
Hi @CarlosUvaSilva ,

Thanks for the clarification. Is it possible for you to publish your app somewhere (ex: Heroku) so that I can play around with it?

Thanks,

Manjesh Malavalli
Video JavaScript Team

**Comment by CarlosUvaSilva** [comment]
@manjeshbhargav hello, i fixed the problem now. thanks for the help

**Comment by nafisahmedkhan9** [comment]
Can you please tell me was the problem you face indetail. i am also getting same error

**Comment by joshuapinter** [comment]
For anybody else, it was likely a insecure issue. `getUserMedia` throws an error unless the URL uses HTTPS or it's `localhost`. 

Read more about it and some solutions [here](https://stackoverflow.com/a/58090783/293280).

**Comment by razinazam** [comment]
> @manjeshbhargav hello, i fixed the problem now. thanks for the help

Kindly tell me How to resolve the problem ?
Thank!

**Comment by manjeshbhargav** [comment]
Hi @razinazam ,

Please see [this comment](https://github.com/twilio/twilio-video.js/issues/177#issuecomment-534838673) for more details.

Thanks,

Manjesh Malavalli
JSDK Team
