### ISSUE TITLE
LocalParticipant disconnected when RemoteParticipant leaves

### ISSUE THREAD

**Issue by stoffiz** [twilio/twilio-video.js#1770]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Description of problem:**
When in peer-to-peer call and one participants leaves, the other participants first gets the event 'reconnecting' with error message 'Media activity ceased'  and the after a few seconds gets the event 'disconnected' with same error message. 

We've had this issue for a couple of years but only on the reconnecting event so we could just ignore it. But now we're actually getting disconnected from the room and it's causing major problems.

When testing this in a group room it works as expected with no problems. Seems like this person had the same problem: https://github.com/twilio/twilio-video.js/issues/1698 but we are experiencing it on chrome to chrome.

**Steps to reproduce:**
1. Join p2p room with two participants A and B.
2. Close browser for participant B.

**Expected behaviour:**
Participant A is still in the room when participant B has left the room.

**Actual behavior:**
Participant A gets disconnected from the room when participants B leaves the room.

**Logs:**
https://pastebin.com/79H77Xcw

**Software versions:**

 - [X] Browser(s): Chrome 100.0.4896.127] (but have got it for multiple versions)
 - [X] Operating System: Windows and macOS latest
 - [X] twilio-video.js: 2.21.1
 - [X] Third-party libraries (e.g., Angular, React, etc.): none

**Comment by PikaJoyce** [comment]
Hi @stoffiz,

Thanks for submitting this issue. This is currently a known issue and being tracked in this [issue](https://github.com/twilio/twilio-video.js/issues/1725). When we have updates, we will post on that thread! For now, I'll be closing this issue so please keep track of progress there. 

Best,
Joyce
