### ISSUE TITLE
A question about track.isStarted option

### ISSUE THREAD

**Issue by hailie-rei** [twilio/twilio-video.js#1777]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

 - [x] Browser(s): all
 - [x] Operating System: all
 - [x] twilio-video.js: 2.21.1
 - [x] Third-party libraries (e.g., Angular, React, etc.): none
 

Hi Twilio team,

Thank you for your product, it's enjoyable to use.

We have one question though, how to use option of the video track named isStarted.

Our flow is the following:
We have a lobby where all participants are shown. We have a host with high video track priority and players with low video track priority. Because our users have a slow internet connection, we show a spinner before a video track appears. We use the following code to handle it:
- we store the Twilio room object in a variable:
```
import {connect} from "twilio-video";
globals.twilioRoom = await connect(token, connectOptions);
```

- an event for a participant when the track is started:

```
    participant.on('trackStarted', publication => {
        if (participant.identity !== globals.localParticipant.identity && publication.kind === 'video') {
            hideRemoteParticipantSpinner(participant.identity);
        }
    });
```
- if the track is started during rendering, we hide the spinner as well:
```
    participant.tracks.forEach(publication => {
        _publishedTrack(publication, participant);
    });

    // Handle theTrackPublications that will be published by the Participant later.
    participant.on('trackPublished', publication => {
        _publishedTrack(publication, participant);
    });

function _publishedTrack(publication, participant) {
    if (publication.track) {
        _attachTrack(publication.track, participant);
    }
    // subscription only for remote
    if (participant.identity !== globals.twilioRoom.localParticipant.identity) {
        if (publication.track && publication.track.kind === 'video' && publication.track.isStarted) { // THIS LINE
            hideRemoteParticipantSpinner(participant.identity);
        }
        if (!publication.isSubscribed) {
            publication.on('subscribed', track => {
                _attachTrack(track, participant);
            });
            // Once the TrackPublication is unsubscribed from, detach the Track from the DOM.
            publication.on('unsubscribed', track => {
                _detachTrack(track, participant);
            });
        }
    }
}

```

It works great. But then we change our template and render participants again (without refreshing the page). During this rendering, the spinner is hidden immediately because `publication.track.isStarted` is equal to `true` (the track was started earlier). So our participants experience just a blank template instead of the video. If the internet speed is slow (like we have), the delay is big, and our users are confused. 

Do you have any recommendations on how we can re-read option `isStarted` if possible, or other recommendations for the case when re-rendering of participants takes place?

Thank you in advance!

**Comment by hailie-rei** [comment]
Hi @makarandp0,
Thank you for your reply. Yes, during the re-rendering, I attach tracks, but for a reason, I can see a delay between attaching the track and the actual video appearing. That's why we show spinners. I don't understand why I see the delay when the track is already started.

**Comment by makarandp0** [comment]
Hello @hailie-rei, what [connection options](https://media.twiliocdn.com/sdk/js/video/releases/2.21.1/docs/module-twilio-video.html#.connect__anchor) does your application use to connect to a room ? Can you share a room-sid.

How much of the delay do you see when re-rendering? If you are specifying `clientTrackSwitchOffControl: "auto"` as one of your [bandwidth profile option](https://media.twiliocdn.com/sdk/js/video/releases/2.21.1/docs/global.html#ClientTrackSwitchOffControl__anchor),  then SDK will switch off Remote Tracks as they are detached from the DOM. But shouldn't take more than a second for it to start streaming once its attached to video element again.

**Comment by hailie-rei** [comment]
Hi @makarandp0 ,
I use these options:

```
        audio: true,
        video: {
            aspectRatio: 1,
            facingMode: "user",
            deviceId: globals.localOptions.cameraDeviceId,
        },
        bandwidthProfile: {
            video: {
                width: 256,
                height: 256,
                trackSwitchOffMode: 'predicted',
                mode: "collaboration",
                contentPreferencesMode: 'manual',
            },
        },
        preferredVideoCodecs: [{codec: "VP8", simulcast: true}],
        dominantSpeaker: true,
        networkQuality: {local: 3, remote: 3},
```

So I can try to use manual value for `clientTrackSwitchOffControl ` option? It takes more than a second for us to receive the streaming track.

**Comment by hailie-rei** [comment]
Instead of using the re-rendering process, we decided to use `detach` and `appendChild` js functions. I'm closing this issue.
@makarandp0 Thank you for your help
