### ISSUE TITLE
Error: Error in connection establishment.

### ISSUE THREAD

**Issue by taubancam1995** [twilio/twilio-video.js#179]
![selection_067](https://user-images.githubusercontent.com/25761022/31000586-dbf2b8c0-a506-11e7-9469-bf71be5446b5.png)
Sometimes I get this error(Chrome 61.0.3163.100) when connecting to the room
I want to know the cause and how to fix it. Thanks

**Comment by manjeshbhargav** [comment]
Hi @taubancam1995 ,

I'm closing this issue since this was opened more than 2 years ago. It looks like you are having DNS name resolution issues. Please feel free to re-open if you are still having this problem.

Thanks,

Manjesh Malavalli
JSDK Team
