### ISSUE TITLE
Microsoft Edge not receive a remote video

### ISSUE THREAD

**Issue by mnesrine** [twilio/twilio-video.js#180]
**Browser affected**
Microsoft Edge 40.15063.0.0
Microsoft EdgeHTML 15.15063

**Twilio video**
Version  twilio-video.js 1.3.0

**Description**
I test a simple example of video call with twilio-video.js, it work just a fine in Firefox-Firefox and Firefox-Chrome and Chrome-Chrome. 
However for Microsoft Edge, the local video is triggered, but I not receive the remote video and I got this error:
`script5022 InvalidAccessError
twilio-video.min.js 102,9113`

**Comment by markandrus** [comment]
Hi @mnesrine,

Thanks for the report, unfortunately we are not yet supporting Microsoft Edge. Please follow along in https://github.com/twilio/twilio-video.js/issues/94—we will keep that thread up-to-date with our plans to support Edge.

Best,
Mark
