### ISSUE TITLE
[Question] Catch "Ringing" event at web?

### ISSUE THREAD

**Issue by vinaysomawat** [twilio/twilio-video.js#1805]
I need to show the 'Ringing...' text on the web if the target starts ringing for that I need to capture the ringing event somewhere.

Here is my function:
```
registerRoomEvents(room: Video.Room) {
    room
      .on('participantConnected', this.addParticipant)
      .on('participantDisconnected', (participant) => {
        this.removeAwaitingParticipant(participant.identity);
      })
      .on('disconnected', this.onRoomDisconnection)
      .on('dominantSpeakerChanged', this.onDominantSpeakerChanged);
  }
```

Please tell me how can I capture the ringing event?

**Comment by charliesantos** [comment]
Hi @vinaysomawat , thanks for the question. I'm not sure if I understand your use case. We don't have a concept of "ringing" for a "target". All participants connects and "meet" in a "room". If by "ringing" you meant something similar to "loading", we can definitely do that and I can provide some guidance. But please tell us at what point you want to show "loading" or some kind of a message.

Here's an example workflow:
Participant A initiates connecting to a room. While connecting, show a "connecting" message and hide it once connected.
Participant B initiates connecting to a room. While connecting, show a "connecting" message and hide it once connected.
The "connect" method returns a promise that resolves once you are successfully connected to the room.

In which point in this example did you want to show the "ringing" text?

**Comment by vinaysomawat** [comment]
I tried to show the "ringing" text when the target application start getting notifications for the call.

But thanks, I got the answer.
