### ISSUE TITLE
undefined device width/height results in error: Client is unable to create or apply a local media description

### ISSUE THREAD

**Issue by nrotstan** [twilio/twilio-video.js#1806]
- [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

We're using v2.21.1

We are occasionally seeing the error "Client is unable to create or apply a local media description" (or sometimes a remote media description) in Chrome. In trying to investigate, it appears this occurs when no width or height is available on the MediaStreamTrack.getSettings(). In the `_updateEncodings` function in `peerconnection.js`, when attempting to determine which `activeLayersInfo` to use, it compares against `width * height`. If either of those are undefined, that will result in `NaN`, which will always be false when compared against the pixel values in `pixelsToMaxActiveLayers`. That means no layer info is assigned, and then an error gets generated when attempting to access the `maxActiveLayers` field. That exception seems to ultimately get turned into a MediaClientLocalDescFailedError.

https://github.com/twilio/twilio-video.js/blob/ad2cede5ad29b191c6a934d7376b9e2544e36f5c/lib/signaling/v2/peerconnection.js#L525)

It's not clear to me why sometimes the width and height is missing from the track settings. It's very intermittent and hard to reproduce, but I have seen it occasionally with Snap camera when rapidly disabling and enabling the (published) video track over and over (i.e. muting and unmuting the video). While rare, it does seem to happen in the wild, and it results in errors in the code mentioned above.

As an aside, is there anything we should be doing to try to avoid this issue until it's fixed? I've tried ensuring we use a `min` constraint for both width and height when creating the local track, but that doesn't seem to help. Thanks.

**Comment by makarandp0** [comment]
Hello @nrotstan, This can happen if the track was in `ended` state. The `getSettings` call on stopped track returns `undefined`.  This is same as https://github.com/twilio/twilio-video.js/issues/1765. Please upgrade to [2.21.2](https://github.com/twilio/twilio-video.js/releases/tag/2.21.2) which fixes this issue.

**Comment by makarandp0** [comment]
Please reopen this if you continue to see this issue after upgrading to 2.21.2
