### ISSUE TITLE
Dimensions Change Event

### ISSUE THREAD

**Issue by CarlosUvaSilva** [twilio/twilio-video.js#181]
how do i get the change in dimensions event? 

i was trying to console.log "Twilio.LocalVideoTrackStats" after mounting the tracks and joining the room but it comes back undefined

**Comment by manjeshbhargav** [comment]
Hi @CarlosUvaSilva ,

You can use the ["dimensionsChanged" event on a VideoTrack](http://media.twiliocdn.com/sdk/js/video/releases/1.3.0/docs/LocalVideoTrack.html#event:dimensionsChanged).

**Comment by markandrus** [comment]
Hey @CarlosUvaSilva,

Did that work for you? If you still have issues, feel free to re-open this issue or open a new one.

Thanks,
Mark
