### ISSUE TITLE
Feature Request: Speech to Text

### ISSUE THREAD

**Issue by vsimeikoKG** [twilio/twilio-video.js#1814]
Is there any planning to add Speech to Text service as part of the Twilio Video product?

**Comment by PikaJoyce** [comment]
Hi @vsimeikoKG,

Thank you for opening this question with us. Short answer is, yes! It's currently on our roadmap. So for now, I'll keep this open and of course, update this thread once GA happens. Let me know if you've got any further questions!

Best,
Joyce

**Comment by vsimeikoKG** [comment]
Hi Joyce,

Thanks for the update!
