### ISSUE TITLE
IOS mobile devise video screen show a black screen

### ISSUE THREAD

**Issue by vikasshinde448** [twilio/twilio-video.js#1815]
On IOS mobile devise we are facing a problem we can not see a local and participate video is always show a black screen on both chrome and safari

its work on 
IOS and other desktop
Android mobile

**only not working on IOS mobile** 

can any one please help us to find a problem. 

TODO
**Software versions:**
 - [ ] Browser(s): chrome and safari
 - [ ] Operating System: IOS mobile devise
 - [ ] twilio-video.js: 2.21.3
 - [ ] Third-party libraries (e.g., Angular, React, etc.): React

**log screenshot are added**

 

<img width="1078" alt="Screenshot 2022-06-29 at 1 12 21 PM" src="https://user-images.githubusercontent.com/54267782/176380868-9b1440d2-c27b-4590-ab24-43df9af49f71.png">
<img width="1077" alt="Screenshot 2022-06-29 at 1 12 36 PM" src="https://user-images.githubusercontent.com/54267782/176380901-23acc537-7781-4a68-aca8-8eb43d5fac2e.png">
<img width="1077" alt="Screenshot 2022-06-29 at 1 13 02 PM" src="https://user-images.githubusercontent.com/54267782/176380910-21637465-59f3-4905-8cc8-cf083936338b.png">
<img width="1078" alt="Screenshot 2022-06-29 at 1 13 09 PM" src="https://user-images.githubusercontent.com/54267782/176380921-dec02099-b026-4180-9eba-3fe77194b268.png">

**Comment by PikaJoyce** [comment]
Hi @vikasshinde448,

Thank you for opening this issue with us and providing some of the logs.

I have a couple of questions, if you could answer them:
1. You mentioned it's working on iOS and other desktop, but not working on mobile iOS? Do you mean on a MacOS device?   Or do you mean Desktop Mode for iOS Safari? If it's the latter, what OS is this device on?
2. Could you please try out the workaround mentioned [here](https://github.com/twilio/twilio-video.js/issues/1724#issuecomment-1146448951) to see if this fixes the issue for you?

Thank you!
Joyce

**Comment by vikasshinde448** [comment]
1) its not working on iOS mobile devise but i send a log from using browser IOS mobile view on browser IOS mobile view it behave like same as mobile devise.

2) i try your suggested solution on browser IOS mobile view it's not work 

on IOS mobile devise its not working on ( chrome and safari )
other devises its working fine

please help us to figure out what was a problem

**Comment by vbabenko** [comment]
This is an annoying issue and reproduced from time to time

Room SID: RM3fe29f6671b476d5e022b28b0bfdf466
Device: iPad

In our case, it reproduced when we change the video layout from one type to another. If the user repeats manipulation again it helps to restore the video
 ```
2022-08-04T18:33:02.342Z warn [LocalAudioTrack #1: 72c5320c-d720-4299-a024-05454a26b027] Failed to detect silence: AbortError: The operation was aborted.
2022-08-04T18:33:02.343Z warn [LocalAudioTrack #1: 72c5320c-d720-4299-a024-05454a26b027] Unintentionally paused: [object HTMLAudioElement]
2022-08-04T18:33:02.344Z warn [LocalAudioTrack #1: 72c5320c-d720-4299-a024-05454a26b027] Unintentionally paused: [object HTMLAudioElement]
```

**Comment by manjeshbhargav** [comment]
Hi @vbabenko , @vikasshinde448 ,

Thanks for the updates. We will continue the investigation and get back to you soon.

**Comment by vikasshinde448** [comment]
Hi developers
we find out the problem and solve it on over side

the problem is that we are using videojs library to play steam so that library can create this problem
