### ISSUE TITLE
Feature Request: Client Side Track Subscriptions API

### ISSUE THREAD

**Issue by vsimeikoKG** [twilio/twilio-video.js#1821]
We would like to see the Track Subscriptions API supported from the client side JS SDK.

In the group call with a large amount of participants the Twilio SDK consumes way more CPU & bandwidth when compared to the AWS Chime SDK. This is primarily due to lack of track subscribe/unsubscribe feature.

**Use cases:**
- Pagination for the video tiles;
- Dynamically swapping visible & hidden participants based on the business logic prioritization;
- Slider to control number of visible tiles in the screen.

**Possible solutions:**
- Add new methods `track.subscribe()` and `track.unsubscribe()`;
- Add an option to the `connect()` config to automatically unsubscribe from all non-attached video tracks.

Unfortunately, we can't use the Track Subscription REST API as there always be some delay from the network call (~1-3 seconds). This will just give a bad user experience to our end customers.

**Comment by manjeshbhargav** [comment]
Hi @vsimeikoKG ,

The latest SDK version ensures that the hidden video tracks are switched off, and thumbnail tracks get less video bandwidth, thereby saving cpu and bandwidth. Plus, the "adaptive simulcast" feature makes sure you're only publishing the amount of video consumed by the subscriber. Please check out this [CHANGELOG.md entry](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md#new-features-2) for details.

**Comment by vsimeikoKG** [comment]
@manjeshbhargav ,

We re-enabled simulcast with bandwidth profile API and the issue is resolved for us.

Thanks.
