### ISSUE TITLE
Selecting best twilio region when location of all the participants is known in advance

### ISSUE THREAD

**Issue by genevpd** [twilio/twilio-video.js#1837]
Would it be possible to extend GLL to find the best location when we know the locations of all the participants before any of them joins? We can provide approximate latitude+longitude pairs for all of the participants.

https://www.twilio.com/docs/video/tutorials/video-regions-and-global-low-latency

> Applying these recommendations may be complex and sometimes developers prefer Twilio to select the region on their behalf. This can be achieved using GLL (Global Low Latency).

> Many times it's not possible to have prior knowledge of a participant's location. In that case, a simple rule of thumb that typically works is to select the region closest to the first Participant.

**Comment by manjeshbhargav** [comment]
HI @genevpd ,

Thanks for writing in with your question. For your use case, GLL should be sufficient. Can you let me know why the current GLL implementation is not working for you?

Thanks,

Manjesh

**Comment by genevpd** [comment]
@manjeshbhargav thanks for getting back to me! 

Here are two scenarios where I think GLL region selection can be improved if we provide latitude+longitude of every participant:
1. Five participants from Germany and one participant from Australia. In that scenario de1 is the best, but GLL can select au1. 
2. One participant from US East, one from US West, and one from Australia. us2 (West Coast) will be the most optimal, but GLL can just as likely select us1 (East Coast) or au1.

Btw, does Twilio Video use AWS Global Accelerator https://aws.amazon.com/global-accelerator/ or the traffic from every participant travels the whole distance over the internet?

**Comment by genevpd** [comment]
Hi @manjeshbhargav was this fixed or closed by mistake?
