### ISSUE TITLE
Unhandled rejection on Safari (iPad retina iOS 8.0.2 and etc)

### ISSUE THREAD

**Issue by av-k** [twilio/twilio-video.js#184]
On mobile devices (Safari), the request to receive user media data don't return anything.

![Image of bug](https://raw.githubusercontent.com/av-k/pub/master/images/twilio-video/ipad8-usermedia-bug-o.jpg)

**Comment by markandrus** [comment]
Thanks for the report @av-k—I think we should remove that `return` statement, so that, on platforms that don't support `getUserMedia`, like iOS 8, we invoke `onFailure` with the expected error. WDYT @manjeshbhargav?

**Comment by markandrus** [comment]
@av-k we release twilio-webrtc.js@1.0.2 with a fix for this. `getUserMedia` should now reject instead of hang indefinitely. If you install twilio-video.js from NPM, could you please try re-installing? Otherwise, if you use the CDN, our next release will have the latest fix.
