### ISSUE TITLE
Video source cannot be started on chrome

### ISSUE THREAD

**Issue by CyranMS** [twilio/twilio-video.js#1848]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Expected behavior:**

Chrome can access the camera.

**Actual behavior:**

We have multiple cases where Chrome cannot access the camera anymore and throws this error. We checked for all permissions, and everything is as expected. Also, nothing was changed, and it worked before. Google Meet also throws this error. Are there any reports of a chrome bug regarding this on version 
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36`
> Error: NotReadableError:Could not start video source

 Other browsers work. So this is not a Twilio issue, but I wonder if others also noticed this?

**Comment by manjeshbhargav** [comment]
@CyranMS ,

Please refer to this [guide](https://www.twilio.com/docs/video/build-js-video-application-recommendations-and-best-practices#handling-errors) for how to handle media capture errors in the application.
