### ISSUE TITLE
Dominant Speaker API does not detect local participant as speaking 

### ISSUE THREAD

**Issue by aibek-top** [twilio/twilio-video.js#1861]
I am experiencing the issue that the dominantSpeakerChanged event returns null when there are 2 users in the room, when the current (local) user is speaking and the other one is muted. The participant argument is given as nullish value.

 - [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

```js
export const useDominantSpeaker = ({ room }: { room?: Video.Room }) => {
  const isMounted = useMountedState();
  const [dominantSpeaker, setDominantSpeaker] = useState(
    room && room.dominantSpeaker
  );

  useEffect(() => {
    if (dominantSpeaker) {
      store.setState({ dominantSpeaker: identity(dominantSpeaker).id });
    }
  }, [dominantSpeaker]);

  const onDominantSpeakerChanged = useCallback(
    (participant: Video.RemoteParticipant) => {
      if (isMounted() && participant && !identity(participant).isBroadcasting) {
        setDominantSpeaker(participant);
      }
    },
    [isMounted]
  );

  useEffect(() => {
    if (!room) return;
    let unmounted = false;

    const onParticipantDisconnected = (participant: Video.RemoteParticipant) =>
      !unmounted &&
      setDominantSpeaker((prevDominantSpeaker) =>
        prevDominantSpeaker === participant ? null : prevDominantSpeaker
      );
    room.on('dominantSpeakerChanged', onDominantSpeakerChanged);
    room.on('participantDisconnected', onParticipantDisconnected);
    return () => {
      unmounted = true;
      room.removeListener('dominantSpeakerChanged', onDominantSpeakerChanged);
      room.removeListener('participantDisconnected', onParticipantDisconnected);
    };
  }, [onDominantSpeakerChanged, room]);

  return dominantSpeaker;
};
```

**Expected behavior:**

Dominant speaker API should also detect the local participant speaking the loudest in the room

**Actual behavior:**

The argument to event callback for the event dominantSpeakerChanged is null

**Software versions:**

Pilot Large Room Program is enabled for our client

 - [x] Browser(s): Chrome 104.0.5112.82 
 - [x] Operating System: Windows 10
 - [x] twilio-video.js: ^3.0.0-preview.1
 - [x] Third-party libraries (e.g., Angular, React, etc.): Next.js

**Comment by manjeshbhargav** [comment]
@aibek-top ,

This is expected behavior. The dominant speaker points to the RemoteParticipant that is active. If `Room.dominantSpeaker` is `null`, then most likely it is the LocalParticipant that is dominant. Hope this answers your question.
