### ISSUE TITLE
Mute and Unmute doesn't work as expected

### ISSUE THREAD

**Issue by JosepSalvat** [twilio/twilio-video.js#1868]
Hello, 
For some reasons, when we're in a call it works just fine. But if u mute yourself, sometimes when u unmute you, some people doesn't hear you. It's happening a lot since 1 month more or less. We didn't do any change on the code.

Call --> Mute --> Unmute --> you're still muted for some people and you've to leave the call and enter again.

**Software versions:**

 - [ Chrome] Browser(s):
 - [ Windows, Linux, Mac] Operating System:
 - [ 2.21.1] twilio-video.js:
 - [ React] Third-party libraries (e.g., Angular, React, etc.):

**Comment by JosepSalvat** [comment]
Any clue? I'm kinda lost atm

**Comment by JosepSalvat** [comment]
I'll close this issue as I found how to reproduce the bug

**Comment by Galzk** [comment]
@JosepSalvat Did you manage to reliably recreate this one?
I suspect browser version, as we had made no changes to our codebase for over 6 months and suddenly started getting reports on this bug
