### ISSUE TITLE
CRITICAL: noiseCancellationOptions overwrites mediaStreamTrack

### ISSUE THREAD

**Issue by vbabenko** [twilio/twilio-video.js#1869]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

```js
const mediaRequest = await Video.createLocalTracks({
  audio: {
    noiseCancellationOptions: {
      sdkAssetsPath: `${location.origin}/${path}`,
      vendor: 'krisp',
    },
  },
});
```

**Expected behavior:**

Returned audiotrack should belong to `navigator.mediaDevices.enumerateDevices()`

**Actual behavior:**
it's not possible to match returned track with `navigator.mediaDevices.enumerateDevices()`
The new track belongs to the `AudioDestinationNode` and `deviceId` doesn't belongs to any `enumerateDevices`

<img width="478" alt="image" src="https://user-images.githubusercontent.com/4083910/187439958-b2cb0c38-62db-464d-bb4b-b5a8618f921a.png">
<img width="581" alt="image" src="https://user-images.githubusercontent.com/4083910/187440109-9ee70eb0-131a-42b3-9992-55fd24c8e011.png">

**Software versions:**

 - [x] Browser(s): Chrome 104
 - [x] Operating System: MacOS Monterey
 - [x] twilio-video.js: 2.24.0
 - [x] Third-party libraries (e.g., Angular, React, etc.): Vue.js

**Comment by manjeshbhargav** [comment]
Hi @vbabenko ,

Thanks for writing in. As of now, this is expected since the original MediaStreamTrack acts as the source for the noise cancellation module, which outputs a new MediaStreamTrack. If you are dependent on the human-readable label in your UI, you can pass a `name` property in the options for creating a track. Please let me know if this works for you.

**Comment by vbabenko** [comment]
`name` property doesn't work for our case. We use `deviceId` to match the existing `MediaStreamTrack` with all available devices (`navigator.mediaDevices.enumerateDevices()`)
This doesn't work since the noise cancellation module returns a completely new track that doesn't match any existing devices...
I do not know how devs can identify a device by source id if they use noiseCancelling solution, it brokes basic logic...

**Comment by manjeshbhargav** [comment]
Hi @vbabenko ,

We have opened an internal ticket to work on this. Please watch this space for updates. In the meantime, if you want to show which default device is being used, you can use [`navigator.mediaDevices.enumerateDevices()`](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/enumerateDevices) to access the default device info.

**Comment by vbabenko** [comment]
@manjeshbhargav thank you!
I will keep eye on this issue. 
I am really interested in your new noise-canceling solution. I've tested it internally and the quality is quite impressive!
> if you want to show which default device is being used, you can use [navigator.mediaDevices.enumerateDevices()](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/enumerateDevices) to access the default device info.

yep, it's exactly what I do now and it's a reason of this ticket that with noise-canceling solution I cannot identify used device...

**Comment by makarandp0** [comment]
@vbabenko, noiseCancellation does overwrite the LocalAudioTrack.mediaStreamTrack, but it does store original track in [LocalAudioTrack.noiseCancellation.srcTrack](https://github.com/twilio/twilio-video.js/blob/master/lib/media/track/noisecancellationimpl.ts#L87). Does that help in identifying the device used?

**Comment by vbabenko** [comment]
Hi @makarandp0 ,
Thank you for the update! 
This might help, let me test this solution and I will come back to you with the results

**Comment by vbabenko** [comment]
@makarandp0 thank you for your help!
`LocalAudioTrack.noiseCancellation.sourceTrack` works and returns all needed information!
