### ISSUE TITLE
Ionic or Angular example?

### ISSUE THREAD

**Issue by stojankukrika** [twilio/twilio-video.js#1881]
I have a problem because I can't find any angular or ionic example on google. Does anybody here like to share something to take a look at how to make a video room for participants? If someone can and want please help me :(

**Comment by vadimluminous** [comment]
https://www.twilio.com/blog/video-chat-app-asp-net-core-3-angular-8-twilio.

I'm working on this currently myself, converted the angular app into ionic, and studied the .NET API code and made a Node.js service out of it.

Works for me at the moment.

**Comment by manjeshbhargav** [comment]
Closing this issue since the angular example is available. Thanks @vadimluminous !

**Comment by stojankukrika** [comment]
@vadimluminous would you like to share with me ionic part only?

**Comment by vadimluminous** [comment]
@stojankukrika in the link I shared, they shared the github repo for the angular project - https://github.com/IEvangelist/IEvangelist.VideoChat/tree/main/ClientApp

I pretty much initialized a blank ionic project, and then just copied the files from the angular /app folder into the ionic /app folder, and then installed whichever dependencies were missing

**Comment by stojankukrika** [comment]
@vadimluminous tnx for idea!
