### ISSUE TITLE
ios 16 video orientation error

### ISSUE THREAD

**Issue by Hyeongjoon** [twilio/twilio-video.js#1882]
This is not a phenomenon in iOS 15.7, but it was caused by updating to 16. In localtrack, if i change the iPhone to landscape mode or portrait mode, it comes out exactly. 
However, when a remote participant sees an iPhone participant, changing the direction of the video does not change.

 - [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

```js
// TODO
```

**Expected behavior:**

When a remote participant changes the direction of the cell phone, the direction of the video of the remote participant that I see must change.

**Actual behavior:**

Video size, not change the direction of the iPhone to use the remote participants as it is. For example, horizontal-mode video appears to be crushed left and right due to the size of the long-length video.

**Software versions:**

 - [x] Browser(s): chrome browser
 - [x] Operating System: ios 16
 - [x] twilio-video.js: 2.22.1
 - [x] Third-party libraries (e.g., Angular, React, etc.): pure javascript

**Comment by manjeshbhargav** [comment]
Hi @Hyeongjoon ,

Thanks for writing it. I will investigate and get back to you soon.

**Comment by alexandermaisey** [comment]
Hello @manjeshbhargav is there an update on the status of this issue?  It is causing some mission-critical problems for my application.  Thank you.

**Comment by PikaJoyce** [comment]
Hello everyone,

We thank you all for your patience. We have been able to reproduce this issue on our end and have filed a ticket (VIDEO-11690) to track it. We will begin the work on this very soon. As always, we will update this thread as the ticket progresses. 

Best,
Joyce

**Comment by Hyeongjoon** [comment]
After updating to the latest iPhone version, we tested it and found that the phenomenon was resolved.

**Comment by PikaJoyce** [comment]
Hi @Hyeongjoon,

Thanks for testing it! I've also verified that it's been fixed in the latest iOS 16.1 update. I'll now be closing this issue as well as the ticket.

Best,
Joyce
