### ISSUE TITLE
The screen sharing frame rate cannot be changed

### ISSUE THREAD

**Issue by michalzaq12** [twilio/twilio-video.js#1883]
**In a video room with screen sharing, the first published video track sets a maximum frame rate that cannot be changed later.**

 - [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

Code: https://glitch.com/edit/#!/twilio-video-demo
Demo: https://twilio-video-demo.glitch.me/

**Expected behavior:**

New published video track should keep requested frame rate.

**Actual behavior:**

The frame rate of the new video track is limited by the frame rate settings of the first track.

**Software versions:**

 - [x] Browser(s): Chrome 105
 - [x] Operating System: Windows 11
 - [x] twilio-video.js: 2.24.1
 - [x] Third-party libraries (e.g., Angular, React, etc.):

**Comment by manjeshbhargav** [comment]
Hi @michalzaq12 ,

Thanks for writing in with your question. Screen share tracks behave differently from camera tracks in the sense that the frame rate changes based on what is being shared. If static content is shared (presentations, web pages), then the frame rate will be low, even though your requested frame rate is higher. If you are sharing dynamic content (youtube videos), then the frame rate will catch up to something closer to the requested frame rate. So, we always recommend that the application NOT specify the frame rate while capturing the screen. That way, the browser will manage the frame rate based on the content being shared. I hope this answers your question.

**Comment by michalzaq12** [comment]
@manjeshbhargav thanks for answer.
I understand that sometimes the required settings are unattainable, but that's not what this bug is about.
For example: We start at 24fps and everything works fine, then you can switch the track to 6fps.
But the other way around it doesn't work anymore, I start with 6 fps and then it can't be increased in any way. It looks like the first track is setting some kind of upper limit.

You can also try with other (smaller) values. It is not that the captured image is not able to obtain this quality at the moment.
