### ISSUE TITLE
While only turning off the video , sound is also getting off.

### ISSUE THREAD

**Issue by vikasshinde448** [twilio/twilio-video.js#1886]
when we off the camera audio is also stop can you please help us to resolve this problem 

**we are using following code to on off camera** 
room.localParticipant.videoTracks.forEach(async (publication: any) => {
      publication.track.disable();
});

room.localParticipant.videoTracks.forEach(async (publication: any) => {
      publication.track.enable();
});

**we are using version 2.24.1**

**Comment by vikasshinde448** [comment]
Browser(s): on every browser
Operating System: all OS
twilio-video.js: 2.24.1
Third-party libraries: React

**Comment by manjeshbhargav** [comment]
Hi @vikasshinde448 ,

Is it possible for you to deploy your app somewhere and share the link so I can play around with it? Please make sure that the Room object is available in the `window` scope so I can try some things out.

**Comment by vikasshinde448** [comment]
We find the problem is over code that create this problem. 
We fix this issue so I am closing this issue.
