### ISSUE TITLE
runPreflight - access token

### ISSUE THREAD

**Issue by michalzaq12** [twilio/twilio-video.js#1887]
I would like to use the `runPreflight` method (https://sdk.twilio.com/js/video/releases/2.20.0/docs/module-twilio-video.html#.runPreflight__anchor) to diagnose the connection. I am using Twilio helper Node.js lib to generate tokens (https://sdk.twilio.com/js/video/releases/2.20.0/docs/module-twilio-video.html#.runPreflight__anchor).

Can I generate an access token that can only be used for `runPreflight`?

**Comment by manjeshbhargav** [comment]
Hi @michalzaq12 ,

I don't think you can create a token specific for preflight, but you can set the `ttl` to a low value so that it expires pretty soon after you run the test. Does that work for you?

**Comment by michalzaq12** [comment]
@manjeshbhargav thanks for the suggestion, `ttl` should work for me.
