### ISSUE TITLE
Quick start demo freezes iPhone 6 on resize or zoom

### ISSUE THREAD

**Issue by acoolprogrammer123** [twilio/twilio-video.js#189]
- [y] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [y] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [y-ish] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.

**Code to reproduce the issue:**

https://github.com/twilio/video-quickstart-js

**Expected behavior:**

Rotate the phone to see portrait/landscape video

**Actual behavior:**
Room shared between iOS and Chrome.

When I rotate the phone or pinch zoom, the phone locks up.  I see the webpage, the video stops moving, Chrome side sees the iOS video as frozen, pinch zoom no longer works, the home button doesn't respond, the power button doesn't respond.  The only way to get back is to hard restart the phone.  As long as I don't move anything, the video keeps going, the second I zoom or rotate it completely freezes the phone.

Small edit - If I let the room run for a several minutes I have also experienced the freeze/crash, so it is not just on rotating, zooming, or scrolling, but any of those actions cause the problem almost instantly.

Would send you log files, but I am an iOS noob (got the phone yesterday), and I have not yet figured out how preserve the log when I need to hard power cycle the phone to get it to respond... sample code would be appreciated :)

**Software versions:**

iPhone 6 (A1549) factory reset yesterday and updated to 11.0.2
Safari
Twilio Video JS 1.4
Group Room - H.264

**Comment by markandrus** [comment]
There is a WebKit bug in which [Youenn mentions](https://bugs.webkit.org/show_bug.cgi?id=176439#c23) that iOS 11.2 beta may have fixed this.

**Comment by markandrus** [comment]
I will close this issue here, since I think the issue stems from the one identified on https://github.com/twilio/twilio-video.js/issues/176. We can continue to track there.
