### ISSUE TITLE
WebSocket connection to 'wss://endpoint.twilio.com/' failed:

### ISSUE THREAD

**Issue by AndreTheSpire** [twilio/twilio-video.js#1892]
im currently trying do integrate twillo video for vue so im looking some guide and found guide for that
resource: https://github.com/dongido001/VueVideoChat (for vue)
                https://github.com/dongido001/TwilioNodeServer (for the backend)
i already check that i already got the token with the correct account SSID, SID and secret
but when i connect im getting error :
WebSocket connection to 'wss://endpoint.twilio.com/' failed: 
connect	@	Transport.js?8eab:160
i have looking some fix in the internet but it didnt work, is there any good method to fix this?

**Comment by PikaJoyce** [comment]
Hello @AndreTheSpire,

Thank you for opening this issue with us. I believe we'll need some more information to help you debug some of this. A few questions:
1. Can you please plug in your credentials into the [quickstart](https://github.com/twilio/video-quickstart-js) and ensure that the application works and that your credentials are correct?
2. Can you also provide the full error in which you're getting?

Thank you,
Joyce
