### ISSUE TITLE
Need help related to aspect ratio

### ISSUE THREAD

**Issue by vikasshinde448** [twilio/twilio-video.js#1893]
I over site we need to display video in a square shape so we set a aspect ratio as 1:1 but it not working is not give the participant video in 1:1 form so please help how to get participant video in from of 1:1 (same Hight and Width)

**over code for connect to meeting is as below:**

                                        const videoRoom = await connect(accessToken, {
						audio: {
							echoCancellation: true,
							noiseSuppression: true,
						},
						video: {
							width: { min: 0, ideal: 720, max: 720},
							height: { min: 0, ideal: 720, max: 720 },
							facingMode: 'user',
							frameRate: { ideal: 15, max: 30 },
							aspectRatio: 1 / 1,
						},
					});

we use **aspectRatio** in over code but not work as we want can any one help

**Comment by PikaJoyce** [comment]
Hi @vikasshinde448 

Can you please try setting your video constraints so the min matches the maximum? Something along the lines of:
```
	video: {
		width: { min: 720, max: 720},
		height: { min: 720, max: 720 },
	},
```
You may, however need to include [adapter.js](https://github.com/webrtc/adapter) to shim apps from spec changes.

Let me know if this works!

Best,
Joyce

**Comment by vikasshinde448** [comment]
Hi @PikaJoyce 
We try your suggestion but most of time it gives OverconstrainedError

![Screenshot (2)](https://user-images.githubusercontent.com/54267782/193742248-95cc71cd-2d00-48f3-9c0b-e1b6303fc157.png)


Please help us with other solution

**Comment by PikaJoyce** [comment]
Hi @vikasshinde448 

Please try to remove the min/ideal properties so you get something like
```
	video: {
		width: 720,
		height: 720 ,
	},
```

Best,
Joyce

**Comment by vikasshinde448** [comment]
Hi @PikaJoyce 
We try your suggested solution but most of time participant video height and width are get different
