### ISSUE TITLE
Failed to set the 'direction' property on 'RTCRtpTransceiver' in Chrome, Windows

### ISSUE THREAD

**Issue by aibek-top** [twilio/twilio-video.js#1897]
Hi dear twilio-video team,

We are using Rollbar API to track errors from our users and receive following error sometimes:

```InvalidStateError: Failed to set the 'direction' property on 'RTCRtpTransceiver': Cannot set direction on a stopping transceiver.```
File webpack-internal:///./node_modules/twilio-video/es5/signaling/v2/peerconnection.js:595:39 in eval

also this one:

```InvalidStateError: Failed to set the 'direction' property on 'RTCRtpTransceiver': The peer connection is closed.```
File webpack://_N_E/./node_modules/twilio-video/es5/signaling/v2/peerconnection.js:595:29 in [anonymous]

Could you please tell us what could be the reasons for that and how to prevent this error from happening?

 - [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Software versions:**

 - [x] Browser(s): Chrome 104.0.5112, Chrome 105.0.0
 - [x] Operating System: Windows, Mac OS, Linux
 - [x] twilio-video.js: [3.0.0-preview.3](https://www.npmjs.com/package/twilio-video/v/3.0.0-preview.3)
 - [x] Third-party libraries (e.g., Angular, React, etc.): Next.js

**Comment by manjeshbhargav** [comment]
Hi @aibek-top ,

Can you share some browser logs with me? That will help me pinpoint the reason why those errors are appearing.

**Comment by aibek-top** [comment]
Hi @manjeshbhargav , are there any updates for this issue? Could you please let me know if I can help with anything else?
