### ISSUE TITLE
Possible missing null check in the library

### ISSUE THREAD

**Issue by aibek-top** [twilio/twilio-video.js#1898]
Hi twilio-video team,

Our team uses rollbar to catch client side errors, and here is the error we received in logs for one of our users:

```TypeError: null is not an object (evaluating '(r=e._dummyEl).paused') (Most recent call first)```

```
File webpack://_N_E/./node_modules/twilio-video/es5/media/track/localvideotrack.js:304:34 in [anonymous]
el = localVideoTrack._dummyEl;
File [native code] in [anonymous]
File [native code] in promiseReactionJob
```

Seems like there is a nullity check missing in the SDK, could you please check if that's correct?

 - [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Software versions:**

 - [x] Browser(s): Chrome Mobile iOS 105.0.5195
 - [x] Operating System: iOS 15.7
 - [x] twilio-video.js: [3.0.0-preview.3](https://www.npmjs.com/package/twilio-video/v/3.0.0-preview.3)
 - [x] Third-party libraries (e.g., Angular, React, etc.): Next.js

**Comment by manjeshbhargav** [comment]
Hi @aibek-top ,

Thanks for writing in with your issue. We have a release candidate (`npm install twilio/twilio-video.js#3.0.0-rc12`) that is scheduled to go out as `3.0.0-preview.4`. This version has the fix for it. Can you try it out on your end and let me know if it stops raising the error?

**Comment by aibek-top** [comment]
Hi @manjeshbhargav , 

Thank you so much for your response! Unfortunately, we don't have a specific set of actions to reproduce this issue as this issue was recorded by Rollbar API (unhandled errors catching library). In this case, I think I will wait for 3.0.0-preview.4 and then see if there is any record of this error appearing again.

**Comment by aibek-top** [comment]
Hi @manjeshbhargav , 

Thank you for your response. To my regret, we are not able to reproduce it locally, but we are going to definitely watch over the similar error events and let you know if this issue has been resolved. Could you please trigger the release of it?

**Comment by aibek-top** [comment]
Hi @manjeshbhargav ,

Hope you are well, could you please tell us if there any updates about the newest RC 3.0.0-preview.4? our team would be very happy to try new SDK version
