### ISSUE TITLE
Audio issues on iPhone, iPad, Mac. 

### ISSUE THREAD

**Issue by YuriiShyshkin** [twilio/twilio-video.js#1899]
**Problem**

The participant cannot hear other participants if he logged in by iPhone, iPad, Mac.

**Technical Details** 

Code responsible for creation and publication of a local audio track:

```
...
Twilio.Video.createLocalAudioTrack({
    name : 'Microphone'
});

twilioRoom.localParticipant.publishTrack(track, {priority : 'low'});
...
```

Code responsible for listening to audio track publication:

```
twilioRoom.participants.forEach(participant => {
    participant.on('trackPublished', publication => {
        publication.on('subscribed', track => {
            if (track.kind === 'audio') {
                const audioElement = track.attach();
                audioElement.id = participant.sid + 'audio';
                document.getElementById('remote-media').appendChild(audioElement);
            }
        });
    });
});
```

**Steps to reproduce**
1. Publish an audio track as Host;
2. As Participant receives track on iPad;
3. Participant does not hear Host;

For your convenience please use this [demo app](https://github.com/YuriiShyshkin/twilio-demo-audio-app). 

**Investigation**

After calling `track.attach();` we receive the following warn logs on participant who has audio issue:

![image](https://user-images.githubusercontent.com/115140037/194311592-5291c98a-0785-4bf8-a12d-d0e0668a096b.png)

**Additional information**

Room sid: RM5bc6299a09f5b0b328c2d8871e08cc65;
Room type: group;
JS Version: 2.24.2;
Browser: Safari, Version: 15.7;
Internet download/upload speed: 55.83/55.94Mbps.

**Questions**

Could you suggest something?
Are there any known issues regarding the problem?

**Comment by manjeshbhargav** [comment]
Hi @YuriiShyshkin ,

Are the participants on iOS (iPad and iPhone) also publishing audio? If not, then the browser will not allow the autoplaying of audio elements that play back the remote audio tracks. In that case, you need to ensure that the user clicks on a button before calling `audioElement.play()` on all the remote audio elements. Hope this helps.

**Comment by YuriiShyshkin** [comment]
Hi @manjeshbhargav,

I appreciate your feedback.

_Are the participants on iOS (iPad and iPhone) also publishing audio?_
Participants on iOS (iPad and iPhone) publish audio not when they join but after that when they turn on their microphones. So, the issue is when they join and do not turn on their microphones.

_If not, then the browser will not allow the autoplaying of audio elements that play back the remote audio tracks._
Could you share a link to a documentation?

What do you mean by "clicking on a button before calling `audioElement.play()` on all the remote audio elements"? Let's assume that we are on a call with a few participants. Should we click on each remote `audioElement` to hear somebody?

Are there any workarounds? Is that device or browser specific?
Because when a participant joins from Firefox or Chrome from Windows, there are no any issues with audio.

We have built [demo app](https://github.com/YuriiShyshkin/twilio-demo-audio-app) to reproduce the issue.

**Comment by YuriiShyshkin** [comment]
Hi @manjeshbhargav 
Could you please provide any updates?
