### ISSUE TITLE
CRITICAL: Video is not working properly in android (Chrome)

### ISSUE THREAD

**Issue by theDude30** [twilio/twilio-video.js#190]
- [X ] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [X ] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ ] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.

**Actual behavior:**

the phone receives the remote video stream and display it on screen, but the video is frozen most of the time.
When the phone is publishing the video, the video looks great in the PC but the local video on the phone also freezes and there is too much delay even for a local stream.
When using the audio/video The phone gets heated very fast and usually i need to force close the chrome in order to exit.

Important to mention is that everything worked well until a week ago.

Please note that the whole audio/video component lives inside an IFRAME.

TODO

**Software versions:**

 - [ X] Browser(s): Phone android 7 - Chrome(61.0.3163.98), OSX -Chrome (61.0.3163.100)
 - [X ] Operating System: Android 7 , OSX 10.12.6
 - [X ] twilio-video.js: latest
 - [ ] Third-party libraries (e.g., Angular, React, etc.):

**Comment by theDude30** [comment]
Problem solved.
Below is the actual issue and how i resolved it:

Environment: chrome 61.0.3163.98 Android 7 and PC Chrome.
Issue: Video is not rendering properly on the phone, video freezes or not showing.
Solution/workaround: add border-radius: 1px to the video element.
* will be fixed in chrome 62.
Link to the bug in chromium : [https://bugs.chromium.org/p/chromium/issues/detail?id=769148](url)

**Comment by markandrus** [comment]
@theDude30 thanks for including the Chromium bug!
