### ISSUE TITLE
Angular warning due to  "CommonJS or AMD dependencies can cause optimization bailouts."

### ISSUE THREAD

**Issue by thisisomar** [twilio/twilio-video.js#1900]
Hi there!

Using the latest version of the twilio-video library in an Angular 14 project (this warning occurs beginning Angular 10 fyi) - Angular throws a warning when CommonJS dependencies are being used as it can cause performance issues.

Is there a reason as to why this is using CommonJS? I can add this to a whitelist for now, but I would like to avoid doing so.

Simply importing from twilio-video causes this, like so:

**Code to reproduce the issue:**
```js
import { connect, Room } from 'twilio-video';
```

**Expected behavior:**

No warning should be returned.

**Actual behavior:**
```
Warning: example.component.ts depends on 'twilio-video'. CommonJS or AMD dependencies can cause optimization bailouts.
```

**Software versions:**

 - twilio-video.js: 2.42.2
 - Third-party libraries (e.g., Angular, React, etc.): Angular 14.2.2

**Comment by caeb92** [comment]
This message is from angular and can happen with any library, this is not specific to this twilio video library.

You can [Follow this solution](https://stackoverflow.com/questions/62592903/upgrading-to-angular-10-fix-commonjs-or-amd-dependencies-can-cause-optimizatio)

Add the reference in **angular.json** into **allowedCommonJsDependencies**

**Comment by thisisomar** [comment]
> This message is from angular and can happen with any library, this is not specific to this twilio video library.
> 
> You can [Follow this solution](https://stackoverflow.com/questions/62592903/upgrading-to-angular-10-fix-commonjs-or-amd-dependencies-can-cause-optimizatio)
> 
> Add the reference in **angular.json** into **allowedCommonJsDependencies**

Hi @caeb92 

I'm well aware of that. That is the whitelist I was referring to in my issue.

I'm asking, why is Twilio Video using CommonJS and not ES20XX? I don't see a reason for it and am reaching out to Twilio here for curiosity and the reason behind it 

P.S: Also, I do not mind submitting a PR to take care of this if this isn't intentional for the Twilio folks

**Comment by manjeshbhargav** [comment]
Hi @thisisomar ,

We have always built the SDK to generate ES5/CommonJS modules. We want to move to ES6, but it is not in our roadmap for the near future. So, I will close this issue for now. But we can continue the conversation here if you like.

**Comment by nsmithdev** [comment]
It's probably a good time to start looking at this again with the twilio-video product no longer being retired.
Below are two articles that seem relevant to the how and why.  

Ship ESM & CJS in one Package (2021)
https://antfu.me/posts/publish-esm-and-cjs

Move on to ESM-only (2025)
https://antfu.me/posts/move-on-to-esm-only

**Comment by luisrivas** [comment]
Hi @nsmithdev

Thank you for bringing this issue back to our attention! We want to confirm that we will prioritize ESM output in the next releases.

Regards,
Luis
