### ISSUE TITLE
Black video feed when blurring background.

### ISSUE THREAD

**Issue by stoffiz** [twilio/twilio-video.js#1902]
So we are experiencing some weird behaviour with our video app since we recently implemented blur functionality in the application. The thing is it works for almost everyone but for some users there seems to be some kind of weird behaviour. When a user tries to blur their video, they just see a black feed. First we thought it was something with unpublish/publish new local track but everything seem to be working as it should.   

So my question is if you’ve had any experience with this kind of behaviour? Have this issue been reported by anyone else? 

We have only been able to reproduce this issue on two Windows computers (as we know of yet) and it has also only happened in 121 calls and not multiparty.	

I’ve included some code snippets below that has most of the blur related functionality. And as I said, the weird part of it all is that it works most of the time and very few get the black feed issue. So we are having some real trouble trying to understand the problem.

**Code to reproduce the issue:**

```
public async blurVideo(): Promise<void> {
	if (!this.isFetchingModule) {
		this.getBlurProcessor()
			.then((res) => {
				state.videoProcessor = res;
				state.localVideoTrack = [];

				const tracks = state.mediaStream?.getVideoTracks();
				if (tracks == null) return;
				tracks.forEach((track) => {
					this.publishLocalStream(track);
				});
			})
			.catch((err) => {
				console.log(err);
			});
	}
}
```

```
private publishLocalStream(track: MediaStreamTrack): void {
	const localTrack = new LocalVideoTrack(track);

	if (state.videoProcessor != null) {
		localTrack.addProcessor(state.videoProcessor);
	}

	if (state.localVideoTrack != null) {
		state.localVideoTrack.push(localTrack);
	}

	this.state.patch({ localVideoTrack: localTrack });

	if (state.localVideoTrack != null && state.localVideoTrack.length > 0) {
		entangledInstance.instanceRef?.provider.updateLocalBlurStream(state.localVideoTrack);
		state.hasVideoBlurred = true;
	}
}
```

```
public async updateLocalBlurStream(tracks: LocalVideoTrack[]): Promise<void> {
        this.room?.localParticipant.videoTracks.forEach((track) => {
	        track.unpublish();
        });
    
        tracks.forEach(async (track) => {
	        setTimeout(async () => {
		        await this.room?.localParticipant.publishTrack(track);
	        }, 1000);
        });
}
```

**Expected behavior:**
When blurring video, track should be blurred.

**Actual behavior:**
When blurring video, track is instead just black.

**Software versions:**

 - [x] Browser(s): Chrome, Edge
 - [x] Operating System: Windows (when testing internally)
 - [x] twilio-video.js: Latest
 - [ ] Third-party libraries (e.g., Angular, React, etc.):

**Comment by manjeshbhargav** [comment]
Hi @stoffiz ,

Thanks for writing in. It looks like you are unpublishing/republishing the track every time you toggle the blur processor. You can just add/remove the video processor without unpublishing/republishing. Can you try that and let me know?

**Comment by stoffiz** [comment]
Thanks for the response. We'll try to implement this and evaluate if we notice any difference. I will get back to you once we know how everything is working.
