### ISSUE TITLE
codec, dimensions and frameRate (LocalVideoTrackStats) return null on Firefox

### ISSUE THREAD

**Issue by pedroGenio** [twilio/twilio-video.js#1908]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

```js
activeRoom.getStats()
      .then(statsReport => {
      console.info("statsReport", statsReport);
});
```

**Expected behavior:**

get codec, dimensions and frameRate values from [LocalVideoTrackStats](https://sdk.twilio.com/js/video/releases/2.20.1/docs/LocalVideoTrackStats.html)

Chrome:
![image](https://user-images.githubusercontent.com/30578989/196819705-9cc22198-dfc7-4228-bd3e-043e9a523625.png)

**Actual behavior:**

Firefox:
![image](https://user-images.githubusercontent.com/30578989/196819919-aa9693bc-b527-4121-bedf-cab97f4da9ce.png)

**Software versions:**

 - [x] Browser(s): Firefox 105.0.3
 - [x] Operating System: W10
 - [x] twilio-video.js: 2.24.3
 - [x] Third-party libraries (e.g., Angular, React, etc.): Angular 13.3.3

**Comment by PikaJoyce** [comment]
Hi @pedroGenio,

Thanks for opening this issue with us. 

Are you connecting to a P2P room or a group room when calling `getStats()`? This question is due to the fact that many of the supported stats are only available through group rooms. So calling it within a P2P room can leave many fields `null`.

In addition to that, some more background information. The getStats implementation is based on the [RTCPeerConnection.getStats() API](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/getStats). Some values may be returning null due to a lack of support across the various browsers. So for example, Chrome has support for codec, but Firefox does not.

From [callstats.io](https://webrtc-stats.callstats.io/) which maintains an up to date state of the implementation of the `getStats()` in both Chrome and Firefox in case you wanted to check!

Also RTCPeerConnections is not officially exposed to the developer, but if you wanted the raw stats, but you can call getStats directly on the peer connection as shown below:
```JavaScript
[...(await room._signaling._peerConnectionManager._peerConnections.values().next().value._peerConnection._peerConnection.getStats()).values()]
```

In addition to the snippet above, you can also manually check out the statistics by opening up your application, and opening another tab `about:webrtc` to view the stats of your session. 

Less related, but you can do the same in chrome as well by opening `chrome://webrtc-internals/`

Please let me know if that is helpful! 

Best,
Joyce

**Comment by pedroGenio** [comment]
Hi @PikaJoyce ,

Thank you for your reply,

Currently, we use a group room. 
It looks like on callstats.io all browser versions are pretty old. I'm not sure if, currently, the attribute "track" is still not supported but Firefox as Chrome.

Check out my _signaling, I couldn't find _peerConnectionManager._peerConnections, please correct me if I'm wrong.
![image](https://user-images.githubusercontent.com/30578989/197640003-62b312de-f66e-4d25-b88d-af643d5aae83.png)

`[...activeRoom.localParticipant.videoTracks.values()].forEach(localVideoTrack => {
          console.info("localVideoTrack", localVideoTrack);
        });`

Based on [MediaStreamTrack](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack), I don't have frame height and width.

However, looking into `about:webrtc`

![image](https://user-images.githubusercontent.com/30578989/197640364-ab5174ba-deef-48ab-a45e-02e4759f6c03.png)

How does it get the "Video Track Statistics"? Since that's what I need.

I imagine Twilio-video fetches all info only from "track" which FF doesn't support.

**Comment by pedroGenio** [comment]
Hi @PikaJoyce 

Thank you for your attention.
I have different results for different browsers.

the following image is from Chrome:
![image](https://user-images.githubusercontent.com/30578989/198415997-c5ee51d9-05dc-4ec1-8da1-509fd5b19f69.png)

the next image is from Firefox
![image](https://user-images.githubusercontent.com/30578989/198416085-d8c06c72-3668-43b6-a129-40cc66e9992d.png)


I believe there is an explanation for this and I hope you can give me.

We dont have any problem fetching the statusReport on Chrome.

Best Regards,

**Comment by PikaJoyce** [comment]
Hi @pedroGenio,

Thank you for trying it out for me! After looking into it a bit, it seems that FireFox may support frameRate. I've opened an internal ticket to track this issue (VIDEO-11881). However, I did not see any details with regards to the codec field at all.

I'll keep this thread updated as we get more information.

Best,
Joyce

**Comment by pedroGenio** [comment]
Hi @PikaJoyce 

Thank you so much for checking this.
The attributes that we need are frameRate and,
mainly dimensions ( the values that upscale since the video starts, not the static constants)
Please, let us know how to fetch those values on FF when you figure it out.

Best regards,
Pedro Elias

**Comment by PikaJoyce** [comment]
Hi @pedroGenio,

I believe you can access what you're looking for from the snippet I've sent earlier.
```JavaScript
[...(await activeRoom._signaling._peerConnectionManager._peerConnections.values().next().value._peerConnection._peerConnection.getStats()).values()].find(stat => stat.kind === 'video' && stat.type === 'inbound-rtp'); 
```
I've simply added the last bit to give you access to the object that contains some of the information you're looking for, as for frameRate, you will have to calculate that. Here's a sample of what you should see when running the snippet above: 
![image](https://user-images.githubusercontent.com/43423318/199860933-34e801cb-b895-4b24-b4dd-9f2c845478f5.png)

Below is the general formula to obtain the frame rate which is 
```
// You will need to determine how to obtain your elapsedTime in this case.
const frameRate = framesDecoded / elapsedTime;
```
After digging around some more, I've discovered how about:webrtc grabs their data and some of that information can be found here ([RTCStatsReport webidl](https://hg.mozilla.org/mozilla-central/file/tip/dom/webidl/RTCStatsReport.webidl) At line 203). Unfortunately, it does not seem like we have access to that.

I hope this was helpful,
Joyce

**Comment by pedroGenio** [comment]
Hi @PikaJoyce,

yes thank you so much,

"Find by type" finally helped me see those frame attributes on FF, it's extremely helpful.

Much appreciated.

BR,
Pedro Elias
