### ISSUE TITLE
Connection issue on iPhone 14

### ISSUE THREAD

**Issue by q-kit** [twilio/twilio-video.js#1909]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Expected behavior:**

User video should be available soon after the user joins a video room.

**Actual behavior:**

It seems that iPhone 14 takes much longer time to start streaming video. So far, this issue can be reproduced by 2 users with iPhone 14 pro max. After the iPhone 14 users join a video room, their video is shown as black screen with 0 as the `networkQualityLevel`, and it took about 30 secs for the others to see their video, which is usually robotic and in wrong resolution. My app plays a *.mp4 video simultaneously with the webRTC video, and the *.mp4 video is always frozen or even corrupted while the webRTC video is trying to get started.

I tried my app on iPhone 14 emulator as well as an iPhone 13 pro with iOS 16, and both had no issue. So it doesn't seem to be an issue with iOS 16 or Safari 16. I also tried different video codecs and reducing the resolution and FPS of the selfied video, but they didn't help.

I tested iPhone 14 with https://networktest.twilio.com, and the result shows some video group room failure with/without TURN, and it could not establish an ICE connection within 10 seconds.
![Screen Shot 2022-10-20 at 4 26 37 PM](https://user-images.githubusercontent.com/87209197/197077979-fc9fc852-6460-4f24-81bd-9816a2bd2d16.png)

Can anyone please suggest? Let me know if any more clue is needed. Thanks!

**Software versions:**

 - [x] Browser(s): Safari 16
 - [x] Operating System: iOS 16
 - [x] twilio-video.js: 2.24.3
 - [x] Third-party libraries (e.g., Angular, React, etc.): vue.js

**Comment by PikaJoyce** [comment]
Hi @q-kit,

Thank you for opening up this issue with us. I have joined a couple of video rooms with my own device (iPhone 11 Pro on iOS 16) and haven't seen any major issues with connecting via video. So I can confirm that this is likely not an issue with iOS 16 (Although there are other issues with iOS 16).

Can you please confirm if this is an issue with other applications as well such as google meets? 

Also, please test your peer connection with [the peer connection webrtc example](https://webrtc.github.io/samples/src/content/peerconnection/pc1/). Or other examples just to see if anything is acting out of the ordinary on that device?

Please let me know the results of your findings!

Thanks,
Joyce

**Comment by q-kit** [comment]
Hello @PikaJoyce,

Thanks for looking into this!

Right, it doesn't seem to be an iOS 16/Safari 16 issue since it worked well on a iPhone 13 pro with iOS 16 as I mentioned above.

As I tried with 2 iPhone 14 pro max, Google Meets works fine. [the peer connection webrtc example]( https://webrtc.github.io/samples/src/content/peerconnection/pc1/) works too, but with noticeable lag (about 5 sec) between clicking the start button and the selfied starts playing back.

Hope this helps. Please let me know your thoughts. Thanks!

Q

**Comment by PikaJoyce** [comment]
Hi @q-kit,

Thanks for getting back to me and trying those out. Could you please provide some room sids with the iPhone 14 device in the rooms? I'd love to see if there's any details in the logs.

Would it also be possible for you to revert the iPhone 14 to an older iOS version in order to see if it's a device or if it's a iOS issue. Just to confirm since we've been testing on different devices with different iOS's, but what would happen if it was the same device, on an older OS?

Thank you for your patience!

Best,
Joyce

**Comment by PikaJoyce** [comment]
Hi @q-kit,

Thank you for getting back to me with those room sids. From some initial investigation, I don't see anything going on in the room logs. The one thing I did notice was that your participant was also connecting and publishing data tracks, could you please try one last connect without data tracks on the iPhone to see if there's any issue with that?

You can do such a test using the [quickstart](https://github.com/twilio/video-quickstart-js) as well. That way, we can see if it's related to data tracks on the iPhone.

This may require some extra investigation, so I have opened an internal ticket (VIDEO-11834) to investigate further.

Thank you for testing and your patience! I'll post updates as they come along.
Joyce

**Comment by q-kit** [comment]
Hello @PikaJoyce,

Thanks for the investigation!

I just test with an iPhone 14 in my dev env without data tracks, but the same issue still happens. Below are the room SID and participant SID for your reference.

RM96cd9052bd2b3b7677b9b26f2b57892b / PA8814f21ebd5f46510b75ae38a1b6657a

Please let me know if anything is needed from my end, and keep me updated on your further investigation. Thanks!

Q

**Comment by q-kit** [comment]
Hello @PikaJoyce,

Did you have any luck with the investigation?

I did some more experiments with both iPhone 14 pro and iPhone 14 pro MAX, and noticed that this issue only happens to iPhone 14 pro MAX. Another thing I noticed is that the MAX got very hot while trying to connect. Not sure if the MAX has some unique hardware that could caused it. Hope this helps with your investigation.

Q

**Comment by PikaJoyce** [comment]
Hello @q-kit,

Thank you for updating us. I apologize for the delayed response. However, I have looked into your room sids and it does not seem that there is any issues from that end. 

The issue has not gained movement as of yet, but I will keep this thread updated if anything changes.

Best,
Joyce

**Comment by CyranMS** [comment]
@PikaJoyce also happened here RM8a4995360d752e138cf993c169615e48
