### ISSUE TITLE
Is it possible to apply noise cancellation for already existed track?

### ISSUE THREAD

**Issue by vbabenko** [twilio/twilio-video.js#1910]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

Currently, according to the documentation, if we want to use a noise cancellation solution we need to request a track with such options
```js
// Create a LocalAudioTrack with Krisp noise cancellation enabled.
const localAudioTrack = await createLocalAudioTrack({
  noiseCancellationOptions: {
    sdkAssetsPath: 'path/to/hosted/krisp/audio/plugin/dist',
    vendor: 'krisp'
  }
});

```
 **The problem:** for some users, downlaoding the model for noise canceling takes some time... For some of our users, it takes up to ~15 sec.

**Question:** Is it possible to request a track (to resolve browser permissions faster) and then apply the model to the requested track?
Something like this:
```js
const localAudioTrack = await createLocalTrack({audio: true});
localAudioTrack.connectNoiseCancellation({
    sdkAssetsPath: 'path/to/hosted/krisp/audio/plugin/dist',
    vendor: 'krisp'
})
```

**Software versions:**

 - [x] Browser(s): Any
 - [x] Operating System: Any
 - [x] twilio-video.js: 2.24.0
 - [x] Third-party libraries (e.g., Angular, React, etc.): Vue.js

**Comment by manjeshbhargav** [comment]
Hi @vbabenko ,

Thanks for the question. As of now, there is no API to do that. You could do something like this:
```js
const { createLocalAudioTrack } = require('twilio-video');

// Request audio track.
let localAudioTrack = await createLocalAudioTrack();

// Now that user has granted audio permission, recreate audio track with noise cancellation.
localAudioTrack.stop();
localAudioTrack = await createLocalAudioTrack({
  sdkAssetsPath: '...',
  vendor: 'krisp'
});
```
I'll close the issue since I've answered your question. However, feel free to continue the conversation here if you need more clarification.

**Comment by vbabenko** [comment]
@manjeshbhargav thank you for the answer!
Can you pls add this as an improvement to your pipeline? Would be nice to have such an option and apply configuration without stopping the track
