### ISSUE TITLE
A lot of participants with ICE issues / high packet loss

### ISSUE THREAD

**Issue by CyranMS** [twilio/twilio-video.js#1914]
Hi all,
recently we face a lot more issues with high packet loss and participants losing connection to ICE. Do you have more load on your servers? We are running network tests with all of our participants, and they have a great internet connection. But then during meetings, they get a lot of disconnects and freezes. On Google Meet it works fine for them. A lot of those participants are in Germany.  

Help would be very much appreciated, because we lose these users to GMeet, because they say their video conferencing is superior. Which I have a hard time believing. 

Have you ever heard this and do you have any ideas/recommendations on how to help these users? They are already doing everything that is recommended by Twilio (e.g. have strong network connection and close all other windows)

Cases:
- RMad1080b9a31f834ed2a27c454f055572
- RM59853509ca276b565f1c91033a9c99dd
- RM60fae068baebcf624c9514a1bb1163ed
- RM03875519fd093b5c0f202950631a2b7b
- RM0f80d7aed8acb2bfa7181cade0ed84d3

## Context
<img width="900" alt="image" src="https://user-images.githubusercontent.com/10713004/197867115-47e731b7-1ebb-4c5d-8206-dd855438fb1a.png">

**Comment by manjeshbhargav** [comment]
Hi @CyranMS ,

Sorry for the delayed response. Are these customers operating in a corporate firewall? I ask because, if they are, they might be operating under some rules where traffic to well-known video apps like Google Meet may be prioritized over Twilio. If they are not operating under a firewall, then it would be great if I can get some console logs from these Participants. In the meantime, I will check our media server logs to see if I can find anything.

**Comment by manjeshbhargav** [comment]
Hi @CyranMS ,

The media server logs for the Room SIDs you shared with me did not reveal any permanent ICE failures. There was only one Room with ICE failures, but the media connection recovered pretty quickly. Have you been able to reproduce this issue yourself?

**Comment by CyranMS** [comment]
@manjeshbhargav they are not behind a corporate firewall. Yes, we have seen cases where the packet loss is significant when working with Twilio but not with Google Meet. And it's people at the home office. Is there anything we recommend these people? Any router setting or something on your side that you can improve?

**Comment by manjeshbhargav** [comment]
@CyranMS ,

I investigated some more, and looks like in a lot of the rooms, after an ICE restart the available outgoing bandwidth determined by WebRTC is very low, which may explain the high packet loss. One thing you can try is to force the use of TURN server relays for media transmission by setting `ConnectOptions.iceTransportPolicy = 'relay'` for this media region. Let me know if this provides a relatively better experience.

**Comment by CyranMS** [comment]
Thank you for the recommendation, @manjeshbhargav.

Is there a possibility that this will have a negative impact for other participants?

**Comment by CyranMS** [comment]
Are there any plans on the roadmap to improve this any time soon? 
We asked a consultancy to compare us with Google Meet and they found this out. Which also aligns with what we hear from customers. With every next % of package loss - Twilio drops in quality significantly. But, take a look at Google, up to 30% of package losses and it still can deliver quality with rating of 4-5.

<img width="668" alt="image" src="https://user-images.githubusercontent.com/10713004/218798598-37c59719-7937-4c18-93bf-d33bb2957d88.png">
