### ISSUE TITLE
Stopping preflight test throws error in console

### ISSUE THREAD

**Issue by BrandonMathis** [twilio/twilio-video.js#1915]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

```js
const preflightTest = runPreflight(twilioToken);
preflightTest.stop()
```

**Expected behavior:**

Preflight test should stop gracefully

**Actual behavior:**

An error is thrown into the browser's console that makes is appear as if the preflight test failed when it was actually just stopped. There appears to be no way to control this error bubbling up into the console which causes a lot of confusion. Seems like we should be able to intercept this console error and decide to not display it if the value of `payload.error` is "Error: stopped"

**Comment by manjeshbhargav** [comment]
@BrandonMathis ,

Thanks for reporting this. Can you share the console log message that you see when you do this?

**Comment by BrandonMathis** [comment]
Sorry for the delay. Here is the message I receive on the console. Note the `error: "Error: stopped"` value. 
![Screen Shot 2022-11-22 at 3 49 26 PM](https://user-images.githubusercontent.com/362269/203418567-7aee0f95-5b70-4367-afb4-65254c3eb57a.png)
