### ISSUE TITLE
Twilio video: audio not working when krisp-noise cancelation enabled

### ISSUE THREAD

**Issue by sebastian-pathrose** [twilio/twilio-video.js#1916]
We are experiencing an issue with audio when the krisp-noise cancellation enabled:

Relevant code snippet:

navigator.mediaDevices.getUserMedia({
      video: true,
      audio: true
    }).then(async (mediaStream) => {
       const localAudioTrack = await createLocalAudioTrack({
          deviceId: { exact: deviceIds.audio },
          noiseCancellationOptions: {
            sdkAssetsPath: 'krisp-audio-plugin/dist',
            vendor: 'krisp'
         }
       }).then(async localAudioTracks => {
        // join the media with noise enabled audio and media stream-video and passing to the connect method.
        var localMediaTracks = Array.from(localAudioTracks).concat(mediaStream.getVideoTracks());
        connectOptions.tracks = [localAudioTracks, mediaStream.getVideoTracks()];
        
        // Join the Room.
        await joinRoom(token, connectOptions);
  
        // After the video session, display the room selection modal.
        return selectAndJoinRoom();

      });

Expected behavior:
Audio should work without any background voices.

Actual behavior:
When noice cancelation applied, no audio at both sides.

Software versions:
 Browser(s): Chrome android
 twilio-video.js: 2.24.3

**Comment by manjeshbhargav** [comment]
Hi @sebastian-pathrose ,

Can you try the following code snippet and let me know if it works:
```js
const { createLocalTracks } = require('twilio-video');

const tracks = await createLocalTracks({
  audio: {
    deviceId: { exact: deviceIds.audio },
    noiseCancellationOptions: {
      sdkAssetsPath: 'krisp-audio-plugin/dist',
      vendor: 'krisp'
    }
  },
  video: true
});

connectOptions.tracks = tracks;

// Join the Room.
await joinRoom(token, connectOptions);

// After the video session, display the room selection modal.
return selectAndJoinRoom();
```
**NOTE: Noise cancellation works only in group rooms.**

**Comment by manjeshbhargav** [comment]
Hi @vipulSoni458 , please do the following and see if it works:
* Install the plugin as a dependency by running `npm install @twilio/krisp-audio-plugin`.
* Host the node_modules/@twilio/krisp-audio-plugin/dist/ folder on your application server.
The `sdkAssetsPath` should now point to the path where your server hosts the krisp files.

**Comment by vipulSoni458** [comment]
Thank you @manjeshbhargav for the quick response. I will try this. Thank you

**Comment by valbeat** [comment]
The same problem was reproduced. In my case, the krisp-audio-plugin is loading correctly, but no audio is heard.

**Comment by RG-Pavithra** [comment]
I need to add the noise cancellation for the audio. Sdk Asset path showing the error and showing the errors like 1.twilioutils.js:43 Krisp noise cancellation is not available.
krisp-audio-plugin/dist/krispsdk.mjs:1 
2. Failed to load resource: the server responded with a status of 404 (Not Found)
3. log.js:167 2024-02-19T06:14:58.982Z error [createLocalTracks #1] Error loading noise cancellation sdk:krisp-audio-plugin/dist/krispsdk.mjs TypeError: Failed to fetch dynamically imported module: http://localhost:3001/krisp-audio-plugin/dist/krispsdk.mjs
export const connectToRoom = async (accessToken, roomId = "test-room", callback, cameraCallback) => {
    debugger
    const settings = localStorage.getItem('videoSettings');
    const videoSettings = settings != undefined ? JSON.parse(settings) : {}
    console.log("connectToRoom-settings", settings)
    const { selectedMic } = videoSettings
    try {
        debugger
        // const stream = await navigator.mediaDevices.getUserMedia(videoConstraints);
        let dataTack = new LocalDataTrack();
        dataChannel = dataTack;
        // Create a LocalAudioTrack with Krisp noise cancellation enabled.
        const localAudioTrack = await createLocalAudioTrack({
            deviceId: selectedMic,
            noiseCancellationOptions: {
                sdkAssetsPath: 'krisp-audio-plugin/dist',
                // sdkAssetsPath: 'path/to/hosted/krisp/audio/plugin/dist',
                // sdkAssetsPath: '/noisecancellation',
                vendor: 'krisp'
            }
        });
        console.log("localAudioTrack", localAudioTrack);
        if (!localAudioTrack.noiseCancellation) {
            // Handle case where Krisp plugin fails to load or is disabled.
            console.warn('Krisp noise cancellation is not available.');
        } else {
            debugger
            console.log("localAudioTrack", localAudioTrack, dataTack);
            // Join a Room with the LocalAudioTrack.
            const room = await connect(accessToken, {
                name: roomId,
                tracks: [localAudioTrack, dataTack]
            });
            console.log("Room", room);
            callback(room);
        }
    } catch (err) {
        debugger
        // alert("err.message  in twilio")
        console.log('Error occourred', err);
        if (err.message == "Permission denied" || err.message == "Permission denied by system" || err.message == "Requested device not found") {
            debugger
            const dataTack = new LocalDataTrack();
            dataChannel = dataTack;
            const manage = new GuestUserManager()
            const uuid = getUUID()
            const screenTrack = manage.getScreenShareStream()
            if (screenTrack.video) {
                const track = new LocalVideoTrack(screenTrack.video.mediaStreamTrack, {
                    name: uuid + 'dummy'
                })
                let tracks = [dataTack, track];
                const room = await connect(accessToken, {
                    name: roomId,
                    tracks
                });
                callback(room);
            } else {
                //navigate back with error
                console.log("navigate back with error")
                callback();
            }
        }
        if (err.message == "Participant not found") {
            console.log("err.message pt not found", err.message)
        }
    }
}
