### ISSUE TITLE
Video mute not correct perfectly

### ISSUE THREAD

**Issue by muhamedoufi** [twilio/twilio-video.js#1919]
When I make mute for twilio video with ```track.disable()```
It still  show local video.
And with the remote participiants my local video track paused only but not muted(video is not replaced by black screen)

**Comment by PikaJoyce** [comment]
Hello @muhamedoufi,

Thank you for opening this issue with us. Please follow this [quickstart example](https://github.com/twilio/video-quickstart-js/tree/master/examples/localmediacontrols). 

If you'd like a black screen, you'd have to add that yourself. In the case of the example, we [removed the element](https://github.com/twilio/video-quickstart-js/blob/2734a083a8a2b3e77f1436d7cee8bc9ec18a94f0/examples/localmediacontrols/src/index.js#L91), but you can most certainly replace this. 

I'll now be closing this issue but please feel free to continue the discussion in this thread if you have any further issues.

Best,
Joyce
