### ISSUE TITLE
Twilio video processors: replace BodyPix by Selfie Segmentation

### ISSUE THREAD

**Issue by genevpd** [twilio/twilio-video.js#1920]
The latest release of @twilio/video-processors 1.0.2 is based on outdated BodyPix model https://github.com/tensorflow/tfjs-models/tree/master/body-pix

Are there plans to switch it to more optimized Selfie Segmentation model part of Body Segmentation https://blog.tensorflow.org/2022/01/body-segmentation.html

> Prior to this launch, many of our users may have tried our [BodyPix](https://github.com/tensorflow/tfjs-models/tree/master/body-pix) model, which was state of the art when it launched. With today’s release, our two new models offer a much higher FPS and fidelity across devices for a variety of use cases.

**Comment by Dosant** [comment]
I noticed that there is a [2.0.0-rc1](https://github.com/twilio/twilio-video-processors.js/tree/2.0.0-rc1) branch in twilio-video-processors which has a bunch of improvements including the removal of BodyPix. 

But looks like there was no progress for a while. 

Dear Twilio team, could you please share the status of the 2.0 video processors? Was the release abandoned or is there work happening in private? 🙏

**Comment by anthonylazaro** [comment]
Hi All. Work was indeed started in this area to enhance the video processor SDK. It will not be completed this year and is currently on hold. I'll provide an update on status for this work in Q1 2023.

**Comment by genevpd** [comment]
@anthonylazaro for getting back to us and sharing an update! 

I just wanted to add that the quality and performance of the background blur is the main complain that we hear from our customers when they compare our twilio-based product with zoom/meet/teams. Very delighted to learn that this might be addressed soon. Please let us know if we can help with testing or in any other way. It seems that that branch is in pretty solid state already.

**Comment by manjeshbhargav** [comment]
@genevpd ,

The video processor library version 2.0.0 has been published.
