### ISSUE TITLE
Can you offer a signalling server in Europe?

### ISSUE THREAD

**Issue by CyranMS** [twilio/twilio-video.js#1922]
Hi all,
are there any plans to offer signaling sever in Europe? We see a lot of participants (around 100 per week) in Europe that cannot connect to Twilio because they block US AWS IPs.

**Comment by PikaJoyce** [comment]
Hi @CyranMS,

We have several servers based out of Europe, if they are connecting to to the US servers and blocking AWS IPs, I suggest using [`gll`](https://www.twilio.com/docs/video/tutorials/video-regions-and-global-low-latency#selecting-the-signaling-region). Of course, there is also a list of various regions (some based in the EU!) if you'd like to manually set that as well.

I'll now be closing this issue as there are no action items from this issue. But I'm more than happy to answer questions if you have anything further.

Best,
Joyce
