### ISSUE TITLE
Video is not started while running app builded with Electron and Angular

### ISSUE THREAD

**Issue by vitaliyzolotoy** [twilio/twilio-video.js#1924]
- [ +] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [ +] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ +] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [ +] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

```js
          video.connect(String(token), {
            name: this.roomName ,
            audio: true,
            video: { width: 250, height: 170},
            logLevel: 'debug'
          }).then(room => {
            console.log('Connected to Room "%s"', room.name);
          }).catch(error => {
            console.log(error);
          });
        });
```

**Expected behavior:**

Running electron app and Twilio was connected to room 

**Actual behavior:**
Got next error:

```
main.fbaf8dc5e08c6f3b.js:1 2022-11-10T14:41:28.428Z warn [connect #1] The ConnectOptions "logLevel" is deprecated and scheduled for removal. Please use "Video.Logger" instead.
O.log @ main.fbaf8dc5e08c6f3b.js:1
main.fbaf8dc5e08c6f3b.js:1 2022-11-10T14:41:28.434Z info [connect #1] Connecting to a Room
main.fbaf8dc5e08c6f3b.js:1 2022-11-10T14:41:28.435Z debug [connect #1] Options: Object
main.fbaf8dc5e08c6f3b.js:1 2022-11-10T14:41:28.437Z info [connect #1] LocalTracks were not provided, so they will be acquired automatically before connecting to the Room. LocalTracks will be released if connecting to the Room fails or if the Room is disconnected
main.fbaf8dc5e08c6f3b.js:1 2022-11-10T14:41:39.191Z warn [createLocalTracks #1] Call to getUserMedia failed: DOMException: Could not start video source
O.log @ main.fbaf8dc5e08c6f3b.js:1
O.warn @ main.fbaf8dc5e08c6f3b.js:1
(anonymous) @ main.fbaf8dc5e08c6f3b.js:1
G @ main.fbaf8dc5e08c6f3b.js:1
(anonymous) @ main.fbaf8dc5e08c6f3b.js:1
G @ main.fbaf8dc5e08c6f3b.js:1
value @ polyfills.697bada0d9eacb6d.js:1
value @ polyfills.697bada0d9eacb6d.js:1
(anonymous) @ polyfills.697bada0d9eacb6d.js:1
value @ polyfills.697bada0d9eacb6d.js:1
value @ polyfills.697bada0d9eacb6d.js:1
ee @ polyfills.697bada0d9eacb6d.js:1
Promise.then (async)
K @ polyfills.697bada0d9eacb6d.js:1
Q @ polyfills.697bada0d9eacb6d.js:1
value @ polyfills.697bada0d9eacb6d.js:1
value @ polyfills.697bada0d9eacb6d.js:1
value @ polyfills.697bada0d9eacb6d.js:1
ve @ polyfills.697bada0d9eacb6d.js:1
J @ polyfills.697bada0d9eacb6d.js:1
(anonymous) @ polyfills.697bada0d9eacb6d.js:1
(anonymous) @ polyfills.697bada0d9eacb6d.js:1
main.fbaf8dc5e08c6f3b.js:1 2022-11-10T14:41:39.195Z info [connect #1] Error while connecting to a Room: DOMException: Could not start video source
main.fbaf8dc5e08c6f3b.js:1 DOMException: Could not start video source
```

TODO

**Software versions:**

 - [ +] Browser(s):  Electron JS (Chrome)
 - [ +] Operating System: Mac OS Ventura
 - [ +] twilio-video.js:  "twilio-video": "2.21.3"
 - [ +] Third-party libraries (e.g., Angular, React, etc.): Angular, Electron

**Comment by PikaJoyce** [comment]
Hi @vitaliyzolotoy

Thanks for opening this issue with us. 

Some suggestions for this error : `DOMException: Could not start video source`. 

1. Could you please ensure that another application is not open and using your video source?
2. Could you ensure that you have granted your browser permissions to your microphone/camera at an OS level? If you have not granted your OS these permissions, please follow the below steps:
```
1. Access System Preferences 
2. Head to Security & Privacy 
3. Privacy 
4. Camera / Microphone (two different tabs, you must grant the browser access to both) 
5. Check the browser 
6. Restart the browser
```

Thanks,
Joyce

**Comment by vitaliyzolotoy** [comment]
Hi @PikaJoyce,
1) No, another application is not using video source
2) Permissions granted for app
