### ISSUE TITLE
How to check the used signaling region?

### ISSUE THREAD

**Issue by michalzaq12** [twilio/twilio-video.js#1931]
Hi everyone,
 Is there any property/method to check the client's used signaling region. I'm using the default `gll` option and I want to know which region this is resolving to.

**Comment by seancoleman2** [comment]
Hi @michalzaq12, the signaling region selected is surfaced in Video Insights (docs [here](https://www.twilio.com/docs/video/troubleshooting/insights)) via the Twilio Console. The data is available ~10-15 min after the room ends. You can access Video Insights in the Console by navigating to Monitor -> Insights -> Video. 

For individual Rooms, you can see this data for each of the participants that connected to the room: 
<img width="943" alt="Screen Shot 2022-11-28 at 12 09 32 PM" src="https://user-images.githubusercontent.com/11685703/204339405-5e9da31f-72b3-4d9d-b48c-36b0835fed50.png">

You also can see the distribution of signaling regions selected across all your participants on Insights Dashboard: 
<img width="1538" alt="Screen Shot 2022-11-28 at 12 13 53 PM" src="https://user-images.githubusercontent.com/11685703/204339954-09b5fecb-4e1f-4a25-af86-0d50fec75647.png">

I will close this issue for now, but let me know if there is a reason you would need to info while the room is in progress or if you have any further questions!
