### ISSUE TITLE
dominantSpeaker setting disables cross-talking ?

### ISSUE THREAD

**Issue by cindyloo** [twilio/twilio-video.js#1951]
I am not sure if this is a feature or a bug or an elusive setting, but when we turn dominantSpeaker to True, cross-talk (talking at the same time) is disabled. For example, 4 users all talking at the same time are all audible when dominantSpeaker is False. When set to true, we can only hear one person at a time and if there is a switch, some words are lost. 

what we want is the video to switch back and forth depending on who is speaking, but we don't want to have anyone cut off. Is this possible and if so, what are the correst Connection Settings? (we played with Mode: Collaboration and Speaker priority:standard/high to no avail)

**Comment by seancoleman2** [comment]
@cindyloo can you provide the platform details where you saw this behavior so that we can reproduce it? OS/Browser etc.

**Comment by seancoleman2** [comment]
I will close this one due to inactivity, but @cindyloo please do comment here if you are still having this issue and we will reopen. We could not reproduce in out daily standups using the React app, so OS/browser details would be helpful. Thanks!
