### ISSUE TITLE
createLocalAudioTrack ignores tracks parameter

### ISSUE THREAD

**Issue by simeiko** [twilio/twilio-video.js#1952]
We're facing an issue where `createLocalAudioTrack` doesn't respect given audio track and always uses the default audio input device.

**Steps to reproduce:**
1) Join Twilio Room.
2) User unmutes and uses audio input A.
3) Audio is coming from the default audio input.
4) User changes audio input to B.
5) Audio is still coming from the default audio input.

**Code to reproduce the issue:**
```js
// const audioMediaStream: MediaStream;

createLocalAudioTrack({
  noiseCancellationOptions: isNoiseSuppressionSupported() // true
    ? noiseCancellationOptions
    : undefined,
  tracks: audioMediaStream.getAudioTracks().map((track) => {
    console.debug(`Original track - ${track.label}`);

    return new LocalAudioTrack(track.clone());
  }),
}).then(async (clonedTrack) => {
  console.debug(
    // @ts-ignore
    `Noise cancellation track - ${clonedTrack.noiseCancellation._sourceTrack.label}`
  );

  // ...
});
```

**Expected behavior:**

`createLocalAudioTrack` should respect `tracks` parameter and not use default audio input.

**Actual behavior:**

`createLocalAudioTrack` uses whatever default audio input device all the time despite manually passed audio track.

**Software versions:**

 - Browser(s): Chrome 108.0.5359.98
 - Operating System: Mac OS
 - twilio-video.js: 2.26.0
 - Third-party libraries: React 16 and Krisp noise suppression

[logs.txt](https://github.com/twilio/twilio-video.js/files/10240977/logs.txt)

**Comment by manjeshbhargav** [comment]
Hi @simeiko ,

`tracks` is not a valid member of [CreateLocalAudioTrackOptions](https://sdk.twilio.com/js/video/releases/2.26.0/docs/global.html#CreateLocalAudioTrackOptions). If you want to create your own LocalAudioTrack from a pre-existing MediaStreamTrack, you can do it like this:
```js
const localAudioTracks = audioMediaStream.getAudioTracks().map(track => new LocalAudioTrack(track.clone()));
```
If you want to add noise cancellation, then you HAVE TO create the LocalAudioTrack using `createLocalAudioTrack()`.
Hope this answers your question.

**Comment by simeiko** [comment]
@manjeshbhargav ,

createLocalAudioTrack function accepts `CreateLocalTracksOptions` interface which allows passing `tracks` argument.

Could you please update TS types to avoid confusion for other developers?

```ts
// From: node_modules/twilio-video/tsdef/index.d.ts
export function createLocalAudioTrack(options?: CreateLocalTracksOptions|CreateLocalAudioTrackOptions): Promise<LocalAudioTrack>;

// From: node_modules/twilio-video/tsdef/types.d.ts
export interface CreateLocalTracksOptions {
  audio?: boolean | CreateLocalTrackOptions | CreateLocalAudioTrackOptions;
  /**
   * @deprecated
   */
  logLevel?: LogLevel | LogLevels;
  loggerName?: string;
  tracks?: LocalTrack[];
  video?: boolean | CreateLocalTrackOptions;
}
```

___

Could you please add the support to create tracks with noise suppression from given `MediaStream` or `MediaStreamTrack` object(s)?

It is inconsistent with Twilio Video SDK as you can use it with own `MediaStream` object for all parts, but not noise suppression.

**Comment by manjeshbhargav** [comment]
@simeiko There is a bug in the `createLocalAudioTrack` definition. It accepts `CreateLocalTrackOptions`, not `CreateLocalTrack(s)Options`. I will open an internal ticket to fix the definition.

**Comment by simeiko** [comment]
@manjeshbhargav ,

Thanks.

What about adding the support to create tracks with noise suppression from given `MediaStream` or `MediaStreamTrack` object(s)?

**Comment by manjeshbhargav** [comment]
@simeiko ,

Any reason why you need this? You can enable noise suppression using `createLocalAudioTrack()` without the need to pass an audio stream.

**Comment by simeiko** [comment]
@manjeshbhargav ,

There is a bug within iOS which kills all previously obtained media streams upon calling `navigator.mediaDevices.getUserMedia`. I'm pretty sure `createLocalAudioTrack` calls it in order to obtain a new media stream track.

We do support iOS and we had to implement custom stream management for other features within our application.

**Comment by manjeshbhargav** [comment]
@simeiko FYI, noise cancellation is not supported in Safari (iOS/MacOS).

**Comment by simeiko** [comment]
@manjeshbhargav ,

Right, forgot about that.

However, it is still inconsistent with all other parts of Twilio Video SDK where you can publish your own audio/video tracks, but you can't do it with noise suppression enabled.

Why would SDK provide such functionality for all tracks except noise suppressed ones?

**Comment by manjeshbhargav** [comment]
@simeiko ,

This is primarily because noise suppression only applies to microphone tracks as of now, so we ensure this by applying noise suppression only to tracks created by calling `createLocalAudioTrack()`.
