### ISSUE TITLE
ERROR - 53405 - Media connection failed or Media activity ceased for Video.connect

### ISSUE THREAD

**Issue by lovedota** [twilio/twilio-video.js#1953]
**Description**

- We have several customers using Edge 
  - Family: Edge
  - Major:  108
  - Minor: 0
  - Patch: 1462
  - Patch_Minor: 46
- That cannot access to TwilioRoom, but they can access using Chrome. 

**Software versions:**

 - [x] Browser(s): Edge 
 - [x] Operating System: Windows
 - [x] twilio-video.js: 2.25.0
 - [x] Third-party libraries (e.g., Angular, React, etc.): React

**Comment by mcarrerasm** [comment]
Hey @lovedota  unfortunately I'm not able to reproduce the issue.

Could you please confirm that you still experiencing this issue? 

Can you please try it on our [react app](https://github.com/twilio/twilio-video-app-react) or [quickstart app](https://github.com/twilio/video-quickstart-js/) and see if you can reproduce it?

**Comment by seancoleman2** [comment]
@lovedota going to close this one due to inactivity, but please let us know if you are still having this issue and we will reopen it. Thanks!
