### ISSUE TITLE
Safari desktop: Delays when switching audio or video input device

### ISSUE THREAD

**Issue by cmecklenborg** [twilio/twilio-video.js#1955]
- [X] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [X] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [X] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [X] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

This issue is reproducible on the current (0.8.0) version of [twilio-video-app-react](https://github.com/twilio/twilio-video-app-react)

**Expected behavior:**

Changing the audio or video input happens quickly and accurately

**Actual behavior:**

On Safari desktop, switching audio input devices takes 2-3 seconds to complete. Switching video input devices takes about 0.5 seconds.

The same operations on Chrome and Firefox take less than 1ms.

The delay appears to be occurring in the [initialize method](https://github.com/twilio/twilio-video.js/blob/master/lib/media/track/mediatrack.js#L120) of mediatrack.js.

Safari - Audio Input Change
![Safari - Audio Input Change](https://user-images.githubusercontent.com/816447/208498872-8feacaf6-49a1-4111-a462-96d1c69d7363.png)
Safari - Video Input Change
![Safari - Video Input Change](https://user-images.githubusercontent.com/816447/208498870-8298909c-62f7-49c4-b7c1-62cf95ee418d.png)
Chrome - Audio Input Change
![Chrome - Audio Input Change](https://user-images.githubusercontent.com/816447/208498867-fbccd2f0-ca26-4060-967a-c47e0d9c4e4e.png)

**Software versions:**

 - [X] Browser(s): Safari versions 15.5 and 16.1
 - [X] Operating System: macOS Monterrey 12.4 and Ventura 13.0.1
 - [X] twilio-video.js: 2.24.0 - 2.26.0
 - [X] Third-party libraries (e.g., Angular, React, etc.): React

**Comment by seancoleman2** [comment]
@cmecklenborg going to close this due to inactivity, but let us know if you have any other questions and we will reopen it. Thanks!
