### ISSUE TITLE
Feature Request: Expose networkQualityLevelChanged events on the room object

### ISSUE THREAD

**Issue by jpodwys** [twilio/twilio-video.js#1956]
## Feature Request
I've really enjoyed the SDK team's decision to expose participant-specific and track-specific events on the `room` object. Doing so has allowed me to centralize my event listeners and keep them to only one listener per event.

This is not currently possible with the `networkQualityLevelChanged` event. Today I need to attach/detach this listener from each individual participant. I'd really like to be able to manage this via a single room-level event handler.

#### `room.networkQualityLevelChanged`

Just as the `localParticipant`'s connection events are available via the top-level `reconnecting`, `reconnected`, and `disconnected` events, it would be nice to expose the `localParticipant`'s `networkQualityLevelChanged` event directly on the `room` object.

#### `room.participantNetworkQualityLevelChanged`

Just as with the existing `participant*` events, the `room` object can emit `participantNetworkQualityLevelChanged` for `RemoteParticipants`.

Thank you for your time and for all the great work!

**Comment by seancoleman2** [comment]
Hi @jpodwys - thanks for the feature request! I see how this could provide some more convenience when consuming these events. At the moment, this is not on our roadmap but I will keep this open and monitor community interest. 

If others would like to see this in the future, please do upvote / comment as that will help us prioritize.

**Comment by jpodwys** [comment]
@seancoleman2 thank you for the response. Would the team be open to a PR that's adds this behavior?

**Comment by manjeshbhargav** [comment]
We have de-prioritized this feature.
