### ISSUE TITLE
iOS Captured video not showing in web but working fine with android & iOS

### ISSUE THREAD

**Issue by MjCodingCamp** [twilio/twilio-video.js#1957]
Hi guys I'm facing an issue Actually iOS Captured video not showing in web but working fine with android & iOS. 

code is HERE! 

    private func startPreview() {
        if PlatformUtils.isSimulator {
            return
        }
        
        let frontCamera = CameraSource.captureDevice(position: .front)
        let backCamera = CameraSource.captureDevice(position: .back)
        camera = CameraSource(delegate: self)
        
        if (frontCamera != nil || backCamera != nil) {
            // Preview local camera track in the video previewer.
            localVideoTrack = LocalVideoTrack(source: camera!, enabled: true, name: "Camera")
            self.localCameraTrack = localVideoTrack
            logMessage(messageText: "Video Track Created Successfully")
            camera!.startCapture(device: frontCamera != nil ? frontCamera! : backCamera!) { (captureDevice, videoFormat, error) in
                if let error = error {
                    logMessage(messageText: "Capture failed with error.\ncode = \((error as NSError).code) error = \(error.localizedDescription)")
                } else {
                    logMessage(messageText: "Local Camera Video Render Successfully")
                    self.shouldMirrorCamera = true
                }
            }
        }
        else {
            logMessage(messageText:"No front or back capture device found!")
        }
    }

    func connectToARoom(roomName: String, accessToken: String) {
        let connectOptions = ConnectOptions(token: accessToken) { (builder) in
            
            // Use the local media that we prepared earlier.
            builder.audioTracks = self.localAudioTrack != nil ? [self.localAudioTrack!] : [LocalAudioTrack]()
            builder.videoTracks = self.localVideoTrack != nil ? [self.localVideoTrack!] : [LocalVideoTrack]()
            builder.networkPrivacyPolicy = .allowAll
            builder.isNetworkQualityEnabled = true
            builder.networkQualityConfiguration = NetworkQualityConfiguration(localVerbosity: .minimal, remoteVerbosity: .minimal)
            builder.preferredVideoCodecs = [ H264Codec(), Vp8Codec()]
            builder.roomName = roomName
        }
        
        // Connect to the Room using the options we provided.
        room = TwilioVideoSDK.connect(options: connectOptions, delegate: self)
    }

Twilio version - 5.4.0
Swift version - 5.7.2
Xcode version - 14.2 
iOS device version - 16.2 

Thanks: 🙂

**Comment by seancoleman2** [comment]
Hi @MjCodingCamp Screen capture is not possible on iOS via the Javascript SDK because mobile web browsers do not support [getDisplayMedia](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getDisplayMedia). See the note in the docs about this [here](https://www.twilio.com/docs/video/screen-capture-chrome#screen-share-not-supported-on-mobile-web-browsers). 

I'll close this issue for now, but let me know if you have other questions! Thanks!
