### ISSUE TITLE
Type mismatch between mediatrack.js and AudioTrack.d.ts and VideoTrack.d.ts

### ISSUE THREAD

**Issue by CamilleDrapier** [twilio/twilio-video.js#1960]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

```js
track.detach(element).forEach
```

This sometimes (when passed a non-falsy parameter) produces the following error: 

```
track.detach(...).forEach is not a function
``` 

**Expected behavior:**

There is no problem, or developers that are using `detach` are invited by TS to check for the type of result before proceeding with it.

**Actual behavior:**

The reason why we wrote `track.detach(...).forEach` is because the Typescript definition for [AudioTrack](https://github.com/twilio/twilio-video.js/blob/2.26.0/tsdef/AudioTrack.d.ts#L10) or [VideoTrack](https://github.com/twilio/twilio-video.js/blob/2.26.0/tsdef/VideoTrack.d.ts) says that `detach` always returns an array.  But in the implementation of [mediaTrack's detach](https://github.com/twilio/twilio-video.js/blob/2.26.0/lib/media/track/mediatrack.js#L253) seems to either return an element or an array (depending on the passed 'element').

Could we consider either:
- Changing the implementation so it follows the typing (this might be a breaking change, so it might be difficult to push as a simple update)
- Changing the TS definition so it accounts for the function returning either an element (or `undefined` in some edge cases maybe) or an array of elements.

**Software versions:**

 - [x] Browser(s): Chrome Version:108.0.0
 - [x] Operating System: Windows Version:10
 - [x] twilio-video.js: 2.26.0
 - [x] Third-party libraries (e.g., Angular, React, etc.): None relevant?

**Comment by PikaJoyce** [comment]
Hi @CamilleDrapier,

Thank you for reporting this issue with us! Great catch! I've filed a ticket (VIDEO-12242) to track this issue and will keep this thread updated with any progress! 

Best,
Joyce

**Comment by manjeshbhargav** [comment]
twilio-video.js@2.26.1 is now available.

**Comment by CamilleDrapier** [comment]
Thank you, I could confirm it works great with the new changes
