### ISSUE TITLE
How to emit events between participants

### ISSUE THREAD

**Issue by Avataw** [twilio/twilio-video.js#1966]
[Help-Wanted] 
Hey there!

I'd like to know if there is a possibility to emit events and share those between participants.

For example:

I have a twilio group room with two participants: **A**, **B** and **C**.

Now I want A to be able to click on **B**s video and disable that video for every participant
=> **A** can now only see themself and **C**
=> **B** can only see **A** and **C**
=> **C** can only see **A** and themself.

I tried emitting events on the Room / Participant / Publishing / Track - but nothing lead to the desired outcome.
Neither did calling the _switchOff_ method on the _RemoteVideoTrack_.

Is this even possible only in the frontend? :)

 - [ ] Browser(s): Chrome
 - [ ] twilio-video.js: 2.26.0
 - [ ] Third-party libraries (e.g., Angular, React, etc.): React

**Comment by yashrojesara** [comment]
@Avataw I think it's possible with **Data Track API**
https://www.twilio.com/docs/video/using-datatrack-api

What you can do is you can pass some data to the room which contains Participant B's SID and the action you want to perform
everyone will receive this data but you can compare the received SID with the local participant's SID, if that matches then you can perform the given action.

**Comment by Avataw** [comment]
@yashrojesara perfect! Exactly what I was looking for, thanks :)
