### ISSUE TITLE
Cannot capture front camera in LG G5 SE

### ISSUE THREAD

**Issue by theDude30** [twilio/twilio-video.js#197]
Hi,
The LG G5 SE comes with three cameras attached : 2 in the back and 1 in the front.
When i use this
Twilio.Video.createLocalTracks({video: true,audio:true}) ...
It gives the back camera.

When i Do this:
Twilio.Video.createLocalTracks({video: { facingMode: { exact: 'user' }},audio: true}
It gives by the back camera as well.

I tried to use navigator.mediaDevices.enumerateDevices() to identify which device is the front and which is the back camera, but i have no indication of that(i only have kind and deviceId).

**Comment by theDude30** [comment]
any updates?

**Comment by markandrus** [comment]
Hi @theDude30,

What browser are you using on the LG G5 SE? Could you try each of the below suggestions?

1. According to [this](https://www.w3.org/TR/mediacapture-streams/#dom-videofacingmodeenum), `facingMode` can be one of "user", "environment", "left", or "right". Can you try each of these and see if they work?
2. Can you try each of the video devices reported by `enumerateDevices`?

**Comment by theDude30** [comment]
I resolve the issue.
1. i used the following constraints that will force front camera to be used:
 constraints = {
		    video: {
        	    facingMode: {
            	    exact: "user"
            	}
        },
        audio:true
	  	};

2. It appears that if you are using webview and call enumerateDevices the label of the devices will be missing, it a known bug.
