### ISSUE TITLE
Some Room.getStats errors can't be caught via Promise.catch

### ISSUE THREAD

**Issue by SergeyPoznyakAkvelon** [twilio/twilio-video.js#1973]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `twilio-video@2.24.3` for the project I'm working on.

We encountered issue #1968 and it results in a dropped call for us, even though we used `.catch` on the promise returned from getStats. I looked through the twilio-video code and found one place where for some reason the error is not resulting in a rejected promise.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/twilio-video/es5/webrtc/getstats.js b/node_modules/twilio-video/es5/webrtc/getstats.js
index ecebb16..504ef2a 100644
--- a/node_modules/twilio-video/es5/webrtc/getstats.js
+++ b/node_modules/twilio-video/es5/webrtc/getstats.js
@@ -315,7 +315,11 @@ function chromeOrSafariGetTrackStats(peerConnection, track) {
             return;
         }
         peerConnection.getStats(track).then(function (response) {
-            resolve(standardizeChromeOrSafariStats(response));
+            try {
+                resolve(standardizeChromeOrSafariStats(response));
+            } catch (err) {
+                reject(err)
+            }
         }, reject);
     });
 }
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by manjeshbhargav** [comment]
Hi @SergeyPoznyakAkvelon ,

Thanks for bringing this issue. 2.26.1 is released, which does not throw the exception anymore. I will create an internal ticket to surface all getStats errors to the application. I will close this issue, since updating to 2.26.1 should solve your problem.
