### ISSUE TITLE
Warning related to 'setParameters' when starting a twilio call

### ISSUE THREAD

**Issue by CamilleDrapier** [twilio/twilio-video.js#1983]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ ] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

This might be related to: 
- [this known issue](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md#firefox-desktop) - But I only noticed this console warning quite recently.
- [this Firefox change](https://hg.mozilla.org/integration/autoland/annotate/92f418bbba4a4b7b7b6438b3af47c56837eec551/dom/media/webrtc/jsapi/RTCRtpSender.cpp#l431)

**Code to reproduce the issue:**

Sorry, there is no specific code to show here, this happens after calling `connect`, probably more or less when the `participantConnected` event is fired for "self"?

**Expected behavior:**

There should be no warnings

**Actual behavior:**

```
WARNING! Invalid setParameters call detected! The good news? Firefox supports sendEncodings in addTransceiver now, so we ask that you switch over to using the parameters code you use for other browsers. Thank you for your patience and support. The specific error was: Cannot change transaction id: call getParameters, modify the result, and then call setParameters
```

**Software versions:**

 - [x] Browser(s): Firefox 110.0b9 (64-bit) <- please note that this is not the standard release version.
 - [x] Operating System: Manjaro Linux
 - [x] twilio-video.js: 2.26.0
 - [x] Third-party libraries (e.g., Angular, React, etc.): VueJs

**Comment by fippo** [comment]
Most likely Firefox is overly aggressive about that warning: https://bugzilla.mozilla.org/show_bug.cgi?id=1817936

**Comment by CamilleDrapier** [comment]
Thanks, then sorry for the false alarm if that is the case; I'll try to confirm I do not see the warning anymore when using Twilio on a newer version of firefox! :bow:

**Comment by anna-vasilko** [comment]
Thanks @fippo for answering this question. 
@CamilleDrapier I will close this ticket as it seems as a known Firefox issue and nothing to do for us here.
