### ISSUE TITLE
Picture in Picture 

### ISSUE THREAD

**Issue by banshi-b** [twilio/twilio-video.js#1984]
Hello,
i want to do picture in picture during video calling when user access the some other function of the my portal but i get this error in 
 angular when click button please check attached screenshot 
![image](https://user-images.githubusercontent.com/120625111/219296586-d22fe63b-5493-4ad6-affc-feb8fc8c4757.png)

Thank you.

**Comment by manjeshbhargav** [comment]
@banshi-b ,

I think this means your browser does not support picture-in-picture, as `requestPictureInPicture` is not available.

**Comment by banshi-b** [comment]
hello,
As I checked with native videos, it supports picture in picture, but it
doesn't work with Twilio video calling.

Thank you,
Banshi Bhatt
Hyperlink Infosystem Pvt Ltd.
