### ISSUE TITLE
Screen Sharing. Safari 16

### ISSUE THREAD

**Issue by Aleksandern** [twilio/twilio-video.js#1985]
Hello.

Screen Share isn't working on Safari but it's working okay on Chrome.
I get error `getdisplaymedia must be called from a user gesture handler`

```js
          stream = await navigator.mediaDevices.getDisplayMedia({
            video: true,
            audio: false,
          });
```

Maybe I should get the share screen stream somehow else?

Thank you.

**Comment by manjeshbhargav** [comment]
@Aleksandern ,

The error message is asking you to call `getDisplayMedia()` from a user gesture handler, like a button click event handler.
If you do that, then it should work.
