### ISSUE TITLE
The mediaStreamTrack.muted value is always false in remote video track, only Firefox browser.

### ISSUE THREAD

**Issue by YuriiShyshkin** [twilio/twilio-video.js#1988]
**Host** - user that starts the room.
**Participant** - user that joins into the room.

**Problem**

The issue reproduces only if the track is published from **Firefox** browser.

When participant joins to room and processes remote data tracks, the remote track which is responsible for screen sharing always has "_false_" value in mediaStreamTrack.muted.

Host that publishes local video track with muted mediaStreamTrack. (Publish from Firefox)
![image](https://user-images.githubusercontent.com/115140037/220146741-0a5814c8-f5c8-4540-9880-68c24c2c9908.png)

The participant that processes the remote video track when joining has the muted parameter set to false.![image](https://user-images.githubusercontent.com/115140037/220147352-5e498cc1-06f1-4913-ae0f-5c365736b4fc.png)

**Technical Details** 

Code responsible for creation and publication of a local video track:

```
...
let screenSharingTrack = new Twilio.Video.LocalVideoTrack(sharingTrack, {name: TWILIO_TRACK_TYPE_SHARING});
twilioRoom.localParticipant.publishTrack(screenSharingTrack, {priority : TWILIO_TRACK_HIGH});
...
```

**Steps to reproduce**
1. Publish a local video track as Host with muted mediaStreamTrack.;
2. As Participant join into the room and process Host tracks;
3. The remote track which is responsible for screen sharing has "_false_" value in mediaStreamTrack.muted (and isStarted property has "true");

**Investigation**
If the **Host** publishes muted local video track from **Chrome**, everything works fine and when the **participant** joins the room and starts processing the remote tracks, the _muted_ property of mediaStreamTrack in the screen sharing track has value "_true_"

Host that publishes local video track with muted mediaStreamTrack.
![HostLaunchedFromChrome](https://user-images.githubusercontent.com/115140037/220150929-2b9d622f-f8bd-49ce-a0e7-eda178192e3b.png)

Participant that processing the remote video track when joining has the muted parameter set to true. (isStarted property of remote track is "_false_")
![ParticipantSideChrome](https://user-images.githubusercontent.com/115140037/220151371-09c0dd87-b1fe-438e-b338-172cd40ce786.png)

**Additional information**

Room sid: RM5803938f861548ff962473005b2c9d8b;
Room type: group;
JS Version: 2.26.1;
Browser: Firefox, 110.0 (64-bit);
Internet download/upload speed: 55.83/55.94Mbps.

**Questions**

Could you suggest something?
Are there any known issues regarding the problem?
Should the isStarted property on Participant side be true if the track is muted?

**Comment by manjeshbhargav** [comment]
Hi @YuriiShyshkin ,

The `muted` state of the remote MediaStreamTrack has nothing to do with the `muted` state of the local MediaStreamTrack.  Please check out this [blog about RTCRtpTransceivers](https://blog.mozilla.org/webrtc/rtcrtptransceiver-explored/) for more details on which publisher actions toggle the `muted` state of a remote MediaStreamTrack.

**Comment by YuriiShyshkin** [comment]
Hi @manjeshbhargav
Thank you for your response.

**But why the behavior is different in these two browsers(Chrome and Firefox)?**

When the **Host** publishes the track into the room and the **participant** joins into the room and starts processing that remote track, it always has the value **isStarted = true** on **Firefox**.(Regardless of whether the Host track was muted or not.)

When the **Host** publishes the track into the room and the **participant** joins into the room and starts processing that remote track, it's always different value **isStarted = true/false** on **Chrome**. If Host track is muted then isStarted variable is always false and if the Host track is not muted then isStarted variable is always true.(_Depends on is the remote track was muted or not_)

**Comment by manjeshbhargav** [comment]
@YuriiShyshkin ,

We depend on `HTMLVideoElement.oncanplay` to set `isStarted` to `true`. I'm guessing Firefox is firing the event even if the track is muted? In any case, I think the desired behavior is to have `isStarted` set to `false` if a RemoteVideoTrack is created with a muted MediaStreamTrack.

You could work around this by doing something like this:

```js
participant.on('trackSubscribed', track => {
  ...
  trackActuallyStarted(track);
  track.on('actuallyStated', () => {...});
  ...
});

function trackActuallyStarted(track) {
  track.on('started', () => {
    if (track.mediaStreamTrack.muted) {
      track.mediaStreamTrack.addEventListener(
        'unmute',
        () => track.emit('actuallyStarted'),
        { once: true }
      );
    } else {
      track.emit('actuallyStarted');
    }
  });
}
```

**Comment by YuriiShyshkin** [comment]
Thank you for work around but **participant** that receives the track  from Firefox always has `track.mediaStreamTrack.mute = false`).

When I publish muted track from _Chrome_ (**Host**) to _Firefox_ (**Participant**) everything works fine. (isStarted property works correct and it's false and `track.mediaStreamTrack.muted = true`).

But when I publish muted track from _Firefox_  (**Host**) to _Chrome_ (**Participant**) isStarted property is always _true_ and `track.mediaStreamTrack.muted = false`.

**Comment by YuriiShyshkin** [comment]
Oh, sorry for mistake.
I've tried your code snippet and have following result:

When muted track published from _Firefox_ (**Host**) to _Chrome_ (**Participant**), participant receives remote track with isStarted = true and track.mediaStreamTrack.muted = true.
After 1-2 seconds unmute event fires and mediaStreamTrack become unmuted. But published track from Firefox is still muted.

Why mediaStreamTrack unmutes after 1-2 seconds?

**Comment by YuriiShyshkin** [comment]
@manjeshbhargav Could you please help?

**Comment by YuriiShyshkin** [comment]
@manjeshbhargav <https://github.com/manjeshbhargav>
Could you please help me?

**Comment by manjeshbhargav** [comment]
@YuriiShyshkin ,

As I said earlier, the `muted` state of a remote MediaStreamTrack have nothing to do with the `muted` state of the local MediaStreamTrack. Can you tell me what are you trying to accomplish? Maybe we can discuss a workaround if you describe your use-case.

**Comment by manjeshbhargav** [comment]
@YuriiShyshkin ,

One reason why the behavior between browsers might be different is that the SDK internally uses `video.oncanplay` to determine if the remote MediaStreamTrack has started. I think Chrome is not calling the callback for muted MediaStreamTracks, but Firefox is. So, in order to standardize the behavior, I suggested the workaround.

Another thing you can try is to [register a video frame callback](https://wicg.github.io/video-rvfc/#dom-htmlvideoelement-requestvideoframecallback) on a video element attached to the remote track. If it is called once, then mark the track as started.

**Comment by YuriiShyshkin** [comment]
@manjeshbhargav thank you for work around but it also does not work for me.
When **Host** publish muted track, on **Participant** side videoFrameCallback fires after 1-2 sec when track is still muted.
I just need to **NOT** show last screen share frame on **Participant** side when track is paused on **Host** side while joining into the room, and show custom message.

**Comment by manjeshbhargav** [comment]
@YuriiShyshkin ,

Another thing you can try is to call `localVideoTrack.disable()` if it is muted, and listen to the `disabled` event on the remote track. If the local track is unmuted, you can call `localVideoTrack.enable()` which will emit `enabled` on the remote track.
Let me know if this works.
