### ISSUE TITLE
`room.GetStats` return empty array

### ISSUE THREAD

**Issue by masterminh219** [twilio/twilio-video.js#1989]
```const statsReports = await room.getStats();```

I'm using this one to get Stats reports for both Local and Remote. But now it return empty arrays

 - [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [ ] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

```js
  ```const statsReports = await room.getStats();```
```

**Expected behavior:**

TODO

**Actual behavior:**

TODO

**Software versions:**

 - [ ] Browser(s): Chrome 110, Edge 110
 - [ ] Operating System: Windows 10
 - [ ] twilio-video.js: 2.26
 - [ ] Third-party libraries (e.g., Angular, React, etc.): React

**Comment by manjeshbhargav** [comment]
Hi @masterminh219 ,

Sorry for the delayed response. Can you provide me with the exact steps to reproduce this issue? How many participants are in the Room when this happens?
