### ISSUE TITLE
open a meeting on ios when a call is on, audio is muted

### ISSUE THREAD

**Issue by omermyspitch** [twilio/twilio-video.js#1993]
- [X] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [X] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [X] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [X] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

I used const isLocalRoomMuted = useLocalMediaMuted(room); 
and it return false.
I call  room.refreshInactiveMedia(); but nothing help (its only help if the I get a call in the middle of a chat)

**Expected behavior:**

To return the audio to the room

**Actual behavior:**

TODO

**Software versions:**

 - [X] Browser(s): Chrome
 - [X] Operating System: IOS16.0
 - [X] twilio-video.js: 2.26.2
 - [X] Third-party libraries (e.g., Angular, React, etc.): React

**Comment by manjeshbhargav** [comment]
Hi @omermyspitch ,

Thanks for reporting the issue. Can you share your source code, or your application url? I will play with it on my iOS device and see what's going on.

Thanks,

Manjesh
