### ISSUE TITLE
Is disabled VideoTrack included into a recording?

### ISSUE THREAD

**Issue by PavloShchur** [twilio/twilio-video.js#1998]
**Technical details**

We have custom implementation based on [Twilio Video JS](https://github.com/twilio/twilio-video.js/releases/tag/2.27.0).

There is a functionality which the shares screen of one participant to other participants based on [LocalVideoTrack](https://sdk.twilio.com/js/video/releases/2.27.0/docs/LocalVideoTrack.html) and creates a [composition](https://www.twilio.com/docs/video/api/compositions-resource) at the end. 

For pausing screen sharing we use **disable()** function on LocalVideoTrack instance. As a result, other participants see the last frame because the media server stops sending bytes for disabled track.

**Scenario**

A participant shares a screen for 5 seconds and after that pause sharing also for 5 seconds.

**Question**

Will composition include 5 seconds of recording or 10? Basically, will disabled video track be included into a composition?

**Comment by manjeshbhargav** [comment]
@PavloShchur ,

The disabled video track will be available in the recording. If you unpublish and publish again, the new video will be available in a separate recording since it has a new Track SID.
