### ISSUE TITLE
Participants who join with WeChat app browser can not see themselves while sharing their cameras.

### ISSUE THREAD

**Issue by PavloShchur** [twilio/twilio-video.js#1999]
**Steps To Reproduce**
1. Install and deploy [twilio-video-app-react](https://github.com/twilio/twilio-video-app-react) as described in [README.md](https://github.com/twilio/twilio-video-app-react#readme);
2. Open twilio-video-app-react Web App URL inside "WeChat" app;
3. Enter "Your Name" and "Room Name";
4. Click "Allow app to use your camera and microphone";
5. Click "Join Now";
6. Click "Start Video".

**Result**
The participant can not see himself on the screen while sharing his own camera, but other participants who have joined with any other browser can see him.
![photo_5287375062778890121_y](https://user-images.githubusercontent.com/87853135/229822607-7896c484-bd6a-4367-ace1-e607481d1412.jpg)

**Technical Details**
Room Sid: RMf62040c802f9a29b532ee6180903b908;
Device: iPad Pro;
Device OS Version: 16.3.1;
WeChat app version:  8.0.34.

**Question**
Can you please suggest any solutions or workarounds for this issue?

**Comment by manjeshbhargav** [comment]
Hi @PavloShchur ,

Can you share the console logs? Maybe the app does not have permission to access the camera?
