### ISSUE TITLE
Video orientation issue in Chrome for Android from iOS

### ISSUE THREAD

**Issue by maximeloizeau** [twilio/twilio-video.js#20]
Hello,

I am currently integrating Twilio SDK for video calls. I have an issue when the video is streamed from iOS to web on Android, the video is rotated 90deg.
When streaming web (desktop or Android) to web (desktop or Android), it is fine. It is also fine when streaming from iOS to desktop browser.

I am not sure which party might be at fault in this case. If you have any clue for me, I would appreciate it! Thanks.

**Comment by markandrus** [comment]
Let's track on #170
