### ISSUE TITLE
I want to Turn off the Remote Participant Media stream using Js/ API

### ISSUE THREAD

**Issue by godwinabishek** [twilio/twilio-video.js#2020]
Actually I want to Turn Off/On the remote participant video stream, sometimes we feel there's a lag in audio track while streaming the remote participant video. So we planned to Turn Off/On the remote participants video track and enable audio only, and we need this to be achieved only by the Admin login. Is there a way to achieve this? I have checked the documentation but i cant find any.

**Software versions:**

 - [ ] Browser(s): Chrome
 - [ ] Operating System: Windows 11
 - [ ] twilio-video.js: 2.14.0
 - [ ] Language: C#/ Javascript

**Comment by manjeshbhargav** [comment]
@godwinabishek ,

Thanks for writing in. You can use DataTracks to send messages to the RemoteParticipants to turn off their media. Hope this helps.
