### ISSUE TITLE
trackPublicationFailed or trackPublicationError

### ISSUE THREAD

**Issue by anand-io** [twilio/twilio-video.js#203]
Hi Team, 
In change log file,
https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md

is event trackPublicationFailed or trackPublicationError?

**Comment by manjeshbhargav** [comment]
Hi @anand-io ,

The event name is "trackPublicationFailed". Thanks for bringing this to our notice. We will update the CHANGELOG.md to change all references to "trackPublicationError" to "trackPublicationFailed".

Thanks,

Manjesh Malavalli
