### ISSUE TITLE
Apple hand gestures getting sent on video call

### ISSUE THREAD

**Issue by RyanDurkin** [twilio/twilio-video.js#2036]
I've just had a report from a customer thinking that we have added a new feature to our application (but we haven't). It turns out that when a user is on an Apple device then it picks up on the persons hand gestures and sends that down the pipe with the video call.

Apple explanation is here: https://youtu.be/NGc6TaCQe4M?feature=shared&t=19

Is there anyway to stop it injecting into the Twilio video stream? I have an application that people discuss very serious things and sending reactions can cause some major concerns and customers also thinking that we are intercepting their video calls.

It can be disabled on an individual device basis: https://www.macrumors.com/how-to/disable-gesture-based-facetime-reactions/

Has anyone else experienced this?

**Comment by fippo** [comment]
This is by now a well-known issue, see https://github.com/w3c/mediacapture-extensions/issues/118
Feel free to leave a note there.

**Comment by luisrivas** [comment]
The W3C has recently added support for gesture reaction constraints in MediaCapture Extensions (https://github.com/w3c/mediacapture-extensions/pull/141). Once browsers integrate this, people could use this constraint to adjust the user experience based on their specific case.
