### ISSUE TITLE
End of Life

### ISSUE THREAD

**Issue by michalzaq12** [twilio/twilio-video.js#2037]
### Twilio Programmable Video End of Life and Transition Plan

What do you need to know?
 

We know video is a key channel for many customer engagement use cases, and we have concluded that partnering with industry leaders in video is the best path to ensuring product innovation for our customers now and in the future. As such, we have decided to End of Life (EOL) our Programmable Video product on December 5, 2024, and we are recommending our customers migrate to the Zoom Video SDK for your video needs. 
 

The Zoom Video SDK is a fully customizable, developer-centric platform that largely supports the same set of use cases as Twilio's Programmable Video. Our partnership with Zoom ensures that customers have access to a global video infrastructure of the highest quality, a market-leading product roadmap, and a partner committed to enabling frictionless, secure video communications. We have prepared this [Twilio Programmable Video Migration Guide](http://url3648.twilio.com/ls/click?upn=VdWZaOOvtV9q8yde6oiVFqQolw6dgQ2hNM-2FFimWDr0Yq57mJCCsWSr3ytZvMcufqnR47EoMOHdDvNR4j-2BEThsQ-3D-3DQPzv_JdoYdXsGyDGkjz5-2Fq6AU5sfYmxqvg4zivk5BMn1SuhNLWnjKcCTo-2FlSTcGTAkXNQ26H1bUVk-2FNQbWO2v3GHpMA5Ac9IgfnApTPqS6L0anY5VZnApDJdUfBKA9wCM6qWRXy-2BbENWZwwAa5JfCA3oVyiH-2F6P-2FxKW-2Bh08HgGyJdk97-2BYXa-2B4KK65e3ml-2FmToNpIzPD1GeRfN0CM2RQDy7Wf-2BWu5dNugdvhq-2FFroMRzPoGn1g1HIfp02OfBI1RiUrzYDpmN1oM3ndBSzb0vgkJitNNZO7pz1I1ttkE-2BL01a7fKQGxJWMCfg6o5uSQyfw1bniNJ08bgMkqzYJogQrvBp4StYhSKRKvrag4FgK1lBxnEe7b4oIy7LqM9Am9Azt5rPTaTevFW1SiRPIGLdp7F8pISavsNKMB5aDgBBvLDYwiK2oaODhveJnS0WuN6UjgMwnePUiqy6iR4WGUVlmDRA1KZY46-2F2-2FkTQ-2Be5-2B3uhBnY5TGn5FsEhi0AME7rhda-2F7w3OOtPSqD3ok3yE8CdSJhnWw-3D-3D) with Zoom to minimize any service disruption. 
 

What do you need to do?

Existing customers can continue to use Twilio Programmable Video for the next 12 months until December 5, 2024; however, we will not be offering new feature enhancements or releases going forward. 
 

Please plan to migrate off Twilio Programmable Video by December 5, 2024, and remember to allocate enough time for product development and testing to ensure a successful transition. While customers can choose to migrate to any video provider, we recommend migrating to Zoom and have put together this [Twilio Programmable Video Migration Guide ](http://url3648.twilio.com/ls/click?upn=VdWZaOOvtV9q8yde6oiVFqQolw6dgQ2hNM-2FFimWDr0Yq57mJCCsWSr3ytZvMcufqnR47EoMOHdDvNR4j-2BEThsQ-3D-3Dnjak_JdoYdXsGyDGkjz5-2Fq6AU5sfYmxqvg4zivk5BMn1SuhNLWnjKcCTo-2FlSTcGTAkXNQ26H1bUVk-2FNQbWO2v3GHpMA5Ac9IgfnApTPqS6L0anY5VZnApDJdUfBKA9wCM6qWRXy-2BbENWZwwAa5JfCA3oVyiH-2F6P-2FxKW-2Bh08HgGyJdk97-2BYXa-2B4KK65e3ml-2FmToNpIzPD1GeRfN0CM2RQDy7Wf-2BWu5dNugdvhq-2FFroMRzPoGn1g1HIfp02OfBI1RiUrzYDpmN1oM3ndBSzb0vgkJitNNZO7pz1I1ttkE-2BL01a7fKS-2Fazz8rwyF1w0YG5-2FARbMFnJbBXzoIC2hQ-2BOndY9fL8UgtBlonddcmaKJGi8PIqgHQeHe5z-2FJUs7NYTWtVKR9D6UANazfTqM7M3CINOWauNriWvY6CBnG1tX-2FSoBEGd2I4ExvrYDMAmzEPeq5v4-2FzURD0ffSJ1Sb77OvsmwpKb3Y-2FIodfTrT4xnTMPMX4Czv30IHx5PJvNCszxo-2FErT9EIIjhKLjl1ys77m32gSRr88w-3D-3D)to get you started on your transition.
 

Additionally, you’ll receive communications with Flex-specific information if you use Programmable Video within Flex.
 

Sincerely, 
 

Team Twilio

**Comment by anna-vasilko** [comment]
Hi @michalzaq12  Thank you for creating this ticket. I am going to close it in favor of the same announcement ticket opened by the Twilio Video team.

**Comment by kumail-raza** [comment]
That sad.
