### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by jpodwys** [twilio/twilio-video.js#2039]
I've been using twilio-video for nearly 2.5 years now and I want to express my gratitude to those involved with this repo's development. It's been a sincere pleasure to work with this SDK. It's obvious that the devs who built this cared about ergonomics and scalability.

Here are a few things I really appreciate about twilio-video.

### The decision to re-emit (nearly) all events at the room level

This wasn't necessary, but the individuals who decided to do this really understand good code and library consumption. This single decision allowed me to avoid callback nesting on multiple resources and instead allowed me to attach all of my event handlers at the top level. Thank you!

### Extreme flexibility

1. Want to connect to a room with default tracks? Great! Don't pass any tracks to `connect` - twilio takes care of it.
2. Want to get custom tracks? Great! Provide your track constraints and twilio will get them for you.
3. Need even more control over your tracks? Great! Get them yourself then pass them to a `LocalTrack` constructor.
4. Need to identify your track because it's a screen or PTZ or some other special track? Great! Provide a `trackName`.

### Efficiency

When tracks aren't visible, they're not rendered. When they become visible again, they're rendered - all automatically.

### Features
1. Your simulcast implementation is superior - you support 1080p and allow three concurrent upload streams.
2. The ability to set a video bandwidth profile mode to tell twilio-video how to prioritize tracks is excellent.
3. Exposing the room's telemetry stats on-demand is incredibly useful.

I'm sad to see this product go. It's exceptional and you should be proud of it. Thank you for the hard work you did and for advocating for devs and ergonomics.

**Comment by jpodwys** [comment]
Hooray, you're sticking around after all!

**Comment by jpodwys** [comment]
Excellent news today! I'm happy you're sticking around.

**Comment by donaltoomey** [comment]
Thanks @jpodwys for your support.
