### ISSUE TITLE
Video: Test Group Room with TURN & Video: Test Group Room without TURN FAILS

### ISSUE THREAD

**Issue by mesarojgiri** [twilio/twilio-video.js#2041]
I am not a developer but a customer support rep and my employer requires me to pass all 10 aspects. But the Video: Test Group Room with TURN & Video: Test Group Room without TURN FAILS everytime. 
How can I resolve this issue. If possible explain it in NON TECH language. 
![image](https://github.com/twilio/twilio-video.js/assets/46751096/4a09a505-b432-4e11-bcb6-3ab6ecf53a43)

**Comment by spalmertwilio** [comment]
Hello!

Thanks for writing in! That tester should fail, as it  was moved to legacy for video in June of 2022.  

We have a hosted tester via URL https://video-diagnostics.twilio.com

Please read through https://www.twilio.com/docs/video/troubleshooting/pre-call-testing-and-diagnostics#video-diagnostics-application 

We recommend that you set up https://github.com/twilio/twilio-video-diagnostics-react-app on your own servers for any of your customers to use.

Take care!
