### ISSUE TITLE
Heroku deploy fails

### ISSUE THREAD

**Issue by jonathanazulay** [twilio/twilio-video.js#21]
```

npm ERR! sip.js@0.7.5 postinstall: `cd src/Grammar && mkdir -p dist && pegjs --extra-options-file peg.json src/Grammar.pegjs dist/Grammar.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the sip.js@0.7.5 postinstall script 'cd src/Grammar && mkdir -p dist && pegjs --extra-options-file peg.json src/Grammar.pegjs dist/Grammar.js'.
```

For some reason the postinstall step fails. Could it be that we need dots in the paths (`./src/Grammar`)? Or maybe add pegjs as a devDependency in the SIP.js fork.

I'm using this buildpack
https://github.com/tfarla/heroku-buildpack-meteor

**Comment by markandrus** [comment]
Hi @jonathanazulay,

We've made some changes to better support Meteor and we've also started testing our integration with Meteor on every commit (see our [twilio-video-meteor Framework Test](https://github.com/twilio/twilio-video.js/tree/master/test/framework/twilio-video-meteor)). Do you mind re-testing with twilio-video.js@beta-4 or later and re-opening this issue if the problem persists?

Thanks,
Mark
