### ISSUE TITLE
Missing "trackAdded" events

### ISSUE THREAD

**Issue by randallb** [twilio/twilio-video.js#212]
This is a question that might result in a bug report.

Occasionally when my users connect to a room it doesn't fire a 'participantConnected' or 'trackadded' event... i'm currently unsure which doesn't fire but I'm working on debugging that.

Regardless, I've been saving the track ID out of band for some other reasons. I have the track ID that I want to subscribe to, but I can't find a method to subscribe to it out of band.

I'm thinking about hacking the library to expose your track added method somehow to my application, though I'm not clear how it'd go.

Is this something you think would be reasonable to add to twilio-video.js, or should i just hack it on my own? If I can, I'll dig into the library probably today to do so.

Thanks so much for Twilio Video! It's so much better than what we were using before.

Thanks,
rb

**Comment by randallb** [comment]
It's the `trackAdded` event that's not firing.

It's extremely inconsistent. I can only get it to happen once every 20 or so publishes. Maybe sometimes even less often than that.

Basically, we send an out of band message that fires every time with the track ID which we need for our system.

Sometimes that track isn't available / hasn't connected yet.

We're in a peer-to-peer room configuration right now.

**Comment by markandrus** [comment]
Hey @randallb,

Sorry to hear you are having these issues. Missing "trackAdded" events are concerning, and we'd like to look into them.

> What information could I provide to aid in debugging?

Can you share

1. What version of twilio-video.js you are using.
2. What browser(s) you are using.
3. Any example Room SIDs.
4. Any debug logs you might have.

> I'm thinking about hacking the library to expose your track added method somehow to my application, though I'm not clear how it'd go.
>
> Is this something you think would be reasonable to add to twilio-video.js, or should i just hack it on my own? If I can, I'll dig into the library probably today to do so.

I cannot recommend this. The "trackAdded" event fires when two things happen (in either order) inside the SDK,

* We learn about a new Track in the **signaling layer** (i.e., by exchanging WebSocket messages with the Server).
* We learn about a new MediaStreamTrack from the **WebRTC layer** (i.e., by invoking the underlying RTCPeerConnection APIs).

There _have_ been bugs where we actually had the required information from the signaling and WebRTC layers, but didn't raise the "trackAdded" events. It's possible this might be happening here. If so we should fix the bug. But logs and/or Room SIDs should hopefully clarify the issue.

Thanks for raising this to our attention,
Mark

**Comment by randallb** [comment]
What version of twilio-video.js you are using.
1.6.0
What browser(s) you are using.
Chrome 62
Any example Room SIDs.
Finding
Any debug logs you might have.
Finding.

I'll try to put together a minimum viable case today that is somewhat reproducible. I'll let you know what I find.

**Comment by randallb** [comment]
I got it to happen with Room SID:
`RMc457e22798d9bb1cb5aef2d914eac030`

And the twilio video and audio track IDs that didn't appear:
video: `cce458c8-fc87-4799-9098-8c596f93ff4e`
audio: `f2ffbb65-466c-4041-99c1-31488abab9a1`

Looking at the logs, I know it'll jump out at you that i connected a bunch of times, but we've had this happen when only 3 nodes are connected. Sometimes even only 1 node. Our users end up showing black video and it makes them very angry as you might imagine.

Does this make sense?

**Comment by randallb** [comment]
I got it to happen again:
`RMa0e2ba258ea24bac1ebe6aad4197f6f5`

tracks:
`5973a47b-8908-41ed-ae86-2937be182e4f` 
`e90e3fb9-ce23-4724-b879-96d182cb4a7f`

**Comment by markandrus** [comment]
Thanks for these, @randallb. I'll step through them and try to analyze what's happening.

**Comment by randallb** [comment]
We ended up bailing out of relying on trackadded events... instead we're keeping our own copy of 'who is live' on our side, and trying to iterate through `room.participants` to find the tracks we're looking for. It seems that it's not that trackAdded events don't fire, they just might not fire fast enough. Our new approach has proved more reliable in our testing.

Race conditions. :/

**Comment by markandrus** [comment]
Sorry @randallb, I haven't had a chance to look through the event log yet—there are quite a few Participants in the Room.

Do you mind explaining this a bit more?

> We ended up bailing out of relying on trackadded events... instead we're keeping our own copy of 'who is live' on our side, and trying to iterate through room.participants to find the tracks we're looking for.

Are you saying that you, if you try to depend on "trackAdded" events, it's not working for you? However, if you just iterate through the Participants and Tracks collections, you can get access to the Tracks you need?

Also, just to make sure: you're handling both synchronously and asynchronously added Participants and Tracks, right? Just to confirm, in order to handle all the orderings in which events can you occur, you should have code like

```js
room.participants.forEach(handleParticipantConnected)
room.on('participantConnected', handleParticipantConnected)

function handleParticipantConnected(participant) {
  participant.tracks.forEach(handleTrackAdded)
  participant.on('trackAdded', handleTrackAdded)
}
```

Thanks,
Mark

**Comment by coolnalu** [comment]
we might be having the same issue. videos are recorded but participants couldn't see each other.

**Comment by randallb** [comment]
We had code like that @markandrus, now we just save the IDs and iterate through the participants and tracks collections and it seems to work.

**Comment by hugomallet** [comment]
Hi,

Don't know if it is really related but i have issues regarding trackadded events.
Once a track has been added, next trackadded events are not fired (peer seems to not receive at all the new track). I need to unpublish then republish after a delay every tracks at once.

Have you any issue like this ?

**Comment by smkrn110** [comment]
Same issue facing, but only on Firefox, with chrome its working fine.

**Comment by smkrn110** [comment]
> We had code like that @markandrus, now we just save the IDs and iterate through the participants and tracks collections and it seems to work.

@randallb 

I have try to do the same but unfortunately, I check the participant is there but with no tracks.

**Comment by manjeshbhargav** [comment]
@randallb , @coolnalu , @hugomallet , @kumail-raza ,

I'm closing this issue since its really old. Please feel free to open a new issue if you are still experiencing this problem.

Thanks,

Manjesh Malavalli
JSDK Team
