### ISSUE TITLE
Unable to switch to rear camera on iOS mobile safari

### ISSUE THREAD

**Issue by vsrboth** [twilio/twilio-video.js#218]
I am currently using twilio_video.js V 1.6.0 for mobile safari. I am able to render the video using the front camera but unable to make it works on the rear camera using the following codes:

```
publisherElem = document.getElementById('mobile-publisher')
video = publisherElem.querySelector('video')
Twilio.Video.createLocalVideoTrack(
  deviceId: source.deviceID
).then (localTrack) ->
  localTrack.attach video
  return
```
here is the screenshot

<img width="999" alt="screen shot 2017-11-20 at 11 37 07 am" src="https://user-images.githubusercontent.com/5484995/33018380-763fff7e-cdf6-11e7-8430-9acabc824211.png">

**Comment by markandrus** [comment]
Hi @vsrboth,

Can you please try specifying the `facingMode` constraint? It can have one of two values, e.g.

* "user", or
* "rear".

You can use it as follows in your code snippet:

```js
Twilio.Video.createLocalVideoTrack({
  facingMode: "rear" // or "user"
});
```

There was some similar discussion for the LG G5 SE [here](https://github.com/twilio/twilio-video.js/issues/197).

Best,
Mark

**Comment by MilllerTime** [comment]
Just a friendly heads up - the non-user camera constraint should be

```js
Twilio.Video.createLocalVideoTrack({
  facingMode: "environment"
});
```

instead of

```js
Twilio.Video.createLocalVideoTrack({
  facingMode: "rear"
});
```

Source: https://www.w3.org/TR/mediacapture-streams/#def-constraint-facingMode

**Comment by markandrus** [comment]
I think this question is answered, as far as constraints go. For anyone struggling with switching between front and back cameras, though, please be aware of [this issue](https://github.com/twilio/twilio-video.js/issues/394) and the associated [WebKit Bug 188606](https://bugs.webkit.org/show_bug.cgi?id=188606).

Best,
Mark
