### ISSUE TITLE
Uncaught GATEWAY_DISCONNECTED | Connection to Twilio's servers was lost

### ISSUE THREAD

**Issue by cyx-charan** [twilio/twilio-video.js#22]
Hi,

I downloaded the starter kit for programmable video. The standalone code works but when I integrated the code with my react app, it gives me this strange error
`Uncaught GATEWAY_DISCONNECTED | Connection to Twilio's servers was lost`
I have left all the quickstart.js as it is except that when my video component mounts, i am calling an init function which run all the twilio related code. The logs just say that the call failed but provide no explanation.

Please help!

**Comment by markandrus** [comment]
Hi @cyx-charan,

It sounds like you ran into a similar bug as was reported in https://github.com/twilio/twilio-video.js/issues/29! The issue related to some dependencies including `ws`—a WebSocket library we use when testing in Node—that was getting included in bundles used with certain React configurations. We fixed this in twilio-video.js@beta-4.

Would you mind retesting and re-opening this issue (or a new one) if the problem persists?

Thank you,
Mark
