### ISSUE TITLE
memory leaks in peerconnection.js and SIP.js's SanityCheck.js

### ISSUE THREAD

**Issue by anand-io** [twilio/twilio-video.js#220]
When I tried Chrome's heap snapshot after few calls. I found there were some memory leaks. 

This line makes the defaults variable to keep the reference to the last room. 
https://github.com/twilio/twilio-video.js/blob/master/lib/signaling/v2/peerconnection.js#L88

Tried this fix and it worked. https://github.com/anand-io/twilio-video.js/commit/54f01a046b09183b6c73ea3bef0d34639f59ce99

Memory leak with SIP.js https://github.com/onsip/SIP.js/issues/381

I tried the similar fix on the twilio's SIP.js fork and the memory leak issue is solved. 
https://github.com/anand-io/SIP.js/commit/189b6a0eb4ca6dee85bb690356e1891cd954d406

**Comment by markandrus** [comment]
Really nice! Thanks @anand-io 👍

**Comment by markandrus** [comment]
We landed the PeerConnectionV2 fix in twilio-video.js@1.6.1. We are working to land the SIP.js fix for twilio-video.js@1.7.0.

**Comment by markandrus** [comment]
This was fixed in twilio-video.js@1.7.0.
