### ISSUE TITLE
Add additional data to participant json info?

### ISSUE THREAD

**Issue by derekshull** [twilio/twilio-video.js#221]
Is it possible to attach a piece of data to the information coming from the web sockets for a participant?  For instance: if I wanted to have a user role added, how could I attach the user role to the participants json that's given to a user when the participant joins the room?

**Comment by manjeshbhargav** [comment]
Hi @derekshull ,

We do not support custom extensions to our Room Signaling Protocol messages. However, you could take advantage of the Participant's `.identity` field to signal a user role. For ex:
```javascript
const identity = 'moderator';
const token = getToken(identity);
const room = await Twilio.Video.connect(token, { name: 'my-cool-room' });
room.on('participantConnected', participant => {
  if (participant.identity === 'speaker') {
    // do something.
  }
});
```

Please let me know if this works for you.

Thanks,

Manjesh Malavalli

**Comment by derekshull** [comment]
@manjeshbhargav could that identity be a json object instead of a string?

**Comment by manjeshbhargav** [comment]
@derekshull ,

It has to be a string. So you could set the `.identity` to a stringified JSON, as long as its not too long.

Thanks,

Manjesh Malavalli
