### ISSUE TITLE
Adding a data attribute to audio/video

### ISSUE THREAD

**Issue by derekshull** [twilio/twilio-video.js#227]
I'm trying to add a data attribute (something like data-id='${identity}') to the audio or video element.  When I try the following code I get the error that setAttribute isn't a function:

```
// Attach the Tracks to the DOM.
export const attachTracks = function attachTracks(participant, tracks, container) {
    tracks.forEach(function attachEachTrack(track) {
        track.setAttribute('data-id', participant.identity);
        container.appendChild(track.attach());
    });
};
```

Is the element not represented by `track`?

**Comment by manjeshbhargav** [comment]
Hi @derekshull ,

The `track` is an instance of `LocalTrack`, not a DOM element. `track.attach()` returns an `audio|video` DOM element, on which you can set your attribute like this:
```javascript
const domEle = track.attach();
domEle.setAttribute('data-id', participant.identity);
container.appendChild(domEle);
```
Thanks,

Manjesh Malavalli

**Comment by derekshull** [comment]
Thanks!
