### ISSUE TITLE
Using twilio-conversations in node

### ISSUE THREAD

**Issue by Cameron2920** [twilio/twilio-video.js#23]
Hi guys,

This is not really an issue because I assume this library was only meant to be used in a browser, but I am trying to use this library in node. Here is the code I'm trying to run in node

` 
        var accessToken = "my access token";

        var accessManager = new Twilio.AccessManager(accessToken);
        this.conversationsClient = new Twilio.Conversations.Client(accessManager);
        this.conversationsClient.listen().then(
            function() {
                console.log('ready for invites');
                conversationsClient.on('invite', function (invite) {
                    console.log('Incoming invite from: ' + invite.from);
                });
            },
            function (error) {
                console.log('Could not connect to Twilio: ' + error.stack);
            }
        );`

I then send an invite from the starter app to this client and then I get the following

<pre>
 ready for invites
  node_modules/sip.js/src/SIPMessage.js:485
  this.server_transaction.receiveResponse(code, response).then(onSuccess, onFailure);
                         ^

TypeError: Cannot read property 'receiveResponse' of null
    at Object.IncomingRequest.reply (node_modules/sip.js/src/SIPMessage.js:485:26)
    at EventEmitter.UA.receiveRequest (node_modules/sip.js/src/UA.js:665:19)
    at Object.Transport.onMessage (node_modules/sip.js/src/Transport.js:308:17)
    ...</pre>

This looks like the same issue as this @markandrus posted to sip.js [https://github.com/onsip/SIP.js/issues/75](url). Do you have any suggestions on how to get around this?

**Comment by markandrus** [comment]
Hi @Cameron2920,

Thanks for the report. In the future, I'd love to see this library used from Node, e.g. with some server-side WebRTC library. Until then, depending on what you are trying to do, you may wish to simply "fake" WebRTC support in your Node build. For an example of this, see [test/lib/mockwebrtc.js](https://github.com/twilio/twilio-conversations.js/blob/master/test/lib/mockwebrtc.js). Note that the implementation there may not be suitable for all cases (e.g., the dummy SDP is passes around may cause a `setRemoteDescription` error if passed to remote Clients).

What would you like to achieve with Node?

**Comment by Cameron2920** [comment]
Hi @markandrus,

I stumbled across [test/lib/mockwebrtc.js](https://github.com/twilio/twilio-conversations.js/blob/master/test/lib/mockwebrtc.js) and I was able to get it working on node by using a node-webrtc client (I ended up using this one [electron-webrtc](https://github.com/mappum/electron-webrtc)). My goal is to record a call on a node server, but the problem is that none of the node webrtc clients support media streams, so I think I'm out of luck. I haven't completely given up yet, so I'll let you know if I make any progress.

**Comment by markandrus** [comment]
@Cameron2920 have you tried https://github.com/vmolsa/webrtc-native? It supports MediaStreams I believe.

**Comment by Cameron2920** [comment]
I hadn't seen that one yet, but I'm having problems building that library on my computer. I've decided that recording a call will be much easier with [https://github.com/meetecho/janus-gateway](https://github.com/meetecho/janus-gateway) and then letting twilio handle the peer to peer connections. I'll let you know if I ever do get the twilio video library working on node, but for now I am okay with closing this issue.

Thanks for the help, @markandrus!
