### ISSUE TITLE
I can not get VideoTrack 

### ISSUE THREAD

**Issue by pekubu** [twilio/twilio-video.js#235]
I can not get VideoTrack when using google chrome 63 on android, I have tested on firefox and it works normal. Please check my help.

Here is the console log.
![image](https://user-images.githubusercontent.com/26251116/33920972-98d6d2b0-dff3-11e7-8390-7307c34a178f.png)

**Software versions:**

 - [ ] Browser(s):google chrome 63 
 - [ ] Operating System:Android 
 - [ ] twilio-video.js:
 - [ ] Third-party libraries (e.g., Angular, React, etc.): Angularjs

**Comment by pekubu** [comment]
I checked on google chrome 60, and it also does not work.

**Comment by markandrus** [comment]
Hi @pekubu,

Is this issue distinct from #236 or can we consolidate them? If it is distinct, can you please share a Room SID?

The warnings you see about distrusted certificates can be ignored. They are known (https://github.com/twilio/twilio-video.js/issues/224) and we will fix the before Chrome 70 ships. They should not affect video chats.

Mark

**Comment by markandrus** [comment]
Let's track on #236.
