### ISSUE TITLE
Safari LTE Connection Issues

### ISSUE THREAD

**Issue by Westbrook** [twilio/twilio-video.js#241]
Discussed this with Rob Brazier on the team at Twilio, who was able to track this down as an issue on the Safari end super fast, BUT iPhones connecting over IPv6 are having trouble establishing an ICE connection when using LTE. The issue has been raised to Safari via https://bugs.webkit.org/show_bug.cgi?id=181009 and subsequently imported into the internal bug tracker at Apple. Devices with IPv4 based SIM cards don't exhibit this issue, so I'd like to think that means it's not going to be crazy difficult for them to track down and we get a fix before too long.

Hopefully this can save the next person some time when they find themselves debugging this in the wrong place, as I did. Fingers crossed a solution comes to bear on their end soon!

**Comment by mding5692** [comment]
Hi, having similar issues with most recent v1.18.1 of twilio-video.js on iphones on LTE, seems also very laggy when it does work.

**Comment by manjeshbhargav** [comment]
Hi @Westbrook , 

It looks like the webkit bug has been fixed. Please let me know if that has solved the issue you were facing.

@omacesc ,

We do not support cordova at this point, so I'm not sure if its using a version of WebView Safari in which the webkit bug has been fixed.

@mding5692 ,

On LTE, it depends on your uplink and downlink bandwidth and availability. Can you please create a separate issue with more details (Room SIDs where you observe this lagging)?

Thanks,

Manjesh Malavalli
JSDK Team
