### ISSUE TITLE
Use Twilio Client with Twilio Video?

### ISSUE THREAD

**Issue by acoolprogrammer123** [twilio/twilio-video.js#242]
Is it possible to use the Twilio Client with Twilio Video?

I want a video participant to be able to bring a phone call into the video, with each of the video participants hearing the caller, and the caller hearing the audio from each of the video participants.

I recognize that if the video participant that brought the caller in left (closed their page), it would also disconnect the caller.  This is OK for my use case.

**Comment by rfbrazier** [comment]
Yes, it's possible to use these two SDKs side-by-side. Let us know if you have any questions!

**Comment by acoolprogrammer123** [comment]
Ok, since you say it is possible I did a bit more digging, but I am having trouble making the leap of how to get these two to work together.  This might be more of a Client question

**Step 1:** Get the remote audio of the audio call (assuming if a conference is called, all remote callers are included in this track)
```
var connection = Twilio.Device.connect();
var remoteAudioTrack = connection.getRemoteStream();
```

**Step 2:** Publish this remote track to the local participant of the video call
```
room.localParticipant.publishTrack(remoteAudioTrack, {
    name: 'POTS PARTICIPANTS'
  });
```

_At this point I assume that the video participants can hear the audio from the people who have dialed into a Twilio Conference._  

**Step 3:** Collect the audio of the remote video participants and push it to the client
```
room.participants.forEach(function(participant) {
    participant.audioTracks.forEach(function(track) {
    //??? Not seeing anything on either Twilio.Device or Twilio.Connection that allows me to push audio to it. 
});
});
```
Also wondering I am missing a more streamlined way to get the sum total of all remote audio that the local participant is hearing from the room

**Comment by rfbrazier** [comment]
I think the model you want is a bit simpler:

* Connect all participants to a Twilio Conference for audio only. Share audio tracks exclusively through the Conference.
* Connect all participants to a Twilio Room for video only. Share video tracks exclusively through the Room.

Let me know if you have other questions. Thanks!

**Comment by acoolprogrammer123** [comment]
My typical use case would be a 4 way, with only one of the participants if any joining in via a regular phone call.

For those times, I am then paying .0018 for the conference + .004 for the client + .0047 for the video or a  2.25x price increase (or higher if I am only doing a 3 way since the video pricing would be lower) for 3 of the participants who don't necessarily need to be using the client for audio.

 I could write additional logic to split the video to a video/conference hybrid when needed, but then recordings are split in multiple places and there is potentially an audio disruption for the other participants as everyone transitions from video audio to video client.

Not saying your solution won't work, but it is a pretty ugly work around for "I would like to bring one phone call into the video conference".

**Comment by manjeshbhargav** [comment]
Hi @acoolprogrammer123 ,

You can now [add voice Participants to a Video Room](https://www.twilio.com/docs/video/adding-programmable-voice-participants-video-rooms). Please let me know if this helps.

Thanks,

Manjesh Malavalli
JSDK Team
