### ISSUE TITLE
Missing trackAdded events for the next published tracks

### ISSUE THREAD

**Issue by hugomallet** [twilio/twilio-video.js#248]
Hi,

Once a track has been added, next trackadded events are not fired (peer seems to not receive at all the new track). If i unpublish then republish  every tracks at once after a delay, it works as expected.

I have this issue on **chrome mac last version**. 
Rooms are in **p2p mode**.
It may relates to **issue #212**.

To reproduce you can use this gist : 
https://gist.github.com/hugomallet/c80c5d2bcbfb7fd26a205a1726e93f8b

Code : 
```js
const { connect } = window.Twilio.Video;

const params = new URLSearchParams(location.hash.replace(/^#/, ''));

let token = params.get('token');
const publish = params.has('publish');

if (!token) {
	token = window.prompt('Add Twilio API token to URL hash (/#token=...)');
	params.set('token', token);
	location.hash = params;
}

const onTrackAdded = track => {
	console.log('trackAdded', track.name);
};

const onParticipantConnected = participant => {
	console.log('participantConnected', participant.identity);
	participant.on('trackAdded', onTrackAdded);
	participant.tracks.forEach(onTrackAdded);
};

const connectRTC = (tok, roomName) => {
	return connect(tok, {
		name: roomName,
		audio: false,
		video: false,
		logLevel: {
			// default: 'debug',
			// media: 'debug',
			// signaling: 'debug',
			// webrtc: 'debug'
		}
	});
};

const pub = room => {
	navigator.mediaDevices
		.getUserMedia({ audio: false, video: true })
		.then(stream => {
			room.localParticipant.publishTrack(stream.getTracks()[0])
				.then(({ trackName }) => { console.log('pub', trackName); });
		});
};

connectRTC(token, 'test-room')
	.then(room => {
		console.log('connected', room);
		room.on('participantConnected', onParticipantConnected);
		room.participants.forEach(onParticipantConnected);

		if (publish) {
			pub(room);
			setTimeout(() => { pub(room); }, 3000);
		}
	})
	.catch(error => {
		console.error(error);
	});
```

**How to proceed using the gist :** 
You will have to open the index.html file on two tabs.

On the first tab add a hash param "token" (to provide a twilio api access token).
ex: file:///index.html#token=abcdefgh1234

On the second tab, you'll need a different token plus a bool param "publish".
ex: file:///index.html#token=abcdefgh123456&publish

**Expected behavior :**  Two trackAdded events should be logged in the console.
**Actual behavior :** Only the first one is displayed.

Thanks,
Hugo

**Comment by markandrus** [comment]
Hi @hugomallet,

Thanks very much for the working code sample! And sorry you are having trouble with this. I converted your code sample to a JSFiddle [here](https://jsfiddle.net/fj5n44o4/2/). The checkbox is for setting `publish` and the "Connect" button will `prompt` for the Access Token. Unfortunately, I could not reproduce your issue this way using twilio-video.js@1.7.0 and two Chrome 63 browsers in a P2P Room. I got both events:

```
// Window 1
connected Room {_events: {…}, _maxListeners: undefined, localParticipant: LocalParticipant, name: "test-room", …}
(index):70 participantConnected bbb
(index):66 trackAdded 076a3062-b6ae-421e-bec2-e1ab5290c758
(index):66 trackAdded 55d6b3ba-93cc-4315-996c-fde347ac949a

// Window 2
connected Room {_events: {…}, _maxListeners: undefined, localParticipant: LocalParticipant, name: "test-room", …}
(index):70 participantConnected aaa
(index):94 pub 076a3062-b6ae-421e-bec2-e1ab5290c758
(index):94 pub 55d6b3ba-93cc-4315-996c-fde347ac949a
```

Do you mind sharing a Room SID with me so that I can take a look server-side?

Thanks,
Mark

**Comment by jeehyukwon** [comment]
I got a same problem too.

I am making a Video Conferencing Application using 'DataTrack', 'VideoTrack' and 'AudioTrack'. When a new participant connected, the participant subscribes all others tracks nicely.

But, the other participants who already connected to the room cannot receive the 'TrackAdded' event for Video and AudioTracks but can receive the 'TrackAdded' event for 'DataTrack'. and also the new participant's `room.participants[...].tracks` doesn't have a child node in  `audioTracks`, `videoTracks` properties.

Can I send a mail for more detailed information?

**Comment by manjeshbhargav** [comment]
Hi @tonyfromundefined , @hugomallet ,

Please open a new issue with fresh Room SIDs if you are still experiencing this issue. Unfortunately, we don't retain logs for really old Rooms.

Thanks,

Manjesh Malavalli
JSDK Team
