### ISSUE TITLE
Occasional "unable to connect to twilio" status.

### ISSUE THREAD

**Issue by pekubu** [twilio/twilio-video.js#251]
We've been using twilio for a while, but recently we've received an error message "Unable to connect to wss: //sdkgw.us1.twilio.com/v1/VideoEvents" .
Please check it help me.
SID: RMc178921d99db1ae69fcb357c394a4387
Error log:
> SIP/2.0 504 Downstream Cancelled
CSeq: 615 INVITE
Call-ID: 5gsfldj286tj2ajqoffl
From: <sip:8328df2c-43ba-4aeb-9e77-e44592e70bcf@endpoint.twilio.com>;tag=dk97gu7b50
To: <sip:orchestrator@endpoint.twilio.com>;tag=42150681_6772d868_0b3a64a2-91a1-466d-800e-ec04111ed41e
Via: SIP/2.0/WSS 127.0.0.1:43092;branch=z9hG4bK6450689;rport=43092
Server: Twilio
Contact: <sip:172.18.5.226:443;transport=wss>
X-Twilio-LegInfo: external
X-Twilio-TlsVerify: true
Content-Length: 0

> aINVITE sip:orchestrator@endpoint.twilio.com SIP/2.0
Via: SIP/2.0/WSS svqsinb0rvs8.invalid;branch=z9hG4bK6450689
Max-Forwards: 70
To: <sip:orchestrator@endpoint.twilio.com>
From: <sip:8328df2c-43ba-4aeb-9e77-e44592e70bcf@endpoint.twilio.com>;tag=dk97gu7b50
Call-ID: 5gsfldj286tj2ajqoffl
CSeq: 615 INVITE
X-Twilio-AccessToken: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImN0eSI6InR3aWxpby1mcGE7dj0xIn0.eyJqdGkiOiJTSzM2ZWMwMjc3NDg2ZTBmMDhmZTEwZDBlMjI5M2I2MThhLTE1MTU1NjgyMTkiLCJpc3MiOiJTSzM2ZWMwMjc3NDg2ZTBmMDhmZTEwZDBlMjI5M2I2MThhIiwic3ViIjoiQUM2ODM5OTE0ZTllNGFhZWNhOWNmODUzOTQyYjhmMzIzOCIsImV4cCI6MTUxNTY1NDYxOSwiZ3JhbnRzIjp7ImlkZW50aXR5IjoiVVNFUjU5NmMzNjYyZTdkOGQzLjQwNTU4MzkzIiwiaXBfbWVzc2FnaW5nIjp7InNlcnZpY2Vfc2lkIjoiSVMzMTJjNmZhZmQ5MTQ0ODU0YWU4MjQyYTQxNDU2MjY0YiJ9LCJ2aWRlbyI6e319fQ.7cbu6seBprPeU0SbTvst5SesKHOMaisugW3mt0UYbWI
Session-Expires: 120
Contact: <sip:bbc4ls2v@svqsinb0rvs8.invalid;transport=wss;ob>
Allow: ACK,CANCEL,INVITE,MESSAGE,BYE,OPTIONS,INFO,NOTIFY,REFER
Supported: outbound, room-signaling, timer
User-Agent: SIP.js/0.7.7
Content-Type: application/room-signaling+json
Content-Length: 3186

> {"peer_connections":[{"description":{"type":"offer","revision":1,"sdp":"v=0\r\no=- 9045664940371370261 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE audio video\r\na=msid-semantic: WMS 545eb9a3-7b21-4a74-b186-22d5a13ab10e\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 110 112 113 126\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:FZae\r\na=ice-pwd:dHkXLxXSmmp12e3cQ5he4swx\r\na=ice-options:trickle\r\na=fingerprint:sha-256 6C:96:CF:76:47:FA:FA:D3:CF:B5:78:C2:01:3D:EB:F8:BA:FD:F5:C5:E7:C0:2E:E4:F6:BC:0B:66:91:65:69:5B\r\na=setup:actpass\r\na=mid:audio\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=sendrecv\r\na=rtcp-mux\r\na=rtpmap:111 opus/48000/2\r\na=rtcp-fb:111 transport-cc\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=rtpmap:103 ISAC/16000\r\na=rtpmap:104 ISAC/32000\r\na=rtpmap:9 G722/8000\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:106 CN/32000\r\na=rtpmap:105 CN/16000\r\na=rtpmap:13 CN/8000\r\na=rtpmap:110 telephone-event/48000\r\na=rtpmap:112 telephone-event/32000\r\na=rtpmap:113 telephone-event/16000\r\na=rtpmap:126 telephone-event/8000\r\na=ssrc:2248287641 cname:zLXPJ2gcw1BMmgKo\r\na=ssrc:2248287641 msid:545eb9a3-7b21-4a74-b186-22d5a13ab10e a0d858f9-a3e5-4b46-9a0e-f8d4ad62b199\r\na=ssrc:2248287641 mslabel:545eb9a3-7b21-4a74-b186-22d5a13ab10e\r\na=ssrc:2248287641 label:a0d858f9-a3e5-4b46-9a0e-f8d4ad62b199\r\nm=video 9 UDP/TLS/RTP/SAVPF 96 98 100 102 127 97 99 101 125\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:FZae\r\na=ice-pwd:dHkXLxXSmmp12e3cQ5he4swx\r\na=ice-options:trickle\r\na=fingerprint:sha-256 6C:96:CF:76:47:FA:FA:D3:CF:B5:78:C2:01:3D:EB:F8:BA:FD:F5:C5:E7:C0:2E:E4:F6:BC:0B:66:91:65:69:5B\r\na=setup:actpass\r\na=mid:video\r\na=extmap:2 urn:ietf:params:rtp-hdrext:toffset\r\na=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:4 urn:3gpp:video-orientation\r\na=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay\r\na=recvonly\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=rtpmap:96 VP8/90000\r\na=rtcp-fb:96 ccm fir\r\na=rtcp-fb:96 nack\r\na=rtcp-fb:96 nack pli\r\na=rtcp-fb:96 goog-remb\r\na=rtcp-fb:96 transport-cc\r\na=rtpmap:98 VP9/90000\r\na=rtcp-fb:98 ccm fir\r\na=rtcp-fb:98 nack\r\na=rtcp-fb:98 nack pli\r\na=rtcp-fb:98 goog-remb\r\na=rtcp-fb:98 transport-cc\r\na=rtpmap:100 H264/90000\r\na=rtcp-fb:100 ccm fir\r\na=rtcp-fb:100 nack\r\na=rtcp-fb:100 nack pli\r\na=rtcp-fb:100 goog-remb\r\na=rtcp-fb:100 transport-cc\r\na=fmtp:100 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f\r\na=rtpmap:102 red/90000\r\na=rtpmap:127 ulpfec/90000\r\na=rtpmap:97 rtx/90000\r\na=fmtp:97 apt=96\r\na=rtpmap:99 rtx/90000\r\na=fmtp:99 apt=98\r\na=rtpmap:101 rtx/90000\r\na=fmtp:101 apt=100\r\na=rtpmap:125 rtx/90000\r\na=fmtp:125 apt=102\r\n"},"id":"fbbdf712-a1ee-48b7-b7db-19645c9d85ca"}],"name":"RMc178921d99db1ae69fcb357c394a4387","participant":{"revision":1,"tracks":[{"enabled":true,"id":"a0d858f9-a3e5-4b46-9a0e-f8d4ad62b199","kind":"audio","name":"a0d858f9-a3e5-4b46-9a0e-f8d4ad62b199"}]},"type":"connect","version":1}

**Comment by Enijar** [comment]
@pekubu I'm having the same issue. Did you fix the issue?

**Comment by jhovad** [comment]
same here

**Comment by reinoutkool** [comment]
same problem here
