### ISSUE TITLE
How to get proper mime type for video recording ?

### ISSUE THREAD

**Issue by playahater** [twilio/twilio-video.js#252]
Hi all,

The session [ room ] recording is working fine.
The question is that when i try to load the returned url in html video element _in firefox only_ I get mime type error. the one i get is application/octet-stream.

```
HTTP “Content-Type” of “application/octet-stream” is not supported. Load of media resource https://com-twilio-us1-video-recording.s3.amazonaws.com/AC401b7a8aa5b679c2ae916b42fae74fe9/RTaff975b80c7a960f4a2291e7291a393d.mkv?X-Amz-Security-Token=somestring failed.
Cannot play media. No decoders for requested formats: application/octet-stream, application/octet-stream, application/octet-stream, application/octet-stream
```

The configuration on twilio control panel is set to use VP8 video codec. Though the same error is thrown for x264.
P.S - Chrome is working fine.

Any help more than welcome.

Thanx in advance.

**Comment by markandrus** [comment]
Hi @playahater,

I see that we need to set the Content-Type to "video/webm" in order to enable playback in Firefox. I've filed a ticket with our Recordings Team to make this change. Will post back when it's done.

Thanks!
Mark

**Comment by playahater** [comment]
Hi @markandrus,

Thanx for quick reply.

Waiting for feedback.

btw .. VRS-511 - can i view this ticket [progress] as twilio logged in user or it is just as a reference ?

Thanx

**Comment by markandrus** [comment]
Sorry, we can't share the ticket (it's internal), so yes—here it is just a reference so we can link GitHub and our internal work together.

**Comment by playahater** [comment]
Hi @markandrus,

any news on progress. Perhaps some rough eta on this issue ?

Thanx in advance,
Best

**Comment by igracia** [comment]
Hi @playahater! Sorry for the late response. This was pushed back a bit, but we'll be tackling this issue in our next sprints, and hope for the fix to be deployed in a couple of weeks. Sorry for the inconveniences and thanks from bringing this up!

**Comment by igracia** [comment]
Hi @playahater, haven't forgotten about this. Just got pushed back a bit more. Don't despair!

**Comment by playahater** [comment]
Hi @igracia,

Eager to see it deployed on production.
Thanx for feedback and effort.

Best

**Comment by igracia** [comment]
@playahater so the pre-signed URL that AWS generates now the following URL
```
https://xxxx.s3.amazonaws.com/ACxx/RTxx.mka?response-content-type=audio%2Fx-matroska&X-Amz-Security-Token=XXXXXX&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20180301T164346Z&X-Amz-SignedHeaders=host&X-Amz-Expires=...
```
Note the `response-content-type=audio%2Fx-matroska` part. wget correctly gets the content type

```
Connecting to xxxxxxx.s3.amazonaws.com (xxxxxx.s3.amazonaws.com)|xx.xx.xx.xx|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5156256 (4.9M) [audio/x-matroska]
```
This hasn't been deployed yet, but will hopefully be deployed next week. Would this behavior cover your use case?

**Comment by playahater** [comment]
Hi @igracia,

if the header is correctly set, then it covers the use case.
Thanx for effort. Will wait until it is deployed and do a round of testing.

Best

**Comment by igracia** [comment]
@playahater the fix has been deployed. You should be getting the following content types
```
vp8 -> video/webm
opus -> audio/webm
pcmu -> audio/x-matroska
h264 -> video/x-matroska
```
This will work fine for vp8 and opus, while pcmu and h264 are a different beast. From [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats#MP4_H.264_(AAC_or_MP3))

>Since H.264 is currently not a royalty free format, it is unfit for the open web platform, according to Mozilla [1, 2], Google [1, 2] and Opera. However, since royalty free formats are not supported by Internet Explorer and Safari, Mozilla has decided to support the format anyway, and Google never fulfilled their promise to remove support for it in Chrome.

**Comment by markandrus** [comment]
Thanks, @igracia! @playahater if you have any other issues, feel free to re-open this or a new issue.
