### ISSUE TITLE
isSupported false on Chrome app on iPad

### ISSUE THREAD

**Issue by ihatecodinglikeking** [twilio/twilio-video.js#253]
Hi I am using `isSupported` check from video.js 

When I am using Safari in iOS 11.2.2 on iPad 

----- Browser: Safari `isSupported` is true
----- Browser: Chrome `isSupported` is false, while creating a call its giving `getUserMedia is not supported error` 

**Software versions:**

 - [ ] Browser(s): Chrome 63
 - [ ] Operating System: iOS

**Comment by dannycohn** [comment]
Based on [this](https://stackoverflow.com/questions/45055329/does-webkit-in-ios-11-beta-support-webrtc) SO thread, Chrome on iOS 11+ does not support WebRTC

**Comment by ihatecodinglikeking** [comment]
Ohhh... 
any idea about Firefox?

**Comment by dannycohn** [comment]
I believe Firefox on iOS is also based on WKWebView, so the same limitations would apply.  I'd be happy to be wrong though
