### ISSUE TITLE
Simulcast behavior: Start out with better quality and degrade vs start with poor quality and improve?

### ISSUE THREAD

**Issue by randallb** [twilio/twilio-video.js#254]
Hey everyone,

We're testing VP8 Simulcast, which we love BTW. We notice the behavior of VP8 simulcast is to first connect using the lowest bandwidth available, and then progressively improve until it achieves the best possible connection, typically 30 seconds into the connection. This is great in most usecases, except ours. See, our most important time is the first 30 seconds of a broadcast. When our rendering servers connect, we typically have about 5-8 seconds to spin up the webrtc connection. The bad news for our users is that the most important part of the show is the first 30 seconds of the show.

Do you have any suggestions for us how to use group rooms, simulcasting and how to mitigate the spin up time from vp8 simulcast? We're trying to figure out how to allow more users in our sessions.

**Comment by manjeshbhargav** [comment]
Hi @randallb ,

The video quality ramp-up should be significantly quicker now, especially in Group Rooms. Please feel free to open a new issue with more platform and browser details (and Room SIDs) if you're still experiencing problems.

Thanks,

Manjesh Malavalli
JSDK Team
