### ISSUE TITLE
How to measure the video/audio bandwidth in production?

### ISSUE THREAD

**Issue by lightbringer2994** [twilio/twilio-video.js#256]
**Question**

I need to measure the bandwidth used for video and auido for different clients in production. The `room.getsStats` function doesnt seem to return this information and to call the webRTC getStats api, I need the RTCPeerConnection object. Is it possible to access the RTCPeerConnection object in twilio? If not, how can I measure this?

**Comment by manjeshbhargav** [comment]
Hi @lightbringer2994 ,

I don't know if you already found a way to calculate the media bandwidth, but here is an example of using `Room#getStats()` to calculate bandwidth at a particular instance of time:

https://github.com/twilio/video-quickstart-js/blob/master/examples/bandwidthconstraints/src/index.js#L119

Please let me know if this is helpful.

Thanks,

Manjesh Malavalli

**Comment by lightbringer2994** [comment]
Hi, @manjeshbhargav , thanks for the snippet. I had indeed found a way to calculate the media bandwidth :)
