### ISSUE TITLE
Can't connect to any other media region than us1

### ISSUE THREAD

**Issue by tillkruss** [twilio/twilio-video.js#259]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.

**Code to reproduce the issue:**

```js
Video.connect('token', {
    realm: 'us2',
});
```

**Expected behavior:**

Connect to Twilio.

**Actual behavior:**

```
OPTIONS https://ecs.us2.twilio.com/v1/Configuration net::ERR_NAME_NOT_RESOLVED

Failed to get ICE servers (using defaults): ConfigurationAcquireFailedError {code: 53500, stack: "TwilioError: Unable to acquire configuration

WebSocket connection to 'wss://endpoint.us2.twilio.com/' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED
```

**Software versions:**

 - [x] Browser(s): Google Chrome 63.0.3239.132
 - [x] Operating System: macOS 10.13.3
 - [x] twilio-video.js: 1.7.0
 - [x] Third-party libraries (e.g., Angular, React, etc.): Vue.js

**Comment by markandrus** [comment]
Hi @tillkruss,

`realm` is not a public API—it's private and subject to change. 

We use it internally when testing our dev and stage environments. It actually controls the _signaling_ region, not the media region. There is currently no client-side API in any of our SDKs (JavaScript, iOS, or Android) for setting media region. Instead, it must be set via the REST API (see [here](https://www.twilio.com/docs/api/video/rooms-resource)). Would you like to be able to specify it when creating a Room client-side? If so, I can forward this feature request on to our PMs.

Thanks,
Mark

**Comment by tillkruss** [comment]
Aha, okay. So if I create a room in `us2` and connect the client will connect to `us2` automatically?

**Comment by markandrus** [comment]
Correct 👍

**Comment by sfakir** [comment]
Just to clarify:

1) Client sided-rooms do not allow to be on a specific region. Correct?
2) To which region do they connect to?

**Comment by tmikoss** [comment]
Is there a significant cost to implementing `mediaRegion` setting on clientside rooms? I'd very much love to have it controllable there.
