### ISSUE TITLE
Error: Wrong name on bower.io and outdated library version

### ISSUE THREAD

**Issue by 5h1rU** [twilio/twilio-video.js#26]
The documentation says:

`bower install --save twilio-video` but isn't found

I did a small research and find the `twilio-conversations V0.13.10` bower package.

Is possible get the last version on bower?

**Comment by markandrus** [comment]
Hi @5h1rU,

Sorry about that. Please try again, e.g.

```
bower install twilio-video#1.0.0-beta2 
```

Mark

**Comment by 5h1rU** [comment]
That's working @markandrus.

thanks
