### ISSUE TITLE
Force HD video

### ISSUE THREAD

**Issue by tillkruss** [twilio/twilio-video.js#260]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.

Is there a way to force a higher video resolution and frame rate. Chrome doesn't seem to care much about my requested dimensions/frame rate. I don't mind high CPU usage.

**Code to reproduce the issue:**

```js
Video.connect(token, {
    video: {
        width: { min: 856, ideal: 1280, max: 1920 },
        height: { min: 480, ideal: 720, max: 1080 },
        frameRate: { min: 18, ideal: 24, max: 26 },
    }
});

this.conversation.getStats().then(stats => {
    console.log(stats[0].localVideoTrackStats[0].dimensions);
    console.log(stats[0].localVideoTrackStats[0].frameRate);
});
```

**Expected behavior:**

```
1280×1920
24
```

**Actual behavior:**

```
640×360
15
```

**Software versions:**

 - [x] Browser(s): Google Chrome 63.0.3239.132
 - [x] Operating System: macOS 10.13.3
 - [x] twilio-video.js: 1.7.0
 - [x] Third-party libraries (e.g., Angular, React, etc.): Vue.js

**Comment by markandrus** [comment]
Hi @tillkruss,

So the constraints you passed at `connect` control the resolution and frame rate of the LocalVideoTrack acquired via getUserMedia in the browser. You should be able to confirm, if you haven't already, the captured resolution by checking your LocalVideoTrack's `dimensions`:

```js
console.log([...this.conversation.localParticipant.videoTracks.values()][0].dimensions);
```

WebRTC may still downscale the video depending on CPU usage, network, etc. We don't have direct control over this, however there is a proposed WebRTC API our library could use, [RTCDegradationPreference](https://www.w3.org/TR/webrtc/#dom-rtcrtpparameters-degradationpreference). We have been discussing this on the team recently. Setting "maintain-resolution" might at least keep your expected width and height (good for screen share), while setting "maintain-framerate" might at least keep your frame rate at 24 fps (good for webcam). Unfortunately, I don't know of any options to maintain both exactly.

**Comment by tillkruss** [comment]
@markandrus: That would be amazing. Some kind of way to enforce quality if necessary. There is also settings like `googCpuOveruseDetection`. Not sure if that's still working.

**Comment by masudhossain** [comment]
Has this been implemented, yet?

**Comment by manjeshbhargav** [comment]
Hi @tillkruss , @masudhossain ,

You can use `{ width: { exact: 1920 }, height: { exact: 1080 }, frameRate: 3 }` instead of `min`, `max`, `ideal` in order to enforce capture quality for screen share (and camera) tracks.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by ryango** [comment]
RTCDegradationPreference is available now - is it possible to set this in twilio video?

**Comment by ryango** [comment]
Looks like you can set contentHint on the mediaStreamTrack, and in my testing, this behaves as expected
https://www.w3.org/TR/mst-content-hint/
`localTracks.forEach(track => {
      if (track.kind === 'video') {
        track.mediaStreamTrack.contentHint = 'detail';
      }
    });`

**Comment by anil1712** [comment]
@tillkruss which solution works for you? I am also facing the issue. Please help me to get out of it.
