### ISSUE TITLE
Chrome: Device not found

### ISSUE THREAD

**Issue by theDude30** [twilio/twilio-video.js#266]
- [X ] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [ X] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [X ] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.

ISSUE:
on dell laptop with integrated webcam,when using CreateLocalTracks with audio:true,video:true we receive the following error saying that device not found:
<img width="858" alt="screen shot 2018-02-15 at 08 19 19" src="https://user-images.githubusercontent.com/5785389/36243934-bfa71a42-122c-11e8-87dc-72b1cdacddca.png">

When we ran the webcam test page, it worked:
https://webrtc.github.io/samples/src/content/getusermedia/gum/

When using the same application in firefox it worked as well.

Code that we used to create local tracks:
 let constraints={video:true,audio:true};
Video.createLocalTracks(constraints).then((localTracks)=> {.....

**Software versions:**

 - [ X] Browser(s): Chrome 64
 - [X ] Operating System: Windows 10
 - [ X] twilio-video.js: 1.7.0
 - [ X] Third-party libraries (e.g., Angular, React, etc.):
React

**Comment by markandrus** [comment]
@theDude30 in the logs you shared, I see that `createLocalTracks` was called 4 times at least. Does the issue happen if you only call it once? What if you use just `createLocalVideoTrack`? Mind including a JSFiddle with the minimal repro example? AFAICT, twilio-video.js shouldn't behave any differently. Also, when you checked off that the Quickstart works, does that mean the Quickstart works on the Dell laptop?

**Comment by ccnokes** [comment]
@theDude30 I think this happens when there are no available media devices. If I start a VM (VMs tend to not have access to the hosts' media devices) and just use the native DOM methods I get this error: 

![image](https://user-images.githubusercontent.com/1610343/43413309-f6961c6e-93ec-11e8-9edd-55af20bfb5ef.png)

Hope that helps.

**Comment by smkrn110** [comment]
It could occur in different scenarios,

- Chrome browser having issues detecting the devices.
- Some other application already occupied the devices.
- Malfunctioning of devices itself.

I had experience and get it fixed by restarting the Chrome, also restart my PC. 🤔

**Comment by nminchow** [comment]
If anyone winds up here while debugging this: I had to explicitly allow the domain "Microphone" access under "site settings" in chrome. It wasn't being requested automatically, for some reason.
