### ISSUE TITLE
FR: Add Network test to SDK

### ISSUE THREAD

**Issue by ZuSe** [twilio/twilio-video.js#27]
Hey guys,

would it be possible to provide an interface for testing the client constraints with the SDK?
Sth. like here: https://networktest.twilio.com/
Just without the UI part.

I also asked Rob Brazier for it, he told me it is considered to be shipped with the rooms api, however I can't find it atm.

Best,
Patrick

**Comment by markandrus** [comment]
Hi @ZuSe,

We have been chatting about providing such an API internally, and it is in our backlog; however, we haven't landed these APIs yet. There are some challenges to doing so in a P2P environment that can be avoided when a Server is in the picture. We'll update this ticket as we tackle this problem.

Thanks,
Mark

**Comment by jamesgraham** [comment]
Hey @markandrus is there any further update on this? We would also like a tool to provide an environment test for our users.

**Comment by nikolaylukyanchuk** [comment]
I need this as well, any updates ?

**Comment by idosius** [comment]
+1

**Comment by josephbisaillon** [comment]
+1
