### ISSUE TITLE
[Question] Best practice: choosing default audio

### ISSUE THREAD

**Issue by gjdownes** [twilio/twilio-video.js#270]
I have some scenarios where users have multiple audio inputs available from the following method:

     navigator.mediaDevices.enumerateDevices ()

I attempt to choose the default audioinput with the following logic:

	if (device.kind === "audioinput")
	{
		if (device.label && /default/ig.test (device.label))
			vm.audioTracks.defaultDevice = device;

		vm.audioTracks.availableDevices.push (device);
	}

Is there a reliable way to choose the default audio device? I have users complaining they can't hear audio on the other end, leading me to believe I've selected the wrong audio track.

**Comment by markandrus** [comment]
Unfortunately, I think there may be not be a good API to solve this problem. [Media Capture and Streams](https://w3c.github.io/mediacapture-main), which defines `getUserMedia` and `enumerateDevices`, has this to say about `getUserMedia` (which is what twilio-video.js uses in `createLocalTracks`, `createLocalAudioTrack`, etc.):

> User Agents are encouraged to default to using the user's primary or system default camera and/or microphone (when possible) to generate the media stream. User Agents MAY allow users to use any media source, including pre-recorded media files.

And, regarding the "label" attribute on MediaDeviceInfo returned by `enumerateDevices`, it says this:

> A label describing this device (for example "External USB Webcam"). If the device has no associated label, then this attribute MUST return the empty string.

Neither of these APIs are sufficient for answering the question, "Is this audio input actually receiving audio?" So, the solution I've seen deployed in audio and video apps is to instead solve this in the application layer. There are kind of two solutions I've seen:

1. Optimistically start chatting with the default audio device, and prompt the user to select a new one no audio is detected, or
2. Confirm with the user that their microphone is working before allowing them to start chatting.

Which solution you deploy will depend on the type of application experience you want. If it should be really easy to dive into your app and start chatting immediately (and the multiple device inputs is only a problem for a fraction of users), you'll want Option 1. If you're OK delaying the start of a chat until a user has confirmed their microphone and/or camera is working, Option 2 can work. But in either case, you'll want to build

1. A UI for selecting between audio input devices (possibly hidden until you detect the default is invalid), and
2. A UI for showing audio input levels, and detecting when they are zero.

For Item 2, we don't have APIs for volume in twilio-video.js yet, although we did implement them in our Voice SDK. There's a great example by @ryan-rowland over here showing how it works in twilio-client.js over [here](https://github.com/twilio/client-js-1.4-examples): 

<img src="https://user-images.githubusercontent.com/359154/38638376-ebfa831e-3d82-11e8-9754-65102e02e456.gif" width=240 />


For twilio-video.js, we should add these. In the meantime, it's possible to roll your own using the Web Audio APIs by doing something like

```js
const stream = new MediaStream()
stream.addTrack(localAudioTrack.mediaStreamTrack)
// Pipe `stream` into Web Audio APIs to compute audio input level...
```

**Comment by gjdownes** [comment]
Thanks for articulating the workarounds with great detail. I went with picking a default, and giving users the option to switch the input / output devices as you mentioned.

**Comment by gjdownes** [comment]
A follow up to this, are there any general reasons (and tips) you can provide for participants not being able to see/hear the other person? Is there something I can capture in my logs to help with troubleshooting these types of issues? This happens for me even when participants are both using Google Chrome after connecting to the room.

I've seen a bit documented on codecs options; does this factor into audio/video issues between chrome<->chrome and connections with different browsers? 

I couldn't find a "Troubleshooting guide", so I figured I'd ask here.

**Comment by vincentwoo** [comment]
Any updates on adding volume APIs?
