### ISSUE TITLE
(Video|Audio)Track.isStarted

### ISSUE THREAD

**Issue by Westbrook** [twilio/twilio-video.js#279]
I'm trying to get a better understanding of the `isStarted` property of a video or audio track and the associated `started` event and was wondering if there was better documentation than `The VideoTrack started. This means there is enough video data to begin playback.` available for review in this area.

Particularly, I've run into instances where a track is listed as `isStarted=false` and I'm:
1. unsure why
2. desiring to `start()` the track
3. interested in whether I need to manage a more complex API surface to correct this

I've had no trouble adding a screen share track in cases where the main video remained as `isStarted=false`, so possibly I should do some sort of listening for the `started` event and then replace after some interval? Is there some better way to manage tracks that don't flip into `isStarted=true`.

For instance, in RM4a1e8d3d1ca28f834452532112735433, I had two participants connected with audio and video tracks and one (PA882a18e1cd2459ba86f66a79dd28317d) delivering a shared screen for a time. However, while the initial video track for PA882a18e1cd2459ba86f66a79dd28317d was listed in `getVideoTracks()` of participants, it never changed to `isStarted=true` and now there is no reference to that track in the recordings. I'm also interested if there would be somewhere in my dashboard that I could see that track, even though data for is doesn't exist. It made it to the other participant, so it seems that it would be logged somewhere, right?

Thanks in advance for your assistance

**Comment by markandrus** [comment]
Hi @Westbrook,

If `isStarted` remains false on a RemoteTrack, there's typically an error (unless you intentionally `disconnect` from a Room before a RemoteTrack has a chance to start). The most common error that will cause `isStarted` to remain false is a media connection (ICE connection) failure. So, if you receive a RemoteTrack, e.g., in the "trackPublished" (or "trackAdded") event, but that RemoteTrack never raises a "started" event, then something is wrong.

> I've had no trouble adding a screen share track in cases where the main video remained as `isStarted=false`, so possibly I should do some sort of listening for the `started` event and then replace after some interval? Is there some better way to manage tracks that don't flip into `isStarted=true`.

Sorry, I'm not sure I understand: you're saying that, although a "main" (e.g., webcam) RemoteVideoTrack remained not started, you were able to add a screen share (and it did start?). That would indicate some other error than an ICE connection, and we'd appreciate a bug report with a Room SID we could look into.

Regarding whether or not you should do something to manage RemoteTrack, our goal would be that you would not have to and to instead raise, e.g., a "reconnecting" event if we detect your media connection failed and needs to be repaired (something we're working on). You could, though, set a timeout and wait, e.g., up to 10 seconds to see if a RemoteTrack ever does start. If not, it would indicate a problem you may want to raise in the UI. The `getStats` API may also provide information here (e.g., if you see `bytesReceived` is zero or constant, there again may be a media connection error).

We will look into RM4a1e8d3d1ca28f834452532112735433 on the backend.

Thanks,
Mark

**Comment by Westbrook** [comment]
Thanks for the response @markandrus 

Yes, for the call RM4a1e8d3d1ca28f834452532112735433 on participant was delivering both audio and video 100% of their connection and the other was delivering one active audio track and one `isStarted=false` video track from the beginning of the call. Later in the call, that second participant added a shared screen that transmitted fine while the initial video track never emitted a `started` event.

This is something that I'd been told about experientially, but have only recently been able to confirm during an active connection, so it's not a singular problem, though I'm only 80% sure it's been the same on these other calls.  This SID seems to have experienced this same issue if it is helpful in your research: RMfdf8c1876acaa0af0a6f4cf705c04c1f

**Comment by Westbrook** [comment]
@markandrus Thanks for the extensive response.

1) The track in question would have be delivered from a webcam. It would have originated from Chrome 65.0.3325.181 via OSX Intel 10.13, if that's any help. 

2) Look forward to your Fiddle findings. Let me know if there is any further information that I can supply you in this area.

Thanks!

**Comment by Westbrook** [comment]
We actually use the `VP8 & H.264` if that makes any difference.

In both of those rooms noted, if the `frameRateInputs>0` track the same as the `bytesSent=0` track? Could that then be an issue with the webcam returning itself as part of the `getUserMedia` constraints but not being fully connected/accessible somehow? What would be the best ways to debug this on  our end if we run into this again in a testable situation? I'd love to say we could get to a fully repeatable situation, but in that users that have reported this has reported full connectivity on other occasions with the same remote participants, I'm not bullish on doing so.

**Comment by markandrus** [comment]
> In both of those rooms noted, if the frameRateInputs>0 track the same as the bytesSent=0 track? 

Yes.

> Could that then be an issue with the webcam returning itself as part of the getUserMedia constraints but not being fully connected/accessible somehow?

That's what I wonder. For customers experiencing this issue, do you know if they can see themselves or not in the app? Do you show local video and/or ask the user if they can see themselves? If local video is not playing, that would at least rule out any weirdness due to WebRTC.

Here is another idea: set check the `isStarted` property on the LocalVideoTrack; if it's `false`, set an event listener for "started"; if, after some timeout, the LocalVideoTrack hasn't started, consider it failed. The "trackStarted" event is driven by the `oncanplay` event on HTMLMediaElement (see [here](https://github.com/twilio/twilio-video.js/blob/1.8.0/lib/media/track/mediatrack.js#L94)). `oncanplay` is fired "when the user agent can play the media" ([MDN](https://developer.mozilla.org/en-US/docs/Web/Events/canplay)). I only wonder then in this error scenario if the "started" event will fire erroneously or not for the LocalVideoTrack.

**Comment by Westbrook** [comment]
We do show the local video locally, so maybe that rules that out. :/

I should be back to looking at this part of our code tomorrow and the next day, so hopefully I can find some added insight with your notes to date.

**Comment by tylergould** [comment]
Hello there, I believe we're experiencing a similar issue, and would like to offer room SID RM3ab1cc0bf566afc622ba72e9f7bb6663 if it would help you debug.

Our symptoms:

- two users successfully subscribing to each other's cam/microphone
- one user publishes a screen track, and can see the video locally
- the second user can't see the screen track, which is enabled and subscribed, but `isStarted=false`.

@markandrus , can you determine from internal stats if this is indeed the same issue?

In our experience, we've only seen the issue when a Chrome user is publishing their screen stream to a Firefox user, but I'm not 100% confident that this isn't a coincidence.

**Comment by tylergould** [comment]
@Westbrook we determined (w/help from Twilio support) that our issue was related to a bug in the way Firefox negotiates incoming data from hybrid codec rooms. Switching to either VP8- or H264-only rooms in the Twilio dashboard resolved the problem for us. May or may not be feasible depending on your browser support requirements, but thought it might be helpful to somebody to share.

**Comment by Westbrook** [comment]
Thanks @tylergould that's very interesting. It's been too long since I checked, but in the web while there are some quality/performance implications, H264 is supported pretty well in FF/Chrome/Safari, right? I'll see where we can get with that.

I am also running into this sometime with no FF participant, but maybe I'll be able to get the data needed to hunt it down when using a single codec.

**Comment by markandrus** [comment]
@tylergould thanks for the extra context. To re-iterate:

**If you're having trouble with Firefox in Group Rooms using both VP8 _and_ H.264, please use only H.264 _or_ VP8.** This will work around [Firefox Bug 1333879 - Receiving multiple codecs in a SDP answer does not work](https://bugzilla.mozilla.org/show_bug.cgi?id=1333879) until we have a proper fix in our media server.

@Westbrook 

> It's been too long since I checked, but in the web while there are some quality/performance implications, H264 is supported pretty well in FF/Chrome/Safari, right? I'll see where we can get with that.

Yes, it should be pretty well-supported. On mobile or more constrained devices, you sometimes want to be more thoughtful in the codec you choose, based on the availability of hardware encoders. Please let me know if you see an improvement.

> I am also running into this sometime with no FF participant, but maybe I'll be able to get the data needed to hunt it down when using a single codec.

An example of this (no FF participant) would be useful, too. The original Room SIDs you shared have expired, so I can't re-evaluate whether or not those were due to Firefox Bug 1333879. If you encounter this with Chrome-only, then it may even be a separate issue. But more Room SIDs will be helpful.

**Comment by Westbrook** [comment]
Thanks for the update @markandrus. I'll be putting together the some quick reporting for us on this mid-to-late week, so that I should have more actionable data for you then.
