### ISSUE TITLE
Error when connecting between Chrome and Firefox Quantum 59.0.2

### ISSUE THREAD

**Issue by ahey** [twilio/twilio-video.js#280]
Hi there,

I have encountered a new bug when attempting to establish a Twilio Video call between Chrome and Firefox.

 - [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.

**Software versions:**

 - [x] Browser(s): Chrome version: Version 65.0.3325.181 (Official Build) (64-bit) and Firefox Quantum version: 59.0.2 (64-bit)
 - [x] Operating System: MacOS High Sierra 10.13.3
 - [x] twilio-video.js: 1.8.0

**Expected behavior:**

Video call is successfully established between Chrome and Firefox

**Actual behavior:**
Javascript error occurs in Chrome. Please note, I have confirmed that this issue does not occur when using the older Firefox version 58.0.2.

**Steps to reproduce:**

- Start video call in Chrome
- Join call from firefox
- Since this is running in a dev environment on localhost, Firefox Prompts for permission to use the camera and mic. Click Allow.
- A Javascript error occurs in Chrome when attaching the remote video track.

**Logs:**

The following occurs soon after I call the `attach()` method on the `RemoteVideoTrack` instance

2018-03-28 04:46:46.027Z | WARN in [object Object]: Calling setLocalDescription with an RTCSessionDescription of type "answer" failed with the error "Failed to set local answer sdp: Failed to push down transport description for video: Applying an answer transport description without applying any offer.".
log @ application-e9b2fa75221d4e79efbd.js:10343
warn @ application-e9b2fa75221d4e79efbd.js:10391
(anonymous) @ application-e9b2fa75221d4e79efbd.js:96367
Promise.catch (async)
_setLocalDescription @ application-e9b2fa75221d4e79efbd.js:96365
(anonymous) @ application-e9b2fa75221d4e79efbd.js:96136
Promise.then (async)
_answer @ application-e9b2fa75221d4e79efbd.js:96132
_updateDescription @ application-e9b2fa75221d4e79efbd.js:96460
transition @ application-e9b2fa75221d4e79efbd.js:96668
gotKey @ application-e9b2fa75221d4e79efbd.js:24894
Promise.then (async)
bracket @ application-e9b2fa75221d4e79efbd.js:24892
update @ application-e9b2fa75221d4e79efbd.js:96654
(anonymous) @ application-e9b2fa75221d4e79efbd.js:95710
getConfigurationSucceeded @ application-e9b2fa75221d4e79efbd.js:95705
Promise.then (async)
update @ application-e9b2fa75221d4e79efbd.js:95704
_update @ application-e9b2fa75221d4e79efbd.js:98395
EventEmitter.emit @ application-e9b2fa75221d4e79efbd.js:6473
handleRequestOrResponse @ application-e9b2fa75221d4e79efbd.js:99433
EventEmitter.emit @ application-e9b2fa75221d4e79efbd.js:6473
onInfo @ application-e9b2fa75221d4e79efbd.js:99192
receiveRequest @ application-e9b2fa75221d4e79efbd.js:105047
receiveRequest @ application-e9b2fa75221d4e79efbd.js:106624
receiveRequest @ application-e9b2fa75221d4e79efbd.js:103536
UA.receiveRequest @ application-e9b2fa75221d4e79efbd.js:108819
onMessage @ application-e9b2fa75221d4e79efbd.js:100171
ws.onmessage @ application-e9b2fa75221d4e79efbd.js:100039
application-e9b2fa75221d4e79efbd.js:10343 2018-03-28 04:46:46.028Z | WARN in [object Object]: The SDP was v=0
o=- 6344075251938777656 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE video
a=msid-semantic: WMS d5ea0019-5847-4ed6-ab26-2c9414497a31
m=audio 0 UDP/TLS/RTP/SAVPF 109 9 0 8 101
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=sendrecv
a=rtcp-mux
a=rtpmap:109 opus/48000/2
a=fmtp:109 minptime=10;useinbandfec=1
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=ssrc:2621675788 cname:6DJ8ihJKyv/oyCyj
a=ssrc:2621675788 msid:d5ea0019-5847-4ed6-ab26-2c9414497a31 283f1da9-f3c1-423f-bf55-e21ae8af2691
a=ssrc:2621675788 mslabel:d5ea0019-5847-4ed6-ab26-2c9414497a31
a=ssrc:2621675788 label:283f1da9-f3c1-423f-bf55-e21ae8af2691
m=video 9 UDP/TLS/RTP/SAVPF 120 121 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:81Po
a=ice-pwd:aQ0tMX5Vs00g63GeX0hYNBwq
a=ice-options:trickle
a=fingerprint:sha-256 B3:29:12:26:8E:24:55:D8:F3:AA:28:D9:10:E4:6D:DF:A9:19:8E:8C:D0:D0:7D:A7:E1:61:CA:F0:B6:DA:AA:1F
a=setup:active
a=mid:video
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=extmap:1 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=sendrecv
a=rtcp-mux
a=rtpmap:120 VP8/90000
a=rtcp-fb:120 goog-remb
a=rtcp-fb:120 ccm fir
a=rtcp-fb:120 nack
a=rtcp-fb:120 nack pli
a=rtpmap:121 VP9/90000
a=rtcp-fb:121 goog-remb
a=rtcp-fb:121 ccm fir
a=rtcp-fb:121 nack
a=rtcp-fb:121 nack pli
a=rtpmap:126 H264/90000
a=rtcp-fb:126 goog-remb
a=rtcp-fb:126 ccm fir
a=rtcp-fb:126 nack
a=rtcp-fb:126 nack pli
a=fmtp:126 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=ssrc:3628125124 cname:6DJ8ihJKyv/oyCyj
a=ssrc:3628125124 msid:d5ea0019-5847-4ed6-ab26-2c9414497a31 984dd7c7-3474-4ca3-8c37-680461cee736
a=ssrc:3628125124 mslabel:d5ea0019-5847-4ed6-ab26-2c9414497a31
a=ssrc:3628125124 label:984dd7c7-3474-4ca3-8c37-680461cee736

log @ application-e9b2fa75221d4e79efbd.js:10343
warn @ application-e9b2fa75221d4e79efbd.js:10391
(anonymous) @ application-e9b2fa75221d4e79efbd.js:96371
Promise.catch (async)
_setLocalDescription @ application-e9b2fa75221d4e79efbd.js:96365
(anonymous) @ application-e9b2fa75221d4e79efbd.js:96136
Promise.then (async)
_answer @ application-e9b2fa75221d4e79efbd.js:96132
_updateDescription @ application-e9b2fa75221d4e79efbd.js:96460
transition @ application-e9b2fa75221d4e79efbd.js:96668
gotKey @ application-e9b2fa75221d4e79efbd.js:24894
Promise.then (async)
bracket @ application-e9b2fa75221d4e79efbd.js:24892
update @ application-e9b2fa75221d4e79efbd.js:96654
(anonymous) @ application-e9b2fa75221d4e79efbd.js:95710
getConfigurationSucceeded @ application-e9b2fa75221d4e79efbd.js:95705
Promise.then (async)
update @ application-e9b2fa75221d4e79efbd.js:95704
_update @ application-e9b2fa75221d4e79efbd.js:98395
EventEmitter.emit @ application-e9b2fa75221d4e79efbd.js:6473
handleRequestOrResponse @ application-e9b2fa75221d4e79efbd.js:99433
EventEmitter.emit @ application-e9b2fa75221d4e79efbd.js:6473
onInfo @ application-e9b2fa75221d4e79efbd.js:99192
receiveRequest @ application-e9b2fa75221d4e79efbd.js:105047
receiveRequest @ application-e9b2fa75221d4e79efbd.js:106624
receiveRequest @ application-e9b2fa75221d4e79efbd.js:103536
UA.receiveRequest @ application-e9b2fa75221d4e79efbd.js:108819
onMessage @ application-e9b2fa75221d4e79efbd.js:100171
ws.onmessage @ application-e9b2fa75221d4e79efbd.js:100039
0e3706fc-02d4-4022-8114-6dd4d54eb852:1 Uncaught (in promise) MediaClientLocalDescFailedError {code: 53400, stack: "TwilioError: Client is unable to create or apply a…packs/application-e9b2fa75221d4e79efbd.js:96146:9", message: "Client is unable to create or apply a local media description", name: "TwilioError"}

The exception is [being thrown from here](https://github.com/twilio/twilio-video.js/blob/7e82c3424f9f06bd1593047158bb5c506d3b2e76/lib/signaling/v2/peerconnection.js#L559)

With thanks

**Comment by spalmertwilio** [comment]
Twilio Engineers please see support request 1334174 for more logs.  The above was for a rest api peer-to-peer created room.   Customer switched to Group rooms, setting the codecs, and the media region, and it is working.
