### ISSUE TITLE
Memory used for previous calls not destroyed (Memory leak)

### ISSUE THREAD

**Issue by anand-io** [twilio/twilio-video.js#283]
There is a memory leak from every call. Once the call is disconnected the objects used for the calls still exists. Is this intentional?
Here is a sample from the video-quickstart-js.
https://cl.ly/1V2831180k0n

The sample is just for the joining the call alone where less memory is used. If there was more than one participant joins, more memory is used and not destroyed after the call.

**Comment by markandrus** [comment]
Thanks very much for the video, @anand-io — it clearly demonstrates the issue. We have created an epic in our backlog to address memory leaks. I don't think it will be a quick fix (we need to audit, e.g., event listeners we set on HTMLVideoElements, `setInterval`s, etc., both in our code and our dependencies' code—most notably, SIP.js). At this time, I can only recommend working around the issue.

**Comment by anand-io** [comment]
Thanks, @markandrus. Sounds good.

**Comment by ccnokes** [comment]
Just saw a similar thing with tracks leaking the other day. If video tracks aren't disposed of the camera light will stay on even if the user has turned it off, which then makes them feel like they're being creepily watched. Looking forward to the fix on this 👍

**Comment by markandrus** [comment]
> If video tracks aren't disposed of the camera light will stay on even if the user has turned it off

@ccnokes Any LocalAudioTracks and LocalVideoTracks that are acquired via `createLocalAudioTrack`, `createLocalVideoTrack`, and/or `createLocalTracks` should be stopped by calling `stop` when done. This will stop capturing from the hardware, and the webcam light will go off. The memory leak should not affect whether or not the webcam light stays on. If you are seeing issues with this, please open an issue or write to [support@twilio.com](mailto:support@twilio.com) where we can troubleshoot.
