### ISSUE TITLE
Microsoft Edge support

### ISSUE THREAD

**Issue by my-name-was-already-taken** [twilio/twilio-video.js#291]
Microsoft just released the April update for their Windows 10 operating system, which also updates Edge to v17 and apparently bug fixes their WebRTC implementation (kudos to https://github.com/twilio/twilio-video.js/issues/94#issuecomment-384293234 ).
As there are already working cross-browser WebRTC video call implementations out there, it seems like now it's actually possible to get to work (I don't want to reference the competition).

Since the issue "Support for MS Edge 15" #94 hasn't been the most lively discussion so far, I am assuming this is because we as a society just decided to ignore Edge version 15 (I can understand that) and hope that with a new issue humbly asking for Edge support (any version) we can get a roadmap, a rough estimate or any indication whether support will be added at all.

**Comment by kedartoraskar** [comment]
@my-name-was-already-taken thanks for opening this issue and reporting on the Edge v17 update. We will test out the new Edge version with our SDK and report back on our findings in the next week or so.

**Comment by sedenardi** [comment]
Just tested this with `twilio-video v1.1.0` and `Microsoft EdgeHTML 17.17134` and received an error preventing video with this stack trace:

```
Error: Could not complete the operation due to error c004e001. 
    at ChromeRTCPeerConnection
    at PeerConnectionV2 
    at _getOrCreate
    at Anonymous function 
    at run
    at Anonymous function
    at flush
```

Let me know if I can help by testing anything else out.

**Comment by markandrus** [comment]
@syerrapragada has started work on support for Edge in [twilio-webrtc.js](https://github.com/twilio/twilio-webrtc.js) (a dependency of twilio-video.js). We've made some progress, but there are still many quirks to Edge. For example, we are able to crash Edge with our integration tests. If we get some kind of Edge support working, it will almost certainly be "more experimental" than Safari was when we launched support for Safari.

**Comment by sedenardi** [comment]
@markandrus Great, thank you for the progress update.

**Comment by dibari** [comment]
Any further development update for Edge support?

**Comment by manjeshbhargav** [comment]
@dibari ,

We have some very basic use cases working on Edge. We still want to fine-tune our implementation to cover more complex use cases before we think about making it generally available. Please watch this space for updates.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by yleviel-notarize** [comment]
@manjeshbhargav, is there any timeline for Edge support even in a preview release?

**Comment by manjeshbhargav** [comment]
Hi @yleviel-notarize ,

We are testing experimental Edge support right now, and we are aiming to have it released sometime in Q1 of 2019. Please watch this space for updates.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by cmorgenthaler** [comment]
Hi,

How do you deal with the announcement that Microsoft is using Chromium as its browser engine?

Thanks,

Chris

**Comment by ktoraskartwilio** [comment]
@cmorgenthaler - thanks for reaching out. As of now, we are testing experimental support for Edge using ORTC APIs. We are tracking further updates from Microsoft around release timelines for the Chromium based Edge browser. We will provide details accordingly.

**Comment by manjeshbhargav** [comment]
Hi @cormacguerin ,

Microsoft [announced](https://blogs.windows.com/windowsexperience/2018/12/06/microsoft-edge-making-the-web-better-through-more-open-source-collaboration/) that they have stopped developing on the current version of Edge and will move to a Chromium compatible version sometime in the future. In light of this, we have put our Edge Support effort on hold.

We will revisit once there is some movement by Microsoft in this regard.

Thanks,

Manjesh Malavalli
JSDK Team
