### ISSUE TITLE
Does changes in track dimensions indicate that the track has started?

### ISSUE THREAD

**Issue by katranci** [twilio/twilio-video.js#296]
Hello,

I am watching changes in track dimensions in order to tell if they are ready to be displayed to our users. Today, we have seen a behaviour where the dimensions were changed but the video was still black and stayed black (room RMd76a0a3de52fd9fe701d6b0607aff499). Is my approach not reliable or something else might be going on? The reason I chose this approach was because [RemoteVideoTrack#started](https://media.twiliocdn.com/sdk/js/video/releases/1.8.0/docs/RemoteVideoTrack.html#event:started__anchor) was giving false positives sometimes (videos were still black for a short period of time after it was emitted)

Thanks

**Comment by markandrus** [comment]
Hmm, I guess I'm not surprised that there are false positives with "started" (it uses `oncanplay`), although the dimensions changing, yet receiving no frames is surprising. I will try to reproduce.

**Comment by lifeofzero** [comment]
@markandrus any additional insights on this one?
