### ISSUE TITLE
Warn: Failed to publish the LocalVideoTrack: No supported codec

### ISSUE THREAD

**Issue by alielkhateeb** [twilio/twilio-video.js#312]
Hi, 

I am using H264 encoding for the room and I'm forcing users to connect with H264 codec. 

As H264 is implemented in chrome from version 66 onwards, I expected it will work on both Safari and Chrome on android. The issue is on android chrome I still get `warning: Failed to publish the LocalVideoTrack: No supported codec` and the video is not published. And even the subscription to `RemoteVideoTrack` that are added fails for the same reason, may I know is this a problem on my side or is it not supported yet?

**Comment by markandrus** [comment]
It sounds like your Chrome on Android does not support the required H.264 profile level. If you share a Room SID, we can confirm. The issue should be the same as the one described [here](https://github.com/twilio/twilio-video.js/issues/236#issuecomment-359118421).

**Comment by alielkhateeb** [comment]
Room SID: RMac3884573b84f0215b73f864ebc27761

Just a friendly question, is chrome gonna support more profile levels soon? or is it something we can do on our side?

**Comment by markandrus** [comment]
@alielkhateeb in reviewing RMac3884573b84f0215b73f864ebc27761, I see that Participant PA1fafbb114e03becb7a18aba72e97416a fails to publish a LocalVideoTrack and fails to subscribe to a RemoteVideoTrack. And actually, I see that, in this case, it is not an H.264 profile-level issue. PA1fafbb114e03becb7a18aba72e97416a supports only VP8 and VP9, based on the SDP it sends.

> As H264 is implemented in chrome from version 66 onwards

Where did you find mention of this? I could not find this in the Chrome or WebRTC release notes for 66. I do see that there is a flag that can be enabled, [`chrome://flags/#enable-webrtc-h264-with-openh264-ffmpeg`](chrome://flags/#enable-webrtc-h264-with-openh264-ffmpeg).

> Just a friendly question, is chrome gonna support more profile levels soon? or is it something we can do on our side?

Sorry, this all depends on Chrome. I am not sure their exact strategy for adding support.

**Comment by alielkhateeb** [comment]
Thanks for reviewing the room.

So I just have to wait for chrome to add this support. I checked it using [caniuse](www.caniuse.com) 

Here is a screenshot from the website, but obviously they meant the flag only maybe.
![caniuse](https://user-images.githubusercontent.com/20101678/41326304-fc01d2fe-6ef0-11e8-80ff-7d8bdbdb2eac.PNG)

Anyway thanks a lot Mark.

**Comment by keyurpatel87** [comment]
I am getting the same problem. Is there any way to join the room with Both VP8 and H264? Or any way that we can check that is this device browser supports h264 before joining the call?

**Comment by ppriyank40** [comment]
I am facing the same problem. I want to join a room from ios and android devices.But as some android still doesn't support h264, video is not working.
Is there any way to detect h264 support before joining room?
Is there any way to exchange codec between 2 users and then join room after that?
