### ISSUE TITLE
remote tracks not displayed when making call between mobile app and website

### ISSUE THREAD

**Issue by XemaA** [twilio/twilio-video.js#316]
- [ ✓] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [✓ ] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ ✓] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.

**Code to reproduce the issue:**

**Expected behavior:**

Establish a call between two users. one connected from a laptop and the other using an android app ( https://github.com/blackuy/react-native-twilio-video-webrtc)
**Actual behavior:**
remote tracks not displayed, only local tracks
web - web: works as expected
mobile - mobile: works as expected

**Software versions:**

 - [x] Browser(s): Chrome, firefox
 - [x] Operating System: ubuntu, windows
 - [x] twilio-video.js: 1.10 (on web)
 - [x] Third-party libraries (e.g., Angular, React, etc.):  React native https://github.com/blackuy/react-native-twilio-video-webrtc 1.3.8

**Comment by markandrus** [comment]
Hi, can you please include a Room SID?

**Comment by XemaA** [comment]
THis is the Room SID: RM27c64f42c4b47c0331b4d63a5d36b0c8
