### ISSUE TITLE
During simulcast conference if two participants publish video at the same time the tab crashes in Chrome

### ISSUE THREAD

**Issue by anand-io** [twilio/twilio-video.js#319]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.

**Code to reproduce the issue:**

https://github.com/anand-io/video-quickstart-js

**Expected behavior:**

Should not crash

**Actual behavior:**
Chrome crashed

Steps to reproduce:
1) Clone [modified video-quickstart-js](https://github.com/anand-io/video-quickstart-js) in which I changed the "Preview my camera" button to "Toggle my camera" to attach a video track in-between the call, also turned on "simulcast".
2) You need two people/machine to replicate this issue so use ngrok/server.
3) Both participants join the same room
4) Both participants turn on the camera almost at the same time or a one sec delay.
5) one side it should crash(the one that gets "Glare detected; rolling back")

Note: Happening only for simulcast conference.

Video sample:
https://cl.ly/1U1I2r1v3t3a
https://cl.ly/271H3v0J0I32
https://cl.ly/0K0w2M1X3i2M

The crash happens only when this I see this log - "Glare detected; rolling back"

**Software versions:**

 - [x] Browser(s): Chrome
 - [x] Operating System: MacOS and Windows
 - [x] twilio-video.js: 1.10.0(since the simulcast released)
 - [x] Third-party libraries (e.g., Angular, React, etc.): None, reproducible using video-quickstart-js.

**Comment by markandrus** [comment]
@anand-io thanks very much—we'll dig into this and file a bug. My guess is it is a change in behavior in Chrome.

**Comment by anand-io** [comment]
I gotta give you more info. This has been happening since the simulcast release in twilio-video. I didn't get time to replicate that in quick start app and create an issue here that time.
So I don't think this is recent chrome issue.

**Comment by markandrus** [comment]
@anand-io we have fixes for this issue slated to land in 1.12.0:

- https://github.com/twilio/twilio-video.js/pull/347
- https://github.com/twilio/twilio-webrtc.js/pull/30
