### ISSUE TITLE
Websocket errors when using Pace JS

### ISSUE THREAD

**Issue by DJLemkes** [twilio/twilio-video.js#32]
While upgrading from the old `twilio-commons` and `twilio-conversations` libraries, I experienced a rather strange bug when setting up conversations. The client setup would go fine but connecting to a room would cause a `Websocket is closed` error that was visible in the SIP JS debug log. 

Eventually it turned out to be caused by [Pace](http://github.hubspot.com/pace/docs/welcome/), a tiny lib that we use to indicate page load and AJAX call progress. Still don't know what exactly went wrong but in the network tab of the dev console, one could see that the Twilio websocket connection iniator was `pace` instead of `twilio-video`.

In our case, Pace was loaded in the HTML head so that it would also give a page load indication. Removing it and bundling it with the rest of our Javascript fixed our problems.

Don't know who is 'to blame' of this, but thought that some trace of this behaviour might help to prevent debugging headaches for others.

**Comment by markandrus** [comment]
@DJLemkes that's very interesting. Thanks for writing in. We'll take a look and try to reproduce. There do seem to be some issues on the Pace issue tracker regarding WebSockets.

**Comment by acomito** [comment]
@DJLemkes, sounds potentially like my issue: https://github.com/twilio/twilio-video.js/issues/29

I also had some websocket errors coming up and also some of the stack trace pointing to SIP.js

**Comment by markandrus** [comment]
@DJLemkes it would be interesting to know if the recent changes I mentioned [here](https://github.com/twilio/twilio-video.js/issues/28#issuecomment-271441280) or [here](https://github.com/twilio/twilio-video.js/issues/29#issuecomment-271443065) improve things.

**Comment by markandrus** [comment]
@DJLemkes I have a feeling this ought to be addressed in `-beta4` now. Can you please retry and reopen this issue if the problem persists?

Thanks!
Mark

**Comment by kmanaseryan** [comment]
I've got the same issue. I just set `trackWebSockets: false` in Pace.js configuration and it works without the error. 

**Pace.js config:**
```JavaScript
window.paceOptions = {
       ... 
       ajax: {
            trackWebSockets: false
        }
       ...
    };
```

**Versions:**
**twilio-video: 1.6.0**
**pace.js: 1.0.2**

**Comment by akvaliya** [comment]
@kmanaseryan  Can you explain how can i add **Pace.js configuration**? 
I am facing the same issue with angular application. I have added `pace.min.js` in index.html file
