### ISSUE TITLE
Store friendly username for display

### ISSUE THREAD

**Issue by jstarkfaro** [twilio/twilio-video.js#331]
Do you guys plan to add any meta-data fields to the participant api so that we can have a unique ID for the twilio_token but then capture a friendly name to pass to the application we are building so that there can be more than one Bob in a room for instance.  We will have the ability to join as "Anonymous" but we cant do that today because the user must have a unique id to join the room. 

Thanks
Jeff

**Comment by manjeshbhargav** [comment]
Hi @jstarkfaro ,

Thanks for reaching out to us with your question. As of now, we do not have any plans to add meta-data to the Participant API. However, you can generate the `identity` string (used to generate the Access Token) which consists of a display name and a random string (ex: timestamp of when the Participant is joining the Room) separated by a delimiter.

Please let me know if this works for your particular use case.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by markandrus** [comment]
Elaborating on @manjeshbhargav's suggestion, you might also consider specifying a JSON `identity`. You must be careful with the size, though, as `identity` is capped at 128 bytes. See also https://github.com/twilio/twilio-video.js/issues/221

I'll close this ticket for now, but feel free to reach out to video-product@twilio.com to discuss some more.

Mark

**Comment by timscott** [comment]
Participants need to be able to change their display name. If I am not mistaken, `identity` is immutable. This is kind of essential to any non-trivial video conferencing app.
