### ISSUE TITLE
Get Track attached to a Div || Swap Video tracks of two Divs

### ISSUE THREAD

**Issue by shikhar-scs** [twilio/twilio-video.js#332]
## HELP REQ'D

I was implementing multiple participant video calling and to render their tracks, I am iterating the tracks of room.participants and attaching it to newly created Divs. 

Now I have a main Div (the big one)  and several small ones, to show all current participants in the room. So, now, when I click on any of the small Div, I want the video of the mainDiv and the targetted smallDiv to swap so that I can view the smaller one as the main one (the way it happens in all video calling apps) .

I am using a swap function which, though, is swapping the video and audio elements with the respective reqd divs but it stays **static**. 

So, 
1. If I continue my approach, how do I actually swap ?
2. Another way is if I could somehow get the track attached to a div in someway (jquery or any other place I could access). Once, I have the track I can attach it in the normal way 

**Code to reproduce the issue:**

The code is below :- 

P.S. its in coffeescript ::

    1. incoming twilio video is the main div and I check if its empty. I f yes I attach a track here and for 
       rest of them I generate new Divs and attach
    2. nextIncomingTwilioVideo is the small div

Attaching videos normally:
```javascript
 @room.participants.forEach((participantNext) ->
          if @$('.cp_chat_incomingTwilioVideo video').length == 0
            participantNext.tracks.forEach((track) ->
              @$('.cp_loading, .js-call-status').hide()
              if track.kind == 'video'
                @$('.cp_chat_incomingTwilioVideo').append track.attach()
            )
          else
            nextIncomingDiv = $('<div class="nextIncomingTwilioVideo" id=""></div>')
            participantNext.tracks.forEach((track) ->
              nextIncomingDiv.append track.attach()
            )
            @$('.cp_chat_twilioMainWrapper').append nextIncomingDiv
        )
```

The function Code For Swapping 
```javascript
swapVideoCall: (e)->
      mainAud = $('.cp_chat_incomingTwilioVideo audio')[0]
      mainVid = $('.cp_chat_incomingTwilioVideo video')[0]

      $('.cp_chat_incomingTwilioVideo audio').remove()
      $('.cp_chat_incomingTwilioVideo video').remove()

      smallAud = $(e.currentTarget).children()[0]
      smallVid = $(e.currentTarget).children()[1]

      $(e.currentTarget).empty()

      $('.cp_chat_incomingTwilioVideo').append $(smallAud).attach()
      $('.cp_chat_incomingTwilioVideo').append $(smallVid).attach()

      $(e.currentTarget).append $(mainAud).attach()
      $(e.currentTarget).append $(mainVid).attach()

      console.log(e)
      debugger
```

Also, if there's any other approach please tell 🙂

**Comment by shikhar-scs** [comment]
@philnash @markandrus

**Comment by philnash** [comment]
Hey @shikhar-scs,

I think the issue here is that you're detaching the playing video and audio elements from the DOM and then reattaching them somewhere else.

Rather than doing that, I would use the methods available for [attaching and detaching tracks from the Video SDK](https://media.twiliocdn.com/sdk/js/video/releases/1.10.0/docs/AudioTrack.html#attach__anchor).

Then, to deal with this you'll want to keep a connection between the participant that is currently showing in the large video and the participants in the small videos. When you receive the click event on the small video, detach that participant's tracks with `track.detach(e.currentTarget)` and detach the main video tracks with `track.detach('.cp_chat_incomingTwilioVideo')`, then use the respective `track.attach` methods to reattach the tracks in their new containers.

I don't have an example of that to hand right now, but give it a go and let me know how you get on.

**Comment by shikhar-scs** [comment]
Thanks @philnash for the approach 😅 .

I, however, figured out a way to swap the tracks.

Whenever I attached tracks to a div, I stored the track.id in the `data-audioId` and `data-videoId`  attributes and then accessed the ids later. Once, I had the Ids, I polled through all the current tracks of all the current participants of the room and then attached the respective tracks. It did solve my purpose. 

However, you're approach looks better to me and I'll try that if I get time.

I have one doubt though. Will `track.detach(<a random div id OR css selector>)` give me back the track attached to a div ? Won't `track` be undefined here (given the way in which I have structured my swap function)

**Comment by philnash** [comment]
You would need to maintain a reference to the `track` somehow yourself. It depends on how you handle the `roomJoined` and `trackAdded` tracks within the rest of your application as to how you'd manage that.

Glad you found a way to achieve this though.

**Comment by shikhar-scs** [comment]
> You would need to maintain a reference to the track somehow yourself.

Yeah. The same reason why I defined the data attributes. Thanks for your help though! 

Issue solved, we can close this 👍
