### ISSUE TITLE
Official Content Security Policy whitelist

### ISSUE THREAD

**Issue by JensAxians** [twilio/twilio-video.js#344]
**Question:**
I wonder if it would be possible to provide a (official) list of resources that the Twilio Video JavaScript library requires, that should be white-listed in an app's content security policy.

This would be easier than using a trial and error method to find these domains.

Thank you.

For example:
```
default-src 'self';
script-src 'self' https://static.twilio.com https://media.twiliocdn.com;
connect-src 'self' wss://*.twilio.com https://eventgw.twilio.com https://media.twiliocdn.com;
media-src 'self' https://*.twilio.com https://media.twiliocdn.com;
object-src 'self' https://*.static.twilio.com;
```

**Comment by markandrus** [comment]
We've merged this, but please feel free to comment here or open a new issue if anything is lacking.

**Comment by chrisdostert** [comment]
@markandrus seems w/ latest v2 beta these instructions need updating; getting this CSP error after following current docs:
`Refused to connect to 'wss://global.vss.twilio.com/signaling' because it violates the following Content Security Policy directive:`

**Comment by manjeshbhargav** [comment]
Hi @chrisdostert ,

Thanks for reporting this. We are aware of it and will update the security policy in the next sprint. In the meantime, you can add `wss://global.vss.twilio.com` to your whitelist.

Thanks,

Manjesh Malavalli
JSDK Team
