### ISSUE TITLE
Export getStatistics 

### ISSUE THREAD

**Issue by ssskip** [twilio/twilio-video.js#35]
Add ability for people who want capture RTC statistics realtime.

**Comment by markandrus** [comment]
Hi @ssskip,

Thanks for writing in. This is actually a feature we are currently implementing. If all goes well, we'll have support in our next 1.0.0-beta3 release later next week. Likely this will look something like the following:

```js
/**
 * Get WebRTC statistics for the {@link Room}.
 * @returns {Promise<StatsReport>}
 */
Room.prototype.getStats = function getStats() { /* ... */ };
```

Best,
Mark

**Comment by manjeshbhargav** [comment]
Hi @ssskip ,

We have released `twilio-video.js#1.0.0-beta3`, which contains `Room#getStats()`, as @markandrus specified in the previous comment. Please feel free to play around with it.

Thanks,

Manjesh
