### ISSUE TITLE
TypeError: track must be a LocalAudioTrack, LocalVideoTrack, LocalDataTrack, or MediaStreamTrack

### ISSUE THREAD

**Issue by JunusErgin** [twilio/twilio-video.js#352]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**
Hello, 
i'm trying to get my local video with the following code:

```js
    private E_VIDEO_SETTINGS = {
        logLevel: 'debug',
        video: true,
        width: 1920,
        height: 1080
    };

    Twilio.Video
             .createLocalVideoTrack(this.E_VIDEO_SETTINGS)
             .then((localVideoTrack: any) => {
                 this._logger.debug('[VideoService] Created local video track', localVideoTrack);
              // ...
```

**Expected behavior:**

I should get a LocalVideoTrack.

**Actual behavior:**
I'm getting the following error:
```
TypeError: track must be a LocalAudioTrack, LocalVideoTrack, LocalDataTrack, or MediaStreamTrack
```

This error occurs **only in the Chrome browser** and only on **one of my computers** (Medion Akoya S3409, ~ 2 years old, Latest Windows 10 Home).
I debuged the twilio-video-min.js file (v1.11.1) in order to reproduce the error.
First, twilio tries to get the user media:
![image](https://user-images.githubusercontent.com/7281463/42692336-a4fa1c28-86ab-11e8-9331-ef72116720de.png)
This works successfully: 
![image](https://user-images.githubusercontent.com/7281463/42692374-cf93b7be-86ab-11e8-9805-00d87c251e9d.png)
In the next step, Twilio-video tries to convert the MediaStreamTrack into a local track with the function:
```return mediaStreamTracks.map(function (mediaStreamTrack) {
                        return asLocalTrack(mediaStreamTrack, Object.assign(localTrackNameOptions[mediaStreamTrack.kind], 
```

Twilios function `asLocalTrack(track, options) ` now throws my error that is mentioned above:
`TypeError: track must be a LocalAudioTrack, LocalVideoTrack, LocalDataTrack, or MediaStreamTrack`

i tried to debug the function as well:
![image](https://user-images.githubusercontent.com/7281463/42692598-7f39d90a-86ac-11e8-8f41-33ba95ea9646.png)
My console gave out:
![image](https://user-images.githubusercontent.com/7281463/42692615-8e7beda4-86ac-11e8-97ab-77eb8fc69064.png)

For some reason, your line `if (track instanceof options.MediaStreamTrack) {...` returns ´false´for some reason. Even if a `MediaStreamTrack` is provided in the first parameter it seems to differ from the one that is provided in the options.

Ad mentioned, my code works on all other computers. It also works on Opera, Vivaldi, Firefox and Edge on the current computer. 
**Software versions:**

 - [x] Browser(s): Chrome 67.0.3396.99 (Official Build) (64-Bit)
 - [x] Operating System: Windows 10 Home
 - [x] twilio-video.js: 1.11.1
 - [x] Third-party libraries (e.g., Angular, React, etc.): Angular 6.0.5

Thanks for your help in advance,
Junus

**Comment by manjeshbhargav** [comment]
Hi @JunusErgin ,

Thank you for your question. So, to sum up, are you saying that the code snippet you posted works on all other OSs except for Windows 10 Home? Please let me know if that is indeed the case.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by mertkokusen** [comment]
We are experiencing the same issue. @JunusErgin were you able to resolve this. The error occurs intermitantly. User can't connect to the room but after refreshing the page a couple of times, they can connect.

**Comment by koistya** [comment]
Same issue here — `track` is not an instance of `options.MediaStreamTrack`:

![image](https://user-images.githubusercontent.com/197134/135316944-669e90c5-3660-4e64-9c43-e32393a75c12.png)

**Comment by Artfloriani** [comment]
@mertkokusen @JunusErgin were you guys able to workaround this issue?
