### ISSUE TITLE
Test browser

### ISSUE THREAD

**Issue by VincentSim** [twilio/twilio-video.js#359]
Hi,

We use Twilio video for our business and I would like to know if there is a way to create (or embed) a test like this one : https://networktest.twilio.com with our own brand and design in our app.

Thanks in advance,

Vincent

**Comment by lifeofzero** [comment]
You could always take source from here - https://github.com/webrtc/testrtc which you can see at https://test.webrtc.org/

**Comment by jamesgraham** [comment]
Very useful- could we point this at Twilio servers to check for Firewall issues?
