### ISSUE TITLE
Edge compatibility

### ISSUE THREAD

**Issue by Mathew78540** [twilio/twilio-video.js#37]
Hi,

I would like to know if in the futur Twilio-Video will be compatible with Microsoft Edge ? 

Thx.

**Comment by philnash** [comment]
Hey, Edge compatibility is dependent on the implementation of WebRTC in Edge. It is currently under development and you can see the [progress here](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/webrtcwebrtcv10api/?filter=f3f0000bf&search=rtc&q=webrtc). You can also add your vote for support for the feature (which helps their team prioritise their work) on the [Edge Uservoice page](https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/6508336-webrtc-webrtc-v1-0-api).

**Comment by ZuSe** [comment]
Has someone tested running against Edge 15? You can enable WebRTC support by setting the related flag
