### ISSUE TITLE
playsinline no more in video tag, making streams no more working on iPhone 7, iOS 11.4.1

### ISSUE THREAD

**Issue by ZelStudio** [twilio/twilio-video.js#370]
Just find out than on iOS 11.4.1 with an iphone 7, i have a play button on the participant stream. I notice than the video / audio tag do not have the playsinline tag on it as required and added on https://github.com/twilio/twilio-video.js/pull/163/commits/f35be1c4d27c1ed869183108659dbc324ccbf65d

But ... on an iphone 8 plus + iOS 11.4.1, no issues even without playsinline !

 - [X] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [X] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [X] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [X] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

Just start the sample, start a room and browse to the HTML tags of the live stream

**Expected behavior:**

Must see < video autostart playsinline ></video>

Stream must start

**Actual behavior:**

Only see < video autostart ></video> on HTML tags

A play is button is over a black image

**Software versions:**

 - [X] Browser(s): Safari
 - [X] Operating System: Mac OS or iOS
 - [X] twilio-video.js: 1.12.0
 - [X] Third-party libraries (e.g., Angular, React, etc.): Angular

**Comment by markandrus** [comment]
Hi @ZelStudio,

This is very strange. Actually, I just tried out the [https://draw-with-twilio.appspot.com](https://draw-with-twilio.appspot.com) test app on my iPhone 6s, and I noticed the same thing! No video (actually, it didn't even prompt for microphone and webcam access) and then I saw the play button you described.

Here's what's weird, though: I looked in Settings → Safari → Camera & Microphone Access, and I saw that this setting was disabled; I also looked in Settings → Safari → Advanced → JavaScript and saw that this setting was disabled, too. I have no idea why. Maybe because I am in low power mode right now? Maybe a recent iOS update accidentally disabled this for my phone? But can you check the same settings?

Best,
Mark

**Comment by ZelStudio** [comment]
I also realized that Camera & Microphone Access was off and javascript too on my both device iPhone 7 & 8 Plus. I switch those on -> no changes same issues. What's strange is than the iPhone8 Javascript was at off, but Javascript definitely work as all my test use JS. So i put all on, and iphone 8 plus is working 100%, iphone 7 ... still have a play button.

For the iphone 6, i know than is not a camera/mic issues because i can see the red camera on the top when recording, but i only see an Play button

**Comment by markandrus** [comment]
> still have a play button.

In your app, can you please use the following code to log the &lt;audio&gt; and/or &lt;video&gt; element you attach to? I haven't tested this, I just typed it up.

```js
function logAudioOrVideoElementsSrcObject(audioOrVideoElement) {
  console.log(`autoplay=${audioOrVideoElement.autoplay}`);
  console.log(`playsInline=${audioOrVideoElement.playsInline}`);
  console.log(`muted=${audioOrVideoElement.muted}`);
  if (!audioOrVideoElement.srcObject) {
    console.error('No srcObject!');
    return;
  }
  const mediaStream = audioOrVideoElement.srcObject;
  if (!mediaStream.getTracks()) {
    console.error('No MediaStreamTracks!');
    return;
  }
  console.log(`${mediaStream.getAudioTracks().length} audio MediaStreamTrack(s)`);
  console.log(`${mediaStream.getVideoTracks().length} video MediaStreamTrack(s)`);
}
```

Can you also please set `{ logLevel: 'debug' }` in your calls to `connect`, `createLocalTracks`, `createLocalAudioTrack`, and/or `createLocalVideoTrack`? And can you share these logs in the ticket?

Thank you,
Mark

**Comment by ZelStudio** [comment]
You know what, my iPhone 7 was in battery saving mode and not my iPhone 8 ... may be you got the point! I will test it.

**Comment by ZelStudio** [comment]
Good new, so it's the Battery Saving Mode fault ! Without it i get : autoplay=true playsInline=true muted=false | 1 video MediaStreamTracks on my video tag

**Comment by markandrus** [comment]
Nice find, @ZelStudio 👍
