### ISSUE TITLE
invitation to the call

### ISSUE THREAD

**Issue by zhukovka** [twilio/twilio-video.js#38]
Hi, 
I'd like to know how can I get something like an invitation to the room before connecting to it.
From the [blog post](https://www.twilio.com/blog/2015/05/getting-started-with-twilio-video.html) I can see that earlier version used ```client.on('invite' ...``` handler.
What I'm trying to achieve is that I don't keep open connection to the room but I can get some message when someone has connected.

**Comment by manjeshbhargav** [comment]
Hi @zhukovka ,

We have moved away from the `invite` model to a `connect` model. You can build an invite mechanism in your application where you send the name of the room in the invite.

Let me know if that works for you.

Thanks,

Manjesh
