### ISSUE TITLE
Error while connecting to a Room: Error: Open failed

### ISSUE THREAD

**Issue by katranci** [twilio/twilio-video.js#381]
Hi,

Could you also look into a connection issue where the user failed to connect to Twilio several times and the API returned `Error: Open failed` eventually?

`2018-07-31 18:00:13.547Z` First attempt to connect
`2018-07-31 18:10:06.597Z` Second attempt to connect
`2018-07-31 18:14:06.813Z | INFO in [connect #1]: Error while connecting to a Room: Error: Open failed`

Thanks

**Comment by sandeepnandula** [comment]
It's happening for us also several times, we checked the Twilio error codes they are suggesting to change the region. We tried it but still its happening.

**Comment by kamesh-a** [comment]
+1

**Comment by jamesgraham** [comment]
We are seeing this occur for participants physically on the same network as others who successfully connect. What's going on?

**Comment by manjeshbhargav** [comment]
Hi @jamesgraham ,

Do you happen to have client-side debug logs for this behavior. It would help us greatly in debugging this issue.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by jamesgraham** [comment]
Hi @manjeshbhargav - we do - I am not sure how best to share them as they are not easy to export and hundreds of lines long. We are tracking this with a Zendesk ticket, shall I share the details there?

**Comment by manjeshbhargav** [comment]
@jamesgraham ,

Sure. That would work.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by jamesgraham** [comment]
Hey @manjeshbhargav - just checking you got the note attached to the ticket? How can we mitigate this issue today?

**Comment by manjeshbhargav** [comment]
Hi @jamesgraham ,

I did get the PNG that shows your logs. Thank you for sending the logs. I will take a look at them today and get back to you.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by katranci** [comment]
@manjeshbhargav I've managed to reproduce getting _Open failed_ error from Twilio. If network is down when `connect` is called and it stays down then it eventually (~47 seconds later) rejects the promise with that error. However, the reconnect mechanism doesn't kick in (should it?) and therefore we don't have a way of informing the user.

**Comment by manjeshbhargav** [comment]
@katranci ,

Our experiments reveal the same thing. Unfortunately we don't have the ability to re-connect to the back-end using our existing SIP-based signaling Transport (We can re-establish media connections). However, we are working on moving towards a pure JSON-over-WebSocket Transport, where we have control over re-connection. We will reach out to you once we have something working.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by jamesgraham** [comment]
Hi @manjeshbhargav, do you have a rough estimate of when that might land?

**Comment by mozimos** [comment]
+1

**Comment by jamesgraham** [comment]
Hi @manjeshbhargav is this now rolled into v2?

**Comment by manjeshbhargav** [comment]
Hi @jamesgraham ,

We still have a few outstanding issues we are addressing. Our tentative plan is to release this formally in a minor version upgrade after we make version 2.0 generally available.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by Ffoisal** [comment]
"Could not connect to Twilio: Could not start video source" this message show when i want to connect twilio video system in my app

**Comment by ajru** [comment]
Error while connecting to a Room: Error: Open failed
