### ISSUE TITLE
dominantSpeaker feature availability

### ISSUE THREAD

**Issue by tinque** [twilio/twilio-video.js#389]
Hi,

In the changelog, I found this

```
Room now includes a dominantSpeaker property that represents the RemoteParticipant publishing the loudest RemoteAudioTrack your LocalParticipant is subscribed to, if any. Whenever the Dominant Speaker changes, Room emits the "dominantSpeakerChanged" event. This feature depends on server-side support, which we are rolling out gradually. As such, expect this value to always be null for the time being. We will make an announcement once the feature is enabled. This feature is currently unsupported in Peer-to-Peer (P2P) Rooms.
```
Do you have an ETA for this feature's availability ?

Thanks

**Comment by ktoraskartwilio** [comment]
Thanks for your interest in the Dominant Speaker detection API. As you noticed, we've shipped support for this feature as an early release. I'd be happy to provide access to early adopters. Please send me an email directly with your Account SID at ktoraskar@twilio.com. We will open access to this feature to everyone in a couple of weeks.

**Comment by tinque** [comment]
Thanks a lot ! I've sent you an email :)

**Comment by manjeshbhargav** [comment]
@tinque ,

I will close this issue. Feel free to open another issue if you experience any problems with the `dominantSpeaker` feature.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by markandrus** [comment]
Hey @tinque (and anyone else with preview access),

I wanted to give you a heads up: before this feature is released more widely, we're adding a `dominantSpeaker` flag to ConnectOptions so that customers opt-in to this feature, rather than get it by default. This change is coming in 1.14.0, which I plan on releasing today. Please set the following when you call `connect`:

```js
connect(token, {
  dominantSpeaker: true
});
```

See [here](https://github.com/twilio/twilio-video.js/blob/1.14.0-rc2/CHANGELOG.md#new-features) for more information.

**Comment by tinque** [comment]
Thanks a lot for the notification ! Awesome !

**Comment by chamoda** [comment]
@ktoraskartwilio Is this now available in the library. Which version?

**Comment by manjeshbhargav** [comment]
Hi @chamoda ,

The Dominant Speaker Detection feature is available starting from 1.14.0 (for Group Rooms only).

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by himanpan** [comment]
Is there any plan to make this feature available for peer to peer rooms?

**Comment by manjeshbhargav** [comment]
@himanpan ,

As of now, we do not have any plans to implement this for Peer-to-Peer Rooms. Have you considered using our Small Group Rooms (max 4 Participants) for your use case? You can have access to the Dominant Speaker API with this Room type, and it costs a lot less than Group Rooms (max 50 Participants). Please refer to the "Group Rooms Billing" section of the [Pricing Estimates for Twilio Programmable Video](https://support.twilio.com/hc/en-us/articles/115004710208-Estimating-pricing-for-Twilio-Programmable-Video) to see if Small Group Rooms is a viable option for you.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by himanpan** [comment]
Thanks. But, the purpose of using Peer-to-Peer rooms is encrypted streaming. So, using Small/Group Rooms doesn't solve the purpose.
In the absence of dominant speaker functionality, how do people identify who is speaking in Peer-to-Peer conference?
