### ISSUE TITLE
Access to data channel 

### ISSUE THREAD

**Issue by rlancer** [twilio/twilio-video.js#39]
Is this planned or possible using this library? 

Also if anyone wants to play around with the app I'm building with this https://bernie.chat ... 

Code on GitHub https://github.com/rlancer/berniechat

**Comment by rfbrazier** [comment]
Hey @rlancer, we don't support DataChannel in this SDK today, but plan to do so in the near future. Thanks for asking, and let us know if there's anything else we can do.

**Comment by Prendo93** [comment]
+1

**Comment by arturitu** [comment]
+1

**Comment by markandrus** [comment]
Hey y'all,

We added P2P DataTrack support in 1.4.0 (released October 2nd). You can read up on it here: https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md#datatrack

We should have Group Room DataTrack support in 1.6.0 (hopefully out by next week).

Thanks,
Mark
