### ISSUE TITLE
bower install --save twilio-video resolves  to twilio-conversations

### ISSUE THREAD

**Issue by sfakir** [twilio/twilio-video.js#40]
actually your versioning is quite confusing.

```bower install --save twilio-video
bower twilio-video#*        not-cached https://github.com/twilio/twilio-video.js.git#*
bower twilio-video#*           resolve https://github.com/twilio/twilio-video.js.git#*
bower twilio-video#*          download https://github.com/twilio/twilio-video.js/archive/0.13.10.tar.gz
bower twilio-video#*           extract archive.tar.gz
bower twilio-video#*      invalid-meta for:/var/folders/cx/9900fxfj7zx_nqwz4d861n5m0000gn/T/simonfakir/bower/fa46d7c94a7d9aaaff8ed773fe391d04-10105-DOe6jp/bower.json
bower twilio-video#*      invalid-meta The "main" field cannot contain minified files
bower twilio-video#*          resolved https://github.com/twilio/twilio-video.js.git#0.13.10
bower twilio-conversations#^0.13.10          install twilio-conversations#0.13.10

twilio-conversations#0.13.10 client/bower_components/twilio-conversations
````

So in the end I got a **twilio-conversations.js 0.13.10** from bower, which seems to be wrong.
On your CDN i found **twilio-video.js 1.0.0-beta3** (copyright 2015?) this should be the latest version right? 

**Update:** looks like npm instsall works fine and you just need to fix your bower repo.

thank you.

**Comment by girtis** [comment]
Hi, @sfakir - `twilio-video.js 1.0.0-beta3` is indeed the latest version. Thanks for pointing this out, we're checking in on the bower repo.

**Comment by markandrus** [comment]
Hi @sfakir,

Unfortunately, bower will act this way until we push a proper 1.0.0 release (1.0.0-beta3 is technically a pre-release and bower will not install it by default). Here's how you can get a hold of 1.0.0-beta3 with bower today:

```
bower install 1.0.0-beta3
```

We'll update the `README.md` to clarify.

Thanks,
Mark

**Comment by ZuSe** [comment]
I would recommend to go for npm if you can.
Bower does stuff like this a lot.

**Comment by markandrus** [comment]
Clarified in 3403337aab51ddc5f00a05a6a0f4247473f49873
