### ISSUE TITLE
Firefox: Client is unable to create or apply a local media description

### ISSUE THREAD

**Issue by alestab** [twilio/twilio-video.js#402]
Hi, 
since 8/15 we get errors and warnings using the twilio-video.js sdk on Firefox after trying to publish a local track.

WARN in [object Object]: Calling setLocalDescription with an RTCSessionDescription of type "offer" failed with the error "Failed to parse SDP: SDP Parse Error on line 71:  No webrtc-datachannel token in m= media line, parse failed.

and 

Error: Client is unable to create or apply a local media description

The result is that tracks are not published to the room.

 On Chrome all is working well as expected.

At first we were using version 1.12.0 but this occurs also after updating to version 1.13.1 or 2.0.0-beta1.

Are we missing something related to the fix released with sdk version 1.13.1 ?

thanks

**Comment by markandrus** [comment]
Hi @alestab,

Sorry you're hitting this. Can you please share some Room SIDs? This will allow us to see the exact SDK versions, Firefox versions, and SDPs that are causing this issue.

Mark

**Comment by alestab** [comment]
Hi @markandrus ,

here some room SIDS:

RMa1ca7846d432058cbc6182dc0d8bfd98

RMce4de3dedeb02db8f08a982606099adb

RM7a094704b2afd08eae3772f86a1e01c1

thank you

**Comment by markandrus** [comment]
Thanks for the Room SIDs, @alestab. These allowed me to isolate the issue. A server-side change caused this issue which we are now rolling back.

**Comment by markandrus** [comment]
The underlying issue is the one described here: https://bugs.chromium.org/p/webrtc/issues/detail?id=7706

**Comment by markandrus** [comment]
@alestab the rollback is complete and this issue should be fixed for the time being. We attempted to upgrade all our traffic to the new SDP format described [here](https://blog.mozilla.org/webrtc/how-to-avoid-data-channel-breaking/) in advance of Firefox 63 hitting stable; however, this impacted the Twilio Video Android SDK version you are using, 2.1.1, and any older mobile SDKs where DataTracks are used. We'll consider other options for managing the upcoming Firefox 63 release, but we recommend you upgrade your Twilio Video Android SDK version, if possible, in the meantime.
