### ISSUE TITLE
Trigger Event on Participant's Microphone Sound Input

### ISSUE THREAD

**Issue by mawrierajat** [twilio/twilio-video.js#409]
Is there any existing event to know that the participant is speaking to their microphone?

**Comment by manjeshbhargav** [comment]
@mawrierajat ,

Thank you for your question. Do you mean whether there exists an event to find out which Participant is currently talking in the Room? If so, __for group Rooms only__ , we have the "dominantSpeakerChanged" event on the Room (https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md#1140-august-28-2018).

```js
room.on('dominantSpeakerChanged', participant => {
  console.log(`New dominant speaker: ${participant.identity}`);
});
```

Please let me know if this is what you are looking for.

Thanks,

Manjesh Malavalli
JSDK Team
