### ISSUE TITLE
Accessing Raw Pixel Data

### ISSUE THREAD

**Issue by seanadkinson** [twilio/twilio-video.js#413]
Hello there,

Does the javascript client have the ability to access the raw pixel data from the frames coming into the browser?

Thanks

**Comment by manjeshbhargav** [comment]
Hi @seanadkinson ,

Thanks for writing in with your question. You can use the `<canvas>` element to grab a frame from a `<video>` element like this:
```js
/**
 * Take snapshot of the video from the HTMLVideoElement and render it
 * in the HTMLCanvasElement.
 * @param {HTMLVideoElement} video
 * @param {HTMLCanvasElement} canvas
 */
function takeLocalVideoSnapshot(video, canvas) {
  var context = canvas.getContext('2d');
  context.clearRect(0, 0, canvas.width, canvas.height);
  context.drawImage(video, 0, 0, canvas.width, canvas.height);
}
```
If you want to continuously grab frames, you can use this function within [requestAnimationFrame](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame).

Please let me know if this works for you.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by seanadkinson** [comment]
Thanks @manjeshbhargav.  We'll be plugging this in soon and let you know if we have any issues.
