### ISSUE TITLE
WARN RemoteMediaTrack#id has been deprecated

### ISSUE THREAD

**Issue by katranci** [twilio/twilio-video.js#414]
Another usage of deprecated api internally.
twilio-video.js version: 1.14.0

> 2018-09-04 13:03:37.580Z | WARN in [RemoteVideoTrack #1: MTc6bf65fb1b5dbafdede41403fd63503f]: RemoteMediaTrack#id has been deprecated and is scheduled for removal in twilio-video.js@2.0.0. Use the parent RemoteTrackPublication's .trackName or .trackSid instead.

**Comment by coding365days** [comment]
Even i've seen this. what does it mean ? I am trying to build angular 6 app for twilio-video, where i am trying to get the remote video and audio tracks to pass to a component. I am unable to get that.

**Comment by markandrus** [comment]
Thanks for the report—we will fix this in 1.14.1.

**Comment by manjeshbhargav** [comment]
@katranci , @coding365days ,

`twilio-video.js@1.14.1` has been released. Please let me know if the deprecation warnings have stopped appearing in your logs. I will close the issue for now, and feel free to reopen if necessary.

Thanks,

Manjesh Malavalli
JSDK Team
