### ISSUE TITLE
When the without TURN test fails should we force TURN? If so how?

### ISSUE THREAD

**Issue by stueynet** [twilio/twilio-video.js#417]
We are finding that certain clients report that the test at https://networktest.twilio.com/ fails for `Video: Test Group Room without TURN`. This is a result of their networking configuration and makes sense as it sometimes works fine. I assume the solution here is to force the client to always use TURN? If so do we simply specify a single region when we initialize the client? Its not 100% clear the best resolution for this. 

If I were to do it this way would this be the correct code:

```
 const room = await connect(roomInfo.token, {
                name: roomInfo.name,
                tracks: localTracks,
                region: 'us1' // adding this in
            });
```
If not is there another solution to this issue where one client does not do well without TURN?

**Comment by manjeshbhargav** [comment]
Hi @stueynet ,

Thanks for writing in. Most probably the clients for whom the "Video: Test Group Room without TURN" test is failing are behind a symmetric NAT. The Twilio Video SDK by default uses TURN as one of the ways to establish media connections. So your client should be able to connect to a Room.

If you want to override the default TURN behavior and provide your own ICE servers, you can do so by specifying an `iceServers` property in ConnectOptions like so:

```js
const room = await connect(token, {
  name,
  tracks,
  iceServers: [...]
});
```

Here is the [ConnectOptions documentation](https://media.twiliocdn.com/sdk/js/video/releases/1.14.0/docs/global.html#ConnectOptions).

Please let me know if this answers your question.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by manjeshbhargav** [comment]
Hi @stueynet ,

You can also enforce usage of TURN by setting `iceTransportPolicy` to `'relay'` in ConnectOptions.
Let me know if this solution is workable for you.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by stueynet** [comment]
@manjeshbhargav changing iceTransportPolicy to 'relay' seems to now show this error:

![error](https://user-images.githubusercontent.com/1100677/45819577-abf59880-bcb2-11e8-820e-2e2699986596.png)

**Comment by manjeshbhargav** [comment]
Hi @stueynet ,

Can you send me the full client logs and the Room SID?

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by stueynet** [comment]
I can provider a bit more detail. In terms of logs where did you want me to send those?

So 2 things at play here. 

Client1, Client2

1. When `Client1` is moving around and potentially switching between Wifi access points, the audio drops out. So they can hear and see `Client2` but `Client2` can only see `Client1`. `Client2` cannot hear `Client1`. Disconnecting and re-connecting fix the issue.

2. When the connection begins to deteriorate, occasionally it freezes completely. After 10 seconds it rights itself and the above warning shows in the console Regarding `ICE failed`.  

Number 2 occurred much more frequently when I set `iceTransportPolicy`: `relay`.  When removed, it would still happen when there was network congestion, but way less often. Very rarely in fact.

A room SID where this happened a lot was `RM880fa569734652a55ced4046a34aae28`

**Comment by manjeshbhargav** [comment]
Hi @stueynet ,

The ICE-failed warning is expected on weak network conditions, especially with `iceTransportPolicy: "relay"`, because whenever there is a problem with media connectivity, we restart the process of establishing it. Also, TURN adds some delay to media streaming as all media flows through the TURN server to the remote peers. Therefore, enforcing TURN is usually recommended only for peers behind strict firewall rules.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by brianburt** [comment]
We are a new Twilio Prog Video customer and getting this Fail result somewhat predictably (most of the time from some Australian IPs).   We are not trying to do any peer-to-peer connections, only server-based connections, all with the JS SDK.  On networktest, both "with TURN" and "without TURN" are red from those IPs.  

Is there anything our system engineers can to get more details on what's failing?  (debug steps within whatever javascript is behind networktest, or port or traceroute tests, wireshark etc?)

This is very high priority for us with a very major stakeholder totally blocked, so I very much appreciate any guidance.
