### ISSUE TITLE
Loop: WebSocket disconnected (code: 1006)

### ISSUE THREAD

**Issue by katranci** [twilio/twilio-video.js#421]
We've detected that the sequence of events in the screenshot below kept repeating in a loop for one of our users. The strange thing is the we haven't received any Twilio error throughout. Shouldn't connect api fail with a rejected promise? Also, could you please guide us on how to reproduce this behaviour? Thanks

![image](https://user-images.githubusercontent.com/61077/45682356-fb638980-bb37-11e8-998f-712a39fdabdd.png)

**Comment by katranci** [comment]
@manjeshbhargav We are seeing more of this issue. When a web socket connection fails then twilio-video enters in a retry attempt that goes forever and doesn't reject the _connect_ promise. Is this going to be resolved in v2?

**Comment by spalmertwilio** [comment]
Reference only: Support Request #1536980.

**Comment by divyamrastogi** [comment]
@manjeshbhargav : We faced this issue as well, right around the same time on 26th September. Is this fixed?

**Comment by manjeshbhargav** [comment]
@divyamrastogi ,

We are working on moving away from our existing SIP-based signaling stack. We have tentatively  scheduled rollout of the new signaling stack for the early part of Q1, 2019. Please watch this space for updates.

Thanks,

Manjesh Malavalli
JSDK Team
