### ISSUE TITLE
Is there a way to flip (mirror) a local video track horizontally?

### ISSUE THREAD

**Issue by vincentwoo** [twilio/twilio-video.js#425]
It's often useful to flip the local user's view of themselves to get rid of the uncanny "my hand moves left when I move it right" thing. Is this something that this library supports? I couldn't find any mention of it in the docs.

**Comment by markandrus** [comment]
We do not have an API for this; however, you can do this with CSS. It would be useful to call this out somewhere.

```js
const video = localVideo.attach();
video.style.transform = 'scale(-1, 1)';
```

**Comment by gjdownes** [comment]
This solution also worked for me; keep in mind you need to switch it back if doing screen share. 
Naming the video tracks (e..g webcam vs screenshare)

**Comment by Asadbaig11** [comment]
can we flip or add mirror function in node js if yes than how?

**Comment by IamSanjayGupta** [comment]
is there any way to flip the localvideo and then publish it
