### ISSUE TITLE
'trackPublicationFailed' or 'trackSubscriptionFailed' events not fired

### ISSUE THREAD

**Issue by kinjalhinguss** [twilio/twilio-video.js#428]
Hello, 
I am trying to join a video call from chrome to android devide with same web page. when i am publishing video track from chrome my android device is not getting  'trackAdded' event fired. so i am not able to view chrome's video on android device. I have also added 'trackPublicationFailed' and 'trackSubscriptionFailed' events in my 'participantConnected' event listener. But it never gets fired. Please guide me on this.

This is my code:  

   room.on('participantConnected', function (participant) {
                alert('participant connected');
            
                participant.on('trackPublicationFailed',function(error,track){
                    _this.trackPublishFailed();
                });
                participant.on('trackSubscriptionFailed',function(error,track){
                    _this.trackSubscriptionFailed();
                });
  });

My requirement is 'trackAdded' should be called for remote participant or if track is not added dispaly some error message when 'trackPublicationFailed' or 'trackSubscription' fired.

I am using twilio-video.js 1.14.0

**Comment by manjeshbhargav** [comment]
Hi @kinjalhinguss ,

Thanks for writing in with your question. Can you provide a Room SID (present in .sid property of the Room object) where you are observing this behavior? Also, can you show me the code snippet where you are listening to the "trackAdded" event?

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by kinjalhinguss** [comment]
Hello,
Thanks for reply. Problem was from my side. It has been solved now.
