### ISSUE TITLE
Add / Update stream during call

### ISSUE THREAD

**Issue by kmahlqvist** [twilio/twilio-video.js#43]
Hi,

I'd like to add a separate or change the current video stream/track during a call. Is this or will this be possible? I guess there would need to be some renegotiation.

End goal being screen sharing.

**Comment by markandrus** [comment]
Hi @kmahlqvist,

Yes, this is possible. For example, you may construct a LocalMedia object as follows,

```js
const localMedia = new Twilio.Video.LocalMedia();
// Possibly adding LocalVideoTracks to it...
```

or perhaps access your LocalMedia from an active Room, e.g.

```js
const localMedia = room.localParticipant.media;
```

Either way, once you have a reference to your LocalMedia, you can call [`LocalMedia#addCamera`](http://media.twiliocdn.com/sdk/js/video/releases/1.0.0-beta3/docs/LocalMedia.html#addCamera__anchor), [`LocalMedia#removeCamera`](http://media.twiliocdn.com/sdk/js/video/releases/1.0.0-beta3/docs/LocalMedia.html#removeCamera__anchor), [`LocalMedia#addMicrophone`](http://media.twiliocdn.com/sdk/js/video/releases/1.0.0-beta3/docs/LocalMedia.html#addMicrophone__anchor), [`LocalMedia#removeMicrophone`](http://media.twiliocdn.com/sdk/js/video/releases/1.0.0-beta3/docs/LocalMedia.html#removeMicrophone__anchor), etc.

For example, to replace the current video that is being shared, you could do the following:

```js
// First, remove the current video.
localMedia.removeCamera();

// Then add a new video, effectively replacing the first.
// You could provide constraints if you wish, for example to select
// screen share on platforms that support it.
const constraints = {};
localMedia.addCamera(constraints).then(() => {
  console.log('Successfully added new LocalVideoTrack');
}, error => {
  console.error('Failed to add new LocalVideoTrack', error);
});
```

Renegotiation will be handled automatically within an Rooms that you are sharing this LocalMedia instance. There's one caveat to the code sample I shared above, though. Currently `addCamera` (and `addMicrophone`) will only add up to one LocalVideoTrack (or LocalAudioTrack). We may change this APIs in the future, but, until then, if you wanted to share two LocalVideoTracks (where one is your camera and the other is screen share) then you'd need to add the screen share via [`LocalMedia#addStream`](http://media.twiliocdn.com/sdk/js/video/releases/1.0.0-beta3/docs/LocalMedia.html#addStream__anchor). For example,

```js
// Call getUserMedia with screen share constraints.
const constraints = {};
navigator.getUserMedia(constraints).then(stream => {
  // Then add the MediaStream to LocalMedia.
  localMedia.addStream(stream);
}, error => {
  console.error(error);
});
```

Does this help? Is there any way we could make this flow better for you?

Thanks,
Mark

**Comment by kmahlqvist** [comment]
It worked great with both solutions, thank you!

Only thing I noticed is that it doesn't seem to listen to the end event of screen share when using the "Stop sharing" button that chrome shows.

**Comment by markandrus** [comment]
Glad to hear it, and you're welcome :-)

> I'll just listen for the onended of the videotrack on the client and end it manually when needed.

Ah, interesting--so you do use this event. We may need to think about whether to raise this on our Track classes...

**Comment by Viokeoke** [comment]
Hi, how can i change between cameras without create new video recording on server? when i go to download the videos that i recorded i got two, but i only want one video with the two streams.

Regards
