### ISSUE TITLE
ICE failure doesn't trigger Room#reconnecting event

### ISSUE THREAD

**Issue by katranci** [twilio/twilio-video.js#431]
In room RM10da21d3609dc8091d12a0c57693f96a, the screenshare subscriber experienced an ICE failure (Sep 26, 2018 2:20:08 PM UTC) and his video froze due to that. The publisher restarted his screenshare (Sep 26, 2018 2:24:46 PM UTC) in a hope to resolve the problem, and that triggered a _connect_ on the other side, which revealed that his room was in "reconnecting" state. Later on, the subscriber had to refresh his the page to fix the issue. We log all Room#reconnecting events on Sentry yet I cannot see one for this session. What is the guideline for detecting and handling these type of interruptions?

**Comment by manjeshbhargav** [comment]
Hi @katranci ,

I took a look at our back-end logs for the Room, and I did see a couple of ICE failed events. It's weird that `Room#reconnecting` was not fired. Can you send me the sentry logs and the code snippet where you log reconnects?

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by katranci** [comment]
Hi @manjeshbhargav,

Sorry for the delayed response. I'm thinking this might be a false alarm. There is a chance that the event got fired but wasn't logged on Sentry because user might have hit the reload button around that time.
