### ISSUE TITLE
How to make a Receive Only Peer

### ISSUE THREAD

**Issue by cameronrll** [twilio/twilio-video.js#435]
Hi there,

Wondering if anybody has had any success in building a receive only peer?

For example participant A and B would be in a call (using the peer-to-peer rooms) and participant C could monitor this call (receive video and audio from participant A and B) without sending any video or audio themselves.

I've seen this in the documentation:

https://www.twilio.com/docs/video/api/publishedtrack?code-sample=code-retrieve-track-published-by-a-participant&code-language=Node.js&code-sdk-version=default

This published track has a URL, would I be able to use something like this to accomplish a receive only peer?

If anyone has any advice on how to go about this, that would be great!

Thanks.

**Comment by manjeshbhargav** [comment]
Hi @cameronrll ,

Thanks for writing in with your question. You can join a Room without any media like so:
```js
const { connect } = require('twilio-video');
const room = await connect(token, { name: 'my-room', tracks: [] });
```
This way, you will only receive any media published by other RemoteParticipants. Please let me know if this works for you.

Thanks,

Manjesh Malavalli
JSDK Team
