### ISSUE TITLE
Reconnect when Room#disconnected event is emitted

### ISSUE THREAD

**Issue by katranci** [twilio/twilio-video.js#438]
May I ask your thoughts on the crude model of the reconnect mechanism below? Our aim is to force a connection all the time and recover from any signalling disconnects that are caused by intermittent network failures. It seems like the logger utility inside twilio-video and possibly some other processes are registered everytime _connect_ is called. Therefore, when I let the code below run for a while when network is down then I start getting duplicates of same messages. Similarly, I see duplicates of same messages when network is back.

![image](https://user-images.githubusercontent.com/61077/46422588-61a5fa00-c73d-11e8-84e0-faf08b4d8b07.png)

![image](https://user-images.githubusercontent.com/61077/46422671-8601d680-c73d-11e8-8e11-b7b224dc954f.png)

```javascript
const { connect } = require('twilio-video')

async function connectToTwilio() {
  const room = await connect(token, { name: 'my-room', tracks: [] })
  room.on('disconnected', reconnect)
}

async function reconnect() {
  try {
    await connectToTwilio()
  } catch (e) {
    reconnect()
  }
})

reconnect()
```

**Comment by manjeshbhargav** [comment]
Hi @katranci ,

I would recommend that you use some kind of exponential backoff delay while reconnecting. Also, you can differentiate between legitimate disconnects and inadvertent ones by accessing the extra `error` argument in the [Room's "disconnected" listener](https://media.twiliocdn.com/sdk/js/video/releases/2.0.0-beta2/docs/Room.html#event:disconnected).

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by katranci** [comment]
Thanks for the reply @manjeshbhargav. They are already in place in the real code, just kept them out for clarity. What do you think about the duplicate messages? Would it be a symptom of a bug/problem? Is it safe to call _connect_ repeatedly while the network stays down?

**Comment by manjeshbhargav** [comment]
@katranci 

Does the number of duplicate messages correspond to the number of "connect" attempts?

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by katranci** [comment]
Not sure if there is a one-to-one mapping but there is definitely a causation there.

**Comment by manjeshbhargav** [comment]
@katranci ,

After some digging, I think what you're seeing is our underlying SIP transport's attempts to re-connect.
Due to a limitation in our existing infrastructure, web-based SIP clients are not able to re-establish a connection. It is expected behavior. So you can go ahead with your own re-connect logic.

We are working on replacing our SIP stack with our own transport. Please watch this space for
updates on that front.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by katranci** [comment]
Thanks @manjeshbhargav 👍
