### ISSUE TITLE
Is there any way to join into room without subscribing to the remote tracks by default ?

### ISSUE THREAD

**Issue by sandeepnandula** [twilio/twilio-video.js#448]
**Actual behavior:**
If the room size is more than 10 while joining into video call room it's taking high usage of user CPU, GPU (Updating the DOM, all the video encodings will start at a time of 10milliseconds gap cause heavy bitrate load occurs for a second)and bandwidth at a time. We saw few users couldn't able to join into the call having 20+ participants because of low configuration Machines.

**Experiment & Results**
We tried unsubscribing the tracks to the user on server level when we get the participant connected webhook event for him. But sometimes remote trackSubscibed event on the client side is triggering before the unsubscription server response. It's leading for a small glitch on videos.

**Expected behavior:**
It would be very helpful for us if we have an option by default unsubscribing the remote tracks while connecting to the room with a parameter. We feel it will reduce the initial heavy usage impact on the user's machine while entering into the room which leads the user to connect faster into the call.

**Comment by manjeshbhargav** [comment]
@sandeepnandula , @katranci ,

Thanks for writing in with your question. I will let our PM @ktoraskartwilio address any questions you may have about our roadmap and priorities.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by sandeepnandula** [comment]
Hi, @manjeshbhargav. any new updates on this enhancement?
