### ISSUE TITLE
Help with Programmable Video

### ISSUE THREAD

**Issue by victorpintot8** [twilio/twilio-video.js#45]
Hi, greetings from Ecuador. My team and I have a few questions about using Programmable Video SDK (PHP + Javascript).

1) Recording a video call, is it possible to end up with a video file with the audio (voices) separated in individual channels?. One for the voice of the user A and the other for the user B so that we can discard the voice channel of user B and only keep the voice of the user A. We wish to perform some sort of voice analysis but just for one user of the video call.

2) In our application, we first set up an appointment and later we do the call. Is it possible to generate the room in server side, store its name and then let the users connect to it ?

3) How can we use Programmable Video and Programmable chat in the same window?

Thank you for your help.

**Comment by markandrus** [comment]
Hi @victorpintot8, thanks for writing in.

1. Recording will be available as a developer preview shortly. AudioTracks, e.g. User A's voice versus User B's voice, will in fact be represented as separate Recordings. So you will be able to perform analysis for just one User the way you describe.
2. Pre-creating Rooms in the way you mentioned is also on the roadmap.
3. You can use twilio-video.js and twilio-chat.js in the same application. So for example, you may wish to share a `name` between your twilio-video.js Room and your twilio-chat.js Channel. Your application would ensure the Clients are connecting to resources with the same name. When Feature 2 above lands, we may also allow you to pin down the particular Room a Client can connect to, making this use case a little easier.

Does that answer your questions?

Thanks!
Mark

**Comment by victorpintot8** [comment]
Great!. Don't want to put pressure on you guys, but when do you think recording will be available ?. I'm currently developing an application whose launch date is late March.

**Comment by markandrus** [comment]
We cannot make any commitments on when the remaining Server-side work will complete; however, we have already landed Client-side APIs, such as `Room#isRecording` and the "recordingStarted" and "recordingStopped" events, for querying the recording state. We will post back here when recording is available. Leaving this ticket open until then.

**Comment by sedenardi** [comment]
@markandrus For issue #2, could this be accomplished in the meantime by generating a GUID some some similarly unique string on the server, and then sending that to the clients as the room name?

**Comment by jamesgraham** [comment]
@markandrus any update on the recording situation?

**Comment by markandrus** [comment]
Hi @jamesgraham and @sedenardi,

A Rooms REST API (which allows you to pre-create Rooms) and the recording functionality are available today in Developer Preview. Please reach out to me (mroberts@twilio.com) or rbrazier@twilio.com for early access. We are actively working on getting customer feedback during this period, after which the features will move to Beta (and anyone ought to be able to try them out).

In the meantime, @sedenardi, yes I think a GUID like that could work.

Best,
Mark

**Comment by jamesgraham** [comment]
Thanks @markandrus have dropped you an email 👍

**Comment by contactpkb** [comment]
@markandrus any update on the recording preview in dashboard? Please let me know where  I cant see recordings. I tried here : https://www.twilio.com/console/video/logs/conversations
But this page is not working and show permission required something....

**Comment by markandrus** [comment]
@contactpkb Group Rooms and Recordings are now in Public Beta as of May 18. That URL you shared appears to be for the now deprecated "Conversations" product.

Please see the blog post [Announcing Programmable Video Group Rooms: More Participants, Video Recording, and Pricing for Scale](https://www.twilio.com/blog/2017/05/announcing-programmable-video-group-rooms.html) for more information. It should include everything necessary to get started.

**Comment by saibaggins** [comment]
@markandrus Is there any way to get the audio recording for the meeting in a single mixed format instead of separate tracks? What is the motivation for providing the recording as separate tracks instead of a single mixed file?

**Comment by hverma** [comment]
@markandrus Is there a way to get a single mixed recorded file for the group room? I need to give access to the recordings of the group chat room to my clients right after the session is completed.
