### ISSUE TITLE
Modify remote streams on server

### ISSUE THREAD

**Issue by parv16** [twilio/twilio-video.js#452]
- [ ] I need the custom implementation of twilio programmable video such that I need to modify remote streams on server before showing it to peer joined in twilio programmable video room. Is there any way of doing so using twilio programmable video. 
**P.S.** The remote stream modification needs to be done at server as it requires some processing that cannot be done at client side.

**Comment by parv16** [comment]
Any update on this?

**Comment by manjeshbhargav** [comment]
@parv16 ,

Unfortunately, as I mentioned before, we do not support stream forwarding at this moment, and it is not on our roadmap for the near future. I'm going to close this issue. Please feel free to open a new one if you have any other questions/concerns regarding `twilio-video.js`.

Thanks,

Manjesh Malavalli
JSDK Team
