### ISSUE TITLE
SIP/2.0 500 Server Internal Error

### ISSUE THREAD

**Issue by katranci** [twilio/twilio-video.js#456]
I have just bumped into `SIP/2.0 500 Server Internal Error` messages when looking into traffic in the websocket connection. The socket closes eventually at 2018-10-31T20:15:28.476Z and that is followed by `Signaling connection timed out` error in DevTools console at 2018-10-31T20:15:28.508Z. Room id is `RMd6871644ae58ab363bf103049990b4c7`. What is causing 500 status? How can we fix it?

![image](https://user-images.githubusercontent.com/61077/47816654-a11b3280-dd4b-11e8-9923-4fcd8a6f2aad.png)

**Comment by manjeshbhargav** [comment]
@katranci ,

Thanks for writing in with your issue. I will have someone from our back-end team take a look and get back to you.

Thanks,

Manjesh Malavalli,
JSDK Team

**Comment by katranci** [comment]
Thanks @manjeshbhargav. Looking forward to your reply.

**Comment by manjeshbhargav** [comment]
Hi @katranci ,

Can you send us the UPDATE message payload for which you are getting a 500 response? And also if you can send us the Participant SID which is experiencing this, it would help us focus our attention.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by katranci** [comment]
Participant SID should be `PA4fa8500f609801874261ea5cfc5566fb` and the last UPDATE message payload is:
```
UPDATE sip:172.18.53.75:443;transport=wss SIP/2.0
Via: SIP/2.0/WSS j0ah020286o1.invalid;branch=z9hG4bK662035
Max-Forwards: 70
To: <sip:orchestrator@endpoint.twilio.com>;tag=76453107_6772d868_febd1002-1d04-49d4-9550-1f4526397718
From: <sip:e9808f79-4705-4973-95e6-7a8b076324c6@endpoint.twilio.com>;tag=bnpp3a376q
Call-ID: 9fcthmejd5ci6v41i5g9
CSeq: 1616 UPDATE
Session-Expires: 120
Supported: outbound, room-signaling, timer
User-Agent: SIP.js/0.7.7
Content-Length: 0
```

**Comment by katranci** [comment]
Hi @manjeshbhargav, I'm just curious if you managed to get to the bottom of it? We have a huge list of `Signaling connection disconnected` errors logged on Sentry. The fact that they are logged indicates users have internet connection. So I'm wondering if those errors stem from the same reason that kicked me out of the video room.

**Comment by innerverse** [comment]
Hi @katranci -

First, sorry you're running into this! 

I looked into your Participant, `PA4fa8500f609801874261ea5cfc5566fb` - the PCAP shows the Server repeatedly resending messages to the Client with no response from the Client SDK.  In the room `RMd6871644ae58ab363bf103049990b4c7` there are 219 ParticipantSids, using just 2 unique identities.  It doesn't appear that either Participant ever shares media in the Room.  Does your application repeatedly rejoin a Room based on some condition?

The message `Signaling connection disconnected` indicates that the Client has not sent a ping (UPDATE) message that the server has received, and the Server will disconnect the Client in this case.

If you're able to reproduce the issue again, can you please send a full client-side log?  The server logs don't indicate an issue alone, but together with a client-side log, we can investigate it further for you.  

Seth Miller
Twilio Video Team

**Comment by katranci** [comment]
Hi @innerverse, thanks for getting back.

You are correct, I've come across it in an auto-reconnect feature I'm working on at the moment. The crude implementation invokes connect api every time it is rejected until connection is established. 

What I have realised is that every time connect api is invoked a new WebSocket connection is created and each connection has an internal reconnect attempt with a backoff strategy. Therefore if I call connect 100 times then 100 WebSocket connections are created and each tries to reconnect. I suppose when internet connection comes back then WebSocket connections start connecting and creating ParticipantSids? The connections start shutting down gradually but sometimes giving `Signaling connection disconnected` error even after connect api is resolved.

I'm planning to put a network connection check and invoke connect api only if there is an internet connection but I believe things should still be stable without it.
