### ISSUE TITLE
Network Quality Levels for RemoteParticipants

### ISSUE THREAD

**Issue by katranci** [twilio/twilio-video.js#457]
We receive `networkQualityLevelChanged` event only on local participant and not on any remote participants.

**Comment by persamina** [comment]
Initially the networkQualityLevelChanged event will only fire for your LocalParticipant As per this, https://github.com/twilio/twilio-video.js/issues/392#issuecomment-411855501

**Comment by katranci** [comment]
Hi @manjeshbhargav,

I've upgraded to v2.0.0-beta8 and still not receiving `networkQualityLevelChanged` on remote participants. I'm passing `networkQuality: { local: 1, remote: 1 }` to enable it. Could you please check?

Thanks

**Comment by manjeshbhargav** [comment]
Hi @katranci ,

We have an internal test app which is using 2.0.0-beta8, and we are receiving the events. Can you try printing the `networkQualityLevel` on the RemotePadticipant to see if it has a value?

**Comment by katranci** [comment]
Hi @manjeshbhargav,

I've looked into it and realised that the event is is emitted only when remote participant publishes a track. That is different than how it works for the local participant. Local participant receives the event with networkQualityLevel of 5 as soon as they join the room.

**Comment by katranci** [comment]
Would it be possible to make network quality level available for remote participants as soon as they join the room?

**Comment by manjeshbhargav** [comment]
@katranci I talked to our Video Media Service team about your question, and this was their response:

> It can be possible, but we decided to provide  remote quality only for participants that are sending media to you as we thought that it doesn't make sense to have the quality for others. If we decide to report all other participants it shouldn't be hard to implement, but in a very big room you'll be sending a lot of not relevant data.

Based on what they've described, I think you can assume that a RemoteParticipant's Network Quality Level is 5 if no tracks are published. Does that make sense?

Thanks,

Manjesh Malavalli
JSDK Team
