### ISSUE TITLE
Unable to resolve sip dependency in latest release

### ISSUE THREAD

**Issue by newtriks** [twilio/twilio-video.js#46]
I've just updated to the latest dev release using `yarn` and discovered a new error seemingly related to https://github.com/twilio/twilio-video.js/commit/24e7320e1b4f56003f71b0a8ae48467cd0ffe7b4:

```
ERROR in ./~/sip.js/src/Grammar.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./Grammar/dist/Grammar
```

**Comment by newtriks** [comment]
Hi @markandrus,

Thanks for the quick reply. I'm on `v0.19.1`, odd...? I'll dig a bit more and see if I can come up with more info, not much more to report on than that though if I'm honest.

**Comment by markandrus** [comment]
That is odd... Here is what my little test package looks like:

```json
{
  "name": "test",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "twilio-video": "twilio/twilio-video.js#1.0.0-rc11"
  }
}
```

And then

```
$ yarn install
yarn install v0.19.1
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 2.95s.
```

🤔

**Comment by newtriks** [comment]
Hmmm, the only inconsistency I see is I reference this master branch directly in my `package.json`:

```
"twilio-video": "git+ssh://git@github.com/twilio/twilio-video.js.git#master",
```

Interestingly, this https://github.com/newtriks/twilio-video.js/commit/97339a53a0dd708a4e4a8393390c3c4c885fc2f4 fixes it for me.

**Comment by newtriks** [comment]
@markandrus 🎉 so `"twilio-video": "twilio/twilio-video.js#1.0.0-rc11",` fixes this for me, I guess pulling from master is a no-no 😄 Thanks for the quick response mate.

**Comment by markandrus** [comment]
NP, glad it's working now :-)
