### ISSUE TITLE
Firefox v63.0 showing warning from twilio-video.js:31306

### ISSUE THREAD

**Issue by smkrn110** [twilio/twilio-video.js#460]
Following warning message is appearing, on firefox version 65., seem twilio api is very much un stable with firefox, already reported other issue.

`Detected soon-to-break getStats() use with key="packetsLost"! stat.isRemote goes away in Firefox 65, but won't warn there! - See https://blog.mozilla.org/webrtc/getstats-isremote-65/ twilio-video.js:31306 `

**twilio-video-v1.14.1.js**

**Comment by manjeshbhargav** [comment]
@smkrn110 ,

Thanks for writing in with your issue. We are aware of this change in the WebRTC API, and we are working to accommodate this change. We will reach out to you once this is available.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by manjeshbhargav** [comment]
Hi @smkrn110 ,

The latest release, [twilio-video.js@2.0.0-beta5](https://github.com/twilio/twilio-video.js/blob/2.0.0-beta5/CHANGELOG.md) has a workaround for this issue. Please test and let me know. I am going to close this issue.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by AxelTheGerman** [comment]
@manjeshbhargav thanks for addressing this!

Is there an estimated timeline for getting v2 out of beta? - or a backlog of issues to see how far along we are.
Also is it recommended to use v2 in production?

**Comment by manjeshbhargav** [comment]
@AxelTheGerman ,

We are currently aiming for the first half of Q1, 2019. I definitely recommend using v2 in production since we are very close to GA.

Thanks,

Manjesh Malavalli
JSDK Team
