### ISSUE TITLE
Incorrect error handling in V2 signalling

### ISSUE THREAD

**Issue by katranci** [twilio/twilio-video.js#468]
Hello,

In V1 if a user enters the room with a duplicate identity then Video disconnects that user with TwilioError 53205. In V2 I can see this error in signalling payload however it is not exposed and Video thinks it is a signalling issue and tries to reconnect the user with error _Media connection failed_.

![image](https://user-images.githubusercontent.com/61077/49293851-31fb4000-f4a9-11e8-91a3-fa568b44a451.png)

**Comment by manjeshbhargav** [comment]
Hi @katranci ,

We have a release candidate undergoing testing right now. I will reach out to your soon once I can share this with you.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by manjeshbhargav** [comment]
Hi @katranci ,

The latest release, [twilio-video.js@2.0.0-beta5](https://github.com/twilio/twilio-video.js/blob/2.0.0-beta5/CHANGELOG.md) has the fix for this issue. Please let me know if this solves the problem for you.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by katranci** [comment]
Thanks @manjeshbhargav, seems like it issue has been resolved. Thanks a lot.
