### ISSUE TITLE
[Feature Request] Screen sharing only part of the screen

### ISSUE THREAD

**Issue by alielkhateeb** [twilio/twilio-video.js#474]
Hi,

I was wondering if this is even possible, can we share just one part of the screen?

I mean screen sharing has sources, like Desktop, Tab and so on, can we have the option to screen share one Div element only instead of sharing everything?

Thanks.

**Comment by manjeshbhargav** [comment]
@alielkhateeb ,

The [W3C Spec](https://w3c.github.io/mediacapture-screen-share/) for screen capture does not mention any way to capture only part of the media source. However, you could achieve something similar by rendering the video stream in a `<video>` element, capturing and cropping the frames on a `<canvas>` element and generating a new MediaStream from it.

You can use the `<canvas>` element to grab a frame from a `<video>` element like this:
```js
/**
 * Take snapshot of the video from the HTMLVideoElement and render it
 * in the HTMLCanvasElement.
 * @param {HTMLVideoElement} video
 * @param {HTMLCanvasElement} canvas
 */
function takeLocalVideoSnapshot(video, canvas) {
  var context = canvas.getContext('2d');
  context.clearRect(0, 0, canvas.width, canvas.height);
  context.drawImage(video, 0, 0, canvas.width, canvas.height);
}
```
If you want to continuously grab frames, you can use this function within [requestAnimationFrame](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame).

Please let me know if this works for you.

Thanks,

Manjesh Malavalli
JSDK Team
