### ISSUE TITLE
Muting all other participants to all other participants

### ISSUE THREAD

**Issue by shaharsol** [twilio/twilio-video.js#476]
Let's say I want to enable a single user in a group room the ability to mute all other participants for all other participants, effectively making her audio the only one everybody else hears 
Can I do that?

**Comment by manjeshbhargav** [comment]
@shaharsol ,

We do not support a Participant controlling other Participants' media. However, you can achieve this in your application code by assigning a Participant as the "speaker", which is the only Participant that will join the Room with an AudioTrack.

Please let me know if this works for you.

Thanks,

Manjesh Malavalli
JSDK Team
