### ISSUE TITLE
Network quality rating doesn't change

### ISSUE THREAD

**Issue by katranci** [twilio/twilio-video.js#487]
In video room RM0631269401e7dbf182827390eae404d0, I've throttled my network using Network Link Conditioner by switching between _Very Bad Network_, _100% Loss_, and unthrottled profiles several times but my network quality rating stayed at 5 all the time.

**Comment by katranci** [comment]
Thanks for getting back @manjeshbhargav. Not sure if you read my message fully but the network rating doesn't change on _Very Bad Network_ profile either. Do you keep a log for network quality changes on your side, and if you do what do you see for that room?

**Comment by manjeshbhargav** [comment]
Hi @katranci ,

I noticed that there are no tracks being published to the Room. Twilio depends on WebRTC media stats sent by the client to determine network quality. Can you retry your experiment with media?

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by jamesgraham** [comment]
Hi @manjeshbhargav, without any media, is it expected behaviour that it shows a rating of 5 (e.g. Excellent)?

**Comment by manjeshbhargav** [comment]
Hi @jamesgraham ,

The score is always relative to the usage of bandwidth by a Participant's media. So, in the case of no media, any type of network would have enough bandwidth to send no media. So the score will always be 5. I hope that makes sense.

We will make sure that the documentation clarifies the behavior of the Network Quality Score.

@katranci ,

I will close this issue for now. You can re-open it if you see the score not changing for unexpected reasons.

Thanks,

Manjesh Malavalli
JSDK Team
