### ISSUE TITLE
Participant left timeout

### ISSUE THREAD

**Issue by jamesgraham** [twilio/twilio-video.js#488]
If a participant closes their browser once connected to a room, we are seeing the participant left event fired around 60 seconds after the fact. Is this timeout configurable in V2?

You can see this on `PAfb8136f7dc6137e4001b9b59024e9bc3` as an example.

**Comment by manjeshbhargav** [comment]
Hi @jamesgraham ,

In twilio-video.js@2.x, we recommend that you call `room.disconnect()` on a page unload event like `onbeforeunload`. That way, other Participants get notified in real time.

Thanks,

Manjesh Malavalli
JSDK Team
