### ISSUE TITLE
Twilio Video Error with Firefox and Chrome

### ISSUE THREAD

**Issue by abhishekgahlot** [twilio/twilio-video.js#49]
Hi,

When I remove and add track from chrome and see the results in firefox the following error is generated in chrome.

Unhandled rejection TwilioError: Client is unable to apply a remote media description

Browser: Chrome 56, Mac and Firefox 51

**Comment by markandrus** [comment]
Hi @abhishekgahlot,

Was this issue fixed for you? I am wondering if there was something wrong with the library, our servers, or the browser under test. FWIW, we monitor browser releases and test against twilio-video.js builds, and our dashboards have been green. For reference,

![screen shot 2017-02-14 at 2 11 21 pm](https://cloud.githubusercontent.com/assets/359154/22951854/9c3ecdc6-f2bf-11e6-8a6f-0009356d0d67.png)

If you provide a Room SID, we can look at server logs as well.

Best,
Mark

**Comment by markandrus** [comment]
Hi @abhishekgahlot,

After some testing, I reproduced your issue. This is a server-side bug originating from our SDP translation (we need to translate between Chrome's "Plan B"-format SDPs and Firefox's "Unified Plan"-format SDPs—it appears we are hitting a bug there). I will re-open this issue until we fix the server-side bug.

Thanks!
Mark

**Comment by abhishekgahlot** [comment]
Hi @markandrus, Yes its related to the past twilio video mechanism where I had to turn off camera in both firefox and chrome using different API. But now it works fine in both firefox and chrome with addCamera and removeCamera in twilio room.

**Comment by ssskip** [comment]
@markandrus 

same problem:

sid: RM145b8f7a5d11431195b43e4cab47452b

**Comment by markandrus** [comment]
This particular bug (where Chrome, connected to Firefox, removes and adds a Track) has been fixed and deployed at the server-side.
