### ISSUE TITLE
On leaving room, video icon on browser remains there.

### ISSUE THREAD

**Issue by smkrn110** [twilio/twilio-video.js#492]
The video cam icon remains there in address bar even when the local participant, participants are detached and leave the room.

Twilio version 1.12.0.

**Comment by manjeshbhargav** [comment]
@smkrn110 ,

Thanks for writing in with your question. This is a behavior of Chrome where once you access the user's video camera, the icon will always be present until you refresh the browser tab. You can use `LocalVideoTrack.stop()` to ensure that the camera light turns off, but I don't think you can get the camera icon to go away.

I hope this answers your question.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by smkrn110** [comment]
Thanks, I had already reported this issue to google chrome so they could provide some API for that, it seems permissions for that tab remains there, could be a vulnerability issue in case if the user put some other app link having webcam functionality.
