### ISSUE TITLE
TwilioError: failed to allocate videosource on joining room.

### ISSUE THREAD

**Issue by smkrn110** [twilio/twilio-video.js#495]
The code is below, on connecting room, Twilio throw error **failed to allocate videosource**, being sure permissions are granted to the browser and also **NO** other application being utilizing the webcam.

This error is random having no particular steps to reproduce and encounter once by our app' client.

```
    Twilio.Video.connect(this.twToken, connectOptions).then((room) => {
         this.roomJoined(room)
    }, (e) => {
      console.error('Twilio Error ' + e.message);
    });
```
**Software versions:**
 - [x] Browser(s): Firefox
 - [x] Operating System: Mac
 - [x] twilio-video.js: v1.12.0
 - [x] Third-party libraries (e.g., Angular, React, etc.): Angular5+

**Comment by manjeshbhargav** [comment]
Hi @smkrn110 ,

Thanks for writing in. Is your application trying to get access to the video camera from an `<iframe>` by any chance? If yes, then it looks like it is a known Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1384800 .

Please let me know.

Thanks,

Manjesh Malavalli
JSDK Tean

**Comment by smkrn110** [comment]
No Iframe, its just SPA application, working totally fine, its random issue with no proper steps, otherwise would have provided them too. I had read **StackOverflow**, too on this issue.

- No Iframe.
- Permissions to devices camera/mic are already there. 
- Use to work fine on the same machine, the issue reported on.
- No other application accessing the cam/mic.

Thanks

**Comment by smkrn110** [comment]
Long time not faced this issue, so closing it for now.
