### ISSUE TITLE
Better handling of autoplay failures

### ISSUE THREAD

**Issue by ayavilevich** [twilio/twilio-video.js#496]
- [V] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [V] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [V] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [V] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

Chrome V70 added restrictions that prevent some video/audio streams from being activated until a user interaction happens with the page.
https://www.chromium.org/audio-video/autoplay

**Code to reproduce the issue:**

Take the quickstart js example. Change it to connect automatically to the room after getting the token. Change it to create no local tracks and pass no tracks at create. Basically make it a view only client that starts working right away on load.
Run this test on a new origin that is not already allowed in chrome://media-engagement/
Reload the page without clicking in the page.

**Expected behavior:**

No remote audio is heard and no remote video is show.
When attaching remote track, some error should be thrown because the track can't be played.

**Actual behavior:**

No remote audio is heard and no remote video is show.
No error is thrown. Attempting manual element.play() on the video/audio elements will throw an error.

**Suggestion:**

Twilio should not use "autoplay" property in track.attach because that doesn't provide indication about the success of the operation. Instead, it should call "play" explicitly and pass the error to the caller.
https://github.com/twilio/twilio-video.js/blob/3639775a9a880db6dc36f41537dbc734226ee751/lib/media/track/mediatrack.js#L155

**Software versions:**

 - [ ] Browser(s): Chrome 71.0.3578.98
 - [ ] Operating System: Mac, Android, Windows
 - [ ] twilio-video.js: 1.14.0 , 1.14.2
 - [ ] Third-party libraries (e.g., Angular, React, etc.): Vanilla and React

**Comment by manjeshbhargav** [comment]
Hi @ayavilevich ,

Thanks for writing in with your suggestion. Playback of HTMLMediaElements is out of the scope of twilio-video.js. There are three ways you can approach this problem:

1. Set autoplay to false on the video element returned by track.attach().
2. Provide your own video element without the autoplay attribute as an argument to track.attach().
3. You can set the video element 's

**Comment by thibaudcolas** [comment]
I had an issue similar to what’s described here. Even without a `video` or `audio` track created when using `connect` on page load, the video SDK would still trigger the autoplay detection because of the AudioContext created by `workaroundWebKitBug180748`. For me the solution was to only use this flag in Safari (with UA detection).

**Comment by antoniohof** [comment]
"For WebRTC audio playback, I don't think you need the HTMLAudioElement"
How is that possible?
