### ISSUE TITLE
Included SIP.js fails to parse constructed SIP URI

### ISSUE THREAD

**Issue by ngharo** [twilio/twilio-video.js#50]
Issue tracking isn't enabled on the twilio/SIP.js repo so I hope this OK.

master as of now fails initializing Twilio.Video.Client due to a parse failure:
`Invalid value "identity@account_sid.endpoint.twilio.com" for parameter "uri"`

This is bubbled up from a call to SIP.Grammar.parse that looks like:
`SIP.Grammar.parse('sip:identity@account_sid.endpoint.twilio.com', 'SIP_URI');`

My fix involved forking twilio/SIP.js and merging in upstream SIP.js changes then rebuild this project using it.  Let me know if you'd like PRs.

**Comment by markandrus** [comment]
Hi @ngharo,

Can you share some browser logs, the token, and/or the identity you used when triggering this error? Also, I'd be interested to see your changes. FWIW, I have an open issue regarding SIP.js's handling of SIP URIs [here](https://github.com/onsip/SIP.js/issues/286).

Best,
Mark

**Comment by ngharo** [comment]
Chrome Version 55.0.2883.87

I created a simple case here that shows the failure.  I get the same error in Firefox so I hope you can reproduce it.
https://cube.ngha.ro/twilio-test.htm
`exception {code: 1, name: "CONFIGURATION_ERROR", parameter: "uri", value: "caller@AC1ecfc46e738d70d36e65ec091136a16d.endpoint.twilio.com", message: "Invalid value "caller@AC1ecfc46e738d70d36e65ec091136a16d.endpoint.twilio.com" for parameter "uri""}`

When I do practically the same thing on jsfiddle, it works.
https://jsfiddle.net/ngharo/km5mjkxv/

I kind of feel like I'm going crazy.

My SIP.js changes can be seen here (I didnt do anything but merge upstream SIP.js into twilio/SIP.js)
https://github.com/ngharo/SIP.js
Here's my same test case but with twilio-video.js built using SIP.js from my repo
https://cube.ngha.ro/twilio-test_SIP.js-0.7.7.htm

**Comment by markandrus** [comment]
@ngharo ah, I figured out the problem. It only occurs with the minified version when you don't set the charset in your HTML. We should change our UglifyJS2 options to specify

```
-b beautify=false,ascii-only=true
```

However, you can also either

1. Add `<meta charset="UTF-8">` to the `<head>` of your `index.html`, or
2. Use the un-minified version.

Probably 1 is preferable for now. We will update the build script for future releases.

Sorry about that,
Mark

**Comment by ngharo** [comment]
Wow, thanks so much for figuring that out!

**Comment by markandrus** [comment]
NP, you're welcome @ngharo! We've merged a fix for future releases (as well as a test), so future versions should work even without charset.

Best,
Mark
