### ISSUE TITLE
Chrome 71.x does not subscribe remote tracks in 1.12+

### ISSUE THREAD

**Issue by sfakir** [twilio/twilio-video.js#505]
## Affected Systems:
* Affects only Browser Chrome Version 71.0.3578.98
* Affects twilio-video 1.12+;  ( 1.11 no issues ); I use now 1.15.0
* it's a client generated p2p room
## Behaviour:

```
   participant.trackPublications.forEach(publication => {
        publication.isSubscribed // always false;
    });
```
not fired:
- participant.on("trackSubscribed",...)
- participant.on("trackAdded", .. )

Values of **RemoteVideoTrackPublication**:

>     isSubscribed: false
>     isTrackEnabled: true
>     track: null
>     trackName: "d3f2d8d3-7af7-47e0-829e-9c0f76c1056c"
>     trackSid: "MT3a72401bd8b13c764a3021f0c78feec1"

    
## Expected Behaviour:

- Publications were automatically subscribed.
- trackAdded or trackSubscribed events were fired.
- ** It works like this in Firefox **

## Additional information
* trackSubscriptionFailed not fired
* version 1.11 -> everything works fine; update to 1.12 (or later) -> publications were not subscribed anymore
* Firefox to Chrome;  Firefox sees Chrome User as usual; Chrome user does not see (subscribe) the Firefox user.

**Comment by frederikbosch** [comment]
I am also having this. Basically, since I upgraded to 1.15 due to [the announcement](https://support.twilio.com/hc/en-us/articles/360012782494-Breaking-Changes-in-Twilio-Video-JavaScript-SDKs-December-2018-), I see more problems than before.

With 1.10 I saw ICE related issues, lately even more than before. With 1.15 I have problems establishing connections completely.

**Comment by frederikbosch** [comment]
I just tried 1.15.1 and so far I had no problems with the connections between the two. I do want to note that refreshing the page, while having a published video track, is troubling. It leads to an unresolved promise once the page is reloaded.

```log
Call leg/Transaction does not exist
```

**Comment by frederikbosch** [comment]
We are having problems with people seeing each other. This happened in room RM23a07295ae6374e614d6feeb9c3fd5f8. 

This room was used yesterday (feb 12) and today (feb 13). On both days we were having similar problems, only related to audio. We believe that it is likely the following is the case. The participant who joins the room first, is not able to hear to hear the others.

Our version is 1.15.2.

**Comment by manjeshbhargav** [comment]
Hi @frederikbosch ,

Chrome 71 has enabled an [autoplay policy](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes) where they don't play unmuted <video> tags with `autoplay=true`.  Please look at the browser console to see if you are getting any warnings regarding this.

If you are experiencing this, there are two ways to work around this:
1. Call `Twilio.Video.connect()` only after a user gesture, like a button click.
2. If you have to join a room on page load, then set the `muted` attribute to `true` on the <video> element returned by `Track.attach()`.

Please let me know if this helps.

Thanks,

Manjesh Malavalli
JSDK Team
