### ISSUE TITLE
Error: Cannot transition from "closed" to "updating

### ISSUE THREAD

**Issue by msi008** [twilio/twilio-video.js#506]
hi.  When cameras and microphones is none ,  With others P2P, Receive video track muted is true,
other error  is  "Error: Cannot transition from "closed" to "updating"  

error detail:
statemachine.js:362 Uncaught (in promise) Error: Cannot transition from "closed" to "updating"
    at PeerConnectionV2.transition (statemachine.js:362)
    at eval (peerconnection.js:934)
    at gotKey (statemachine.js:156)

Between chrome version 65 and 71 maybe no problem
What problems lead to?  thanks

**Comment by manjeshbhargav** [comment]
Hi @msi008 ,

Thanks for writing in with your question. Can you share your javscript console logs with me? Also, can you provide some Room SIDs where you are observing this error?

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by aibek-top** [comment]
Hi @manjeshbhargav ,

Our app also constantly receives this error, could you please let us know what could be the reason for this?

Here are some JS logs:
```
File webpack://_N_E/./node_modules/twilio-video/es5/statemachine.js:327:19 in t.transition
throw new Error("Cannot transition from \"" + this.state + "\" to \"" + newState + "\...
File webpack://_N_E/./node_modules/twilio-video/es5/signaling/v2/peerconnection.js:1486:19 in [anonymous]
_this.transition('updating', key);
File webpack://_N_E/./node_modules/twilio-video/es5/statemachine.js:157:20 in [anonymous]
return transitionFunction(key);
```
I unfortunately don't have the specific room SID for this, but in case needed I can let you know about our account SID and the timestamp in which this has occurred

Thank you
