### ISSUE TITLE
Electron 2x RemoteTracksPublication is not subscribed

### ISSUE THREAD

**Issue by kamesh-a** [twilio/twilio-video.js#507]
#### Group Call:
================
**Example room SID:**
	- RM5718ffec5bc4a17d0cab5344416454d7
	- RM03ec29900294a615266eed3a03caffc8

**Twilio-Video-JS-Lib:** `1.11` to `1.15 (latest)` We have ran our test with those mentioned Libraries in client side with clean module installations with `yarn`

**Client-1:** 
**Browser version:** _Electron 2.0.0_
**userAgent:** _Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) AnswerConnect/7.7.37 Chrome/61.0.3163.100 Electron/2.0.0 Safari/537.36 Tc-webkit_

NO **twilio-events** room are fired !!!

**Publication Object:**
```javascript
	- Remote{Audio|Video}Publication 
		{
			isSubscribed: false,
			isTrackEnabled: true
			track: null
		}
```

**Client-2:**
**Browser version:** _Electron 3.1.1_
**userAgent:** _Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) AnywhereWorks/7.7.81 Chrome/66.0.3359.181 Electron/3.1.1 Safari/537.36 Tc-webkit_

**Twilio-events:**
```javascript
	- Remote{Audio|Video}Publication 
		{
			isSubscribed: true,
			isTrackEnabled: true,
			track: <remoteTrack> is available
		}
	- participantConnected event came
	- trackSubscribed event came
```
Steps to Reproduce:
===============
1. Download `Electron-2x` and `Electron-3x` versions:
2. Start the development server from [electron-quick-start-compatible-with-twilio-1x-and-2x](https://github.com/kamesh-a/twilio-electron-quickstart)
3. `yarn start` - compile the build and start the server
4. Spun `Electron-2x` and `Electron-3x` version
5. Use the below snippet to launch the quickstart in electron dev console `cmd + shift + i`
```javascript
let {BrowserWindow} =  require('electron').remote.require('electron')
let win = new BrowserWindow({
	webPreferences : {
		nodeIntegration : false,
		devTools: true
	}
})
win.loadURL('http://localhost:3000')
```
6. Join the room

**Expected Behavior**:
- Room events after joining the room should be followed by `participantConnected` and `trackSubscribed` in both `electron2x` and `electron3x`

**Actual Behavior**:
- Room events after joining the room should be followed by `participantConnected` and `trackSubscribed` triggered in `electron3x`
- Room events are **NOT** triggered in `electron2x`

Also attached screen shots or remote participants from `Electron-2x` and `Electron-3x`

electron_2x: [Electron_2x_remote_track_publication](https://www.dropbox.com/s/tx3mbhvkwzjmjke/Screen%20Shot%202019-01-22%20at%203.52.55%20PM.png?dl=0)

electron_3x: [Electron_3x_remote_track_publication](https://www.dropbox.com/s/yt2ro64v1glkcx9/Screen%20Shot%202019-01-22%20at%203.53.20%20PM.png?dl=0)

PS: We are aware of that `Twilio-2x` won't support `Electron-2x` but, `Twilio-1x` build suddenly stopped emitting `tracksubscribed` in `electron-2x` this is production grade issue. Please do take a look at it.

**Comment by manjeshbhargav** [comment]
Hi @kamesh-a ,

I'm sorry that you ran into this problem. I think the changes in 2.x to support Unified Plan SDPs in Chrome, which result in twilio-video.js not supporting Electron 2.x was also introduced in 1.x. I will work to restore support for Electron 2.x (in our 1.x APIs) right away. Please look out for twilio-video.js@1.15.1.

Once again, I apologize for this mis-step. Thank you so much for bringing this to our notice.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by manjeshbhargav** [comment]
Hi @kamesh-a ,

I wanted to let you know that I have cut a release candidate with a fix for this issue. I will reach out to you once this is released.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by kamesh-a** [comment]
@manjeshbhargav 

Great Thanks.

**Comment by kamesh-a** [comment]
@manjeshbhargav When we are expecting this release to from release candidate to release.

**Comment by manjeshbhargav** [comment]
Hi @kamesh-a ,

The release candidate is undergoing a final round of testing, and should be released by EOD Monday.
Thank you so much for your patience and understanding.

Manjesh Malavalli
JSDK Team

**Comment by kamesh-a** [comment]
Hi @manjeshbhargav 

Thank you for update, We really appreciate your timely help on this bug 👍, Have a great day!!!

**Comment by manjeshbhargav** [comment]
Hi @kamesh-a ,

twilio-video.js@1.15.1 is available on NPM and Twilio CDN. Please let me know if this fixes your issues on Electron 2.x.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by kamesh-a** [comment]
Hello @manjeshbhargav 

Yes, it worked 👍 Thanks for looking into this. Closing the issue :)
