### ISSUE TITLE
Question! What is the difference between the two ways of 'trackSubscribed'?

### ISSUE THREAD

**Issue by smkrn110** [twilio/twilio-video.js#512]
What is the difference between these two ways and also which is the better way? Or both to be used?

**bind on room:** (as per the quickstart app)
```
  room.on('trackSubscribed', function(track, publication, participant) => {
  });
```

**bind on participants:** (as per the README.md git-repo)
```
  room.on('participantConnected', function(participant) {
    participant.on('trackSubscribed', track => trackSubscribed(div, track));
  });
```

https://stackoverflow.com/questions/54344311/what-is-the-difference-between-the-two-ways-of-tracksubscribed

**Comment by manjeshbhargav** [comment]
Hi @smkrn110 ,

Thanks for writing in with your question. We bubble up all events to the Room object. The QuickStart app shows you how to get started quickly with as few lines of code as possible. Once you're familiar with the APIs, my recommendation would be to listen to events on objects which emit them. In the case of Track subscription, the first event that gets fired is "subscribed" on the RemoteTrackPublication, which bubbles up to the RemoteParticipant as "trackSubscribed", which in turn bubbles up to the Room.

I hope this clarifies things for you.

Thanks,

Manjesh Malavalli
JSDK Team
