### ISSUE TITLE
videoTracks have tracks set as null

### ISSUE THREAD

**Issue by webzvornikgit** [twilio/twilio-video.js#520]
After updating to latest beta5 version videoTracks have tracks array which is always null.
If I downgrade to beta1 it works well for video, but audio is a guess, sometimes works sometimes don't, but that is different issue, but video track always contained real tracks.

In beta5 audio tracks are well attached/working well, just problem with video tracks inside videoTracks being set as null.

**How to Reproduce**

Start a video call with both sides sharing video and it will cause problems. Other side can be whichever ( Chrome, Firefox, Android ), only problem is in iOS.

**Software versions:**

 - [x] Browser(s): Safari
 - [x] Operating System: iOS
 - [x] twilio-video.js: 2.0.0-beta5
 - [x] Third-party libraries (e.g., Angular, React, etc.): AngularJS

**Comment by manjeshbhargav** [comment]
Hi @webzvornikgit ,

Thanks for writing in with your question. Can you provide some Room SIDs so that we can take a look at the logs for them? In the meantime, I will see if I can reproduce this issue.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by webzvornikgit** [comment]
> 
> 
> Hi @webzvornikgit ,
> 
> Thanks for writing in with your question. Can you provide some Room SIDs so that we can take a look at the logs for them? In the meantime, I will see if I can reproduce this issue.
> 
> Thanks,
> 
> Manjesh Malavalli
> JSDK Team

Thank you for quick reply.

Room SID is: RM475a2f51ff7869aa247188137c8e0c88

But there was many more on that account yesterday, today we went back to older version, trying to re-write twilio-video.js to fit updates without this problem, but haven't found efficient way to to cover both video track missing and having audio tracks always.

In recording both sides of video are visible, just when it comes to receiving end the track object inside videoTracks is null.

Thank you!

Best regards,
Nenad

**Comment by webzvornikgit** [comment]
**Quick update**

Just checked audio vs video tracks, and it looks like when video is on, if it happens that works, in that case audioTracks have track but it is null, and audio is combined with video in video track. In this case I can hear and see remote tracks over videoTracks.

It looks like one is canceling other making it null and joining with other one.

Is in case I wrote above videoTracks null because audioTracks ( somehow ) merged video and audio?

Thank you.

**Comment by manjeshbhargav** [comment]
Hi @webzvornikgit ,

I took a look at the Room SID that you gave me. It looks like one Participant was on twilio-video.js@1.15.0 and the other Participant was on twilio-video.js@2.0.0-beta1. The SDK object model has changed with our 2.x APIs, and I recommend that you follow this [guide](https://www.twilio.com/docs/video/migrating-1x-2x) to migrate your app to use the latest 2.x SDK version 2.0.0-beta5.

Please let me know if you still experience issues once all Participants join a Room with the SDK version 2.0,0-beta5.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by manjeshbhargav** [comment]
@webzvornikgit ,

Thanks for the info. Can you let me know what version of Safari and iOS you are using? I can then work with QA to try and reproduce this on our end.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by quentinhayot** [comment]
Hi,
We just stumbled onto this issue too. But it's not only iOS related:
- Data tracks are NOT affected
- Audio and video tracks are affected
- Firefox <-> Firefox : ✅ 
- Firefox <-> Safari : ✅ 
- Firefox <-> Chrome : 🔴(Firefox gets all remote tracks correctly but chrome only gets data)
- Chrome <-> Safari : 🔴(Safari gets all remote tracks correctly but chrome only gets data)
- Chrome <-> Chrome :  🔴(Only data tracks are working)
- Android (sdk 2) <-> Safari : ✅
- Android (sdk 2) <-> Chrome : 🔴(Android gets audio and video, chrome gets nothing - data not tested)
- Android (sdk 2) <-> Firefox : 🔴(Firefox get audio and video, Android gets nothing)

In all case all publications are there but in the  🔴cases, audio and video publications will have "track" set to "null" and isSubscribed to "false".

Hope this helps !

**Comment by honeykapoor7** [comment]
videoTracks have tracks set as null #520
 Same issues is in android phone while other end is chrome browser

**Comment by jaxonjma** [comment]
Maybe this can help...
https://github.com/twilio/twilio-video.js/issues/899
