### ISSUE TITLE
Duplicate remote participant

### ISSUE THREAD

**Issue by shrutigv** [twilio/twilio-video.js#525]
- [ ] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [ ] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ ] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [ ] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

@manjeshbhargav

**I am trying to stream multiple video stream from a local participant. I am able to stream web cam and external camera stream but I see remote participant duplicated. Help much appreciated**

**Code to reproduce the issue:**

```js
Video.connect(token, { audio: true, video: { width: 640 } ,name:this.meetingRoom} ).then(room => {
                room = room;
  })
room.on('participantConnected', this.onParticipantConnected);
            //If a local Participant leaves the conference
room.on('disconnected', this.disconnect);
room.on('trackSubscribed',(remoteTrack)=>{
                this.count++;
                if(remoteTrack){                  
                    this.$refs.remoteVideo.appendChild(remoteTrack.attach());                  
                // const remoteLabel = document.createTextNode(participant.identity.toString());
                if(this.count == 1){
                    //const remotePTag = document.createElement("p");
                    //remotePTag.innerHTML = remoteParticipant.identity.toString();
                    //this.$refs.remoteVideo.appendChild(remotePTag);
                }
                }
            });
            navigator.mediaDevices.enumerateDevices()
            .then((devices)=>{
              let devicesList = devices.filter(devices => devices.kind =='videoinput');
              devicesList.forEach((device)=>{
                 Video.createLocalVideoTrack({
                    deviceId: { exact: device.deviceId }
                  }).then((localVideoTrack)=>{
                    room.localParticipant.publishTrack(localVideoTrack);
                    console.log(room.localParticipant.identity," added track: ",localVideoTrack.name);
                    this.$refs.selfVideo.appendChild(localVideoTrack.attach());
                  }).catch((error)=>{
                    console.log(error);
                  })
              });
            }).catch((err)=>{
              console.log(err);
            });   
```

**Expected behavior:**
only one remote participant

TODO

**Actual behavior:**
I see duplicate remote participant

TODO

**Software versions:**

 - [ ] Browser(s):
 - [ ] Operating System:
 - [ ] twilio-video.js:
 - [ ] Third-party libraries (e.g., Angular, React, etc.):

**Comment by shrutigv** [comment]
Thanks @manjeshbhargav for writing back. Tried subscribing on participant but still i see duplicate remote video get attached. 

```
initiateTwilioVideo(room){  
            room.on('participantConnected', this.onParticipantConnected);
            //If a local Participant leaves the conference
            room.on('disconnected', this.disconnect);
            
            navigator.mediaDevices.enumerateDevices()
            .then((devices)=>{
              let devicesList = devices.filter(devices => devices.kind =='videoinput');
              devicesList.forEach((device)=>{
                 Video.createLocalVideoTrack({
                    deviceId: { exact: device.deviceId }
                  }).then((localVideoTrack)=>{
                    room.localParticipant.publishTrack(localVideoTrack);
                    
                    //this.$refs.selfVideo.appendChild(localVideoTrack.attach());
                  }).catch((error)=>{
                    console.log(error);
                  })
              });
            }).catch((err)=>{
              console.log(err);
            });            
            const trackValues = Array.from(room.localParticipant.tracks.values());
            this.tracks = trackValues;
            if(this.tracks.length > 0){
                this.tracks.forEach(track => {
                    this.$refs.selfVideo.appendChild(track.attach());
                });
            }
            // const selfLabel = document.createTextNode(room.localParticipant.identity.toString());
            //const selfPTag = document.createElement("p");
            //selfPTag.innerHTML = room.localParticipant.identity.toString();
            //this.$refs.selfVideo.appendChild(selfPTag);
            
      },
       
      generateAccessToken(){
             this.loaderText = 'Generating Token...';       
            const accessTokenService = appContext.sendAsyncRequest('http://inblrcaobr:5000/videoGrantToken','GET');
            accessTokenService.then((data)=>{
                this.connectRoom(data.token);
            });
      },
      disconnect(){
            this.room ? this.room.disconnect():null;
            this.$router.push('/');
        },
      onParticipantConnected(participant){
        participant.on('trackSubscribed',(track)=>{
                if(track){
                    console.log('remoteTrack',track.name);            
                    this.$refs.remoteVideo.appendChild(track.attach());
                }
            });
            setInterval(()=>{
            if(!this.isRemoteParticipantConnected){
                let tempList = this.remoteParticipantList.length>0 ? this.remoteParticipantList : [];
                tempList.push(participant);
                this.remoteParticipantList = tempList;    
                this.isRemoteParticipantConnected = true;
            }
            },3000);
     },
      connectRoom(token){
            this.loaderText = 'Connecting to Room...';
            //PAJ - 26th Sept 2018 - Added Video Setting to be 640
            Video.connect(token, { audio: true, video: { width: 640 } ,name:this.meetingRoom} ).then(room => {
                this.room = room;
                this.localParticipant=room.localParticipant;
                this.initiateTwilioVideo(this.room);
            })
        }
    },
```

remote video tracks are duplicated but the track name are different.

Thanks,
Shruti

**Comment by manjeshbhargav** [comment]
Hi @shrutigv ,

In your code snippet, it looks like you are publishing more than one video track. Can you clarify what you mean by duplicate remote video?

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by shrutigv** [comment]
Hi @manjeshbhargav ,

I am trying to stream multiple video like streaming web cam and external camera stream to remote participant. When i stream these video to remote participant I see duplicate remote participants connected to call with the 2 local video stream.

Thanks
Shruti

**Comment by shrutigv** [comment]
@twilio-sdk-build @manjeshbhargav @twilio-ci  can someone help me out with the above???/

**Comment by manjeshbhargav** [comment]
Hi @shrutigv ,

Can you list the Rooms RemoteParticipants in the javascript console? If you are in a 1-on-1 Room, then you should see only one RemoteParticipant. You can list the Room's RemoteParticipants this way:
```js
room.participants
```
This will return a Map of RemoteParticipant SIDs and RemoteParticipants. The size of this Map should be one. Please let me know what you find.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by RussNZ** [comment]
@shrutigv I've just come across the same problem.

I think `room.localParticipant.publishTrack(localVideoTrack)` adds a second video track to participants, I presume the connect method itself creates the first video track? 

Most of the examples I've come across do this. I'm not sure how you'd handle clean up of local tracks if you don't do this though? @manjeshbhargav might be able to elaborate?

**Comment by manjeshbhargav** [comment]
Hi @RussNZ @shrutigv ,

Sorry for the delayed response. I think I know where the problem is. If you call `connect()` without specifying `tracks` in `ConnectOptions`, then twilio-video.js will automatically publishes local media (audio + video) to the Room while joining. twilio-video.js then takes the responsibility of cleaning up such automatically acquired LocalTracks. If you want to control local media acquisition and clean-up, you can use `createLocalTracks()` and then pass in the acquired LocalTracks to `ConnectOptions` in the `tracks` property. For more details, please refer to the [connect() documentation](https://media.twiliocdn.com/sdk/js/video/releases/2.0.0-beta5/docs/global.html#connect).

Hope this clear things up for you.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by RussNZ** [comment]
@manjeshbhargav Thanks for clarifying.

**Comment by ZachMoreno** [comment]
Came across this same issue & found that using `participant.on('trackAdded', (track) => { ... })` does not cause the duplicate remote participant issue, only with `participant.on('trackSubscribed', (track) => { ... })`. `RemoteParticipant#trackAdded` has, of course, been deprecated & is scheduled for removal in 2.0.0.

**Comment by ZachMoreno** [comment]
I can also verify that specifying `LocalAudioTrack` & `LocalVideoTrack` as values for the `audio` & `video` properties within the `ConnectOptions` does not resolve this issue with `participant.on('trackSubscribed', (track) => { ... })`. The temporary solution I've found is to use `participant.on('trackAdded', (track) => { ... })`, but using deprecated code is not cool. Details are below.

```
const token = 'fromBackend';
const name = 'videoRoom';
const microphone = { deviceId: '123' };
const camera = { deviceId: 'abc' };

createLocalAudioTrack({ deviceId: { exact: microphone.deviceId } }).then((newAudioTrack) => {
    audioTrack = newAudioTrack;

    return createLocalVideoTrack({ deviceId: { exact: camera.deviceId } });
}).then((newVideoTrack) => {
    videoTrack = newVideoTrack;

    return Video.connect(token, {
        name: name,
	audio: audioTrack,
	video: videoTrack
    });
}).then((room) => {
    room.on('participantConnected', (participant) => {

        // we push each participant to an array & then template each into the DOM, each containing its own respective participant. On init of each participant element we do the following...

        participant.tracks.forEach((track: any) => { subscribeTrack(element, track); });

        // causes duplicate remote participant video & audio elements to be attached to the DOM
	// participant.on('trackSubscribed', (track) => { subscribeTrack(element, track); });
        // participant.on('trackUnsubscribe', (track) => { unsubscribeTrack(track); });

        // are deprecated, but do not cause the issue
	participant.on('trackAdded', (track) => { subscribeTrack(element, track); });
	participant.on('trackRemoved', (track) => { unsubscribeTrack(track); });
    });
});

const subscribeTrack = (element, track) => {
    const trackElement = track.attach();
    element.appendChild(trackElement);
}

const unsubscribeTrack = (track) => {
    track.detach().forEach((element) => {
        element.remove();
    });
}
```

**Comment by manjeshbhargav** [comment]
Hi @ZachMoreno ,

In your code snippet, the `audio` and `video` ConnectOptions parameters accept [MediaTrackConstraints](https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints) objects, not LocalTrack objects. If you want to pass LocalTracks, please use the `tracks` parameter:

```js
connect(token, {
  tracks: [audioTrack, videoTrack]
});
```

Also, please make sure you are publishing only one audio track and one video track by checking `room.localParticipant.audioTracks` and `room.localParticipant.videoTracks`. On the other side, check the `.audioTracks` and `.videoTracks` collections for the corresponding RemoteParticipant to see if there are more than one audio tracks and video tracks. Let me know what you find.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by anasappsaya** [comment]
Hi, Maybe I am wrong, but I noticed that
` participant.on("trackSubscribed", (track) => {})`
is executed twice, once for the video track and another for the audio one. As a result, It seems like there is a duplicate track, but it is only one.
Is it normal? 

Thank you for your responses.

**Comment by naserio** [comment]
I'm having the same issue of duplicate tracks when users rejoin. was there a solution not posted here?

**Comment by ashish-beetle** [comment]
[manjeshbhargav](https://github.com/manjeshbhargav)]  I am facing the same issue. For some reason, the "trackSubscribed" event is being triggered twice when a participant joins. 
I am using .connect() to join the room with only roomName connectOpitons. Then I am using createLocalTracks() to publishTracks() with the video and audio options.
Does this create two instances of the the same user?

The only workaround I could think of to solve the issue for now is to write a condition to check if the remote div already has a video or audio element and then stop the traack.attach() depending on the result. Please let me know if there is a better solution as the event is still being triggred twice although the video is not duplicated.

[shrutigv](https://github.com/shrutigv)] were you able to find a solution?
