### ISSUE TITLE
audioLevel issues in stats

### ISSUE THREAD

**Issue by seanmetrix** [twilio/twilio-video.js#526]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

We just upgraded from 1.5 to 2.0.0-beta5 and noticed the following issues with the audioLevel values in stats.

1) LocalAudioTrackStats always has a audioLevel of 0. Even though the other side can hear the audio just fine.

2) For the RemoteAudioTrackStats of that same audio stream that is reporting audioLevel=0 on the source, it appears to be a decimal value between 0-1 - the documentation says it should be an int between 0 and 32767, which is what it was doing on the 1.5 version.

```js
// TODO
```

**Expected behavior:**

TODO

**Actual behavior:**

TODO

**Software versions:**

 - [ ] Browser(s):
 - [ ] Operating System:
 - [ ] twilio-video.js:
 - [ ] Third-party libraries (e.g., Angular, React, etc.):

**Comment by seanmetrix** [comment]
Sorry - I clicked save too early.

This is on Windows10, Chrome 71.0.3578.98

**Comment by manjeshbhargav** [comment]
Hi @seanmetrix ,

Thanks for writing in with your question. You are seeing this behavior because of this [Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=736403). We had to stop using Chromium's legacy `getStats` API because it has been deprecated and is scheduled for removal, and will no longer work when Chromium [switches](https://webrtc.org/web-apis/chrome/unified-plan/) to "unified-plan" as the default SDP semantics.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by tr00st** [comment]
Just checking in on this one, as the linked Chromium bug is marked as resolved. Our application's currently receiving "null" _audioLevel_ and _jitter_ values for local tracks - presuming this is an indication that the issue's still occurring, given I can't find anything in the docs about enabling these stats for local streams?

**Comment by manjeshbhargav** [comment]
Hi @seanmetrix , @tr00st ,

Since we last chatted, we have released some bug fixes regarding stats. Can you try the latest SDK version (2.7.1) to see if this is fixed? I'll close the issue, but we can continue the discussion here.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by tr00st** [comment]
Hi Manjesh,

Thanks for the update. Just ran a couple of tests using 2.7.1 and I still appear to be hitting the same behaviour for audioLevel (ie: constantly zero) - looks like jitter may be picking up correctly. I'll try and clean up the code I'm using to pull the audio levels out and see if there's anything obvious on my end.

**Comment by tr00st** [comment]
@manjeshbhargav - any chance of a reopen on this, as it still appears to be occurring?

**Comment by julien-l** [comment]
This might help getting the audio level on Chromium browsers:

**Attach** the track to the HTML document:

    room.on('trackSubscribed', function(track, publication, participant) {
        if (track.kind === 'audio' && track.name == 'your track') {
            var div = document.getElementById('your HTML element');
            div.appendChild(track.attach());
    });

However the returned value is incorrect on Chromium. I log the audio level for debugging:

    room.getStats().then(function(value) {
        value[0].remoteAudioTrackStats.forEach(function(track) {
            console.log(`track.trackSid: ${track.trackSid} level ${track.audioLevel}`);
        });
    });

On Brave Browser on Mac OS:

    // not speaking, room is silent:
    track.trackSid: MTfbcf486eef... level 753641
    track.trackSid: MTfbcf486eef... level 753641
    track.trackSid: MTfbcf486eef... level 819175
    track.trackSid: MTfbcf486eef... level 622573

    // when speaking:
    track.trackSid: MTfbcf486eef... level 243688179
    track.trackSid: MTfbcf486eef... level 12746363

Audio levels are clearly out of bound.

On the other hand, Safari does not need to attach the track and audio levels are normal:

    [Log] track.trackSid: MT3af13d71... level null
    [Log] track.trackSid: MT3af13d71... level 43
    [Log] track.trackSid: MT3af13d71... level 28
    [Log] track.trackSid: MT3af13d71... level 23

**Comment by shyamady** [comment]
I tried this, but I can't get the `audioLevel` in real time and it remains `null`.

```
participant.on('trackSubscribed', (track) => {
  handleRemoteSoundCheck()
})

const handleRemoteSoundCheck = (twilioIdentity: string) => {
  twilioRoom.getStats().then(function (value) {
    value[0].remoteAudioTrackStats.forEach(function (track) {
      console.log(
        `track.trackSid: ${track.trackSid} level ${track.audioLevel}`,
      )
    })
  })
}
```

**Comment by charliesantos** [comment]
audioLevel should now show in 2.18.3. However, it is not supported in firefox, and in local audio tracks in safari.
