### ISSUE TITLE
Error: Media connection failed onn reconnecting event.

### ISSUE THREAD

**Issue by smkrn110** [twilio/twilio-video.js#530]
@manjeshbhargav, thanks for being so responsive. 

I like to tell you without enabling of it, 'reconnecting' and 'reconnected' event still emits. I tried with `_useTwilioConnection: true,` , also. I am receiving an error on reconnecting event **Media connection failed.**, although after that reconnected event also emit. 

The issue I am facing is, media tracks remain stuck. I try to re-attach the tracks after the reconnected event, but no success.

_Originally posted by @smkrn110 in https://github.com/twilio/twilio-video.js/issues/503#issuecomment-460652047_

**Comment by smkrn110** [comment]
Hi Team,

Just a little bit curious regarding the error **Media Connection failed** on `room.on('reconnectiving',..)` event, I search in the https://media.twiliocdn.com/sdk/js/video/releases/2.0.0-beta5/twilio-video.js on line#6724, and found this ` room.emit('reconnecting', new MediaConnectionError());`

In that case, I will always be getting this error message on reconnecting event.

```
signaling.on('stateChanged', function stateChanged(state, error) {
  log.info('Transitioned to state:', state);
  switch (state) {
    case 'disconnected':
      room.participants.forEach(function (participant) {
        participant._unsubscribeTracks();
      });
      room.emit(state, room, error);
      signaling.removeListener('stateChanged', stateChanged);
      break;
    case 'reconnecting':
      room.emit('reconnecting', new MediaConnectionError());
      break;
    default:
      room.emit('reconnected');
  }
});
```

**Comment by manjeshbhargav** [comment]
Hi @smkrn110 ,

Thanks for writing in with your question. I have responded to this message in #503 so I'm going to close this issue.

Thanks,

Manjesh Malavalli
JSDK Team
