### ISSUE TITLE
Chrome red circular icon does not dis-appears.

### ISSUE THREAD

**Issue by smkrn110** [twilio/twilio-video.js#531]
Hi Team,

I tried with the self-written snippet to verify that on calling the **stop** method on the **MediaStreamTrack**, the red circular icon in the tab gets disappear.

Besides, on `room.disconnect` event the following code does not work always, but on verifying the **track.mediaStreamTrack** the state is also found to be `'ended'`, but the red circular icon in the tab does not disappear.

```
room.on('disconnected', (room) => {
  room.localParticipant.tracks.forEach(function (track) {
     track.stop();
  });
});
```

I then try with **clone** method in **MediaStreamTrack** in my self-written snippet, able to reproduce the same behavior. I think Twilio SDK does not perform the **stop** event with all the references of that **mediaStreamTrack**. 

Can you verify and update on this issue, as it is reported by our client considering a compliance issue.

 - [x] Browser(s): Chrome v71+
 - [x] Operating System: Windows & Ubuntu
 - [x] twilio-video.js: v1.14.1
 - [x] Third-party libraries (e.g., Angular, React, etc.): Angular 5

**Comment by manjeshbhargav** [comment]
Hi @smkrn110 ,

Can you try running the [Video JS QuickStart]() and connecting to a Room? Then, when you hit the "leave room" button, do you see the red circular icon going off?

Please let me know. Also, we do not clone MediaStreamTracks in the 1.x APIs. So I'm surprised you are experiencing this issue.

Also, it would be great if you can let me know how you acquire your local tracks and how you stop them once you leave the Room.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by smkrn110** [comment]
@manjeshbhargav 

Yes, I test the quickstart app, and it's working fine. I will be verifying our app code further and update you accordingly.

Thanks.

**Comment by smkrn110** [comment]
@manjeshbhargav 

The issue was at our end, and fixed.

**Comment by chiragpurohit71085** [comment]
HI I am facing the same issue.  When user clicks on disconnect room I am detaching all tracks and also un-publishing tracks

````

				this.state.localVideoTracks.forEach(function (track) {
					if (track) {



						track.detach().forEach(function (detachedElement) {
							console.log("detachedElement local video - ", detachedElement);
							detachedElement.remove();
						});

						track.stop();
						track.disable();



					}
				});

				this.state.localAudioTracks.forEach(function (track) {
					if (track) {

						console.log("detached local audio - ", track);
						


						track.detach().forEach(function (detachedElement) {

							console.log("detachedElement local audio - ", detachedElement);
							detachedElement.remove();

						});

						track.stop();
						track.disable();


					}
				});
				


````
