### ISSUE TITLE
Can't join room with Firefox when in "Responsive Design Mode"

### ISSUE THREAD

**Issue by ayavilevich** [twilio/twilio-video.js#543]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Steps to reproduce the issue:**

Open quickstart example in Firefox, open developer tools and connect to room. Should connect ok.
Open "Responsive Design Mode" in the dev tools and reload the page. Try to connect to room. Does not connect.
Getting stuck in the sip.transport/ua phase. If logLevel is set, can see "sending Websocket message:" with no data inside.
Doesn't matter what device I select in "Responsive Design Mode". Happens even for "Responsive" device which doesn't change userAgent and should not change any browser webrtc functionality.

**Expected behavior:**

Connect to room.

**Actual behavior:**

Gets "stuck" in room connection phase.

**Software versions:**

 - [x] Browser(s): Firefox 65 (not tested in other versions but I don't remember this being an issue before)
 - [x] Operating System: Windows 10
 - [x] twilio-video.js: 15.2 as well as other versions
 - [x] Third-party libraries (e.g., Angular, React, etc.): happens with react but also in quickstart.

**Comment by manjeshbhargav** [comment]
Hi @ayavilevich ,

Thanks for writing in with your question. I did some cursory testing, and it looks like WebSockets are being throttled in the responsive design mode. This might be a regression in Firefox. Can you try with earlier versions of Firefox (64 and 63, if possible)? I will try on my end when I have some time as well.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by ayavilevich** [comment]
Hi @manjeshbhargav 

Had 64.0.2 and 63.0.3 available. Tested and both have the same issue as latest Firefox version.
Interested to know what Firefox does different in the responsive mode.
