### ISSUE TITLE
VideoTracks not showing while joining from iOS to Chrome 7[Mac]

### ISSUE THREAD

**Issue by sathishvgs** [twilio/twilio-video.js#551]
**Description:**

Participants video not showing on my Mac browser. I have joined the room from iOS to Chrome 7 [Mac]. I got the participants Audio tracks but the Video track alone not showing in browser.

**Scenario:**
1. Local Participant L creates the room from iOS.
2. Remote Participant R1 joined the room from Chrome 7 [Mac]
3. Room is connected and both subscribed their Video and Audio tracks.
4. Local Participant L got the Video and Audio tracks who joined from iOS
5. **Remote Participant R1 who joins from Mac got the AudioTrack but didn't get the VideoTrack .**

**Things to note:**
1. If both the participant joins the call from Mobile [either iOS or Android], it's working fine with Audio and Video tracks.

> Note: The issue is happening only from iOS to Web.

**Expected behaviour:**
If the participant joins the room from any device or Machine, the Audio and Video track should work.

**Reproduce:**
100% percentage Reproducible.

**Versions:**

Twilio iOS sdk version     -        2.7.0
Twilio Js   sdk version     -        1.15.2

iOS - 12.1.4
Browser - Chrome 7

**Comment by manjeshbhargav** [comment]
Hi @sathishvgs ,

Thanks for writing in with your question. Can you provide SIDs of the affected Rooms? Also, can you check the browser console logs to see if there are any errors, and paste them here?

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by sathishvgs** [comment]
Hi @manjeshbhargav ,

Here is the Info,
Room SID -> RMeb3e8a75d2b78db4f8e86c3d39d564e8

**Comment by kamesh-a** [comment]
Please close this issue, Thanks issue got rectified @manjeshbhargav

**Comment by manjeshbhargav** [comment]
@kamesh-a ,

Great that you're issue got solved. Thank you for helping us in assisting you with your issue.

Manjesh Malavalli
JSDK Team

**Comment by kamesh-a** [comment]
@manjeshbhargav 

Thanks for your quick response on issues and helping us resolve it. We really appreciate it.

Have a good day !!!

**Comment by romil-officetroops** [comment]
@kamesh-a  I am facing the same issue. How can I resolve this issue?

**Comment by kamesh-a** [comment]
@romil-officetroops

From IOS Application level for each video track while creation we didn't give a  `{ name : 'camera' or 'screen' }` but from our WebApplication level we where expecting video track supposed to be in either  with { name: 'camera' } or { name:'screen' } so our validation skipped them to add it to our view.

This was the issue what we faced. We were getting **videoTracks** and **AudioTracks** BTW.
