### ISSUE TITLE
How to make use of getDisplayMedia from chrome-72 for screen capture

### ISSUE THREAD

**Issue by kamesh-a** [twilio/twilio-video.js#552]
Hello, 

Would like to leverage the native media api for desktop screen capture, which solves the problem of needing to install the chrome extension for capturing video.

https://www.chromestatus.com/feature/6744724455030784

How to make use of the captured stream with twilio library. Please advise.

Browser Version : Chrome 72.

**Comment by manjeshbhargav** [comment]
Hi @kamesh-a ,

Thanks for writing in with your question. You can use the [LocalVideoTrack](https://media.twiliocdn.com/sdk/js/video/releases/2.0.0-beta5/docs/LocalVideoTrack.html) constructor with the MediaStreamTrack(s) returned by `getDisplayMedia()`:
```js
const { LocalVideoTrack } = require('twilio-video');

const stream = await navigator.mediaDevices.getDisplayMedia({
  /* constraints */
});

const tracks = stream.getVideoTracks().forEach(mediaStreamTrack => {
  return new LocalVideoTrack(mediaStreamTrack);
});
```

Hope this helps.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by kamesh-a** [comment]
Ah, I was looking to global functions, I missed the classes :) Thanks @manjeshbhargav
