### ISSUE TITLE
RemoteParticipant video/audio not showing on Chrome 72 

### ISSUE THREAD

**Issue by nakulypatil** [twilio/twilio-video.js#553]
Description: 
After updating to Javascript 2.0.0-beta5 version on Chrome 72 remote participant video/audio track not showing on browser. 
publication.isSubscribed is always false and track also null.

flow: 
Chrome Browser to Android/ios app

Versions;
Javascript 2.0.0-beta5
Android 2.+ and 3+ both tested not working
iOs 2+ tested not working

**Comment by manjeshbhargav** [comment]
Hi @nakulypatil ,

I apologize for the delayed response. Can you provide some Room SIDs that have Participants from all the above-mentioned platforms? They will enable us to take a look at our server-side logs.

Thanks,

Manjesh Malavalli
JSDK Team
