### ISSUE TITLE
Programmable video JS:  Full Screen feature

### ISSUE THREAD

**Issue by Ramizkhan313** [twilio/twilio-video.js#554]
Hello Support,
I am using twilio video JS and I'm wondering how can i achieve full screen method for all the browsers different resolutions including mobile browsers screen? do you have some in build functions and setting for the same?

**Comment by harwinder-developer** [comment]
I am a developer not the member of Twilio. Simply make the parent div absolute or fixed and give width and height 100% for full screen. hope it will help you

**Comment by Ramizkhan313** [comment]
Thanks for the answer harwinder. I tried that also but its like we stretched the video not look like a full screen. Any idea?

**Comment by Asif-chohan** [comment]
> I am a developer not the member of Twilio. Simply make the parent div absolute or fixed and give width and height 100% for full screen. hope it will help you

I followed the solution provided above. But in my case, this is only affecting the parent div and the parent div is now on full screen but not the video. The video has a fixed dimension.

**Comment by harwinder-developer** [comment]
> 
> Thanks for the answer harwinder. I tried that also but its like we stretched the video not look like a full screen. Any idea?
> […](#)
> Sent from my iPhone
> On 27-Mar-2019, at 7:34 PM, harwinder-developer ***@***.***> wrote: I am a developer not the member of Twilio. Simply make the parent div absolute or fixed and give width and height 100% for full screen. hope it will help you — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

Hi, Sorry i did not received a notification about your reply , I think you are doing something wrong in the other html part . can i see your html and css about particular div.

**Comment by harwinder-developer** [comment]
> 
> 
> > I am a developer not the member of Twilio. Simply make the parent div absolute or fixed and give width and height 100% for full screen. hope it will help you
> 
> I followed the solution provided above. But in my case, this is only affecting the parent div and the parent div is now on full screen but not the video. The video has a fixed dimension.

I think you are doing something wrong in the other html part . can i see your html and css about particular div. you have to change something in the other divs and css to make it perfect and auto fixed related to screen. As if remote user is using portrait mode then on your screen it will show some space at left and right of your screen due to video ratio.

**Comment by Ramizkhan313** [comment]
yes, its showing the space left and right which I don't want actually then its not full screen other providers offers  full screen without showing left and right space. How can we fix that any idea?

Thanks in adavance

**Comment by claide** [comment]
@manjeshbhargav have you found your solution to this?

**Comment by zunnurainbadar** [comment]
Hi @Ramizkhan313  Did you find any solution for this?

**Comment by RJRahevar** [comment]
hi Support..,

same issue get my product full screen video stretched not look good..

**Comment by Ramizkhan313** [comment]
Hello,
We can’t make it to full screen because of screen aspect ratio but google meet does that I know don’t know how?
Regards,
Ramiz khan

**Comment by AlanGreyjoy** [comment]
Change the actual video track elements css. It's all in html. Make sure the parent divs are also set up correctly.
You can right click on the video and then click inspect to play around with the css and then set it. If you're using vue.js or something similar, you can adjust the css of the video element in realtime.

They also added events to the video track to catch when the width and height changes. Useful for tracking state changes.

This is not a feature they can really do. They can't guess at your css framework, or any parent divs above the video element. They're not wizards.
