### ISSUE TITLE
Missing frameRate in getStats as of 1.15.0

### ISSUE THREAD

**Issue by patricktemple** [twilio/twilio-video.js#555]
Hi,

I have some monitoring of the results of `getStats` on my remote video tracks. Here's a typical output for that video track, before this issue occurred:

```
{
    "trackId": "27bf0A6a6d1B03477BCD436DA4aaDA98",
    "trackSid": "MTe0a643b5acc1fceecf670f0e8dd65433",
    "timestamp": 1551053097979,
    "ssrc": "607888050",
    "packetsLost": 2,
    "codec": "VP8",
    "bytesReceived": 785619,
    "packetsReceived": 858,
    "dimensions": {
      "width": 640,
      "height": 480
    },
    "frameRate": 13
}
```

I recently upgraded from Twilio version `1.14.2` to `1.15.0`, and the `frameRate` field is always null (though still present in the stats result). The real cause seems to be that this update forces an update of `twilio-webrtc` from `2.1.4` to `2.2.0`, which is where the real problem lies. In other words, upgrading just the webrtc library by itself causes the issue.

I've also tried upgrading to `2.0.0-beta5`, but have the same issue. Now here's a stats output:
```
{
    "trackId": "80BA49Fa206EE1E5c7bF2Dd1fAEBb158",
    "trackSid": "MT372dd3105cc6b20dbbc9628f37440dd5",
    "timestamp": 1551053361292,
    "ssrc": "2921563299",
    "packetsLost": 8,
    "codec": "VP8",
    "bytesReceived": 70555,
    "packetsReceived": 78,
    "dimensions": {
      "width": 640,
      "height": 480
    },
    "frameRate": null
}
```

I'm using Chrome  72.0.3626.109 on MacOS 10.13.6.

Minor other issue I discovered in my upgrade: the Typescript definition for `RemoteVideoTrackStats` extends `RemoteTrackStats`. However `RemoteTrackStats` does not extend `TrackStats`, as it probably should. This means that fields like `trackId` are not available on the `RemoteVideoTrackStats`, even though they're clearly in the JS object (as in the snippet above).

Thanks for your help.

**Comment by manjeshbhargav** [comment]
Hi @patricktemple ,

I apologize for the delayed response. Google Chrome has deprecated their legacy stats API and moved to supporting the [WebRTC 1.0 compliant Stats API](https://www.w3.org/TR/webrtc-stats/#dom-rtcvideohandlerstats-framespersecond). But, they are not generating the "framesPerSecond" field in their stats, which we depend on. I will monitor the Chromium bug tracker to see if there is any movement on generating "framesPerSecond" and keep you posted.

Also, thanks for bringing the TypeScript definition file issue to our notice. I will take a look into it.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by patricktemple** [comment]
Thanks for the update. I'm interested in a workaround that would let me upgrade to the latest Twilio JS version (mostly to benefit from your type definitions rather than our own hacked together version from 1.14). Is the underlying `RTCPeerConnection` exposed through the Room, so that I could call the legacy Chrome `getStats` API until they fix this issue? Quickly glancing through your JS codebase, nothing jumped out, but maybe I'm missing something.

**Comment by manjeshbhargav** [comment]
Hi @patricktemple ,

We don't officially expose the RTCPeerConnections to the developer, but you can access them as show here:

```js
const peerConnections = [...room._signaling._peerConnectionManager._peerConnections.values()]
  .map(pcSignaling => pcSignaling._peerConnection);
```

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by Nifled** [comment]
@patricktemple Did you ever find a workaround for this? I just spent a few days dealing with this bug after upgrading `twilio-video` until I saw this lol.
