### ISSUE TITLE
Twilio: Signaling connection disconnected

### ISSUE THREAD

**Issue by sarvesh456** [twilio/twilio-video.js#569]
Could not connect to Twilio: Signaling connection disconnected. when we are use Chrome browser...

**Comment by manjeshbhargav** [comment]
@sarvesh456 ,

Thanks for writing in with your question. It would greatly help us in debugging your issue if you can follow the issue template and provide as much information as possible. Can you share your browser console logs with us?

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by mjamal-tiu** [comment]
I am getting below error in console while I am trying to connect to Room on the Chrome browser. Please let me know how can I resolve or is it error at the twilio-video.js file which I am using from CDN.

WebSocket connection to 'wss://sdkgw.us1.twilio.com/v1/VideoEvents' failed: WebSocket is closed before the connection is established.

**Comment by pixsolution** [comment]
Hello! We are working with Twilio in Laravel where we have implemented a programmable video, and when making the Video call to enter the video room, the camera is not ON and immediately I get these errors: Could not connect to Twilio: Signaling connection disconnected and sip.transport | WebSocket abrupt disconnection. I attached a screen shot of this error [https://ibb.co/0QwFKwL](url)

How can I solve this error?
I have read that we must update the sdk by referring to it by cdn https://media.twiliocdn.com/sdk/js/client/v1.7/twilio.min.js
but referencing it in direct script displays the same error, how can we solve it?

Moreover, we have installed sdk through composer "twilio / sdk": "^ 5.31",

and by cdn referral we have this
<script src = "https://media.twiliocdn.com/sdk/js/common/v0.1/twilio-common.min.js"> </ script>
<script src = "https://media.twiliocdn.com/sdk/js/conversations/v0.13/twilio-conversations.min.js"> </ script>
<script src = "https://cdn.firebase.com/js/client/2.4.0/firebase.js"> </ script>
with which our videochat worked and in previous versions of browsers. It works in chrome versions 72 and below and it doesn´t work in the new Chrome 74 version. In Opera Version: 58.0.3135.132 it works

I will appreciate your help
Regards

**Comment by akvaliya** [comment]
I just found out that using `pace.js` creates this issue. It closes WebSocket.
