### ISSUE TITLE
Participent Video not show

### ISSUE THREAD

**Issue by sarvesh456** [twilio/twilio-video.js#570]
> Joining room 'sanjay'...

> Joined as 'OldSchoolXanderKane'

> Joining: 'BrashKendraNevis'

message display what the issues...
![capture](https://user-images.githubusercontent.com/45789658/54016857-4175dd80-41aa-11e9-812a-7c77f0265776.PNG)

**Comment by manjeshbhargav** [comment]
Hi @sarvesh456 ,

Thanks for writing in with your issue. I was wondering whether the other participant was successful in joining the Room with audio and video? Can you provide a Room SID that we can look at. A Room SID is a string that starts with `RM...` which is a unique identifier that is associated with a Room. It is available as a property called `sid` on the `Room` object.

Thanks,

Manjesh Malavalli
JSDK Team
