### ISSUE TITLE
Errors when disconnecting in beforeunload event

### ISSUE THREAD

**Issue by katranci** [twilio/twilio-video.js#582]
Hey team,

Following your guidelines on disconnecting participants when they navigate to another page, I'm seeing the errors below in the console when I call `room.disconnect()` in beforeunload event handler. Does the presence of errors indicate that disconnect attempt was failed?

![image](https://user-images.githubusercontent.com/61077/54680960-1755e100-4b03-11e9-8a38-2be371f70de0.png)

**Comment by manjeshbhargav** [comment]
@katranci ,

Thanks for writing in with your issue. Did you get "participantDisconnected" events for this Participant on other clients. If so, then the disconnect was successful. These errors look like they are being generated in `webrtc_internals.js`, which is probably bundled with Chrome.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by katranci** [comment]
Thanks @manjeshbhargav. I've just checked this and yes, other participants do receive _participantDisconnected_ event. `webrtc_internals.js` is indeed bundled with Chrome, it is running behind the chrome://webrtc-internals page.
