### ISSUE TITLE
Refresh token

### ISSUE THREAD

**Issue by katranci** [twilio/twilio-video.js#583]
>Note, a reconnection attempt with an expired AccessToken will result in an AccessTokenExpiredError.

Is there a way to refresh the access token and continue the reconnection process?

**Comment by manjeshbhargav** [comment]
Hi @katranci ,

Thanks for your question. The changelog contains our recommendation for making sure the AccessToken doesn't expire:

> Set the Time-To-Live (TTL) of your AccessToken to the maximum allowed session duration, currently 14400 seconds (4 hours). This ensures that when a network loss occurs the client will be able to re-authenticate the reconnection.

If you are concerned that the AccessToken can be re-used by a malicious actor, you can scope the AccessToken to a particular Room:

```js
const AccessToken = require('twilio').jwt.AccessToken;
const VideoGrant = AccessToken.VideoGrant;

const token = new AccessToken(
  'account_sid',
  'api_key',
  'api_secret'
  { ttl: 14400 });

token.identity = 'foo';

token.addGrant(new VideoGrant({
  room: 'my-room'
}));
```

Please let me know if this helps.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by katranci** [comment]
Hi @manjeshbhargav,

Thanks for your reply. My concern is that in the case of a meeting running over 4 hours, if a participant's room enters into _reconnecting_ state, it will fail to reconnect and leave the user in a dead end.

**Comment by innerverse** [comment]
Hi @katranci ,

Currently the longest individual Participant session we support is 4 hours.  After this, the Participant will need to re-join the Room.  At the 4 hour mark, Participants will be disconnected with a 53002 message, possibly followed by a 53106 Room Not Found (if the room is empty and collected), or a 53204 Participant Not Found (if the Participant sends a message that races with the arrival of 53002).

Hope this helps,
Seth

**Comment by katranci** [comment]
Thanks @innerverse, that's informative.
