### ISSUE TITLE
VP8 support on Safari v12.1

### ISSUE THREAD

**Issue by vladimirmoushkov** [twilio/twilio-video.js#584]
Hello,

Knowing that most of the Android devices support only VP8 and iOS based ones just h264 
I believe those are good news for inter browser (/devices) communication we are all waiting on:
[On the Road to WebRTC 1.0, Including VP8](https://webkit.org/blog/8672/on-the-road-to-webrtc-1-0-including-vp8/). In brief it is about [Safari to support VP8 video codec from v12.1, improving compliance with WebRTC standard](https://www.reddit.com/r/apple/comments/b0nwps/safari_to_support_vp8_video_codec_from_v121/).

We could finally have transcode-less, purely browser based communication without wasting CPU (and battery)! Of course it will take the Safari v12.1 to get to the masses but iOS fragmentation usually don't last long - [> 80% of the people use the last version](https://developer.apple.com/support/app-store/) and [50% have used it within month of the release](https://www.phonearena.com/news/iOS-12-adoption-rate-75-percent_id111479).

 I was wondering when we could get support on this in our beloved Twilio Video project?

EDIT: I just saw there is (planned?) release of 2.0.0-beta7 in the [ChangeLog](
https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md) that includes the aforementioned support! This is great! However seems like like no NPM package yet. So my question is still valid - when we could get support?

Regards!

**Comment by aymenn** [comment]
Hey @vladimirmoushkov,

Thank you for getting in touch.
We are also very excited about this! It is planned in the current sprint and it will be available next week.
We will add support in 2.0 beta as well as the 1.17.0 version.

**Comment by katranci** [comment]
@manjeshbhargav Do you have any insights on when Safari v12.1 release is scheduled?

**Comment by manjeshbhargav** [comment]
@katranci @vladimirmoushkov ,

We have released twilio-video.js@2.0.0-beta7 and twilio-video.js@1.17.0 which has support for VP8 simulcast on Safari 12.1+. Any version of twilio-video.js greater than 1.2.1 will support VP8 (but not simulcast) out of the box. Please refer to this [guide](https://www.twilio.com/docs/video/javascript-v2-developing-safari-11#version-compatibility) for more details.

Thanks,

Manjesh Malavalli
JSDK Team
