### ISSUE TITLE
Twilio 2.0.0-beta6 Throwing 20101 and 53000 

### ISSUE THREAD

**Issue by kamesh-a** [twilio/twilio-video.js#589]
Hello @manjeshbhargav, 

First of all thanks for working on enhancing the platform to support changes from browser vendors and fixing disconnection issues. Would like to report few issues which we are facing in recent times.

Before **twilio-2.0.0-beta6**, we got media connection error, but call will still be able to reconnect faster, but after updating to **twilio-2.0.0-beta6** we are getting **Invalid Access Token** and **Signaling Disconnection Error**  taking our users out of the call. We can share our analytics data report to your official mail, if needed in case. 

**Invalid Access Token:** we can see this access token **is VALID for 4+ hours** but still we got this error and we have attached the logs
[log_sample_1](https://connect-feedback-logs.storage.googleapis.com/generallog-cce47c4a-e300-40b7-a191-cce34ecfd387.log)
[log_sample_2](https://connect-feedback-logs.storage.googleapis.com/generallog-ca79ceb7-fd65-4238-98c8-bd2925d35661.log)

**Signaling Disconnection Error** : After reconnecting we got `incoming message` from server to disconnect with 53000 and **web-socket** received it successfully, previous the heart beats also looks fine, so how signaling error raised in this case. [logs for this issue](https://connect-feedback-logs.storage.googleapis.com/generallog-31ff10e5-4ae9-45e8-9d1d-bcc6f2d4539f.log)

```log
2019-03-25 10:23:09.974Z | DEBUG in [TwilioConnection #1: wss://global.vss.twilio.com/signaling]: Incoming: {"type":"heartbeat"}
2019-03-25 10:23:10.704Z | DEBUG in [TwilioConnection #1: wss://global.vss.twilio.com/signaling]: Outgoing: {"type":"heartbeat"}
2019-03-25 10:23:14.570Z | DEBUG in [TwilioConnection #1: wss://global.vss.twilio.com/signaling]: Incoming: {"type":"heartbeat"}
2019-03-25 10:23:15.709Z | DEBUG in [TwilioConnection #1: wss://global.vss.twilio.com/signaling]: Outgoing: {"type":"heartbeat"}
2019-03-25 10:23:19.169Z | DEBUG in [TwilioConnection #1: wss://global.vss.twilio.com/signaling]: Incoming: {"type":"heartbeat"}
2019-03-25 10:23:20.715Z | DEBUG in [TwilioConnection #1: wss://global.vss.twilio.com/signaling]: Outgoing: {"type":"heartbeat"}
2019-03-25 10:23:23.769Z | DEBUG in [TwilioConnection #1: wss://global.vss.twilio.com/signaling]: Incoming: {"type":"heartbeat"}
2019-03-25 10:23:25.733Z | DEBUG in [TwilioConnection #1: wss://global.vss.twilio.com/signaling]: Outgoing: {"type":"heartbeat"}
2019-03-25 10:23:27.097Z | DEBUG in [TwilioConnection #1: wss://global.vss.twilio.com/signaling]: Incoming: {"body":{"version":1,"type":"error","participants":[],"code":53000,"message":"Signaling connection error","subscribe":{"revision":1,"rules":[{"type":"include","all":true}]}},"type":"msg"}
```

**Room Not Found**:  [logs](https://connect-feedback-logs.storage.googleapis.com/generallog-9ed598bd-7bc2-4e87-b526-6585af5418a8.log)

Note: All these errors are throwing **AFTER RECONNECTION** most of the time.

**Comment by manjeshbhargav** [comment]
Hi @kamesh-a ,

Thanks for writing in with your issue. I took a look at the logs for **Invalid Access Token**, and what I noticed was that it took about 20-30 seconds just to re-open a WebSocket connection after a couple of attempts. By the time a handshake message reaches our service, it has determined that the Participant has left the Room. So, it looks like the reconnect requests took too long to reach our service. This might be due to severe network latency issues or cpu overload on the client side. We have an [entry](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md#reconnecting-to-a-room-due-to-network-disruptionhandoff-opt-in) in COMMON_ISSUES.md explaining this behavior. In the near future, we will surface a more appropriate error code.

I see a similar pattern for **Room Not Found**.

Regarding **Signaling Disconnected Error**, it looks like there was a network blip between a couple of our microservices resulting in this error. Do you see this often or was it a one-off case?

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by kamesh-a** [comment]
Hi @manjeshbhargav 

On **March 25** from **15:35 to 15:52 IST** we got almost 15 request which had this sort of **Signaling Disconnected Error** all of them had good heartbeats incoming and outgoing.

After that instance 1 or 2 per/day but those **53000** looks to be valid as they are missing heartbeats consecutive 3 times.

`So, it looks like the reconnect requests took too long to reach our service. This might be due to severe network latency issues or cpu overload on the client side` - Possibilities of CPU load is less cause these rooms were only 4-6 participants and their machines are MID to High range systems, which I have seen the configuration and current runtime load when issue was witnessed, but we are connecting **us1** for **beta** any idea when this will be globally released, we have been waiting for beta release deployed to all other regional servers.

[Room-Not-Found/Invalid-Access-Token](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md#reconnecting-to-a-room-due-to-network-disruptionhandoff-opt-in) any possible measures what should we do in such instance, I am guessing should we opt reconnect-mannually after getting this event but doing network ping to fetch a smallest bit resource/image from our servers? Any idea if you we would be glad to hear.

I would like to request for **subscription API** to reduce CPU load issue which we have been waiting for almost 6months now. Can you please check into this.

**Comment by kamesh-a** [comment]
@manjeshbhargav any update on regional servers and regarding above queries.

**Comment by innerverse** [comment]
Hi @kamesh-a ,

We've pushed a small update to change the error code we return when a reconnect arrives to our servers after the Participant has already timed out.  In all cases now, this should return a 53204, Participant not found.  If this happens, and the Participant wants to rejoin, they can reconnect to the Room (via a new token/connect call).  Currently we allow 3 missed heartbeats, plus a 30-second reconnect window before we transition to a disconnected Participant state.  

Subscription API work is currently underway, and we're targeting Q2.  

We have Media Servers in all global regions today, and if you've opted in to our new BETA signaling stack with the JSDK 2.0b6, you're experiencing global signaling infrastructure as well (I do see you using several regions for signaling already!)

Hope this helps,
Seth
Twilio Video Infrastructure

**Comment by kamesh-a** [comment]
Hello @innerverse @manjeshbhargav ,

> Subscription API work is currently underway, and we're targeting  Q2.

Thanks, please let us know if you can give early api access we will be glad to check them and give our opinion or feedbacks. This is going to help us a lot with bigger audience, we are using previous api which applies only single filter which we couldn't leverage fully because of its restriction.

> We have Media Servers in all global regions today, and if you've opted in to our new BETA signaling stack with the JSDK 2.0b6, you're experiencing global signaling infrastructure as well (I do see you using several regions for signaling already!)

We are able to connect to regional based media servers but just wanted to clarify. Is the Signaling server is global tpp or pointing to `us1` we have attached one of our screen shots.

![Screen Shot 2019-04-02 at 3 10 43 PM](https://user-images.githubusercontent.com/3531949/55392742-8860b400-5559-11e9-804f-7d43c2f4916e.png)

Please let me know your comments on this.

**Comment by innerverse** [comment]
Hi @kamesh-a 

For the new signaling stack, using `global.vss.twilio.com` will route you to the lowest latency regional signaling server automatically.  Media is still selectable via REST API (although we're working on adding other mechanisms to choose media region very soon).

`realm` is internal and is used just for moving between test environments at Twilio.  It should always say `us1` and isn't an indication of any regional signaling nor media servers.

We'll be sure to reach out to you when the new Subscription API is ready for early access.

Seth
Twilio Video Infrastructure

**Comment by kamesh-a** [comment]
Hi @innerverse 

Thank you for the updates, Looking for testing it. Closing this issue
