### ISSUE TITLE
Cannot resolve 'file' or 'directory' ../package 

### ISSUE THREAD

**Issue by av-k** [twilio/twilio-video.js#59]
On start application i catch error. (v.1.0.0-beta4)

`ERROR in ./~/twilio-video/lib/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../package in E:\Projects\eurekly_js\node_modules\twilio-video\lib
 @ ./~/twilio-video/lib/index.js 3:14-35`

and

`ERROR in ./~/twilio-video/lib/client.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../package in E:\Projects\eurekly_js\node_modules\twilio-video\lib
 @ ./~/twilio-video/lib/client.js 18:14-35`

as an option, you can replace:
`var version = require('../package').version;`
on
`var version = require('../package.json').version;`

**Comment by markandrus** [comment]
Hi @av-k,

Thanks for writing in—can you share a little bit more about the environment you are using twilio-video.js with? It looks like Windows. What version of Node are you using? Any special bundling, e.g. with Webpack or Browserify? Any frameworks like Meteor?

We will try out your proposed change. I can't remember if it mis-interacted with Meteor in the past though. We will try it out.

Thanks,
Mark

**Comment by av-k** [comment]
@markandrus, hi, my environmen (bug reproduce on local and production machine):
- react 15.3.0
- webpack 1.13.1
- nodejs (local machine v.4.4.7, production 7.3.0)

**Comment by markandrus** [comment]
Hi @av-k,

We started seeing this issue in Travis CI ourselves. We will land the fix (https://github.com/twilio/twilio-video.js/commit/4994895bf199d3e00894db8a65aeb4916a702562) in the next release.

Thanks,
Mark

**Comment by markandrus** [comment]
Hi @av-k,

This landed in 1.0.0-beta7. Would you mind retesting?

Thank you,
Mark

**Comment by markandrus** [comment]
This also made it into 1.0.0—please re-open the ticket if you still experience the issue.

Thanks,
Mark

**Comment by av-k** [comment]
Hi @markandrus,
Vesrion *1.0.0* - issue fixed.
Thanks.
