### ISSUE TITLE
Feature request: report the running browser's codecs capability

### ISSUE THREAD

**Issue by vladimirmoushkov** [twilio/twilio-video.js#597]
Hello,
We are currently using very complex algorithm to detect browser video codecs capabilities, e.g. is the mobile device running chrome for android capable of h264 video transmission). 
This is a lot of work to maintain and you could guess that it is very unreliable approach.

We hope twilio video package could deliver an API to serve list of the video and audio codecs browser is capable of (by connecting to a test page or something like this).

We use the list of codecs to inform our customers in case of there will be issues with the connection to be conducted. This improves vastly the product use.

Thank very much for  considering this!

**Comment by aymenn** [comment]
Hey @vladimirmoushkov 

Thank you for using our SDK and contacting us regarding your feature request.

I would like to understand the problem you are facing a little better.

What do you mean with "issues with the connection"?
Does this apply to all types of Rooms?
Also, can you also list some scenarios where you are running into this problem?

Thank you again.

**Comment by vladimirmoushkov** [comment]
Let's put a hypothetical situation of our customers using the Twilio
Platform.

One of them is using Chrome for Android, that supports just VP8 video
encoding and another is using Safari for iOS that supports just H264.
If let them use Twilio it will fail to connect them via video as there are
no compatible video codecs. This will bring lots of frustration of the
system. We want to tell them in advance that video communication will fail
in advance, so we can ask one of them to use desktop browser to avoid this
kind of problems.

This applies in our case for peer to peer room but I believe it is valid
for all kind of cases.

Imagine every time a user logins on new browser (/device) it will be
redirected to a Test page, where bunch of tests will be conducted - does
the browser has access to microphone, video camera and what kind of video
codecs are supported. This will "prepare" the system to not attempt
connections that will fail - ie if the logged in user attempts connection
with another user having incompatible video codecs.

We have such as software and it is nicely accepted by our users. The
problem we have is that we "detect" the supported video codecs based on
browser user agent, which rather unreliable. Ideally it will be Twilio API
like twilioClient.getBrowserSupportedCodecs(). This I imagine would perform
actual connection to dummy endpoint to detect what is the browser of
capable on.

Regards,
Vladimir Moushkov
