### ISSUE TITLE
Question About usage

### ISSUE THREAD

**Issue by OrlandoCo** [twilio/twilio-video.js#60]
Hello!

I have few questions about twilio video and I want to know if I can use it as follows:

 8 to 8 video conference.
 1 to many video conference.

Thank you!

**Comment by manjeshbhargav** [comment]
Hi @OrlandoCo ,

You can use it in both scenarios. The only thing to keep in mind is that we have an upper limit of 10 participants per room.

Thanks,

Manjesh Malavalli
