### ISSUE TITLE
Participant who is initiating is able recieve video and audio of other participant but vice versa is not receiving(only preview visible).

### ISSUE THREAD

**Issue by 12MIT0020** [twilio/twilio-video.js#600]
- [ ] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [ ] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ ] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [ ] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

```
function roomJoined(room) {
    console.log(room);
    window.room = activeRoom = room;
  
   
    var previewContainer = angular.element('#local-media');
    console.log(previewContainer);
  

    room.on('participantConnected', function(participant) {
      var previewContainerPat = angular.element('#remote-media');
      console.log(previewContainerPat);
      attachParticipantTracks(participant, previewContainerPat[0]);
    
      participant.on('trackSubscribed', function(track) {
        var previewContainer = angular.element('#remote-media');
        attachTracks([track], previewContainer[0]);
      });
    });
  
    
    room.on('trackRemoved', function(track, participant) {
      detachTracks([track]);
    });
  
    room.on('participantDisconnected', function(participant) {
      detachParticipantTracks(participant);
    });
  
    room.on('disconnected', function() {
      if (previewTracks) {
        previewTracks.forEach(function(track) {
          track.stop();
        });
        previewTracks = null;
      }
     
      room.participants.forEach(detachParticipantTracks);
      activeRoom = null;
    });
  }

function attachTracks(tracks, container) {
    tracks.forEach(function(track) {
      container.appendChild(track.attach());
    });
  }
  
  function attachParticipantTracks(participant, container, isLocal) {
    var tracks = getTracks(participant);
    attachTracks(tracks, container, isLocal);
 }
 
 function getTracks(participant) {
    return Array.from(participant.tracks.values()).filter(function (publication) {
       return publication.track;
    }).map(function (publication) {
       return publication.track;
    });
 }

function  detachParticipantTracks(participant) {
  var tracks = getTracks(participant);
  detachTracks(tracks);
}

function detachTracks(tracks) {
  for (var track of tracks) {
    const htmlElements = track.detach();
    for (var htmlElement of htmlElements) {
       htmlElement.remove();
     }
  }
}
```

**Expected behavior:**

Both participant should recieve video and audio simultanously in sync

**Actual behavior:**

Participant who is initiating is able recieve video and audio of other participant but vice versa is not receiving(only preview visible).

**Software versions:**

 - [ ] Browser(s):chrome
 - [ ] Operating System:Ubuntu
 - [ ] twilio-video.js:2.0.0.beta6
 - [ ] Third-party libraries (e.g., Angular, React, etc.):Angular js

**Comment by manjeshbhargav** [comment]
Hi @12MIT0020 ,

Sorry for the delayed response. I took a look at your code, and the reason why the second Participant does not see any media from the first Participant is because, just after joining the Room, you are not subscribing to tracks from already present Participants. Try adding this to your code:
```js
function roomJoined(room) {
  ...
  room.participants.forEach(function(participant) {
    attachParticipantTracks(participant, previewContainerPat[0]);
    participant.on('trackSubscribed', function(track) {
      attachTracks([track], previewContainer[0]);
    });
  });
  ...
}
```
Also, "trackRemoved" is not supported in 2.x SDK versions. Please use "trackUnsubscribed" instead.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by mding5692** [comment]
Hi, had similar issue, but with twilio-video 1.x SDK, did that fix for you @12MIT0020 

Just asking because hard to recreate for me and thus hard to test if working properly.

**Comment by mding5692** [comment]
@manjeshbhargav 

This is my code, I am using React.js and Refs to attach tracks to video HTML5 elements:

```
startCall = (sessionID, accessToken, localMediaRef, remoteMediaRef) => {

    const trackOptions = {
      audio: true,
      video: { width: 640 },
    }
      
    TwilioVideo.createLocalTracks(trackOptions).then(localTracks => {

      let localVideoTrack = localTracks.filter(track =>
        track.kind == 'video'
      );

      if (localVideoTrack.length == 0) {
        console.error("Unable to grab local video track");
        return;
      }

      localVideoTrack[0].attach(localMediaRef.current)

      // Connects to room using access token
      return TwilioVideo.connect(accessToken, {
        logLevel: 'error',
        name: sessionID,
        tracks: localTracks
      }).then(room => this.roomJoined(room, remoteMediaRef), err => {
        console.error(`Unable to connect to room ${err.message}`);
      });
    });
  }

  roomJoined = (room, remoteMediaRef) => {

    this.activeRoom = room

    const localUser = room.localParticipant

    // Log any Participants already connected to the Room
    room.participants.forEach(participant => {

      participant.tracks.forEach(track => {
        this.groupTracksAndAddTrack(track, remoteMediaRef.current)
      });

      participant.on('trackAdded', track => {
        this.groupTracksAndAddTrack(track, remoteMediaRef.current)
      });
    });

    // When a Participant joins the Room, log the event. Right now testing for remote tracks
    room.on('participantConnected', participant => {
      console.log(`${participant.identity} has joined`);

      participant.tracks.forEach(track => {
        this.groupTracksAndAddTrack(track, remoteMediaRef.current)
      });

      participant.on('trackAdded', track => {
        this.groupTracksAndAddTrack(track, remoteMediaRef.current)
      });

    });

  groupTracksAndAddTrack = (track, videoElement) => {
    track.attach(videoElement);
  }
```

I am using twilio-video, v 1.18.1 and faced similar issues, one of my users were in Copenhagen and I could see and hear her but see could not see or hear me.

**Comment by mding5692** [comment]
@manjeshbhargav  Talked with that user, she was using the Brave browser, however we were able to communicate using Zoom so I think still able to grab video access. Might be different way of grabbing permissions or does Twilio Video also not support Brave.

User was using Brave Browser on MacOS.
