### ISSUE TITLE
Feature request: Minimize the Twilio Video library size footprint

### ISSUE THREAD

**Issue by vladimirmoushkov** [twilio/twilio-video.js#602]
Currently when you add twilio video npm package 2.0.0 to your project, it adds twilio npm package v3.30.0. 
If you run webpack along with [webpack-bundle-analyzer](https://www.npmjs.com/package/webpack-bundle-analyzer) plugin it will report that the final bundle produced contains:
- 719 kb for the Twilio Video library sources
- 448 kb for the Twilio library sources
If parsed, minified and compressed this adds total of 97 kb.

While this does not lot looks significant - it is actually the half of the recommenced size for a web app (200 kb).

My question to the team is - whether there are plans for optimisation of the size footprint or lazy loading some parts of the libraries.

**Comment by manjeshbhargav** [comment]
Hi @vladimirmoushkov ,

Thank you for writing in with your question. I just wanted to get some clarification. By "Twilio library sources", do you mean the `twilio` npm package? If so, this package is mainly for generating AccessTokens, which will not be part of the front-end code anyway (ideally, AccessTokens should be generated by a back-end service). The last time I checked, the minified Twilio Video SDK has a size of around 750kb. Are you having issues with loading a JS file of this size?

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by vladimirmoushkov** [comment]
Speaking here about the npm package, whose sources are included as part of the final web app bundle package.
The sources included with the npm library bundle are 500 kB like side in above.
The Webpack has solid minification, compression and even recognition of non used sources process that reduces those 500 kB to little more than 50 kB.
However this is just the Twilio video. The Twilio lib itself has the same characteristics and this adds 100 kB to the final bundle.

Like said in above this is the half of the recommended maximum for web application bundle.

**Comment by manjeshbhargav** [comment]
Hi @vladimirmoushkov ,

I'm still not getting why you are bundling the `twilio` npm package along with the SDK. This package is for generating AccessTokens and using the Twilio Video REST APIs, which are usually done from a back-end service. You webpack bundle for the web app should not be including this. Please let me know if I'm misunderstanding your situation.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by vladimirmoushkov** [comment]
Yes, the `twilio` npm package is used on the backend. However the package still gets bundled somehow along with twilio-video. I was thinking that is dependancy of the `twilio-video` package. Your question made me to investigate this and indeed it is not direct `twilio` package npm dependancy, but siding packages `@twilio/sip.js` and `@twilio/webrtc`:
>       "twilio-video": {
>          "version": "2.0.0-beta7",
>          "resolved": "https://registry.npmjs.org/twilio-video/-/twilio-video-2.0.0-beta7.tgz",
>          "integrity": "sha512-yW4aCIOohco8Ti1llQLGo1Lps+UgpP9mum4/8ExOGVJQVHuAQoR1nefMKO9mkCBurWQIymrgSgmnjInSYSn2yA==",
>          "requires": {
>             "@twilio/sip.js": "^0.7.7",
>             "@twilio/webrtc": "4.0.0",
>             "ws": "^3.3.1",
>             "xmlhttprequest": "^1.8.0"
>          }

Those generated the following footprint:
<img width="1243" alt="Screenshot 2019-04-09 at 1 55 45" src="https://user-images.githubusercontent.com/21225376/55762188-b454cb80-5a6a-11e9-987d-f0166abb442d.png">

Hopefully my report is understandable, now. Apologies for misleading you earlier.

**Comment by manjeshbhargav** [comment]
Hi @vladimirmoushkov ,

FYI, right now, our new signaling transport which enables reconnection is behind a private ConnectOptions flag `_useTwilioConnection`. Once we make this the default signaling transport, we will remove the `@twilio/sip.js` library altogether. That should reduce the bundle size significantly.

I will close this issue for now, since a future version of the SDK will no longer have the library that you are pointing to. Please let me know if this answers your question.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by vladimirmoushkov** [comment]
Just one last question- when’s is the new SIP transport planned to be released?

**Comment by manjeshbhargav** [comment]
@vladimirmoushkov ,

The new signaling transport was released behind a private ConnectOptions flag in [twilio-video.js@2.0.0-beta6](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md#200-beta6-march-15-2019). See the section related to Network Reconnection. The latest release is 2.0.0-beta7 with Safari 12.1+ VP8 codec and simulcast support.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by vladimirmoushkov** [comment]
I was asking when you are planning to release the new signalling transport
mechanism as default that will lead to lesser library size footprint.
