### ISSUE TITLE
I have faced some bug on iPad and iPhone safari

### ISSUE THREAD

**Issue by Govind13100** [twilio/twilio-video.js#606]
- iPad and iPhone Safari (not desktop Safari), if you change tab, it turns off your camera (screen is black) - and when you go back to video tab, the screen stays black.

**Comment by manjeshbhargav** [comment]
@Govind13100 ,

Please let us know if you are still facing this issue, and if so, in which versions of Safari did you try your test? Also, please share your browser logs. It would be ideal if you can open a new issue, since this one is really old.

Thanks,

Manjesh Malavalli
JSDK Team
