### ISSUE TITLE
on iPhone chrome video is not working

### ISSUE THREAD

**Issue by Govind13100** [twilio/twilio-video.js#607]
i have used lasted tiwlio-video.js i.e 2.0.0-beta7... but still i am not able to use video quickstart app on my iPhone chrome browser and MacOS chrome browser. 

here are some console screenshot if they help

![mac-chrome-not-support-video](https://user-images.githubusercontent.com/26818036/56202850-92a6a600-6061-11e9-82ea-ecea1651720f.png)
![debug](https://user-images.githubusercontent.com/26818036/56202863-99351d80-6061-11e9-953e-96e4de5b18c6.png)
![debug1](https://user-images.githubusercontent.com/26818036/56202876-9f2afe80-6061-11e9-8c75-e0a9dc91ecb7.png)
![debug2](https://user-images.githubusercontent.com/26818036/56202884-a225ef00-6061-11e9-8fe9-8a0b59f26523.png)
![debug3](https://user-images.githubusercontent.com/26818036/56202886-a4884900-6061-11e9-953c-053ee5d8fbe6.png)

Thank you

**Comment by manjeshbhargav** [comment]
Hi @Govind13100 ,

From the logs, it looks like the browser denied permission to use the camera and/or microphone.  Can you make sure that media permissions are granted and try again?

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by mc4rol9** [comment]
Hello, @Govind13100.

Chrome and Firefox can't access webRTC on iOS (IPHONE), it's only supported with Safari >=v.11 - https://www.twilio.com/docs/video/javascript#supported-browsers.

About MacOS, i am using the  tiwlio-video.js 2.0.0-beta9 and it's working perfectly.

Best regards,
Carol.
