### ISSUE TITLE
Many to many room

### ISSUE THREAD

**Issue by OrlandoCo** [twilio/twilio-video.js#61]
Does Twilio use a media server for a many to many conference, so a user just have 1 outgoing connection and n incoming, or just act as signaling and the user ends with n outgoing connections and n incoming connections?

If it doesn´t use a media server, and it going to use it in the future it's going to be for the same price?

**Comment by markandrus** [comment]
Hi @OrlandoCo,

Thanks for writing in. We will have two options: P2P or SFU. In general, SFU is going to be the better option for many-to-many conferences, and will employ the star topology you describe: 1 outgoing and N incoming.

There will be two different price points:

* For P2P it is $0.01 per Participant per hour. Additional charges for Network Traversal Service (TURN) may apply depending on the network may apply (see [here](https://www.twilio.com/stun-turn/pricing) for more).
* For SFU, the pricing model is TBD, but we are leaning towards a bandwidth-based model.

Does that answer your question?

Best,
Mark

**Comment by OrlandoCo** [comment]
Hi @markandrus 

Thanks for your quick response, do you have a roadmap to know when th  SFU it's going to be available for testing, and any clue for the prices per GB?

We are developing a Virtual Classroom, and we want to know what would be the best option for the video conference part.

**Comment by markandrus** [comment]
@OrlandoCo we are aiming for a preview in early April, but pricing is still TBD. I'm going to close this ticket for now, but if you want to chat some more, please reach out to ktoraskar@twilio.com or rbrazier@twilio.com.

Thanks!
Mark
