### ISSUE TITLE
DSCP support

### ISSUE THREAD

**Issue by jamesgraham** [twilio/twilio-video.js#615]
I can't see any documentation on this and haven't checked any logs, but is it possible for the service to mark the packets accordingly?

We are testing this on Meraki kit and found a good reference here: https://documentation.meraki.com/MR/WiFi_Basics_and_Best_Practices/Wireless_QoS_and_Fast_Lane

Your colleagues in Client suggest this in this article https://www.twilio.com/docs/voice/client/best-practices#manage-the-calling-environment

**Comment by manjeshbhargav** [comment]
Hi @jamesgraham ,

Thanks for writing in with your question. Although we don't have a public API to enable DSCP support on Chrome, you can try using one of our experimental ConnectOptions flags which we are using to test different Chrome-specific RTCPeerConnection constraints:

```js
const room = await Twilio.Video.connect(token, {
  chromeSpecificConstraints: {
    optional: [{ googDscp: true }]
  }
});
```

Please let me know if this works for you.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by jamesgraham** [comment]
Thanks @manjeshbhargav ! Do you happen to know which marker it uses for video?

**Comment by manjeshbhargav** [comment]
Hi @jamesgraham ,

I'm not sure off the top of my head. I'll look into it and reach out if I have anything.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by makarandp0** [comment]
Hello @jamesgraham - We recently added a flag to enable dscp support. Please checkout release notes @ https://github.com/twilio/twilio-video.js/releases/tag/2.0.0-beta13. Let us know if it works for your use case.

Thanks,
Makarand
JSDK Team

**Comment by jamesgraham** [comment]
Thanks @makarandp0, we noted and will be deploying to production at the weekend 👍
