### ISSUE TITLE
Web browsers are not showing iOS devices video track

### ISSUE THREAD

**Issue by romil-officetroops** [twilio/twilio-video.js#619]
Room Unique Name: 326436ba-43f0-492f-b81b-bac2997ae515 

Web browsers are not showing iOS devices video track but audio track is working. How can I fix this issue?

twilio-video version 1.15.2

**Comment by manjeshbhargav** [comment]
Hi @romil-officetroops ,

Thanks for writing in with your question. In order to better understand your issue, please provide the following information:

----------



 - [ ] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [ ] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ ] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [ ] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**



```js
// TODO
```

**Expected behavior:**

TODO

**Actual behavior:**



TODO

**Software versions:**

 - [ ] Browser(s):
 - [ ] Operating System:
 - [ ] twilio-video.js:
 - [ ] Third-party libraries (e.g., Angular, React, etc.):

**Comment by romil-officetroops** [comment]
**Steps which I followed:**
1. Created a room using create_room api using video_codes: ['H264', 'VP8'].
2. One participant connected to this created room with connect api of twilio-video.js from chrome.
const { connect, createLocalTracks, createLocalVideoTrack } = require('twilio-video')
createLocalTracks({
    audio: true,
    video: { width: 640 }
  }).then(localTracks => {
    return connect(token, {
      name: roomName,
      tracks: localTracks,
      networkQuality: true,
      preferredVideoCodecs: ['H264', 'VP8']
    })
  })
3. One participant connected to this created room with connect api of twilio-video.js from safari browser on ios.

Now there were 2 participants in that room. For both audio was working. Safari was showing chrome's video but chrome was not showing safari's video. But when I tried to connect to the same room using safari on mac. Then it was working.

twilio-video.js version 1.15.2
Third party library: Vue.js

**Comment by manjeshbhargav** [comment]
Hi @romil-officetroops ,

Thanks for the info. Can you provide all the information specified in the [previous comment](https://github.com/twilio/twilio-video.js/issues/619#issuecomment-489256841)? Also, it would be great if you can:

1. Post the entire code snippet (including how you handle Participant and Track events)
2. Provide some Room SIDs (34 character string starting with `RM`, which you can access using the `sid` property on the Room object) which we can use to look at server side logs?

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by romil-officetroops** [comment]
@manjeshbhargav Room SIDs: 
RM8cb4296f4e4d0c536d125d32095689e7
RMcaf8283d0934dfdf14c3dd76e7637c39
RM9b09e8faa6bab1005879845c0e35a3de
RM5adb906dd7305499234f6be138f53b7c

const { connect, createLocalTracks, createLocalVideoTrack } = require('twilio-video')
createLocalTracks({
  audio: true,
  video: { width: 640 }
}).then(localTracks => {
  return connect(token, {
    name: roomName,
    tracks: localTracks,
    networkQuality: true,
    preferredVideoCodecs: ['H264', 'VP8']
  })
}).then(room => {
  room.participants.forEach(participant => {
    participant.tracks.forEach(publication => {
      if (publication.isSubscribed) {
        const track = publication.track
        document.getElementById('remote-media-div').appendChild(track.attach())
      }
    })
    participant.on('trackSubscribed', track => {
      document.getElementById('remote-media-div').appendChild(track.attach())
    })
  })
  room.on('participantConnected', participant => {
    participant.tracks.forEach(publication => {
      if (publication.isSubscribed) {
        const track = publication.track
        document.getElementById('remote-media-div').appendChild(track.attach())
      }
    })

    participant.on('trackSubscribed', track => {
      document.getElementById('remote-media-div').appendChild(track.attach())
    })
  })
}, error => {
  console.error(`Unable to connect to Room: ${error.message}`)
})

**Comment by romil-officetroops** [comment]
@manjeshbhargav I was creating 2 local video tracks that is why chrome was not showing safari's video track. Now I have removed one instance and it is working as expected.

**Comment by NarHakobyan** [comment]
@romil-officetroops I have the same problem, only ios tracks are not visible in chrome, what was your solution?

**Comment by romil-officetroops** [comment]
@NarHakobyan So before connecting to a room I was calling 'createLocalTracks' function.
**Code Snippet:**
createLocalTracks({
    audio: true,
    video: { width: 640 }
  }

and then I was connecting to a room. After connection again I was calling createLocalVideoTrack function to create local video track and that is resulting into 2 local video track. So after removing createLocalVideoTrack function call, it started working as expected.

**Comment by dsngeu** [comment]
how you guys solved this problem,
I am facing same issue.
in case of iOS to web video calling , the web is not able to display iOS video but audio is working fine. 
and iOS to iOS/android everything working fine.
