### ISSUE TITLE
The composition settings option is not present in Twilio dashboard

### ISSUE THREAD

**Issue by Glory-Victor** [twilio/twilio-video.js#627]
Docs link :: https://www.twilio.com/docs/video/api/external-s3-compositions

https://www.twilio.com/docs/video/tutorials/storing-aws-s3

As mentioned in the above docs link, the external s3 composition can be activated by enabling the enable button present in the settings tab under composition tab by providing our s3 account. 

But the settings options for composition is not been updated yet in our Twilio dashboard.

**Comment by manjeshbhargav** [comment]
Hi @Glory-Victor ,

This is not in the scope of the JavaScript SDK. Please reach out to our [support](https://support.twilio.com/).

Thanks,

Manjesh Malavalli
JSDK Team
