### ISSUE TITLE
CSP section potentially out of date

### ISSUE THREAD

**Issue by hugopeixoto** [twilio/twilio-video.js#630]
We are using twilio and have CSP configured to allow the domains in the README:

```javascript
      "connect-src": [
        // bunch of other stuff
        "https://ecs.us1.twilio.com",
        "wss://endpoint.twilio.com",
        "wss://sdkgw.us1.twilio.com", 
      ]
```

After upgrading to beta9, we started getting this:

`twilioconnection.js:204 Refused to connect to 'wss://global.vss.twilio.com/signaling'`

From a cursory look into the changelog, it seems related to this change:

[beta8...beta9#diff](https://github.com/twilio/twilio-video.js/compare/2.0.0-beta8...2.0.0-beta9#diff-4a482819a8e25734634444e7e16ef2aaL6)

Should this `global.vss.twilio.com` domain be added the README?

**Comment by manjeshbhargav** [comment]
Hi @hugopeixoto ,

Thanks for bringing this to our attention. I have scheduled this work and will reach out to you once its completed.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by manjeshbhargav** [comment]
Hi @hugopeixoto ,

This [pull request](https://github.com/twilio/twilio-video.js/pull/639) updates the domain of the signaling endpoint. I will close this issue once it is merged.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by manjeshbhargav** [comment]
Hi @hugopeixoto ,

I've merged the PR mentioned in my previous comment. I will close this issue now.

Thanks,

Manjesh Malavalli
JSDK Team
