### ISSUE TITLE
How to determine if participant's video or audio track is muted

### ISSUE THREAD

**Issue by swarnimsuman** [twilio/twilio-video.js#636]
I'm using one to one Twilio Audio/Video call, i want to know is there a way i can know if other participant's video track is muted or not. 
Right now it works strangely sometime whole screen goes blank and sometime screen just freezes on the last frame before other participant clicked on mute

**Expected behavior:**
An event triggered from the other participant to notify state of video/audio track

**Actual behavior:**
Currently there is no event and it's difficult to determine the state of video component

**Comment by nageshnkt2007** [comment]
Hey ,
I am facing the same issue, wondering if this issue was resolved ?

**Comment by DipenIprospl** [comment]
Hey
I am also facing same issue Any Solution So multiple participant audio and video mute.

**Comment by hardik-singhal** [comment]
Is anyone find the solution yet. Please update here if anyone succeed in doing this.

**Comment by makarandp0** [comment]
Hello @hardik-singhal, I noticed you created another issue for this. I have addressed this question in https://github.com/twilio/twilio-video.js/issues/969

Please let me know if that does not work.
Thanks,
Makarand
