### ISSUE TITLE
iOS 12.2 Safari on Video Rotation (rotating right) Remote Video Freezes with Group Rooms

### ISSUE THREAD

**Issue by browniefed** [twilio/twilio-video.js#637]
- [ X] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [ X] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [X ] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [X ] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Bug Information**
Rotating the phone to the left lets rotation happen and video doesn't freeze on remote side.

Testing Peer-To-Peer rotating to the right/left works and video doesn't freeze for remote participant.
Testing Group Rooms rotation to right will cause remote participants video to freeze.

When rotating to Portrait or rotating to the left and entering landscape mode video for remote participant returns to normal.

This was with H264, and saw the same issue when testing VP8.

This only occurs on phones with iOS 12.2. I tested on iPhone S, 6s, 7 all running iOS 12 or below and things worked correctly.

Once updating the iPhone 7 to iOS 12.2 I ran into this bug.

The video on the mobile device will continue in landscape mode as normal, only the remote participant (tested on Chrome/Firefox) will have video frozen.

**Other Notes**
We listen for `dimensionsChanged` and log that to console on Remote Participant side. I am not seeing this log coming in when the video enters into a frozen state when the phone is turned to the right landscape mode.

Turning to the left I see the dimensionsChanged event coming in.

**Expected behavior:**
I expect the remove participant video to not freeze when rotating phone to the right and entering in landscape

**Actual behavior:**
Remote participant video will freeze.

**Software versions:**

 - [X] Browser(s): Chrome 74, Firefox 66.0.5, Mobile Safari
 - [X] Operating System: iOS 12.2
 - [X] twilio-video.js: 2.0.0-beta9
 - [X] Third-party libraries (e.g., Angular, React, etc.): React

**Comment by browniefed** [comment]
Looking into this further. Trying to create a simple repro with video-quick-start but having a little trouble doing so.

I will continue to look into any logging/stack traces I can obtain or anything we may be doing incorrectly.

**Comment by browniefed** [comment]
@manjeshbhargav I've added a repro but it's for rotating the phone to the left here.

https://github.com/browniefed/grouproomtest

**Comment by manjeshbhargav** [comment]
Hi @browniefed ,

Thanks for writing in with this issue. I will investigate further and get back to you soon.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by browniefed** [comment]
I realized that the reason it is left in the demo is because it's front facing camera. On our app it's the environment facing camera so turning right causes the freeze.

**Comment by manjeshbhargav** [comment]
Hi @browniefed ,

I've asked our QA team to verify the behavior you have described. I'll update you with our findings when they get back to me.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by manjeshbhargav** [comment]
Hi @browniefed ,

Our QA team was able to reproduce this behavior. We have an internal JIRA ticket, JSDK-2358, tracking this bug. I will keep you posted on further developments.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by ceaglest** [comment]
Hi @browniefed,

After some internal investigation, there seems to be an issue with stripping of CVO (rotation) tags in Safari 12.2. This capability is required in a Group Room, where there is no guarantee that all connected Participants support CVO tags. When CVO tags are stripped, the frames must be physically rotated to compensate.

In a Peer-to-Peer Room, as long as both Participants support CVO tags, there is no need to strip them and the bug does not occur.

I am investigating the WebKit source code (which uses large portions of Chromium WebRTC), to determine where the issue is occurring.

Best,
Chris

**Comment by ceaglest** [comment]
Hi,

There is a WebKit bug ([#201315](https://bugs.webkit.org/show_bug.cgi?id=201315)) that is tracking the issue with CVO tag removal. It is claimed to be resolved as of iOS 13.0 and above. We will re-test JSDK-2358 to make sure.

Thanks,
Chris
