### ISSUE TITLE
Video SDK for React Native

### ISSUE THREAD

**Issue by kskang** [twilio/twilio-video.js#642]
From the #510, I found out that there is RN version Video SDK. We are using React Native so we want to test RN version SDK. Could I get access authority?

I left comment in the #510 issue and sent an email to the support center, but heard nothing back so created a new issue.

Thanks.

**Comment by ycherniavskyi** [comment]
Also interested in RN version of Video SDK.

**Comment by ankushranka** [comment]
Requesting access for the same.

**Comment by JamieCorkhill** [comment]
Also requesting access.

**Comment by rebirthtobi** [comment]
Requesting access for this as needed for a project

**Comment by JamieCorkhill** [comment]
I was told somewhere that this project was abandoned internally by Twilio, @rebirthtobi and @ycherniavskyi and @kskang. I _might_ start working on a TypeScript React Native wrapper around the IOS and Android SDKs. I'll update here if I do.
