### ISSUE TITLE
Pausing outgoing audio/video to remote participants

### ISSUE THREAD

**Issue by carterbryden** [twilio/twilio-video.js#644]
Disabling a track seems to only disable locally. I want to give users the ability to pause/unpause their tracks being sent out to remote participants.

How can I do that? The docs don't mention this at all.

**Comment by manjeshbhargav** [comment]
Hi @carterbryden ,

Thanks for writing in with your question. If you call `localTrack.disable()`, it will also stop sending media to all RemoteParticipants who subscribe to your Tracks. On the other hand, if you are asking for a way to disable somebody else's Track(s), then we do not support that. However, you can achieve that with some application-level logic where you can use DataTracks to communicate to the other RemoteParticipants to call `LocalTrack#disable()` on their side.

I hope this answers your question. If not, please describe more in detail exactly the use-case you're looking for, preferably with code samples.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by carterbryden** [comment]
Thank you, this can be closed. 

In my case it was an issue of there being two sets of local tracks - one set connected to the html elements displaying them, and another unattached set sending to the twilio connection but not displayed. So anyone searching for this in the future, make sure you're disabling and enabling the right local tracks if pausing doesn't seem to work.

In the future it would be very nice if the sdk handles a full stop and resume (unpublish, recreate local tracks, and republish) so that the webcam and microphones can actually stop capturing. Nice but not all that urgent or anything.

**Comment by manjeshbhargav** [comment]
Hi @carterbryden ,

You don't need to create a separate set of LocalTracks for displaying and publishing you can use the same LocalTracks.

Thanks,

Manjesh Malavalli
JSDK Team
