### ISSUE TITLE
Initial connection attempt fails silently

### ISSUE THREAD

**Issue by katranci** [twilio/twilio-video.js#646]
Hey team,

I'm investigating a screenshare problem where a user reported he couldn't see screenshare video. I've checked client-side logs and realised that the user wasn't connected at all. The logs suggest that Twilio tried connecting a few times and then gave up. However, this wasn't conveyed via the SDK in any way so we failed to guide the user accordingly.

![image](https://user-images.githubusercontent.com/61077/58038207-0728a500-7b38-11e9-8ebd-776314cbc217.png)

**Comment by makarandp0** [comment]
Hello @katranci, Thank you for reporting the issue, and posting the corresponding client log lines. In case of such of failure to connect, the promise returned by `Video.connect` API should have rejected. 

```
const Video = require('twilio-video');
Video.connect(data.token, connectOptions).then(roomJoined, function(error) {
  log('Could not connect to Twilio: ' + error.message);
});

```
Can you confirm that your application is handling the rejection of the returned promise? One of the line in the log you posted above indicate that the promise should have been rejected. its coming from here: https://github.com/twilio/twilio-video.js/blob/2a7d19c9fb760c10f8a48dc60e8beff4945b5ecf/lib/connect.js#L260

One easy way to repro such issue would be to disable network connection and try connecting. 
I was not able to repro the issue with the quickstart application - I found  that promise rejection handler was executed. 

Please see if you can get repro and any additional information on repro steps would help further debug this. 

Thanks,
Makarand
JSDK Team

**Comment by katranci** [comment]
Hey @makarandp0, thanks for linking to the relevant section in the codebase, it's been useful to test it. I forgot to mention that we are on v2.0.0-beta6. I've checked the behaviour on video-quickstart-js master branch by clicking on the Join Room button while disconnected. The SDK didn't reject the promise and kept trying to connect.

![image](https://user-images.githubusercontent.com/61077/58189731-b5148a80-7cc3-11e9-81e9-0ae20fd18664.png)

**Comment by makarandp0** [comment]
Hey @katranci,
 
Thank you for writing back. The SDK attempts to reconnect 5 times before giving up. 
https://github.com/twilio/twilio-video.js/blob/30c3ce688d5cd5d0e00b7b83e786a3e759e5dc15/lib/signaling/v2/twilioconnectiontransport.js#L22

From the image you posted above we see that network connection is timing out after ~30 seconds, and it SDK tried to reconnect 4 times. If you waited little more time you should see the connect promise getting rejected after 5 attempts. In this case it should take about ~4 mins before you see the promise getting rejected. Can you please confirm if you see promise rejection after waiting longer? 

But anyways I agree that having to wait for 4 mins before you know that connection isn't happening is not ideal. I will file an internal task to see how we can address this. Can you give me more information about your setup - OS version,  browser version, and how did you disconnect the network? On my machine I see different error (`net::ERR_INTERNET_DISCONNECTED` ), and it fails immediately. I am wondering what is causing `net:ERR_CONNECTION_TIMEOUT` and 30 second wait in your case.

Thanks 
Makarand
JSDK Team

**Comment by katranci** [comment]
Hey @makarandp0,

Here is a fresh case that I believe is related. This one was also occurred on v2.0.0-beta6. Seems like Twilio Video just keeps trying to connect infinitely without rejecting the connect promise. Room SID it is trying to connect to is RMda8274eeeed95bc7fc6fb4603cf977e9.

![image](https://user-images.githubusercontent.com/61077/58546137-a87cbe80-81fc-11e9-855d-d20e5b11c138.png)
![image](https://user-images.githubusercontent.com/61077/58546149-af0b3600-81fc-11e9-9a8a-0f63d675884a.png)
![image](https://user-images.githubusercontent.com/61077/58546158-b2062680-81fc-11e9-8b4f-e0218cc83b1d.png)

**Comment by makarandp0** [comment]
@katranci - Thank you for writing back. In the logs you posted above - I do see a line that indicates that promise was rejected after 1+5 attempts at connecting. 

![rejection](https://user-images.githubusercontent.com/6174737/58593282-4d0ff800-821f-11e9-8456-2fdb6b6af590.png)

Notice the line: 
```
Error while connecting to a Room. Error: Signaling connection error  
```
which is logged in rejection path @ 
https://github.com/twilio/twilio-video.js/blob/2a7d19c9fb760c10f8a48dc60e8beff4945b5ecf/lib/connect.js#L260
 
Do you have any instrumentation that logs when promise is rejected/resolved? Can you add some ? Also if you can you post the code snippet of how you are handling the promise that might help.

**Comment by katranci** [comment]
I don't have a handler for the rejected promise but I will add one. However, we capture unhandled promise rejections in our logger and they normally appear as below, yet, I cannot see such an entry for the sessions I posted earlier in this thread.

![image](https://user-images.githubusercontent.com/61077/58621939-61f19780-82c2-11e9-9c49-f7fed6382483.png)

Is there any chance that firewall-caused connection problems somehow act differently? Because, when I test it by turning off my internet connection then I can see the Unhandled promise rejection in the logs. Do you run tests against firewall behaviours?

**Comment by makarandp0** [comment]
Thank you for writing back @katranci 

I think that explains the issue. For `Video.connect` promise rejection, you would not see  `unhandled promise rejection` because there is a handler attached to the promise - [which just logs](https://github.com/twilio/twilio-video.js/blob/2a7d19c9fb760c10f8a48dc60e8beff4945b5ecf/lib/connect.js#L253). So even without your handler this rejection is not "unhandled"  

But you do need rejection handler in your code to act on the rejection and let user know that connection did not work.

I am still curious about the earlier logs where you were getting `net:ERR_CONNECTION_TIMEOUT` after 30 seconds. Can you tell us how did you disconnect the network that caused these timeout errors. I would like to understand the repro and am wondering if we should tweak our retry logic for such timeouts. 

Thanks
Makarand
JSDK Team

**Comment by ceaglest** [comment]
Hi @katranci,

While we discuss the retry behavior internally, I wanted to follow up with a few thoughts:

> I am still curious about the earlier logs where you were getting net:ERR_CONNECTION_TIMEOUT after 30 seconds. Can you tell us how did you disconnect the network that caused these timeout errors. I would like to understand the repro and am wondering if we should tweak our retry logic for such timeouts.

I second the suggestion from @makarandp0. If its possible to debug the connection attempt in your browser's console it might reveal what stage your request is getting stuck. In the original logs that you posted, the WebSocket was opened and then closed milliseconds later when the first message was sent. In the second set `net::ERR_NAME_NOT_RESOLVED` was raised which indicates that hostname resolution (DNS) failed, so the (TCP) connection attempt never began.

Best,
Chris

**Comment by makarandp0** [comment]
Hello @katranci, Do you have any update on this - Does the issue resolve after you attach rejection handle to Promise returned by `Video.connect` API ? Let us know what you find.

**Comment by katranci** [comment]
Hey @makarandp0, sorry I couldn't get back to this ticket yet. I'll run some tests soon and update you here.
