### ISSUE TITLE
Twilio.Video JS Lib is preventing sleep in Electron Desktop Client in MAC

### ISSUE THREAD

**Issue by kamesh-a** [twilio/twilio-video.js#648]
We are using **Twilio.video JS** in Electron Desktop Client, We are getting reports from our users that Electron app is preventing sleep in **MAC os.** 

```
Operating System: Mac 10.14
Electron Version: 3x, 4x, 5x
Twilio version: 2.0.0-beta5,6,9
```

Spinning up an [electron browser](https://electron.atom.io/releases/), tested with 3x,5x electron

- Open Electron ( Right click and open the `electron.app` as it is not signed )
- `Command+Option+I` ( open inspect element )
- Creating an electron browser window to load webpage removing node-integration snippet below
```javascript
let {BrowserWindow} =  require('electron').remote.require('electron')
let bwHandle = new BrowserWindow({
	webPreferences : {
		nodeIntegration : false,
		devTools: true
	}
})
bwHandle.loadURL('<any-url>');
bwHandle.openDevTools();
```
**default step**: 
- load any webpage in above syntax ( replace `<any-url>` to your `URL of choice` )
- access camera and mic via code ( `navigator.getusermedia` )
- give permission for camera and audio access in mac ( Mac OS will 
popup permission screen once app asks for camera or audio access for first time )

**Case 1: Native API to get audio & video from browsers** :
- Step-1: navigator.getUseMedia to get media streams
```javascript
let constrains = {video:true, audio:true};
// Gets the video and audio in electron
navigator
      .getUserMedia( constrains , streams => window.streams = streams , () => {})
```

If we notice in activity-monitor in Energy **preventing-sleep** option will be saying **yes**

- Step-2: Stopping all tracks inclusive of video & audio
```javascript
streams
	.getTracks()
	.forEach( track =>  track.stop() )
```

Once we stop the tracks, after sometime ( average 5-10 seconds ) **preventing-sleep** option will fallback to **NO** for electron app in **ENERGY** tab of **activity-monitor**  

**Case 2: Using twilio.video js library to create tracks** :
- Step-1: load the contents of script into opened dev console `<script src="//media.twiliocdn.com/sdk/js/video/releases/2.0.0-beta9/twilio-video.min.js"></script>`
- Step-2: create video tracks
```javascript 
let trackPromise =  Twilio.Video.createLocalTracks()
trackPromise
   .then( t => window.tracks = t )
```

If we notice in activity-monitor in Energy **preventing-sleep** option will be saying **yes** ( similar to navigator.getUserMedia )

Step-3: Stop the tracks
```javascript
tracks.forEach( t => t.stop() )
```

NOTE: **preventing-sleep** option will be STAY in **yes** for the lifetime of app.

As Electron apps are used for desktop application users generally don't quit the app, so because of it, application prevents OS from going into energy savings mode.

PS: If we reload `location.reload()` the loaded URL, **preventing-sleep** option will fallback to *NO* without restarting the electron renderer process.

Please do let us know if you have any queries on this.

**Comment by manjeshbhargav** [comment]
Hi @kamesh-a ,

Thanks for writing in with your issue. I was able to reproduce the behavior that you are seeing. At this point its not clear to me why the behavior is different for stopping MediaStreamTracks as opposed to stopping LocalTracks. I've created an internal ticket to investigate this. I'll let you know if I find out anything.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by kamesh-a** [comment]
@manjeshbhargav Thanks 👍

**Comment by kamesh-a** [comment]
Hello @manjeshbhargav 

Any luck on this, please let us know if you need any other info.
