### ISSUE TITLE
Error detaching stream after element removed

### ISSUE THREAD

**Issue by kmahlqvist** [twilio/twilio-video.js#65]
Hi, I'm using angular2 in my application and noticed that when i run  .disconnect() in ngOnDestroy it throws me an error in Media.prototype._selectContainer because the element which I attached the stream to no longer exists.

I can work around this, but wanted to let you know.

**Comment by acunniffe** [comment]
+1 Having the same issue with reactjs.

**Comment by markandrus** [comment]
A small reproduction example—in either Angular or React—would be useful. Alternatively, perhaps it's possible to trigger the issue without either framework by just removing the element, then calling `disconnect`? Will try to carve out some time to address this soon.

**Comment by acunniffe** [comment]
That's definitely the issue. I can confirm that removing it causes the issue.

-AC

On Apr 21, 2017, at 8:11 PM, Mark Roberts <notifications@github.com<mailto:notifications@github.com>> wrote:


A small reproduction example—in either Angular or React—would be useful. Alternatively, perhaps it's possible to trigger the issue without either framework by just removing the element, then calling disconnect? Will try to carve out some time to address this soon.

**Comment by markandrus** [comment]
Hi @kmahlqvist @acunniffe,

Thanks for following up: I just realized the original report refers to `Media.prototype._selectContainer`, an internal method of the Media class. This class was removed in 1.0.0-beta5, and will not be present in the 1.0.0 release. Any chance you can reproduce with the current beta, 1.0.0-beta7? Granted this will take some changes to handle Tracks directly instead of through the Media APIs...

FWIW, I cannot reproduce with the following code:

```js
(async () => {
  const videoTrack = await Twilio.Video.createLocalVideoTrack();
  const div = document.createElement('div');
  document.body.appendChild(div);
  videoTrack.attach(div);
  div.remove();
  videoTrack.detach();
})();
```

Thanks,
Mark

**Comment by kmahlqvist** [comment]
Hi @markandrus, sorry for being a bit absent.

I just tried it on beta5 and was not able to reproduce the error.

So atleast I'm happy. Leaving it open for @acunniffe to confirm.

**Comment by acunniffe** [comment]
Just got a chance to change over and it looks good now. Thanks for looking into this. Been really impressed with the pace of your work here.

On Apr 26, 2017, at 2:36 AM, kmahlqvist <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @markandrus<https://github.com/markandrus>, sorry for being a bit absent.

I just tried it on beta5 and was not able to reproduce the error.

So atleast I'm happy. Leaving it open for @acunniffe<https://github.com/acunniffe> to confirm.

**Comment by markandrus** [comment]
Thanks, y'all!
