### ISSUE TITLE
No option to use custom logger with Twilio

### ISSUE THREAD

**Issue by Poky85** [twilio/twilio-video.js#650]
Currently there is no option to use custom logger for Twilio logs. So capturing issues on user's side for debugging purpose is tricky.

**Expected behavior:**

Twilio should provide option to pass custom `Logger` object implementation. So we can log using 3rd party tool like Bunyan (https://github.com/philmander/browser-bunyan)

**Actual behavior:**

Overiding internal logger not possible.

**Software versions:**

 - twilio-video.js: 2.0.0-beta9
 - Browser(s): n/a
 - Operating System: n/a

**Comment by makarandp0** [comment]
Thank you for the suggestion @Poky85 - Sounds like a good idea to me. I will file an internal issue to to research more into this idea. 

Thanks,
Makarand
JSDK Team.

**Comment by rotvulpix** [comment]
Any news on this?

**Comment by thenorthstarblues** [comment]
@makarandp0 Are there any updates about when this feature might be released? We regularly reach out to Twilio Support for assistance with room issues and they almost always request the SDK logs...however we currently have no way to capture them. This is really affecting our experience with the SDK...can you provide any update?

**Comment by makarandp0** [comment]
Hello @thenorthstarblues, Thanks for the question @thenorthstarblues - We are actively working on this feature, and expect to release within a week or so. You can see [this link](https://github.com/twilio/twilio-video.js/blob/feature_connect_event/CHANGELOG.md#2100-in-progress) to see current direction its headed. If you are willing to try out this release candidate, let me know and we can share some details.

**Comment by thenorthstarblues** [comment]
@makarandp0 That's great news, thank you for the update! I'm interested in trying out the RC.

**Comment by makarandp0** [comment]
@thenorthstarblues, @rotvulpix, @Poky85  we have now released the version that allows you to intercept the logged message. Please check it out @ https://github.com/twilio/twilio-video.js/releases/tag/2.10.0

**Comment by thenorthstarblues** [comment]
Thank you @makarandp0!

**Comment by rotvulpix** [comment]
Thanks a lot! This is outstanding!

**Comment by Poky85** [comment]
Thank you, works like a charm!
