### ISSUE TITLE
trackAdded event is not fired after Media.addStream()

### ISSUE THREAD

**Issue by fredsmoo** [twilio/twilio-video.js#67]
I am trying to add a screen sharing mediaStream on an existing participant who is already sharing an audio and video track (webcam/mic). Adding a stream with addStream() works well (I am using a custom Chrome extension for domain whitelisting) and I can attach the stream to the DOM and display it on the local participant (participant A).

The problem is that the "trackAdded" event never fires on the remote participant (participant B). I tried listening on the participant's media and the room with no luck. Also when I refresh the page of participant B and reconnect only audio and video streams are listed on the participant A's media. 

Here is the code:

```
const participants = {};
// .. some authentication code here
const videoClient = new Twilio.Video.Client(token);
videoClient.connect({ to: ROOM_NAME }).then(onRoomJoined);
const localMedia  = new Twilio.Video.LocalMedia();

// sharing webcam
Twilio.Video.getUserMedia().then(mediaStream => {
    localMedia.addStream(mediaStream);
    localMedia.attach('#local-media');
});

// called by the Chrome extension after user presses a "share screen" button
const publishScreen = streamId => {
  const constraints = {
    video: {
      mandatory: {
        chromeMediaSource: 'desktop',
        chromeMediaSourceId: streamId,
        maxWidth: window.screen.width,
        maxHeight: window.screen.height
      }
    }
  };
  Twilio.Video.getUserMedia(constraints).then(mediaStream => {
    localMedia.addStream(mediaStream);
    localMedia.attach('#local-media');
  });
};

const attachRemoteStream = participant => {
  const element = participant.media.attach();

  element.dataset.pid = participant.identity;
  elmRemoteMedia.appendChild(element);
};

const onRoomJoined = room => {
  room.participants.forEach(participant => {
    participant.media.on('trackAdded', track=> {
      console.log('track added', track);
    });
    attachRemoteStream(participant);
    participants[participant.identity] = participant;
  });

  room.on('participantConnected', participant => {
    participant.media.on('trackAdded', track => {
      console.log('track added', track);
    });
    attachRemoteStream(participant);
    participants[participant.identity] = participant;
  });

  room.on('participantDisconnected', participant => {
    detachRemoteStream(participant);
    delete participants[participant.identity];
  });

  room.on('disconnected', () => {
    room.localParticipant.media.detach();
    room.participants.forEach(
      participant => participant.media.detach()
    );
  });

  room.on('trackAdded', track => {
    console.log('track added', track);
  });
};
```

**Comment by fredsmoo** [comment]
I am using 1.0.0-beta4.

**Comment by fredsmoo** [comment]
Also when I log my localMedia after attaching the screen sharing stream I can see all tracks and two mediaStreams.

![screen shot 2017-03-14 at 10 35 07](https://cloud.githubusercontent.com/assets/813577/23894353/0a24b3d0-08a2-11e7-8154-c828f5ff6844.png)

**Comment by fredsmoo** [comment]
It's worth mentioning that if I reconnect with the same localMedia using `client.connect({ to: ROOM_NAME, localMedia: localMedia });` the user with all tracks successfully appears on the remote end. But I obviously end up with a duplicate user. Dropping the old connection is not an option as we are already postprocessing the existing webcam streams.

**Comment by markandrus** [comment]
Hi @fredsmoo,

If this is indeed your code, then the issue appears to be that you are constructing a LocalMedia instance unrelated to the LocalMedia instance actually in use on the Room. In the following lines,

```js
videoClient.connect({ to: ROOM_NAME }).then(onRoomJoined);
const localMedia  = new Twilio.Video.LocalMedia();
```

You connect to a Room without specifying LocalMedia. By default, twilio-video.js is then going to automatically acquire LocalMedia for you (containing one LocalAudioTrack and one LocalVideoTrack). This LocalMedia instance will be distinct from the instance you construct in the subsequent line. You should be able to check with the following:

```js
room.localParticipant.media === localMedia
// => false
```

Instead, you can either access the automatically-acquired LocalMedia instance from the LocalParticipant, e.g.

```js
const onRoomJoined = room => {
  const localMedia = room.localParticipant.media;
  // ...
};
```

Or you can pass in LocalMedia yourself:

```js
Twilio.Video.LocalMedia.getLocalMedia({ audio: true, video: false }).then(localMedia => {
  return videoClient.connect({ to: ROOM_NAME, localMedia: localMedia });
}).then(onRoomJoined);
```

Once you have the correct LocalMedia instance, you should be able to confirm that

```js
room.localParticipant.media === localMedia
// => true
```

**Comment by markandrus** [comment]
@fredsmoo I am going to close this issue due to inactivity, but if you still have questions, please feel free to reopen this or another issue.

Thanks,
Mark

**Comment by fredsmoo** [comment]
Thanks for your help @markandrus. I didn't have a chance to test it yet, but will surely get back to it in the next couple of months.
