### ISSUE TITLE
Twilio dont turn off builtin Bose QC 35 microphone

### ISSUE THREAD

**Issue by kosaa** [twilio/twilio-video.js#677]
I integrate my application with Twilio and after switching between available microphones microphone in my headphones (Bose QC 35 II) isnt turned OFF and is still active.

Now I am using OpenTok library and there is no problem with these headphones

code what I use to select active track:
```
Twilio.createLocalAudioTrack({
	deviceId: { exact: DEVICE_ID }
}).then(localAudioTrack => {
	const tracks = Array.from(localParticipant.audioTracks.values());

	tracks.forEach(v => {
		v.track.disable();
		localParticipant.unpublishTrack(v.track);
	});

	localParticipant.publishTrack(localAudioTrack);
});
```

**Steps to reproduce:**
- select computer builtin microphone
- select headphones microphone
- turn back to computer builtin microphone

**Expected behavior:**

microphone from Bose QC will be disabled

**Actual behavior:**

microphone from Bose QC doesnt publish audio to the room, but is still active localy and I have two microphones active

**Software versions:**

 - [x] Browser(s): Chrome 75
 - [x] Operating System: MacOs 10.14.5
 - [x] twilio-video.js: ^2.0.0-beta11
 - [x] Third-party libraries (e.g., Angular, React, etc.): angular 7

**Comment by kosaa** [comment]
I found the solution: after calling disable() on the track we need to call stop().

I think it isn't good behaviour because when I call disable I expected that disable method close all things with this track and it can be deleted from the memory.

**Comment by manjeshbhargav** [comment]
Hi @kosaa ,

Thank you for writing in with your issue and your feedback about stopping the Track. The reason we don't completely stop the input device when you call `disable()` is that you may want to `enable()` the Track later. That is why we have a separate method called `stop()` which releases the input device from the Track. We have an [example](https://github.com/twilio/video-quickstart-js/blob/master/examples/mediadevices/src/helpers.js#L25) in our Quick Start project that shows you how you can switch between different tracks once you are in the Room. I hope this makes things clearer for you.

Thanks,

Manjesh Malavalli
JSDK Team
