### ISSUE TITLE
Question: Different users connected to Twilio via different region's signaling server, for the same room. What will be the impact?

### ISSUE THREAD

**Issue by kumail-raza** [twilio/twilio-video.js#684]
Hi,

Referring to new feature in [twilio-video.js@2.0.0-beta11](https://github.com/twilio/twilio-video.js/releases/tag/2.0.0-beta11), that one can explicitly define region using the following option, while connecting to Twilio

```js
const { connect } = require('twilio-video');
const room = await connect(token, {
  region: 'de1'
});
```

May be its very foolish question to ask, but still I am asking this, what will be the overall impact, if user connects from different regions' server to the same room? Both while peer-to-peer and group case.

**Comment by makarandp0** [comment]
Thank you for question @smkrn110, 

This newly added `region` option lets you chose the signaling region gateway that will be used for connecting to the room. Room service is hosted in US1, but Regional signaling are gateways in each region, that send the signaling traffic over XRP (private amazon network link) from the remote regions back to US1.

Even when two clients use different region, they should both see lower latencies, as they will use public network only to connect upto region, and private network from the client region to US1.
