### ISSUE TITLE
App crashes on joining room on button click in 2.0.0(beta)

### ISSUE THREAD

**Issue by ciosynergy** [twilio/twilio-video.js#687]
Hi i am using the 2.0.0(beta) version. 
Where i am facing issue as my app crashes on joining room. 

Can you please help me with the debug procedure ? 

Its urgent please help me. 

 - [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

```js
// TODO
```

**Expected behavior:**

TODO

**Actual behavior:**

TODO

**Software versions:**

 - [x] Browser(s):
 - [x] Operating System:
 - [x] twilio-video.js:
 - [x] Third-party libraries (e.g., Angular, React, etc.):

**Comment by makarandp0** [comment]
@ciosynergy, thank you for your question, Can you provide more details on the crash you are seeing, Any output from the console logs, Stack trace for the crash and code sample to reproduce the crash would be useful. 

Thanks,
Makarand 
JSDK Team
