### ISSUE TITLE
Listener(trackDimensionsChanged) is not working in chrome.

### ISSUE THREAD

**Issue by EnioAbrantes** [twilio/twilio-video.js#691]
I have verified that the issue occurs with the twilio-video.js("^1.18.2") and chrome 75, the listener trackDimensionsChanged doesn't work on chrome.

**Expected behavior:**

Work well as firefox and safari.

**Actual behavior:**

The listener is not listening in chrome.

**Software versions:**

Browser(s): Google Chrome 75.0.3770.142
Operating System: Windows 10 Pro
twilio-video.js: "^1.18.2"
Third-party libraries (e.g., Angular, React, etc.): React

**Comment by manjeshbhargav** [comment]
Hi @EnioAbrantes ,

Thanks for writing in with your issue. Can you enable verbose console logging by adding `logLevel: 'debug'` to ConnectOptions and share the logs? Also, it would be great if you can share a code snippet that demonstrates how you are listening to the event.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by EnioAbrantes** [comment]
sure @manjeshbhargav 

`| sip.transport | received WebSocket text message:

INFO sip:ab4otenp@127.0.0.1:44604;transport=wss;ob SIP/2.0
CSeq: 8 INFO
From: <sip:orchestrator@endpoint.twilio.com>;tag=05696476_6772d868_6dd22f55-5979-4473-850d-48b666fd6de4
To: <sip:72eec426-cfe7-45c2-aedf-bfc948b0b622@endpoint.twilio.com>;tag=cbfvmmgogn
Call-ID: 69t7pfdlr45vooggljqv
Max-Forwards: 69
Via: SIP/2.0/WSS 172.18.40.171:443;branch=z9hG4bK6dd22f55-5979-4473-850d-48b666fd6de4_6772d868_291-7753004753726292005
Content-Type: application/room-signaling+json
Recv-Info: room-signaling
Info-Package: room-signaling
Supported: room-signaling
User-Agent: Twilio Gateway
X-Twilio-CallSid: CA9a0508d7fe64d17746478bffcdd01377
X-Twilio-LegInfo: external
X-Twilio-TlsVerify: true
Content-Length: 1045

{"version":2,"type":"update","sid":"RMdd0f49053249b7d56f252c814e721376","name":"RMdd0f49053249b7d56f252c814e721376","participant":{"sid":"PA2d82882652ccc122f40c3c5e4695d596","identity":"customer_5d3065d20e032d4edd89eba0","tracks":[{"kind":"audio","priority":"medium","id":"a2bd9416-bd43-4d70-b057-eb79004fb357","enabled":false,"sid":"MTc867c95fe96d3b07613b3393b507a73d","name":"a2bd9416-bd43-4d70-b057-eb79004fb357","state":"ready"}],"revision":3,"state":"connected"},"participants":[],"recording":{"enabled":false,"revision":1},"subscribe":{"revision":1,"rules":[{"type":"include","all":true}]},"subscribed":{"revision":2,"tracks":[{"id":"D306edf11a45aC6eaDc52CAfAFe5dEbb","sid":"MT0b62d77e1b1eb65454a474d0103bb352"},{"id":"dEf2D3Fa2f25AC513EABFe6dAB4B48FA","sid":"MTe309983fa49a6d0cafa5cad67f00be50"}]},"published":{"revision":3,"tracks":[{"kind":"audio","priority":"medium","id":"a2bd9416-bd43-4d70-b057-eb79004fb357","enabled":false,"sid":"MTc867c95fe96d3b07613b3393b507a73d","name":"a2bd9416-bd43-4d70-b057-eb79004fb357","state":"ready"}]}}`


I can't share the code, but is something like [this](https://jsfiddle.net/EnioAbrantes/1r45w3dv/3/)
