### ISSUE TITLE
Agora.io's Performance Test

### ISSUE THREAD

**Issue by katranci** [twilio/twilio-video.js#697]
Hey team,

Just come across Agora's performance test in WebRTC weekly newsletter. In the short video below you can see Twilio comes last when dealing with packet loss. I wanted to ask what is your take on it and what your plans are to improve the performance?

https://www.youtube.com/watch?v=PAK5Pw8pnsc&feature=youtu.be

Many thanks

**Comment by anna-vasilko** [comment]
Hi @katranci,
Thanks for your question. Unfortunately our company policy is to not comment on other companies' marketing materials. We are confident in the performance of our Video product and would be happy to work with you on testing out its performance in low-bandwidth conditions.
