### ISSUE TITLE
Detect lose connection of remote participation

### ISSUE THREAD

**Issue by vinhp1292** [twilio/twilio-video.js#701]
Hey team,
I'm implementing a video call between web user and tablet (ios) user

When tablet user turn WI-FI off, the room event `participantDisconnected` is triggered too late (60s)

Do you have a way to trigger it immediately?
I really appreciate if you can help.
>
> ```js
> room.on("participantDisconnected", (participant)=> {
>   console.log(participant)
>    this.log("Participant '" + participant.identity + "' left the room");
>    this.participantDisconnected(participant)
> });
> ```
> 

Browser(s): Chrome 75
Operating System: macOS Mojave
twilio-video.js: 2.0.0-beta12
React

**Comment by spencersteiner** [comment]
@vinhp1292 Have you tried using the `beforeunload` event? Something like this example from the documentation:

```javascript
window.addEventListener('beforeunload', () => {
  room.disconnect();
});
```

The `beforeunload` event is fired when the page is reloaded or closed completely, when it unloads its resources. This will cause the disconnect to trigger instantly. There's also a `reconnecting` state (https://www.twilio.com/docs/video/reconnection-states-and-events) that you can use if you want to disconnect the user if they're having issues and it's trying to reconnect.

**Comment by mding5692** [comment]
The reconnecting state usually has to wait for wifi to come back to trigger, at least thats how it went for me, so I just detect if user is offline and then reconnect when user is online or at least when reconnecting has failed.       

window.onoffline = event => {
   // Indicate in some kind of object tracking state that user has went offline
   this.previouslyWentOffline = true;
}

window.ononline = event => {
   if (this.previouslyWentOffline) {
     // Use the twilio video's connect(...) method
  }
}
