### ISSUE TITLE
Firefox does not ask for camera permissions in android

### ISSUE THREAD

**Issue by jgpavez** [twilio/twilio-video.js#710]
Hi there, 

I'm having problems with twilio-video.js in firefox. The problem is that Twilio video can't connect the camera on firefox + Android.

**Code to reproduce the issue:**

```
    twilio.createLocalVideoTrack()
      .then(track => {
        console.log("Video accepted");
        self.setState({ video_accepted: true });
      });
    console.log('After creating local video track')
```
**Expected behavior:**
Firefox should ask the user for video permissions.

**Actual behavior:**

The following exception is thrown and firefox does not ask for permissions:
```
WARN in [createLocalTracks #1]: Call to getUserMedia failed: 
MediaStreamError { name: "NotFoundError", message: "The object can not be found here.", constraint: "", stack: "" }
```
The error is thrown in line 129 of file: `createlocaltracks.js`

**Software versions:**

 - [Firefox 68.0] Browser(s):
 - [Android 9.0] Operating System:
 - [twilio-video@2.0.0-beta12 ] twilio-video.js:
 - [React] Third-party libraries (e.g., Angular, React, etc.):

Thanks!.

**Comment by manjeshbhargav** [comment]
Hi @jgpavez ,

Thanks for writing in with your issue. I just tried accessing the camera on Firefox 68 on my Pixel 2 phone and it worked without a hitch. `NotFoundError` implies that Firefox was not able to find a camera on your phone that satisfies the default video constraints. Mozilla has a [getUserMedia test page(https://mozilla.github.io/webrtc-landing/gum_test.html). Can you go to this page and see if the camera works? If it doesn't then it means Firefox is not recognizing your camera. Maybe you can try re-installing Firefox to see if that fixes it.

Please let me know what you find.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by jgpavez** [comment]
Hi Manjesh,

Thank you for your quick reply!. you were right, it was a firefox configuration problem. Android camera permissions for firefox were disabled. 

Thanks!.
Best regards.
