### ISSUE TITLE
DTLS handshake failed on Edge client

### ISSUE THREAD

**Issue by 35d** [twilio/twilio-video.js#715]
Hi folks,

We made a software product using Twilio SDK. It works correctly on Chrome, Safari and other browsers, but not on Edge and the following error occurs:

`ORTC18615: ORTC RTCDtlsTransport: DTLS ハンドシェイクが失敗しました。hr=c004e00f。 `

- Is there any workaround for this error?
- Do you have a track record of using Edge with adapter.js?

Please give me some advice.

**Software versions:**

 - [x] Browser(s): Edge 44.18362.267.0 / EdgeHTML 18.18362
 - [x] Operating System: Windows 10
 - [x] twilio-video.js: 1.18.2
 - [x] Third-party libraries (e.g., Angular, React, etc.):
  - webrtc-adapter: 7.2.9,

Best, 
35d

**Comment by manjeshbhargav** [comment]
HI @35d ,

Thanks for writing in with your issue. As of now, we do not support the Edge browser. We haven't yet decided when we want to work on Edge support, but this will be one of our focus points early next year.

Thanks,

Manjesh Malavalli
JSDK Team
