### ISSUE TITLE
Refresh token option

### ISSUE THREAD

**Issue by okland** [twilio/twilio-video.js#73]
Looking for an option to refresh token for already connected room, Is there anyway to do it ?

**Comment by markandrus** [comment]
Hi @okland,

What are you trying to achieve via a token refresh while participating in the Room?

Mark

**Comment by okland** [comment]
I open a room for long time, and the accessToken if i understand right is valid for only an hour.
So if new people join the already open room i don't get them.
You can try it and see the use case - 
http://bit.ly/WorkPartyAlpha010
A mac only app.

Use activation code TwXlio

**Comment by rfbrazier** [comment]
Hi @okland, a few comments:

1. Expiry on Access Tokens is configurable up to 24hrs. You can set it by passing an integer value reflecting the desired expiry time in seconds into the Access Token constructor. If you let me know what back-end language you're using, we can provide a code snippet.
2. If you're connect to a Room and the Access Token expires, everything should continue working as expected. Events will be raised as Participants connect/disconnect and add and remove Tracks, media will flow, etc. You will of course not be able to use the expired Access Token to connect to a new Room, but expiry should not affect an active Room connection.
3. Either way, we're going to test with the sample app you provided and make sure nothing strange is going on. More info soon.

Thanks for using Twilio!

**Comment by okland** [comment]
Hi @rfbrazier,
Thanks for the reply :)
1. I'm using node.js at the back-end and would be happy to get a sample snippet.
2. Great to know.
3. Waiting to hear your voice in the app - My co-founder username in the app is "hlandao" you can check with him as well.

Thanks !
