### ISSUE TITLE
Cannot switch camera on android device

### ISSUE THREAD

**Issue by dranzi666** [twilio/twilio-video.js#730]
I cannot change camera on android devices (front/back), it working fine with pc devices (windows / mac).
I found this solution https://github.com/twilio/twilio-video.js/issues/284 and I call ```stop``` on ```localVideoTrack``` before call ```createLocalVideoTrack``` but it does not work.

**My code:**

```js

TwilioVideoCall.detachTracks = function (tracks, type) {
    tracks.forEach(function (track) {

        if (type == undefined || (type != undefined && type == track.kind)) {
        
            track.stop();
            track.detach().forEach(function (element) {
                element.remove();
            });
        }

    });
};

  let selectedVideo = $('select[name="videoInput"]').val();

	if (selectedVideo !== '') {
		const tracks = Array.from(TwilioVideoCall.localParticipant.tracks.values()).map(publication => publication.track);

		TwilioVideoCall.detachTracks(tracks);
		TwilioVideoCall.localParticipant.unpublishTracks(tracks);

		createLocalVideoTrack({
			deviceId: {exact: selectedVideo}
		}).then(function (localVideoTrack) {
			console.log(localVideoTrack);

			const tracks = Array.from(TwilioVideoCall.localParticipant.tracks.values()).map(publication => publication.track);
			
			TwilioVideoCall.unpublishFiltered(tracks, 'video');

			TwilioVideoCall.detachTracks(tracks, 'video');

			TwilioVideoCall.localParticipant.publishTrack(localVideoTrack);


			$('#my_video_wrapper').addClass('twilio-video-preview').html(localVideoTrack.attach());
		}).catch(error => {
				console.error(error);
			});
	}
```

**Error:**

```
10:48:18.169 log.js:138 2019-08-28 08:48:18.169Z | WARN in [createLocalTracks #3]: Call to getUserMedia failed: DOMException
log @ log.js:138
warn @ log.js:199
(anonymous) @ createlocaltracks.js:120
Promise.then (async)
createLocalTracks @ createlocaltracks.js:111
createLocalTrack @ createlocaltrack.js:27
createLocalVideoTrack @ createlocaltrack.js:87
(anonymous) @ video_test.js:149
dispatch @ jquery.js:5183
elemData.handle @ jquery.js:4991

10:48:18.171 video_test.js:165 DOMException
(anonymous) @ video_test.js:165
Promise.catch (async)
(anonymous) @ video_test.js:149
dispatch @ jquery.js:5183
elemData.handle @ jquery.js:4991
```

**Software versions:**

 - [ ] Browser(s): Chrome 76.0.3809.132
 - [ ] Operating System: Android 9 - SM-G950F
 - [ ] twilio-video.js: v2.0.0-beta12
 - [ ] Third-party libraries (e.g., Angular, React, etc.): Jquery

**Comment by manjeshbhargav** [comment]
Hi @dranzi666,

Thanks for writing in with your question. Did you manage to get access to the camera the first time you created a LocalVideoTrack? If not, then Chrome may not yet have the permission to access your camera. Please let me know.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by dranzi666** [comment]
At the first start of the video, it asks for permission to access the camera. The fork works with the front camera fired. The problem described above occurs when attempting to replace the camera during an ongoing connection

**Comment by manjeshbhargav** [comment]
Hi @dranzi666 ,

Is it possible for you to run the "media devices" example from the [Video JS QuickStart](https://github.com/twilio/video-quickstart-js/tree/master) on your mobile android browser? Please test and see whether switching the camera after joining the Room works.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by dranzi666** [comment]
Yes it possible http://localhost:3000/mediadevices/ first time i can start front or back camera but also i cannot change device after fired it

**Comment by dranzi666** [comment]
Everything is OK, i didn't stop local camera preview...
