### ISSUE TITLE
[question] How can we create a room for future events?

### ISSUE THREAD

**Issue by syang** [twilio/twilio-video.js#732]
I am building an application that allow the user to create a video chat room for a future event. (Imagine a link as a future handle, as Google Hangout provided; or imagine a webinar link but not from zoom, but instead from my Twilio app)

Is twilio-video.js able to do that?

**Comment by manjeshbhargav** [comment]
Hi @syang ,

Thanks for writing in with your question. There are two types of video Rooms:

 - Ad-hoc room: This Room is created when the first Participant joins the Room and is torn down about a minute after the last Participant leaves.
 - REST room: This Room is created using [Programmable Video REST API](https://www.twilio.com/docs/video/api), and is torn down using another REST API call.

In either case, you can create an invite url with the Room name, and then later use that Room name while connecting to a Twilio Room.

Please let me know if this works for you.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by smkrn110** [comment]
@manjeshbhargav 

the second REST room we are doing in our case, my question as you mentioned above Ad-hoc Room is torn down about a minute after the Participant leaves, what will be the case for REST room?

**Comment by manjeshbhargav** [comment]
@smkrn110 

As I mentioned in the above comment, you can tear down a REST room by calling another REST API. Please take a look at the documentation mentioned in the above comment for how to do it.
