### ISSUE TITLE
errors and inconsistent state during frequent room switching on a single LocalTrack

### ISSUE THREAD

**Issue by shrugs** [twilio/twilio-video.js#744]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

Sorry this is mostly pseudo-code, but I figured a general idea would be a good first step and if necessary I can put the work into building an isolated codesandbox. The actual project is open source at https://github.com/XLNT/dot.gallery/tree/feat/audio

I have a react hook like below (some unrelated code removed for clarity, but see the source files for full info).

**code at** 👉 https://github.com/XLNT/dot.gallery/blob/feat%2Faudio/packages/gallery/src/hook/useTwilioRoom.ts

**Expected behavior:**

I can switch between rooms at any speed and twilio-video will gracefully handle interruptions and maintain consistency.

**Actual behavior:**

twilio-video throws a few errors about websocket requests being interrupted and new room joins fail to behave in a consistent way. Additionally, I'm also getting EventEmitter errors about oversubscribing to the localtrackpublicaton that represents my local tracks — am I tearing those publications down correctly?

```
Firefox can’t establish a connection to the server at wss://sdkgw.us1.twilio.com/v1/VideoEvents. src.f69400ca.js:85006:18
2019-09-13 17:46:34.075Z | DEBUG in [TwilioConnection #18: wss://global.vss.twilio.com/signaling]: WebSocket opened: 
WebSocket { url: "wss://global.vss.twilio.com/signaling", readyState: 1, bufferedAmount: 0, onopen: null, onerror: null, onclose: null, extensions: "permessage-deflate", protocol: "", onmessage: null, binaryType: "blob" }
src.f69400ca.js:63853:23
2019-09-13 17:46:34.076Z | DEBUG in [TwilioConnection #18: wss://global.vss.twilio.com/signaling]: Outgoing: {"id":"7ff0cf41-94cb-4c48-b0eb-29968b1d2b05","timeout":5000,"type":"hello"} src.f69400ca.js:63853:23
The connection to wss://sdkgw.us1.twilio.com/v1/VideoEvents was interrupted while the page was loading.
```

along with

```
MaxListenersExceededWarning: "Possible EventEmitter memory leak detected. 11 enabled listeners added. Use emitter.setMaxListeners() to increase limit"
    _addListener events.js:206
    addListener events.js:222
    LocalTrackPublication localtrackpublication.js:65
    LocalAudioTrackPublication localaudiotrackpublication.js:35
    asLocalTrackPublication index.js:50
    updated localparticipant.js:311
    emit events.js:151
    setSid track.js:132
    setSid localtrackpublication.js:96
    update localtrackpublication.js:62
    update localparticipant.js:105
    update localparticipant.js:102
    _update room.js:348
    emit events.js:146
    handleMessage twilioconnectiontransport.js:463
    emit events.js:146
    _handleMessage twilioconnection.js:332
    _connect twilioconnection.js:232
backend.js:1:11466
```

**Software versions:**

 - [x] Browser(s): Firefox, Chrome (latest)
 - [x] Operating System: MacOS (latest)
 - [x] twilio-video.js: `2.0.0-beta13`
 - [x] Third-party libraries (e.g., Angular, React, etc.):
  - `react@16.9.0`

**Comment by makarandp0** [comment]
Hey @shrugs, Thank you for writing about this issue. I have started looking at it, and will get back to you soon but I have one quick initial questions - Can you point me to the file(s) that has the code that you pasted above ? I did not find anything related with a quick `grep` on https://github.com/XLNT/dot.gallery/tree/feat/audio

Thanks,
Makarand

**Comment by shrugs** [comment]
@makarandp0 oops, should have done that! here's the specific file: https://github.com/XLNT/dot.gallery/blob/feat%2Faudio/packages/gallery/src/hook/useTwilioRoom.ts 

I've been playing with in the meantime — if I stop users from changing rooms too frequently (by throttling the change events [here](https://github.com/XLNT/dot.gallery/blob/feat/audio/packages/gallery/src/pages/Gallery.tsx#L140)), the problems disappear (or at least, I haven't run into them yet in minimal testing)
