### ISSUE TITLE
Twilio.Video.isSupported flag returns true on Edge, but Edge is not supported

### ISSUE THREAD

**Issue by dambusm** [twilio/twilio-video.js#748]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

```js
console.log(Video.isSupported)
```

**Expected behavior:**

When running on Microsoft Edge on Windows 10 (EdgeHTML), should return false as Edge is not supported (https://github.com/twilio/twilio-video.js#browser-support)

**Actual behavior:**

Returns true

**Software versions:**

 - [x] Browser(s): Microsoft Edge 44.18362.329.0
 - [x] Operating System: Windows 10 Pro 10.0.18362
 - [x] twilio-video.js: 2.0.0-beta14
 - [x] Third-party libraries (e.g., Angular, React, etc.): React 16.8.6

**Comment by makarandp0** [comment]
Hello @dambusm,  Thank you for writing in regarding this issue. Yes this flag checks for functionality provided by the browser, than actual checks against browser version.

https://github.com/twilio/twilio-video.js/blob/master/lib/util/support.js#L31

Can you tell us how are you using or planning to use this flag in your application, and maybe we can suggest some workaround, or see if we can update this flag to report false for anything bug supported browsers.

**Comment by dambusm** [comment]
Hi @makarandp0, in our application we need to display a notice to the user and prevent them from attempting to join calls if they're running in an unsupported browser. On Edge our Twilio calls all fail when the local participant connects, with this error:
```
code: 53405
description: "Media connection failed"
message: "Media connection failed"
name: "TwilioError"
stack: "TwilioError: Media connection failed at _getOrCreate (https://c457642d.ngrok.io/static/js/0.chunk.js:338743:11) at Anonymous function (https://c457642d.ngrok.io/static/js/0.chunk.js:338820:9)"
```
I haven't done much debugging of this or reported it as I understand Edge is not supported. It would be great to get an update to the flag or a workaround.

**Comment by makarandp0** [comment]
Hey @dambusm, I have opened a bug to track this issue (JSDK-2515). In the meanwhile you can workaround this by detecting Edge in your code ? Something like: 

```
function isSupportedBrowser() {
   return /Edge/.test(navigator.userAgent) === false && Video.isSupported;
}
```

Thanks,
Makarand
JSDK Team

**Comment by dambusm** [comment]
Thanks @makarandp0. I'd love to have something a little more reliable than checking the userAgent, especially as it's working fine on the canary builds of Edge with Chromium, but I can live with that in the meantime.

**Comment by makarandp0** [comment]
This issue should now be fixed in [beta15](https://github.com/twilio/twilio-video.js/releases/tag/2.0.0-beta15) release.
