### ISSUE TITLE
Is there a plan to rollout twilio 2.x stable version?

### ISSUE THREAD

**Issue by raghav-g** [twilio/twilio-video.js#751]
I am awaiting the stable version of twilio 2.x. Is there a plan to roll it out before 2019?

**Comment by manjeshbhargav** [comment]
Hi @raghav-g ,

Sorry for the delayed response. Based on our current roadmap, it looks like this may happen sometime in Q1, 2020. Please follow the CHANGELOG.md in the master branch for updates.

Thanks,

Manjesh Malavalli
JSDK Team
