### ISSUE TITLE
[Q] How to publish lower resolution/size of the video?

### ISSUE THREAD

**Issue by smkrn110** [twilio/twilio-video.js#762]
Do Twilio handle the video resolution by itself according to the bandwidth of the user? Or should we handle it, if yes? How?

Sending option while connecting two `Twilio.Video.connect({video:{width:640}})` what is the impact of this?

**Comment by manjeshbhargav** [comment]
Hi @smkrn110 ,

Yes, to a certain extent. You can listen to changes in the resolution of the RemoteVideoTracks by listening to the [dimensionsChanged](https://media.twiliocdn.com/sdk/js/video/releases/2.0.0-beta14/docs/RemoteVideoTrack.html#event:dimensionsChanged) event.

If you specify video dimensions in ConnectOptions, then twilio-video.js will capture video from your camera at the suggested resolution.

On a separate note, I recommend that you try the new [Bandwidth Profile API](https://github.com/twilio/twilio-video.js/blob/2.0.0-beta14/CHANGELOG.md#new-features), which we released recently. This will allow you to configure how your downlink bandwidth is distributed among the RemoteVideoTracks based on their relative importance to the application. This might help you in better managing the video experience for the customer.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by smkrn110** [comment]
@manjeshbhargav

Actually what in my mind is that we are using Network Quality Api, and I want to accomplish that when badnetwork detected, instead of high resolution video to publish I want to reduce the resolution of the video track of the user.

**Comment by mding5692** [comment]
Hi @manjeshbhargav 

What does changing the video resolution to 640 mean? Does that mean the video the other user sees is cropped down to 640pixels to 640 pixels?

Trying to read through the API docs and the code for an explanation of video resolution but there isn't any.

**Comment by manjeshbhargav** [comment]
@smkrn110 ,

Please check out the [Bandwidth Profile API Guide](https://www.twilio.com/docs/video/tutorials/using-bandwidth-profile-api). However, in order to gain access to it, please reach out to [video-product@twilio.com](mailto:video-product@twilio.com) to request enabling the Bandwidth Profile API for your account.

@mding5692 ,

I didn't quite get your question. What precisely are you trying to accomplish with video resolutions?

**Comment by mding5692** [comment]
@manjeshbhargav Is there a way to reduce resolution using the video dimensions?

**Comment by manjeshbhargav** [comment]
@mding5692 ,

Once you have published a LocalVideoTrack to a Room, there are two options to change the video resolution:

1. Unpublish the existing LocalVideoTrack and publish a new LocalVideoTrack with different resolution.

2. Access the underlying LocalVideoTrack's MediaStreamTrack and change the capture constraints:

### twilio-video.js 1.x
```js
const videoTrack = [...room.localParticipant.tracks.values()][0];
videoTrack.mediaStreamTrack.applyConstraints({
  width: 640,
  height: 360
}).catch(e => {
  console.error('Error while applying capture constraints:', e.message);
});
```

### twilio-video.js 2.x
```js
const videoTrackPublication = [...room.localParticipant.tracks.values()][0];
videoTrackPublication._signaling._trackTransceiver.track.applyConstraints({
  width: 640,
  height: 360
}).catch(e => {
  console.error('Error while applying capture constraints:', e.message);
});
```

Option 1 is straightforward, but the RemoteParticipant will notice that you unpublished and re-published the VideoTrack.

Option 2 dynamically alters the capture constraints, but it is not directly supported by the SDK and is a bit of a hack.

Hope this helps.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by mding5692** [comment]
Ok much thanks!

**Comment by ing-fabian** [comment]
Hi @manjeshbhargav,

I'm having a problem with the dimensions and found this issue, so I think was good idea to comment here. I'm publishing our local tracks with dimensions as 1280x720 for all of our users. But when we get the participant tracks these video tracks are coming with other dimensions, I think is coming from the original setting for the camera but I can not be sure about it, what's clear is that I don't get the original dimension that was used to publish the track.

I tested your solution using _signaling, but with this solution the user will see a jump between the resolutions when the video is added by first time. Is there any other way to handle this dimensions? All what I need is to keep the same proportions, for example: 

If I create a video 1280x720, I should receive any dimension that respect this proportion like 896x504, 640x320, 512x256, etc.

These are the constraints I'm sending to createLocalVideoTrack:

`{
          width: 1280,
          height: 720,
          frameRate: { exact: 30 },
          deviceId: { exact: 'someDeviceId' }
  }`

I'm passing my localTracks to connect function using the option `tracks` like this:

` Twilio.Video.connect(token, { tracks: localTracks, region: 'xxx', networkQuality: { ... }, ... }) `

and I'm getting these dimensions when the participant get connected:

`{ width: 640, height: 480 }`

My Twilio version is 2.0.0

Any help will be much appreciate it!

**Comment by gritbranch** [comment]
Hi @manjeshbhargav,

I am having similar issue with what @ing-fabian has mentioned. When using Option 2 (i.e. videoTrackPublication._signaling._trackTransceiver.track.applyConstraints(...)) to lower the resolution, the 16:9 aspect ratio is not applied. This happens when I try to lower the resolution and I'm using Safari or Firefox. For Chrome, this is working really well with aspect ratio maintained to what was originally set.

I'm aware that Option 2 is not fully supported at this point as you've mentioned but is there a way to work around the aspect ratio problem on Safari and Firefox?

Thanks.
