### ISSUE TITLE
[Issue] Can we have participant sid(s) along with track sid(s) with getStats() method.

### ISSUE THREAD

**Issue by smkrn110** [twilio/twilio-video.js#767]
@philnash @manjeshbhargav @syerrapragada 

Hi 

On getStats() I am receiving the object, which not include RoomSID and the participant SID, is it possible we can have these details in that object?

**Comment by manjeshbhargav** [comment]
Hi @smkrn110 ,

Each TrackStats object contains the corresponding Track SID, which you can use to look up the Room SID and Participant SID by cycling through `room.participants`:
```js
const getParticipantSidForTrackSid(room, trackSid) {
  const participant = [...room.participants.values()].find(participant => participant.tracks.has(trackSid);
  return participant.sid;
}
```
Right now, we don't have any plans to include Room SID and Participant SID in the stats object.
I hope this unblocks you from moving forward with your implementation.

Thanks,

Manjesh Malavalli
JSDK Team
