### ISSUE TITLE
Semver invalid with 2.0 beta

### ISSUE THREAD

**Issue by KaelWD** [twilio/twilio-video.js#768]
We had `2.0.0-beta9` installed before and thought we'd updated to `beta14`, but the prerelease identifier is compared alphabetically so yarn thinks `beta9` is the latest version. 

![image](https://user-images.githubusercontent.com/16421948/66369771-6ef96280-e9e9-11e9-9260-866e28dbe45f.png)

Prerelease versions should have a period between the name and number, eg. `2.0.0-beta.9` or `2.0.0-beta.14`

![image](https://user-images.githubusercontent.com/16421948/66369672-08744480-e9e9-11e9-9dd5-de79b9c5450d.png)

![image](https://user-images.githubusercontent.com/16421948/66369795-833d5f80-e9e9-11e9-8b77-ab640616df56.png)

**Comment by makarandp0** [comment]
Thank you @KaelWD for bringing this up. We also noticed the mistake, and will keep this in mind going forward.
