### ISSUE TITLE
Muting video

### ISSUE THREAD

**Issue by github4f** [twilio/twilio-video.js#772]
I am wondering how I can mute the video (i.e., switch to audio mode) in the middle of a call? is there any flag to set? I can mute the audio by disabling LocalAudioTracks but have no idea to disable video.

**Comment by makarandp0** [comment]
Hello @github4f,  

Assuming you are trying to disable local participant's video - You can use  `enable` method on `LocalVideoTrack` Its documented [here](https://media.twiliocdn.com/sdk/js/video/releases/2.0.0-beta14/docs/LocalVideoTrack.html#enable__anchor)

So for example, given a room object following function will disable all local video tracks:
```
function disableAllMyVideoTracks(room) {
  room.localParticipant.videoTracks.forEach(({ track }) => {
    track.enable(false);
  });
}
```

Which version of the SDK are you using? The code above should work for version 2.x, It will be slightly different for 1.x version of the SDK.

Let me know if you have any further questions,
Thanks,
Makarand

**Comment by makarandp0** [comment]
Hey @github4f - I am closing this issue now. Let us know if the solution does not work for you or if you have any further questions.
