### ISSUE TITLE
Video and Audio Stream are empty for inbound and as well as Outbound

### ISSUE THREAD

**Issue by kamesh-a** [twilio/twilio-video.js#773]
- [x ] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [ xx] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x ] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

Hi,

One our windows user was having issues with her video, When we check it, we found that there are no frames/data in video stream. While looking into remote mediaStream capabilities, `frameRate:0` and `chrome://webrtc-internals` shows a flat line of noEncoding or framesSent.

We have initially tested our application and verified the same behaviour exhibited with twilio-quickstart. For the same user the streams are getting proper bytes in Firefox. Both in Chrome and Edge ( Chromium ) based it wasn't.

Twilio-Quickstart : Twilio SDK 1.19.2
Our App: Twilio SDK 2.0.0-beta12

**Expected behavior:**
- Should get the incoming video stream
- Should produce outgoing video stream.

**Actual behavior:**
- Incoming MediaStreamTrack was having frameRate:0 
- Both audio and video tracks were not working.

We did test chrome & Edge  browser with other video call products, it was able to produce/consume the streams.

**Logs**
- [Twilio SDK 2.0.0-beta12 logs](https://connect-feedback-logs.storage.googleapis.com/generallog-1f284f56-ddf7-4a96-86d9-53b98ea893f4.log)
- [Twilio SDK 1.19.2 logs ](https://www.dropbox.com/s/dmgn16rq9wc44ez/windows_8.1_twilio_quickstart.log?dl=0)

**Software versions:**

 - [x] Browser(s): Chrome 77, Edge ( Chromium 79 )
 - [x] Operating System: Windows 8.1
 - [x] twilio-video.js: 1.19.2, 2.0.0-beta12
 - [x] Third-party libraries (e.g., Angular, React, etc.): React

**Comment by makarandp0** [comment]
Hello @kamesh-a, Thank you for reporting this issue. 

I am looking to see if I can find something from the server side logs. I will get back to you.

I have few questions in the meanwhile: 

I assume the logs linked to this issue were captured from the machine/browser that has this issue. How about other users in the same call on these logs - were they connected from the same machine / browser ? 

When the issue repros is it limited to incoming audio/video tracks or for outgoing tracks as well? 

Does this issue repro consistently with windows 8.1 for other users too ? I will also try to get hold of a windows 8.1 to see if I get a repro.

**Comment by kamesh-a** [comment]
Hi @makarandp0 ,

Thank you for acknowledging, 

` I assume the logs linked to this issue were captured from the machine/browser that has this issue` - Yes, we have captured this logs from user who was having issue.

`How about other users in the same call on these logs - were they connected from the same machine / browser ?` - they were connected to same room from different machines. I initiated this call to get the logs.

Yes, it is very much reproducible from her machine. But Firefox does seems to work for the user who was having the issue, streams properly send data for inbound as well as outbound streams in same machine.

We have asked our team to monitor, as of now, we didn't get any info from other. I will try to check this in our development machines with windows 8.1 and update the thread. If it helps.

Please let us know, if you need any other info. We will be glad to check them as well.

**Comment by makarandp0** [comment]
Thank you for the update @kamesh-a. I looked into server logs and indeed see that there were no media sent or received by this user (`PAea4374374d13876035469d96a2186a0b`) 

We are looking further into this issue . 

About outgoing/local streams - I have a quick question - In quickstart app, if you preview-stream on this browser (w/o connecting the room) does it previews correctly ?

**Comment by kamesh-a** [comment]
Hello @makarandp0 

`About outgoing/local streams - I have a quick question - In quickstart app, if you preview-stream on this browser (w/o connecting the room) does it previews correctly ` - yes local preview of video stream of the participant was showing properly for both our app and twilio quick-start. 

We indeed connected quickstart with ngrok and added few more participants they got connected to room properly and successfully sent/recieved streams apart from that windows 8.1 user whom neither received stream nor pushed to SFU

Please let me know, if you have any other queries.
