### ISSUE TITLE
Group room communicate with one to one

### ISSUE THREAD

**Issue by DipenIprospl** [twilio/twilio-video.js#778]
User-1 is connected to room1 and do not want to allow other participants to see his/her video until allow by User-1.  How this can be done. As in current flow if user-2 is connecting, he/she can able to view the already participant screen.

**Comment by makarandp0** [comment]
@DipenIprospl - How about letting user1 connect w/o Video Track, 
```
const room = await Video.connect('my-token', {
  name: 'room1',
  audio: true
});
```
and Publish Video track only when needed. 
```
// Add video when user-1 is ready 
Video.createLocalVideoTrack().then(function(localTrack) {
   room.localParticipant.publishTrack(localTrack);
});

```

**Comment by DipenIprospl** [comment]
This Issue Solve.
