### ISSUE TITLE
Update stream during call

### ISSUE THREAD

**Issue by acbuitrago** [twilio/twilio-video.js#793]
Hi,
Is there any way of updating the stream of a `LocalVideoTrack` without unpublishing the current track and adding a new one? 
I would like to swap my stream as smoothly as possible, but haven't been able to do it without unpublishing the track. 
I found this issue: https://github.com/twilio/twilio-video.js/issues/43, but the function used to update the stream is no longer available.

**Comment by makarandp0** [comment]
Hello @acbuitrago, Thank you for writing about this issue. Which version of the SDK are you using? 

When you say that you want to swap your stream smoothly - I am wondering if handling from subscriber side is an option ? Basically let publisher add  2nd video track first and then unpublish 1st track. On Subscriber side listen for track getting added, and as track get added swap them smoothly ?   

Thanks,
Makarand

**Comment by acbuitrago** [comment]
Hi @makarandp0, thanks for your answer. 
I'm using the SDK version *2.0.0-beta14*.

You are right, we can handle the swap from the subscriber side. I wasn't aware until now that when a track is published we receive a promise if it's successful, so we could unpublish the track right there. 
So, (just to know) rightnow there's no way to change the stream of a published stream similar to the way proposed on https://github.com/twilio/twilio-video.js/issues/43?

**Comment by makarandp0** [comment]
@acbuitrago - Glad that subscriber side track switch option works for you. Yes, I do not see a way to replace track from publisher side. And yes the [publish API](https://media.twiliocdn.com/sdk/js/video/releases/2.0.0-beta14/docs/LocalParticipant.html#publishTrack__anchor) returns a promise, that resolves with [LocalTrackPublication](https://media.twiliocdn.com/sdk/js/video/releases/2.0.0-beta14/docs/LocalTrackPublication.html), which  can be used to call `unpublish` on.
