### ISSUE TITLE
What is the error if a firewall block the connexion

### ISSUE THREAD

**Issue by VincentSim** [twilio/twilio-video.js#797]
Hi there,

I have issues with firewall some people are enable to launch the visio and they see them but they don't see the other person. 
There is a code error in the twilio logs for this situation ?

And more generally is it possible to have the code error ? I manage to find error.message but not the error.code...

Best,

Vincent

**Comment by manjeshbhargav** [comment]
Hi Vincent,

Sorry for the late response. It depends on the firewall rules that you have set. Please refer to the [IP Address Whitelisting Guide](https://www.twilio.com/docs/video/ip-address-whitelisting) to make sure your firewall rules conform to the recommendations in it.

Thanks,

Manjesh
