### ISSUE TITLE
Documentation for createLocalVideoTrack incomplete

### ISSUE THREAD

**Issue by kaitlynbrown** [twilio/twilio-video.js#808]
The documentation for `createLocalVideoTrack` indicates that it takes a `CreateLocalTrackOptions` as an argument, however the documentation for `CreateLocalTrackOptions` does not contain all of the possible arguments that can be given. It is at least missing `aspectRatio` and `width`. What else is it missing? Please update the documentation

https://media.twiliocdn.com/sdk/js/video/releases/2.0.0-beta10/docs/global.html#CreateLocalTrackOptions

**Comment by makarandp0** [comment]
Thank you @kaitlynbrown for pointing this issue. Yes, the documentation is missing details about possible options. twilio-video passes these options to  [getuserMedia](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia) call, Thus various options listed for [MediaStreamConstraints](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamConstraints) are also applicable. we have a work item to fix the documentation (JSDK-2567).

Thanks,
Makarand
JSDK Team

**Comment by manjeshbhargav** [comment]
Hi @kaitlynbrown ,

The latest [SDK docs for version 2.3.0](https://media.twiliocdn.com/sdk/js/video/releases/2.3.0/docs/global.html#CreateLocalTrackOptions) provides a link to the MediaTrackConstraints API, which is accepted by `createLocalVideoTrack()`. Please check it out.

Thanks,

Manjesh Malavalli
JSDK Team
