### ISSUE TITLE
Docs for LocalAudioTrack, LocalVideoTrack disappeared in 2.0.0-beta15

### ISSUE THREAD

**Issue by graue** [twilio/twilio-video.js#810]
2.0.0-beta14 has documentation for these two classes:

https://media.twiliocdn.com/sdk/js/video/releases/2.0.0-beta14/docs/LocalAudioTrack.html
https://media.twiliocdn.com/sdk/js/video/releases/2.0.0-beta14/docs/LocalVideoTrack.html

For 2.0.0-beta15 these are 404s:

https://media.twiliocdn.com/sdk/js/video/releases/2.0.0-beta15/docs/LocalAudioTrack.html
https://media.twiliocdn.com/sdk/js/video/releases/2.0.0-beta15/docs/LocalVideoTrack.html

**Comment by makarandp0** [comment]
Hello @graue, Thank you for reporting this issue. Recently we updated our documents to include top level module [`twilio-video`](https://media.twiliocdn.com/sdk/js/video/releases/2.0.0-beta15/docs/module-twilio-video.html).   

With this change some of the previously `globals` types including `LocalAudioTrack` and `LocalVideoTrack` can now be found under the module.

https://media.twiliocdn.com/sdk/js/video/releases/2.0.0-beta15/docs/module-twilio-video.LocalAudioTrack.html
https://media.twiliocdn.com/sdk/js/video/releases/2.0.0-beta15/docs/module-twilio-video.LocalVideoTrack.html

Thanks,
Makarand
JSDK Team.

**Comment by makarandp0** [comment]
We have now restored the doc links for these classes back as they were in beta14
