### ISSUE TITLE
Add Typescript EventEmitter typings 

### ISSUE THREAD

**Issue by cdunford** [twilio/twilio-video.js#818]
It looks like there are no specific typings to narrow what events can be subscribed to (narrowing `EventEmitter.on(...)`). on the various EventEmitter objects in the API. It would be great if these could be added at some point.

**Comment by anna-vasilko** [comment]
Thank you for bringing it up @cdunford. This is already in our backlog and will be worked on early in 2020.

**Comment by DylanVann** [comment]
To make the types work for now you can install `@types/events`.

**Comment by nsmithdev** [comment]
For my project it was giving errors only on compile that the `.on` method did not exist.
This lib seems to require the node type be included for the event emitter methods to be available.

```json
  // tsconfig.json
  "compilerOptions": {
    "types": [
      "node"
    ]
  },
```

**Comment by Pitazzo** [comment]
@nsmithdev does your tsconfig file look like this? I'm facing the same issue, but without any success

```
{
  "files": [],
  "references": [
    {
      "path": "./tsconfig.app.json"
    },
    {
      "path": "./tsconfig.spec.json"
    }
  ],
  "importHelpers": true,
  "compilerOptions": {
    "types": ["node"]
  }
}
```

**Comment by PikaJoyce** [comment]
Hey @cdunford and @nsmithdev,

Apologies for getting back to this late, but the TypeScript definitions have been added to our library in `2.11.0`, please see the [CHANGELOG.md entry](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md#2110-january-26-2021). Please let us know if you encounter any issues and feel free to respond to this thread if you do. However, I will be closing this issue for now! 

Thank you for your patience,
Joyce
