### ISSUE TITLE
Twilio Video Error: Signaling connection disconnected

### ISSUE THREAD

**Issue by acbuitrago** [twilio/twilio-video.js#825]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**
We used the latest quickstart: https://github.com/twilio/video-quickstart-js

**Expected behavior:**
We should be able to connect to all the rooms without getting "Signaling connection disconnected".

**Actual behavior:**
For some rooms we are getting a "Signaling connection disconnected" and for others it's connecting rightaway. This is not a client or network issue, since we tried at the same to connect to two rooms and one connected successfully and the other received the error "Signaling connection disconnected". 

_Data of the room that's working as expected:_
 Name: room_5653241173901312
SID: RM129a30d5cb6312f4e325762b60c61874

_Data of the room that's not working as expected:_
Name: room_5664342561259520
SID: RM0c24deb3e0d414e66525a88d604ea326

I'm attaching both logs. 
[error_twilio.txt](https://github.com/twilio/twilio-video.js/files/3932688/error_twilio.txt)
[sucess_twilio.txt](https://github.com/twilio/twilio-video.js/files/3932689/sucess_twilio.txt)

**Software versions:**

 - [x] Browser(s): Firefox 71.0 and Chrome 78
 - [x] Operating System: MacOS Mojave 10.14.6
 - [x] twilio-video.js: "^1.20.0", though we have also seen it with "^2.0.0-beta14"
 - [X] Third-party libraries (e.g., Angular, React, etc.): The ones on video-quickstart-js, though we also tested with an app on Angular.

**Comment by makarandp0** [comment]
Thank you for reporting this issue @acbuitrago. I noticed that you have also opened a support ticket for this. We will investigate the support ticket and get back to you.

**Comment by manjeshbhargav** [comment]
Hi @acbuitrago ,

I sincerely apologize for the delay, as we are short-staffed during the holiday season. It looks like the Room where you got disconnected was affected by an incident in our back-end, which has been resolved. You should not experience this issue any longer. Please re-open the issue if you are still experiencing this problem.

Thanks,

Manjesh
