### ISSUE TITLE
twilio-video getusermedia is not supported on chrome

### ISSUE THREAD

**Issue by Pkaran26** [twilio/twilio-video.js#831]
- [ ] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [ ] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

```js
// TODO
```

**Expected behavior:**

TODO

**Actual behavior:**

TODO

**Software versions:**

 - [Google Chrome ] Browser(s):
 - [Windows 10, Linux Mint 19.2 ] Operating System:
 - [2.x ] twilio-video.js:
 - [ ReactJS ] Third-party libraries (e.g., Angular, React, etc.):

**Comment by manjeshbhargav** [comment]
Hi @Pkaran26 ,

Thanks for writing in with your issue. I see that you have not checked the first 2 items in the checklist for opening the issue. From your heading it looks like you're getting an error on Chrome saying the `getUserMedia` is not supported. I'm surprised you're getting this error since WebRTC has been supported by Chrome since a long time. Please let me know once you've filled out the other details (code samples, browser version, etc.) and I will take a look.

Thanks,

Manjesh

**Comment by manjeshbhargav** [comment]
@Pkaran26 ,

You can also get this error if you're running Chrome in "incognito" mode. Can you check whether you ran your app in "incognito" mode?

Thanks,

Manjesh

**Comment by rajesh-smartwebtech** [comment]
@manjeshbhargav 
Thank you 
Can i use on without domain online using with IP ?? 
is this possible ??

**Comment by magbhu** [comment]
Hi,
i am developing a mobile app using iOS - Swift . There is a facility called WKWebView which will load the browser inside the app. I am trying to load the Twilio video chat js in this WkWebView.   I am able to get the first page but when i am initiating the video , it is giving an error as mentioned above "Could not connect to Twilio:getUserMedia is not supported".   
![IMG_1024](https://user-images.githubusercontent.com/47789946/87400839-f908d400-c5d6-11ea-8624-197878673f4b.PNG)

**Comment by rajesh-smartwebtech** [comment]
@magbhu  it working on only https 
or localhost

**Comment by maxidirienzo** [comment]
@magbhu You cannot call `getUserMedia()` on a page served via HTTP (except when browsing `localhost`), the page needs to be served via HTTPS otherwise Chrome blocks this API.

You can install a self signed certificate to overcome this in dev or test environments.

**Comment by amadoru** [comment]
@magbhu try tunnelling it through ngrok.com. That should be good enough for your development workflow.

**Comment by anagharm** [comment]
Hi,

I am trying to implement this using React APP and token is generated from NodeJS REST API

My NodeJS API is url is ssl certified but my React APP url is not ssl certified. And I am getting this error. 

Do we need to have both the urls ssl certified?

**Comment by ScottAgirs** [comment]
Would be nice to have the ability to specify specific IP addresses to allow the insecure connection. I wonder if that's something that could be considered/done?
