### ISSUE TITLE
Huge difference in time of recorded video duration and the room duration.

### ISSUE THREAD

**Issue by Gauri7** [twilio/twilio-video.js#832]
Hi, @ twilio_team our clients are receiving wrong duration and broken video call recorded video files.

Example:
The actual call ends in `5 minutes` but we are getting recorded videos for  `2 hours` and it's getting stuck with the last screen share frame.

We could able to see these issues normal browser calls followed by the screen share.

Scenario 1:
If user join from safari browser, screen share is started by any other user in room.

Scenario 2:
- If user who screen shares disconnect the room during screen share without stopping the track.

`Twilio_sdk_version` : `2.0.0-beta15`

`RoomSID` : `RMb73d779c00fc0e9810449660a3cf42ca`

**Comment by sandeepnandula** [comment]
Hi, @team any updates regarding this issue?

**Comment by anna-vasilko** [comment]
Hey @sandeepnandula. Thanks for reporting the issue! That does not sound right. I am not seeing anything abnormal in room's logs per se, so ended up opening a ticket for our recordings team. Will reply as soon as I hear back from them.

**Comment by anna-vasilko** [comment]
@sandeepnandula In the logs I can see that RMb73d779c00fc0e9810449660a3cf42ca was 33 seconds long, recording for Participant 1 was 25 seconds long, and for Participant 2 it was 21 seconds long. That seems correct. How long are the actual recordings you are getting for this particular room? Mind providing a recording sid for a case where it does not match the reality.

[group_billing_event] for P1 with bytes sent 559344, bytes received 2876384, **recording time in secs 25**
....
2019-12-05T12:30:16.722Z: P2 received disconnected
2019-12-05T12:30:16.907Z: [group_billing_event] for P2 with bytes sent 1412212, bytes received 874310, **recording time in secs 21**

**Comment by anna-vasilko** [comment]
@sandeepnandula Hi, we got a confirmation from backend teams that the issue was known and the fix got released end of last week. Basically it should be working properly now. Please re-open if you encounter it again.

**Comment by sandeepnandula** [comment]
Thank you @anna-vasilko for the update. We will let you know if the issue encounters again.
