### ISSUE TITLE
Twilio video warning in version 1.14

### ISSUE THREAD

**Issue by jinming88** [twilio/twilio-video.js#840]
Hi.
I am using twilio video sdk.
version is 1.14.
Now,I found this warning.
I don't know well why this happened.

2019-12-25 04:37:13.317Z | WARN in [LocalParticipant #1: PA60d926a6c26eb8ac83dfc01541b5fe5a]: LocalParticipant#trackAdded has been deprecated and scheduled for removal in twilio-video.js@2.0.0.

Please let me know,why this error happend.
Thanks.
Jin

**Comment by manjeshbhargav** [comment]
@jinming88 ,

Thanks for writing in with your question. We added this warning message to make sure all our customers know that "trackAdded" event on the LocalParticipant will no longer be supported starting from v2.0. When you decide to migrate toe v2.0 of the SDK, I recommend that you follow our [migration guide](https://www.twilio.com/docs/video/migrating-1x-2x).

Hope this answers your question. Please feel free to re-open the issue if you need more clarification.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by anna-vasilko** [comment]
@jinming88 In addition, v1.14 is pretty old and will stop working properly in Google Chrome in Q1 2020. We recommend updating to versions 1.20 or 2.0.0 as soon as possible. Find more details in our [public advisory](https://support.twilio.com/hc/en-us/articles/360039098974-Upcoming-Breaking-Changes-in-Twilio-Video-JavaScript-SDK-Google-Chrome)

**Comment by jinming88** [comment]
Thanks Anna!

Please help me one more time.
I tried to migrate my version to 2.0 but some functions have some errors.

This is my code.
Twilio.Video.createLocalTracks({
   audio: true,
   video: {width : "" , height : "100vh" }
}).then(function(localTracks) {
   return Twilio.Video.connect(res, {
       name: name,
       tracks: localTracks,
       video: {width : "" , height : "100vh"}
   });

}).then(function(room) {
   	console.log('Successfully joined a Room: ', room.name);

   	room.participants.forEach(participantConnected);
   	setTimeout(function(){
   		if(room_id == 1)
	   	{
	   		$("#check_start").val(1)
	   		console.log("start_remote");
	   	}else{
	   		console.log("start_local_again");
	   		twilio_video();
	   	}
   	}, 3000);

   	var previewContainer = document.getElementById(room.localParticipant.sid);
   	if (!previewContainer || !previewContainer.querySelector('video')) {
		participantConnected(room.localParticipant);
   	}

   	room.on('participantConnected', function(participant) {
       console.log("Joining: '"+participant.identity+"'");
       participantConnected(participant);
   	});

   	room.on('participantDisconnected', function(participant) {
       	console.log("Disconnected: '"+participant.identity+"'");
   		participantDisconnected(participant);

       	// $.ajax({
	       // 	url : "home_controller/disonnect_room",
	       // 	type : "POST",
	       // 	data : {
	       // 		id : participant.identity 
	       // 	},
	       // 	dataType : "JSON",
	       // 	success : function(res)
	       // 	{

	       // 	}
       	// })
   });
});

How can I migrate this to 2.0?
Please help me.
Thanks.

**Comment by manjeshbhargav** [comment]
@jinming88 ,

It looks like your code is based on our quickstart. Please refer to this [piece of code](https://github.com/twilio/video-quickstart-js/blob/master/quickstart/src/index.js) which demonstrates how to use the 2.0 SDK.

Thanks,

Manjesh Malavalli
JSDK Team
