### ISSUE TITLE
Hi team I have no issue just need to confirm if you will make video library available officially for Cordova plugin in future. 

### ISSUE THREAD

**Issue by guruaugust** [twilio/twilio-video.js#841]
- [ ] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [ ] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ ] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [ ] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

```js
// TODO
```

**Expected behavior:**

TODO

**Actual behavior:**

TODO

**Software versions:**

 - [ ] Browser(s):
 - [ ] Operating System:
 - [ ] twilio-video.js:
 - [ ] Third-party libraries (e.g., Angular, React, etc.):

**Comment by manjeshbhargav** [comment]
Hi @guruaugust ,

Thanks for writing in with your question. As of now, we don't have plans to support Cordova in the near future. However, you can check out this [open source project](https://github.com/okode/cordova-plugin-twilio-video) that provides a Cordova plugin for Twilio Video. Maybe that will work for your use case.

Thanks,

Manjesh Malavalli
JSDK Team
