### ISSUE TITLE
Does Twilio-Video has a timeout event when none joined a room? 

### ISSUE THREAD

**Issue by nitzanb-medopad** [twilio/twilio-video.js#843]
When I connect a room I want it to behave like a call, so I'm "calling" other user. Does Twilio have a timeout event if none of the other users connected to the room after X seconds?

**Comment by manjeshbhargav** [comment]
@nitzanb-medopad ,

Thanks for writing in with your question. No, we don't have a timer if there is only one Participant and no one else joins the Room. But you can easily achieve that from your application:
```js
const { connect } = require('twilio-video');

const timeoutPromise = () => new Promise(resolve => {
  setTimeout(() => resolve(false), 5000);
});

const participantConnectedPromise = room => new Promise(resolve => {
  if (room.participants.size > 0) {
    resolve(true);
  } else {
    room.once('participantConnected', () => resolve(true));
 }
});

let activeRoom;

connect(token, options).then(room => {
  activeRoom = room;
  return Promise.race([
    participantConnectedPromise(room),
    timeoutPromise()
  ]);
}).then(didParticipantConnect => {
  if (!didParticipantConnect) {
    console.log('No Participants connected after 5 seconds, disconnecting...');
    activeRoom.disconnect();
  }
});
```
Hope this helps. Please feel free to re-open the issue if you need any further clarifications.

Thanks,

Manjesh Malavalli
JSDK Team
