### ISSUE TITLE
Providing a method to clear events

### ISSUE THREAD

**Issue by nitzanb-medopad** [twilio/twilio-video.js#844]
Does Twilio provide a way to clear its events?

I use 'once' but it's not helpful:
```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 participantDisconnected listeners added. Use emitter.setMaxListeners() to increase limit
```

**Comment by manjeshbhargav** [comment]
Hi @nitzanb-medopad ,

Thanks for writing in with your issue. Is it possible for you to share the code snippet where you are observing this issue?

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by nitzanb-medopad** [comment]
I use mostly room.once, I change modes and call those events again and because of that I need to clear them

**Comment by manjeshbhargav** [comment]
@nitzanb-medopad ,

All public classes in the SDK derive from the EventEmitter class, which has a `removeListener()` method. You can use that method to clear event listeners added using `on()` or `once()`.
Please let me know if this works for you.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by nitzanb-medopad** [comment]
works for me, thanks :)

**Comment by csellis** [comment]
> works for me, thanks :)

Do you mind sharing how you did this? I'm getting the same error

**Comment by cooper6101** [comment]
Can someone please post an example using the removeListener() method. This is driving me nuts. I keep getting errors stating the argument must be a function or it cannot except an object as an argument. Here is my latest attempt.

conversation.removeListener('messageAdded', conversation.getMessages());

I also tried conversation.removeListener('messageAdded', getMessages(); 

and adding this to getMessages();

Thanks!

**Comment by cooper6101** [comment]
Hey @PikaJoyce! Thanks for the response. I had tried that as well. It turns out I was initializing my messages twice in my application and one was outside of my useEffect call. This was causing the event to fire infinitely ugh. Dumb mistake but glad I finally caught it. 

Thanks!

Trey

**Comment by lucasbasquerotto** [comment]
I was getting an error of maximum listeners reached and was able to simulate disconnecting a participant and reconnecting it again successively.

I was able to solve the issue changing the code when the participant is disconnected to:

```js
const handleDisconnectedParticipant = (participant) => {
	participant.audioTracks.forEach(trackPublication => {
		trackPublication.track && trackPublication.track.removeAllListeners();
		trackPublication.removeAllListeners();
	});

	participant.videoTracks.forEach(trackPublication => {
		trackPublication.track && trackPublication.track.removeAllListeners();
		trackPublication.removeAllListeners();
	});

	participant.removeAllListeners();

	//...
};
```

Before I used only `participant.removeAllListeners()`, which I assumed removed all listeners of the participant, including their tracks and publications, but it seems that's not the case.

**Comment by angstyloop** [comment]
An alternative solution to listener management in JS is to extend the EventTarget class from the JS Web API, overriding the addEventListener and removeEventListener methods to maintain a data structure containing the listener function references.

I follow this approach in the Gist below, where I also have a few unit tests. You can run the tests in the browser JS console by copying the code from the Gist to your clipboard, pasting it into the browser JS console, and pressing enter. Please read strange JS from the internet before running it in your JS browser console.

https://gist.github.com/angstyloop/504414aba95b61b98be0db580cb2a3b0
