### ISSUE TITLE
networkQualityLevelChanged event  triggers for both local and remote participants when localparticipant's quality changes

### ISSUE THREAD

**Issue by light94** [twilio/twilio-video.js#846]
I am using twilio-video 1.20.0 and trying to make use of the `networkQualityLevelChanged` event.
I've observed that almost always changes in network quality of the local participant also results in the `networkQualityLevelChanged` event being trigerred for the remote participant as well.

I am trying to replicate this scenario by using traffic control utility `tc`. I am using it in this way
`tc qdisc del dev wlp2s0 root netem loss 10%` which is basically dropping 10% of my packets.
I've tested this on Linux and Mac, on Chrome and Firefox browsers 

- [x]  I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).

 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Expected behavior:**

The `networkQualityLevelChanged`  event for the local and remote participants should be independent

**Actual behavior:**

**Software versions:**

 - [x] Browser(s): Firefox, Chrome
 - [x] Operating System: Linux, Mac
 - [x] twilio-video.js: 1.20.0
 - [ ] Third-party libraries (e.g., Angular, React, etc.):

**Comment by manjeshbhargav** [comment]
Hi @light94 ,

Thanks for writing in with your issue. In your test, was the RemoteParticipant running on the same machine as the LocalParticipant? If so, it may explain why you're seeing `networkQualityLevelChanged` events for both LocalParticipant and RemoteParticipant.

If the RemoteParticipant is running on a different machine, then this might just be a coincidence. Have you been able to reproduce this behavior consistently? Can you update your test to log the network quality level of the LocalParticipant and RemoteParticipant(s) whenever `networkQualityLevelChanged` is fired? That way, you can know if the event fired on the RemoteParticipant due to an actual change in the level.

Please let me know what you find.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by light94** [comment]
Hi @manjeshbhargav, thanks for the quick response.

**Comment by light94** [comment]
Hi @manjeshbhargav ,
thanks for the quick response.
I was using 2 different systems to run the tests.

I am able to reproduce this behavior consistently. I tried logging in the way you mentioned above and found that the Remote participant's network quality was almost always around +/-1 range of the local participant if I manually changed the network condition as described above. 
Is there a more robust method of testing this scenario , so that I can eliminate the possibility you have mentioned where in it can be a coincidence?

**Comment by light94** [comment]
I came across this article https://www.twilio.com/docs/video/tutorials/working-with-vp8-simulcast
There is this line mentioned 

> Hence, when there are subscribers with limited receive bandwidth, publishers need to reduce quality to adapt to the worst of them so that no subscriber is congested. 

Does this influence the network quality reported by twilio's api?

**Comment by manjeshbhargav** [comment]
Hi @light94 ,

I just wanted to clarify what the network quality level actually means. It is a relative score based on whether your available bandwidth is enough to handle the amount of media you want to share. For example, you may get a level of 5 (highest) even on a low-bandwidth system if all you want to share is your audio. And, you may get a level of 1 (lowest) even on a high-bandwidth system if the amount of audio+video you want to share exceeds the bandwidth capacity of your system.

So, one way to set up your test is to have one Participant share only audio, and the other Participant share audio+video+screen. Then, start throttling the bandwidth on the latter Participant's system.

Please let me know how it pans out.

Thanks,

Manjesh Malavalli
JSDK Team
