### ISSUE TITLE
Package not working in React Scripts < 2.0

### ISSUE THREAD

**Issue by ashishajimal** [twilio/twilio-video.js#848]
Can someone verify?
Does the package compile down to ES5 ?

"react-scripts": "1.0.17"

**Comment by manjeshbhargav** [comment]
Hi @ashishajimal ,

Thanks for writing in with your issue. I tried the `react-scripts` package version that you mentioned and was able to build the es5 source without any problems. Can you share with me exactly what errors you are seeing?

Also, did you change the version of `react-scripts` after creating your react app? If so, please try removing `node_modules` and `package-lock.json` and running `npm install`. Hope this helps.

Thanks,

Manjesh Malavalli
JSDK Team
