### ISSUE TITLE
Unpublishing and Publishing video track not resuming with JS SDK 1.20 on Chrome.

### ISSUE THREAD

**Issue by gouthamRT** [twilio/twilio-video.js#850]
**Steps to reproduce the issue:**
- Create a peer-peer room, and attach remote participant track coming form app on the browser.
- After the room has been joined, unpublished the video track on the app side.
- Now try republishing the video track on the app side.
- Browser receives a trackSubscribed event after the video is published but never receives any info on the track.

**Expected behavior:**
It would get the new track updated.

**Actual behavior:**
No video on the track is visible.

On the chrome://webrtc-internals
I can notice that there was always a new track created during the previous releases
"RTCMediaStreamTrack_receiver_1 (track)" something of this line.
But in the current SDK nothing of that sort gets created and I am assuming the might be causing the issue.

It works perfectly on Firefox.

**Software versions:**

 - [x] Browser(s): Chrome 79.0.3945.88
 - [x] Operating System: MacOS
 - [x] twilio-video.js:1.20
 - [x] Third-party libraries (e.g., Angular, React, etc.):React yes.

**Comment by manjeshbhargav** [comment]
@gouthamRT ,

We highly recommend that you upgrade to the latest SDK version 2.3.0. Here is a [guide](https://www.twilio.com/docs/video/migrating-1x-2x) on how to migrate from 1.x to 2.x.

Thanks,

Manjesh Malavalli
JSDK Team
