### ISSUE TITLE
Disconnected, then reconnecting and reconnected events for room not firing

### ISSUE THREAD

**Issue by phzio** [twilio/twilio-video.js#854]
There are disconnected events being raised where the remote streams were never interrupted in any way noticeable by the user (perhaps a lost frame or two of video). I'm not sure if these are being falsely emitted.

If a disconnect was detected, it also seems reasonable that the reconnecting and reconnected events should be emitted if the remote streams continue to pass to the participants. Perhaps this is a difference between the websocket server vs. the RTC connection as the RTC connection could be continuing even if the other server becomes unresponsive.

Can you indicate if these disconnects should be ignored or how to detect a "real" problem from a problem that isn't noticeable to participants.

Attached is a console debug log of the events from twilio.js (v.2.0.0):

[js-console-disconnect.txt](https://github.com/twilio/twilio-video.js/files/4055427/js-console-disconnect.txt)

**Comment by manjeshbhargav** [comment]
Hi @phzio ,

Thanks for writing in with your issue. I took a look at our server logs for the Room SID you shared, and it looks like there are quite a few instances where Participants are trying to join the Room with the same identity (string used in creating the AccessToken), which results in the existing Participant with the same identity being "disconnected" from the Room with an error code of [53205](https://www.twilio.com/docs/api/errors/53205).

Please make sure Participants in a Room have unique identities. Please let me know if this helps.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by phzio** [comment]
It was the same participant and they never left the session. I'm not sure why but they were randomly disconnnected and then immediately reconnected. This was not a result of leaving, or changing anything in the connection (add/remove track publications, etc.) that would have triggered it.

**Comment by phzio** [comment]
In fact, I was on the same PC, left the browser windows open and didn't touch anything. It disconnected on it's own and then reconnected.

**Comment by mding5692** [comment]
Had a similar issue with this

**Comment by phzio** [comment]
Issue was my end. I had an auto-restart if no participant connected within 5 minutes (room closes automatically by Twilio). The second participant doesn't get a participantConnected event because the first was already in the room. Sorry for the confusion.
