### ISSUE TITLE
Chromium-based Microsoft Edge support

### ISSUE THREAD

**Issue by alinkedd** [twilio/twilio-video.js#856]
Since today is new Edge release day, it would be great to get support for Chromium-compatible versions in the near future.

**Comment by aymenn** [comment]
Hey @alinkedd, 
Microsoft Edge is supported! Video JS 2.0 runs without any problems. However, we need to make a  change to isSupported so it reports true when run on MS Edge. This will be fixed in 2.0.1. See this for supported browsers https://www.twilio.com/docs/video/javascript#supported-browsers

**Comment by cindyloo** [comment]
hi - is this fixed? It seems isSupported still returns false in 2.23.0
