### ISSUE TITLE
Audio Level event

### ISSUE THREAD

**Issue by lehmannsystems** [twilio/twilio-video.js#862]
This is a simple question... is there a way to detect a change in audio level from a participant's audio track or a local audio track?   Trying to show who all is talking and how loud.

**Comment by manjeshbhargav** [comment]
Hi @lehmannsystems ,

Thanks for writing in with your question. You can use the [Web Audio APIs](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API) to access the raw audio samples. You can then use these samples to calculate an audio level. Please refer to our [QuickStart](https://github.com/twilio/video-quickstart-js/blob/master/examples/util/waveform.js) for an example.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by ume-daniel** [comment]
Hi @manjeshbhargav ,

Following up on this, how resource intensive is to be monitoring the audio levels of a 20-30 users?

Ideally, the twilio api would do the analysis of the mic levels on the client side and combine it with the audio data being sent to twilio, that way all users can receive it with no extra computation.
