### ISSUE TITLE
How to create a Peer-to-Peer connection ?

### ISSUE THREAD

**Issue by enzoferey** [twilio/twilio-video.js#866]
Hi ! 

After reading the docs and looking at the [examples/quickstart](https://github.com/twilio/video-quickstart-js/tree/master), I have found no way to create a Peer-to-Peer room. The REST API [details](https://www.twilio.com/docs/video/api/rooms-resource#post-parameters) a  `type` property on `Room` that can be `peer-to-peer`, but looking at the source code of `twilio-video` I can't find any reference to it.

Thank you for your help :+1:

**Comment by manjeshbhargav** [comment]
Hi @enzoferey ,

Thanks for writing with your question. There are two ways of creating a Peer-to-Peer Room:
1. Go to your [Twilio Console](https://www.twilio.com/console/video/configure) and select Room Type as Peer-to-Peer.
2. You can use the [Programmable Video REST API](https://www.twilio.com/docs/video/api/rooms-resource#create-room) (not part of the SDK) to create a Peer-to-Peer Room. If you don't want to use the raw REST API, you can use this [helper library](https://github.com/twilio/twilio-node).

Thanks,

Manjesh Malavalli
JSDK Team
