### ISSUE TITLE
Android 9 + Chrome Mobile 79 issue

### ISSUE THREAD

**Issue by karls** [twilio/twilio-video.js#871]
Hi Twilio team,

I'm not sure if this is a bug or something else, but we are seeing several users on Android 9 (and one user on Android 8) and Chrome Mobile 79 run into `TwilioError: Client is unable to apply a remote media description`, and thus unable to have their video recorded in a small-group room.

 - [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ ] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Expected behavior:**

Users on Android 9 and Chrome Mobile 79 should be able to have their video recorded in a small-group room.

**Actual behavior:**

Users on Android 9 and Chrome Mobile 79 encounter `TwilioError: Client is unable to apply a remote media description` when they connect to a room.

**Software versions:**

 - [x] Browser(s): Chrome Mobile 79
 - [x] Operating System: Android 9
 - [x] twilio-video.js: 2.0.1
 - [x] Third-party libraries (e.g., Angular, React, etc.): web app Running Svelte 3.18.1, using [hark](https://github.com/otalk/hark) to allow users to optionally verify working microphone.

I can provide the UA strings and/or Room IDs for the problematic recordings if needed.

**Comment by makarandp0** [comment]
Hello @karls, Thank you for reporting this issue. Were you able to repro this issue locally? Can you please share room sids (and client side logs if you have any captured when this issue repros). 

Thanks,
Makarand
JSDK Team

**Comment by karls** [comment]
Hey, thanks for reacting quickly.

I haven't been able to repro this locally because I don't have an Android device available at the moment. I'm hoping I should be able to get a device for testing in the next couple of days.

Two room SIDs where this issue has happened:
- RM76fc116a75d0e5c90aa28d5ac1aa4bb2
- RM6fef9c0221a35d36dcc64d1b7d4ba5c2

Traceback from the app:
```
TwilioError: Client is unable to apply a remote media description

File "../node_modules/twilio-video/es5/util/twilioerror.js" line 37 col 23 in TwilioError
var error = Error.apply(_this, args);

File "../node_modules/twilio-video/es5/util/twilio-video-errors.js" line 1077 col 149 in MediaClientRemoteDescFailedError
return _possibleConstructorReturn(this, (MediaClientRemoteDescFailedError.__proto__ || Object...

File "../node_modules/twilio-video/es5/signaling/v2/peerconnection.js" line 1063 col 15 in value
throw new MediaClientRemoteDescFailedError();
```

Rollbar Telemetry (sorry, I don't think there's a way for me to share this more conveniently):
![image](https://user-images.githubusercontent.com/251402/73687470-cd51fb80-46d2-11ea-95f2-cf82386edc92.png)

**Comment by makarandp0** [comment]
Hi @karls, Looking at those sids, looks like the rooms were created with support only for `H264` codec  and client device in this case did not have support for the codec. 

You can read more about managing codec preferences at https://www.twilio.com/docs/video/managing-codecs

Let me know if that addresses your issue.

**Comment by karls** [comment]
Hey @makarandp0,

Yes, that's right, we're creating all the rooms with only H264 support, because according to the Browser Support table on the Managing Codecs page, it seems that H264 support meets our requirements well. And further, as the MKV and MKA are "transcoded" into a single MP4 as soon as recording finishes and Twilio sends us a webhook, having a H264-encoded MKV as the source is very convenient as the transcoding process takes only a split second.

So, I guess what we didn't anticipate is new-ish device running Android 9 and Chrome 79 not having support for H264.. 

I've just had the user run the test for H264 support outlined on Managing Codecs and the answer is indeed negative — it's not supported on the browser they're using.

Do you know why a recent Chrome might not be shipping with H264 support? Is it down to hardware support and vendor decisions?

Thanks for bearing with me through this.

**Comment by karls** [comment]
Let's close this issue. I think we got to the bottom of this. The user has a fairly old Huawei phone, which seems to not support H264.

We're going to do some more work on our end to support our use case.

Thanks!
