### ISSUE TITLE
Could not connect to Twilio: Signaling connection error

### ISSUE THREAD

**Issue by divya-kanak** [twilio/twilio-video.js#876]
Hello folks, 

I am trying to make the connection between chrome (v - 67) and chrome (v- 79), at the time got the error like:

` WebSocket connection to 'wss://global.vss.twilio.com/signaling' failed: Error in connection establishment: net:: ERR_SOCKS_CONNECTION_FAILED`

I have attached the video link here. please check out and let me help out for this.

Chrome (v-79) : connection is successfully. 
check below url- [https://drive.google.com/file/d/1aVsRhDEmp7q1atAwMcbh9L_bPv-iiqNA/view](https://drive.google.com/file/d/1aVsRhDEmp7q1atAwMcbh9L_bPv-iiqNA/view)

Chrome(v-67): Could not connect to Twilio: Signaling connection error
check URL: [https://drive.google.com/file/d/1TbGaJ_aSyfswTGOXA-8Sw1u_s_skBH-C/view](https://drive.google.com/file/d/1TbGaJ_aSyfswTGOXA-8Sw1u_s_skBH-C/view)

I have added below option in `connectOptions` 

`const connectOptions = {
  _useTwilioConnection: true
};`

But I have faced the same issue. I have created an Http tunnel. So, If you want to check this feature using my end. 
please hit this link: [https://b256e195.ngrok.io ](https://b256e195.ngrok.io ) 

 - [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

```js
Video.connect(data.token, connectOptions).then(roomJoined, function (error) {
      alert("Video connect error part");
      console.log(error);
      log('Could not connect to Twilio: ' + error.message);
    });
```

**Expected behavior:**

Need to work on both sides.

**Actual behavior:**

The connection could not establish in chrome (v-67)

**Software versions:**

 - [x] Browser(s): Chrome(v-79), Chrome(v-67) (not working), Chrome(v-75) (not working)
 - [x] Operating System: window 10
 - [x] twilio-video.js: we have migrate from 1.x to 2.x
 - [x] Third-party libraries (e.g., Angular, React, etc.): Angular js

**Comment by mding5692** [comment]
I have the same error message in my console:

`WebSocket connection to 'wss://endpoint.twilio.com/' failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT`

Is this because I need to upgrade my Chrome browser or that I need to upgrade the twilio-video version like in this issue #576 or #289 ?

**Comment by mding5692** [comment]
Ok, this finally worked @divya-kanak 

I updated my Twilio-node library to v3.39.5 and videochat worked again.

**Comment by makarandp0** [comment]
Hello @divya-kanak, sorry for the late response. 

Are you still seeing this issue ? Is this limited to Chrome v-67 or do you see it in other browsers/versions as well ? Can you please reopen that https tunnel, and I can take a look into it. 

BTW Re: `_useTwilioConnection` - this property is not necessary. its not used by the SDK anymore.

**Comment by meness** [comment]
Configure CSP (Content Security Policy) to allow Twilio.
