### ISSUE TITLE
trackDisabled and trackEnabled events emited by Room provide wrong parameter type

### ISSUE THREAD

**Issue by milost1982** [twilio/twilio-video.js#877]
In docs for twilio video v2.0.0:
https://media.twiliocdn.com/sdk/js/video/releases/2.0.0/docs/Room.html#event:trackDisabled__anchor
https://media.twiliocdn.com/sdk/js/video/releases/2.0.0/docs/Room.html#event:trackEnabled__anchor

it says that trackDisabled and trackEnabled events provide parameter **track** of type **RemoteTrack**

In my application what I actually get for this **track** parameter is that they are of type **RemoteTrackPublication** (eg. RemoteVideoTrackPublication).

Please fix the docs or code, whichever is more appropriate thing to do.

**Comment by manjeshbhargav** [comment]
Hi @milost1982 ,

Thanks for bringing this to our attention. We will investigate and do the needful.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by manjeshbhargav** [comment]
Hi @milost1982 ,

The fix for this issue is available in v2.2.0's [documentation](http://media.twiliocdn.com/sdk/js/video/releases/2.2.0/docs/Room.html#event:trackDisabled__anchor). I'm closing this issue.

Thanks,

Manjesh Malavalli
JSDK Team
