### ISSUE TITLE
limits

### ISSUE THREAD

**Issue by spike99** [twilio/twilio-video.js#885]
I want to limit calls to a maximum of 5 minutes
how can i do this?

**Comment by manjeshbhargav** [comment]
Hi @spike99 ,

You can use the [Programmable Video REST API](https://www.twilio.com/docs/video/api/rooms-resource) to create and close down a Room from your application server. That way you can limit the life-cycle of the Room.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by spike99** [comment]
and how can I do that?
which is the js code to limit up to 5 minutes
