### ISSUE TITLE
Question about logging

### ISSUE THREAD

**Issue by thenorthstarblues** [twilio/twilio-video.js#887]
Hello,

I'm trying to find a way to collect logs from the Programmable Video SDK so that I can better debug occasional issues connecting to rooms. I'd like to be able to see logging from user devices in our production environment. The issue is that in our production environment we use a custom logger to send logs to a service instead of outputting them to the console, but this doesn't include Twilio's logs. 

I've seen some SDKs that accept a custom logger from their consumer in order to enable this type of behavior, but I don't believe that the Programmable Video SDK has that capability. 

Another possibility that occurred to me was to override the various `console` methods in the browser to intercept logging from Twilio, but that doesn't quite work either. I've created an example using the video-quickstart [here](https://github.com/thenorthstarblues/video-quickstart-js) that shows what I'm trying to do. I override the browser's `console.log` method to use the `log` function which was already provided by the quickstart. I replace the calls to `log` with regular `console.log`s, and we continue to see those message displayed in the UI as before. However, the log messages from the SDK are printed to the console.

I think I know why this is happening, so I'm happy to submit a PR if this is a behavior that you are interested in supporting. I understand this is a bit of an unusual case however, so if you'd like to suggest a different approach it would be much appreciated.

Thanks for the help!

**Comment by makarandp0** [comment]
Hey @thenorthstarblues - Thank you for your suggestion. We have seen this feature request [before](https://github.com/twilio/twilio-video.js/issues/650) and have a item tracking this - we will try to get to it soon.  

I like your idea for the workaround - You would also need to override few other methods (console.error, console.info, console.warn), and may get into other issues since our usage of console.log function is bit unusual - we call it with  `fn.apply(console, args)` [here](https://github.com/twilio/twilio-video.js/blob/master/lib/util/log.js#L126).

**Comment by thenorthstarblues** [comment]
Hi @makarandp0, thanks for the quick response! I've looked at the code in `log.js`, and I think the reason that my solution won't work is because of how the `_levels` property is defined. The various `logFn` methods are defined with their corresponding `console` statements, so what those functions do will not be changed even if we later override the global `console` object. Attaching a screenshot that demonstrates what I'm talking about.

I've also added a commit to the Programmable Video SDK that would enable the kind of thing I'm trying to do and you can check it out [here](https://github.com/thenorthstarblues/twilio-video.js/commit/f7502df4562376011d6d4db120035570e81cfce5). If this is something that you would be interested in supporting I am happy to send a PR.

Thanks again!
![Screen Shot 2020-02-13 at 3 36 07 PM](https://user-images.githubusercontent.com/10489589/74489074-ffa0ed00-4e78-11ea-8fb1-d640ba8dda3e.png)

**Comment by makarandp0** [comment]
Thanks again @thenorthstarblues, 

I see the issue, but I think you can workaround it by  overriding `console.log` before our SDK gets chance to cache the console.xxx functions.

for example:
```
window.console.log = function(msg) { return "hi:" +  msg; }
var log = { fn: console.log };
log.fn.apply(console, ["twilio"]);
```
works the way you want. You can override console.log before including twilio SDK in your code, something like:
```
window.console.log = function(msg) { 
   return "hi:" +  msg; 
}
const video = require('twilio-video');
```
does that work for you? By the way I will definitely push for this feature to enable customizable logger with our SDK very soon, and will keep you posted.

Thanks,
Makarand

**Comment by thenorthstarblues** [comment]
Hey @makarandp0,

Thanks for the help. It would definitely work if I were to override the functions before importing the SDK. Our setup right now makes it a little tricky, but we could make it work. I'll keep an eye out for the customizable logger. Thanks again!
