### ISSUE TITLE
Expose maxReconnectAttempts as a configuration option

### ISSUE THREAD

**Issue by amok** [twilio/twilio-video.js#896]
It looks like `maxReconnectAttempts` configuration is hardcoded https://github.com/twilio/twilio-video.js/blob/9d9d7a63434f28cb4090861d96250e1ef7103a0a/lib/signaling/v2/twilioconnectiontransport.js#L24-L26 and I haven't found any straightforward way to overwrite it.
If such a way exists - please share the docs-link and excuse for inattention. Otherwise I would suggest to expose hardcoded vars as a Twilio connect options.

**Comment by makarandp0** [comment]
Thank you @amok for your suggestion. Yes, `maxReconnectAttempts` is not configurable. we do have a work item in our backlog to fine tune this value (JSDK-2393). We also want to look into total time in reconnection attempts (instead of just number of attempts) 
 
Can you elaborate on what value do you want to set for this? Are you seeing many connections failing after 5 attempts  ? What was the reason for failures ?   

Thanks,
Makarand

**Comment by amok** [comment]
The use-case is the following:
1. User goes offline (f.e disable wi-fi, restarting wi-fi router)
2. Twilio tries to reconnect
3. After a few seconds it throws error on `reconnecting` event.
4. User goes online in a minute or so but Twilio connection has already been lost.

Our need is to increase number of reconnection attempts and delay between them.
The simplest example would be:
1. Open twilio-video session on mobile.
2. Disable wi-fi and enable it right away.
3. Sometimes connection gets lost even before phone establishes wi-fi connection back.

@makarandp0 let me know if you need more info.

**Comment by makarandp0** [comment]
Thank you for the additional information @amok.
I think we are mainly looking at updating this logic from "reconnect for 5 attempts"
 to more like "try reconnecting for 30 seconds" before giving up. And looks like in your case you want this value 30 seconds configurable - Would that work for you ? We will definitely look into this further.  

In the meanwhile you can workaround this limitation by wrapping connect into multiple attempts version in your code.

```
function customConnect(token, options, numAttempts = 3) {
  return Video.connect(token, options).catch(error => {
    if (numAttempts === 0) {
      throw error;
    }
    return customConnect(numAttempts - 1);
  });
}
``` 

What do you think?
Thanks,
Makarand

**Comment by amok** [comment]
> Would that work for you 
That would be great. Thanks

And thank you for the code tip - I was thinking about similar implementation but was suspicious that it will not work due to some internal encapsulated logic (otherwise why would you implement reconnecting support on a lib level - that was my thought).
