### ISSUE TITLE
SDK 1.x error: JSON.stringify cannot serialize cyclic structures

### ISSUE THREAD

**Issue by matthensley** [twilio/twilio-video.js#908]
With the 1.x version of the SDK, we have had occasional "JSON.stringify cannot serialize cyclic structures" errors. These were traced back to the package **@twilio/sip.js** in **Transport.js**.

Turns out **@twilio/sip.js** is a re-publishing of **sip.js**. The original package fixed this issue already:
https://github.com/onsip/SIP.js/commit/d9bf3ef8335a95a3f1d61dc0cb67dee6bccb52df#diff-8825bca693c55fe320921b6ff4ff85b1

Looks the fix was published in version **0.8.0** of the original package, however the Twilio version of the package is only at **0.7.7**.

**Comment by makarandp0** [comment]
Hello @matthensley  Thank you so much for notifying us about this issue. I have filed an internal bug to track this issue now (JSDK-2719). Can you give us some repro that help reproduce this stringify error ? 
 
Thanks,
Makarand

**Comment by matthensley** [comment]
Unfortunately we have only seen this issue in the wild and have been unable to reproduce intentionally. Anecdotally, the only common factor is a participant running Safari.

**Comment by makarandp0** [comment]
closing this old issue in 1.x version that we are not updating anymore. Please update to 2.x following this [guide](https://www.twilio.com/docs/video/migrating-1x-2x)
