### ISSUE TITLE
iOS safari is getting publication.isSubscribed as null and tracks as null

### ISSUE THREAD

**Issue by pchvramesh** [twilio/twilio-video.js#911]
I'm using "twilio-video": "2.1.0" in our application.
We are begin to support ios mobiles in our project. But for ios safari we are getting publication.isSubscribed as null and tracks as null. I have tried many solutions by checking the previous issues, but none got success. 
I have provided the complete code block that we are using in our application.

 - [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

```js
connectTOMeeting(res) {
    const self = this;
    connect(res['token'], { name: 'room' + this.params.meeting_id, audio: true, video: true , logLevel: 'info'})
      .then(room => {
        this.room = room;
        room.participants.forEach(self.participantConnected);
        room.on('participantConnected', self.participantConnected);
        room.on('participantDisconnected', self.participantDisconnected);
        room.once('disconnected', error => room.participants.forEach(self.participantDisconnected));
        this.initLocalVideo();
      })
      .catch(error => {
        console.log(error);
      });
  }

  participantConnected = (participant) => {
    console.log('Participant "%s" connected', participant.identity);
    const identity = parseInt(participant.identity, 10);

    const div = document.createElement('div');
    div.id = participant.sid;

    participant.on('trackSubscribed', track => this.trackSubscribed(div, track));
    participant.on('trackUnsubscribed', this.trackUnsubscribed);

    participant.tracks.forEach(publication => {
      if (publication.isSubscribed) {
        this.trackSubscribed(div, publication.track);
      }

    publication.on('subscribed', function(track) {
        console.log('Publication subscribe') 
       /* This line is firing in chrome, and safari desktop but not on safari ios*/
      });
      publication.on('unsubscribed', ()=>{
        console.log('Publocation unsubscribe')
      });
    });

    document.getElementById('twilio').appendChild(div);
  };

  participantDisconnected = (participant) => {
    console.log('Participant "%s" disconnected', participant.identity);
    document.getElementById(participant.sid).remove();
    this.endCall();
  };

  trackSubscribed = (div, track) => {
    div.appendChild(track.attach());
  };

  trackUnsubscribed = (track) => {
    track.detach().forEach(element => element.remove());
  };
```
### Log 
[Info] 2020-03-18 – "09:58:37.345Z" – "|" – "INFO" – "in" – "[Room #1: RMd3405b0acfebef035489cd6a9416eaf2]:" – "A new RemoteParticipant connected:" – RemoteParticipant {_events: Object, _eventsCount: 1, _maxListeners: undefined, …} (dashboards-shared-video-calls-video-calls-module.js, line 24300)
RemoteParticipant {_events: Object, _eventsCount: 1, _maxListeners: undefined, _audioTracks: Map, _dataTracks: Map, …}RemoteParticipant_RemoteAudioTrack: function(sid, mediaTrackReceiver, isEnabled, setPriority, options)_RemoteAudioTrackPublication: function(signaling, options)_RemoteDataTrack: function(sid, dataTrackReceiver, options)_RemoteDataTrackPublication: function(signaling, options)_RemoteVideoTrack: function(sid, mediaTrackReceiver, isEnabled, setPriority, options)_RemoteVideoTrackPublication: function(signaling, options)_audioTracks: Map {}Map (0)_dataTracks: Map {}Map (0)_events: {disconnected: Array, trackSubscribed: Array, trackUnsubscribed: Array, reconnected: function, reconnecting: function, …}Object_eventsCount: 16_instanceId: 2_log: Log {_component: RemoteParticipant, _logLevels: Object, _warnings: Set, name: "[RemoteParticipant #2: PA463389bfdb6e00c54745cfcb51961033]"}Log_maxListeners: undefined_signaling: RemoteParticipantV2 {_events: Object, _eventsCount: 4, _maxListeners: undefined, _reachableStates: Map, …}RemoteParticipantV2_trackEventReemitters: Map {}Map (0)_trackPublicationEventReemitters: Map {"MTe1ddcd39b4dfb179528a0e7fe01ab1a5" => Map {"subscriptionFailed" => function, "trackDisabled" => function, "trackEnabled" => function, "publishPriorityChanged" => function, "trackSwitchedOff" => function, …}, "MTc0b590acc0b733fbe6529f4b7670de23" => Map {"subscriptionFailed" => function, "trackDisabled" => function, "trackEnabled" => function, "publishPriorityChanged" => function, "trackSwitchedOff" => function, …}}Map (2)_trackSignalingUpdatedEventCallbacks: Map {"MTe1ddcd39b4dfb179528a0e7fe01ab1a5" => function, "MTc0b590acc0b733fbe6529f4b7670de23" => function}Map (2)_tracks: Map {}Map (0)_videoTracks: Map {}Map (0)audioTracks: Map {"MTc0b590acc0b733fbe6529f4b7670de23" => RemoteAudioTrackPublication {_events: Object, _eventsCount: 6, _maxListeners: undefined, _instanceId: 3, _log: Log, …}}Map (1)dataTracks: Map {}Map (0)identity: networkQualityLevel: networkQualityStats: sid: state: tracks: Map {"MTe1ddcd39b4dfb179528a0e7fe01ab1a5" => RemoteVideoTrackPublication {_events: Object, _eventsCount: 6, _maxListeners: undefined, _instanceId: 2, _log: Log, …}, "MTc0b590acc0b733fbe6529f4b7670de23" => RemoteAudioTrackPublication {_events: Object, _eventsCount: 6, _maxListeners: undefined, _instanceId: 3, _log: Log, …}}Map (2)videoTracks: Map {"MTe1ddcd39b4dfb179528a0e7fe01ab1a5" => RemoteVideoTrackPublication {_events: Object, _eventsCount: 6, _maxListeners: undefined, _instanceId: 2, _log: Log, …}}Map (1)RemoteParticipant Prototype

**Software versions:**

 - [x] Browser(s): Safari 13.3.1
 - [x] Operating System: iOS 13.3.1
 - [x] twilio-video.js: 2.1.0
 - [x] Third-party libraries (e.g., Angular, React, etc.): Angular 6

**Comment by pchvramesh** [comment]
I Resolved this issue by my self.
I have added the below lines to my polyfills.ts in angular project

```
import 'zone.js/dist/zone-patch-user-media';
import 'zone.js/dist/webapis-rtc-peer-connection';
```

It worked great.

**Comment by tinncdev** [comment]
> I Resolved this issue by my self.
> I have added the below lines to my polyfills.ts in angular project
> 
> ```
> import 'zone.js/dist/zone-patch-user-media';
> import 'zone.js/dist/webapis-rtc-peer-connection';
> ```
> 
> It worked great.

Also fix my case that `RemoteVideoTrackPublication` does not fire `subscribed` event on iOS Safari
