### ISSUE TITLE
beta7 - Internet Explorer can't connect to a room.

### ISSUE THREAD

**Issue by drbeermann** [twilio/twilio-video.js#92]
I *believe* that IE is supported, at least recent versions, but we aren't able to connect. I haven't had a chance to dig into this very far, but we're getting the following error:

```
Error while connecting to a Room: TypeError: Object doesn't support this action
```

Should this in fact work? Thanks,

Dale

**Comment by markandrus** [comment]
Hi @drbeermann,

We do not support IE, as it does not support WebRTC. In the future, we will support Edge; however, we have not begun that work yet.

Mark

**Comment by drbeermann** [comment]
Thanks Mark, I appreciate the quick feedback. I assumed that things were partly working because the video showed up, but it isn't a big deal for us.

Dale
