### ISSUE TITLE
Media connection failed or Media activity ceased for Video.connect

### ISSUE THREAD

**Issue by kubasolecki** [twilio/twilio-video.js#925]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) - **does not work on my envirenment**
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

```js
      cordova.plugins.permissions.permissions.requestPermission(
        this.permissions.CAMERA,
        (status) => {
          if (!status.hasPermission) {
            return this.log('false');
          }
          Video.connect(this.$store.getters['video/token'], {
            name: this.name,
            audio: false,
            video: true,
          }).then(
            (room) => {
              this.log('success');
            },
            (err) => this.log(err.message),
          );
        },
      );
```

**Expected behavior:**
After accessing camera should successfully connect to room and in my case call `this.log('success')`

**Actual behavior:**

`this.log(err.message)` getting called and fallowing error message appears:
`Media connection failed or Media activity ceased`

`createLocalVideoTrack` method works perfectly, properly accesing the video stream and return video track. I am having problems only with connect method

**Software versions:**

 - [ ] Browser(s):
 - [x] Operating System: Android
 - [x] twilio-video.js:
 - [x] Cordova android 8.1.0, Quasar v. 1.9.6, Vue 2.6.11

**Comment by makarandp0** [comment]
Thank you for writing about this issue @kubasolecki. 
From the error text looks like the SDK failed to create a PeerConnection.

Few questions:
which version of twilio-video.js are you using?
which version of browser ?
Can you share logs from the browser ?  
Also please verify that the browser is supported by checking property `Video.isSupported`

Thanks,
Makarand (JSDK Team)

**Comment by kubasolecki** [comment]
Thank you for your answer @makarandp0.
I am using `twilio-video 2.3.0,`. 
I am not using the browser. I am using Apache Cordova platform to compile and run the application on mobile.
Here are the error log: 
```js
{
"stack":"TwilioError: Media connection failed or Media activity ceased\n at MediaConnectionError.TwilioError (webpack-internal:///./node_modules/twilio-video/es5/util/twilioerror.js:37:23)\n at new MediaConnectionError (webpack-internal:///./node_modules/twilio-video/es5/util/twilio-video-errors.js:1146:125)\n at PeerConnectionManager._getOrCreate (webpack-internal:///./node_modules/twilio-video/es5/signaling/v2/peerconnectionmanager.js:200:17)\n at eval (webpack-internal:///./node_modules/twilio-video/es5/signaling/v2/peerconnectionmanager.js:272:23)",
"message":"Media connection failed or Media activity ceased",
"code":53405,
"name":"TwilioError"
}
```
`Video.isSupported` returns `true`

**Comment by makarandp0** [comment]
Thanks for the update @kubasolecki.  Currently Twilio-Video is not supported on Apache Cordova platform.

**Comment by guevaraf** [comment]
I think we need to re-open this as I have the same issue in Chrome (Version 105.0.5195.102 (Official Build) (x86_64)) on MacOS.
ERROR: Media connection failed or Media activity ceased TwilioError: Media connection failed or Media activity ceased
    at t [as constructor] (twilioerror.js:20:25)
    at new t (twilio-video-errors.js:898:5)
    at t._getOrCreate (peerconnectionmanager.js:190:15)
    at peerconnectionmanager.js:249:19
twilioerror.js:17 Uncaught (in promise) TwilioError: Media connection failed or Media activity ceased
    at t [as constructor] (twilioerror.js:20:25)
    at new t (twilio-video-errors.js:898:5)
    at t._getOrCreate (peerconnectionmanager.js:190:15)
    at peerconnectionmanager.js:249:19

**Comment by domenkralj** [comment]
Me too.
I am using the lastest react SKD version.

**Comment by vipulSoni458** [comment]
We are also facing the same issue on MacOs Chrome (114.0.0.0), it keeps getting Media connection failed or Media activity ceased error
