### ISSUE TITLE
Is there any way to switch from video to voice and back to video?

### ISSUE THREAD

**Issue by stephanoparaskeva** [twilio/twilio-video.js#928]
On mobile, I want my users to be able to switch from voice calling to video calling at their leisure. Both voice and video are 1-to-1. This is not for phone calls, it's for audio/video calling 1-to-1 over wifi. 

Also I'm using pusher as a notification service, is there any way to send notifications of the incoming call and have the user connect to the call by just tapping the notification?

Thank you

**Comment by manjeshbhargav** [comment]
Hi @stephanoparaskeva ,

Sorry for the delayed response. If your voice calls are also between 2 instances of your application on different devices, and not for phone calls, then you can indeed use the SDK to join a Room with audio only initially, and then later add video when the user wants. You can send a unique URL to your meeting in the notification, and when the user clicks on it, they should be able to join the Room. It is totally up to the application to manage how people join the video Room.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by stephanoparaskeva** [comment]
@manjeshbhargav What if you want audio and video, but you want it to be like a call. So it is not a phonecall. It is not a group call. But it is 1 mobile device, that calls another device.. with a notification that rings. The second user connects and the two have a 1-to-1 audio call, can they turn video on just by tapping a button so that it can display their face. IE on android/IOS/react native to switch between?

When this call ends am I right in thinking that twillio then sends a request to an api url that you provide with data about the call?

**Comment by manjeshbhargav** [comment]
@stephanoparaskeva ,

You could build something like a WhatsApp audio call, and later add video to it using the Video SDK. But the calling and notification mechanism is not in scope for the SDK, and it has to be built by the application.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by stephanoparaskeva** [comment]
@manjeshbhargav 
Ah, I see. but my question is that: Can a notification system be built for handling mobile-to-mobile voice calls that can switch to audio just like whatsapp while using the Twillio voice and video SDK, using something like AWS appsync, can notifications for twilio voice and video work or will it have to involve URL's and adding users to groups etc?

**Comment by manjeshbhargav** [comment]
@stephanoparaskeva ,

As I said earlier, the Video SDK will allow you to establish webapp-to-webapp voice and/or video connections. Since you would be building a web app with the JS SDK, you would have to send a unique URL to the other side either by text/sms or build some kind of login system where you can send push notifications from your app server. In either case, it would have to be implemented by the application.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by stephanoparaskeva** [comment]
@manjeshbhargav  No, not a web app. A mobile app using react native. Is there a difference in that regard?

**Comment by manjeshbhargav** [comment]
@stephanoparaskeva ,

Oh ok. You won't be able to use the JS SDK directly there. You would have to use our iOS and Android SDKs then and build a React Native bridge to the JS layer. In that case, you should have access to the native notifications api, which you can use to invite people to join a Room.

Thanks,

Manjesh Malavalli
JSDK Team
