### ISSUE TITLE
Missing Documentation for JQuery, Plain JavaScript. 

### ISSUE THREAD

**Issue by hpandroid** [twilio/twilio-video.js#929]
Hi,
The official documentation does not have any example for implementation in jQuery or plain JavaScript. We do not use Node for our projects, we were using V1.X in our current Video Chatting Integration.

Now In V2.X it has more feature like reconnecting, Remote and Local Participants, etc.

We were trying to upgrade to V2.x and Review the Quickstart guid and multi chart room video both are based on NPM and React but not in plain JS.

Even we have reviewed all Twilio JS API documentation which is only defined in NPM.

Only thing we found is 
<script src="//media.twiliocdn.com/sdk/js/video/releases/2.3.0/twilio-video.min.js"></script>
const Video = Twilio.Video;

Apart from this there is not even a single example given about connections and event handling.

We are able to connect based on the old version implementation with connection options but we are not receiving any participants events like tracks published, unpublished, subscribed, unsubscribed.

In iPhone or iPad Safari Browser is not prompting the users to allow the access to to devices while crating the tracks which is working other browsers properly. As a workaround we did  

if (navigator.mediaDevices.getUserMedia) {                            
                            navigator.mediaDevices.getUserMedia({ audio: true, video: true });
                            setTimeout(CreateLocalTracks, 3000);
                        }
If user minimize the browser in mobile video stream is not triggering videoUnpublished. So on remote end it is showing a blank screen. 

If we are not looking at proper documentation please direct us to wards the plain JS examples.

I did worked on both mobile native platforms using iOS and Android SDKs, all the events were trigging properly based on the delegates and Event Listeners.

In Twilio Access token documentation it says by default the token will be valid for 4 hours but it is expiring with in an hour. it is referring to TTL value but I do not see any property to provide at the time of Generating a token apart form Grants and identity. It would be really nice if you can include participant identity and Name separately. 

Do we have set TTL from client side? are we missing anything here?

 - [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

TODO

**Software versions:**

 - [x] Browser(s): All Browsers events not trigging
 - [x] Operating System: All OS(Windows, Mac, iOS, Safari)
 - [x] twilio-video.js: 1.X and 2.X
 - [x] Third-party libraries (e.g., Angular, React, etc.): None

Thanks,
Harry

**Comment by makarandp0** [comment]
Hey @hpandroid, Thank you for writing. 

You are right that our [samples](https://github.com/twilio/video-quickstart-js) use npm for dependency management, but they are written in plain javascript otherwise. You should be able to follow the same code in your javascript or jquery app. 

The events have changed from 1.x to 2.x - You can read more about the changes at https://www.twilio.com/docs/video/migrating-1x-2x#whats-new
Please checkout the [quickstart](https://github.com/twilio/video-quickstart-js/tree/master/quickstart) sample to see the events in action.

about `ttl` for the access tokens. I think the default value is 1 hour,  The code to generate access token typically lives on your server. And yes, you should be able to set the ttl when generating access token. It is [recommended](https://www.twilio.com/docs/video/tutorials/user-identity-access-tokens#time-to-live) that you set it to 4 hours when creating a token. 

Thanks,
Makarand

**Comment by gabomontero89** [comment]
Hey @makarandp0 

I am using this config to create a new access token `MAX_ALLOWED_SESSION_DURATION: 14400`:
```
const newToken = new AccessToken(
    process.env.TWILIO_ACCOUNT_SID,
    process.env.TWILIO_API_KEY_SID,
    process.env.TWILIO_API_KEY_SECRET,
    { ttl: process.env.MAX_ALLOWED_SESSION_DURATION }
);
```
...but, decoding the token at `https://jwt.io` it show the `ttl` as `30s`.

I am doing something wrong? 
Thanks.

**Comment by makarandp0** [comment]
Hello @gabomontero89, 

what value have you set for `process.env.MAX_ALLOWED_SESSION_DURATION` ? This value needs to be in seconds and the maximum you can set is `14400` (i.e 4 hours)

let me know if that helps,
thanks,
Makarand

**Comment by gabomontero89** [comment]
Hi @makarandp0,
thanks for taking the time to assist me with this.

I set the value to `14400`, but now the token always gets a 1h difference, so after trying with different values I decided to remove the TTL config from the setup and keep the 1h difference that the token gets by default.

Thanks once again for your help.
Regards.

**Comment by razbakov** [comment]
@makarandp0 You refered [quickstart](https://github.com/twilio/video-quickstart-js/tree/master/quickstart). What does `public` and `src` mean? All js are in src folder, shouldn't it be public?

**Comment by makarandp0** [comment]
@razbakov 
Thank you for your question, 

During build process, src/**.js get compiled into a public/index.js 

try running: 
```
npm install
npm run build:quickstart
```  
and you will see `quickstart/public/index.js` being generated.
