### ISSUE TITLE
Cannot iterate over participant tracks

### ISSUE THREAD

**Issue by LuanGarrido89** [twilio/twilio-video.js#930]
Im facing the problem I cannot iterate over a participant tracks after it joins the room.

```
Twilio.Video.connect(token, connectOptions).then(function(room){
    			
    console.log("Room created: " + room.name);
    			
    			room.participants.forEach(function(participant){
    			
    				console.log("Already in room: " + participant.identity);
    				
    				console.log(participant.tracks);
    				
    				console.log(participant.tracks.values());
    			})
    			
    			room.on('participantConnected', function(participant) {
    			
    				console.log("Joining: '" + participant.identity + "'");
    			
    				console.log(participant.tracks);
    				
    				console.log(participant.tracks.values());
    			});
    			
    }).catch(function(error){

    console.log(error);
})

```

When I take a look at participant.tracks, it point to a 0 length map, with 2 values. See below image:

![image](https://user-images.githubusercontent.com/62933366/78008397-fdee9400-7315-11ea-889d-bf3fea366e35.png)

Im using only Javascript SDK 2.x, and Im testint using a desktop chrome 79+ version and a chrome from an android device 80+ version.

Im not beign able to add remote tracks, because I cannot get them from the _participant.tracks_ maps.

Can someone help me ?

Thanks

**Comment by manjeshbhargav** [comment]
Hi @LuanGarrido89 ,

Thanks for writing in with your issue. Are you sure you are using the 2.x SDK? It looks like `participant.tracks()` is a Map of RemoteTracks, which is the case in a 1.x SDK. In 2.x it should be a Map of RemoteTrackPublications. Please let me know.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by LuanGarrido89** [comment]
Hello @manjeshbhargav 

You were right.

Thanks man =)

**Comment by manjeshbhargav** [comment]
@LuanGarrido89 ,

Happy to have helped. Take care and stay safe!

Manjesh Malavalli
JSDK Team
