### ISSUE TITLE
Unable to set correct aspect ratio for iOS camera

### ISSUE THREAD

**Issue by lazevedo** [twilio/twilio-video.js#936]
I've been trying to setup a ReactJS component for a room with two participants. I'm using the connection code below:

```
Video.connect((props.token), {
  name: props.roomName,
  maxAudioBitrate: 16000, //For music remove this line
  video: { width: 640, height: 480, frameRate: 24 },
  bandwidthProfile: {
    video: {
      // mode: 'grid', // tried with this enabled and disabled too
      maxSubscriptionBitrate: 2500000,
      maxTracks: 4,
      renderDimensions: {
        high: { width: 640, height: 480 },
        standard: { width: 320, height: 240 },
        low: { width: 320, height: 240 },
      }
    }
}
```
But regardless of the values I use for the renderDimensions and video objects, the aspect ration of the camera on iOS is alway of a vertical video. How can I make it work for a horizontal 4:3 aspect ratio?

 - [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ ] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Comment by manjeshbhargav** [comment]
Hi @lazevedo ,

On mobile browsers, the devices invert the aspect ratio that you specify in portrait mode. So, I don't think there is a way to maintain your desktop/landscape aspect ratio in portrait mode.

Thanks,

Manjesh Malavalli
JSDK Team
