### ISSUE TITLE
Pause screenshare in a frozen state

### ISSUE THREAD

**Issue by katranci** [twilio/twilio-video.js#937]
Hey team,

We're working on the ability to pause screenshare and the requirement is that the subscribers should see a frozen video (instead of a black frame) when screenshare is paused.

I've done a little implementation using canvas where I capture the local video frame using CanvasRenderingContext2D.drawImage(), then turning that into a stream with HTMLCanvasElement.captureStream(), and finally publishing the stream in Twilio video room (see my code below)

I can see the captured frame when I test the resulting stream on the publisher side by connecting it to a video element. However, when the stream is published in Twilio video room, it doesn't load on the subscriber side and they see this instead:

![image](https://user-images.githubusercontent.com/61077/78374188-33c0a080-75d4-11ea-89b2-8b071937d108.png)

Can you spot anything wrong in my code? Is there a limitation in Twilio regarding canvas streams?

Many thanks

```js
sendLastFrameImageToParticipants () {
  const screenshareTrack = this.videoRoom.findLocalTrack('screenshare')
  const videoElement = screenshareTrack.attach()
  const { aspectRatio } = screenshareTrack.mediaStreamTrack.getSettings()
  const height = 720
  const width = height * aspectRatio

  const canvas = document.createElement('canvas')
  canvas.width = width
  canvas.height = height

  const captureFrame = () => {
    const context = canvas.getContext('2d')
    context.drawImage(videoElement, 0, 0)
    const stream = canvas.captureStream()
    this.videoRoom.publishPausedScreenshare(stream)
    videoElement.removeEventListener('resize', captureFrame)
  }

  videoElement.addEventListener('resize', captureFrame)
}
```

**Comment by manjeshbhargav** [comment]
Hi @katranci ,

Twilio Video does not differentiate between canvas streams and regular streams. However, have you tried using DataTracks to transmit the paused screen share video frame? That way, you can then create a canvas element on the subscriber side and render the paused frame instead of publishing a separate stream.

Please let me know if that works for you.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by katranci** [comment]
Thanks for your reply @manjeshbhargav,

I initially started an implementation using data tracks but abandoned the idea because:
- The image size (150kb) is much larger than the max size allowed in a single data track message (16kb). This means I need to add instrumentation to split it into chunks and combine them on the receiver side.
- I would need to send the image to any new participant joined after screenshare is paused. This is handled out of the box in video streams.

I managed to make the canvas stream work by redrawing the same image on the canvas on an interval basis. However, I hit a new problem with the video quality. Most of the time, the video arrives in very low resolution and it takes a long time to reach its full dimensions.

Here is the publisher log showing track dimensions as 1728x1080
![image](https://user-images.githubusercontent.com/61077/78657085-f0667a80-78d0-11ea-8fc3-98bd2e5fb55f.png)

Here is the subscriber logs
![image](https://user-images.githubusercontent.com/61077/78657200-168c1a80-78d1-11ea-8da7-9d9021ed6d18.png)

Is there a way to force Twilio to deliver the video in high resolution in the first place?

**Comment by manjeshbhargav** [comment]
Hi @katranci ,

Sorry for the delayed response. Unfortunately, these resolution changes happen at the WebRTC level due to bandwidth management algorithms downsampling the video resolution. I am curious though, were you able to work around this issue since our last chat? I'm going to close this issue, but we can continue our discussion here.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by katranci** [comment]
Thanks for your response @manjeshbhargav. I think we will put the feature live and see what the feedback is like.
