### ISSUE TITLE
Mobile Safari 13.0.5 not sending Audio

### ISSUE THREAD

**Issue by rkiller** [twilio/twilio-video.js#938]
I am not sure whether this is related to all the other audio bugs but we have this library in production and our clients fail nearly 100% of the time when one of client is using it from an iPhone with Mobile Safari 13.0.5. 

All other clients work as expected so I am assuming this is an issue with Twilio-video.js and/or webrtc implementation on iPhone. 

Posting this here in case others are searching for resolution on this bug. Tried all workarounds to no avail. This is an extremely critical issue at this time as you can imagine (COVID19 related spike in utilization). Hopefully Twilio can resolve this ASAP. 

 - [ ] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [ ] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ ] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [ ] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

```js
// TODO
```

**Expected behavior:**

TODO

**Actual behavior:**

TODO

**Software versions:**

 - [ ] Browser(s):
 - [ ] Operating System:
 - [ ] twilio-video.js:
 - [ ] Third-party libraries (e.g., Angular, React, etc.):

**Comment by manjeshbhargav** [comment]
Hi @rkiller ,

What you are seeing is most likely due to another tab or app which has reserved your microphone. We are recommending all developers that they should include a pre-connect mic check with an audio level indicator so the user can know that his/her mic is reserved by your web app. If the indicator does not move, then you should recommend the user to close all other apps and restart Safari.

Here is a [guide](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Visualizations_with_Web_Audio_API) on how to visualize audio samples from your microphone.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by rkiller** [comment]
I don't think that is it. It is happening to too many cases for this to be the case and it seems like it's only happening on 13.0.5 ...

**Comment by rkiller** [comment]
Also, if one were to implement a visualizer, how would you get a MediaStream from LocalAudioTrack in order to make this work:

source = audioCtx.createMediaStreamSource(stream);

**Comment by manjeshbhargav** [comment]
@rkiller ,

The LocalAudioTrack has a `mediaStreamTrack` property which you can use to create a MediaStream as follows:

```js
const mediaStream = new MediaStream([localAudioTrack.mediaStreamTrack]);
source = audioCtx.createMediaStreamSource(mediaStream);
```

In all our tests, this is the most likely reason why there are no audio bytes sent by the iOS Safari Participant, so I'm pretty confident that this is indeed the case. We have observed that even playing YouTube after joining a Room will cause this to happen. So, it would be great if you can try it out and let us know.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by rkiller** [comment]
Thank you @manjeshbhargav . We've implemented the audio check. Let's see what happens.

**Comment by anna-vasilko** [comment]
@rkiller Just for your visibility here is a Safari ticket tracking this issue, they seemed to have fixed this very recently https://bugs.webkit.org/show_bug.cgi?id=208516

**Comment by rkiller** [comment]
Thank you Anna. This is exactly what we are experiencing. In production it seems about 50% of clients on iPhones will face this issue.
