### ISSUE TITLE
createLocalVideoTrack / createLocalAudioTrack MS Edge error

### ISSUE THREAD

**Issue by av-k** [twilio/twilio-video.js#95]
Hi all,
caught the error after call methods `createLocalVideoTrack` and `createLocalAudioTrack`, by environment:
_Microsoft Edge 40.15063.0.0
Microsoft EdgeHTML 15.15063_

[error screen](http://image.prntscr.com/image/3804454759524f1f86008e5c6d9af870.jpg)

**Comment by markandrus** [comment]
Hi @av-k,

Thanks for opening the ticket. I am actually going to close this one in favor of tracking on #94. We are currently looking at this and related features in Edge.

Best,
Mark
