### ISSUE TITLE
Video freezes when new webcam is added after LocalTracks have been created

### ISSUE THREAD

**Issue by rkiller** [twilio/twilio-video.js#952]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ ] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [ ] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

```js
// TODO
```

**Expected behavior:**

TODO

**Actual behavior:**

TODO

**Software versions:**

 - [ ] Browser(s):
 - [ ] Operating System:
 - [ ] twilio-video.js:
 - [ ] Third-party libraries (e.g., Angular, React, etc.):

We've been trying to allow attachment and detachment of additional video and audio sources. When adding another webcam (plugging it into the USB port or powering it on) after local tracks were created, the video freezes on localparticipant.

**Comment by manjeshbhargav** [comment]
@rkiller ,

Thanks for reporting this. Please fill out the other details in your previous post so that we have more context about your issue.

Thanks,

Manjesh Malavalli
JSDK Team
