### ISSUE TITLE
[question] Possible to blur background (like in Teams)?

### ISSUE THREAD

**Issue by aastlind** [twilio/twilio-video.js#953]
Hello!

We're using Twilio SDKs for all platforms in our product and we want to thank you for a product that's very easy to implement!

This isn't an issue, but a question/feature enhancement request. Please remove if this is the wrong forum for this.

Since the use of video conferencing has grown a lot lately, some of our users has discovered features in other video applications. One of them is the "blur background" feature in Microsoft Teams. Is this something you have discussed to ship with your SDKs? If not, is it possible to achieve this using twilio-video.js? My guess is that you need some face tracking data to be able to know where to add blur.

**Comment by rkiller** [comment]
Hi @aastlind :

We've successfully used Chromacam https://www.chromacam.me/ for this.

Hope this helps.

**Comment by manjeshbhargav** [comment]
Hi @aastlind ,

Thanks for reaching out with your request. What you are looking for would require some image processing logic to run on every video frame to determine what part of the video is the background, which is most likely very expensive in terms of CPU especially on browsers. You can use the `<canvas>` element to grab video frames and apply your background detection and blurring logic, but as I said before that would be very expensive.

I'll close this issue for now. Please feel free to continue the discussion here if you need any more clarification.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by flfw** [comment]
Hi @manjeshbhargav do you ever see this as being part of the Twilio video roadmap? This is a common request from customers on our platform and suggesting Chromacam is not ideal. Over the last year most customers have come to expect video background blurring as a core feature of video platforms. Thank you!

**Comment by acro5piano** [comment]
I'm looking forward to blur background!

**Comment by manjeshbhargav** [comment]
Hi @flfw , @acro5piano ,

It is under consideration, but I cannot say anything more at this point. However, the latest SDK version 2.13.1 has the [Video Processor APIs](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md#new-features), which allows you to add a processor to a LocalVideoTrack. You can use that in conjunction with libraries like [bodyPix](https://github.com/tensorflow/tfjs-models/tree/master/body-pix) to achieve background blurring.

Thanks,

Manjesh

**Comment by acro5piano** [comment]
Thanks @manjeshbhargav

**Comment by RaptorMai** [comment]
Hi @manjeshbhargav 

I noticed that there there is a Twilio video processor package posted two months ago in the link attached below.
https://www.npmjs.com/package/@twilio/video-processors

The website lists "Virtual background" and "Background blur" as features but there is no document and example.
I wonder if this is on Twilio's roadmap and will be released officially soon?

Thank you so much

**Comment by acro5piano** [comment]
Hi there,

> You can use the <canvas> element to grab video frames and apply your background detection and blurring logic, but as I said before that would be very expensive.

I've created a gist to implement the blur background, using canvas and TensorFlow.

https://gist.github.com/acro5piano/0972a180348643031dd54a2d29c59301

Not testing much, but it's works well on my PC.

Note that it is client-side effect, so stream data sent to Twilio is not blur. This has impact on recording. Please anyone improve it.

**Comment by acro5piano** [comment]
Related: https://github.com/twilio/twilio-video.js/issues/1413

**Comment by charliesantos** [comment]
@flfw @acro5piano @RaptorMai blur and virtual background is not officially supported. Please see this announcement https://www.twilio.com/blog/introducing-virtual-backgrounds-browser-based-video-applications

**Comment by RaptorMai** [comment]
> @flfw @acro5piano @RaptorMai blur and virtual background is now officially supported. Please see this announcement https://www.twilio.com/blog/introducing-virtual-backgrounds-browser-based-video-applications

Thank you so much. Just want to confirm, the computationally expensive part is done on the local side right?

**Comment by charliesantos** [comment]
>Thank you so much. Just want to confirm, the computationally expensive part is done on the local side right?

That is correct.

**Comment by Dipesh-Das97** [comment]
Regarding twilio's blur. Can anyone help me to find the range of the blurRadius and maskRadius? I want to try out to increase intensity and smoothen edges. Right now, I am using blurFilterRadius = 10 and maskFilterRadius = 5. I would like to know the max and min ranges for both and also any additional info anyone has will be appreciated.

**Comment by charliesantos** [comment]
Answered @Dipesh-Das97 's question here https://github.com/twilio/twilio-video.js/issues/1664
