### ISSUE TITLE
[Question] Get stream for video tag without attach function

### ISSUE THREAD

**Issue by brunokunace** [twilio/twilio-video.js#956]
Hi all,

i am using vuejs and cant get direct stream to use em video tag, like it

`<video autoplay :src="sourceTrack" />`

i try get a local participant source first

```
const mapTracks = this.getTwilioRoom.localParticipant.tracks
      return [ ...mapTracks.values() ]
    }
```
but i cant get a stream, only get a mediaStreamTrack
i would not like to use the DOM directly, using appendChild or similar.

Have way to make it? Thanks!

**Comment by makarandp0** [comment]
@brunokunace, how about creating mediaStream in your code, and the adding a track manually?
something like:
```
var ms = new MediaStream();
ms.addTrack([...room.localParticipant.tracks.values()][0].track.mediaStreamTrack);
```

let me know if that helps,
thanks,
Makarand

**Comment by manjeshbhargav** [comment]
Hi @brunokunace ,

@makarandp0 's suggestion should help you create a MediaStream from Twilio Video's Tracks.
I'll close this issue for now. Please feel free to continue commenting here for additional clarifications related to your question.

Thanks,

Manjesh Malavalli
JSDK Team
