### ISSUE TITLE
[Question] Hi team we like to see the webinar  api from twilio end. Is there any plans regarding this ?

### ISSUE THREAD

**Issue by sandeepnandula** [twilio/twilio-video.js#962]
We are getting many webinar feature requests from our users.

**Comment by manjeshbhargav** [comment]
Hi @sandeepnandula ,

Can you elaborate more on what you are exactly looking for when you say webinar? 

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by sandeepnandula** [comment]
Hi @manjeshbhargav we like to see webinar kind of rooms which are capable of handling minimum 200 + participants. 

We have users from different organisations including education institutions etc.., . They like to run their classes and webinar through our product.

**Comment by manjeshbhargav** [comment]
Hi @sandeepnandula ,

So far, this is not in our product roadmap for 2020. However, you could in theory build a service that joins the Room as a Participant and forwards all RemoteTracks to a HTTP streaming service.
A couple of our customers have built something like that.

Thanks,

Manjesh Malavalli
JSDK Team
