### ISSUE TITLE
I am getting signalling connection disconnected issue

### ISSUE THREAD

**Issue by GauravAndroidIS** [twilio/twilio-video.js#967]
I am facing an issue in chrome browser whenever i am trying to connect to the room I am getting signalling connection disconnected issue.One twilio is implemented in an android app where Android is connected to the room but I am not able to connect the same room  . I have checked my internet is working fine still I am getting this issue. Please help me to solve this issue I stucked in this issue 😭😭

**Comment by makarandp0** [comment]
Hello @GauravAndroidIS, Thank you for writing about this issue?

Does your signaling connection disconnect intermittently or does it consistently fail to connect? Can you share some logs and room-sids from the browser where this error occurs.

Please make sure that you have whitelisted addresses from this table: https://www.twilio.com/docs/video/ip-address-whitelisting#signaling-communication

you can also experiment by setting the [connectOptions](https://media.twiliocdn.com/sdk/js/video/releases/2.3.0/docs/global.html#ConnectOptions).region parameter to the region closest to you. The signaling connection uses region specified. 

Let me know if that helps,
Thanks,
Makarand

**Comment by GauravAndroidIS** [comment]
It is happening consistently. This is one of the roomid and chatroom name
which we were connecting.

chat306961053

RMe9cb5cf58831cc8a9d64dc9af4b637b1

**Comment by manjeshbhargav** [comment]
@GauravAndroidIS ,

It looks like you are using the same `identity` to create the AccessTokens for both Desktop Chrome and Android Chrome. So, when the second Participant joins the Room, the first one gets disconnected. Please use different identities for different Participants. That should solve your issue.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by GauravAndroidIS** [comment]
Using different identities means we need to create different tokens for
both to connect to a chatroom. Right?

**Comment by GauravAndroidIS** [comment]
I have made the changes in the identity but getting the same issue. Please
check what is the issue. This log might help you.

 E/TwilioonParticipantConnected: RM766e8ab2bfbcf72f869c1e354ab232f7 -
PA2782b1d1c15697c143eff83a9c4642aa -
 E/TwilioonParticipantDisconnected: RM766e8ab2bfbcf72f869c1e354ab232f7 -
PA2782b1d1c15697c143eff83a9c4642aa -
 E/TwilioonParticipantConnected: RM766e8ab2bfbcf72f869c1e354ab232f7 -
PA38c22f96d5d6f1ccaa8853008470bd08 -
 E/TwilioonParticipantDisconnected: RM766e8ab2bfbcf72f869c1e354ab232f7 -
PA38c22f96d5d6f1ccaa8853008470bd08 -
 E/TwilioonParticipantConnected: RM766e8ab2bfbcf72f869c1e354ab232f7 -
PAda048b59050fb91297bb0e3b9a02fbb1 -
 E/TwilioonParticipantDisconnected: RM766e8ab2bfbcf72f869c1e354ab232f7 -
PAda048b59050fb91297bb0e3b9a02fbb1 -
 E/TwilioonParticipantConnected: RM766e8ab2bfbcf72f869c1e354ab232f7 -
PA06efc1b48c9dd2152f30ebb28cc99409 -
 E/TwilioonParticipantDisconnected: RM766e8ab2bfbcf72f869c1e354ab232f7 -
PA06efc1b48c9dd2152f30ebb28cc99409 -
 E/TwilioonParticipantConnected: RM766e8ab2bfbcf72f869c1e354ab232f7 -
PA9f636a3e6a26586a7fad623f5e2f93bf -
 E/TwilioonParticipantDisconnected: RM766e8ab2bfbcf72f869c1e354ab232f7 -
PA9f636a3e6a26586a7fad623f5e2f93bf -
 E/TwilioonParticipantConnected: RM766e8ab2bfbcf72f869c1e354ab232f7 -
PAf97eb1680372f630cb5d8151acf44aeb -
 E/TwilioonParticipantDisconnected: RM766e8ab2bfbcf72f869c1e354ab232f7 -
PAf97eb1680372f630cb5d8151acf44aeb -
 E/TwilioonParticipantConnected: RM766e8ab2bfbcf72f869c1e354ab232f7 -
PAe6c6b103f13e765119f339ee8827810d -
 E/TwilioonParticipantDisconnected: RM766e8ab2bfbcf72f869c1e354ab232f7 -
PAe6c6b103f13e765119f339ee8827810d -
 E/TwilioonParticipantConnected: RM766e8ab2bfbcf72f869c1e354ab232f7 -
PA4ae7353d05c3ca067636887c38ec228e -
E/TwilioonParticipantDisconnected: RM766e8ab2bfbcf72f869c1e354ab232f7 -
PA4ae7353d05c3ca067636887c38ec228e -
E/TwilioonParticipantConnected: RM766e8ab2bfbcf72f869c1e354ab232f7 -
PAe2128d1c44d375adddad96c6dd02bbc5 -
 E/TwilioonParticipantDisconnected: RM766e8ab2bfbcf72f869c1e354ab232f7 -
PAe2128d1c44d375adddad96c6dd02bbc5 -
 E/TwilioonParticipantConnected: RM766e8ab2bfbcf72f869c1e354ab232f7 -
PAb7ea311d9ec5cff0e986f20eae077c80 -
 E/TwilioonParticipantDisconnected: RM766e8ab2bfbcf72f869c1e354ab232f7 -
PAb7ea311d9ec5cff0e986f20eae077c80 -
E/TwilioonParticipantConnected: RM766e8ab2bfbcf72f869c1e354ab232f7 -
PA9a212e0785a0a6d890f6c2534f4405ee -
E/TwilioonParticipantDisconnected: RM766e8ab2bfbcf72f869c1e354ab232f7 -
PA9a212e0785a0a6d890f6c2534f4405ee -
E/TwilioonParticipantConnected: RM766e8ab2bfbcf72f869c1e354ab232f7 -
PA3d90c8dd55d2a17c8116097927bf0528 -
 E/TwilioonParticipantDisconnected: RM766e8ab2bfbcf72f869c1e354ab232f7 -
PA3d90c8dd55d2a17c8116097927bf0528 -
 E/TwilioonParticipantConnected: RM766e8ab2bfbcf72f869c1e354ab232f7 -
PA7197450b1ff353ae6d986a1bac88ca66 -
 E/TwilioonParticipantDisconnected: RM766e8ab2bfbcf72f869c1e354ab232f7 -
PA7197450b1ff353ae6d986a1bac88ca66 -
 E/TwilioonParticipantConnected: RM766e8ab2bfbcf72f869c1e354ab232f7 -
PAc3bc6b374f8f59d1b72d8d144f07142b -
 E/TwilioonParticipantDisconnected: RM766e8ab2bfbcf72f869c1e354ab232f7 -
PAc3bc6b374f8f59d1b72d8d144f07142b -
