### ISSUE TITLE
How to determine whether any participant has muted/unmuted the video or audio track?

### ISSUE THREAD

**Issue by hardik-singhal** [twilio/twilio-video.js#969]
I'm using one to one Twilio Audio/Video call, i want to know is there a way i can know if other participant's video track is muted or not.
Right now it works strangely sometime whole screen goes blank and sometime screen just freezes on the last frame before other participant clicked on mute

Expected behavior:
An event triggered from the other participant to notify state of video/audio track

Actual behavior:
Currently there is no event and it's difficult to determine the state of video component

**Comment by makarandp0** [comment]
@hardik-singhal - Thank you for writing about your question.

Local tracks can be enabled/disabled. On the remote side you can use [enabled](https://media.twiliocdn.com/sdk/js/video/releases/2.2.0/docs/RemoteAudioTrack.html#event:enabled__anchor) and [disabled](https://media.twiliocdn.com/sdk/js/video/releases/2.2.0/docs/RemoteAudioTrack.html#event:disabled__anchor) events on RemoteAudioTrack or RemoteVideoTrack to determine if its muted.

let me know if that addresses your question,
thanks,
Makarand

**Comment by kurapatijayaram** [comment]
Hi,
The above mentioned information is about after subscribing to the stream, what about identifying the mute/unmute state of the remote participant who already muted their tracks before the subscription.
