### ISSUE TITLE
Question: Increase user limit for certain use case

### ISSUE THREAD

**Issue by gniquil** [twilio/twilio-video.js#97]
Is it possible to increase the limit of number of users per room if only 1 stream (or 1 video/1 audio) is on at a time? I'm building something with features that's similar to Youtube's live stream. It would be nice if several hundred people can join the same room but with only the "host" presenting.

**Comment by ktoraskartwilio** [comment]
Hi @gniquil 

I work on the Video Product team at Twilio. Using our Group Rooms API you may be able to achieve a live stream use case the way you describe it with 1 presenter. Group Rooms is currently in Developer Preview and will move to a Public Beta soon. I'd be happy to provide more information - please DM at ktoraskar@twilio.com. 

Thanks,

**Comment by markandrus** [comment]
Following up here, now that [Group Rooms is in Public Beta](https://www.twilio.com/blog/2017/05/announcing-programmable-video-group-rooms.html), you can select this new Room type and scale to 50 Participants (Peer-to-Peer only scales to 10). Definitely reach out over email if you are interested in scaling to larger numbers—we're actively looking for developer feedback.

Thanks,
Mark

**Comment by JeanCarriere** [comment]
@markandrus would it be possible to have group rooms with 1 user sending his video stream and 500 or 1000 watching (like tokbox which supports up to 2000) ?
