### ISSUE TITLE
Signalling Connection Disconnected Issue

### ISSUE THREAD

**Issue by GauravAndroidIS** [twilio/twilio-video.js#971]
I have made the changes in the identity but getting the same issue.FYI video calling working in only one system but not working if i used any different system  Please check what is the issue. This log might help you.

 E/TwilioonParticipantConnected: RM766e8ab2bfbcf72f869c1e354ab232f7 - PA2782b1d1c15697c143eff83a9c4642aa -
 E/TwilioonParticipantDisconnected: RM766e8ab2bfbcf72f869c1e354ab232f7 - PA2782b1d1c15697c143eff83a9c4642aa -
 E/TwilioonParticipantConnected: RM766e8ab2bfbcf72f869c1e354ab232f7 - PA38c22f96d5d6f1ccaa8853008470bd08 -
 E/TwilioonParticipantDisconnected: RM766e8ab2bfbcf72f869c1e354ab232f7 - PA38c22f96d5d6f1ccaa8853008470bd08 -
 E/TwilioonParticipantConnected: RM766e8ab2bfbcf72f869c1e354ab232f7 - PAda048b59050fb91297bb0e3b9a02fbb1 -
 E/TwilioonParticipantDisconnected: RM766e8ab2bfbcf72f869c1e354ab232f7 - PAda048b59050fb91297bb0e3b9a02fbb1 -
 E/TwilioonParticipantConnected: RM766e8ab2bfbcf72f869c1e354ab232f7 - PA06efc1b48c9dd2152f30ebb28cc99409 -
 E/TwilioonParticipantDisconnected: RM766e8ab2bfbcf72f869c1e354ab232f7 - PA06efc1b48c9dd2152f30ebb28cc99409 -
 E/TwilioonParticipantConnected: RM766e8ab2bfbcf72f869c1e354ab232f7 - PA9f636a3e6a26586a7fad623f5e2f93bf -
 E/TwilioonParticipantDisconnected: RM766e8ab2bfbcf72f869c1e354ab232f7 - PA9f636a3e6a26586a7fad623f5e2f93bf -
 E/TwilioonParticipantConnected: RM766e8ab2bfbcf72f869c1e354ab232f7 - PAf97eb1680372f630cb5d8151acf44aeb -
 E/TwilioonParticipantDisconnected: RM766e8ab2bfbcf72f869c1e354ab232f7 - PAf97eb1680372f630cb5d8151acf44aeb -
 E/TwilioonParticipantConnected: RM766e8ab2bfbcf72f869c1e354ab232f7 - PAe6c6b103f13e765119f339ee8827810d -
 E/TwilioonParticipantDisconnected: RM766e8ab2bfbcf72f869c1e354ab232f7 - PAe6c6b103f13e765119f339ee8827810d -
 E/TwilioonParticipantConnected: RM766e8ab2bfbcf72f869c1e354ab232f7 - PA4ae7353d05c3ca067636887c38ec228e -
E/TwilioonParticipantDisconnected: RM766e8ab2bfbcf72f869c1e354ab232f7 - PA4ae7353d05c3ca067636887c38ec228e -
E/TwilioonParticipantConnected: RM766e8ab2bfbcf72f869c1e354ab232f7 - PAe2128d1c44d375adddad96c6dd02bbc5 -
 E/TwilioonParticipantDisconnected: RM766e8ab2bfbcf72f869c1e354ab232f7 - PAe2128d1c44d375adddad96c6dd02bbc5 -
 E/TwilioonParticipantConnected: RM766e8ab2bfbcf72f869c1e354ab232f7 - PAb7ea311d9ec5cff0e986f20eae077c80 -
 E/TwilioonParticipantDisconnected: RM766e8ab2bfbcf72f869c1e354ab232f7 - PAb7ea311d9ec5cff0e986f20eae077c80 -
E/TwilioonParticipantConnected: RM766e8ab2bfbcf72f869c1e354ab232f7 - PA9a212e0785a0a6d890f6c2534f4405ee -
E/TwilioonParticipantDisconnected: RM766e8ab2bfbcf72f869c1e354ab232f7 - PA9a212e0785a0a6d890f6c2534f4405ee -
E/TwilioonParticipantConnected: RM766e8ab2bfbcf72f869c1e354ab232f7 - PA3d90c8dd55d2a17c8116097927bf0528 -
 E/TwilioonParticipantDisconnected: RM766e8ab2bfbcf72f869c1e354ab232f7 - PA3d90c8dd55d2a17c8116097927bf0528 -
 E/TwilioonParticipantConnected: RM766e8ab2bfbcf72f869c1e354ab232f7 - PA7197450b1ff353ae6d986a1bac88ca66 -
 E/TwilioonParticipantDisconnected: RM766e8ab2bfbcf72f869c1e354ab232f7 - PA7197450b1ff353ae6d986a1bac88ca66 -
 E/TwilioonParticipantConnected: RM766e8ab2bfbcf72f869c1e354ab232f7 - PAc3bc6b374f8f59d1b72d8d144f07142b -
 E/TwilioonParticipantDisconnected: RM766e8ab2bfbcf72f869c1e354ab232f7 - PAc3bc6b374f8f59d1b72d8d144f07142b -

**Comment by GauravAndroidIS** [comment]
Please provide me solution for the same. I am stuck in this issue for a long time and some work is suffering because of this

**Comment by manjeshbhargav** [comment]
Hi @GauravAndroidIS ,

I took a look at the Room SIDs, and the Participants get disconnected still have the same `identity`. Please provide a different `identity` while [creating the token](https://www.twilio.com/docs/video/tutorials/user-identity-access-tokens#javascript) for each Participant.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by GauravAndroidIS** [comment]
Please check this code we are using the same code as mentioned in the
document and if there is problem in the code it should not work in any of
the system but right now it's working only in my system. I think there is
some other issue.

// $room = isset($_GET["room"]) ? $_GET["room"] : "Icici";
      $identity ="chat".rand();
        // Create access token, which we will serialize and send to the
client
        $token = new AccessToken(
            TWILIO_ACCOUNT_SID,
            TWILIO_API_KEY,
            TWILIO_API_SECRET,
            3600,
            $identity
        );
        // Grant access to Video
        $grant = new VideoGrant();




        //$grant->setRoom($room);
        $token->addGrant($grant);
        $output = json_encode(array(
            'identity' => $identity,
            'token' => $token->toJWT(),
        ));

**Comment by manjeshbhargav** [comment]
@GauravAndroidIS It looks like there is some problem with the way you create the `$identity`. I don't think there is a method called `rand()` on a string  in PHP (BTW I'm not that familiar with PHP). Maybe you could try something like this?
```php
function generateRandomString($length = 10) {
    $characters = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
    $charactersLength = strlen($characters);
    $randomString = '';
    for ($i = 0; $i < $length; $i++) {
        $randomString .= $characters[rand(0, $charactersLength - 1)];
    }
    return $randomString;
}
```
Thanks,

Manjesh Malavalli
JSDK Team

**Comment by GauravAndroidIS** [comment]
I have used your code also but it is still not working for me:

function index() {
        // $identity = isset($_GET["name"]) ? $_GET["name"] : "chat".rand();
        // $room = isset($_GET["room"]) ? $_GET["room"] : "Icici";
    $identity ="identity".generateRandomString(10);
        // Create access token, which we will serialize and send to the
client
    $token = new AccessToken(
      TWILIO_ACCOUNT_SID,
      TWILIO_API_KEY,
      TWILIO_API_SECRET,
      3600,
      $identity
    );
        // Grant access to Video
    $grant = new VideoGrant();




        //$grant->setRoom($room);
    $token->addGrant($grant);
    $output = json_encode(array(
      'identity' => $identity,
      'token' => $token->toJWT(),
    ));
    json_output($output);
  }

**Comment by GauravAndroidIS** [comment]
Log from web:


2020-04-23 23:30:07.643Z | DEBUG in [LocalParticipant #1:
PA44c1d36c619859a442f530706ab536dd]: Removing LocalTrack event listeners
twilio-video.min.js:97:13475
2020-04-23 23:30:07.648Z | INFO in [LocalParticipant #1:
PA44c1d36c619859a442f530706ab536dd]: LocalParticipant disconnected.
Stopping 2 automatically-acquired LocalTracks twilio-video.min.js:97:13475
2020-04-23 23:30:07.651Z | INFO in [LocalAudioTrack #1:
{265362de-915a-422b-89b8-f74fbd937714}]: Stopping
twilio-video.min.js:97:13475
2020-04-23 23:30:07.655Z | DEBUG in [LocalAudioTrack #1:
{265362de-915a-422b-89b8-f74fbd937714}]: Ended twilio-video.min.js:97:13475
2020-04-23 23:30:07.658Z | INFO in [LocalVideoTrack #2:
{520fb02a-d304-455d-b8ba-e4b0311e9a8a}]: Stopping
twilio-video.min.js:97:13475
2020-04-23 23:30:07.666Z | DEBUG in [LocalVideoTrack #2:
{520fb02a-d304-455d-b8ba-e4b0311e9a8a}]: Ended twilio-video.min.js:97:13475
2020-04-23 23:30:07.669Z | INFO in [Room #1:
RMa3b2e8da6275dfdffc6c32b0f8200fd9]: Transitioned to state: disconnected
twilio-video.min.js:97:13475
2020-04-23 23:30:07.678Z | DEBUG in [LocalAudioTrack #1:
{265362de-915a-422b-89b8-f74fbd937714}]: Attempting to detach from
elements:
Array [ audio
 ]
twilio-video.min.js:97:13475
2020-04-23 23:30:07.688Z | DEBUG in [LocalVideoTrack #2:
{520fb02a-d304-455d-b8ba-e4b0311e9a8a}]: Attempting to detach from
elements:
Array [ video
 ]
twilio-video.min.js:97:13475
2020-04-23 23:30:07.698Z | DEBUG in [RemoteAudioTrack #3:
MTa3fd3ddbfba4ee8014b06309dd75c042]: Attempting to detach from elements:
Array [ audio
 ]
twilio-video.min.js:97:13475
2020-04-23 23:30:07.704Z | DEBUG in [RemoteVideoTrack #4:
MT99aac55387eae4f192dfcc3ab2fb432a]: Attempting to detach from elements:
Array [ video
 ]
twilio-video.min.js:97:13475
undefined MQc:328:14
2020-04-23 23:30:07.714Z | INFO in [connect #1]: Disconnected from Room:
[Room #1: RMa3b2e8da6275dfdffc6c32b0f8200fd9] twilio-video.min.js:97:13475
Fri Apr 24 2020 05:00:07 GMT+0530 (India Standard Time) | sip.ua | user
requested closure... twilio-video.min.js:101:30694
Fri Apr 24 2020 05:00:07 GMT+0530 (India Standard Time) | sip.ua | closing
registerContext twilio-video.min.js:101:30694
Fri Apr 24 2020 05:00:07 GMT+0530 (India Standard Time) |
sip.registercontext | already unregistered twilio-video.min.js:101:30694
Fri Apr 24 2020 05:00:07 GMT+0530 (India Standard Time) | sip.ua | closing
session iepq4mcb8kd2l74kobi0menf3rerrs twilio-video.min.js:101:30694
Fri Apr 24 2020 05:00:07 GMT+0530 (India Standard Time) |
sip.inviteclientcontext | terminating Session twilio-video.min.js:101:30694
Fri Apr 24 2020 05:00:07 GMT+0530 (India Standard Time) | sip.transport |
sending WebSocket message:

BYE sip:172.18.6.51:443;transport=wss SIP/2.0

Via: SIP/2.0/WSS puemn4rlnu06.invalid;branch=z9hG4bK9214347

Max-Forwards: 70

To: <sip:orchestrator@endpoint.twilio.com
>;tag=04388089_6772d868_5e83af53-11be-4fba-9d7b-31dd9fec555b

From: <sip:84fdf4af-295d-45ce-8d43-d23ee1946173@endpoint.twilio.com
>;tag=eteoffh48c

Call-ID: iepq4mcb8kd2l74kobi0

CSeq: 4280 BYE

Supported: outbound, room-signaling, timer

User-Agent: SIP.js/0.7.7

Content-Length: 0




twilio-video.min.js:101:30694
Fri Apr 24 2020 05:00:07 GMT+0530 (India Standard Time) |
sip.inviteclientcontext | closing INVITE session
iepq4mcb8kd2l74kobi0menf3rerrs twilio-video.min.js:101:30694
2020-04-23 23:30:07.793Z | INFO in [NTSIceServerSource #1]: Stopping
twilio-video.min.js:97:13475
2020-04-23 23:30:07.801Z | DEBUG in [NTSIceServerSource #1]: Stopped
twilio-video.min.js:97:13475
Fri Apr 24 2020 05:00:07 GMT+0530 (India Standard Time) | sip.dialog |
dialog
iepq4mcb8kd2l74kobi0eteoffh48c04388089_6772d868_5e83af53-11be-4fba-9d7b-31dd9fec555b
deleted twilio-video.min.js:101:30694
2020-04-23 23:30:07.842Z | WARN in [LocalParticipant #1:
PA44c1d36c619859a442f530706ab536dd]: Failed to publish the LocalAudioTrack:
LocalParticipant disconnected twilio-video.min.js:97:13475
2020-04-23 23:30:07.851Z | INFO in [LocalParticipant #1:
PA44c1d36c619859a442f530706ab536dd]: Removed a AudioTrack:
{265362de-915a-422b-89b8-f74fbd937714} twilio-video.min.js:97:13475
2020-04-23 23:30:07.852Z | DEBUG in [LocalParticipant #1:
PA44c1d36c619859a442f530706ab536dd]: AudioTrack:
Object { _events: {…}, _maxListeners: undefined, id:
"{265362de-915a-422b-89b8-f74fbd937714}", kind: "audio", name:
"{265362de-915a-422b-89b8-f74fbd937714}", mediaStreamTrack:
MediaStreamTrack, _dummyEl: audio, isEnabled: Getter, … }
twilio-video.min.js:97:13475
2020-04-23 23:30:07.862Z | WARN in [LocalParticipant #1:
PA44c1d36c619859a442f530706ab536dd]: Failed to publish the LocalVideoTrack:
LocalParticipant disconnected twilio-video.min.js:97:13475
2020-04-23 23:30:07.864Z | INFO in [LocalParticipant #1:
PA44c1d36c619859a442f530706ab536dd]: Removed a VideoTrack:
{520fb02a-d304-455d-b8ba-e4b0311e9a8a} twilio-video.min.js:97:13475
2020-04-23 23:30:07.866Z | DEBUG in [LocalParticipant #1:
PA44c1d36c619859a442f530706ab536dd]: VideoTrack:
Object { _events: {…}, _maxListeners: undefined, id:
"{520fb02a-d304-455d-b8ba-e4b0311e9a8a}", kind: "video", name:
"{520fb02a-d304-455d-b8ba-e4b0311e9a8a}", mediaStreamTrack:
MediaStreamTrack, _dummyEl: video, dimensions: {…}, isEnabled: Getter, … }
twilio-video.min.js:97:13475
2020-04-23 23:30:07.929Z | DEBUG in [RemoteAudioTrack #3:
MTa3fd3ddbfba4ee8014b06309dd75c042]: Ended twilio-video.min.js:97:13475
2020-04-23 23:30:07.934Z | DEBUG in [RemoteVideoTrack #4:
MT99aac55387eae4f192dfcc3ab2fb432a]: Ended twilio-video.min.js:97:13475
Fri Apr 24 2020 05:00:08 GMT+0530 (India Standard Time) | sip.transport |
received WebSocket text message:

SIP/2.0 200 OK

CSeq: 4280 BYE

Call-ID: iepq4mcb8kd2l74kobi0

From: <sip:84fdf4af-295d-45ce-8d43-d23ee1946173@endpoint.twilio.com
>;tag=eteoffh48c

To: <sip:orchestrator@endpoint.twilio.com
>;tag=04388089_6772d868_5e83af53-11be-4fba-9d7b-31dd9fec555b

Via: SIP/2.0/WSS 127.0.0.1:45350;branch=z9hG4bK9214347;rport=45350

Server: Twilio

Supported: room-signaling

Content-Type: application/room-signaling+json

X-Twilio-CallSid: CAe5f15342d733ca55cdd8321a233024f5

X-Twilio-LegInfo: external

X-Twilio-TlsVerify: true

Content-Length: 147



{"version":1,"type":"disconnected","sid":"RMa3b2e8da6275dfdffc6c32b0f8200fd9","name":"room1587683941ashu","participants":[],"status":"in-progress"}
twilio-video.min.js:101:30694
Fri Apr 24 2020 05:00:08 GMT+0530 (India Standard Time) | sip.transport |
closing WebSocket wss://endpoint.twilio.com twilio-video.min.js:101:30694
Fri Apr 24 2020 05:00:09 GMT+0530 (India Standard Time) | sip.transport |
WebSocket disconnected (code: 1005) twilio-video.min.js:101:30694
Fri Apr 24 2020 05:00:09 GMT+0530 (India Standard Time) | sip.ua |
connection state set to 1 twilio-video.min.js:101:30694
Fri Apr 24 2020 05:00:09 GMT+0530 (India Standard Time) |
sip.transaction.ict | transport error occurred, deleting INVITE client
transaction z9hG4bK9944574 twilio-video.min.js:101:30694

**Comment by manjeshbhargav** [comment]
Hi @GauravAndroidIS ,

Here is the list of identities in the Room that you shared:

identityHpwQbvreEK
identity5r0hi6NUfA
**identityGoRBCx41mj
identityGoRBCx41mj**
identityprGKkWdyha
identity1ZAHQXxkjN
**identity567DiWlaO7
identity567DiWlaO7**
identityfJKkMGytgJ
```

The bolded identities are duplicates, and identities have to be unique per Participant.

Thanks,

Manjesh Malavalli
JSDK Team
