### ISSUE TITLE
Track priority does not reflect publishPriority

### ISSUE THREAD

**Issue by HandsomeMedia** [twilio/twilio-video.js#972]
Issue seems similar to this bug: https://github.com/twilio/twilio-video.js/pull/907 however, issue persists.

 - [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

```js
  const identity = sessionForm.elements['identity'].value
  const session = sessionForm.elements['session'].value
  const token = await fetch(`/token?identity=${encodeURIComponent(identity)}&session=${encodeURIComponent(session)}`).then(response => response.text())
  const localTracks = await Promise.all([Video.createLocalAudioTrack(), Video.createLocalVideoTrack(), new Video.LocalDataTrack()])
  const options = {
    name: session,
    audio: false,
    video: false,
    bandwidthProfile: {
      video: {
        mode: 'presentation'
      }
    },
  }

  const room = await Video.connect(token, options)

  localTracks.forEach(track => {
    room.localParticipant.publishTrack(track, {
      priority: 'high'
    })
  })

  room.localParticipant.tracks.forEach(track => track.setPriority(priority))

// setting priority above using method as well as publish property - neither seems to take effect

```

**Expected behavior:**

Track.priority should equal "high"

**Actual behavior:**

Track.priority equals "null"

<img width="1262" alt="Screen Shot 2020-04-23 at 11 11 22 PM" src="https://user-images.githubusercontent.com/14863500/80180971-c7c0cf00-85b8-11ea-8c44-9468a728f84f.png">

**Software versions:**

 - [x] Browser(s): Chrome Version 80.0.3987.149
 - [x] Operating System: Mac OS Mojave 10.14.6
 - [x] twilio-video.js: 2.3.0
 - [x] Third-party libraries (e.g., Angular, React, etc.): none

**Comment by makarandp0** [comment]
Hello @HandsomeMedia, thank you for writing about this question. I think the behavior you are seeing is as expected. 

Each RemoteTrack has two priorities. 

1. priority set by publisher
which is stored in readonly property [RemoteTrackPublication](https://media.twiliocdn.com/sdk/js/video/releases/2.3.0/docs/RemoteTrackPublication.html).publishPriority  
Its value changes when the publisher changes the priority using [LocalTrackPublication.setPriority](https://media.twiliocdn.com/sdk/js/video/releases/2.3.0/docs/LocalTrackPublication.html#setPriority__anchor)

1. priority set by subscriber.
Its value is stored in [RemoteVideoTrack](https://media.twiliocdn.com/sdk/js/video/releases/2.3.0/docs/RemoteVideoTrack.html).priority
This can be updated by subscriber with [RemoteVideoTrack.setPriority](https://media.twiliocdn.com/sdk/js/video/releases/2.3.0/docs/RemoteVideoTrack.html#setPriority__anchor) 

In your example you are only changing publisher priority, and not subscriber priority - so you continue to see subscriber priority of `null`

Let me know if this helps,
Thanks,
Makarand


BTW although the API allows you set priority on audio tracks, it does not have effect on them. It's mainly useful for Video Tracks. Audio tracks always get higher priority than video tracks.

**Comment by makarandp0** [comment]
Please check out this guide on track priorities: https://www.twilio.com/docs/video/tutorials/using-track-priority-api

**Comment by HandsomeMedia** [comment]
Thank you @makarandp0 for the clarification.  I had read that guide and took this line _**the publisher Track priority propagates to all remote subscribers**_ to mean the track viewed by subscriber would be set to reflect the publisher priority.  As I understand it now from your reply, a subscriber priority of `null` will still reflect the publisher priority.  i.e. `if subscriber.priority is null, subscriber.priority = publisher.priority`.

It seems to me a more intuitive approach would be to update the subscriber priority with the publisher priority default.  This, while still allowing the subscriber priority to be updated independently if so desired.

Thanks again for your time.

**Comment by makarandp0** [comment]
@HandsomeMedia,

To answer your question - yes, if subscriber has not set any priority on remote track (remoteVideoTrack.priority === null), then the publisher priority (remoteTrackPublication.publishPriority) will be effective on the track.

This also means that if a subscriber sets a priority on a track, and then later resets it back to `null`, then the publisher priority will be effective again. 

Since these priorities can be independently set, we keep it in different variables. Setting subscriber priority with publisher priority value as default would be misleading, since publisher can change the priority of the published track at runtime. 


Thanks,
Makarand

**Comment by HandsomeMedia** [comment]
Thanks @makarandp0 for the clarification.
