### ISSUE TITLE
Video lag issue on Firefox 75 to other browser or app

### ISSUE THREAD

**Issue by nitin-engine** [twilio/twilio-video.js#978]
We are using the latest version of the Twilio SDK and facing the video lag issue on the Firefox 75 only. We have used the Twilio SDK in our two project and in both we are able to replicate it.

Steps to reproduce:
1) Join the video call as User A from Firefox 75 browser on MAC 10.15 (Catalina).
2) Take the other participant B into the room on Android app or Chrome web browser.

**Expected behavior:**
There should not be any delay in the video and audio on the User B end.

**Actual behavior:**
You will notice the 4-5 seconds delay in the video and audio at the user B end (Android app or Chrome web browser).

**Software versions:**

 - Browser(s): Firefox 75
 - Operating System: MAC 10.15 Catalina
 - twilio-video.js: 1.20.1 and 2.3.0 (We are using these version of two different projects)

The call is working fine with other web browsers, this is happening only with Firefox.
Can you please help me out?

**Comment by makarandp0** [comment]
Hello @nitin-engine, Thank you for reporting this issue. I have not been able to reproduce such delay. Can you share some more details - 

1) room sids that reproduce the issue, 
2) client logs from both sides.

Would be very useful. 

One question - Is your firefox client behind proxy / VPN? if so does this issue repro if the client was not behind the proxy ?

Thanks,
Makarand
