### ISSUE TITLE
Build help for NPM package

### ISSUE THREAD

**Issue by tpict** [twilio/twilio-video.js#979]
The NPM package for `twilio-video` has a dependency on [`@twilio/webrtc`](https://github.com/twilio/twilio-webrtc.js/tree/master/lib), which itself makes use of the [Node.js `util` module](https://nodejs.org/api/util.html#util_util). When calling `Video.connect` in my React app, I get the error

```
react-dom.development.js:13035 Uncaught TypeError: inherits is not a function
    at Object../node_modules/@twilio/webrtc/lib/rtcpeerconnection/chrome.js
```

Does the `twilio-video` NPM package require that I add a transform somewhere in my toolchain to make `@twilio/webrtc` run in the browser?

**Comment by manjeshbhargav** [comment]
Hi @tpict ,

Thanks for writing in with your issue. What version of Node are you using? Also, can you confirm that `inherits` is available in your `utils` module? You shouldn't have to add any special transform plugin in order to get this to work on the browser.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by tpict** [comment]
My machine is running 10.16.0, but the error shown is happening in the browser–`inherits` it's a Node.js built-in that's not available in that environment. In the CDN script, the `util.inherits` function is polyfilled in, but the `twilio-video` NPM package seems to import from `@twilio/webrtc` without polyfills.

Thanks!

**Comment by manjeshbhargav** [comment]
@tpict ,

Was your app created using `create-react-app`? If so, then when you run `react-scripts` build, it should package the `util` module into the JS bundle. Please let me know about your packaging setup.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by tpict** [comment]
The app has a custom Webpack toolchain, so we don't have a runtime dependency on `util`.

It turns out that the issue is that we have a module named `util` ourselves which was colliding with the Node.js `util` module. This hasn't been an issue to date as our other dependencies that use the `util` module add browser support by building with [Webpack's Node plugin](https://webpack.js.org/configuration/node/). In our case, the fix was to rename `util` to something else 🙃

Thanks!

**Comment by manjeshbhargav** [comment]
@tpict ,

Glad to know that you were able to resolve the issue. Thanks for being a Twilio customer! Feel free to open a new issue if you experience any other problems or you want to get some clarification about something else.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by niemyjski** [comment]
Can we get a library that's built for the browser. Polyfiling node especially on webpack5 is a no go for us.
