### ISSUE TITLE
Suggested workaround for Firefox/Chrome interop failing when using twilio.js

### ISSUE THREAD

**Issue by geoffreyabdallah** [twilio/twilio-video.js#98]
From #52 

I'm doing some more testing right now (using v1.0.0), but seems that the preferred way of avoiding the firefox/chrome interop issue (adding a local audio stream/then disabling) may be an untenable solution in our case, since we are also dealing simultaneously with twilio-audio in a room (essentially bridging conferences in audio/video). In test, going that route, I've noticed that it then prevents twilio-audio from connecting to the conference. I'll keep testing and make sure I'm not just messing up something simple on my end as well though.

 - [X] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [X] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.

**Code to reproduce the issue:**

```js
function* connectVideo(roomName) {
  const [videoToken, localVideoTrack] = yield select(getFromTwilio(['videoToken', 'localVideoTrack']))
  const localAudioTrack = yield createLocalAudioTrack()
  localAudioTrack.disable()
  if (videoToken) return yield connect(videoToken, { name: roomName, tracks: [localVideoTrack, localAudioTrack], logLevel: 'debug' })
}
```

**Expected behavior:**

```js
function* connectVideo(roomName) {
  const [videoToken, localVideoTrack] = yield select(getFromTwilio(['videoToken', 'localVideoTrack']))
  if (videoToken) return yield connect(videoToken, { name: roomName, tracks: [localVideoTrack], logLevel: 'debug' })
}
```

The code above currently works in order to connect a participant to a video room, and does not interfere with the connection to twilio.js (Public beta v1.4 JS SDK) - however, it runs into the issue that the current Firefox/Chrome interop workaround tries to solve. I expect that when adding/disabling and sharing a local audio track on video, that audio still works as expected. However, when adding the localAudioTrack to the tracks shared to room, or putting disable between creation/sharing (have tested both) - twilio.js no longer connects to the conference room (no hold music, connect sound etc.)

Debug logs attached
[chromeconsole.txt](https://github.com/twilio/twilio-video.js/files/972099/chromeconsole.txt)
[firefoxconsoledisabled.txt](https://github.com/twilio/twilio-video.js/files/972108/firefoxconsoledisabled.txt)

**Software versions:**

 - Browser(s): Chrome Canary -> Firefox
 - Operating System: MacOS Sierra
 - twilio-video.js: v1.0.0
 - Third-party libraries (e.g., Angular, React, etc.): React/Redux/Redux-Saga/Twilio.js

**Comment by geoffreyabdallah** [comment]
To clarify, the ability to join the twilio.js telephony conference with the adding/disabling of audioTrack only drops out for firefox, Chrome works either way.

**Comment by markandrus** [comment]
Thanks for the logs @geoffreyabdallah. From a twilio.js perspective, it appears

* You are using twilio.js 1.4.14
* Chrome appears to successfully connect to a Call, indicated by the PeerConnection logs from twilio.js:

  > twilio.min.js:69 [Twilio.PeerConnection] signalingState is "have-local-offer"
  > twilio.min.js:69 [Twilio.PeerConnection] signalingState is "stable"
  > twilio.min.js:69 [Twilio.PeerConnection] iceConnectionState is "checking"
  > ...
  > twilio.min.js:69 [Twilio.PeerConnection] iceConnectionState is "completed"

* In Firefox, however, I don't see any log lines after

  > [Device] Stream is ready  twilio.min.js:69:375

  which indicates to me that maybe an incoming Call is expected but not received?

Can you confirm whether or not Firefox received or placed a Call? Could share Call SIDs by any chance? I will begin trying to reproduce myself.

**Comment by markandrus** [comment]
Hi @geoffreyabdallah,

I've created [a test application](https://github.com/markandrus/twilio-voice-and-video-js) that uses both twilio.js and twilio-video.js together. In my testing, I could not reproduce the issue on my machine. It is possible that my test application is dissimilar from your application in its use of twilio.js. Could you share a bit more of your twilio.js-related code? Are you sharing MediaStreams across twilio.js and twilio-video.js?

My test application allows the user to conduct a Voice and Video call at the same time. Once the Voice call connects, an audio indicator begins displaying the remote audio. Once the Video call connects, the Participants are displayed as we'd expect in typical voice applications.

![screen shot 2017-05-03 at 5 05 05 pm](https://cloud.githubusercontent.com/assets/359154/25686496/b16fa124-3023-11e7-922e-5bbfaea4700c.png)

The screen shot is cropped, but below I am connected to a Room at the same time.

**Comment by geoffreyabdallah** [comment]
@markandrus Thanks for the very thorough testing done. I'll go through my code and also run the sample application and see if I can't figure out exactly what's causing the issue on my end and will report back (will also paste the twilio.js connectivity code).

**Comment by geoffreyabdallah** [comment]
@markandrus alright, after more testing I was able to isolate the problem on our end. I was initially creating a local videotrack to display as a 'preview', then creating the local audio/local video w/ disabled audio then passed to connect. For some reason, Firefox doesn't like that. However, after shifting the preview to create both video/audio and disable there, then pass the refs to the connect when that event is fired on the UI - was able to get the browser interop working.

Before:
```js
// For previewing
export function* setUpVideoClient({ payload: { videoToken } }) {
  if (videoToken) {
    const localVideoTrack = yield createLocalVideoTrack()
    yield put({ type: 'GET_VIDEO_CAPABILITY_SUCCEEDED', payload: { videoToken, localVideoTrack } })
  }
}

// For connecting
function* connectVideo(roomName) {
  const [videoToken, localVideoTrack] = yield select(getFromTwilio(['videoToken', 'localVideoTrack']))
  if (videoToken) return yield connect(videoToken, { name: roomName, tracks: [localVideoTrack] })
}
```

After:
```js
export function* setUpVideoClient({ payload: { videoToken } }) {
  if (videoToken) {
    const [localAudioTrack, localVideoTrack] = yield createLocalTracks()
    localAudioTrack.disable()
    yield put({ type: 'GET_VIDEO_CAPABILITY_SUCCEEDED', payload: { videoToken, localVideoTrack, localAudioTrack } })
  }
}

function* connectVideo(roomName) {
  const [videoToken, localVideoTrack, localAudioTrack] = yield select(getFromTwilio(['videoToken', 'localVideoTrack', 'localAudioTrack']))
  if (videoToken) return yield connect(videoToken, { name: roomName, tracks: [localAudioTrack, localVideoTrack] })
}
```

Closing since resolved on my end.
