### ISSUE TITLE
Poor Video Quality

### ISSUE THREAD

**Issue by GWSzeto** [twilio/twilio-video.js#983]
**Describe the bug**
Poor video quality when using application.
Tested with both p2p and group

**To Reproduce**
1. Run the application locally
2. join as a user on laptop
3. join as a user on mobile

**Expected behavior**
Expected the video quality to be clear enough to be able to read lettering on a pill bottle

**Screenshots**
![Screenshot from 2020-04-28 23-12-07](https://user-images.githubusercontent.com/25385051/80566417-f7a91180-89c0-11ea-92d2-2e69aa2fd63c.png)

**Environment (please complete the following information):**
 - Ubuntu: 19.10
 - Chrome Version: 81.0.4044.129 (Official Build) (64-bit)
 - App Version: 0.1.0
 - twilio: ^3.39.3
- twilio-video: ^2.3.0
 - Node.js version: v10.18.0

**Additional Information**
I did this on the twilio-video-app-react application, but I get the same results on my own app.

**Comment by manjeshbhargav** [comment]
Hi @GWSzeto ,

Thanks for opening the issue. Can you please share the Room SID of the Room you tried out. You can get it by typing `twilioRoom.sid` in the JS console after joining a Room.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by GWSzeto** [comment]
@manjeshbhargav 
room sid: RM1178cae5dc34e28630b2d403e9b678de

**Comment by manjeshbhargav** [comment]
Hi @GWSzeto ,

Thanks for the Room SID. I will investigate further and get back to you soon. FYI, I noticed that you are using SDK version 2.0.1. I recommend that you upgrade to 2.3.0.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by manjeshbhargav** [comment]
Hi @GWSzeto ,

I was curious, what mobile device are you using in the screenshot?

Thanks,

Manjesh Malavalli
JSDK Team
