### ISSUE TITLE
Change BandwidthProfile video mode dynamically after connect?

### ISSUE THREAD

**Issue by multiplegeorges** [twilio/twilio-video.js#988]
Is it possible to change the bandwidthProfile settings on a room after the local participant has connected to it?

For example, if the user initially connects like this:

```javascript
const room = await connect(token,{
  name: "my-new-room",
  bandwidthProfile: {
    video: {
      mode: 'collaboration',
      renderDimensions: {
        high: {width: 1080, height: 720},
        standard: {width: 640, height: 480},
        low: {width: 320, height: 240}
      }
    }
  }
});
```

and during use of my app the user decides to select my grid view, can the app adjust the bandwidth profile to match? Something like this pseudo-code:
```javascript
room.setBandwidthProfileVideoMode('grid')
```
My application allows a user to change from tiled to dominant speaker view and it would be very helpful to adjust the bandwidth profile to match their current view.

Is the recommendation that we just choose grid if the end-user layout is not known ahead of time and instead adjust track priority based on the view type?

Thanks,
Georges

**Comment by anna-vasilko** [comment]
@multiplegeorges Thanks for writing in, these are great questions.
So far there is no way to change the bandwidth profile after connecting to the room. But, it is on our roadmap! I will check with the Product team on either we can promise any timeline on this.

As for the initial mode, it's recommended to choose the one which fits your business use case the most. Find a framework for choosing it here - https://www.twilio.com/docs/video/tutorials/developing-high-quality-video-applications#network-bandwidth-profile

**Comment by genevpd** [comment]
We have the same need. In our app users change the layout that while they are in the room and the space allocated for all the videos can be either the entire screen or 1/5 of the screen.

**Comment by makarandp0** [comment]
I am closing this issue as 2.14.0 release should address your use case. Please open a new issue if you have any questions regarding the `Client Track Switch Off Control` and `Video Content Preferences`.
