### ISSUE TITLE
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'participants' of undefined

### ISSUE THREAD

**Issue by surya-vamsi2310** [twilio/twilio-video.js#989]
- [ ] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [ ] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ ] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [ ] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

```js
// TODO
```

**Expected behavior:**

TODO

**Actual behavior:**

TODO

**Software versions:**

 - [ ] Browser(s):
 - [ ] Operating System:
 - [ ] twilio-video.js:
 - [ ] Third-party libraries (e.g., Angular, React, etc.):

**Comment by anna-vasilko** [comment]
Hi @surya-vamsi2310 
This ticket is missing any details other than the title, which makes it quite impossible to work on it. 
Can you please check if the error is reproducible with the [quickstart app](https://github.com/twilio/video-quickstart-js/tree/master) and make sure it's not a problem in your code. If you are certain it's an SDK issue, please open a ticket following the template, provide your code snippet, room sid, environment details etc.
