### ISSUE TITLE
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'participants' of undefined

### ISSUE THREAD

**Issue by surya-vamsi2310** [twilio/twilio-video.js#990]
Hello im building a nodejs and angular application when i integrate twilio to application i get 
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'participants' of undefined

**Comment by anna-vasilko** [comment]
Hi @surya-vamsi2310 
This ticket does not follow our issue template, which makes it quite impossible to work on it. 
Can you please check if the error is reproducible with the [quickstart app](https://github.com/twilio/video-quickstart-js/tree/master) and make sure it's not a problem in your code. If you are certain it's an SDK issue, please open a ticket following the template, provide your code snippet, room sid, environment details etc.
