### ISSUE TITLE
Audio output devices not switching correctly

### ISSUE THREAD

**Issue by bjdelro** [twilio/twilio-video.js#998]
**Describe the bug**
Audio output devices not switching correctly

**To Reproduce**
1. Connect wired headphones
2. Join Room with another participant
3. Hear other participant on headphones
4. Unplug headphones
5. Hear other participant on built in speakers
6. Plug in headphones
7. Notice participant output comes from speakers not headphones

**Expected behavior**
if headphones are plugged in participant audio plays in headphones otherwise should play on speakers

**Screenshots**

**Environment (please complete the following information):**
 - OS: Mac OSX 10.15.3
 - Browser: Chrome 81
 - App Version: 0.1.0
 - SDK Version: 2.3.0
 - Node.js version: 10.17.0

**Comment by manjeshbhargav** [comment]
Hi @bjdelro ,

Thanks for reporting this issue. I have two questions:

1. When you plug in your headphones a second time, does the default speaker in System Preferences change back to your headphones?

2. When you plug in your headphones a second time, what is the default audio output device as shown by `navigator.mediaDevices.enumerateDevices()`?

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by bjdelro** [comment]
@manjeshbhargav thanks for the quick response! 
1. yes
2. it has the headphones as the default

I also attempted to set sink id manually with no luck. I also posted this issue in your demo app repo and it was closed linking to this chromium issue

https://bugs.chromium.org/p/chromium/issues/detail?id=1069504&q=headphones&can=2

**Comment by manjeshbhargav** [comment]
Hi @bjdelro ,

In that case, I don't see anything actionable on the part of the SDK regarding this, since it is a bug in Chrome. We can monitor this issue and let you know if Chrome updates its status. You might have to warn the customer in your application about this issue if you detect that you are running on Chrome.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by Awais-cb** [comment]
Hi @bjdelro did you find any solution to this problem? i am facing same issue
